### ISSUE TITLE
UI basics [Bottom Section]

### ISSUE THREAD

**Issue by unitystation** [unitystation/unitystation#1]
- [x] Tie all onClick events to methods in ControlUI.cs
- [x] Add selector highlight feature to left and right hand buttons (to indicate which hand is active)
- [x] Finish intent button (cycling through Help, Disarm, Hold, Attack sprites) 
- [x] Finish (resist, drop, throw) selector
- [x] Finish Walk / Run selector

**Comment by unitystation** [comment]
UI ref:

![uiscreenshot](https://cloud.githubusercontent.com/assets/23096507/19833648/b35a4990-9e8c-11e6-85da-3591c9622e41.png)

**Comment by daalta** [comment]
How far we've come...
