### ISSUE TITLE
Pushing objects breaks after a while

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1000]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
latest develop

# Report
## Current Behavior
pushing objects randomly breaks after several pushes in a row (you just walk through the object afterwards);
![pushbroken](https://user-images.githubusercontent.com/10403536/37615997-a2f9463e-2bbf-11e8-83f0-5ca9dcf59136.gif)

## Expected/Wanted/Requested Behavior
Want that fixed

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Push something around until it breaks

## OS used:
Windows

## Network
Reproduces well even on editor self-host, but could break faster for clients with ping

**Comment by Inorien** [comment]
This happens when there's something on the tile you're pushing the locker/crate over, like a camera/light/airlock/any dropped item
I suspect the pushed object is somehow getting under such obstacles

**Comment by krille90** [comment]
I think, this was fixed some time ago or would either be fixed with #1145
