### ISSUE TITLE
Pulling containers doesn't work B: 35

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1001]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop after a80a0a1357fe44b61597f657a79072e1eb3a069c (regression in that commit) of PR #968 

# Report
## Current Behaviour
Ctrl+clicking containers like closets just doesn't do anything.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Come by a closet
2.Ctrl+click it while standing next to it
3.Walk away, it won't follow

## OS used:
Windows

## Network
Editor self-host

**Comment by DooblyNoobly** [comment]
Criteria: 

 - Fix the bug above

A bounty of 35 usd will be paid to the contributor on a successful merge

**Comment by StrawberryMoses** [comment]
I'm working on this. Push / Pull seems kind of broken in general right now as well.

**Comment by StrawberryMoses** [comment]
Confirmed working in f394325, broken by #968 . Looks like OnMouseDown isn't being called anymore in PushPull for those objects

**Comment by fomalsd** [comment]
Push code has been commented out in #1084 PR as it's not adapted to work across matrices and is hacky in general

**Comment by dapocalypse** [comment]
If I cannot recreate can I provide proof and claim the bounty?

**Comment by dapocalypse** [comment]
Nvmd

**Comment by krille90** [comment]
FYI: If an issue can't be reproduced and doesn't occur anymore, the issue will be closed. In this case, no bounty will be paid.

**Comment by DooblyNoobly** [comment]
yeah closing this. The problem is because push pull is dead. We need to fix it now that player move has all be sorted out. Will make another TODO
