### ISSUE TITLE
whispering doesn't italicize text

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#10026]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

whispering doesn't italicize the text 

### What should have happened instead?

the text when whisper should be made italic to differentiate it

### Steps to reproduce the issue

1. whisper

**Comment by MaxIsJoe** [comment]
Not a bug, missing feature.

**Comment by eurtod** [comment]
well it used too be in the game and was removed a long time ago
