### ISSUE TITLE
[BUG] [MacOS] Issue on login

### ISSUE THREAD

**Issue by KeroroLulu** [unitystation/unitystation#10079]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23.29.26.19

### I was

Server

### OS

Mac

### What happened?

**OS:** macOS 13.1 22C65 arm64
**Host:** MacBookPro18,1
**Kernel**: 22.2.0
**CPU**: Apple M1 Pro
**GPU**: Apple M1 Pro
**Memory**: 2791MiB / 16384MiB

After dowloading the last version and execution of this one in local for testing I can't connect to this. See the screenshot
<img width="1727" alt="Capture d’écran 2023-09-30 à 16 17 47" src="https://github.com/unitystation/unitystation/assets/36198604/e2840913-baae-49aa-a6c3-ad37aebd5d63">

### What should have happened instead?

I should be connected to the game.

### Steps to reproduce the issue

Launch the last version of the UnityStation.

**Comment by KeroroLulu** [comment]
The same bug happens when I try to start from **UnityStation - Playtest EU**

**Comment by MaxIsJoe** [comment]
We're going to be fixing this very soon with our next update to stationhub.

**Comment by MaxIsJoe** [comment]
This needs to be tested again after removing firebase.

**Comment by MaxIsJoe** [comment]
I'm going to assume this was fixed because we have no Mac testers and realistically the firebase problems have all been gone by now since we removed their DLLs
