### ISSUE TITLE
[BUG] Public Terminal not send :computer: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10098]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.09.26.19

### I was
Server (local hosted)

### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?
At HoP , SquareStation

Hello, I've noticed that:
- The public terminal, even once unlocked, cannot be used to send a message.
- It always displays "0V".
- public Brig terminals are noted as "civilian"
- clock 
- ![Capture d’écran du 2023-10-08 19-11-51](https://github.com/unitystation/unitystation/assets/23202421/8397de12-21e6-47af-85b5-9cc41f86672d). 

### What should have happened instead?
send a message and hear a beep 

### Steps to reproduce the issue
- go near a public terminal, 
- unlock it with your ID
- write to
- send

**Comment by AtnerNT** [comment]
On this issue, it was introduced when Max added the AI radio and added said functionality to the public terminals, seemed to break the old request function.
@MaxIsJoe will have to confirm this, but I remember hearing about plans to replace public terminals/redo them completely? She will have to supply the info on this.

**Comment by MaxIsJoe** [comment]
> On this issue, it was introduced when Max added the AI radio and added said functionality to the public terminals, seemed to break the old request function. @MaxIsJoe will have to confirm this, but I remember hearing about plans to replace public terminals/redo them completely? She will have to supply the info on this.

Honestly, at this point I think it would be better if we removed public terminals because they're not as feature ready and will take away the focus away from developing a proper modular system for PDAs/Laptops/Tablets, which we need for the signals gameplay.

They weren't supposed to be integrated into other aspects of things like the AI, and people seemed to still ignore them like in SS13.

Whatever bug that needs to be fixed in terminals can be ignored, just remove them and hack the AI radio into the AI core.

**Comment by Fr-Dae** [comment]
it's sad, it was practical to be able to send a message to a service rather than going to the office and dropping off a piece of paper.

**Comment by MaxIsJoe** [comment]
> it's sad, it was practical to be able to send a message to a service rather than going to the office and dropping off a piece of paper.

I love the public terminal as well, but it's unfortunately not a thing that most ss13 players seem to pay a lot of attention to even with the small changes we made to try and draw people's attention to it a bit more.
Having a general tool that anyone can use for communication is always good, but as it stands right now; public terminals aren't widely adopted and I see no point in continuing work on them when my focus can be diverted into improving PDAs instead.

**Comment by Fr-Dae** [comment]
> > it's sad, it was practical to be able to send a message to a service rather than going to the office and dropping off a piece of paper.
> 
> I love the public terminal as well, but it's unfortunately not a thing that most ss13 players seem to pay a lot of attention to even with the small changes we made to try and draw people's attention to it a bit more. Having a general tool that anyone can use for communication is always good, but as it stands right now; public terminals aren't widely adopted and I see no point in continuing work on them when my focus can be diverted into improving PDAs instead.

but ... fuck the players of ss13. we don't have to answer to them, and even less need to call their bluff.

**if fix terminals are not a priority, ok. I hear it** 
but if it's just because they've been let down by ss13 players, that's a bogus argument. 
we have no obligation to be a carbon copy of ss13.

**Comment by MaxIsJoe** [comment]
Agreed. Unitystation is a remake, not a remaster.
But as of right now, public terminals are a hog to maintain and take away our very limited man power to work on more useful stuff.

When the entirety of the signals gameplay loop is implemented and PDAs are feature complete, we can then start reimplementing public terminals.

**Comment by MaxIsJoe** [comment]
public terminals are removed as of #10157
