### ISSUE TITLE
admin grab no sound

### ISSUE THREAD

**Issue by mortifia** [unitystation/unitystation#10097]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.09.26.19

### I was
Server (local hosted)

### OS
Linux, win

### What happened?
when admin/host grab there is no sound

but when a player grab there is a sound

SO :
- either there must be no sound when a player grabs
- either the admin / the host must also have the sound that plays when he performs the grab action

### Steps to reproduce the issue
grab as admin

**Comment by MaxIsJoe** [comment]
what?

**Comment by Fr-Dae** [comment]
if the player is the admin who hosts the game

and he grabs someone or something
there's no sound effect, but it's clearly heard by the other players 

in addition, the admin player can hear the other players performing the action.
it's only him

**Comment by Fr-Dae** [comment]
Of course, if you tested the bugs before criticizing them, you'd understand the problem better. 

it's hard to explain something based on sound alone, in a text conversation

**Comment by mortifia** [comment]
first comment updated

**Comment by MaxIsJoe** [comment]
Unable to replicate this issue

**Comment by mortifia** [comment]
> Unable to replicate this issue

you have try to reproduce this bug in dedicated server ?
