### ISSUE TITLE
[BUG] Admin - Add Ghost Roles Menu :heavy_plus_sign: :ghost: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10102]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.09.26.19

### I was
Server (local hosted)

### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?
As admin,
Player manager menu => Ghost roles

There are several problems with this interface, but first, thanks for adding it.

- [ ] The search bar on the player interface doesn't work.
- [ ] The -1 value (no timer) doesn't always work.
- [ ] The "X" (delete) button doesn't work.
- [ ] Scrolling is really REALLY slow (with mousewheel)
- [ ] Images too big for window size
- [ ] The "S" is not intuitive, could you replace it with a gear ? :gear: 
- [ ] It would be nice to have a more detailed description of the different aliens, their powers and their uses. 
 
 ![image (1)](https://user-images.githubusercontent.com/46533559/272609506-36bc7f46-a503-47cd-80bf-8202aef950de.png)

**Comment by corp-0** [comment]
are you talking about the features from #10046 ?

**Comment by Fr-Dae** [comment]
> are you talking about the features from #10046 ?

Excalty, nd again thanks you for have add it

**Comment by MaxIsJoe** [comment]
This is an issue on an external branch that is still heavily in development and these features do not exist on upstream/develop
https://github.com/SerheyKr/unitystation/tree/Improved-Antagonist-Managing-tools-for-Admins

Reopen this issue if the issues persist even after the PR is merged.

**Comment by Fr-Dae** [comment]
it's not an external branch, it's the version offered in the HUB station, publicly accessible to everyone.
