### ISSUE TITLE
[BUG] Security console - back to old time ? :clock10: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10107]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game  Version
- 100461 - 23.10.07.15
- 21.11.03.00
### I was
Server (local Host)
HOS
### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

some time ago (~2021) 
The security console worked like this.

- You insert your ID
- Click on the console
- Click on "login
- You go to a pasager's file.
- Set the status to criminal
- In "crime" you add the code of the broken law
- validate

and in an even earlier version, there was an illustration of the character from the front with his basic uniform (as seen in the spawn). 

It would be fantastic to restore some of this old code, which worked perfectly.

and if possible, once the form has been edited, print out a paper report immediately.
and have a "print wanted notice" button in the console's main menu 

ps: is it normal that I have the impression that version 21.11.03.00 is twice as fluid / smouth as the current version?
or does the character move slower now? 

![Capture d’écran du 2023-10-09 07-42-31](https://github.com/unitystation/unitystation/assets/23202421/6ac23fad-9c08-4caf-ad90-4c68d04fb1b4)

**Comment by MaxIsJoe** [comment]
duplicate of #9004
please refrain from posting issues unless you're 100% sure they have not been posted in the issue tracker before.

**Comment by Fr-Dae** [comment]
it's my fault that each version is more buggy than the last and that there are fewer and fewer features that work now that worked before?
