### ISSUE TITLE
[Feature] Add roles / Faction :mouse: :spider: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10103]
**Two** additional factions could be added. *escaped from the neglectful science department.*

- The **skaven** faction **SQUEARK !**
(composed of RegalRatMob, mouse brown, mouse, white, mouse grey)

(the mouses would be fast scouts)

- The **Lolth** faction 
(composed of GiantSpider, GiantSpiderBroodMother, GiantSpiderHunter, GiantSpiderNurse, GiantSpiderViper, SpiderEges )

**Attention** /!\  
note that these roles are **__not__** intended to destroy the station.
The station is their **nest**, and they intend to defend it against any threat.
A **cohabitation** is entirely conceivable.  ... If you like scratchy in vent and web-covered walls....

At least you won't have to worry about waste disposal, corpses, and can serve as a front line against the nukies.  **It's their home too.**

![Capture d’écran du 2023-10-09 05-45-59](https://github.com/unitystation/unitystation/assets/23202421/54d24949-f341-4afd-95d6-e52a493da15d)

*no web found*

![Capture d’écran du 2023-10-09 05-50-44](https://github.com/unitystation/unitystation/assets/23202421/a64a6d61-f1b3-4601-80a9-101326b3df8b)

**Comment by MaxIsJoe** [comment]
I keep revisiting this issue every couple of weeks and I still struggle to understand what this issue wants
factions are not a thing in game because character attributes have been on hold for an indefinite amount of time until the steam release.

spiders and mice already spawn in maints by default randomly via events, so the only unique thing about this proposal is adding RegalRatMob to the mice spawn pool.

I'm closing this because it seems unnecessary

**Comment by Fr-Dae** [comment]
- to be **able to play**, in you character, the faction of the mouse, or spider. 

the principle of faction already exists, 
- there is the protagonist (centocom) 
- the Crew 
- the badguys syndicate, 
- the xenos 
- plus the faction "other" such as the blob.

Since these are different factions, a syndicate agent has no reason to help a blob or a xeno, everyone does their own thing and lives their own life.

Here it's the same, except that the aim of this faction isn't to destroy the station, but just to live there, with or against the crew.

**Comment by MaxIsJoe** [comment]
That will be dealt with in time when we move over old mobs to MobV2
