### ISSUE TITLE
[BUG] Bad guys unic faction ?

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10106]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game  Version
100461 - 23.10.07.15

### I was
Server (local Host)

### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

the most rescente should be in 1st position and have a descending order whatever their nature, the mob are all allied.

which doesn't make sense.
spider, rat, xeno, blob, clown, space-shark
all have a different goal, so it would be logical for them to defend their own territory and kill each other off,

This would create more life in the maintenance corridors.

**Comment by MaxIsJoe** [comment]
This is not a bug.
