### ISSUE TITLE
[BUG] Order on Hub and version 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10105]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### ~~Game~~ HUB Version
933

### I was
User

### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?
I've spotted several bugs in the **Station Hub.**

- it's not possible to organize builds (and it's not done by default) the most recent should be in 1st position and have a descending order 
- the list is limited to a certain number for no reason
- manually add a folder in ~/.local/share/StationHub/Installations/UnitystationDevelop/23100715/
even if you follow the folder naming norms **exactly**, the build is not added to the list (you have to run it manually from locale) 

![Capture d’écran du 2023-10-09 06-57-00](https://github.com/unitystation/unitystation/assets/23202421/1331ca52-55e1-4fe9-9edc-f144182890b6)
![Capture d’écran du 2023-10-09 06-57-19](https://github.com/unitystation/unitystation/assets/23202421/79c89b7f-3682-4163-bb58-1ac0e5450a1a)

**Comment by MaxIsJoe** [comment]
Post this issue on the [stationhub repo](https://github.com/unitystation/stationhub)

**Comment by Fr-Dae** [comment]
you know you have a button on the right to transfer issues from one repo to another? rather than closing an issue that is NOT resolved?

**Comment by MaxIsJoe** [comment]
![image](https://github.com/unitystation/unitystation/assets/34368774/2d3228b5-7484-4ad1-a5c2-304866cd0504)

no

**Comment by Fr-Dae** [comment]
@corp-0 @Bod9001 could you transfert and re-open this issue please ?
