### ISSUE TITLE
HUD Clothe are not logical :womans_clothes: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10114]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game  Version
- 100461 - 23.10.07.15

### I was
Server (local Host)
HOP
On Ministation 
### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

here's a suggestion for improving the clothes interface, which is currently a huge mess 

![Capture d’écran du 2023-10-09 09-04-21](https://github.com/unitystation/unitystation/assets/23202421/f00a518b-a53a-4b26-9724-3811ac2accc7)

**Comment by MaxIsJoe** [comment]
This is not a bug
