### ISSUE TITLE
Accessing Matrix causes a lot of garbage

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1011]
# Preliminary information

## Category
Bug

## Bug: Release or Development?
Dev

# Report
## Current Behavior
Accessing Matrix causes a lot of garbage

## Expected/Wanted/Requested Behavior
Accessing Matrix causes no garbage

**Comment by fomalsd** [comment]
![default](https://user-images.githubusercontent.com/10403536/38757327-4c546510-3f75-11e8-8d04-40ff90f4548a.png)
