### ISSUE TITLE
[FEATURES] PDA - Add a map button

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10123]
### There is no other issue reporting the same problem.
- [ ] I have searched the existing issues

### What happened?

It would be great to have a button on the PDA to display a window that would load an image of the station.
don't forget the + - and x buttons 

i know bod has a script to generate 4k maps from unity 
@Bod9001 

@AtnerNT 

![Capture d’écran du 2023-10-10 10-06-21](https://github.com/unitystation/unitystation/assets/23202421/b47a0cb8-243d-4b78-9757-481f84f45347)

**Comment by eurtod** [comment]
hm it wouldn't make sense if it was accessed from pda and then popped out like that. could do it like ss14 where there are maps hung up on the wall.

**Comment by Fr-Dae** [comment]
> hm it wouldn't make sense if it was accessed from pda and then popped out like that. could do it like ss14 where there are maps hung up on the wall.

1 - fuck SS14
2 - the idea is to give the PDA, which is clearly underused, a little more usefulness.
3 - it doesn't prevent you from having an object on the wall that displays this same window.

**Comment by eurtod** [comment]
yeah, but the main thing is that it doesn't make sense to have another screen pop out of the pda screen. also, i think the pda screen is too small and limited in colours to properly display a map.

**Comment by Fr-Dae** [comment]
it's just a jpg, don't be jaded

moreover, my image is just an illustration, I have no idea how atner will implement this.

**Comment by NoooneyDude** [comment]
Closely related to #7397.

**Comment by MaxIsJoe** [comment]
#7397 already exists, so closing this.
