### ISSUE TITLE
[Balance] EVENTS - scrubbers overflow

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10124]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues
### Game  Version
- 100461 - 23.10.07.15

### I was
Server (local Host)
HOP
On Ministation 
### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

The event that causes the scrubbers to spew filth all over the station happens far, far too often.

**Comment by MaxIsJoe** [comment]
After some discussion on discord, this issue is no longer a problem due to the current filth gen balance is handled.
