### ISSUE TITLE
[Feature] - Remove the grab intent button

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#10120]
We've had many arguments over how we can implement a grab mechanic in unitystation and many of us are always divided on how it should operate (cqc vs classic, making pulling objects relegated to grab intent only, etc). It is also starting to become annoying to see people constantly refer to a button that has no function as a "bug".

It is also more annoying when a lot of people complain about how the grab function serves no purpose, but never offer any solution or ideas on how we can make the intent meaningful.

We'd save ourselves a lot of headaches by simply removing that button all together and reducing the intents to Help, Disarm and Harm; as these are the main interactions that all our gameplay is revolved around.

Also Bod, don't worry, we can keep the default intent design so that it matches 2017 /tg/'s intent button style still; but just make buttons more wide with text.
That way you can keep the aesthetics you like while improving UX in the long run.

**Comment by Bod9001** [comment]
reeeeeeee I'll implement it now

**Comment by Fr-Dae** [comment]
pulling, dragging, towing, are all important actions in unitystation, and once again you can interpret them as you see fit.

I never said anything about suppressing or making a choice.

but to have the yellow button function IN ADDITION to the "Ctrl click" keyboard shortcut. 

why would you want to delete something as cool as "grab and go" (retorical question)?

**Comment by Bod9001** [comment]
there we go added

**Comment by Fr-Dae** [comment]
> there we go added

are you really going to restrict a character's ability to pull an object behind him? 
when that's clearly the strength of the game?

**Comment by eurtod** [comment]
what if replace it with emote button or something?

**Comment by Fr-Dae** [comment]
like this https://github.com/unitystation/unitystation/issues/10109 ?
