### ISSUE TITLE
[BUG] medical console "bip" spam

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10132]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.10.11.00

### I was
Server Local Host
HOS
SquareStation

### OS
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

Hi, I've found a big, dirty bug.
I was on a localhost session to test some uniforms.
- I spawned a lot of characters with the F7 key
- I deleted the two terminal medical (because of too much noise )

beeping can be heard throughout the station
without attenuation, and continuously
I did spawn a few characters with the F7 key  
![Capture d’écran du 2023-10-13 08-34-16](https://github.com/unitystation/unitystation/assets/23202421/3547864a-0b47-432a-8f6e-ea751699e427)

**Comment by MaxIsJoe** [comment]
Reminder 
![image](https://github.com/unitystation/unitystation/assets/34368774/e45d28c7-5729-40e3-b8aa-66cd361e5a17)
