### ISSUE TITLE
[BUG] Shift buble spaming

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10131]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.10.11.00

### I was
Server Local Host
HOS
SquareStation

### OS
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

Hi, I've found a big, dirty bug.
I was on a localhost session to test some uniforms.
- I spawned a lot of characters with the F7 key
- I use shift on a character
nothing appears.

I press shift several times, and this happens 

![Uploading Capture d’écran du 2023-10-13 07-44-00.png…]()

**Comment by Bod9001** [comment]
fixed
