### ISSUE TITLE
[BUG] Admin tools - Deleting a character does not delete the entity or the rest.  

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10130]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.10.11.00

### I was
Server Local Host
HOS
SquareStation

### OS
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

Hi, I've found a big, dirty bug.
I was on a localhost session to test some uniforms.
- I spawned a lot of characters with the F7 key
- I deleted the duplicate characters

but they are not "really" deleted
a large number of ghosts remain.
and when I pull a character to move him.
I'm sometimes blocked by an invisible wall, as if someone was blocking my path, someone invisible. 
![Capture d’écran du 2023-10-13 08-09-57](https://github.com/unitystation/unitystation/assets/23202421/790119de-2e69-4159-9228-7a82b2f33678)

**Comment by MaxIsJoe** [comment]
This is not a bug. Ghosts are meant to continue existing even after their bodies are removed.

**Comment by Fr-Dae** [comment]
a ghost shouldn't block a human's path , no ?
