### ISSUE TITLE
[BUG]  Suit sensors aren't synced properly

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#10133]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23101306

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

![image](https://github.com/unitystation/unitystation/assets/34368774/c0db5b70-7c28-40b6-a29d-6b1c07c7bb6b)

- Suit sensors no longer report your name within the medical records console
- It will also fail to sync the correct mode of the suit sensor

### What should have happened instead?

Report the name and the correct info

### Steps to reproduce the issue

1. Go to a medical records console
2. Change your suit sensors mode
3. profit

**Comment by Fr-Dae** [comment]
![Capture d’écran du 2023-10-13 14-50-53](https://github.com/unitystation/unitystation/assets/23202421/b4822dde-07e2-4813-bed1-6f8b9963f14b)

- [ ] The "power" button does not close the window
- [ ] You can't scroll down
- [ ] No name / job
- [ ] information coming out of the frame
