### ISSUE TITLE
Tomlyn error when opening the Unity project for the first time

### ISSUE THREAD

**Issue by akshaybharwani** [unitystation/unitystation#10147]
Followed all the steps mentioned here: https://unitystation.github.io/unitystation/contribution-guides/Starting-contribution/
Opening the project in Unity results in it asking to be opened in Safe mode because of errors.

```
Assets\Scripts\Systems\Permissions\PermissionsConfig.cs(2,7): error CS0246: The type or namespace name 'Tomlyn' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Systems\Permissions\PermissionsManager.cs(5,7): error CS0246: The type or namespace name 'Tomlyn' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Systems\Permissions\PermissionsConfig.cs(9,34): error CS0246: The type or namespace name 'ITomlMetadataProvider' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Systems\Permissions\PermissionsConfig.cs(12,10): error CS0246: The type or namespace name 'TomlPropertiesMetadata' could not be found (are you missing a using directive or an assembly reference?)
```

I tried installing Tomlyn package as shown here, but got this error
`Found more than one project in ~\unitystation\UnityProject\. Specify which one to use.`

**Comment by MaxIsJoe** [comment]
have you tried restoring your nuget packages?

Nuget -> Restore/sync packages

**Comment by akshaybharwani** [comment]
I'm using Rider. Restorting Nugest packages doesn't have any effect on it.
Log:

> Restoring packages in solution UnityProject started
> RestorePackagesConfig: Start
> There are no packages in solution
> RestorePackagesConfig: Finish
> Restore result: <Empty>
> Restoring packages in solution UnityProject finished (0.004 sec)

**Comment by akshaybharwani** [comment]
So I think It's resolved. 

I'll just write down my experience with this for anyone coming here in the future.
1. Unity might ask you to open the Game in Safe mode for some errors. And if you see the errors are just Tomlyn ones, open the project anyway.
2. Now, in case of Rider, open Nuget Window, search for Tomlyn, and install it. 
3. This would add a whole lot of new package files which we don't need, so discard everything.
And now there would be no errors.

**Comment by MaxIsJoe** [comment]
You could just open the project directly without going into safe mode, and Unity will handle the nuget packages for you.

**Comment by akshaybharwani** [comment]
Didn't know the errors were for Nuget packages before opening into Safe Mode. And in my case, Unity didn't handle the nuget packages.

**Comment by MaxIsJoe** [comment]
Unity doesn't handle nuget packages natively. We have our own plugin that does that.
