### ISSUE TITLE
[Feature] The docs should probably have an FAQ section

### ISSUE THREAD

**Issue by AlbertSnows** [unitystation/unitystation#10151]
### There is no other issue with the same feature request.

- [X] I have searched the existing issues

### Why is this feature needed/good for the game?

For someone taking a look at the project for the first time, we probably want to minimize the hurdles to get a running instance up. An FAQ doesn't solve this, but it does act as a bandaid in that it allows people to quickly and easily refer to troubleshooting mechanisms to help debug their local repo. 

As an motivating example for this change, refer to this issue: https://github.com/unitystation/unitystation/issues/10147

### User Story

```markdown
- As a developer, I want a means to access and contribute to documentation to troubleshoot issues that may commonly crop up
```

### Describe alternatives you've considered.

There isn't really an alternative aside from not adding the documentation. You could also organize it in a different structure.

**Comment by AlbertSnows** [comment]
I'll try to get a PR open for this.

**Comment by corp-0** [comment]
uhm, what Question do you think should be in that FAQ?

**Comment by AlbertSnows** [comment]
> uhm, what Question do you think should be in that FAQ?

#10147 is a good example, as mentioned in the initial post.
