### ISSUE TITLE
build 23110418 crashes after loading.

### ISSUE THREAD

**Issue by sanek31** [unitystation/unitystation#10167]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23110418

### I was

Client

### OS

Linux

### What happened?

OC:kubuntu 23.04 , updated to kubuntu 23.10 (stills same error)
RAM:16 gb
Proccesor: AMD Radeon 5000 series

When I run this build, after the end of loading the game just crashes with an **error Segmentation fault (core dumped)**.
Older build 4124 starts normally, but when trying to go to the server ipi is reset to local and automatically ticked on host, if you go to the host, when you start the game map will not load (just a view of space with the possibility of zoom)

### What should have happened instead?

Build had to start without error, and also for the map to load so I could play.

### Steps to reproduce the issue

1-try use same OC
If everything is working fine then most likely the problem is amd

**Comment by corp-0** [comment]
do you have any relevant information on your logs?

**Comment by Fr-Dae** [comment]
you can find log on this folder

* **ingame** log, like "f5" menu `~/.config/unity3d/Unitystation/Unitystation/Player.log`
* **StationHub log** `~/.local/share/StationHub/Logs/`

**Comment by sanek31** [comment]
> do you have any relevant information on your logs?
```
- Finished resetting the current domain, in  0.002 seconds
Script error (ProtipObjectOnPickupTrait): OnEnable() can not be a coroutine.
Default vsync count 1
requesting resize 1920 x 1008
resizing window to 1920 x 1008
Desktop is 1920 x 1080 @ 60 Hz
UnloadTime: 1.556235 ms
The referenced script (UpdateTextures) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'BasieCube') is missing!
A scripted object (probably UpdateTextures?) has a different serialization layout when loading. (Read 32 bytes but expected 200 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
Shader 'Light2D/Light 20 Points': fallback shader 'Light2D/Light 1 Point' not found
ScriptableObjects.Atmospherics.GasesSingleton SO took 25 ms to find! Try to serialize a reference to this SO singleton instead!
UnloadTime: 7.425257 ms
CommonSounds SO took 48 ms to find! Try to serialize a reference to this SO singleton instead!
ScriptableObjects.ChemistryReagentsSO SO took 464 ms to find! Try to serialize a reference to this SO singleton instead!
[FaithManager/Awake] - Setting stuff.
Build Version is: 23110418. 
[LobbyManager/TryAutoLogin()] - FirebaseAuth.DefaultInstance.CurrentUser is null. Attempting to send user to first time panel.
KeyNotFoundException: The given key 'first_female' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <fce9c7c21a6948a086653c401626f3cf>:0 
  at StringManager.GetRandomHumanoidName (Gender gender) [0x00042] in <419403394c784ab89ca656d41b9ee29a>:0 
  at StringManager.GetRandomName (Gender gender, System.String species) [0x0004e] in <419403394c784ab89ca656d41b9ee29a>:0 
  at Systems.Character.CharacterSheet.GenerateRandomCharacter (System.Collections.Generic.List`1[T] speciesToChooseFrom) [0x0008a] in <419403394c784ab89ca656d41b9ee29a>:0 
  at Systems.Character.CharacterManager.DetermineActiveCharacter () [0x0000e] in <419403394c784ab89ca656d41b9ee29a>:0 
  at Systems.Character.CharacterManager.Init () [0x00006] in <419403394c784ab89ca656d41b9ee29a>:0 
  at PlayerManager.Start () [0x00005] in <419403394c784ab89ca656d41b9ee29a>:0 

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Invalid Hub creds found, aborting HUB connection
Unloading 62 unused Assets to reduce memory usage. Loaded Objects now: 408142.
Total: 355.910127 ms (FindLiveObjects: 25.037101 ms CreateObjectMapping: 38.353942 ms MarkObjects: 289.169518 ms  DeleteObjects: 3.348544 ms)

Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 408142.
Total: 368.539686 ms (FindLiveObjects: 19.058103 ms CreateObjectMapping: 39.092721 ms MarkObjects: 307.731908 ms  DeleteObjects: 2.655571 ms)

System.Exception: Invalid path in TextDataProvider : '/home/nickname/.local/share/StationHub/Installations/UnityStationDevelop/23110418/Unitystation_Data/StreamingAssets/aa/settings.json'.
RuntimeData is null.  Please ensure you have built the correct Player Content.
Addressables - Unable to load runtime data at location UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1[[UnityEngine.AddressableAssets.Initialization.ResourceManagerRuntimeData, Unity.Addressables, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].
OperationException : Addressables - Unable to load runtime data at location UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1[[UnityEngine.AddressableAssets.Initialization.ResourceManagerRuntimeData, Unity.Addressables, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].
Caught fatal signal - signo:11 code:1 errno:0 addr:0x7f9c18563a98
Obtained 30 stack frames.
#0  0x007f9dc3842910 in __sigaction
#1  0x007f9d8c4716f3 in GC_mark_from
#2  0x007f9d8c46c6c5 in GC_mark_some
#3  0x007f9d8c46c3f4 in GC_collect_a_little_inner
#4  0x007f9d8c46debf in GC_allocobj
#5  0x007f9d8c468271 in GC_generic_malloc_inner
#6  0x007f9d8c46e7ed in GC_generic_malloc
#7  0x007f9d8c4727a1 in GC_malloc_kind_global
#8  0x007f9d8c43cf54 in mono_gc_register_root
#9  0x007f9d8c3e7b0d in mono_array_new
#10 0x007f9d8c3e7c13 in mono_array_new_specific
#11 0x007f9d8c2462f6 in mono_get_runtime_build_info
#12 0x007f9d8c3e3260 in mono_runtime_invoke
#13 0x007f9d8c404743 in mono_thread_has_sufficient_execution_stack
#14 0x007f9d8c364aae in burst_mono_simulate_burst_debug_domain_reload
#15 0x007f9d8c4022cf in mono_thread_has_sufficient_execution_stack
#16 0x007f9d8c402191 in mono_thread_has_sufficient_execution_stack
#17 0x007f9d8c47b3f8 in GC_inner_start_routine
#18 0x007f9d8c47b08b in GC_start_routine
#19 0x007f9dc3897ada in pthread_condattr_setpshared
#20 0x007f9dc392847c in clone
```

**Comment by sanek31** [comment]
Fixed
1-downloaded this https://unitystationfile.b-cdn.net/UnityStationDevelop/StandaloneLinux64/23110418.zip
2-extracted it to .local/share/stationhub folder
and after that i'm can join to build.

**Comment by sanek31** [comment]
oh problem, its works only first run after file replace.

**Comment by MaxIsJoe** [comment]
> If everything is working fine then most likely the problem is amd

This is not AMD's fault, this is unity's fault.
Issues related to addressables on Linux are largely ignored by them and they stated multiple times that they won't fix this issue as well as several other critical issues on their bug tracker.
https://issuetracker.unity3d.com/issues/addressables-runtimedata-is-null-error-in-build-is-thrown-when-assetrefference-dot-loadassetasync-is-called-in-an-async-method-1

There are only three workarounds:

- If you're on a debian based distro, run the game from the unity editor.
- If you're on an arch based distro, clear out all your /user/ files related to unity and unitystation before launching the game.
- Use Proton to run the game via the windows executable.

Hopefully this issue will be fixed when CoreCLR rolls out, but for now we'll have to deal with unity's laziness.

@sanek31 hope this helps.

**Comment by CorruptComputer** [comment]
> * Use Proton to run the game via the windows executable.

This might be possible to add to the flatpak for stationhub, or just be automatically taken care of by Steam when the game releases there. I'm not sure exactly how to do so, but I have seen flatpaks run windows versions of applications using wine in the past, I can try to find those again and look into how thats implemented.

**Comment by MaxIsJoe** [comment]
> > * Use Proton to run the game via the windows executable.
> 
> This might be possible to add to the flatpak for stationhub, or just be automatically taken care of by Steam when the game releases there. I'm not sure exactly how to do so, but I have seen flatpaks run windows versions of applications using wine in the past, I can try to find those again and look into how thats implemented.

A bit late, but just wanted to say; make that an option for players to have rather than forcing them to run a windows application under a compatibility layer.
Wine and Proton are very solid nowadays and rarely break, but because they're still being actively developed with hundreds of changes rolling out every month; a change can happen that can break something that unity uses on some systems.

**Comment by MaxIsJoe** [comment]
closing in favor of #10250
