### ISSUE TITLE
Writing two messages without picking a job causes NRE spam on server

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1020]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
Getting spam of the following errors on server if someone writes a couple of messages without picking a job:
`NullReferenceException: Object reference not set to an instance of an object
PlayerNetworkActions.RpcToggleChatIcon (System.Boolean turnOn) (at Assets/Scripts/PlayGroups/PlayerNetworkActions.cs:516)
PlayerNetworkActions.InvokeRpcRpcToggleChatIcon (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) (at <aacbcd62ca6243bdabacd943c6d5bd51>:0)
UnityEngine.Networking.NetworkIdentity.HandleRPC (System.Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:661)
UnityEngine.Networking.ClientScene.OnRPCMessage (UnityEngine.Networking.NetworkMessage netMsg) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/ClientScene.cs:739)
UnityEngine.Networking.NetworkConnection.InvokeHandler (UnityEngine.Networking.NetworkMessage netMsg) (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkConnection.cs:231)
UnityEngine.Networking.LocalClient.ProcessInternalMessages () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/LocalClient.cs:141)
UnityEngine.Networking.LocalClient.Update () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/LocalClient.cs:69)
UnityEngine.Networking.NetworkClient.UpdateClients () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkClient.cs:965)
UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at C:/buildslave/unity/build/Extensions/Networking/Runtime/NetworkIdentity.cs:1092)
`
## Expected/Wanted/Requested Behavior
There should be no NRE spam

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start a server
2. On profession screen press T, move away profession tab to see chat window and write 2 messages
3. See NRE spam

![chatnre](https://user-images.githubusercontent.com/10403536/39082804-9aa2f5a0-4561-11e8-88c1-b073ed95f920.gif)

## OS used:
Windows

## Network
Local host on server or server+200 ping client

**Comment by Bonfire** [comment]
Did some tracing on this and it seems that the program is trying to interact with a ChatIcon object that simply does not exist. The file that is throwing the error tries to get the current ChatIcon component twice, and both times it doesn't exist (null). I checked the ChatIcon component and there was a comment stating that it needed to be worked on (TODO). My guess is that whoever worked on the ChatIcon component just didnt give a default ChatIcon to players. All-in-all, the object needs to be created somewhere along the line, as it is not currently being done.

Line throwing the error: https://github.com/unitystation/unitystation/blob/9fa227173ae0f043fd4a84b47906ab7fd346cb49/UnityProject/Assets/Scripts/PlayGroups/PlayerNetworkActions.cs#L516

ChatIcon component file: https://github.com/unitystation/unitystation/blob/9fa227173ae0f043fd4a84b47906ab7fd346cb49/UnityProject/Assets/Scripts/PlayGroups/ChatIcon.cs

**Comment by DooblyNoobly** [comment]
That might be the little chat bubble that pops up above the players head. Makes sense that it wouldn't exist if the player hasn't spawned.
