### ISSUE TITLE
[Feature/UX] Color code and organize job selection interfaces

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10204]
### There is no other issue with the same feature request.

- [X] I have searched the existing issues

### Why is this feature needed/good for the game?

the addition of colours for each department, and a grid organisation, would simplify and improve the readability, comfort and use of the job selection menu, 

don't forget the HOP console interface
console interface, which also needs some attention. 

![Job2](https://github.com/unitystation/unitystation/assets/23202421/2497f759-8135-4ad0-8f66-4d636fe4264e)

![HoP-pc8](https://github.com/unitystation/unitystation/assets/23202421/6985f5e7-290c-4f32-9900-e30783e95a45)

* [ ] Rework of Job selection menu 
* [ ] Rework of Hop Interface

**Comment by MaxIsJoe** [comment]
this is kinda repetitive now to #7878 which already exists on the steam tracker.
