### ISSUE TITLE
Implement shuttle thruster FX with Particle System B: 40

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1022]
# Preliminary information

## Category
Feature Request

# Report
## Current Behaviour
No FX of working shuttle engines whatsoever

### Code criteria:
New clientside MonoBehaviour called ShipThruster that would reside on shuttle engine GameObjects in order to control particle generator and subscribe to the following MatrixMove events:
- Start/stop sequences, 
- Left/right rotations,
- Speed change.

MatrixMove event `OnRotation(from, to)` is implemented, will need to also add `OnStart()`, `OnStop()` and `OnSpeedChange(from, to)` events.
Probably should have an editor-selectable `EnginePosition` enum field ( Left, default Center, Right ) in order to i.e. react to rotation events depending on engine position.

### FX criteria:
Should look sexy enough and have pixelated particles that would fit the style of SS13

**Comment by DooblyNoobly** [comment]
Criteria: 

 - Complete the criteria above

A bounty of 40usd will be paid to the contributor on a successful merge

**Comment by badbon** [comment]
I've started on this 2 days ago as well, should have progress to show soon.

**Comment by DooblyNoobly** [comment]
moved to inprogress
