### ISSUE TITLE
Flickering main window when maximizing on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Bonfire** [unitystation/unitystation#1037]
# Preliminary information
The main window for unitystation flickers rapidly on the right-side of the screen when I attempt to maximize the window on my Ubuntu 16.04 LTS environment.

## Category
Bug

## Bug: Release or Development?
Release (Steam Build)

# Report
## Current Behavior
Rapid flickering on the right-side of the screen/window

![screenshot from 2018-05-08 04-48-14](https://user-images.githubusercontent.com/5704760/39747788-474d646c-527c-11e8-8d9b-4d41328a767b.png)

## Expected/Wanted/Requested Behavior
No flickering whatsoever. 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start unitystation on a linux environment
2. Maximize the window

## OS used:
Linux

## System specifications
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.13.0-39-generic
Uptime: 1d 13h 48m
Packages: 2517
Shell: bash 4.3.48
Resolution: 1920x1080
DE: Unity 7.4.5
WM: Compiz
WM Theme: Arc-Darker, Arc-Darker [GTK2], Arc-Darker [GTK3]
Icon Theme: ubuntu-mono-dark
Font: Futura Bk BT 11
CPU: Intel Core i5-7200U CPU @ 3.1GHz
RAM: 4282MiB / 11892MiB
HDD

## Network
Not Connected

**Comment by fomalsd** [comment]
Quick googling showed that you should try running game in OpenGL mode. 
Try running game with `-force-opengl` flag and see if it works

**Comment by fomalsd** [comment]
Also try running in windowed mode

**Comment by Bonfire** [comment]
I have attempted to force the game to run using OpenGL mode and windowed mode, only OpenGL mode, and only windowed mode. None of the options have fixed the issue.

**Comment by fomalsd** [comment]
@Bonfire can you check if it still flickers on latest develop? It likely got fixed by #1070

**Comment by Bonfire** [comment]
When resizing the window on the latest Steam build, the panel on the right flickers twice, then stops. I'd go ahead and say that this is fixed.
