### ISSUE TITLE
Single keypress yields multiple presses in input fields on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Bonfire** [unitystation/unitystation#1038]
# Preliminary information
When entering your name or a server to connect to, or typing in chat, the unitystation window duplicates any keypress you make. An example would be, typing "Bon" would yield "Bboonn". The game makes any duplicated characters lowercase, and when backspacing, the backspace is also duplicated. Spaces are not duplicated. I assume this bug extends to all input fields.

## Category
Bug

## Bug: Release or Development?
Release (Steam Build)

# Report
## Current Behavior
The game duplicates keypresses and backspaces when typing.

![screenshot from 2018-05-08 05-02-19](https://user-images.githubusercontent.com/5704760/39748292-b43878b8-527d-11e8-9949-5b16972026f9.png)

## Expected/Wanted/Requested Behavior
The game should not be duplicating any keypresses or backspaces.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Launch the unitystation client
2. Type in any input field

## OS used:
Linux

## System specifications
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.13.0-39-generic
Uptime: 1d 13h 48m
Packages: 2517
Shell: bash 4.3.48
Resolution: 1920x1080
DE: Unity 7.4.5
WM: Compiz
WM Theme: Arc-Darker, Arc-Darker [GTK2], Arc-Darker [GTK3]
Icon Theme: ubuntu-mono-dark
Font: Futura Bk BT 11
CPU: Intel Core i5-7200U CPU @ 3.1GHz
RAM: 4282MiB / 11892MiB
HDD

## Network
Not Connected

**Comment by fomalsd** [comment]
is it still a thing?

**Comment by Bonfire** [comment]
This issue seems to be resolved
![Screenshot from 2019-03-12 15-45-55](https://user-images.githubusercontent.com/5704760/54231013-0b07cd80-44de-11e9-9f40-099f835cc9b0.png)
