### ISSUE TITLE
You can't shoot over stools

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1039]
# Preliminary information
When shooting at something behind a stool the bullet hits the stool instead of going over.
## Category
Is this a BUG

## Bug: Release or Development?
the beta client  version Steam on the 08/05/2018
# Report
## Current Behavior
The bullet hits the stool instead of going over

## Expected/Wanted/Requested Behavior
the bullet passes over the stool 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Grab any gun
2.Find a stool 
3.Try and fire across the stool 

## OS used:
Windows

## Network
dedicated game server

**Comment by fomalsd** [comment]
![gif](https://user-images.githubusercontent.com/10403536/39913931-0e055830-54f3-11e8-8c8c-53997766fff3.gif)
