### ISSUE TITLE
reoccurrence of  #575 "Doors auto-close when you stand between them"

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1040]
#575 and #583 Related issues

## Category
Is this a BUG

## Bug: Release or Development?
the beta client version Steam on the 08/05/2018

# Report
## Current Behavior
doors close on you

## Expected/Wanted/Requested Behavior
doors only close when you're not in the tile

I suspected something to do with the matrix Stuff

![Image](https://i.imgur.com/5Flzr4t.png)

**Comment by Bonfire** [comment]
I believe this is fixed in #1049.

**Comment by fomalsd** [comment]
Indeed
