### ISSUE TITLE
Alt+click is broken

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1041]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
NRE when alt+clicking tiles around you
`NullReferenceException: Object reference not set to an instance of an object
UITileList.ClearItemPanel () (at Assets/Scripts/UI/UITileList.cs:181)
UITileList.UpdateTileList (System.Collections.Generic.IEnumerable1[T] objects, Tilemaps.Tiles.LayerTile tile, UnityEngine.Vector3 position) (at Assets/Scripts/UI/UITileList.cs:163)
UI.ControlTabs.ShowItemListTab (System.Collections.Generic.IEnumerable1[T] objects, Tilemaps.Tiles.LayerTile tile, UnityEngine.Vector3 position) (at Assets/Scripts/UI/ControlTabs.cs:143)
PlayGroups.Input.InputController.CheckAltClick () (at Assets/Scripts/PlayGroups/Input/InputController.cs:93)
PlayGroups.Input.InputController.Update () (at Assets/Scripts/PlayGroups/Input/InputController.cs:56)
`

## Expected/Wanted/Requested Behavior
Should show object list for chosen tile in a new tab + its world position in tooltip

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Host a server in editor, join as assistant
2.Alt+click nearby tile

## OS used:
Windows

## Notes
Seems like it can't FindObjectOfType<UITileList>, did anyone remove it?

**Comment by badbon** [comment]
I think this doesn't happen anymore?

**Comment by fomalsd** [comment]
It's just commented out:
```cs
		private void CheckAltClick() {
			Event e = Event.current;
			if (e.type != EventType.Used && e.button == 0 && (UnityEngine.Input.GetKey(KeyCode.LeftAlt) || UnityEngine.Input.GetKey(KeyCode.RightAlt)))
			{
				//Check for items on the clicked possition, and display them in the Item List Tab, if they're in reach
				Vector3 position = Camera.main.ScreenToWorldPoint(UnityEngine.Input.mousePosition);
				position.z = 0f;
//				if (PlayerManager.LocalPlayerScript.IsInReach(position))
//				{
//					List<GameObject> objects = UITileList.GetItemsAtPosition(position);
//					LayerTile tile = UITileList.GetTileAtPosition(position);
//					ControlTabs.ShowItemListTab(objects, tile, position);
//				}
				
				UIManager.SetToolTip = $"clicked position: {Vector3Int.RoundToInt(position)}";
				e.Use();
			}
		}
```
