### ISSUE TITLE
WinDoors count as space until you touch them

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1042]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
MetaDataLayer returning null MetaDataNode for WinDoor tiles (when checking for IsSpaceAt()) after round start.
Causes syndicate ops to suffocate inside the ship for no reason.

## Expected/Wanted/Requested Behavior
IsSpaceAt() should be reliable

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Host from editor and join as syndie
2.Move to the following tile:
![default](https://user-images.githubusercontent.com/10403536/39761886-c705851c-52c8-11e8-988b-5e4b24ca1010.png)
(You'll start losing health because MetaDataLayer's IsSpaceAt() check would return true as node is null)
3. Walk away, have a meal, move through doors and back, return to that dreaded tile again. You won't be losing health anymore, node won't be null
![gif](https://user-images.githubusercontent.com/10403536/39762432-2e9920f2-52ca-11e8-86e1-27dff295f741.gif)

## OS used:
Windows

## Network
Local host from editor

**Comment by chairbender** [comment]
this is already fixed, just hadn't been marked as such yet
