### ISSUE TITLE
Guides: "How to PR your code to our codebase" B: 35

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1043]
# Preliminary information
We get asked a lot of questions from new contributors on how to PR there stuff to our codebase. The current guides on the wiki suck. Its time to make a really easy to follow guide with lots of screenshots.

Criteria
  - [x] List all the steps required to make a feature from a contributors fork and to submit a PR to the unitystation codebase
  - [x] Keep instructions simple and to the point
  - [x] Ensure the markdown formatting is neat and easy to read
  - [x] Include plenty of screen shots!

$35 usd will be awarded to the writer of the wiki article who completes all the criteria above to a satisfactory standard

**Comment by pedrosantos53** [comment]
https://github.com/unitystation/unitystation/wiki/How-To-Create-a-Pull-Request-(PR)-from-a-Fork

**Comment by DooblyNoobly** [comment]
Thank you very much pedrosantos53 looks good
