### ISSUE TITLE
[BUG] Impossible crafting

### ISSUE THREAD

**Issue by jujulilope** [unitystation/unitystation#10476]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

24-08-03-21

### I was

Server

### OS

Windows 8, 10, 11

### What happened?

When interacted with building materials, as CE on every station, the caracter freeze.
 Impossible to move, drop the item, change hand. 
The only way to unfreeze is to open the craft menu and to close it.

### What should have happened instead?

...

### Steps to reproduce the issue

1. Spawn as CE / Engi.
2. Take a stack of crafting materials (sheet of metal, glass).
3. Interact with it to open the building menu.

**Comment by Fr-Dae** [comment]
same has HoP and Engy.

interact with material (like metal or glass) don't open the construction menu. just freeze the caracter.
