### ISSUE TITLE
[Mapping] Ministation, hachet missing (botanist) 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10471]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Map

MiniStation

### Description of the problem

hachet mission on locker for botanist, it's a basic tool needed for some craft.

### Pictures/videos

![Capture d’écran (63)](https://github.com/user-attachments/assets/811e0f4d-91a7-456f-9a10-d04f143331f7)

**Comment by MaxIsJoe** [comment]
![image](https://github.com/user-attachments/assets/d4225dab-5a7c-4840-94b3-8f8cb7eb0f6f)

there are ones in lockers
