### ISSUE TITLE
Doors/Windoors share same behaviour (regression)

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1048]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
Both doors and windoors close if you stand on the door tile, make identical sounds, are interacted with if tile is clicked

## Expected/Wanted/Requested Behavior
Their behaviour should be different: Doors should never close if you stand on that tile (windoors should)
They should have different sounds,
Both doors and windoors should only be interacted with if you click on its sprite (and not the whole tile)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Stand in opened doors (they will close on you)
2. Click somewhere on a windoor tile (but not windoor itself) – it will open

## OS used:
Windows

## Network
Editor host

**Comment by Bonfire** [comment]
Looking at the assets for the doors, any door that "has a window" in its sprite is classified under the "Windows" layer. I added a line of code in an earlier PR (#1031) that made it so WinDoors would close even if you were standing on the tile they were placed on. I used the method "isWindowedDoor" from https://github.com/unitystation/unitystation/blob/a101b542aba30d71ab6ba70cd4bd08ca2a86d749/UnityProject/Assets/Scripts/Doors/DoorController.cs#L35

Of course I may be wrong about this, but my best guess is that the isWindowedDoor method simply checks to see if the door has a window, and _not_ if it is a WinDoor. This being said, editing the code on https://github.com/unitystation/unitystation/blob/a101b542aba30d71ab6ba70cd4bd08ca2a86d749/UnityProject/Assets/Scripts/Doors/DoorController.cs#L134 to make sure that only doors of the type WinDoor call RpcClose() should fix the issue. This was of course my fault, as I had assumed that isWindowedDoor checked for whether or not an object was a WinDoor and not if an object had a window.

**Comment by Bonfire** [comment]
I've just edited the DoorController.cs file with the changes I've stated above and it looks like it fixed the issue of doors closing on players when they shouldn't. I'll push out the changes and make a pull as soon as my current pull request is closed.

**Comment by DooblyNoobly** [comment]
yep, reviewing the other pr now

**Comment by DooblyNoobly** [comment]
2/3 is fixed. Only problem left is the clicking issue. I think this has something to do with my door fov tile that I spawn at runtime. It seems to be catching the raycast. Need to find a way to ignore it
