### ISSUE TITLE
[BUG] Deconstruct wall/windows notre possible

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10517]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

2024.08.27.18

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Ha HoP, on fallstation.
la deconstruction des vitre renforcé et des mur remforcé est simplement impossible, aucun outils ne fonction, 

de plus l'usage de la force pour frpper dessus (pieds de biche par exemple) n'a aucun effet, pas d'animation , rien

il est donc techniquement impossible de deconstruire ou de detruire un mur ou une vitre renforcé sans des moyen lourd (shuttle, explosion, destroyer laser etc )

### What should have happened instead?

Test the merge BEFORE publishing a non-functional, unplayable build with no basic mechanics. 

### Steps to reproduce the issue

use tool on a reinforced wall or windows,
do nothing
be disappointed and upset

**Comment by MaxIsJoe** [comment]
Cannot replicate on upstream currently. Needs further investigation.

**Comment by MaxIsJoe** [comment]
Not reproducable
