### ISSUE TITLE
[BUG] put objet on table impossible

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10518]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

2024.08.27.18

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Has HoP, on fallstation.
It is currently impossible to simply place or rest an object on a surface, such as a table, reinforced table or glass table.

You either have to throw it away, which poses a number of problems:
- from a PR point of view it's not right, who throws things in the face or onto a table?
- is not the expected action.
- the bottles will be knocked over and/or broken, which quickly becomes a problem for the chemistry and the bar. 

Whether it's putting a PDA on the hop's desk, a pen on a table, or bottles of product, it's important to do it naturally without having to fiddle.

It is indeed possible to mount on the table (except glass tables) but it's counter-intuitive and time-consuming. 

### What should have happened instead?

Test the merge BEFORE publishing a non-functional, unplayable build with no basic mechanics. 

### Steps to reproduce the issue

clic on table with a objet
nothing happend
be disappointed and upset

**Comment by MaxIsJoe** [comment]
Cannot replicate on upstream currently. Needs further investigation.

**Comment by MaxIsJoe** [comment]
Not reproducable.
