### ISSUE TITLE
Synthetic and Cybernetic limbs should be unified.

### ISSUE THREAD

**Issue by AtnerNT** [unitystation/unitystation#10553]
Currently in game we possess two sets of items, the synthetic limb set, and the cybernetic limb set.
Synthetic limbs look identical to cybernetic limbs, but their purpose is to be implanted on living creates to improve mobility and function.
Cybernetic limbs on the other hand, require power and sole purpose is to be implanted as part of cyborg construction.

It doesn't make sense to have these two items separate, it is unintuitive and can lead to mistakes when attempting to perform surgery on players. 
Synthetic limbs should be dissolved, and their functionality added to cybernetic limbs. Battery packs should be able to be implanted in organics safely and organics should be able to charge them by entering charging bays just like cyborgs.

Not only is this an important balancing factor to synthetic limbs (You can be 10x the normal move speed, but you will need to recharge your limbs) it also is a lot more natural gameplay wise.

**Note to developers:** If you are addressing this issue, synthetic limbs and cyborg limbs both exist on the techweb, design files and their own exosuit fabricator categories. Ensure this is all corrected as part of the unification.

**Comment by corp-0** [comment]
I like this proposal
