### ISSUE TITLE
Bug: Player Matrix detection is not working on Flashlight DeathMatch scene

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1058]
# Preliminary information
- As soon as a player spawns on FlashlightDeathmatch they float off into space. 

## Category
BUG

# Report
## Current Behavior
- When spawning on FlashlightDM you spawn on the station or shuttle correctly but you instantly start to take space damage and when you try to move you just float in the direction of movement until you die.
- When debugging the PlayerMatrixDetector it seems to have the correct matrix but for some reason the player is ignoring the matrix information

## Expected/Wanted/Requested Behavior
- Player should spawn normally and interact with the matrix that they have spawned on in the FlashlightDM map

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open Flashlight DM
2. Spawn anywhere
3. Try to move around

### Notes:
I tried to sneak in the fixes in my last PR by copying the matrix structures from OutpostDM but nothing seems to work. I cross referenced everything I could think of and made sure all layers and components were set correctly. I also debugged curMatrix in player move and it is the correct one. @fomalsd you might have an idea of where to look next?

**Comment by fomalsd** [comment]
I know exactly why this is happening, MatrixManager makes sure there are "4" matrices before init, otherwise it considers level not loaded yet and waits and retries

**Comment by DooblyNoobly** [comment]
Aright, we can set a matrix amt variable in the inspector for the time being
