### ISSUE TITLE
Hovering works for things hidden behind FoV

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1063]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
develop

# Report
## Current Behavior
Hovering mouse over the black (FoV-covered) zone shows tooltips for these objects

## Expected/Wanted/Requested Behavior
Hovering shouldn't work for things you can't see

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
![fovtooltips](https://user-images.githubusercontent.com/10403536/39971904-2216e886-570d-11e8-8c90-34da4fac2388.gif)

## OS used:
Windows

## Network
Self-hosted/steam server

**Comment by chairbender** [comment]
Related to #389

**Comment by chairbender** [comment]
Just to add what I noticed for whoever works on this - there's a VisibleBehavior component that is supposedly what should ensure that these disappear, but it looks like for most objects the "Visible State" flag of that component is never updated, even when the object goes out of view

**Comment by chairbender** [comment]
NVM, I think VisibleBehavior is only used for globally hiding / showing things that are inside of other things. Setting something invisible through VisualBehavior would globally hide it, which we obviously would't want since some players can see things that other players can't.

**Comment by chairbender** [comment]
As part of my other ticket, my investigation found that the logic which hides an out of view object is actually done ENTIRELY via shaders. There's no flag / variable set when an object isn't in view - only Sprite Fov Masked.shader sets its sprite to be invisible based on the Fov Mask texture. There is no output or other flag set which tells us if the sprite has been completely hidden by this shader.

So this ticket will probably involve implementing a system which properly updates all objects' states based on whether they are visible to the local player.

**Comment by chairbender** [comment]
Another alternative suggest in Discord was to just have a check on mouseover if the object is visible (do a single raycast and see if it can be reached). Probably a better option, simpler and less expensive.

**Comment by chairbender** [comment]
Another possibly better alternative - the lighting engine already is figuring out what parts of the map are visible, so it should be possible to re-use one of the textures being generated there to do the check if a given pixel is at a location that is visible. When a user mouses over an object, just look up that coordinate in the texture and see if it is marked as visible. This avoids needing to do any raycasting

**Comment by DooblyNoobly** [comment]
> Another possibly better alternative - the lighting engine already is figuring out what parts of the map are visible, so it should be possible to re-use one of the textures being generated there to do the check if a given pixel is at a location that is visible. When a user mouses over an object, just look up that coordinate in the texture and see if it is marked as visible. This avoids needing to do any raycasting

Yeah I was thinking something similar. I like your idea. So first when the item is instantiated the (VisibleState? ) component needs to find at least one pixel that is not transparent and store its co-ordinate for that texture. Then we can use that pixel as the reference to see if it is visible or not. Only problem is that texture co-ordinates are tricky as they are not relative to the rotation of the texture itself in world space. So if you rotate a texture, the cached co-ordinates used do not match up to when it was at Vector3.zero rotation.

**Comment by DooblyNoobly** [comment]
We might be able to use this instead: https://docs.unity3d.com/ScriptReference/Texture2D.GetPixels.html 

Then iterate through the Color array until we find a Color with Alpha 255. Cache the position in the Array and check the Color at that position whenever we want to know its Visible state.

**Comment by DooblyNoobly** [comment]
### Critera:

- Solve this issue ticket and ensure that #1426 is also fixed in the process

A bounty of 50usd will be awarded to the contributor on the successful merge of a solution.

**Comment by fomalsd** [comment]
also one more thing: you can rightclick behind FoV and it will show tile's contents as well

**Comment by chairbender** [comment]
2 things to fix:
1. Looks like this causes a significant increase in draw calls, fps seems to drop by 20 with this change.
2. Alt click behavior should match right click behavior.

**Comment by fomalsd** [comment]
It is a thing again
