### ISSUE TITLE
Item tooltip doesn't always show until item's interacted with

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1064]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop/Steam

# Report
## Current Behaviour
Items placed on the floor/tables in editor sometimes don't show item name and description in tooltip zone until they're interacted with.
This does not concern items spawned in runtime or ones inside containers.

## Expected/Wanted/Requested Behaviour
Tooltips should always be shown

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host a server
2. Start hovering items and find one that doesn't show a tooltip
3.Pick it up, drop it, and see if it shows a tooltip
![nohovertoolteep](https://user-images.githubusercontent.com/10403536/39971965-48b5dadc-570e-11e8-8bcc-bc8865e2876f.gif)

## OS used:
Windows

## Network
Self-host/Steam server

**Comment by Bonfire** [comment]
Currently looking into this. I've checked to see if the issue would be resolved by using the IPointerEnterHandler interface with the OnPointerEnter function, but that did not resolve anything (it has the very same behavior). Even when a 2D Physics Raycaster was added to the camera (which I believe IPointerEnterHandler requires), the IPointerEnterHandler interface did not fire off any events. I have also checked to see if the items on the map are below the Objects Tilemap in the Sorting Layers, and there are no issues there. Lastly, trying to disable the TopLayerEffects Object Layer component and Tilemap Collider 2D component in the Objects Tilemap did not resolve the issue.
