### ISSUE TITLE
Guide: Adding prefabs to the Tilemap palette B: 35

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1075]
## TODO

Create a guide that explains the steps required to add a new item/object prefab to the Tilemap palette. 

 ### Criteria
 
 - List out the steps required to add a prefab to the objects screen of the Tilemap palette
 - Investigate and explain how to create a preview tile for the new Tile brush
 - Show how to paint the new tile into the scene
 - Create the guide on the Wiki
 - Add sufficient screenshots or gifs to the guide
 - Keep the instructions simple and to the point

Contributor who meets all of the above criteria will be awarded the $35 usd bounty on completion.

Post link to the guide here when it's done.

**Comment by dapocalypse** [comment]
https://github.com/unitystation/unitystation/wiki/Adding-prefabs-to-the-Tilemap-palette

**Comment by DooblyNoobly** [comment]
@dapocalypse did not meet any of the requirements above

**Comment by Scrando** [comment]
https://github.com/unitystation/unitystation/wiki/Using-Tile-Palettes

Here's a rough draft of what I had in mind.
The second criteria has me confused as to what it's asking for. Any clarification is greatly appreciated.

**Comment by DooblyNoobly** [comment]
looking real good @Scrando

So in this tut you pick a prefab that has already been added and because of that the tile asset has already been made. The tutorial needs to go into the process of actually creating that Tile asset from the tiles folder: https://github.com/unitystation/unitystation/tree/develop/UnityProject/Assets/Tilemaps/Tiles

From memory I think you can just duplicate one, add the prefab to it and the preview sprite (that is shown when you have selected paint brush and are hovering over the scene). I'm not 100% sure though as I've never done it. @krille90 can you shed some light on how to create the tile asset?

**Comment by Scrando** [comment]
Thanks for the help @Ornias1993!

Here's the newly updated wiki page. I'm fairly certain it is fully featured, however if there's parts of it that are unclear please let me know and I will update it as soon as I can.

https://github.com/unitystation/unitystation/wiki/Creating-and-Using-Tile-Palettes

**Comment by DooblyNoobly** [comment]
Thanks @Scrando looks really good. Can you add the link to the new page in the right nav and the body of the home page on the Wiki. And then send me your paypal email either through here or discord for the bounty
