### ISSUE TITLE
Easy to use Network Tab Element interactions B: 80

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1086]
# Preliminary information

## Category
Feature Request

## Current situation
It's hard to write a secure networked tab. It involves writing a lot of code in many different places, and is difficult to navigate and understand, especially for new devs. 

## Criteria:
Develop a layer that would take care of security and remove the burden of writing lower-level network code from devs that want networked Tabs/Windows just to work like they do in single player games:

- [x] Window elements should be easily bindable (single- or bidirectional) to server methods. 
Server-to-client updates should be implicit. 
This should also have dynamic element support (like Vend buttons in item list for vendors)
- [x] Built-in implicit serverside security checks
- [x] Multiple instances of the same tab type for one player should be possible
- [x] Server must know if tab is opened at the moment and automatically close it for player if he isn't in range

**Comment by DooblyNoobly** [comment]
Bounty B: 80 applied

 #### Criteria:
 - See above

Bounty of 80usd will be paid to the contributor on a successful merge
