### ISSUE TITLE
Basic Electricity Simulation

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1098]
# Preliminary information

## Category
Feature Request

# Report
## Requested Behavior
Implementation of a Electricity Simulation for the Station.

Things that need to be worked out:
- [x] Networking information
- [x] Simulation of flow between cables
- [ ] Batteries
- [ ] Generation

**Comment by krille90** [comment]
@DooblyNoobly progress?

**Comment by DooblyNoobly** [comment]
yep, super basic power net is in. We need to do batteries and generation next and then all the fun stuff like the GUI's and readouts.
