### ISSUE TITLE
Basic Chemistry System

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1099]
# Preliminary information

## Category
Feature Request

# Report
## Requested Behavior
Implementation of a Chemistry System

Things that need to be worked out:
- [x] Storing chemistry recipes
- [x] mapping of components
- [x] Reaction with other components, e.g. temperature, catalysts...

### Further Remarks
This system used for this could be made as a generic crafting system that can be reused in other area

**Comment by Bod9001** [comment]
What type of stuff should affect reactions?
Currently planned

Temperature 
Catalysts

Any suggestions on any more?

**Comment by dapocalypse** [comment]
we need to make chemistry moar complex then base

**Comment by krille90** [comment]
@dapocalypse what does "more complex" mean? In what way?

**Comment by dapocalypse** [comment]
Instead of just plopping a beaker into a machine and maybe heating it up you have a variety of equipment in which you use to create things.

**Comment by moonheart08** [comment]
Complexity != fun

**Comment by DooblyNoobly** [comment]
> Complexity != fun

I agree. Keep it simple and fun.

**Comment by dapocalypse** [comment]
But SS13 Prides itself in depth

**Comment by moonheart08** [comment]
@dapocalypse https://www.youtube.com/watch?v=jVL4st0blGU

**Comment by ghost** [comment]
Depth comes from a variety of possible outcomes you can do with different approaches. If you use various equipments for chemistry then it should provide benefits in form of more precision in manipulating with outcome.

**Comment by moonheart08** [comment]
@outbools good point. I think offering the usage of more complex/specialized equipment for, say, automation could work out great. I just disagree with making the player manually have to drudge through the complexity every time they want to make some deadly explosives. Automating the production of a chemical is pretty much the only situation where precision should be absolutely necessary. SS13 isn't realism simulator 2005, so making chemistry quick, interesting, and with a fair bit of depth (not complexity) for normal tasks, and letting the people who normally hole up in the circuit lab making circuits or optimize explosives have fun with the complexity.

**Comment by dapocalypse** [comment]
Yea, if you have a chemistry recipe you need it should take you five seconds, but the extra equiptment comes in when you want to experiment with more complex things and find more than basic chemicals.

**Comment by dapocalypse** [comment]
Alright, the four base medicines, Syptic Powder, Silver Sulfatizide, Sabumatol, and Charcoal are all regular, but the other recipies require the use of the other equiptment.

**Comment by moonheart08** [comment]
@dapocalypse that's what i said SHOULDN'T happen. Advanced equiptment, if any, should be used for either automating chemistry, or advanced chemistry like slime core shenanigins

**Comment by dapocalypse** [comment]
yea advanced chemistry, the core medicines are fine, to get better and other types of chemicals you need better equiptment

**Comment by dapocalypse** [comment]
other and better medicines are advanced

**Comment by moonheart08** [comment]
@dapocalypse do i need to keep repeating that i believe that's a bad thing to do.

**Comment by krille90** [comment]
The focus of this issue should a basic chemistry, not any advanced / fancy stuff.

**Comment by dapocalypse** [comment]
You said it should be used for advanced chemicals,anything other than the core medicines are advanced?

**Comment by Bod9001** [comment]
Simple chemistry so far is in #1107 Same as base chemistry
