### ISSUE TITLE
Logo Design: Unitystation

### ISSUE THREAD

**Issue by baranpirincal** [unitystation/unitystation#1108]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by fomalsd** [comment]
Thanks, but we already have a logo in place
![512](https://user-images.githubusercontent.com/10403536/41978005-5dd8f1ae-7a10-11e8-97a3-4888f456b43b.png)
