### ISSUE TITLE
Doors are culled from FOV until opened upon joining server

### ISSUE THREAD

**Issue by JacobSweeten** [unitystation/unitystation#1109]
# Preliminary information
Doors appear black as if culled from FOV until you open them.

## Category
Bug

## Bug: Release or Development?
Steam Release

# Report
## Current Behavior
![bug2](https://user-images.githubusercontent.com/11415022/42015542-70784e6a-7a6d-11e8-8c7e-fd6148dffd7a.png)
![bug1](https://user-images.githubusercontent.com/11415022/42015554-7b6a96a2-7a6d-11e8-8ab0-c9fac8b80062.png)

## Expected/Wanted/Requested Behavior
Doors should be visible without being opened.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Look at a door
2. ???
3. Not profit

## OS used:
Windows 10 x64

## System specifications
Intel core i3-3220, GTX 1060 6GB, 250 GB SSD, 8GB RAM.

## Network
Ping of about 120 on play.unitystation.org

EDIT: After server restarted the round, it worked normally again. It may be a random issue or caused by a set of interactions.

EDIT 2: I restarted the game from Steam, and chose engineer like I did the first time. Issue reproduced.

EDIT 3: Issue also went away in same round. Renaming issue.

**Comment by DooblyNoobly** [comment]
Should be fixed now
