### ISSUE TITLE
Trailblazer needs work

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1120]
# Preliminary information

## Category
TODO

## Bug: Release or Development?
Develop

# Report
## Current Behavior
- Lots of mapping errors, for example:
![screenshot 2018-07-03 21 43 16](https://user-images.githubusercontent.com/10403536/42239170-ca72d410-7f0b-11e8-93b3-8791ca85ae02.PNG)
![screenshot 2018-07-03 21 48 22](https://user-images.githubusercontent.com/10403536/42239172-cf7be8e8-7f0b-11e8-81ad-90c020746d42.PNG)
![screenshot 2018-07-03 21 48 31](https://user-images.githubusercontent.com/10403536/42239178-d54269c8-7f0b-11e8-93fd-f281ef2df2c3.PNG)
- None of the shutters work (shutter button does nothing)
- Some sections are unsealed
- Feels empty with nothing in lockers/boxes and not much around
- Syndicate shuttle is a bit too far from the station IMO

## Expected/Wanted/Requested Behavior
Trailblazer should be fully functional, have no mapping errors and be interesting to play on
Also perhaps its main matrix could be slowly moving on its own

## OS used:
OSX

## System specifications
MBP 2010

## Network
50ms to test server

**Comment by fomalsd** [comment]
it was partially fixed, but issue will stay open

**Comment by krille90** [comment]
Isn't this map now obsolete?

**Comment by DooblyNoobly** [comment]
Trailblazer is ded.
