### ISSUE TITLE
Firearms: NRE when client's mag is ejected while shooting

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1123]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Development

# Report
## Current Behavior
Sometimes when client sends shoot requests and mag is already ejected NREs appear.

## Expected/Wanted/Requested Behavior
No NREs

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
Kinda hard to replicate, might take several attempts
1. Host in editor, join as build (reproduced with 200 ping setting, syndicates)
2. Pick up machine gun as client and keep shooting till you run out of ammo, peeking at server console
3. Eventually these will apear:
`[12:42:21:761] NullReferenceException: Object reference not set to an instance of an object
Weapons.Weapon.Shoot (UnityEngine.GameObject shooter, UnityEngine.Vector2 direction, System.String bulletName, BodyPartType damageZone, System.Boolean isSuicideShot) (at Assets/Scripts/Weapons/Weapon.cs:383)
Weapons.Weapon.ServerShoot (UnityEngine.GameObject shotBy, UnityEngine.Vector2 direction, System.String bulletName, BodyPartType damageZone, System.Boolean isSuicideShot) (at Assets/Scripts/Weapons/Weapon.cs:366)
RequestShootMessage+<Process>c__Iterator0.MoveNext () (at Assets/Scripts/Messages/Client/RequestShootMessage.cs:32)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
`

## OS used:
Windows

## Network
Localhost editor + 200ms build

**Comment by chairbender** [comment]
Seems like the SyncVar on CurrentMagazine.ammoCount is part of the issue - client and server can sometimes disagree on what the ammo count is. Server is not doing enough server-side checking when a shoot message is requested to prevent player from shooting more than they have.

This should be done as part of #989 IMO
