### ISSUE TITLE
Clients can't do melee at all

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1124]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
Nothing happens when clients attempt to fight melee / do suicide shots

## Expected/Wanted/Requested Behavior
Behaviour should be identical to serverplayer's

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host a server in ieditor, join as build
2. Grab some item as client, set intent to harm (key "4"), try clicking yourself or serverplayer (nothing will happen)
3. Also grab a firearm snd try to shoot yourself in the face (nothing will happen)

## OS used:
Windows

## Network
Localhost from editor + 200 ping client

**Comment by DooblyNoobly** [comment]
doesn't work on headless
