### ISSUE TITLE
Bullets are affected by ship movement (and so is throwing)

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1125]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Development

# Report
## Current Behavior
In title.
High ping clients can't throw anything properly on a fast flying ship at all.

## Expected/Wanted/Requested Behavior
Bullet and throwing positions should not be affected by matrix movement and its speed if these are within matrix

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor, join as 200ms client as syndies
2. Start flying ship at max speed
3. Grab a firearm and start shooting perpendicular to the flying direction
![gif](https://user-images.githubusercontent.com/10403536/42372880-f849a41a-8102-11e8-99fe-742a6b1aedb2.gif)
Perhaps there should be some implicit check for shooting/throwing to use local coordinates instead of world ones if aim is within current matrix?

## OS used:
Windows

## Network
Various

**Comment by DooblyNoobly** [comment]
isn't this fixed now?

**Comment by fomalsd** [comment]
shouldn't be. unless someone did a super sneaky fix since then?

**Comment by krille90** [comment]
I suppose the objects are not spawned properly in the Objects layer of the matrix, or their movement isn't calculated in local space.

**Comment by fomalsd** [comment]
yeah, it's due to world space calculations (because they could be cross-matrix)
but making them local/world depending on context would be a delicate task and should probably be postponed until other interaction-related things settle down

**Comment by chairbender** [comment]
this is okay to work on now
