### ISSUE TITLE
Big items cannot be picked up by clients (but server can)

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1126]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
develop

# Report
## Current Behavior
There is a weird slot size mismatch between serverplayer and clients

## Expected/Wanted/Requested Behavior
Slot sizes should be identical

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor, join localhost with Build, both syndies
2. Try to pick up M90 rifle on syndie ship as client
3. Nothing will happen and this will be printed to logs:
`.: Huge M90_ballistic (UnityEngine.GameObject) is too big for Medium leftHand!`

## OS used:
Windows

## Network
Localhost from editor + build as client

**Comment by DooblyNoobly** [comment]
fixed
