### ISSUE TITLE
Create the initial(basic) layout and structure for the Admin Panel (frontend) B:100

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1136]
# Description

We need the initial layout and framework in place to start building a fully functional admin portal with server monitoring and RCON capabilities.

This job is for a web developer to choose the initial environment (node.js, react) set up the project structure and develop two pages with very limited functionality.

## Category
TODO

## Criteria:

- [ ] Decide on a frontend framework and environment to develop the admin portal in. Keep in mind there will be realtime monitoring of the game servers' logger system so the admin portal has to be in some kind of web app framework like react.
- [ ] Create a login page and create the basic layout and styles

This whole system is being modeled off the facepunch.io webrcon portal. For ideas on what we are eventually aiming for here is a screenshot of the facepunch login:

![image](https://user-images.githubusercontent.com/20813925/42729974-f6f9a322-882c-11e8-94b9-58c4fb28b44f.png)

- [ ] Create a box bg image with rounded edges and place it in the center
- [ ] Create two Input fields that will eventually be used to log in to the portal (that will come in a later job)
- [ ]  Create a login button but just make it open the admin portal home screen (no log in system yet)
- [ ] Create the basic layout for the admin portal, there needs to be a top panel for overall stats, a left navigation panel and then the content in the middle.
- [ ] Add 2 test navigation links that should change the content pages in the middle

For ideas see the Facepunch admin portal:

![image](https://user-images.githubusercontent.com/20813925/42730087-cd609a78-882e-11e8-84b8-d3bc86e8268d.png)

## Notes:
Use a bit of imagination and add any buttons or other items that you think belong there.

Bounty:
Contributor will receive $100 usd (minus paypal fees) on a successful merge

**Comment by mikestonecodes** [comment]
Hey my internet sucks so I couldn't download the repo, but I shared a repo with this in it.

**Comment by DooblyNoobly** [comment]
thanks! Let me know when its done and I'll test it out
