### ISSUE TITLE
Reimplement Push/Pull with the new Movement System B: 260

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1145]
# Description
Push pull needs to be rewritten to work with the new movement system. At the moment it has been commented out as it has broken since then.

Some notes to remember:
- The movement works on a replay prediction system, look at PlayerMove and PlayerSync and note where you see the isReplay bool
- There is a lot of old code that will need to be removed

## Category
TODO

## Criteria:

 - Develop a push pull solution that works over network and works well in high lag situations
 - You need to handle the clearing and registering on the matrix of the item being moved
 - Pulling objects between multiple matrices needs to be handled

Bounty of $260 usd will be paid to the contributor on a successful merge

**Comment by TheWrongHands** [comment]
there is a lot of the code i have yet to go though, so i don't know how a lot of what going on under the hood, but this seems like it would be fairly simple to do.

client sends grab request to server
server checks to see if grab can happen
if yes broadcast grab to clients (for sounds and things)
move object behind player until something ends grab
broadcast grab end

fairly simple and strait forward, could be done fairly easily, however "...and works well in high lag situations" throws up a lot of red flags. this is like finding a bluetooth enabled sandwich, why is that even there? beyond not writing terrible laggy code, this mechanic shouldn't be be concerned with any sort of lag compensation, that's the job of the net code, physics engine, animation, and possibly a few other systems that this would be built upon.

is there something weird going on in the code or is that meant to be some sort of standard disclaimer to allow you to reject poorly written code?

**Comment by DooblyNoobly** [comment]
ah no just means that you have tested it with the net simulator on. Check out our wiki on testing (scroll down to the ping simulation title): https://github.com/unitystation/unitystation/wiki/Building-And-Testing

**Comment by TheWrongHands** [comment]
alright, that makes a lot more sense

**Comment by Em3rgencyLT** [comment]
As @TheWrongHands said, implementing this from scratch is not that complicated. The issue is that the old code is still there. And I'd argue that finding and removing it should also be under the requirements here. The few times I had to delve into push code, it was horrible and buggy and we don't want it ruining any more lives ever.

**Comment by DooblyNoobly** [comment]
probably would be a good idea to gut the old stuff. Has anyone made any progress on this yet? If not I can go in and remove all the old code so we have a clear slate

**Comment by DooblyNoobly** [comment]
Bounty increased from B200 to B260
