### ISSUE TITLE
Inventory Items look squeezed and a bit misaligned

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1155]
# Description

## Category
BUG

## Detailed Bug Report
Left hand slot seems to be aligned alright.
ones to the left/right from it suffer from horizontal offset.
Also all of them are squeezed vertically

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Start game and look at your inventory, ID card, for instance

![default](https://user-images.githubusercontent.com/10403536/43123841-ecee4b78-8f14-11e8-93f9-53adff892b25.png)

**Comment by krille90** [comment]
I put this into the Steam Release project as a "polish task". This has low priority though.

**Comment by DooblyNoobly** [comment]
should be fixed now, I've set them to a forced size of 50 x 50. But might try to do 64 x 64 if there is still a problem with visual looks.
