### ISSUE TITLE
Basic Traitor System

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1192]
# Description
To spice up the rounds, a basic traitor system could be implement, where a few people get a target person to kill and escape.

# Example 

0) Traitor selection, one or two as there are also nuke ops people.
1) Team communication amongst traitors.
2) Random target selection, and yes it can be your traitor partner.
3) Have a system to mark escape, meaning if they get away from the main ship by a certain distance you are a successful traitor if you completed the mission.

**Comment by chairbender** [comment]
I believe this is fixed now as of #2237
