### ISSUE TITLE
Bug: Nuke detonation video does not play in steam builds

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1200]
# Description

As per the title. In the steam builds the Nuke det video fails to play

###TODO:

 - Check player logs after the nuke goes off to see if there is an error: https://docs.unity3d.com/Manual/LogFiles.html

 - If nothing is found in there, check the Server build logs to see if there was an import problem with the video

**Comment by badbon** [comment]
I messed with its resolution in #1186

I am not sure if that would break anything though.
