### ISSUE TITLE
Bug: Player Direction twitches on high ping clients

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1209]
# Description

When connecting to the server with a high ping client sometimes PlayerDirection changes cycle back and forth from local and server states until the server updates causing a twitching action. 

Need to make the LocalPlayer rely on its local state more then the ServerState. Perhaps a change direction force flag could be implemented for PlayerDirections that are generated on the server (Like being dragged etc).

**Comment by fomalsd** [comment]
Pretty sure it's because of PlayerSprites.currentDirection SyncVar
