### ISSUE TITLE
Player corpses appearing upright when joining round in progress

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1240]
# Description

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host a server and die once as serverplayer
2. Join with a 200ms ping client
3. Take a look at serverplayer's corpse as client

**Comment by chairbender** [comment]
I can reproduce this, actually I see that the player's corpse is not even there on the clientside as of the latest develop.

**Comment by JaytleBee** [comment]
Doesn't seem fixed to me, has this been reintroduced?
