### ISSUE TITLE
Logout Option

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1251]
# Description

## Category
Feature

## Description

Add a logout option that brings you back to the login window. This would be useful for switch server (or testing)

## Further remarks

When the steam auth fails, you get kicked out and the login screen is shown again. The logout option should do the same and therefore this should be some reusable code. (If not reusable, make it so as both have the same behaviour, i.e. bring you back to the login screen.)

**Comment by fomalsd** [comment]
It's done (but causes side effects)
