### ISSUE TITLE
Bug: Light hit boxes are too big

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1258]
# Description

The light hitbox is as big as a tile. It needs to fit the size of the light itself. Also consider adding the effects of the light when it breaks (sparks and broken tube sprite)

**Comment by fuele** [comment]
Is this still a valid issue? I'm looking at commit https://github.com/unitystation/unitystation/commit/3da3d99bec78cbcc5e8e895df21802bbd9ea2810 and the hitboxes on the LightTubes and LightBulbs look to bee the approriate size. Although the emergency_lights does not have a hit box.

**Comment by fomalsd** [comment]
@fuele it's still a valid issue, but it's more directed to how things get damaged during throw.`
Throw damage system just checks if there is something registered on a tile that thrown object is approaching and just damages it regardless of its hitbox

https://github.com/unitystation/unitystation/blob/3baf9eb68dc5eb039b1bbd32c5370bd4a470420f/UnityProject/Assets/Scripts/Transform/CustomNetTransform.Move.cs#L428

Try throwing something on the tile with a lamp and you'll see what I mean

**Comment by JesterX666** [comment]
Current state of the situation : seems that lights aren't breakable anymore.

**Comment by chairbender** [comment]
yeah and now lights are "Wall protrusions" (using the new WallProtrusion component) and logic would need to be added to rotate their hitboxes along with their sprites due to the new way rotated sprites work for matrix rotations

**Comment by Macoron** [comment]
Well, there two ways to rotate wall protrusions:

- Can create box collider as child object and rotate it. In order to raycasts work, it will require to setup a proxy call to the parent components (Like Meleeable, ObjectAttributes, etc). For sure it's a hard way.
- Can rotate the whole object and doesn't change child sprite render rotation. It's easy to implement and I don't see any downsides.

I tested it a bit and it seems to work fine (even on shuttle). Maybe I'm missing something?

**Comment by chairbender** [comment]
Just to make sure you are aware of the nuances of wall protrusions...There's 2 components which can be used on a directional object (which wall protrusions are) to decide what should happen based on their facing. DirectionalRotatesChildren will rotate ALL child transforms to face in the object's CurrentDirection (which is managed in Directional). DirectionalRotationSprites only rotates child transforms that have SpriteRenderer.
