### ISSUE TITLE
Multimatrix lag

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1268]
# Description

## Category
BUG

## Detailed Bug Report
When two matrices overlap, it gets very laggy. Needs to be investigated

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Fly syndie ship into station
2. ???
3. Profit

**Comment by fomalsd** [comment]
This most likely is due to Rigidbody 2D components on movable matrices and them having non-composite colliders

**Comment by fomalsd** [comment]
~~Turning off physics2d seems to fix this:~~
![default](https://user-images.githubusercontent.com/10403536/52038604-a6df0a80-252a-11e9-8ee2-fc51fa0816e6.png)
Before:
![default](https://user-images.githubusercontent.com/10403536/52038632-c0805200-252a-11e9-87ce-5fa9502db1a7.png)
After:
![default](https://user-images.githubusercontent.com/10403536/52038661-c6763300-252a-11e9-802b-ddd1d64219e4.png)
I'm just not sure if physics2d simulation is required for anything else.

Edit: no, it doesn't really work

**Comment by fomalsd** [comment]
CPU strain is mostly gone after collision layer tweaks
