### ISSUE TITLE
"None" as channel name after round restart

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1269]
# Description

## Category
BUG

## Detailed Bug Report
(Actually not sure if it's really a bug)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Chat a little
2. Restart round
3. have "None" as channel

![image](https://user-images.githubusercontent.com/7312905/46220474-76078280-c34a-11e8-8dd1-74b55c648071.png)

**Comment by Fishfish458** [comment]
going to look into this one

**Comment by krille90** [comment]
Any progress?

**Comment by Fishfish458** [comment]
I got a little distracted with another issue, but from what i tested i could only get it to None after the round ended, on restart it seemed to go back to local.

**Comment by Fishfish458** [comment]
If anyone else wants to try this one, I can't effectively reproduce the issue to actually debug it.

**Comment by Jibbajabbafic** [comment]
I think this should be fixed by #1923
