### ISSUE TITLE
Syndicate headset is hidden behind ear icon

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1271]
# Description

## Category
BUG

## Detailed Bug Report
![image](https://user-images.githubusercontent.com/4493127/46221806-60905980-c346-11e8-9817-82acc7ea1360.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join as syndie
2. Look at ear

**Comment by fomalsd** [comment]
probably just wrong sprite. ItemAttributes likely failed to find the correct inventory one and picked the "on player" one as fallback. 
Setting Trace level to `DmMetadata` in Logger will show what's wrong

**Comment by StrawberryMoses** [comment]
This can be closed: looks like it was fixed at some point in the last year. 
![Screen Shot 2019-10-05 at 4 41 28 PM](https://user-images.githubusercontent.com/8854773/66261232-0ca52580-e78f-11e9-95fb-c8dcc5ceee30.png)
