### ISSUE TITLE
When TTS is enabled steam connection messages are read out B: 15

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1272]
# Description
The TTS voice reads out the steam auth failure messages when they occur

## Category
BUG

## Detailed Bug Report
Examples which were read out:
![image](https://user-images.githubusercontent.com/4493127/46222759-3f7d3800-c349-11e8-99f0-7cd2f1b1b734.png)

![image](https://user-images.githubusercontent.com/4493127/46222780-4c019080-c349-11e8-8218-99e57c7c9baf.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Enable TTS voice
2. Wait for or force a steam auth failure message
3. Hear TTS voice read it out

**Comment by DooblyNoobly** [comment]
Bounty of 15 usd will be awarded to the contributor on a successful merge of a solution to the reported problem

**Comment by ghost** [comment]
Almost certain that #1586 fixes this by nature since the message isn't even sent to chat anymore.

**Comment by Jibbajabbafic** [comment]
But does TTS still read out the disconnect messages?

**Comment by DooblyNoobly** [comment]
ping me tomorrow @contrarianSpirit when you have a spare moment and we will test on the steam server

**Comment by ghost** [comment]
Confirmed, tested between me and @DooblyNoobly, TTS does not read out any disconnect messages. 

#1586 fixes this issue.
