### ISSUE TITLE
Remove FoV for ghosts

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1274]
# Description

## Category
Feature

## Detailed Bug Report
Ghosts should be able to see everything (including other ghosts) without FoV. (Lighting should still be on)

**Comment by chairbender** [comment]
Just updating this, when this is fixed make sure that the ghosts can also see each other. Currently in #1540  ticket ghosts can see each other only when they are within FOV.

**Comment by chairbender** [comment]
NVM, what I just described is fixed. Ghosts can see each other even when out of FOV. Still need to disable FOV for other things however, as described in the original comment.

**Comment by Coolsurf6** [comment]
Still needs to be added.
