### ISSUE TITLE
Syndicate can't see nuke code once it leaves chat window

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1276]
# Description
Can only see nuke code when spawning, there's no way to see it after it has left the chat window.

Need a note tab for random information like this.

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join as syndicate
2. Spam messages until code is gone
3. Try to blow up the nuke and forget the code 😭

**Comment by ShadyGamma** [comment]
I'll look into it

**Comment by ShadyGamma** [comment]
Additional info:
-remember to synchronize the new tab, so that the Player can always see it, even after logout and login

**Comment by ghost** [comment]
@ShadyGamma Are you still working on this?

**Comment by fomalsd** [comment]
Fixed by Doobs
