### ISSUE TITLE
Shortcut keys are still working when writing in chat

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1277]
# Description

## Category
BUG

## Detailed Bug Report
Shortcut keys are still working when writing in chat, although they probably shouldnt.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick up an item
2. open chat
3. Press 'Q' (item will drop)

**Comment by Jibbajabbafic** [comment]
Always works for changing intent (1 to 4), only works for Q and R when holding item.

I suspect these don't have the same checks that WASD have (AZERTY configuration should be checked too)

**Comment by fomalsd** [comment]
Everyone should check for `UIManager.IsInputFocus` when registering keystrokes (and set it to true while chat is focused).
If everyone does that, issue will be resolved
