### ISSUE TITLE
"AuthTicketCanceled" messages when somebody closes the game B: 15

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1278]
# Description

## Category
BUG

## Detailed Bug Report
When another player leaves the game, a Steam error appears in chat "AuthTicketCanceled".
This should be replaced by a more friendlier message, like "X left the game."

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Two player join the game via steam 
2. One leaves
3. The other sees the message

**Comment by DooblyNoobly** [comment]
Bounty of 15 usd will be awarded to the contributor on a successful merge of a solution to the reported problem
