### ISSUE TITLE
Interactions with NetTab-machines failing after a while

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1279]
# Description

## Detailed Bug Report
Touching Nuke or Shuttle Console doesn't open new tabs after a few rounds, restarting game fixes that

## Steps to Reproduce
Exact steps unknown, encountered on steam test

**Comment by fomalsd** [comment]
it's still a thing
![scr 2018-10-28 23 12 27 2018-10-28 23_16_30](https://user-images.githubusercontent.com/10403536/47621352-8789a900-db07-11e8-8834-c4204a1b1107.gif)

**Comment by DooblyNoobly** [comment]
any thoughts on how to recreate this bug?

**Comment by fomalsd** [comment]
It appeared in a build after one full round as station crew.
Couldn't reproduce it in editor when restarting round artificially though

**Comment by fomalsd** [comment]
is it still a thing?

**Comment by fomalsd** [comment]
Will close it, haven't experienced it since last year
