### ISSUE TITLE
TODO: Find all performance improvements with lighting system B: 100

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1289]
# Description

As the lighting system is now at a visually acceptable state it is time to hunt and down and find all possible performance improvements to reduce gpu load.

## Criteria:
- Identify and perform all possible performance improvements with the Lighting System
- Give profiling data on the PR to provide evidence of improvements for each fix 

Bounty of 100usd will be paid to the contributor on a successful merge

**Comment by moonheart08** [comment]
Just going to drop this here:
https://ncase.me/sight-and-light/
It could be a nice way of making lighting both look even cooler and optimize it at the same time.
