### ISSUE TITLE
TODO: Create paper item B: 25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1290]
### Description

We need a paper item that can be used to communicate Centcomm objectives for 0.4 and also allow players to write notes on the paper if they are holding a pen in the other hand and click on the paper in the hand inventory slot:

### Criteria:

- Create a paper item prefab with a network identity component on it and place it in prefab/resources
- Create all of the necessary components to make the paper item functional
- Determine a suitable way to network sync the notes that is on the piece of paper
- Create the GUI pop up when the player clicks on the item in their hand slot to read the piece of paper
- Allow the piece of paper to be edited if the player clicks on the paper item with a pen in the other hand while the hand with the pen on it is selected

Bounty of 25usd will be paid to the contributor who meets the criteria above on a successful merge.

**Comment by fomalsd** [comment]
And remember: no syncvars for text! It should be visible for only the person that's holding it/standing nearby
It is a good candidate for Net Tab System, but we didn't try using it for items yet

**Comment by DooblyNoobly** [comment]
I think net tab might be too small for a sheet of paper. I don't mind if contributor makes a pop up for this that is draggable and resembles an a4 sheet of paper. Also set the text component to rich text so cool formatting can be used by the players.

**Comment by fomalsd** [comment]
It kind of depends on what we want atm: have it quick and rewrite it later, or spend more time now and have no need to rewrite it later on
IMO net tabs is the future proof way, we'll need to add support for opening them as windows though

**Comment by DooblyNoobly** [comment]
```opening them as windows though```

Yeah if this could open up as a window that would be good. If you are reading a piece of paper you should have your view obstructed as your player is distracted. Also we need to make Net tabs easier to use (I haven't looked at it so not sure how complex it is)

**Comment by fomalsd** [comment]
Done by @DooblyNoobly
