### ISSUE TITLE
Spawning without hair, facial hair, underwear or socks

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1304]
# Description
Character spawns without the above things

See gif:
https://imgur.com/a/dDL8J0H

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Setup character with funky hair and clothes
2. Join server
3. Take off all clothes but don't click/move
4. Click/move
5. All those things suddenly spawn in

**Comment by fomalsd** [comment]
It is also the case for the "just joined" players you see until they turn once
