### ISSUE TITLE
TODO: Shuttle Control UI new elements B: 45

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1327]
# Criteria: 

### Two new GUI elements are required for the Shuttle UI:
 - Shuttle Co-ord read outs. A Vector2Int of the current world position of the shuttle needs to be displayed on the shuttle UI
 - Fuel meter. Atm we just need a GUI element of a fuel meter. When Plasma fuel feature is added to the shuttles then we will work on its functionality.

A bounty of 45usd will be awarded to the contributor on the successful merge of these features.

------------------
#### Suggested approach:

 1) Find the TabShuttleControl prefab and drag it underneath the UIManager so that you can work on it in the scene
 2) Rearrange the UI so that you have some room to add a co-ordinate read out and a fuel meter
 3) Create the new graphics to support the additional elements and store them in Assets/UI/Shuttle_Controls
 5) All data for the new UI elements should be present on the client (fuel is not ready yet). Modify the GUI_ShuttleControl script to update the co-ordinates based off the WorldPosition of the associated MatrixMove component
 6) Remove the TabShuttleControl prefab from the Managers tree and apply the changes to the prefab (Applying them while it is in the tree will merge the TabShuttleControl with the Managers prefab and it will break everything)
 7) remove the prefab from the hierarchy, jump on a shuttle and test

**Comment by dapocalypse** [comment]
Ill do this one

**Comment by dapocalypse** [comment]
Actually hand this off to someone else

**Comment by DooblyNoobly** [comment]
Increased bounty from 25 to 45

**Comment by kaffo** [comment]
Started some work on this, nearly done pretty much. Guess I'll self assign and finish over the weekend
