### ISSUE TITLE
TODO: Connector Port for Plasma tank in shuttles B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1328]
# Criteria:

### Plasma canisters are required to fuel the shuttles:

 - Create the atmos connector port prefab that will be placed on the floor of the shuttle near the engines
 - Create the Tile asset for the connector port and add it to the tilemap palette
 - Create the connected to port function for all canisters ensuring the sprites change to show that the canister is connected
 - Create the connecting action when clicking on the canister with a wrench in the players hand and the canister over the connector port

A bounty of 50usd will be awarded to the contributor on the successful merge of these features.

-------------------
### Suggested approach:

Connector Port prefab:
1) Find a prefab that is similar to the connector port (I would use the AirVent prefab). Drag it into the hierarchy. With the item selected choose GameObject --> Break Prefab Instance from the menu
2) Rename the gameobject to AtmosConnectorPort and remove any unwanted components from the gameobject (If you used the AirVent then remove the Animator etc)
3) Find the connector port sprite from the sprite sheets found in Assets/Textures/Obj/atmospherics/ folders and drag it to the spriterender
4) Drag the AtmosConnectorPort object from the hierarchy and into the Assets/Resources/Prefabs/Objects/Atmos/ folder to create a new prefab.

Connector Port Tile Assets:
1) Navigate to the Assets/Tilemaps/Resources/Tiles/Objects/Atmos/ folder. Right click anywhere in that folder and choose 'Reveal In Finder'
2) Duplicate the AirVent.asset file and rename the new file to AtmosConnectorPort.asset
3) Go back to the unity editor and click on the new tile asset in the folde
4) In the Object field, drag and drop the new AtmosConnectorPort prefab and tick the box next to Rotatable
5) Open the tilemap palette: Window --> 2D --> Tile Palette
6) Change the category to Objects and drag the AtmosConnectorPort.asset file into an empty slot
7) Save the project 

Mapping:
1) Map the port to any pilotable shuttle by changing the Active Tilemap to the intended shuttle and using the paint tool to paint the port in
2) Map a Plasma canister (from the Canisters and Tanks category on the Tile Palette) ontop of the connector port. We do not have pull item feature working at the moment so we need to have the canister ontop of the connector port for further development
3) Map a wrench somewhere nearby

Scripting:
1) Create a new script AtmosConnectorPort.cs and add it to the Connector prefab (then apply the prefab changes if you are doing it from the hierarchy)
2) Wait for @krille90 to merge the canister scripts from atmos branch (should be within next 2 weeks from the date of this issue)

_We will use the AtmosConnectorPort script with the matrix to determine if the canister is positioned over it when a player clicks on the canister with a wrench in hand_

3) Check the Canister scripts to see if they derive from InputTrigger, if they don't then change them (Replacing NetworkBehaviour with InputTrigger is fine because InputTrigger derives from NetworkBehaviour)
4) Override the Interact method from InputTrigger and create a condition to check the matrix for any components of AtmosConnectorPort at the position of the Canister **on the server!**. If there is a AtmosConnectorPort component found then check to see if a canister can be connected to it and continue to finish the state change and sprite changes. See PickupTrigger.cs for an example on how things can be triggered on the server: https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/PlayGroups/Input/Triggers/PickUpTrigger.cs
5) Then you need to sync the connected state and sprites from the server to the clients. You can do this with Syncvars, Netmessages or RPC's: https://docs.unity3d.com/Manual/UNetActions.html

Canister Modifications:
_For each canister in Assets/Resources/Prefabs/Objects/Canisters/ you will need to make these changes:_
1) Drag the prefabs into the heirarchy to work on them
2) Duplicate the sprite child object and rename it ConnectorSprite
3) Find the connected pipe overlay sprite and add it to the new sprite renderer (atmos_11 found in Assets/Textures/Obj
4) Set the order in layer field on the new SpriteRenderer a bit higher then the canister (canister is at 0, so put new SpriteRenderer on 1 or 2). This makes sure that it does not get drawn under the canister sprite
4) Turn off the sprite renderer as we will toggle it with the state change
5) Add a bool in the Canister script that can be synced (you can use sync var with a hook for the time being and just change the bool on the server whenever the canister is secured. This will automatically sync with other clients. The Hook is the method to call on a change [SyncVar(hook="MethodName")]. Remember the method has to accept a bool as a parameter for the hook call to work
6) Cache the spriterender on the Canister script and toggle the SpriteRenderer.enable bool based on the SecuredToPort bool
7) Apply the changes to all of the prefabs
8) Remove the prefabs from the heirarchy, start the game, pick up a wrench and test it out to see if it works!

**Comment by dapocalypse** [comment]
Im working on this and im waiting on krile

**Comment by krille90** [comment]
@dapocalypse Still interested?

**Comment by dapocalypse** [comment]
Yea lol

**Comment by chairbender** [comment]
@dapocalypse still working on this?

**Comment by dapocalypse** [comment]
Yea, I've hit a roadblock though

**Comment by JaytleBee** [comment]
@dapocalypse it's been like half a year, are you still working on this?

**Comment by JaytleBee** [comment]
@dapocalypse has given me permission to work on this so I'll do that

**Comment by Aranclanos** [comment]
doing pipenets, taking over this issue

**Comment by chairbender** [comment]
@Aranclanos looks like you are working on #1933 , are you also working on this?

**Comment by Aranclanos** [comment]
this one is technically done, but since I did 10 times what the bounty asks theres a lot of polishing needed until its at a standard that I'm happy with
and I started doing pipenets without realising this bounty was related to it

**Comment by DooblyNoobly** [comment]
@Aranclanos is this still going to be part of your pipenets work? I'll need this done before 0.4 beta release so increasing bounty and adding high priority tag.

**Comment by Aranclanos** [comment]
wait no its finished
