### ISSUE TITLE
TODO: Shuttle fuel system B: 70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1329]
### Now that #1327  #1328 has been completed this job can begin.

# Criteria

### The shuttles can only operate if there is sufficient fuel available:
 
- Monitor fuel levels before and during space flight
- Stop the shuttle if fuel runs out
- Update Fuel Meter GUI to reflect current fuel levels
- Subtract plasma gas from the canister while flying the shuttles
- Test in multiplayer with 2 clients

-------------------
### Suggested approach:

Scripting:
_We need a component that can be added to the parent of the shuttle matrix that can monitor and control the fuel levels in the shuttle_
1) Create a new script and name it ShuttleFuelSystem.cs and place it in the Assets/Scripts/Shuttles/ folder
2) Derive the script from *ManagedNetworkBehaviour and add the UnityEngine.Networking using directive

_*ManagerNetworkBehaviour has a special update override that is cheaper to run then MonoBehaviour.Update() and it also derives from NetworkBehaviour. Make sure that you call the base.OnEnable and base.OnDisable methods if you choose to override them in your script (Or else UpdateMe() won't work)_

3) Create some fields that we will use to make the fuel system work:
  - Add a Private MatrixMove field (Get the component to assign to this field in Awake())
  - Add a Public AtmosConnectorSlot field ( drag the atmos connector slot for this shuttle to this field in via the inspector (Don't forget to save the scene after you do this!))
  - Add a Public Float named FuelLevel (we will need to sync this variable with the one from the server. You need to determine how you will do that, you can use a NetworkMessage and send every second or on every event or you can turn the FuelLevel field into a SyncVar and create a hook for it and only assign a value to it on the server every second.

4) Open the MatrixMove.cs script and add a field for the ShuttleFuelSystem. 
5) On the MatrixMove script add some conditions so that flight cannot start if the FuelLevel from the ShuttleFuelSystem component is 0. Also monitor the levels so that if the level ever reaches 0 in flight then stop the movement
6) On the GUI_ShuttleScript you now have access to the ShuttleFuelSystem through the MatrixMove reference so use the FuelLevel data to update the FuelLevel meter that was created in #1327 
7) On the ShuttleFuelSystem script create the logic to monitor the gas level in the connected Plasma Tank. You do this by having the AtmosConnectorSlot.cs component reference the connected Plasma Canister (Canister script is being completed currently by @krille90  and is coming in the Atmos merge soon)
8) Do all your calculations in the UpdateMe override (You need to override it: `public void override UpdateMe()` <-- This now replaces your Update() method and is a lot cheaper on the CPU)
9) Add some validation checks to make sure the gas in the canister has enough plasma
10) Start a game, connect a plasma tank and try to fly the shuttle!

Contributor will receive a bounty of 70usd on a successful merge of a solution that satisfies the criteria above.

**Comment by DooblyNoobly** [comment]
Looking for contributors now for this job

**Comment by mazuninky** [comment]
@DooblyNoobly I will try to implement this feature
