### ISSUE TITLE
TODO: Create a command access only shuttle and dock B: 25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1330]
# Description

_If the mining shuttle ever gets stranded or lost then there needs to be a backup shuttle to go and either recover it or recover the stranded miners. Create a new shuttle on OutpostStation and park it near the bridge:_

### Criteria:
 - Create a new shuttle and place it near the bridge
 - Map a dock on the station so that people can access the new shuttle
 - Consider having command only access to the airlock

----------------

### Suggested Approach:

 1) Find the mining shuttle and duplicate it in the hierarchy
 2) Change the root gameobject name to Shuttle3(Command)
 3) Change the second gameobject in the hierarchy from CargoEscapeShuttle to CommandShuttle
 4) Position it near the bridge
 5) Using the TilePalette (Window --> 2D --> Tile Palette) modify the bridge and map out a dock with airlocks for the new shuttle (make sure you have Station selected on the TilePalette before you start working)

**Comment by DooblyNoobly** [comment]
Updated TODO to bounty:

A bounty of 25usd will be awarded to the contributor on the successful merge of these features.

**Comment by dapocalypse** [comment]
I du dis
