### ISSUE TITLE
TODO: Mapping: Lights, Emergency Lights, Light Switches and APCs B: 160

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1336]
# Description

We need to finish mapping all of the light bulbs (most are already done), the light switches (which require manually offsetting the child sprite object of each light switch to face the room that it is used in, the emergency lights and all of the room APC's.

As we cannot do automated light discovery yet for APC's (this is coming after 0.4.0) we will also need to manually reference the rooms lights to the APC's. We can do this easily by referencing the light switch as the light switches do auto discovery.

### Criteria (for OutpostStation):

 - Assess all current lights and add any new ones that are required
 - Add light switches to all of the rooms
 - Manually adjust the localPositions of the child sprite objects for the light switches so that they are offset and closer to the room that they are intended to be used from (this allows the light discovery system to work and also prevents players from toggling light switches from other rooms
 - Map emergency lights in common areas (main halls and departments)
 - Map all of the required room APC's
 - Alter the APC script and add a new field that will accept the LightSwitch trigger (make it an array field so you can add multiple light switches if need be)

#### Note: Later the referencing of the light switches is important, later on lights will be turned on/off or dimmed based on APC power

A bounty of 160usd will be awarded to the contributor on the successful merge of these features.

**Comment by DooblyNoobly** [comment]
Bounty increased from B60 to B160

**Comment by Bod9001** [comment]
am Currently working on this
