### ISSUE TITLE
TODO: Emergency Light activation conditions B: 35

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1337]
## This job can only be attempted once #1336 is completed

# Description

 - Emergency lights need to be toggled via the APC based on some conditions:
 1) Complete power loss
 2) Fire Emergency

### Criteria:

 - Reference the emergency lights to the respective APC's
 - Allow emergency light activation from the Fire Alarm switches
 - Toggle emergency lights if all power has been lost for that APC or the APC is switched off

**Comment by DooblyNoobly** [comment]
A bounty of 35 usd will be rewarded to the contributor on a successful merge.

Please note: You may need to create the switch logic for the fire alarm panels (I have not checked if that is implemented yet)

**Comment by dapocalypse** [comment]
claim

**Comment by DooblyNoobly** [comment]
Just know that I'll be making changes to powernet stuff today/tomorrow so don't do any scene changes until I'm done with that

**Comment by DooblyNoobly** [comment]
@dapocalypse alright I've finished with making the scene changes and merged them so you are all good to start on this.

**Comment by DooblyNoobly** [comment]
I'm going to make the Fire Alarm stuff a separate bounty. As we need to install all of the fire doors as well
