### ISSUE TITLE
TODO: Mining Prefabs: PickAxe, Lamp, Eva Helmet and Eva Suit B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1338]
# Description

 We need to start creating the basic equipment for the miners to do their jobs and to also adjust the mapping for the mining department.

### Criteria:

 - Create a PickAxe item prefab
 - Create a Mining Lamp item prefab
 - Create the Eva Helmet and Eva Suit and place in mining (by using unicloth and setting the heir string via inspector at edit time)
 - Map sufficient amounts of these items and closets in the mining department above cargo

A bounty of 50usd will be awarded to the contributor on the successful merge of these features.

-----------------

### Suggested Approach:

 - In project files create 2 new folders in the Assets/Prefabs/Items/ folder. Create a mining folder and also place a Resources folder inside the new mining folder: `Assets/Prefabs/Items/Mining/Resources/`
 - In this folder we will be saving our Lamp and PickAxe prefab

#### PickAxe prefab
 - To create the PickAxe find a similiar prefab to duplicate (for example the crowbar)
 - Drag the crowbar prefab from project files to the Hierarchy
 - With it selected go to the menu and choose GameObject -> Break Prefab Instance
 - Now rename the parent gameobject from Crowbar to PickAxe
 - Remove all CrowBar related scripts from the GameObject
 - Find the PickAxe sprite and drag it onto the spriterender on the child Sprite GameObject (spritesheet: Assets/Resources/Icons/Obj/Mining.png)
 - Drag the new PickAxe gameobject from the hierarchy to the folders we created on step one (this turns it into a prefab. You can now delete the pickaxe you were working on from the hierarchy)

#### Lamp prefab
 - To create the lamp find a similar prefab and repeat the steps from the PickAxe prefab walk through but this time change the name to MiningLamp and add the lamp sprite
 - We also need to add a light2D object so the lamp glows. To do this drag the Light2D prefab found in Assets/Prefabs/Semi_Objects/Lights/ and make it a child of the MiningLamp
 - Using the Rect Tool or the Scale Tool reduce the size of the light2d a little bit
 - Drag the new Lamp prefab into ProjectFiles (`Assets/Prefabs/Items/Mining/Resources/`)

#### Eva Suit
 - First drag some UniCloth prefabs to the Stations Objects GameObject and place them in mining. Each UniCloth will become either a helmet or a suit. Make sure the unicloths become children of OutpostStation/Station/Objects gameobject
 - Open the hier.txt file and search for the mining eva suit and helmet strings (we will be cut and pasting them onto the inspector for the unicloths)
 - Decide which unicloths will be your helmets and which will be your suits then cut and paste the relevant hier strings into the Hierarchy field found on the ItemAttributes component via the inspector on the unicloth object
 - When you start the game these uni cloths will turn into the clothing items set via the hierarchy field

#### Additional Mapping
 - Open up the Tile Palette (Window -> 2D -> Tile Palette) and make any adjustments to mining that you think are needed.
 - Add some closets to store the items (you place the items above the closets and they will automatically become the inventory of the closet at round start)

**Comment by dapocalypse** [comment]
Ill do this instead
