### ISSUE TITLE
TODO: Player Health refactor B: 120

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1352]
## Description

The Player health code is very basic and does not consider Toxin, Atmospheric and burn damage.

This TODO is to refactor the current code to incorporate the other various ways of being injured in unitystation and to also provide a way to treat these certain types of health impacts.

### Criteria:
 - Assess the behaviours of HealthBehaviour.cs, PlayerHealth.cs, PlayerHealthReporting.cs and the body part health components derived from VitalBodyPartBehaviour.cs to come up with a simple and clean PlayerHealth system that takes into account Atmospheric and Temperature conditions along with specific body part burns and brute damage. 
 - Implement public methods on the PlayerHealth component to allow the healing of these health attributes
 - Ensure new Health system is Server Authoritative!
 - Update the required UI hud elements to indicate the current state of the LocalPlayers health
 - New system should be easy to read with plenty of comments (think about the next dev who has to interface with your code)
 - Test new system in multiplayer environment with 2 clients connected to test server

A bounty of 120 usd will be rewarded to the contributor on a successful merge.

**Comment by badbon** [comment]
I'll begin this today or tomorrow :3

**Comment by dapocalypse** [comment]
beat me to it

**Comment by Bod9001** [comment]
"Update the required UI hud elements to indicate the current state of the LocalPlayers health"
I assume this would cover Lack of o2/being on fire/being cold 
Those elements as well?
Since currently it's not too clear when taking damage From the environment like spacewalking

**Comment by DooblyNoobly** [comment]
@Bod9001 correct. Some new icons will need to be added to the UI. This is the third iteration of PlayerHealth and hopefully it will be the last for a long time. So @NicholasM10 take extra care to cover everything you would expect to see from it
