### ISSUE TITLE
TODO: Add Player DNA B: 30

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1353]
## Description

Each player will have a unique id to identify their DNA. This TODO is to create a class that can take a unique string that represents the players DNA and also to assign the player a blood type. The system should assign each new player this blood data via the server on new player join.

### Criteria:

 - Create a Serializable class that contains a field for DNA and a Blood Type
 - Define an ENUM for the blood types
 - Create a field on PlayerHealth to store the data

 On the server when player joins:
 - Generate a random DNA string (You can use System.Guid.NewGuid() to ensure a unique GUID that will represent the individuals DNA)
 - Choose a random Blood Type
 - Assign to player
 - Create a String SyncVar on player health with a hook. In that method hook deserialize the SyncVar string using JsonUtility.FromJson<TheBloodDataClassName>(string); and assign the output to the BloodData field on the clients
 - After the server has Generated the random blood data then Serialize the class into a Json string (JsonUtility.ToJson(class)) and assign the output string to the SyncVar so that it syncs across all clients and for new players who join

A bounty of 30 usd will be rewarded to the contributor on a successful merge.

**Comment by dapocalypse** [comment]
Claim

**Comment by fomalsd** [comment]
@DooblyNoobly why should DNA be a SyncVar though? shouldn't it be kept on server only?

**Comment by DooblyNoobly** [comment]
@fomalsd yeah we still have that obstacle of training people how to create net messages. I wonder if we need to focus on some kind of easy to use net messaging api
