### ISSUE TITLE
TODO: Create Bruise Pack and Ointment cream prefabs B: 25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1354]
## Description
 
This TODO is to create the basic prefab objects of the Bruise pack and Ointment cream and to have sufficient quanities of these items mapped in medbay. Functionality of these prefabs will be completed in a later TODO (waiting for #1352 to be completed first)

Reference: https://tgstation13.org/wiki/Medical_items

### Criteria:

 - Create the two prefabs with basic functionality (with CustomNetworkTransform, Pickup Trigger, ItemAttributes and RegisterItem components added) 
 - Add the correct sprite to each prefab (on child spriterenderer objects)
 - Ensure prefabs are placed in a Resources folder
 - Map sufficient quantities of items to Medbay on OutpostStation

Please see https://github.com/unitystation/unitystation/issues/1338 Suggest approach section for an idea on how to easily create new prefabs.

A bounty of 25usd will be awarded to the contributor on the successful merge of these features.

**Comment by etrose** [comment]
I've got everything done except for mapping. Not sure exactly where to map them in med bay or how many would be sufficient.
