### ISSUE TITLE
BUG: Bumping into doors no longer opens them

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1355]
# Description
Bumping into a door does not open it. 

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start a game 
2. Bump into a door

Missing conditions in PredictiveBump on PlayerSync.Client perhaps?

**Comment by DooblyNoobly** [comment]
looks like this is an intermittent bug

**Comment by fomalsd** [comment]
any more details to this? like, did you remove ID from id slot before bumping?

**Comment by DooblyNoobly** [comment]
no, nothing changed from fresh respawn. Try spawning as an engineer as that is what I was running around as last and it was 50 / 50 interaction with doors. Half worked, half didn't.

**Comment by fomalsd** [comment]
couldn't reproduce it on my (pulling) branch. it's somewhat out of sync with develop though.
are you sure you were able to open them by clicking afterwards? (maybe it was a mapping/access issue)

**Comment by DooblyNoobly** [comment]
yep clicking the door works

**Comment by fomalsd** [comment]
Yes, this only appeared after updating to latest develop, looks like it only affects **doors with wiring underneath** them

**Comment by DooblyNoobly** [comment]
Interesting, looks like the GetFirst functions in the Matrix do not check all RegisteredTiles at a position for a component. Just the first one.
