### ISSUE TITLE
TODO: Player light emission B: 65

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1361]
## Description

Whenever a player picks up a light, the light2d sprite that was on the Light item is disabled. A player light handler should then control the light emission that comes from the player when they are holding a light that is toggled on in any of the hand or belt slots. It should also work with helmets that have lights on them (coming in the future)

### Criteria:

 - Create a GameObject on the PlayerPrefab that will handle the control of the Light Emission from the player
 - Create a component/script to handle the behaviour of the player light
 - Add the new script to the root object of the player prefab and derive it from NetworkBehaviour
 - Drag the Light2D prefab onto the new object and add it to a field in the PlayerLightHandler script so that it can be enabled/disabled and the properties of the SpriteRenderer can be changed
 - Create a method that accepts a SpriteRenderer as a parameter (the other light2d sprite from the item)
 - Create a way to detect when a light has been picked up or dropped
 - Create a way to detect when a light has left any of the slots or entered any of the slots where the light emission will be visible
 - Switch the light2D sprite on the player on and off based on the required conditions, also replicate the attributes of the light2D that is being mimicked
 - Sync the behavior over the network (Ask me for help if you get stuck with this one)

A bounty of 65usd will be awarded to the contributor on the successful merge of these features.

**Comment by dapocalypse** [comment]
claim

**Comment by chairbender** [comment]
fyi to anyone, this is up for grabs to be worked on again
