### ISSUE TITLE
TODO: Player drag and drop interaction with machines/items B: 90

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1362]
## Description

We need the ability to drag and drop players to seats, beds and to put players into machines like the cloner. The system should be Server Authoritative. 

### Criteria:
 - Develop a way (new handler component) to detect the click and drag event on a player object
 - Create a component that can react to a drop event that will be placed on any machine item that can be interacted with in this way (chairs, beds)
 - Make sure that any resulting actions are network synced and server authoritative (contact me if you get stick with this one)
- Drag and dropping a player to a chair should buckle that player to the chair

Note: (Bed and cloner behaviours will come in a later TODO)

A bounty of 90usd will be awarded to the contributor on the successful merge of these features.

**Comment by Bod9001** [comment]
One thing to say is,  When in melee combat + A lot of running around It shouldn't trigger when you're moving your mouse around and clicking to hit somebody, 
Since that's quite a frustrating byond issue

Not quite sure how you would prevent that?

**Comment by Fishfish458** [comment]
going to attempt to look into this one a little

**Comment by chairbender** [comment]
sorry for the spam, wrong window.

@Fishfish458 you still planning on taking this on?

**Comment by Fishfish458** [comment]
@chairbender It's been a busy week and I haven't gotten much time to look at it but from what I've gathered.

* there's a form of drag and drop in already but it's restricted to the UI
* I want to turn that into a clientside event that can be used across the whole screen
* after a drag and drop event has occured, send details of item dragged, item dropped at, user distance to server
* figure out a landing point for checking if there's an interaction between the two.
* if no drag interaction, possibly fallback on a normal click interaction between the two

That's pretty much what I figured, though this one might be above my level at the moment.
if anyone wants to look at it for now they can

**Comment by chairbender** [comment]
nice, thanks for the update, I'll leave it alone for now

**Comment by DooblyNoobly** [comment]
Increasing the bounty for this one to B: 90 as it is a high priority

**Comment by DooblyNoobly** [comment]
Looks like no one is working on this atm, removing in progress tag and applied High Priority tag

**Comment by chairbender** [comment]
just for reference, on tgstation buckling does nothing to the character sprite when you're in a metal chair facing in any direction:
![image](https://user-images.githubusercontent.com/1329062/56253480-5c712280-6071-11e9-9baf-69c114e0ffe2.png)

but when it's facing up it puts the chair sprite on top of you (you appear on top of it until you buckle in):
![image](https://user-images.githubusercontent.com/1329062/56253515-862a4980-6071-11e9-8772-9af0c0d9b5fb.png)
