### ISSUE TITLE
TODO: Create a basic APC screen in NetTabs B: 70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1364]
## Description

This TODO requires #1363 to be completed before attempting

We need a new NetTab to be created for the APC screen 
 
### Criteria:

 - Create the APC interaction component
 - Validate interaction attempts on the server
 - Create new NetTab for APC screen
 - Design layout and create the required graphics and text elements for the nettab
 - Update the screen by polling the Powernet simulation on the server (Client apc - request -> Server APC state)
 - Close screen when player moves away

A bounty of 70usd will be awarded to the contributor on the successful merge of these features.

**Comment by Jibbajabbafic** [comment]
Has anyone claimed this? I've been thinking about doing this

**Comment by DooblyNoobly** [comment]
it's all yours Jibby! thanks
