### ISSUE TITLE
Bloodsplats spawn with an offset

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1373]
# Description
Bloodsplats spawn with an offset from their designated position

Most likely a world<->local coords issue

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host from editor and join from client
2. Start shooting one another
![giff](https://user-images.githubusercontent.com/10403536/49991413-e486d480-ff78-11e8-8048-0bc6981f3576.gif)

**Comment by chairbender** [comment]
Looking into this...
