### ISSUE TITLE
Suicide shot does not work

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1376]
# Description

## Category
BUG

## Detailed Bug Report
Suicide shot does not work, instead you just melee punch yourself

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Grab a handgun
2.Try clicking yourself to suicide
![gif](https://user-images.githubusercontent.com/10403536/50006804-d8b20700-ffa6-11e8-9fa2-208b744a4eb4.gif)

**Comment by chairbender** [comment]
I'll take this on since it's a good first issue.

**Comment by chairbender** [comment]
Tested this on the current version of tgstation. This behavior actually matches tgstation:
![nodamage](https://user-images.githubusercontent.com/1329062/50199835-f2857e00-0307-11e9-8e50-ed7d609a5410.gif)

@fomalsd are you sure this is a bug?

**Comment by fomalsd** [comment]
well, we had a working suicide shot introduced a while ago, and now it stopped working for some reason
https://github.com/unitystation/unitystation/blob/6bf425a9adc3a0b742ec2f57ba50db936482418c/UnityProject/Assets/Scripts/PlayGroups/P2PInteractions.cs#L50
didn't know it's no longer a thing on /tg/ though

**Comment by chairbender** [comment]
Just an update on this, I've discovered some other quirks / bugs related to how shooting is working so I'll be taking those on as well as doing a bit of refactoring for how it works.
