### ISSUE TITLE
Able to generate/choose empty name in character editor. Messes up server.

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1377]
# Description

## Category
BUG

## Detailed Bug Report
~~1) Character name generator is wonky and can generate empty firstname and/or lastname~~
![gif](https://user-images.githubusercontent.com/10403536/50007075-9fc66200-ffa7-11e8-878a-9392ef44770c.gif)
2) Joining with empty name messes up server, it doesn't start
![gif](https://user-images.githubusercontent.com/10403536/50007175-02b7f900-ffa8-11e8-85f7-c2bbac0b7f66.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start game and open character editor
2. ~~Keep randomizing names until you generate an empty one~~ Enter space instead of name
3. Apply changes and try hosting a server

**Comment by fomalsd** [comment]
Seems like name generator is fine on latest develop. But if someone finds a way to join with an empty name it will still mess up server!

**Comment by fomalsd** [comment]
Joining with empty name still messes up server

**Comment by donovanhubbard** [comment]
I can do this one.

While I'm validating the character name, are there any other rules we want to enforce? Like first name and lastname?

**Comment by fomalsd** [comment]
I think almost any non-empty name will do for now (like 2-3+ non-digit chars, maybe)
But I find it more important to handle the situation with empty name on server side so that it wouldn't get messed up (last time I checked, joining existing server with empty name generated some game-breaking exceptions on server side and server went unresponsive)

**Comment by donovanhubbard** [comment]
I plan on tackling it on that side as well but I havent looked at it yet. What would be the desired behavior if a null or empty name is passed to the server? Should it assign a name? Prevent the user from connecting?

**Comment by fomalsd** [comment]
yeah, either refuse connection or assign default name (Cuban Pete)
