### ISSUE TITLE
MatrixMove – ships can move with offsets B: 50

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1386]
# Description
Some time ago, due to change of smooth MatrixMove lerping to the custom blocky one, ships can sometimes stop on non-integer positions. This was quickly patched by snapping to grid when ships stop moving.
Now, while shuttles always snap to grid when stopped, they restore the offset when movement is started and keep moving like that.
## Category
BUG

## Detailed Bug Report
  
![2018-12-16 01_37_53](https://user-images.githubusercontent.com/10403536/50048045-4e1af600-00d3-11e9-8f25-d6bd1b35b919.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get on shuttle and start moving on lowest speed, then try stopping when ship isn't perfectly aligned to grid. (should introduce that offset)
2. Turn left or right
3. Start/stop moving to see if you see wiggling like on the gif

**Comment by DooblyNoobly** [comment]
Bounty of 50 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by chairbender** [comment]
ah, matrixmove, my old nemesis

I'll take this on

**Comment by chairbender** [comment]
This IS an issue, but I don't think it's due to it restoring the offset, I think it's due to the rounding caused by clampedPosition, which uses PPRT to round the transform.position of the matrix and often rounds to almost but not quite exact integer values, producing this "wiggling" behavior.
