### ISSUE TITLE
Some character data lost after round restart B: 35

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1395]
# Description
Player becomes a baldie in mankini and striped socks after round restart, name stays the same though
## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start from Lobby as CubanPete char
2. Restart round
3. Look at yourself

![gif](https://user-images.githubusercontent.com/10403536/50337878-55defe00-050a-11e9-8b68-c0ad0dd89f27.gif)

**Comment by Fishfish458** [comment]
I haven't been able to reproduce this one. I am starting as captain, using the nuke, waiting the 30 seconds and on spawn I still have features. This is after building though.

**Comment by Jibbajabbafic** [comment]
Have you started from Lobby or OutpostStation? That could make a difference

**Comment by Fishfish458** [comment]
used build and run and tested, starting from lobby

**Comment by fomalsd** [comment]
certainly reproducible in editor:
https://files.catbox.moe/vbm9vk.mov

**Comment by DooblyNoobly** [comment]
Bounty of 35 usd will be awarded to the contributor on a successful merge of a solution to this bug
