### ISSUE TITLE
Critical clients can still shoot

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1399]
# Description
Clients who are critical and have a gun in their active hand can still shoot. Note that this can only be reproduced after #1376 is merged.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor, connect in client.
2. As client, grab a gun and shoot yourself until you go unconscious.
3. Try shooting while unconscious (listen for the shoot sfx)
![suicide](https://user-images.githubusercontent.com/1329062/50369786-c8be9800-054f-11e9-91a9-6b274abfccf3.gif)
.

Most of the logic related to this happens in PlayerNetworkActions.SetConsciousState. It looks like the host properly adjusts the player's state, but does not communicate that the player is unconscious to the client. Probably just need to add another rpc method which sends this info to the client and updates the client's consciousness state to unconscious.

**Comment by fomalsd** [comment]
I think we had that at some point, these shots are clientside only (fake)

**Comment by chairbender** [comment]
Should also make sure this validation is performed server side
