### ISSUE TITLE
Zooming out fades objects out too early

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1400]
# Description
When using zoom 1, objects begin fading out before the edge of the FOV has been reached.
The difference can be clearly seen in the highlighted areas when comparing zoom 1 and zoom 2:

**Zoom 1**
![unity_rrkqibuetd](https://user-images.githubusercontent.com/4493127/50385345-0ba57a80-06cc-11e9-9010-6c667a7814b9.png)

**Zoom 2**
![unity_ttiaepyagb](https://user-images.githubusercontent.com/4493127/50385347-0d6f3e00-06cc-11e9-96cb-ad4c9a97e246.png)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Use zoom 2, see objects at edge of screen
2. Switch to zoom 1, see those objects begin to fade out

**Comment by NoooneyDude** [comment]
I don't believe this is still a relevant issue?
