### ISSUE TITLE
Throwing  something or putting something on the table does not update characters Sprite properly

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1411]
# Description
If you throw something from your hand your character's Sprite  doesn't update So it is still holding the item you just thrown 
## Category
BUG 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick up something
2. Throw it 
3. Observes sprite

**Comment by Jibbajabbafic** [comment]
Also happens when dropping stuff (on my branch anyways)

**Comment by DooblyNoobly** [comment]
just noticed this now too. Will look into it
