### ISSUE TITLE
Pulling doesn't show an icon to stop pulling B: 30

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1416]
# Description

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pull anything
2. Notice there isn't an icon to stop pulling

**Comment by Spessmen14** [comment]
Tested and confirmed.

**Comment by DooblyNoobly** [comment]
Bounty of 30 usd will be awarded to the contributor on a successful merge of a suitable solution to the reported problem

**Comment by JaytleBee** [comment]
I'll have a look at this one
