### ISSUE TITLE
Can interact with hidden wallmounts

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1426]
# Description

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find a lightswitch in the room, remember its position
2. Get outside the room, stand next to the tile that has the lightswitch on the other side
3. Click the spot where the lightswitch is located

![scr 2019-01-08 14 04 14 2019-01-08 14_21_12](https://user-images.githubusercontent.com/10403536/50827854-b4044180-1350-11e9-99e0-8a5fd6dafb9e.gif)

A serverside check should be in place to refuse object interaction if player is in the range but is not facing(seeing?) wallmount

**Comment by chairbender** [comment]
IMO this info should be added to #1063 and probably doesn't need to be a separate ticket, similar problem and solution. Only difference is wallmounts can be interacted with rather than just moused over while hidden.
