### ISSUE TITLE
TODO: Add Blood, Respiratory and BrainHealth to health system B: 170

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1427]
## Criteria:

- Create a blood system for all living entities that monitors toxin levels and oxygen saturation in the blood
- Create functions to add and remove toxins to the blood system
- Move the bleeding and blood level properties from the health system to the new blood system
- Create a respiratory system for all living entities that monitors the air being introduced to the lungs 
- Create the procedures to stop all breathing and cease life after 3 minutes of oxygen loss to the system
- Create a way that other players can perform CPR on a player who has stopped breathing
- Create a BrainHealth component that can store a brain object
- Create a brain container that is assigned to a connected player or NPC object via a GUID system
- Create brain damage level property
- Create a mental alertness level property
- Make sure all new systems are Server Authoritative
- Update any needed UI on the owner players client
- Implement the right click overall description for players health when observing them

A bounty of 70usd will be awarded to the contributor on the successful merge of these features.

**Comment by dapocalypse** [comment]
can I do this?

**Comment by Jibbajabbafic** [comment]
@dapocalypse Doobly is already doing it
