### ISSUE TITLE
TODO: Allow the ability for players to reclaim their bodies on reconnection B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1429]
## Criteria (requires completion of #1427):

- When the GUID of the brain has been created on the server then communicate this GUID to the client that owns the brain
- When a client connects to the server check first if the last saved GUID in player prefs matches any brains that are on the server by NetMsg request
- Assign the brain if it is found on the server and inform the client
- Update all LocalPlayer, CameraFollow scripts so that client is now controlling the existing Player
- Preform relevant UI bypasses on scene load as a client (I.E Do not show job selection window if the player is reconnecting has played this round before. Instead wait for a response from server before showing the window)
- Update the current state of the  UI Hud for the player if the player is reclaiming a previous body
- Make sure system works with respawning and there are no conflicting issues between previously owned brains

A bounty of 50usd will be awarded to the contributor on the successful merge of these features.

**Comment by JaytleBee** [comment]
> * When a client connects to the server check first if the last saved GUID in player prefs matches any brains that are on the server by NetMsg request

So if the player disconnects, connects to another server (or clears his prefs) he loses the brain permanently? That doesn't really seem elegant to me. Perhaps going by IP would be somewhat better, though a truly elegant solution would probably require a trustworthy username (like ckeys)

**Comment by Bod9001** [comment]
Can't we use steam ID? 
I suppose it would make it so we would have to rely on steam for account management And that would be a pain

**Comment by Jibbajabbafic** [comment]
We could use the account system that's in place already, unsure how secure it is but it'll do for now

**Comment by chairbender** [comment]
I humbly request we hold off on this until #1540 is fixed as it will contain significant changes to how ghosts work.

**Comment by Itsnotjames** [comment]
Working on this with @Aranclanos
