### ISSUE TITLE
Prevent client from pretending to be a different player

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1433]
# Description
NOTE: We are planning on investigating Unity's new networking system when it comes out and when we upgrade, just having this ticket here so we remember to check this.

Currently it looks like it may be possible for a client to pretend to be someone else. In ClientMessage, there's a SentBy field, which (I'm not sure on this 100%) seems like it could be set to some other client's networkinstanceid. For example, this could be used by a malicious client to cause another client to shoot themselves.

We should ensure that this is not possible, which we probably will want to look into AFTER the new networking features are more clear.

Feel free to close this if you know Unity networking and know it's not actually an issue. IDK if Unity has built in features already to prevent this.

**Comment by fomalsd** [comment]
This can be fixed, will look into it after Health and Atmos are in
