### ISSUE TITLE
Shutters should be already closed from start

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1437]
# Description
Currently shutters always start opened and will close after a few seconds (it plays the normal closing animation). This affects things like Atmos, e.g. if the shutter is next to a space tile, the gases from the room will be drained at round start.

## Category
BUG

## Detailed Bug Report
Desired behaviour is that the shutters already start closed (like doors) and don't play the closing animation. Beware that shutters could also start opened, when the "IsClosed"-Flag the "RegisterDoor"-script is not selected.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Look in scene editor at a shutters
2. press Play
3. See how the shutters start opened and will close after a few seconds

**Comment by fomalsd** [comment]
didn't know we had working shutters (but apparently we do)
Also cargo shutter button is invisible from inside due to mapping error:
![default](https://user-images.githubusercontent.com/10403536/51245513-cbaa7e00-197f-11e9-83e9-1e096c87de03.png)
![default](https://user-images.githubusercontent.com/10403536/51245470-a7e73800-197f-11e9-817b-8d6f077df9d3.png)

**Comment by christmoore** [comment]
I've got this nearly complete. Assign?

**Comment by DooblyNoobly** [comment]
all yours

**Comment by christmoore** [comment]
# Changes to ShutterController Animator

## FROM
![image](https://user-images.githubusercontent.com/8658239/51793597-6f6a0a00-2188-11e9-8069-d39a8872a022.png)

## TO
![image](https://user-images.githubusercontent.com/8658239/51793594-6b3dec80-2188-11e9-9831-cfab7d16f8fb.png)


The new 04_shutterClosed and 04_shutterOpen are determined at game start by the IsClosed empty state, which checks the value of *close* parameter and sets the initial state of the door (open or closed) corresponding to the "IsClosed" flag from "RegisterDoor".

This is made possible by triggering the shutter SetState() (through Trigger method) at the object's creation.

![image](https://user-images.githubusercontent.com/8658239/51793641-26668580-2189-11e9-8926-edae862983d4.png)


I will provide use case examples in PR. I am currently documenting these changes and doing a bit of cleanup
