### ISSUE TITLE
Current Performance Bottlenecks B: 70 x 5 (Total B350)

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1442]
# Description
Currently there are 5 performance bottle necks that are affecting the game. 

![image](https://user-images.githubusercontent.com/20813925/51219354-44a7d680-197c-11e9-8976-d69e1ef71805.png)
* GC = Garbage Collection. Anything over 1KB is usually bad

## TODO:
- IMPORTANT: You need to check out the atmos/work02 branch, this is the most up to date branch (not the develop one) so run your diagnostic tests on there and if you provide a solution please PR to it instead of develop
- Diagnose problem areas related to the bottle necks above and provide a solution

This is a seek and destroy job. You need to use the profiler heavily to determine problem areas. If you can, please provide a before and after screenshot of your solution.

### To use the profiler:
To use the profiler you can run it in the editor by going to Window --> Analysis. You can profile a game running in the editor. Down the bottom left change timeline to heirarchy so your bottom window looks like this: 

![image](https://user-images.githubusercontent.com/20813925/51219485-e16a7400-197c-11e9-9882-2a062b66dc33.png)

Use the Profiler.BeginSample Api call to create samples around blocks of code that you think might be causing the problem (the name of the sample will show up in the hierarchy of the profiler and if you see your GC values or high CPU times there, then that confirms that that is the part of the code causing the problem)

https://docs.unity3d.com/ScriptReference/Profiling.Profiler.BeginSample.html <--- to drill down further on problem areas you think might be the cause. Values to look out for are high cpu time and GC amounts

A bounty of B70 will be paid out for each performance bottle neck problem. If you discover a problem but don't have time to submit a PR then let one of us know and we will try the solution you recommend. If it works we will award you the bounty. There are 5 x B70 bounties all up (check the screen shot above, if a bottle neck has GC and CPU issues that is two separate bounties you can claim for it).

**Comment by DooblyNoobly** [comment]
Task 2 is completed with #1448

**Comment by krille90** [comment]
I think this is done now, right?

**Comment by DooblyNoobly** [comment]
@krille90 are the optimizations done for atmos?

**Comment by DooblyNoobly** [comment]
CPU criteria done for task 1: #1489

**Comment by krille90** [comment]
As far as I can tell, but I will doublecheck later.

**Comment by krille90** [comment]
CPU and GC criteria of Atmos should be finished with PR #1555

**Comment by DooblyNoobly** [comment]
^ confirmed Task 3 complete

**Comment by Aranclanos** [comment]
The only task missing is the electrical system GC?

**Comment by fomalsd** [comment]
yeah, it is

**Comment by Aranclanos** [comment]
I think this should be closed now?

**Comment by fomalsd** [comment]
well, there's still 120kb of garbage during powernet updates, so not yet I'd say

**Comment by Emma3DSS** [comment]
Ill take a look at the powernet updates

**Comment by Emma3DSS** [comment]
> well, there's still 120kb of garbage during powernet updates, so not yet I'd say

As of July 21st there is 17.3kb of GC being created by 
Update.ScriptRunBehaviourUpdate and PreLateUpdate.ScriptRunBehaviourLateUpdate

**Comment by fomalsd** [comment]
hm, perhaps it's time to close it and make new issues if something comes up, this one is too broad
