### ISSUE TITLE
Inserting container into chem dispenser while GUI is opened, doesn't update GUI state B: 20

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1444]
# Description

If you open the chem dispenser GUI and insert a container the dispenser net tab GUI does not update the container loaded status and instead shows it as empty. Pressing eject, ejects the container.

Note: use container prefab from project files for testing, just drag it into the scene before playing (make sure to put it under objects on outpost station matrix)

**Comment by DooblyNoobly** [comment]
Bounty of 20 usd will be awarded to the contributor on a successful merge of a solution to the reported bug

**Comment by Fishfish458** [comment]
Going to attempt this one
