### ISSUE TITLE
Damage indicators wrong default value

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1446]
# Description

Your health indicator when you are at zero damage Is supposed to look like this 
![alt text](https://i.imgur.com/LVqLFGU.png  "What it's supposed to look like")
https://i.imgur.com/LVqLFGU.png 

But it looks like this 
![alt text](https://i.imgur.com/9jCjTwD.png "What it looks like")
https://i.imgur.com/9jCjTwD.png 

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Spawn
2.Observ health
3.

**Comment by fomalsd** [comment]
See #816

**Comment by Fishfish458** [comment]
I'm going to look into this one

**Comment by Jibbajabbafic** [comment]
Heartbeat sprite still needs updating

Fishfish is taking a look

**Comment by Jibbajabbafic** [comment]
@Fishfish458 any updates?

**Comment by fomalsd** [comment]
It's done
