### ISSUE TITLE
Clients cannot place things on table (but server can) B: 20

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1449]
# Description
Also see #1236 #951 #573 
## Category
BUG

## Detailed Bug Report
Clients can't place items on table on atmos branch
![gif](https://user-images.githubusercontent.com/10403536/51466530-5ca79d80-1d62-11e9-95d0-03cad3c42def.gif)

**Comment by DooblyNoobly** [comment]
Bounty of 20 usd will be awarded to the contributor on a successful merge of a solution to this bug
