### ISSUE TITLE
Plasma fire should apply damage to objects and tiles B: 50

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1453]
Currently, plasma fire is only for show and doesn't affect objects, player or tiles.

## Criteria

- [ ] Implement a way to apply damage to objects, players or tiles (use already existing ways if possible)
- [ ] Add Health to all things
- [ ] Destroy things when health is 0, e.g. explode plasma containers

**Comment by DooblyNoobly** [comment]
Bounty of 50 usd will be awarded to the contributor on a successful merge of all completed criteria above

**Comment by DooblyNoobly** [comment]
Might require a job for the new damage component.

**Comment by krille90** [comment]
> new damage component

Is there something in the working?

**Comment by DooblyNoobly** [comment]
@krille90 I didn't get a chance to create a TODO for it yet. Havent even had a chance to design the component either. Feel free to do it before I do, I won't get a chance for a few days now.

**Comment by fomalsd** [comment]
is this still worked on?

**Comment by chairbender** [comment]
I can take this on
