### ISSUE TITLE
Windoors aren't opening by walking against them

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1455]
## Category
BUG

## Detailed Bug Report
At the moment Windoors can only be opened by clicking on them, but not by just walking against them.
However, it should also open (just as the normal doors do)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Place a Windoor on the map via the Tile Palette
2. Start the game
3. Walking against the Windoor

**Comment by christmoore** [comment]
To whoever takes it. It has to do with the Register Door script on the WinDoor prefab, specifically the code logic for One Direction Restricted boolean value. Setting *One Direction Restricted* tag to false causes this door to operator as normally - albeit in all four directions which isn't the intended usage.

It's beyond my skills to really contribute any further, but I am interested in the solution. I assume it's this code block within RegisterDoor class:
![image](https://user-images.githubusercontent.com/8658239/51779975-687fc080-20d0-11e9-8d5a-4487be686a63.png)

For a normal door, this would return !isClosed, however the calculation for determining when to send the value at line 38 may not exactly be right...
![](https://i.imgur.com/oEdF8p5.gif)

**Comment by christmoore** [comment]
@krille90  What is the intended use case for these? Are they supposed to be one-way? Also how are they supposed to be oriented for the enter - exit position? In the gif above is the south side the entrance? or northern

**Comment by JaytleBee** [comment]
I've done some investigating here and it seems that the calculation part (line 38) is correct (though I still don't really understand how that works), but the position handed as a parameter is wrong. I've managed to get it working correctly when entering the door tile, but leaving the door tile is a bit trickier (IsPassableAt is a mess!). I'll keep working on it though.

@MrMepper As seen on /tg/station when the doors are closed, they're supposed to only prevent movement through one side of the tile (the side with the door). They actually work like that already on the current branch.

**Comment by christmoore** [comment]
I'm excited to hear how you resolve this!
