### ISSUE TITLE
Change Respiratory system to use Atmos & add pressure damage from atmos to body parts B: 40

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1456]
## Category
TODO

## Description
At the moment, the respiratory system only uses a simple space check to see if the player is breathing or not. This should be changed to be based on atmos values at the current position, i.e. checking pressure, oxygen in the air. Additionally, it should use up some small amount of oxygen and give back CO2.

## Criteria

- [x] The respiratory system only uses a simple space check to see if the player is breathing or not. This should be changed to be based on atmos values at the current position, i.e. checking pressure, oxygen in the air
- [x] It should use up some small amount of oxygen and give back CO2
- [x] Should only happen on the server and details shared with relevant client
- [x] Additionally low and high pressure should cause brute damage to exposed body parts

**Comment by DooblyNoobly** [comment]
Criteria:
- The respiratory system only uses a simple space check to see if the player is breathing or not. This should be changed to be based on atmos values at the current position, i.e. checking pressure, oxygen in the air
-  It should use up some small amount of oxygen and give back CO2
- Should only happen on the server and details shared with relevant client
- Additionally low pressure should cause brute damage to exposed body parts

Bounty of 40 usd will be awarded to the contributor on a successful merge of all completed criteria above.

**Comment by krille90** [comment]
> * Additionally low pressure should cause brute damage to exposed body parts

afaik high pressure will also cause brute damage

**Comment by krille90** [comment]
Will try my luck on this one
