### ISSUE TITLE
Tooltip doesn't show up when mousing over UI

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1464]
# Description
Mousing over UI doesn't show the tooltip for the items being moused over in the player's inventory. It should show the tooltip for whatever item is moused over.

## Steps to Reproduce
1. Launch in editor and host.
2. Mouse over an item in the inventory
3. Note that the tooltip on the bottom left doesn't change to show what is moused over.

![mouseover](https://user-images.githubusercontent.com/1329062/51791454-24380300-2158-11e9-8840-1f6ebf845999.gif)

**Comment by Fishfish458** [comment]
the tooltip feature as a whole should definitely get a second pass into a more generalized form. it should display only the name of the item and possibly seperated from the register object/register item scripts. byond's could give a name for any tile as well which may be a far goal but it would be useful.

![generalized tooltip](https://user-images.githubusercontent.com/47410468/54500053-c7023780-48e6-11e9-9d02-ef9dd6b21b9d.gif)
