### ISSUE TITLE
Moving diagonally into a windoor doesn't cause it to open

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1465]
# Description
You can bump into a windoor from straight on in order to open it, but this same thing doesn't work when bumping diagonally. Windoor should open even when you bump into it diagonally

## Steps to Reproduce
1. Host game in editor.
2. Go to the kitchen where there's a windoor.
3. Try moving into / out of it diagonally.
4. Verify that it doesn't open.

**Comment by JaytleBee** [comment]
As mentioned in #1463 I strongly suspect that this is the cause of the problem (from isPassableTo in RegisterDoor.cs):
```csharp
if (isClosed && OneDirectionRestricted)
{
	Vector3Int v = Vector3Int.RoundToInt(transform.localRotation * Vector3.down);

	return !(to - Position).Equals(v);
}
```
