### ISSUE TITLE
TODO: Turn off lightingsystem on headless server

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1469]
# TODO:

Use the GameData.IsHeadlessServer bool to determine if instance is running in headless mode and if it is then disable the LightingSystem

This will fix the server error:
`1/27/2019 12:15:24 AM: RenderTexture creation failed. 'Default' is not supported on this platform. Use 'SystemInfo.SupportsRenderTextureFormat' C# API to check format support. Error 1/27/2019 12:15:24 AM: NullReferenceException UnityEngine.Object.set_name (System.String value) (at <d5e15447e36441d9bc7c5bd494facac1>:0) PixelPerfectRT.CreateRenderTexture (PixelPerfectRTParameter iPprtParameter)`

**Comment by chairbender** [comment]
got held up fixing some perf issue I caused, now I can look at this

**Comment by chairbender** [comment]
@DooblyNoobly give the PR a try: #1485
