### ISSUE TITLE
NRE @ headless server when initiating pull

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1477]
# Description

## Category
BUG

## Detailed Bug Report
<img width="1366" alt="scr 2019-01-28 9 52 15" src="https://user-images.githubusercontent.com/10403536/51819141-6d1bc300-22e2-11e9-9180-654f202e05dd.png">
Pulling works normally except you cannot release things you're pulling aside from pushing them away (if they're solid). Can pull multiple things at once.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join steam server
2. Try pulling things

**Comment by DooblyNoobly** [comment]
This issue still exists.

```
NullReferenceException: Object reference not set to an instance of an object
  at PushPull.CmdPullObject (UnityEngine.GameObject pullableObject) [0x00090] in <74b1398afb464b90acb85e5635e3c64f>:0 
```

**Comment by DooblyNoobly** [comment]
my mistake, its all fixed
