### ISSUE TITLE
Picking up items is problematic on moving ships

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1478]
# Description

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
![gif](https://user-images.githubusercontent.com/10403536/51837250-c09a0b00-22fa-11e9-98fa-155ab0623a35.gif)
1. Join as cargotech, get in the shuttle
2. Start moving with max speed
3. Try to pick up screwdriver

**Comment by chairbender** [comment]
Assigning this to me as it seems to be related to the issues in #1125
