### ISSUE TITLE
SoundNetworkActions are unsecure and unreliable B: 50

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1480]
# Description

## Category
TODO

## Detailed Bug Report
Current implementation of networked sounds allows playing arbitrary sounds at any provided position.
Also it uses RPC, which is unreliable and won't guarantee that sound will be played.
https://github.com/unitystation/unitystation/blob/3dde1b020873ae6011fb6ea583fa66036db35714/UnityProject/Assets/Scripts/Sound/SoundNetworkActions.cs#L7-L10
Plus it actually requires server to have a local player to access this component through, and I suspect this is the reason for #1477 bug
https://github.com/unitystation/unitystation/blob/a4893df4fa6d02dbf4bf77f795bd8051cc91cfca/UnityProject/Assets/Scripts/Objects/PushPull.cs#L98-L99

## What is wanted:
- Server should be the only one initiating all networked sounds.
- Reliable, message based sound play notification (so that network culling could be applied later on)
- A couple of static methods that could be accessed from anywhere, maybe even from SoundManager itself: 
`NetPlaySound(name, pos)` and `NetPlaySound(name, gameObject)`,

**Comment by JaytleBee** [comment]
> Also it uses RPC, which is unreliable 

Do you have a source for that? I'm not a unity expert but I went through a few pages of google results and all of them indicated that ClientRpc calls are sent on channel 0 by default, which is reliable. Though I *really* don't know much about this, so please do correct me if I'm wrong. [Source (kinda)](https://docs.unity3d.com/Manual/UNetActions.html)

**Comment by fomalsd** [comment]
@JaytleBee RPC always uses UDP despite explicit "channel=0" setting, which is likely a bug that has never been fixed in uNet. We encountered this a lot when using RPC in health, position (including PushPull), UI updates, it always turned out wonky. It was also hard to reproduce these bugs because they were rare and random, mostly only popping up in real playtests. After rewriting these systems into netmessages all the random bugs were gone.

**Comment by DooblyNoobly** [comment]
Bounty of 50 usd will be awarded to the contributor on a successful merge of a solution to this request
