### ISSUE TITLE
Try splitting code into separate assemblies

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1484]
# Description
Try splitting 
- Network (messages etc)
- UI (tabs etc)
- Tilemaps (+Atmos)
- Transform (CNT, MatrixMove)
- Electricity
- Health
- Sound (+TTS)

into separate assemblies using [asmdef](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) and see how it affects compile time

**Comment by christmoore** [comment]
I'd like to take a whack at this. Seems simple enough 

Just for clarification - when we refer to compile time, are we talking about time to build? Time from clicking play and running from editor mode? I'm new to unity so I need to understand what's being referred to here.

**Comment by fomalsd** [comment]
`Time from clicking play and running from editor mode`
Yes, exactly

**Comment by chairbender** [comment]
might be best to wait until we upgrade to 2019, as it introduces incremental compiling

**Comment by RedlineTriad** [comment]
Closing this as it will likely be a more incremental thing rather than a single large refactor.
