### ISSUE TITLE
Bug Discovery Bounty (B: 30 for 3 x Bug Reports)

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1496]
# Description
For the next 2 weeks we are focusing on finding and resolving as many bugs as possible before pushing on with the rest of the 0.4 scope. For every 3 bugs found we will pay out a bounty of 30usd.

## TODO
This is very simple. Locate and report 3 bugs by making detailed issues on our GitHub and you will receive the bounty. Please post links to your bugs in the comments below. If you are not on our discord then also attach your paypal address in the comment.

### Notes
Also, it’s worth mentioning that minor, cosmetic, or poorly formulated bug reports will most likely be rejected. If you want to receive the bounty make sure your reports sound right, in order to help us move the project forward to a better state.

**Comment by DiscountVee** [comment]
https://github.com/unitystation/unitystation/issues/1501  https://github.com/unitystation/unitystation/issues/1499 https://github.com/unitystation/unitystation/issues/1497

**Comment by hecksadecimal** [comment]
#1503 #1502 #1500 #1498

**Comment by hecksadecimal** [comment]
#1506 #1505

**Comment by DiscountVee** [comment]
https://github.com/unitystation/unitystation/issues/1507 https://github.com/unitystation/unitystation/issues/1508 https://github.com/unitystation/unitystation/issues/1504

**Comment by hecksadecimal** [comment]
#1509 #1510 #1511

**Comment by DiscountVee** [comment]
https://github.com/unitystation/unitystation/issues/1514 https://github.com/unitystation/unitystation/issues/1512 https://github.com/unitystation/unitystation/issues/1513

**Comment by DooblyNoobly** [comment]
Ok thank you all for the submissions. We are putting this bounty on hold now to go through and plan bounties to actually fix them. Will announce when this job is posted again.
