### ISSUE TITLE
Missing map objects and crash after round restart

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1498]
# Description
After allowing a round to run to the end of the timer and then restarting, various map objects disappear in the new round. A few minutes later unitystation crashes.

## Category
BUG

## Detailed Bug Report
**Build**: https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

**output_log.txt + error.log**: https://gist.github.com/hecksadecimal/073f34fc5e91ecb246d86a0313955957
**crash.dmp**: https://www.dropbox.com/s/15czd8z6v7zmp9k/crash.dmp?dl=0

On a fresh install of Unity and a yet unaltered fork of Unitystation, building and running the project behaves as normal for the first round after launch, but after the time runs out and a second round automatically begins, all the doors are missing, animals are missing, the vast majority of game objects that can be interacted with in some way are missing. After exploring around the stripped station for a while and roaming to around where the Nuke spawns, the game crashed.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behavior:
1. Build and run
2. Start game (localhost) 
3. Join and wait for round timer to end
4. Join next round without closing down unitystation

**Comment by chairbender** [comment]
for me, it crashes immediately on round restart when running as host in editor

**Comment by chairbender** [comment]
Nvm, that is due to a DIFFERENT issue (crashing when loading outpoststation). Once I git reset --hard, I could reproduce this issue as described.
