### ISSUE TITLE
Mashing the start button on the nuke ops shuttle ui makes it phase through walls

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1499]
# Description
When I mash the start button on the shuttle control for nuke ops, the entire shuttle phases through walls
## Category
BUG

## Detailed Bug Report
The nuke ops computer ui, to control the shuttle if you push the lever forwards to fly, and then start mashing the start button when you bump the station, your shuttle start phasing through walls
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Go to the shuttle console in nuke ops shuttle
2.Open the console, turn on the lever to max and then fly to the station till you hit a wall
3.Without turning off the throttle, start mashing start and you and the shuttle will be phasing through walls

**Comment by DiscountVee** [comment]
![screenshot 2019-02-05 02 33 35](https://user-images.githubusercontent.com/28511784/52248468-f63c8680-28ee-11e9-8def-5b26ffc85e57.png)

**Comment by fomalsd** [comment]
if someone wishes to destroy their ship that way then it's fine
