### ISSUE TITLE
Wires exposed under floor tiles via right click menu B: 25

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1500]
# Description
When right clicking on the floor, you are able to see where a wire is without first prying up the floor panel.

## Category
TODO

## Detailed Bug Report
**Build**: [d5b5627](https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5)
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

Can't really call this a bug on its own, an implementation of the t-ray scanner would make for a better way to view where wires are once that's coded in. When that happens, wires that are under floor tiles shouldn't be shown in the right click menu. That goes for anything else that might be hidden under a tile as well, such as pipes, bot nav beacons, or more important potential future items like the smuggler's satchel. 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start unitystation
2. Right click on floor

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug
