### ISSUE TITLE
Selecting a color for facial hair and normal hair locks the menu

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1501]
# Description
Selecting facial hair color as a female sex will lock you into the color panel, unable to click anything else
## Category
BUG 

## Detailed Bug Report
If you select the facial hair color selector, pressing cancel or apply does not work, and you cannot click on anything else
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. click on character setup
2. Change sex to female and click on facial hair color selector
3. You are now locked in and can pressing buttons does not work

**Comment by DiscountVee** [comment]
actually male or female it does that

**Comment by DiscountVee** [comment]
AND IT WORKS WITH ALL HAIR

**Comment by Fishfish458** [comment]
Working on this one
