### ISSUE TITLE
Welding fuel tanks and atmos canisters cannot be grabbed and dragged B: 25

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1503]
# Description
The welding fuel tank can be pushed around, and trying to grab it causes the grab sound to play, but you are unable to pull the object.

## Category
BUG

## Detailed Bug Report
**Build**: [d5b5627](https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5)
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

This is a pretty critical feature for the majority of ss13 round types and general gameplay. Being able to quickly move a fuel tank to somewhere needed, either to fight a blob or to cause an explosion, is an indispensable gameplay asset. 

Edit: Effects atmos gas canisters too.
 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run unitystation
2. Join server
3. Attempt to grab a welding fuel tank

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug
