### ISSUE TITLE
Opening and closing lockers on your character make you lose 02 B: 35

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1504]
# Description
Opening and closing lockers while you're inside them makes you get o2 signal for suffocation
## Category
BUG

## Detailed Bug Report
If you stand in a locker and then click on the locker fast to open and close you will get an o2 signal and start suffocating.
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Open a locker and stand in it
2.Start clicking fast on the locker to open and close it
3.Start suffocating

**Comment by DooblyNoobly** [comment]
Bounty of 35 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
Sounds hilarious and I'll look into it

**Comment by coolcat1711** [comment]
Between a mix of fishfish's and my changes, I'm fairly sure that this issue is resolved.

**Comment by DooblyNoobly** [comment]
@coolcat1711 I just rebuilt the steam clients and pushed them to steamworks. Log in and test it out. If it's fixed report back here and I'll split the bounty.

**Comment by coolcat1711** [comment]
![unitystation issue 1504](https://user-images.githubusercontent.com/3880412/54009834-5e72c800-413a-11e9-920d-a575b25709bb.gif)

**Comment by DooblyNoobly** [comment]
cool, looks like that flashing bug has been fixed too (where you would appear, disappear and reappear again after opening closet)
