### ISSUE TITLE
Add ability to switch intent by clicking specific icons B: 25

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1505]
# Description
When you click on an intent square it only cycles your intent instead of selecting the intent you're attempting to click on.

## Category
TODO

## Detailed Bug Report
**Build**: [d5b5627](https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5)
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

In tg codebases you are able to click on a specific intent to switch to that intent in the UI. This feature is missing from unitystation. The layout of the UI implies that tg's UI behavior is to be expected.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run unitystation
2. Join game
3. Click intent boxes

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this request
