### ISSUE TITLE
Player variable speed support + ability to toggle walk and run B: 90

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1507]
# Description
Walk and run switch does not slow you down when you switch to walk
## Criteria

- [ ] Add variable speed support for PlayerSync
- [ ] Add support for walk/run switching
- [ ] Add ability to crawl in crit

## Detailed Bug Report
If you click on the walk/run button you don't slow down or speed up
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Go into the game, spawn in
2.Click on the walk/run switch
3.See that it does nothing

**Comment by DooblyNoobly** [comment]
Bounty of 35 usd will be awarded to the contributor on a successful merge of a solution to this request

**Comment by fomalsd** [comment]
Note that this would essentially require adding variable speed support for PlayerSync

**Comment by DooblyNoobly** [comment]
After further assessment 90 usd will be applied to this bounty.

**Comment by fomalsd** [comment]
Giving this a go
