### ISSUE TITLE
Holding a piece of clothing in hand and clicking anywhere starts saying [Inventory] Slot is full! even if said slot is not full B: 25

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1508]
# Description
Holding a piece of clothing in hand and clicking anywhere starts saying [Inventory] Slot is full! even if said slot is not full
## Category
BUG

## Detailed Bug Report
Holding a piece of clothing in hand and clicking anywhere starts saying [Inventory] Slot is full! even if said slot is not full. Whether it is suit or hat, doesnt matter
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Take an item of clothing, you can take off the clothing on your character or not, doesnt matter
2.Click with that article of clothing anywhere on the screen 
3. See that it says [Inventory] Slot is full! even if slot is not full

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
looking into this one now
