### ISSUE TITLE
Add ability to open radio chat and department chat with keybindings

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1510]
# Description
When attempting to local chat, no text is displayed. Radio and department chat buttons do not even bring up the text entry box.

## Category
TODO
## Detailed Bug Report
**Build**: [d5b5627](https://github.com/unitystation/unitystation/commit/d5b56271e1390db3337adb9171770526b01901d5)
**Unity Version**: 2018.3.4f1Personal
OS: Windows 10 Pro x64

This one seems pretty critical. Unsure at this point if it effects connecting to a server that isn't localhost, but even if it only does effect localhost client-servers it is a glaring issue.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run unitystation
2. Join round
3. Attempt to talk using any of the bound chat keys

**Comment by DooblyNoobly** [comment]
`When attempting to local chat, no text is displayed.` can I get a little more detail here. So chat box popped up and you typed in some text but nothing showed up on the left in the chat window? Also did you notice any critical errors in console?

**Comment by DooblyNoobly** [comment]
`Radio and department chat buttons do not even bring up the text entry box.` which buttons?

**Comment by hecksadecimal** [comment]
Default binding for Radio chat is 'Y' and the default for Department chat is 'U'. They don't bring up anything, but pressing 'Enter' or 'T' brings up the localchat text entry. Typing something there and pressing enter doesn't add anything to the text box in the top left, but it does cause the small speech bubble indicator to appear over the character's head.


What I mean by the text not displaying is, the chat box is in the top left of the window and I see text there from station alerts and looking at/interacting with things, but I do not see anything from localchat or from the radio. 

Attempting to localchat produces the following error:
```
NullReferenceException: Object reference not set to an instance of an object
ChatEvent..ctor (System.String message, UnityEngine.GameObject speaker, ChatChannel channels) (at Assets/Scripts/Chat/ChatEvent.cs:59)
PostToChatMessage+<Process>d__3.MoveNext () (at Assets/Scripts/Messages/Client/PostToChatMessage.cs:19)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<>c__DisplayClass2_0`1:<RegisterHandler>b__0(NetworkMessage) (at Assets/Scripts/NetworkManagerExtensions.cs:48)
UnityEngine.Networking.ULocalConnectionToServer:Send(Int16, MessageBase)
ClientMessage:Send() (at Assets/Scripts/Messages/Client/ClientMessage.cs:19)
PostToChatMessage:Send(String, ChatChannel) (at Assets/Scripts/Messages/Client/PostToChatMessage.cs:97)
ControlChat:PlayerSendChat() (at Assets/Scripts/UI/ControlChat.cs:130)
ControlChat:Update() (at Assets/Scripts/UI/ControlChat.cs:75)
```

**Comment by DooblyNoobly** [comment]
Are you on latest develop?

**Comment by hecksadecimal** [comment]
Yes.

**Comment by DooblyNoobly** [comment]
Ok thanks

**Comment by Jibbajabbafic** [comment]
This is my bad, I added keybindings for radio chat and department chat but didn't add the functionality to the chat

**Comment by Jibbajabbafic** [comment]
Local chat with T works fine, I'm gonna have a look into adding the other functionality
