### ISSUE TITLE
Welding Fuel Tank has two 'pull' entries B: 25

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#1511]
# Description
Right clicking on a welding fuel tank shows dual entries for the pull action. One of them, the default for the pull hotkey, does not work.

## Category
BUG

## Detailed Bug Report
![image](https://user-images.githubusercontent.com/20251491/52251903-7baf3f00-28cd-11e9-91f7-d63a7b6dfb75.png)

Related to #1503 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run unitystation
2. Join round
3. Right click on welding fuel tank

**Comment by Fishfish458** [comment]
I think this issue is actually related to #1513 and #1503 as well.
Both atmos_05 and weldingtank prefab have both a "push pull" script as well as an "object behaviour" script, object behaviour is an extension and is adding another pull method/running ctrl click twice

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
I'll work on this one

**Comment by Fishfish458** [comment]
On second thought, someone else should probably take this one. I am not too familiar with object behaviour and pushpulls role but i know that was a recent one.
