### ISSUE TITLE
pressing E and clicking on a cloth slot dupes the icon B: 25

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1512]
# Description
If you press E and click fast on a clothing slot, the icon of the clothing in question duplicates
## Category
BUG 

## Detailed Bug Report
If you mouse over and click on an equipped piece of clothing, then start mashing E and clicking, the item duplicates, one remains in your hand and the other on your character
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Click on an equipped piece of clothing
2.Press E and click together fast while pointing at the clothing slot
3.Duplicate the item

**Comment by Fishfish458** [comment]
I looked into this a little bit and this is happening when slots are being changed quickly no matter the method. It seems that items ARE still being moved but sometimes the sprite doesn't properly update(get removed) afterwards.

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
Going to attempt to look into this one
