### ISSUE TITLE
Red Error when you try dragging a plasma canister that starts lagging your game B: 25

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1513]
# Description
Red Error when you try dragging a fuel canister that starts lagging your game
![screenshot 2019-02-05 05 22 52](https://user-images.githubusercontent.com/28511784/52253119-54289880-2906-11e9-89ae-9f33e9d9357b.png)

## Category
BUG 

## Detailed Bug Report
When you try to move a canister, a red error appears, as seen in the screenshot, freezes your game and then lags it every time you try to move
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Cntrl + click a red plasma canister to pull it as a character

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug
