### ISSUE TITLE
Getting stuck on the cargo shuttle thrusters B: 25

### ISSUE THREAD

**Issue by DiscountVee** [unitystation/unitystation#1514]
# Description
As a character, if you approach and touch
## Category
BUG

## Detailed Bug Report
If you as a character approach the quartermasters shuttle engines, and touch them, you are stuck to them you cant move, but you can throw an item and itd push you as if you're in space, doesnt work if you're vertically adjacent to the thrusters though, like in this screenshot 
![screenshot 2019-02-05 05 28 23](https://user-images.githubusercontent.com/28511784/52253288-43c4ed80-2907-11e9-9820-ccde190419e3.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Be a character and walk up to the thruster
2. You get stuck in the thruster

**Comment by Bod9001** [comment]
this looks like Collision not counting them as station so The game thinks you're floating in space

**Comment by DiscountVee** [comment]
Well if it'd count it as me being in space, when id throw items it would make me fly in the oppposite direction and it doesnt

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
Going to look into this one

**Comment by fomalsd** [comment]
oops, already fixed this one. Inert objects (like thrusters) didn't count as "sticky"
