### ISSUE TITLE
Add ability to toggle internals B: 35

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1519]
# Description
The button on the right side of the UI should toggle your internals on and off when clicked, and show the corresponding state. Currently your internals are always on if you have a mask and a tank in your suit storage, regardless of the button state.

![image](https://user-images.githubusercontent.com/4493127/52411868-0a41dd00-2ad5-11e9-94af-4919a000b8a4.png)

## Category
TODO

**Comment by donovanhubbard** [comment]
I can work this.

**Comment by DooblyNoobly** [comment]
Bounty of 35 usd will be awarded to the contributor on a successful merge of a solution to this request

**Comment by donovanhubbard** [comment]
This is almost done, but I wanted to clarify. I'm storing the internals state in a boolean in Equipment, and it looks like the primary way to set server variables is through PlayerNetworkActions, so I've added 

`[Command]
	public void CmdSetInternalsEnabled(bool internalsEnabled)
	{
		equipment.IsInternalsEnabled = internalsEnabled;
	}`

But what is the best way to read that variable? Do I have a Get command as well?

`[Server]
	public bool IsInternalsEnabled()
	{
		return equipment.IsInternalsEnabled;
	}`

It seems a little odd to be reading the state from a class called 'Actions'. I just want to make sure I'm following the project conventions correctly.

Relevent commit https://github.com/fuele/unitystation/commit/b187f26f5748bca2ec12af313336220cbc04665b

**Comment by DooblyNoobly** [comment]
You can turn IsInternalsEnabled into a SyncVar but you can't have it as a property. So change it back into a field. That way whenever the server updates it the value will change on the clients. It's not secure though as everyone can find out if someone has oxygen on if they write a script to peek on their client but for this I don't think that matters. Later we can turn it into a message if security becomes a concern

**Comment by fomalsd** [comment]
@DooblyNoobly `IsInternalsEnabled` doesn't need to be syncvar, server shouldn't broadcast its value for anyone. 
Above code looks correct. It's how I'd do it

**Comment by fomalsd** [comment]
@fuele also make sure to handle reset of internals button after respawn/restart, so that it doesn't become out of sync with server

**Comment by donovanhubbard** [comment]
Where is the round restart/respawn logic?
