### ISSUE TITLE
Door Access Denied Animation is wrong

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1527]
# Description

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Walk with a role against a door without the right access rights
2. Wrong animation (first red, then green) plays

**Comment by Jibbajabbafic** [comment]
I definitely fixed this issue before and the prefabs were correct. I think the ones present on the map didn't get updated though so may need placing back down
