### ISSUE TITLE
No bullet trails when firing guns, and no projectiles either

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1532]
# Description
When firing guns it appears no bullets or trails are being created. 

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Fire weapon at window
2. Notice no trails or bullets damaging it

**Comment by chairbender** [comment]
I probably just need to check in some meta files to fix this as it's working locally

**Comment by chairbender** [comment]
opening this until someone else can confirm it's fixed

**Comment by Jibbajabbafic** [comment]
All good now!
