### ISSUE TITLE
Refactor how popup tabs are checked B: 25

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1533]
# Description
New popout tabs have to be placed into a hardcoded check to make them popout.

https://github.com/unitystation/unitystation/blob/f9c5597aac500808ad4d67615d89a69f6caab47c/UnityProject/Assets/Scripts/UI/ControlTabs.cs#L426

This isn't ideal because the tabs already have a `IsPopOut` variable to determine this,

![image](https://user-images.githubusercontent.com/4493127/52521815-e9b08900-2c74-11e9-8ed6-0f0fa5611a71.png)

The code should be refactored so this hardcoded check isn't necessary anymore.

## Category
TODO

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this request
