### ISSUE TITLE
Shooting and meleeing windows doesn't do any damage B: 25

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1534]
# Description
When shooting or meleeing a window, no cracks appear. However, throwing DOES damage windows, and some windows on syndicate shuttle are damageable via melee.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor.
2. Grab a gun.
3. Try meleeing and shooting a window and see that no cracks appear.

**Comment by chairbender** [comment]
window damage is a bit messed up right now, also see #1541

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by vlandemart** [comment]
Going to look into this one

**Comment by vlandemart** [comment]
It is done for the most part. Still needs some tests and tweaking, expect it to be done today-tomorrow.
![image](https://user-images.githubusercontent.com/19672958/53225753-15c30580-368a-11e9-80b0-3c7bb7defd02.png)
