### ISSUE TITLE
Client ghosts cannot see each other and ghost can become stuck when corpse is destroyed B: 80

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1540]
# Description
2 client ghosts can't see each other. They should be able to see each other while they are both ghosts.

Additionally, if a player's body is destroyed with the knife and turned into meat, I think the ghost loses the ability to move.

## Steps to Reproduce
1. Host in editor. (You may want to increase the amount of time before a ghost respawns in order to make testing easier, I think you can do this in PlayerHealth.OnDeathActions by adjusting the timeout passed to RespawnPlayer).
2. Join 2 clients from standalone.
3. Get the knife as the host and stand between the 2 clients.
4. Alternate stabbing them left and right evenly so they both die and become ghosts at the same time.
5. Try moving around as one of the ghosts and notice that the other client doesn't see the ghost.
6. Continue stabbing to turn a corpse to meat. Verify that the ghost becomes stuck.

**Comment by chairbender** [comment]
I would suggest possibly splitting ghost out so it is no longer a child of the player gameobject. Basically have the ghost be a separate player for all intents and purposes.

This will probably be a somewhat significant effort, but having it be separate will probably be a simpler approach in the long run.

Also this is kind of a low priority at the time of writing, since ghosts are something you only see for like 10 seconds.

Additionally, some remarks by foma on ghosts:
ghosts code really gets in the way inside playersync
so at the moment ghosts aren't synced on serverside

I can see why ghost has been initially in the same gameobject as player: in byond ghost can return to player's body and player can get revived/cloned, but that can be handled I believe
also ghost keeps player's hair and whatnot, still that can be arranged
proper ghost support would be nice, we were just shoving it under the carpet

**Comment by DooblyNoobly** [comment]
This is a bit of a complex bug so setting at B 50:

Bounty of 50 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by DooblyNoobly** [comment]
Increasing this bounty to B: 80 as its a high priority

Bounty of 80 usd will be awarded to the contributor on a successful merge of a solution to this bug
