### ISSUE TITLE
Window cracks remaining after window is broken B: 25

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1541]
# Description
In title

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Throw a weapon / heavy object on window till it breaks

![scr 2019-02-10 2 57 17 2019-02-10 02_58_58](https://user-images.githubusercontent.com/10403536/52527815-f61dfb80-2cdf-11e9-8c1d-41a5f33834ad.gif)

**Comment by chairbender** [comment]
window damage is a bit messed up right now, also see #1534

**Comment by fomalsd** [comment]
yeah, but I think this one has been around since tile damage has been first introduced (but it wasn't 100% reproducible until health refactor)

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by hecksadecimal** [comment]
Looking into fixing this.
