### ISSUE TITLE
Enabling "Local Positions" tick in Matrix Check spams NREs B: 25

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1548]
# Description
Enabling "Local Positions" tick in `Window` -> `Matrix Check` menu with gizmos enabled produces NREs every frame:
```
NullReferenceException: Object reference not set to an instance of an object
MetaTileMapView+ShowLocalPositionsCheck.DrawLabel (MetaTileMap source, UnityEngine.Vector3Int position) (at Assets/Scripts/Editor/Matrix/Views/MetaTileMapView.cs:107)
GizmoUtils.DrawLabels[S] (S source, UnityEngine.BoundsInt bounds, System.Collections.Generic.IReadOnlyCollection`1[T] checks) (at Assets/Scripts/Editor/Matrix/Utils/GizmoUtils.cs:86)
GizmoUtils.DrawGizmos[S] (S source, System.Collections.Generic.List`1[T] checks, System.Boolean local) (at Assets/Scripts/Editor/Matrix/Utils/GizmoUtils.cs:23)
MetaTileMapView.DrawGizmoLocal (MetaTileMap source, UnityEditor.GizmoType gizmoType) (at Assets/Scripts/Editor/Matrix/Views/MetaTileMapView.cs:39)
```

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start game in editor
2. Make sure Gizmos are enabled
3. Enable "Local Positions" tick
![gif](https://user-images.githubusercontent.com/10403536/52561797-543c0300-2df4-11e9-81f2-481de5af36e4.gif)

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug
