### ISSUE TITLE
Inconsistent diagonal movement facing B: 25

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1550]
# Description
When moving diagonally, the direction the character is facing is inconsistent, such as when moving down + left or down + right, the character will face straight down when moving down + left and will face right when moving down + right

## Category
BUG

## Detailed Bug Report
up+left / down+left should = left face
up +right / down+right should = right face
if character is inhibited by a wall, and can only move up/down, should face up/down.

## Steps to Reproduce

Please enter the steps to reproduce the bug or behaviour:
1. move in a diagonal movement up+right / up+left / down+right /  down+left
2. the direction the character is facing are inconsistent

https://imgur.com/Xo5B97H

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
I'll look into this one
