### ISSUE TITLE
UI elements like pockets and equipment slots don't return on respawn B: 25

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1554]
# Description
Only your hands slots  are present when you respawn

## Category
BUG

## Detailed Bug Report
This results in that you cannot access anything other than your two hands slots 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Spawn in 
2.Kill self
3.respawn 
4.Observe  the lack of UI

**Comment by fomalsd** [comment]
Indeed; it was introduced in #1551

**Comment by DooblyNoobly** [comment]
Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
I'm going to look into this one
