### ISSUE TITLE
Bloodsplats blink at non-snapped position when spawning

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1566]
# Description

## Category
Annoyance

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Make yourself bleed and walk around, preferably slowly
2. Observe

![gif](https://user-images.githubusercontent.com/10403536/53016156-d48de400-3444-11e9-80b4-12753be143a9.gif)

**Comment by fomalsd** [comment]
will be fixed with #1583

**Comment by daalta** [comment]
@fomalsd has #1583 or https://github.com/unitystation/unitystation/issues/2314 fixed the issue?

**Comment by NoooneyDude** [comment]
I couldn't seem to reproduce this. Has it been fixed, or is it scene-specific? Perhaps the smaller blood drip sprites that are now in use just make it harder to see.
