### ISSUE TITLE
Dying without crit state causes character to still be standing around

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1567]
# Description
if the death state is triggered before the player goes into crit, the player character will still be standing around

## Category
TODO

## Detailed Bug Report
The crit state uses methods to cause the character to drop that the death state does not,
death should be able to work independent of if the character goes into a crit state or not.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. In the editor, use Networking > Gib All(server)
2. Notice how the character is still standing around

**Comment by chairbender** [comment]
assigning this to me because I think it overlaps with fixes I'm making in #1240
