### ISSUE TITLE
If a ghost is revived, other ghosts will become invisible

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1569]
# Description
When multiple clients are ghost and one is revived, any other ghost's model will become invisible
## Category
BUG

## Detailed Bug Report
#1540 could possibly fix this issue if it's done correctly, adding in case there is no effect to it.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. have two players die at near the same time
2. watch when 1st dead revives, other player becomes invisible

**Comment by chairbender** [comment]
yeah, recommend working on #1540 first before this
