### ISSUE TITLE
Vending machine can eject things on weird positions

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1573]
# Description

## Category
BUG

## Steps to Reproduce
It's not always reproducible, results are inconsistent.
Try clicking coffee machine in the main hall (host in editor)

![gif](https://user-images.githubusercontent.com/10403536/53075332-d0190800-34e4-11e9-9c04-ed81f744f23c.gif)

Likely has something to do with parenting.
When fixing please also make sure that it still works on moving shuttles as well (syndie shuttle cigarette dispenser)

**Comment by krille90** [comment]
What would be the correct behaviour?

I think it should only spawn atop of the vending machine, right?

**Comment by Fishfish458** [comment]
Should spawn on top but firing them out should stay as a method in some form for hacked or otherwise
