### ISSUE TITLE
Swap and equip buttons incomplete

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1576]
# Description
There are currently swap and equip buttons that exist on the UIManager, they are set as non-active and they're not finished with texturing

## Category
TODO

## Detailed Bug Report
If this is being worked on, the two lines in the if statement in UIManager.cs - SetDeathVisibility
referring to swap and equip must be removed

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Check UImanager for current implementation under Panelhudbottom > equip-hands > equip and swap

**Comment by PerfectTangent** [comment]
is this issue still relevant with the new UI?

**Comment by PerfectTangent** [comment]
closing as this doesn't seem relevant anymore.
