### ISSUE TITLE
Job/occupation player slots don't update at all

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1580]
# Description
When you join it shows all roles are available, no matter if they have been taken already resulting in being able to have multiple captains on a station.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open 2 clients (build and editor)
2. Host with one and connect with the other
3. Join the station crew with both
4. Select a job on one client
5. Notice the job slot doesn't get updated on the other

**Comment by fomalsd** [comment]
You mean the crew counter? I think it stopped working at all

**Comment by Itsnotjames** [comment]
The job slots update for me:

![itvcqcd](https://user-images.githubusercontent.com/28093344/53696001-68898380-3e27-11e9-87fd-143315bb3886.png)

Assistant:
![zofjhy3](https://user-images.githubusercontent.com/28093344/53696017-98388b80-3e27-11e9-8e2c-956cc308b662.jpg)

Bartender (full):
![wd8q5qr](https://user-images.githubusercontent.com/28093344/53696022-a7b7d480-3e27-11e9-9e75-153a34865001.png)

**Comment by Jibbajabbafic** [comment]
Did it update while it was open on the other client then?

**Comment by Jibbajabbafic** [comment]
Looks like the organisation selector is a bit messed up too, didn't notice that before
