### ISSUE TITLE
Refactor Blood splats to spawn via the TMS

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1583]
# Description
Currently, blood splats are spawned via the EffectsFactory as single gameObjects.

In future, these should be spawned on the tile map system (TMS) via the TileChangeManager.

## To Do
- [ ] Create new blood tiles, that chooses from a random blood sprite
- [ ] Blood tiles should be segmented into small, medium and large (like before)
- [ ] Test if the sprites are the same on multiple clients

## Comment 

Do not create a new tile for every blood sprite! If necessary, create a new tile class that takes a list of sprites and when spawning it selects a random sprite. This would reduce the amount of new tiles to three (small, medium and large)

**Comment by fomalsd** [comment]
keep this in mind:
- they should leave bloody footsteps when player steps on them
- if someone is shot in space, bloodsplats should probably still spawn with CustomNetTransform so they would move for some time before either disappearing in space or making station walls dirty

**Comment by fomalsd** [comment]
Also make sure it would still work with mop

**Comment by Jibbajabbafic** [comment]
@krille90 any progress with this?

**Comment by krille90** [comment]
The goal is to turn the script "FloorDecal.cs" to a Tile.
Requirements:

- Choose random sprite from list of sprites
- stackable, floordecals can be above each other
- Above the floor tilemap
- Can have a lifetime 

Affected by this change:
- BloodSplat (Small, Medium, Large)
- WaterSplat
- Ash (Small, Large)

IMO, pipes and wires should also be turned into tiles, but since those have other requirements too, need to be done in a separate issue.

Any opinions, ideas?

**Comment by chairbender** [comment]
This will be done as part of #2314 , suggest closing this.

**Comment by krille90** [comment]
agreed.
