### ISSUE TITLE
Rapid changes to power source breaks electricity

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1588]
# Description
When a power source is toggled quickly( power generator ) some electrical systems stop updating and toggles no longer change input status
## Category
BUG

## Detailed Bug Report
Some rooms still have their lights on while others don't, they still don't update on toggling slowly. APCS are all in the off state
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Rapidly toggle the plasma generator
2. After a short period, all electricity will stop updating

**Comment by fomalsd** [comment]
fixed in #1703
