### ISSUE TITLE
Mobile/touchscreen support bugs

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1591]
# Description
![image](https://user-images.githubusercontent.com/10403536/53626175-f6cdf180-3bfc-11e9-94ed-f944af10431d.png)
Here's a demo of game running on iOS with virtual gamepad that simulates key presses:
https://files.catbox.moe/520q9z.MP4

- Pressing gamepad buttons doesn't consume touch event (player always attempts to face your finger on gamepad), not reproducible w/mouse
- Touch presses duplicate key down events (not reproducible w/mouse)
- Pixel perfect camera is broken, can see texture leakage
- Throwing aim picks the first touch instead of the last one (will throw in direction of your finger on gamepad)
- CommonInput needs rightclick menu activation by holding finger on one spot for around 700ms
- Pressing `Equip-Clothing` button while holding gamepad button will not make gamepad depress

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
Prereqs:
- Not too slow iOS/Android device with at least 2GB RAM (Android 4+, iOS 9+)
- Installed Unity module to support building for your platform
- Installed dev tools for your platform (Xcode/Android SDK)

1. Switch to `ios` branch if you're on iOS, for Android you can stay at latest develop
2. Go to Build Settings and switch platform (takes time!)
3. Build and deploy it to your device (steps vary)

**Comment by fomalsd** [comment]
**These were fixed by removing P3 profile.**
iOS Metal specific:
– space background is black
– FoV edge artifacts
![image](https://user-images.githubusercontent.com/10403536/53734930-4a4e7280-3e7d-11e9-93ad-b5989138da94.png)

**Comment by Injazz** [comment]
crashing on my device right on startup sadly, I'm pretty sure my callstack is already sent to you via TestFlight

**Comment by fomalsd** [comment]
probably low on RAM... how much do you have?

**Comment by fomalsd** [comment]
Here's some profiling data from xcode
<img width="1330" alt="Scr 2019-03-22 в 8 59 40" src="https://user-images.githubusercontent.com/10403536/54803758-db955580-4c81-11e9-9a46-e7d080bba7b2.png">
