### ISSUE TITLE
Two players with help intention should trade places on push B: 50

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1596]
# Description
When two players have help intent, they should be able to pass each other by swapping places when either one or both are moving toward each other.

## Detailed Bug Report
[example](https://imgur.com/0mBmOTz)
Only when both players have help intent enabled should they be allowed to pass each other, any other intent on both parties should result in pushing. moving diagonally will not trade places unless both players are moving diagonally at the same time.
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.  have one player run at another player with help 
2. players should swap places with each other if they are both help and continue their movement

**Comment by DooblyNoobly** [comment]
This will be a bit tricky so adding a B 50 to it

Bounty of 50 usd will be awarded to the contributor on a successful merge of a solution to this TODO

**Comment by chairbender** [comment]
I've messed with movement enough where I think I got the hang of it, taking this on.

**Comment by chairbender** [comment]
Also planning to fix player rotation not staying upright

**Comment by chairbender** [comment]
Pretty sure this should actually be "Help" intent.
