### ISSUE TITLE
open doors are not synced when joining a game B: 35

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1599]
# Description

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start server
2. stand in a door (server player)
3. join as a client
4. Server player stands in closed door (pov from client):

![image](https://user-images.githubusercontent.com/7312905/53685025-7353f380-3d15-11e9-8331-839edc4d2e0d.png)

**Comment by DooblyNoobly** [comment]
Bounty of 35 usd will be awarded to the contributor on a successful merge of a solution to this bug
