### ISSUE TITLE
Hands always swap even if one item is interacting on another

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1606]
# Description
If you have two items in either hand and use them on each other, swapItem will still run, causing the item to change places if one disappears.
## Category
BUG

## Detailed Bug Report
I noticed this when changing how guns work. UI_InteractOtherSlot runs when an object or empty hand is used on an item. Regardless of what action happens, swapitem will still run.

It could be beneficial if this was made into an optional parameter on UI_InteractOtherSlot

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. get a gun and eject the magazine
2. Load the magazine into the gun and notice that the gun has swapped hands
3. This interaction occurs anytime two items are clicked together, however since both slots are full the hands do not swap.

**Comment by Itsnotjames** [comment]
Works for me:
![ezgif-1-f748ae405db5](https://user-images.githubusercontent.com/28093344/53815264-2fd3e080-3fc6-11e9-9a98-fa6bcd029253.gif)

When I click a gun with it's magazine it moves the gun to where the magazine was like you said. Although i'm pretty sure that is the expected behavior.

**Comment by Fishfish458** [comment]
In that instance, swap item is actually still running in the background but because both slots are full it doesn't switch.

The issue comes up with reloading where one item disappears but the other does not. I believe putting items in back packs does it too if you're holding both in your hands

Expected reloading behavior shouldn't swap

**Comment by Itsnotjames** [comment]
Ah you're right, I remember now that the magazine goes into the gun and the gun stays in place. I see the problem now.

**Comment by Fishfish458** [comment]
working on this one now since i'm running into it while working on something else.

My current plan is to make UI_InteractOther return a bool now which will determine if SwapItem will run aftewards since some items (such as stackables and boxes) have different interactions with empty hands
