### ISSUE TITLE
ghost spawns at incorrect position when dying in a locker B: 30

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1608]
# Description
Ghosts currently spawn using the actual location of the player. if someone dies in a locker the ghost will spawn at 0,0,-100

This should be using objectBehaviour.AssumedLocation to grab it's location if they are inside another container.
## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. close a locker on yourself in space and obtain the sweet release of death
2. when you spawn as ghost it will be at 0,0,-100

**Comment by chairbender** [comment]
Would suggest working on #1540 first before this ticket.

there are quite a lot of issues with ghosts that should be mostly addressed in 1540.

**Comment by DooblyNoobly** [comment]
Bounty of 30 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by chairbender** [comment]
This overlaps with my current ticket, taking this on as well.
