### ISSUE TITLE
Emergency light state is not synced with new clients

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1619]
# Description

If emergency lights are activated on the server before you join you do not get their activated state. Therefore the station is dark with no emergency hall way lighting. 

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open steam client and join the server
2. If power generator is on, turn it off and reconnect
3. Notice that the emergency lights are not on

Bounty of 60 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by badbon** [comment]
I think this is my mess so I will try to fix it. 👍

**Comment by chairbender** [comment]
@NicholasM10 any update on this? Still working on it?

**Comment by badbon** [comment]
Ah sorry, you can take over.

**Comment by DooblyNoobly** [comment]
Taking it off in progress and increasing to B 60

**Comment by Aranclanos** [comment]
I'll take a look

**Comment by badbon** [comment]
Uhh yes sorry for dying again, do it.

**Comment by fomalsd** [comment]
Still a thing
