### ISSUE TITLE
Magazine Fusion Cells are forever stuck in the closet container B: 25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1621]
# Description

Fusion Cells that are put into closets on round start seem to be forever stuck in there. 

Gif of the bug:

![2019-03-11 08-28-09 2019-03-11 08_29_48](https://user-images.githubusercontent.com/20813925/54092444-e7f2f600-43d7-11e9-9301-81f1bdeb8f05.gif)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find a fusion cell in a closet
2. Pick it up and throw it some distance
3. Close the closet door

Bounty of 25 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Fishfish458** [comment]
going to check into this one
