### ISSUE TITLE
Pressing E no longer equips wearable items

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1626]
# Description

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Undress
2. Pick up a cloth
3. Press equip button (E by default) to try to equip it

**Comment by Jibbajabbafic** [comment]
**Note to whoever wants to work on this:**

The key to equip was disabled in #1617 

If you want to enable it again just uncomment the following line: https://github.com/unitystation/unitystation/blob/135b322926f87570ddb4c805df206addbfd16409/UnityProject/Assets/Scripts/Input%20System/KeyboardInputManager.cs#L206

You can either modify Equip(), or you might want to use a different function instead as suggested in the Equip() summary.

**Comment by fomalsd** [comment]
can anyone confirm if this is still a thing on latest develop?

**Comment by NextThang** [comment]
I've tried pressing both Z and E and it does nothing. I literally have to click the slot to equip it again.
