### ISSUE TITLE
Game settings reset after each game title change

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1629]
# Description
Each title change forces creation of another settings folder, therefore they reset.
![image](https://user-images.githubusercontent.com/10403536/54139105-b9493f80-4418-11e9-9588-baf3f1fa7188.png)

Perhaps we could print latest commit data in some textfield in Lobby instead of `PlayerSettings.productName`
(and in console as well)

**Comment by Jibbajabbafic** [comment]
This might also be the cause of #1627

**Comment by fomalsd** [comment]
fixed
