### ISSUE TITLE
Items captured by closet containers retain their momentum

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1630]
# Description
If you catch an object flying through the air with a closet, it will retain its momentum when you open it again.

![ffDnkLZrmS](https://user-images.githubusercontent.com/4493127/54158568-a9deec00-4442-11e9-9270-50000811d8c1.gif)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find locker and an item
2. Stand by the locker, open it and get ready to throw the item
3. Throw and quickly close the locker as it passes over it
4. Open locker and watch it fly out

**Comment by Fishfish458** [comment]
I want to look into this one

**Comment by Jibbajabbafic** [comment]
All yours
