### ISSUE TITLE
Clicks not registering occasionally B: 70

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1634]
# Description
Sometimes as both host and client, clicks are not recognized or do not trigger their action.
This behavior can be noticed with items like picking up the screwdriver.
![clickRegister](https://user-images.githubusercontent.com/47410468/54167373-62069780-4437-11e9-84bf-fb8134f661d0.gif)

## Category
BUG

## Detailed Bug Report

Crates and closets are the most noticeable in reproducing the issue however some small items have to be clicked multiple times as well.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. click on crates slowly in multiple places
2. notice how sometimes open/close does not start

**Comment by DooblyNoobly** [comment]
Most of the mouse input code can be found here. This would be a good place to start debugging
https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Input%20System/MouseInputController.cs

This bug will take some time to work out and is an important one to solve so adding a B: 70 to it.

Bounty of 70 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by fomalsd** [comment]
I think I fixed it yesterday, needs more testing though
![GIF](https://user-images.githubusercontent.com/10403536/54263088-e2c4b100-4567-11e9-93d0-886e73c2d956.gif)

**Comment by fomalsd** [comment]
@chairbender sorry, wasn't logged in to github in the evening to self-assign it yesterday

**Comment by chairbender** [comment]
Np I haven't done any work on it yet.
