### ISSUE TITLE
Space wind! B: 70

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1643]
# Description
What's atmos without players and items being sucked out of hull breaches?
They should definitely react to pressure changes!

## Category
Feature request

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open an airlock into space
2. Don't get sucked into space

**Comment by DooblyNoobly** [comment]
Bounty of 70 usd will be awarded to the contributor on a successful merge of a solution to this TODO

This is only suitable for experienced devs

**Comment by fomalsd** [comment]
gonna give this a go
