### ISSUE TITLE
Player slipping B: 50

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1644]
# Description
Player should be able to slip/fall due to clown's shenanigans, pressure changes or wet floors
(And get back up after some time)
This task implies adding following functionality:
- Cleaning floor tile with a mop should make it wet (slippery) for certain time
- Players should always slip on banana peels if they walk/run onto tile where the peel is registered at
- Players should slip on wet floors if they run on such tile (shouldn't slip if walking)

## Category
Feature request

**Comment by DooblyNoobly** [comment]
Bounty of 50 usd will be awarded to the contributor on a successful merge of a solution to this TODO

**Comment by DooblyNoobly** [comment]
Please also add the slip sound to sound manager. All you have to do is add an AudioSource as a child and soundmanager will pick it up automatically. Use the name of the GameObject to play it
