### ISSUE TITLE
Clients see other clients permanently stuck facing forward B: 20

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1659]
# Description
Clients always appear facing forward to other clients, even though they appear with the correct facing between client / server.

(Currently only discovered on headless)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host.
2. Join with 2 clients.
3. Change direction and observe that it always appears to one client that the other is facing forward.

Probably involves just tweaking the logic in UserControlledSprite

**Comment by chairbender** [comment]
this is my changes so I'll fix it

**Comment by DooblyNoobly** [comment]
Bounty of 20 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by NextThang** [comment]
I tried it even with normal (non-headless) server and server can see the clients rotating. But clients don't see anyone else rotating.

**Comment by fomalsd** [comment]
probably caused by this: https://github.com/unitystation/unitystation/blob/3262fbdb913b2a8779093f0a1965ff87e75e2101/UnityProject/Assets/Scripts/Player/UserControlledSprites.cs#L86
but making it abstract breaks build for IL2CPP

**Comment by chairbender** [comment]
working on it
