### ISSUE TITLE
When put in a locker in critical health, camera is not set to locker B: 40

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1660]
# Description
This happened when a CLIENT was closing a locker on another CLIENT.
(Currently only discovered on headless)

![test](https://user-images.githubusercontent.com/47410468/54873290-56a15d80-4da1-11e9-885a-bb7ec51d3241.png)

## Category
BUG

## Detailed Bug Report
When a client closes the locker on another client in crit/possibly normal state too, the closet player's camera is not set to the locker
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. as a client, close the locker door on another client who is crit
2. locker client will see hidden space instead of locker.

**Comment by DooblyNoobly** [comment]
Bounty of 40 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by Aranclanos** [comment]
lookin into it
