### ISSUE TITLE
Steam thinks game is still running after exiting B: 30

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1666]
# Description
Steam does not register the game as having stopped when you exit the game, resulting in a "Game is already running" message when trying to relaunch it.

This may be due to a process related to the game (such as a simulation thread) not being fully ended when the game is closed.

## Steps to Reproduce
1. Launch steam version of game via Steam.
2. Exit.
3. Try to relaunch it, get the "game still running" message.

Expected Behavior:
It should fully exit and should be possible to re-launch it.

**Comment by DooblyNoobly** [comment]
Bounty of 30 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by fomalsd** [comment]
Do you have Unity opened? It's known to make Steam think you're playing game. Just exit Unity and it will go away

**Comment by chairbender** [comment]
Didn't know about that or I wouldn't have made this. Closing this.
