### ISSUE TITLE
Not losing oxygen inside a breached room on headless B: 55

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1670]
# Description
This might be an exception in atmos.
You get pressure damage in main hall, but not oxygen damage.
When you go outside into space, oxygen damage kicks in.
<img width="1095" alt="Scr 2019-03-24 в 13 53 09" src="https://user-images.githubusercontent.com/10403536/54878856-48a41900-4e43-11e9-9b0c-6e81c7d242b1.png">

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join steam server as miner
2. Put on a helmet, but not oxygen mask
3. Enter the breached main hall

**Comment by fomalsd** [comment]
I think atmos always stops/doesn't start on steam server

**Comment by fomalsd** [comment]
I really think this should be looked into for 0.4

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 35usd on a successful merge of a solution that resolves the issue above.

**Comment by DooblyNoobly** [comment]
This one is a bit tricky to debug so increasing to 55

**Comment by chairbender** [comment]
Can't reproduce anymore, I think the round restart bugs probably caused this. Bounty can be put back into pool.

**Comment by chairbender** [comment]
Will test on remote headless first to make sure, was only testing locally

**Comment by chairbender** [comment]
yep working fine

**Comment by chairbender** [comment]
Back to To Do. The root cause seems to be atmos breaking / atmos thread dying due to some error.

**Comment by JesterX666** [comment]
Related to one of the problem identified in #2646 
If someone has a log of the server when this happened, it will be appreciated.

**Comment by JesterX666** [comment]
Indeed caused by atmos that wasn't working.  I was not able to reproduce it (even in headless).

![image](https://user-images.githubusercontent.com/32009105/73323255-d7788380-4214-11ea-9b55-963f94d6b2c0.png)

Perhaps our atmos is more stable after many corrections that we did?

I suggest we close the ticket for now, put the bounty elsewhere and re-open it if it happens again?

**Comment by DooblyNoobly** [comment]
I agree. Closing now

**Comment by fomalsd** [comment]
<img width="948" alt="Scr 2020-01-31 в 21 25 21" src="https://user-images.githubusercontent.com/10403536/73564312-54ec0000-4470-11ea-929d-5f745af311e2.png">
join GER server and see for yourself

**Comment by fomalsd** [comment]
...or maybe it's just a bug with grille being airtight... breaking grille got me killed within seconds
<img width="715" alt="Scr 2020-01-31 в 21 33 55" src="https://user-images.githubusercontent.com/10403536/73564783-641f7d80-4471-11ea-87c1-6207db6726cb.png">

**Comment by DooblyNoobly** [comment]
So was this just an issue with the grilles?

**Comment by fomalsd** [comment]
It wasn't the same issue, no. But this can be closed
