### ISSUE TITLE
Can't rejoin without restarting game after logging out or disconnecting

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1671]
# Description
You get kicked if you attempt to rejoin server without restarting game.
![Scr 2019-03-24 в 14 04 24-2 2019-03-24 14_54_22](https://user-images.githubusercontent.com/10403536/54878967-c157a500-4e44-11e9-93a3-2cfc74e84c78.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start game and join steam server
2. Press esc and log out
3. Log back in and try joining server again (you'll get kicked)

**Comment by chairbender** [comment]
great, seems like my fix worked. Can reopen if someone else encounters this again.
