### ISSUE TITLE
Leaving a body in cargo/captain's shuttle airlock doesn't depressurize it

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1674]
# Description
Tiles on the right side of the shuttle aren't recognized as space

![no_shuttle_decompression](https://user-images.githubusercontent.com/10403536/54886099-1fac7400-4e95-11e9-8669-6fd815135434.gif)

**Comment by chairbender** [comment]
Just gonna guess this is due to the body being marked as AtmosPassable = false

**Comment by fomalsd** [comment]
should be fixed by #1696
