### ISSUE TITLE
Can slide around while in crit

### ISSUE THREAD

**Issue by HenryBlackie** [unitystation/unitystation#1675]
# Description
## Category
BUG

## Detailed Bug Report
Sometimes when going in to crit I have been able to slide around on the floor for a few seconds

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Shoot self in head, repeatedly
2. Keep pressing WASD when you fall down, you should start moving about

**Comment by chairbender** [comment]
@HenryBlackie I think this is expected, you are able to crawl. There are 2 states of crit, hard and soft. When in soft crit, you can crawl.

**Comment by HenryBlackie** [comment]
Ah okay, I wasn't aware of that.

**Comment by chairbender** [comment]
np, now we have it as a ticket in case anyone else thinks its a bug so they will find it if they search
