### ISSUE TITLE
Don't init until local player is created 

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1676]
# Description
Lots of NREs occur when joining due to trying to init behaviors before LocalPlayer has been created. This is mostly due to the removal of the dummy player. 

Fix this as per Doobly's suggestion:

check this out: https://docs.unity3d.com/ScriptReference/CustomYieldInstruction.html

we should make a Init IEnumerator for those objects that require Local player and just yield until local player is available

a custom yield instruction can be added to YieldHelper for it

the instruction will look like this:
public class WaitForLocalPlayer : CustomYieldInstruction
{
    public override bool keepWaiting
    {
        get
        {
            if(PlayerManager.LocalPlayer == null)
         { 
            return true;
          }
            return false;
        }
    }
}

**Comment by RedlineTriad** [comment]
These NREs no longer happen.
