### ISSUE TITLE
Refactor Interact to handle multiple InputTriggers correctly

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1680]
# Description
Currently the Interact function in the MouseInputController will only trigger the first InputTrigger it encounters which will be MeleeTrigger is most cases. This makes it harder to implement new items since exceptions and checks need to be made for each new Trigger type.

Ideally Interact should be able to pickup all InputTriggers on an item and correctly trigger the right one. 
E.g. triggering the health scanner instead of hitting players with it all the time. 

Hitting should only occur if your intent is set to harm, or the item has no other triggers.

https://github.com/unitystation/unitystation/blob/d80aef8ca399a47a6f1582f19329c67de7794505/UnityProject/Assets/Scripts/Input%20System/MouseInputController.cs#L458-L467

## Category
TODO

## Related issues
#1652 
#1362

**Comment by Bod9001** [comment]
partially covered in #1788 , apparently still needs some work (the new interaction system)
