### ISSUE TITLE
With lag, an opening door can damage you

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1689]
# Description
Walking over a turf with a door opening can damage your mob

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.have a bit of lag
2.bump a door causing it to open
3.keep walking in the direction of the door, you'll be damaged

easier way to trigger it is is enabling gizmos on the editor, causing the game to lag. While this way is unrelated to ping but the issue persists

**Comment by Jibbajabbafic** [comment]
Possibly related to #1110

**Comment by Aranclanos** [comment]
Just realized that the damage you get is probably the lack of air on the tile, by random chance of getting the health tick before the airlock turf merges its air with the neighboors

**Comment by fomalsd** [comment]
it's due to closed doors having zero pressure. players without suits get a serious pressure hit. 
players with high ping tend to get caught in closing doors more often.
