### ISSUE TITLE
Ghosts can help-intent mobs

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1691]
# Description
When walking on top of living mobs as a ghost, you push them towards your previous location ignoring the fact that you shouldn't interact with them

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Be a ghost
2.Walk on top of a standing human
3.Notice how they get pushed towards your previous location (you can keep doing this until you move them inside walls and beyond)

**Comment by Jibbajabbafic** [comment]
Assuming this was introduced by #1673, @chairbender would you be alright having a look at this?

**Comment by chairbender** [comment]
yeah I'll look at it, proud to be the first to necessitate the lol tag
