### ISSUE TITLE
Logging out spams the console with errors (hosting only?)

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1693]
# Description
The console spams errors if you host a game and then proceed to logout.
NullReferenceException
PowerSupply.UpdateMe ()
UpdateManager.Update ()

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Host a game (doesnt seem to work without hosting)
2.Logout to main screen
3.Console spams NullReferenceExceptions

![image](https://user-images.githubusercontent.com/701959/55291138-95db3a00-53b1-11e9-84b7-085d9eb54ccc.png)

**Comment by Jibbajabbafic** [comment]
Logging out was never fully implemented so it's not surprising. We'll need to add additional logic to all systems to ensure they are correctly stopped and reset after logout.

**Comment by krille90** [comment]
Is this still a thing?

**Comment by NoooneyDude** [comment]
I don't think so. Couldn't reproduce, no errors generated.
