### ISSUE TITLE
You can walk on top of open crates

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1695]
# Description
On the byond version of the game, crates are not walkeable no matter their open/closed status. Not to be confused with lockers

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Open a crate
2.Walk towards it
3.You're now on the same turf than a crate

**Comment by kaffo** [comment]
Crates are using RegisterCloset which sets Passable = !Closed which makes sense for lockers, but not so much crates
Either needs a new RegisterCrate script or a switch on RegisterCloset to change the Passable behavior

**Comment by Aranclanos** [comment]
It's happening again

**Comment by chairbender** [comment]
easy fix, will do in next PR. The ClosetType field got reset, this is why I shouldn't have assigned it a default value.
