### ISSUE TITLE
Joining once as client crashes the editor on the next play

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1697]
# Description
If you join a server once with the editor as client, it crashes at the next 'play'.
I'm not logging out, im stopping the game with the play button.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Hit play with the editor
2.Join the game as client with the editor
3.Stop the game
4.Hit play once more
5.Crash after a few seconds

**Comment by fomalsd** [comment]
might be related to SunVox init

**Comment by Aranclanos** [comment]
if there's a quick/temporal solution please say so, this is exhausting

**Comment by fomalsd** [comment]
Are you using linux by chance? Last time it happened to linux users
https://github.com/unitystation/unitystation/pull/1556
maybe try commenting out this line that prevents deinit inside editor:
https://github.com/unitystation/unitystation/blob/8cc47d10fd74b8f3822570f4d0354ca770193821/UnityProject/Assets/Scripts/Sound/SunVox.cs#L75

**Comment by Aranclanos** [comment]
Thanks, that did the trick. I'm on windows 10

**Comment by chairbender** [comment]
since sunvox isn't going away for now and there's a workaround, going to close this. 

This should be fixed when / if we take on #1525

**Comment by Aranclanos** [comment]
slap some tag on it but dont close it

we don't even know whats the exact cause of the crash

**Comment by fomalsd** [comment]
Thing is, there's no such thing as UNITY_EDITOR_LINUX yet, and Linux editors are the only ones benefiting from that empty sv_deinit method. Windows editor reportedly crashes in that case, OSX doesn't

**Comment by chairbender** [comment]
Oh sorry I thought it would be fine to close, my bad.

**Comment by krille90** [comment]
Is this still a thing?

**Comment by corp-0** [comment]
is this still a thing :eyes: ? Haven't heard anyone mentioning this problem

**Comment by corp-0** [comment]
it seems like this is indeed not a thing anymore so I'm closing. Feel free to reopen if that's not the case.
