### ISSUE TITLE
Add containers (toolboxes, medkits, storage boxes, toolbelts, cigs...)

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1698]
# Description
At the moment we only have backpacks. Need a solution to initialize containers from 
dm.json, there are over 150 of these:
( see https://github.com/unitystation/unitystation/blob/4ba018b6bb8abdf92296ca88e71e3dea9bdca702/UnityProject/Assets/Resources/Metadata/dm.json#L31252 )
Preferred way is going the uniCloth/ItemAtrtibutes way, where there is a base prefab which gets initialized from provided hierarchy string.
It needs to take all relevant fields in account: 
amount of slots, item filters (by hierarchy string or bulkiness) and so on, see this one as an exmaple:
```json
 {
    "hierarchy": "/obj/item/weapon/storage/bag/bio",
    "name": "bio bag",
    "icon": "icons/obj/chemical.dmi",
    "icon_state": "biobag",
    "desc": "A bag for the safe transportation and disposal of biowaste and other biological materials.",
    "storage_slots": "25",
    "max_combined_w_class": "200",
    "w_class": "WEIGHT_CLASS_TINY",
    "preposition": "in",
    "can_hold": "list(/obj/item/slime_extract, /obj/item/weapon/reagent_containers/syringe, /obj/item/weapon/reagent_containers/glass/beaker, /obj/item/weapon/reagent_containers/glass/bottle, /obj/item/weapon/reagent_containers/blood, /obj/item/weapon/reagent_containers/hypospray/medipen, /obj/item/trash/deadmouse, /obj/item/weapon/reagent_containers/food/snacks/monkeycube)",
    "resistance_flags": "FLAMMABLE"
  }
```

**Comment by chairbender** [comment]
I think this would also require somehow adding bulkiness to each of our prefabs which don't have an item attribute component. Probably just adding a component which provides access to their dmi attributes would be a good approach. Similar to item attributes but not used to affect their actual sprite, just for providing a way to access their dmi data from other components.

**Comment by chairbender** [comment]
either way i think it would be good long-term to have a component which just provides access to dmi data for a specific object, and I think itemattributes is currently only specifically for uni-items so might not work to just slap it onto a non-unicloth prefab

**Comment by chairbender** [comment]
doobly also brought up the idea of not directly providing access to the dmi data using a component, but instead creating a wizard / editor script that would populate this information into our prefabs

**Comment by fomalsd** [comment]
I have a feeling that container bulkiness might be dynamic depending on its contents
But after thinking about it a bit – it's a can of worms, would be much easier if it was static.
Though anyway, I think everything player can pick up already has an ItemAttributes component, only Objects (closets, machinery...) are unaffected yet. But I think they could all be classified as "very bulky" since player can't pick them up, right?
So I'm not sure if we need an alternative to ItemAttributes right now

**Comment by chairbender** [comment]
as of #2245 it's possible to define container initial contents using inventory populators, I might suggest just doing that rather than trying to automatically set them from DM json

**Comment by fomalsd** [comment]
now to actually add all these containers! toolboxes, medkits, toolbelts, cigs, donuts – it's just a matter of some editor work
