### ISSUE TITLE
APC Text Overflow with Very Small Numbers

### ISSUE THREAD

**Issue by kaffo** [unitystation/unitystation#1709]
# Description
APC NetTab UI Text overflows onto the next line if the value is too long

## Category
BUG

## Detailed Bug Report
![image](https://user-images.githubusercontent.com/1458225/55684068-d3563f00-593e-11e9-9741-e89cebb6df5f.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go to Atmos
2. Turn off the lights
3. Check the APC
4. Notice the text overflows into the next line for Current and Power

**Comment by Jibbajabbafic** [comment]
Looking into this
