### ISSUE TITLE
Can no longer close lockers by clicking them

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1715]
# Description
You can open lockers, but can't close them back by clicking them – only with rightclick option.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find a closet
2. Open it
3. Try closing it by clicking its door or base

Not sure if chaining of ThenByDescending actually works here:
https://github.com/unitystation/unitystation/blob/5ccccb85400f9e3fd58de40001254855cb5a93e3/UnityProject/Assets/Scripts/Input%20System/MouseInputController.cs#L317

**Comment by fomalsd** [comment]
@chairbender could you look at this one? I think I encountered issues when chaining ThenByDescending before

**Comment by chairbender** [comment]
Ah shoot. Yeah I'll take a look.

**Comment by chairbender** [comment]
It's actually because I turned the collider off to make it passable and allow shots through it when open. Forgot collider also used for click detection.
