### ISSUE TITLE
UI: high/low Pressure, Oxygen, high/low Temperature warnings B: 80

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1722]
# Description
At the moment oxygen meter only works on the job selection screen (lol)
Need proper indicators so that player would know what's going on before he's in crit or dead.
Indicators should differentiate too low vs too high pressure and temperature

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 80usd on a successful merge of a solution that satisfies the criteria above.

**Comment by HydraulicSheep** [comment]
I'll take a look at this

**Comment by HydraulicSheep** [comment]
I have made a PR here: https://github.com/unitystation/unitystation/pull/1736
