### ISSUE TITLE
Spraying mechanic (space cleaner, fire extinguisher) B: 80

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1723]
# Description
Introduce mechanic to distribute chemical mixes in a directed stream;
Add space cleaner prefab and allow spraying arbitrary chemicals from it when filled in chem dispenser/from beaker. Should clean up blood if used with water or cleaning solution
Add spraying functionality to the fire extinguisher, it should put off fires

**Comment by DooblyNoobly** [comment]
You could use the particle system here if you like as well. Check the shader that is being used by the Plasma Generator smoke to make it compatible with FOV.

Contributor will receive a bounty of 80usd on a successful merge of a solution that satisfies the criteria above.

**Comment by RokaJosh** [comment]
I'll give this a go

**Comment by fomalsd** [comment]
This is up for grabs again!

**Comment by JakobVaughan** [comment]
Hey, I'll give this a try

**Comment by DooblyNoobly** [comment]
@MoltenAqua can you let us know if you are still doing this one? Its been 20 days since you claimed it

**Comment by JakobVaughan** [comment]
Yh, I'm still working on it, just been moving house recently, and everythings a bit up in the air. I'll get it done within a week or two, sorry for the wait

**Comment by JakobVaughan** [comment]
Hey, really sorry, but I ran into quite a few problems in creating the spraying mechanic, and am unable to complete the bounty

**Comment by Aranclanos** [comment]
I'll take a look

**Comment by chairbender** [comment]
@Aranclanos still working on this?

**Comment by DooblyNoobly** [comment]
I'm guessing aran is no longer working on it, taking off the In Progress tag

**Comment by fomalsd** [comment]
working on this

**Comment by StrawberryMoses** [comment]
For extra credit, the extinguisher gives momentum when fired. This allows for a "jetpack" obtainable by anyone, and for something more fun, being able to propel yourself through the station buckled into a wheely chair

**Comment by fomalsd** [comment]
jetpacking is on my todo list, we don't have rolling wheely chairs yet though
