### ISSUE TITLE
Loose ends with health/damage system B: 160

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1724]
# Description
WIP issue with a list of loose ends with current health/damage system implementation. 
Please comment and add what you think is missing from the list

#### Security:

- At the moment each player's health status is tracked client side.
Health should be serverside instead. 
Player shouldn't know other player's health unless a Scanner is used.
(Don't worry, we'll handle health broadcasting for medical goggles separately later)

#### Stability:
Both players and NPCs have weird health issues (todo: elaborate):

- Many thousands of these can be found in trace logs, I think it's related to PR #1656
```
[Health] NPC_PunPun received 0.0009134412 Oxy damage from aimed for Chest. Health: 0->0 
[Health] NPC_Pete received 0.0009134412 Oxy damage from aimed for Chest. Health: 0->0 
```

- Sometimes punpun is like immortal, but sometimes he's not.
Got errors trying to kill punpun

#### Functionality:
- Tiles should get damage when receiving melee hits (atm only throwing and shooting works)

- Ointments and bandages don't do anything.
Make bandages the only ones to stop bleeding, and food should only fix small amounts of health.
- You should be able to apply bandages and ointments to body parts of your choice

#### Balance:

- Players start bleeding and die too quickly in general
- Oxygen damage should be a lot slower than it is
- Bleeding never stops
- Body parts go to grey state with just a couple of melee hits

**Comment by DooblyNoobly** [comment]
This ticket covers a lot of the little jobs I was going to write out for medbay and medical. So slapping a large bounty on this ticket instead. Please ask for more clarification if it is needed.

Contributor will receive a bounty of 160usd on a successful merge of a solution that satisfies the criteria above.

**Comment by Aranclanos** [comment]
Gonna start with this one

**Comment by DooblyNoobly** [comment]
Most of these have been completed via #1783 
We are just working out what is left todo and will split the bounty + split out remaining issues into new ones

**Comment by DooblyNoobly** [comment]
9 / 10 criteria was completed via #1783 

Will split remaining tasks into their own issues and close this one. B144 will be paid out
