### ISSUE TITLE
Player movement: don't cut corners when moving diagonally

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1728]
# Description
Players shouldn't go through walls/solid objects when walking diagonally.
Instead, one move should be broken into two moves

As it is now:
![GIF](https://user-images.githubusercontent.com/10403536/55888986-df8d0700-5b9f-11e9-9601-164a32aaa5bc.gif)
Should be:
![GIF](https://user-images.githubusercontent.com/10403536/55889096-106d3c00-5ba0-11e9-853f-4905ad0160c8.gif)

It would also fix a bug when it's possible to cross matrices that are directly impassable, but can be passed diagonally (will show gif later)

**Comment by chairbender** [comment]
why not?

For the issue of crossing matrices that are impassable, yes we should fix that. But why not be able to move through a corner like this (when only one edge is impassable)?

**Comment by fomalsd** [comment]
well, players clipping through wall corners look unnatural in my opinion:
![image](https://user-images.githubusercontent.com/10403536/55939161-9931b980-5c2c-11e9-9b6b-1066be6132fe.png)

also I think it's the only way to cheaply fix this matrix switch bug:
![GIF](https://user-images.githubusercontent.com/10403536/55938984-2aecf700-5c2c-11e9-9711-c7740287704e.gif)

**Comment by fomalsd** [comment]
Another gif of why cutting corners is not desirable:
![GIF](https://user-images.githubusercontent.com/10403536/58036005-8c509180-7b19-11e9-8391-93108c58d1da.gif)
