### ISSUE TITLE
Items aren't thrown onto selected tile

### ISSUE THREAD

**Issue by Aestras** [unitystation/unitystation#1733]
# Description
As throwing works now, thrown items are either thrown past where you select or are unable to land on the surface you throw them on, such as a table. Items thrown towards tables hit the tables rather than land on them or past them.
## Category
BUG or TODO?
BUG
## Detailed Bug Report
![GIF2](https://user-images.githubusercontent.com/15038188/56092611-d93ea980-5e83-11e9-9e4e-232ffca0cdc0.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Take item in hand
2.Throw item to target tile
3.Observe item's destination

**Comment by fomalsd** [comment]
Hitting tables is indeed a bug;
Sliding on surface after landing is intended though: Items stop flying on the desired tile, but slide a bit further on the floor (do no damage while sliding). Wet floors are supposed to have low friction, so items will slide even further on these (when implemented)
Perhaps default sliding distance could be tweaked
