### ISSUE TITLE
There's a small flicker on the background at login

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1738]
# Description
When logging in from the start menu, the stars on the background change possition in a noticeable way
![image](https://user-images.githubusercontent.com/701959/56203661-0f169600-601c-11e9-8b19-d0454e15b42d.png)
notice how the stars change possition, its way more obvious watching it live
happens with both client and server

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.select "START GAME" at main menu
2.keep eyes on the background and watch it happen

**Comment by fomalsd** [comment]
Maybe it's due to camera teleporting to the place where serverplayer initially appeared (somewhere around top-right of the station) back when space duplicate players were a thing

**Comment by corp-0** [comment]
is this still happening? I haven't noticed anything like what's described here.

**Comment by jamessimo** [comment]
I can’t replicate this on my dev branch or the latest builds. Recommend closing this.
