### ISSUE TITLE
Scrubbers and vents have the old sprite

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1739]
# Description
![image](https://user-images.githubusercontent.com/701959/56204020-db883b80-601c-11e9-8b84-71baa5c2b2f4.png)
/tg/ got a new scrubber and vent sprite, unitystation is still using the super old one, see image for the differences

## Category
TODO

**Comment by fomalsd** [comment]
I'd say "won't fix". /tg/ also has new locker sprites as well as fuel tank sprite, we don't use them on purpose.
I'd rather keep old sprites that everybody recognizes.
If someone else disagrees with me, this can be reopened

**Comment by Aranclanos** [comment]
I disagree

**Comment by DooblyNoobly** [comment]
Removing Questionable tag, I think we should have the new sprites as they look better then the old ones. And its probably not hard to implement as its just changing some things in the prefabs.

**Comment by Aranclanos** [comment]
Fixed
