### ISSUE TITLE
Character movement

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#174]
you are pressing down for example
and as you are pressing it
you press left
you're now moving left but from where your last position
so if you were in between two tiles
you'll keep moving that way

**Comment by DooblyNoobly** [comment]
[ unitystation/Assets/scripts/PlayGroups/PhysicsMove.cs](https://github.com/unitystation/unitystation/blob/master/Assets/scripts/PlayGroups/PhysicsMove.cs) 

Happens in the MoveDirection function:

```	
        public void MoveInDirection(Vector2 direction)
	{ 
		nextTile.x = (int)(Mathf.Round(transform.position.x) + direction.x); 
		nextTile.y = (int)(Mathf.Round(transform.position.y) + direction.y);

		if (Matrix.Matrix.At(nextTile.x, nextTile.y).IsPassable()) {
		lerpA = false;
		moveDirection = direction;
		isMoving = true;

		if (direction == Vector2.right || direction == Vector2.left) {                         			              clampPos = transform.position.y; 
		}

		if (direction == Vector2.down || direction == Vector2.up) {
		clampPos = transform.position.x;
		}
		  } else {
		  //Check why it is not passable (doors etc)
		DoorController getDoor = Matrix.Matrix.At(nextTile.x, nextTile.y).GetDoor();
		if (getDoor != null && !tryOpenDoor) {
		tryOpenDoor = true;
		StartCoroutine("OpenCoolDown");
		getDoor.TryOpen();
		} 
	}
}
```
So when you change direction clampPos is set with the x or y value you are currently at. We could experiment with Mathf.Round on the clampPos when it is set to lock it to the grid.

**Comment by Scorr** [comment]
I would suggest to prevent movement while moving to a new tile, until player reaches it. However save the direction if a movement key is pressed during the move and execute it after reaching the new tile so it keeps feeling responsive.
