### ISSUE TITLE
Food and drinks lose their sprite when consumed

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1740]
# Description
![image](https://user-images.githubusercontent.com/701959/56204321-8a2c7c00-601d-11e9-8f21-4a9dd404fcdc.png)
Meat, icy soda and beef jerky seems to convert into a white square that goes invisible if its on the floor. 4NoRaisins seem to work properly

![image](https://user-images.githubusercontent.com/701959/56204604-2eaebe00-601e-11e9-8ab4-8a5cea6d1758.png)
4NoRaisins and beef jerky wrapper on the same tile, one invisible

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get icysoda, meat or beef jerky
2.consume it
3.notice the unintended sprite

**Comment by fomalsd** [comment]
Yes, it's known. Caused by me removing a bunch of old spritesheets:
bullet shells are affected as well

**Comment by fomalsd** [comment]
Also glass shards

**Comment by fomalsd** [comment]
Also likely window cracks
