### ISSUE TITLE
Cant place extinguishers back on their lockers

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1741]
# Description
Once you take out a fire extinguisher from their locker, you can't place them back on them.
The extinguisher code checks if the object name string is "extinguisher" to accept it back inside, they're called "fire extinguishers" so they're rejected

## Category
BUG 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Take out fire extinguisher from their locker
2.Try to place it back by clicking on them
3.Locker just closes following the default behaviour for any object interacting with it, leaving the extinguisher in your hand

**Comment by fomalsd** [comment]
Yeah, extinguisher cabinet code is old
