### ISSUE TITLE
Windows block vision for objects on top of walls (APCs only?)

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1742]
# Description
![image](https://user-images.githubusercontent.com/701959/56205118-48043a00-601f-11e9-97c4-0acf273934b5.png)
It's very noticeable on the APC in front of the captain's office, when walking on the room to the right it disappears from your vision, I cant seem to find this error in other part of the station

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Walk in front of the captains office
2.Watch the APC as you move back and forwards on the room to the right
3.Notice how it disappears even through there's a window

**Comment by fomalsd** [comment]
It's how wallmounts work. This APC is positioned left and therefore will only be seen if player is to the left of it

**Comment by Aranclanos** [comment]
the thing is that its a window

**Comment by Bod9001** [comment]
You could make it check if it's on a wall before  Making itself disappear with the Wall mounte behaviour

**Comment by Aranclanos** [comment]
why are windows walls?

**Comment by Bod9001** [comment]
well I'm saying it doesn't implement that yet, For example when you place A wall mount  In the middle of the floor
