### ISSUE TITLE
Can't examine equipped items

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1743]
# Description
It seems to be impossible to inspect an item equipped or in-hand, right clicking doesnt seem to do anything and shift-click is also rejected

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Pick up an item and leave it in-hand or equip it
2.Try to inspect it
3.Find no option to do so

**Comment by chairbender** [comment]
This ticket is similar to #1464 , but is more expansive.
