### ISSUE TITLE
JoinedViewers have a human UI

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1744]
# Description
![image](https://user-images.githubusercontent.com/701959/56205583-9bc35300-6020-11e9-930c-0f40e354ecfe.png)
![image](https://user-images.githubusercontent.com/701959/56205575-91a15480-6020-11e9-813d-58b8dd0e9c65.png)
Oxygen warning, internals toggling, health seem to show up when selecting role (nanotrasen or syndi)
If you pick nanotrasen, the rest of the UI shows up when you're only at the job selection menu
This UI is for humans and shouldn't appear at the menu

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Login and watch the UI
2.Notice how it appears even though you're not a human yet

note: if you're in the editor make sure your scale is 1x otherwise the UI on the right will be out of sight

**Comment by StrawberryMoses** [comment]
Looks like this was fixed at some point
