### ISSUE TITLE
right-ctrl doesnt seem to be registered for pulling

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1746]
# Description
When using right-ctrl to pull something, the game decides to ignore it. Pulling only works if you use the left side ctrl. I'm talking about the keyboard positioning of both ctrl keys

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Use right-ctrl click to pull something
2.Notice how the game registers a normal click, ignoring your ctrl press

**Comment by fomalsd** [comment]
yeah, noticed that, too. Right Cmd needs to initiate pull as well

**Comment by Jibbajabbafic** [comment]
The right Ctrl not working is definitely a bug ~~but I made Cmd equivalent to Ctrl because I didn't think all Macs had both Ctrl and Cmd keys. Should be an easy fix though~~ <- misread foma's comment, nvm
