### ISSUE TITLE
ID, belt and pockets stay equipped when taking off your suit

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1747]
# Description
![image](https://user-images.githubusercontent.com/701959/56206264-57d14d80-6022-11e9-9d49-309b8dc2538d.png)
Notice how the character isn't wearing a suit, yet, the pockets and belt items stay on their place. I'm assuming it happens with your belt slot too.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Place items in your pockets/belt slot/ID slot
2.Take off your suit
3.Notice how they stay on their respective slots without falling on the floor

**Comment by fomalsd** [comment]
yeah, clothing should be refactored so that suits would actually have slots

**Comment by Bod9001** [comment]
I wonder if you could have a variable amount of pockets?
"Assistance running around with fishing vests"

**Comment by fomalsd** [comment]
![pockets](https://user-images.githubusercontent.com/10403536/56424689-eb17b680-62a0-11e9-9ce7-283b6c8ccf1f.png)

**Comment by chairbender** [comment]
Also related to #2248  , there are other slots which are tied to the suit. Might be good to do them together.
