### ISSUE TITLE
Inconsistency with in-hand sprites (chef only, maybe there's more)

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1748]
# Description
![image](https://user-images.githubusercontent.com/701959/56206391-a8e14180-6022-11e9-9a69-a80bc14defef.png)
On this image, the chef's suit (not exosuit) is invisible on-hand and the chef hat has the exosuit sprite on-hand
I am not aware if there's more in-hand sprite inconsistencies, I haven't tested much

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Pick up the chef's hat and cook's suit with your hands
2.Look over at the in-hand sprites for said items
3.Notice their lack of sprite or different sprite as the appropriate item

**Comment by fomalsd** [comment]
that can happen: SpriteManager currently only supports one spritesheet per clothing type. 
So if DMI data has an inhands offset in a spritesheet that's different from one in SpriteManager there could be mismatches
