### ISSUE TITLE
Shooting is wonky B: 60

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1749]
# Description
1) ~~Broken grilles sometimes stop bullets~~ old unity version triggered this 
![image](https://user-images.githubusercontent.com/701959/56206669-48063900-6023-11e9-8ac5-e28c3213ac6f.png)
In this image im shooting down, but the window bellow isn't being shot as the broken grille is stopping bullets
1.Break a window
2.Try to shoot through the hole
3.Notice how the broken grille stops your bullets

2) ~~Can't shoot while hovering items~~ Fixed by chairbender
![GIF](https://user-images.githubusercontent.com/10403536/58490691-22f60180-815d-11e9-9a74-8ba52912d03f.gif)

3) Can sometimes shoot though walls (raycasts are evil)
![GIF](https://user-images.githubusercontent.com/10403536/58490964-9ac42c00-815d-11e9-937f-d6fdffce626c.gif)

4) Shooting doesn't emit muzzleflash/light or shake ground

**Comment by fomalsd** [comment]
![GIF](https://user-images.githubusercontent.com/10403536/56209586-78f66600-6043-11e9-81f9-e58b9bda0db7.gif)
hm, they appear to go through for me

**Comment by Aranclanos** [comment]
It doesn't happen on the steam server, but I can reproduce it locally both in the editor and build. Weird one

**Comment by fomalsd** [comment]
might be related to general unreliability of unity's Physics2D (bullets use RigidBodies) and raycasts

**Comment by fomalsd** [comment]
Modified this issue to be more general

**Comment by chairbender** [comment]
FYI, my next set of changes for IF2 will be refactoring shooting to use IF2, which should at least fix the issue where you can't shoot while hovering over something (adding a new "AimApply" interaction).

**Comment by vlandemart** [comment]
> 3. Can sometimes shoot though walls

Not sometimes, but always - you can shoot though shuttle walls for some reason.

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 60usd on a successful merge of a solution that satisfies the criteria above.

**Comment by DooblyNoobly** [comment]
If you are doing this ticket please make sure you do not break the client side prediction

**Comment by chairbender** [comment]
Just warning, I have a PR that's touching guns (refactoring it to IF2) that should be submitted in a day or two. Doesn't affect bullet behavior but I would suggest waiting for that if you need to make significant changes to Weapon

**Comment by vlandemart** [comment]
I wasn't able to recreate 1. Not in editor, not in build.
3 is happening because Shuttle's `TilemapCollider2D` has `IsTrigger`. Disabling it fixes the problem, but would require scene change since shuttles aren't prefabs.

**Comment by dapocalypse** [comment]
claim

**Comment by chairbender** [comment]
2 will be fixed by my upcoming PR btw

**Comment by chairbender** [comment]
2 will be fixed as of #1936 . Don't worry about crediting me, whoever fixes the other issues can take the bounty.

**Comment by dapocalypse** [comment]
So I have to fix 3 and 4 as it seems.

**Comment by chairbender** [comment]
the PR I mentioned is merged

**Comment by dapocalypse** [comment]
someone else do this

**Comment by Aranclanos** [comment]
edited the OP to mark off step 2 since chair fixed it

**Comment by fomalsd** [comment]
can shoot through atmos tanks
![GIF](https://user-images.githubusercontent.com/10403536/60578021-065a7400-9d70-11e9-95b0-016a42aa8ee1.gif)

**Comment by chairbender** [comment]
Atmos tanks not being shootable will be fixed in upcoming pr

**Comment by chairbender** [comment]
Can not recreate 1. But fixed 3 as indicated by vlandemart.

Will work on muzzle flash and shake

**Comment by Aranclanos** [comment]
I updated unity to 2018.3.14 and the grille stopping bullets stopped happening
