### ISSUE TITLE
Closed tab should minimize tab holder if it was minimized before opening tab

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1750]
# Description
![image](https://user-images.githubusercontent.com/701959/56206882-c7940800-6023-11e9-9f9f-61d04dddcefa.png)
While the window is no longer related to the APC and it turns into the player list, it should close instead of staying open (unless you had it open before interacting with the APC?)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Open an APC window
2.Walk away from it
3.Notice how the screen turns into the player list instead of closing

**Comment by fomalsd** [comment]
Should probably be rephrased to "Closed tab should minimize tab holder if it was minimized before opening tab"
