### ISSUE TITLE
Full spacesuit doesnt block hair

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1752]
# Description
![image](https://user-images.githubusercontent.com/701959/56208005-7d605600-6026-11e9-87fc-d04691345d8d.png)
Your hair sprite seems to ignore the fact that you're using a full body spacesuit and appears glamorously

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Put on a space suit while having long hair
2.Notice how the hair sprite comes off from the spacesuit

**Comment by fomalsd** [comment]
yes, indeed: clothes don't utilize hiding flags like `"flags_inv": "HIDEHAIR"`

**Comment by fomalsd** [comment]
I think these "flags_inv" `HIDEMASK, HIDEEARS, HIDEEYES, HIDEHAIR, HIDEFACIALHAIR, HIDEFACE`
could be either converted to Traits (no idea if anything but clothes would ever need that though), or added to the ClothingV2 script as [Flags] enum

**Comment by StrawberryMoses** [comment]
If doing this it might be worth adding flags for hiding clothes, shoes, and back as well

**Comment by fomalsd** [comment]
found a few more in dm code: `HIDEGLOVES, HIDESHOES, HIDEJUMPSUIT`

**Comment by chairbender** [comment]
I would suggest it be it's own enum field on ClothingV2, so as to avoid cluttering item traits too much
