### ISSUE TITLE
Triggering grenades doesnt active the throw action

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1754]
# Description
When triggering your grenade on, your throw action won't be turned on, forcing the player to activate it manually

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get a grenade
2.Activate it
3.Aim and click
4.Nothing happens as your throw action wasn't activated

**Comment by fomalsd** [comment]
is this a thing on /tg/? sounds more like an UX improvement than a bug

**Comment by Aranclanos** [comment]
Yes, and its extremely old

**Comment by christmoore** [comment]
I will take this.
