### ISSUE TITLE
Grenades lack 'activated' mode

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1755]
# Description
Grenades should have a sprite and sound showing that they're activated 

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Activate a grenade
2.Notice lack of ongoing sound or sprite showing that the grenade is activated and about to blow

**Comment by fomalsd** [comment]
Done in #2230

**Comment by Macoron** [comment]
Doesn't work again 😫

**Comment by DooblyNoobly** [comment]
where were you testing?

**Comment by Macoron** [comment]
Editor, host mode. I guess, it's because new sprite handler system. Need to rewrite animation code.
