### ISSUE TITLE
Player's eyes see through walls

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1757]
# Description
![image](https://user-images.githubusercontent.com/701959/56209805-c6b2a480-602a-11e9-8517-b2ffeb4fa904.png)
On this image I'm opening a door with another client, yet I'm seeing it happen even thought its in another room behind a wall. In reality, the whole area behind the wall should be black

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Play normally
2.Notice your eyes have basically masons, can see through walls but cant see like if you had X-rays
3.opening/closing doors will be shown to you

note: this is not just about doors, the objective would be making the whole area behind vision black

**Comment by chairbender** [comment]
Are we sure we want to make FOV-obscured tiles completely black? I'm wondering if there's a reason it's not currently done that way.

I'm pretty sure a change like this will require shader coding.

**Comment by Aranclanos** [comment]
well it definitely changes the game a lot if you let everyone have masons in their eyes

**Comment by chairbender** [comment]
I'm only asking because it seems like if we wanted it done this way it would've already been done.

**Comment by DooblyNoobly** [comment]
Intention was to not animate the door at all if you can't see it. So it looks closed, but if its opened you won't see its opened state until its no longer under the FoV shroud. Haven't thought about how to actually implement that though.

**Comment by fomalsd** [comment]
I previously experimented with making doors FoV-masked (disappear if not in line of sight), but that didn't look good.
Will probably have to wait until we implement network culling system (which is a huge undertaking)

**Comment by fomalsd** [comment]
done
