### ISSUE TITLE
Leaving and Rejoining steam server while standing in opened airlock causes unexpected behaviour B: 20

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1767]
# Description
Please note only contributors with the discord role "Engineer" can complete this ticket as you need access to the steam server:

if you log out while standing in opened airlock, you'll join back inside a closed one and won't be able to get out of it:

![image](https://user-images.githubusercontent.com/20813925/56547291-49ee7000-65c0-11e9-9c8e-f8a3bd2755d6.png)

A bounty of 20usd will be awarded to the contributor on a successful merge of a solution to this bug.

**Comment by Aranclanos** [comment]
fixed in https://github.com/unitystation/unitystation/pull/1790

**Comment by DooblyNoobly** [comment]
thanks will sort it out soon
