### ISSUE TITLE
Lighting system blocks mouse interaction intermittently B: 35

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1768]
# Description

Clicking is blocked intermittently by lighting system for some reason. 

To recreate, try clicking on closets as it seems to affect them a lot. You can also try to spawn as syndie, rotate the shuttle 90 degrees then try to click on a closet in the shuttle, you'll notice that it is hard to open.

Foma has done some investigating and believes it is to do with lighting FoV checks. Particularly the code found here: https://github.com/unitystation/unitystation/blob/ba582a06dbdfc0452e3a26ac6a0115d3e13a1013/UnityProject/Assets/Scripts/Input%20System/MouseInputController.cs#L294

Code snippet:

```      
// Sample the FOV mask under current mouse position.
if (lightingSystem.enabled && lightingSystem.IsScreenPointVisible(CommonInput.mousePosition) == false)
{
  return false;
}
```

A bounty of 35usd will be awarded to the contributor on a successful merge of a solution to these issues.

**Comment by Itsnotjames** [comment]
Can't reproduce. Been clicking these lockers for awhile but every click opens/closes the locker.
![6YrH4xE](https://user-images.githubusercontent.com/28093344/56620786-3e617e80-667e-11e9-9220-208cbd7176b5.png)

**Comment by fomalsd** [comment]
try clicking things right after you stop walking
