### ISSUE TITLE
Dev spawner doesnt recognize the search 'plasma' for the 'solidplasma' object

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1772]
# Description
![image](https://user-images.githubusercontent.com/701959/56591265-cb450300-65be-11e9-80f4-e589313274e0.png)
The plasma sheets are called 'SolidPlasma' and do not appear if you write 'plasma'

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Type 'plasma' on the dev spawner
2.Get only the envirosuit plasma clothes and no plasma sheets

**Comment by chairbender** [comment]
@Aranclanos 

Temporary solution - just use wildcards when you do the search.
*plasma

More long-term solution - the analyzer should split on camel case.
