### ISSUE TITLE
There's an APC on top of a window

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1773]
# Description
![image](https://user-images.githubusercontent.com/701959/56591562-5c1bde80-65bf-11e9-9ff3-720dabf58172.png)
This APC located in front of the captain's office is on top of a window, APCs should only be on top of walls

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Start the game and head towards the room in front of the captains office
2.Notice the APC on top of a window

**Comment by fomalsd** [comment]
Is #1742 still relevant then?

**Comment by Aranclanos** [comment]
dunno because I dont know if they still would block the vision of an apc on top of a wall

**Comment by ghost** [comment]
Should an APC be able to be mounted on a window?

**Comment by Aranclanos** [comment]
No
