### ISSUE TITLE
Lying down monkeys dont turn their tails

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1774]
# Description
![image](https://user-images.githubusercontent.com/701959/56592279-be291380-65c0-11e9-9121-28ae0e318c07.png)
Notice the tail direction change difference of the unity and byond versions. The unity version is also a few pixels above than it should be.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Stab punpun to crit
2.Notice when he's lying down his tail wont change direction

**Comment by fomalsd** [comment]
![see](https://user-images.githubusercontent.com/10403536/57315085-658a6800-70e2-11e9-8286-883614b31c04.png)
I think we have correct sprite in place. tail is sideways relative to body when it's alive and is in line when it's dead

**Comment by Aranclanos** [comment]
those sprites are unused, the 4 to 8 ones
