### ISSUE TITLE
Oxygen tank sprite issues

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1775]
# Description
![image](https://user-images.githubusercontent.com/701959/56592639-7656bc00-65c1-11e9-8424-bcc92b95aea9.png)
The oxyen tanks use their old sprite, use incorrect in-hand sprites (probably use the emergency oxygen tank in-hand sprite) and when they're on the floor they seem to be too small 

## Category
BUG & TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get an oxygen tank
2.Notice their old sprite 
3.Drop them on the floor
4.Notice their strangely small size sprite
5.Pick it up with your hand
6.Notice the emergency oxygen tank sprite nstead

**Comment by fomalsd** [comment]
gotta make proper emergency oxygen tanks and big ones, current one is a mix of both: it's big (not pocketable), but has little air inside
