### ISSUE TITLE
Slippery tiles with water decal is invisible

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1777]
# Description
![image](https://user-images.githubusercontent.com/701959/56593770-7e632b80-65c2-11e9-9f7b-25321b03f06b.png)
Currently, tiles with water on top of them have no sprite this is how they should look

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Use a mop on the floor
2.Finish cleaning 
3.Notice the lack of sprite on top of the tile

**Comment by fomalsd** [comment]
ah, I specifically asked author not to leave these, my fault
should be easy to re-enable them
