### ISSUE TITLE
ProgressAction cancels on character turning

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1778]
# Description
If your character turns, the progress action will stop.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Find anything that uses a progress action, in this case for example, a mop
2.Start cleaning the floor
3.Click behind you
4.Your character will turn and stop the progressaction bar, stopping you from cleaning the floor tile

**Comment by fomalsd** [comment]
it was initially intended for welders I think, should welding continue if you turn during welding?

**Comment by fomalsd** [comment]
should probably introduce some flags to progress actions like "allow multiple" and "allow changing direction"

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/56676632-15001d00-6695-11e9-8fbb-b888331bbe10.png)
aye mass welding works

**Comment by fomalsd** [comment]
Actually now mass welding works if you don't turn (but there's only one instance of progress bar, so it looks a bit glitchy)
![GIF](https://user-images.githubusercontent.com/10403536/58033650-5fe64680-7b14-11e9-96a4-5e53cff80a2b.gif)
Anyway that anti-turn protection is easy to disable
