### ISSUE TITLE
Can't clean more than one tile at the same time

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1780]
# Description
Probably related to ProgressAction, when using the mop, I can't clean other tiles next to me at the same time unless I cancel the current progress action. I should be able to clean all at the same time

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Click on a tile with a mop to clean it
2.Click on the tiles next to it to clean them at the same time
3.Nothing happens unless my character turns and the progress stops (covered in another issue report)

**Comment by chairbender** [comment]
also an issue with asteroid mining

**Comment by fomalsd** [comment]
are you absolutely sure? because with a welder, you CAN weld multiple walls at the same time but the animation kind of glitches and only the first one is visible until it's finished, then the next one becomes visible

**Comment by chairbender** [comment]
well yeah you can do it, but it doesn't look good as you pointed out. we just need to support having multiple progress bars. current system only supports one at a time per player
