### ISSUE TITLE
Captains room not captain-only access

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1781]
# Description
![image](https://user-images.githubusercontent.com/701959/56595838-be77dd80-65c5-11e9-8195-6bd243366db7.png)
Captain's chambers seem to have command access instead of captain only, or at least it seems so, I only tested it with the CMO

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Spawn as any command role (CMO only?)
2.Head to the captains door and bump it
3.Notice that it opens without you being the captain

**Comment by fomalsd** [comment]
might be a good idea to convert this issue to address all access-related bugs
I think sec doesn't have access to airlocks and detective doesn't have access to either dorms or maint
(probably there are a lot more oversights)
