### ISSUE TITLE
Can see Ian through walls

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1782]
# Description
![image](https://user-images.githubusercontent.com/701959/56596102-465de780-65c6-11e9-8681-6a9ea83b0dbc.png)
Noticed it on the steam server, I can see Ian through the walls even when the scrubber, vent and wallmount disappear on closing/opening the door
I also placed him next to Runtime, and Ian stays on my screen while Runtime disappears when out of vision.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Head to the bridge
2.Make sure all doors are closed and there's no vision that could make you see Ian
3.Notice the dog still appears on your screen

**Comment by fomalsd** [comment]
yeah, not sure why it happens, Ian's sprites are FoV-masked
