### ISSUE TITLE
Can see cables through walls

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1794]
# Description
![image](https://user-images.githubusercontent.com/701959/56994054-65cfb400-6b74-11e9-95fe-2f7eb7b3b38b.png)
Those cables in the maint tunnel are out of vision and should be hidden

## Category
BUG

**Comment by Jibbajabbafic** [comment]
Should be easy to fix.

Who ever takes this on just needs to change the sprite renderer material for all wire prefabs to FovMasked like so:
![image](https://user-images.githubusercontent.com/4493127/56995112-bce78000-6b98-11e9-87e9-402e6d475f50.png)
