### ISSUE TITLE
Cables colour pattern changes

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1795]
# Description
![image](https://user-images.githubusercontent.com/701959/56994128-9c0d3380-6b74-11e9-8303-86285b767281.png)
Above the dorms these blue cables with yellow stripes seem to loose their yellow stripes and be only blue for two turfs. I don't know if there are more cases.

## Category
BUG?

**Comment by Bod9001** [comment]
oh yeah, I fixed this might as well close it
