### ISSUE TITLE
The devspawner can't seem to spawn objects on top of tables

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1796]
# Description
![image](https://user-images.githubusercontent.com/701959/56994247-e2fb2900-6b74-11e9-9862-e020b6cb5853.png)
I'm clicking on top of the table but nothing happens, the item never spawns. Clicking on the floor works fine.

## Category
BUG

**Comment by fomalsd** [comment]
yeah, dev spawner doesn't allow spawning on non-passable tiles, and tables are considered not passable

**Comment by chairbender** [comment]
just want to mark this as feature so its clear it's not some broken functionality and can be prioritized properly. I never intended to allow DevSpawner to spawn on impassable tiles so I consider it a new feature.
