### ISSUE TITLE
Right clicking shows cables in covered tiles

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1797]
# Description
![image](https://user-images.githubusercontent.com/701959/56994320-1c339900-6b75-11e9-964e-a7c5e461e4a0.png)
Here I'm right clicking on the turf in front of the character, and a cable shows up in the interface even if its hidden under the tile

## Category
BUG

**Comment by Jibbajabbafic** [comment]
I think @Bod9001 has this in his todo list

**Comment by fomalsd** [comment]
also I had an NRE when rightclicking a space tile with some items on it:
```
NullReferenceException: Object reference not set to an instance of an object 
Rightclick.IsUnderFloorTile (UnityEngine.GameObject obj) (at Assets/Scripts/UI/Right click/Rightclick.cs:149) 
System.Collections.Generic.List1[T].RemoveAll (System.Predicate1[T] match) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0) 
Rightclick.GetRightClickableObjects () (at Assets/Scripts/UI/Right click/Rightclick.cs:128) 
Rightclick.Update () (at Assets/Scripts/UI/Right click/Rightclick.cs:107)
```

**Comment by chairbender** [comment]
already fixed
