### ISSUE TITLE
Problems when clicking walls to weld

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1799]
# Description
![image](https://user-images.githubusercontent.com/701959/56994434-76ccf500-6b75-11e9-8c2b-eb1534a27035.png)
Here I roughly painted with green the area that you CAN click and with red the area that you CAN'T click.
If you click on the green area, you'll start welding the wall. If you click on the red area, nothing will happen.

## Category
BUG

**Comment by VitrescentTortoise** [comment]
Gonna look into this.

**Comment by DooblyNoobly** [comment]
roger that, set to in progress

**Comment by VitrescentTortoise** [comment]
Okay, so I found the source of the bug, I have a fix, but I do not know exactly what the desired behavior is so I have not made a PR.

![Capture](https://user-images.githubusercontent.com/1689336/57911180-0b617380-7855-11e9-91b4-0455806a7af5.PNG)
It is comparing player position which is (73, 65, 0) and world cell position which is actually the mouse position: (72.9, 66.3, -1) clicked on tile above. We also have the cell position that was clicked on (72, 65, 0) (rounded from mouse pos somehow using baseTilemap.WorldToCell).

I find taking the Euclidean distance between the player and the mouse position strange, even more so in 3D with that -1 z coord, but I haven't played OG ss13 in a while and I don't remember how it works. I assume clicking anywhere on an adjacent tile is the desired behavior, I do not know if diagonals should be included.

Feel free to fix, or let me know what it should do and I will make it work. I might be over complicating this, this stuff hurts my head and it's 4 am.

**Comment by fomalsd** [comment]
proper distance check method should be used, in your case it would be
player.Player.Script.IsInReach()

**Comment by VitrescentTortoise** [comment]
Ah, thanks. Hopefully I will get familiar with the idiomatic methods for these types of things soon. Will fix and make a PR.

**Comment by fomalsd** [comment]
Fixed in #1875
