### ISSUE TITLE
Electric-dependant objects working without power

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1800]
# Description
![image](https://user-images.githubusercontent.com/701959/56994562-ce6b6080-6b75-11e9-90ac-de781f33cefe.png)
Airlocks, air alarms, computer and others work without problem even if the APC is turned off and out of power

## Category
BUG

Note:
please don't fix it'll make debugging a pain unless you increase the duration of the engine or enable some dev tool add plasma to it and turn it on with just a button.

**Comment by chairbender** [comment]
It's easy to smash doors now btw, so this isn't so bad to fix

**Comment by NoooneyDude** [comment]
I think most equipment now requires power. It is probably best to create a new issue listing the cases where this is not true when they are found.
