### ISSUE TITLE
There are many Debug.Log() messages outside of Logger.cs

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1801]
# Description
![image](https://user-images.githubusercontent.com/701959/56994812-86990900-6b76-11e9-810b-4efe38e9843d.png)
Some examples of them, personally I'd like them gone

## Category
TODO

**Comment by fomalsd** [comment]
agree, also want "category-less" Logger.Logs gone, too. People sometimes forget to add logging category

**Comment by RedlineTriad** [comment]
I also think that the logging categories should be documented so it is easier to find out which to use for what. Would the logging category in `ItemAttributes` be `ItemSpawn`, `Inventory`, or `Container`?

**Comment by ghost** [comment]
I'd be happy to try and clean these up.

**Comment by fomalsd** [comment]
Fixed in #1821
