### ISSUE TITLE
Secroom lights are off in clients

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1803]
# Description
![image](https://user-images.githubusercontent.com/701959/56995476-420e6d00-6b78-11e9-8227-a6b4fda7749d.png)
In this pic the server shows the sec room having the lights on while a client who just logged in sees the light tubes turned off. Toggling the switch on and off doesn't seem to change anything.

## Category
BUG

**Comment by VitrescentTortoise** [comment]
I shall work on this.

**Comment by Aranclanos** [comment]
might have been fixed in #1869

**Comment by VitrescentTortoise** [comment]
Thanks, I will check.

**Comment by VitrescentTortoise** [comment]
It appears to be fixed by #1869. I can no longer reproduce after pulling those changes. Thanks for the heads up, you definitely saved me some hours.
