### ISSUE TITLE
Job selection window organization

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1804]
# Description
![image](https://user-images.githubusercontent.com/701959/56995681-c95be080-6b78-11e9-8873-29d2a42e9c0d.png)
![image](https://user-images.githubusercontent.com/701959/56995742-f8725200-6b78-11e9-8c43-966a83836ce6.png)

-Above there's an example of tg's job preferences (note: technically not the same window) 
In unitystation's version the names seem to be different (for example, "DOCTOR" instead of "Medical Doctor", or "MINER" instead of "Shaft Miner")

-It's organized alphabetically instead of by jobtype, and the alphabetically order also has mistakes, "DOCTOR" and "MINER" are in the wrong order.

-Job Names have underlines instead of spaces, see: "chief_engineer"

-Job names are in all caps

-Some job names have the short version of the names. See: "CMO" instead of "Chief Medical Officer"

## Category
BUG

**Comment by Jibbajabbafic** [comment]
Ideally jobs should be grouped together and coloured by department much like in the TG screen.

**Comment by StrawberryMoses** [comment]
With merge of mirror, this is now in develop
