### ISSUE TITLE
You can see your character naked for half a second when spawning

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1805]
# Description
It's too fast so I dont have a screenshot, but before your character gains clothes and its preferences, you'll see the white-human mob that the prefab sprite is

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Die and wait for respawn
2.Try not to blink
3.See the white (rgb 0,0,0) human prefab appear of an instant before it gains its preferences for hair, skin and eyes and its clothes.

**Comment by fomalsd** [comment]
Fixed by Aran
