### ISSUE TITLE
A lot of sprites are outdated

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1806]
# Description
Computers, vending machines, lockers, fuel tanks, guns, telecomms machinery, APCs, chemistry machines, library machines and probably more sprites are using the old sprites. Many of these were changed to have a standard perspective across all sprites of the game.
The ones I listed are the ones that I found from a quick sweep, its highly possible that there are more.

## Category
TODO

**Comment by DooblyNoobly** [comment]
I'm hoping we can just drop in the new sheets, replacing the old ones and it won't break anything.

**Comment by fomalsd** [comment]
fixed in #2008
