### ISSUE TITLE
Missing chemistry reactions

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1808]
# Description
Some reactions seem to be missing from the Reactions.json file which are on the tg wiki:
[Reactions.json ](https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Resources/Metadata/Reactions.json)
[Guide to chemistry wiki](https://tgstation13.org/wiki/Guide_to_chemistry)

We're not sure which ones are missing exactly, so **comment below if you notice any**, or go through the wiki and check them all manually/with some clever scripting.

This will be an ongoing issue as there are a lot of reactions to check so **they don't need to be done all at once**.

Confirmed missing so far:
- [ ] Stabilizing agent

## Category
TODO

**Comment by Schneckenhof** [comment]
This may sound stupid, but I think "Oil" is actually missing. 

I was trying to figure out how the Json editor site I was using worked. (https://jsoneditoronline.org/) 

What I came up with was to load the json file in the editor and go down the Wiki and punching those names in the search button. Once they popped up I'd move that block of code up to the top so the Json file I was using would be in the same order as the Wiki for easy comparison. 

I didn't get very far, but when I searched "Oil" didn't actually pull anything up. Spraytan however did. Soo that might be one way to manually go through the code, but I will note that it isn't helped by the names in the code potentially not containing the test of the names as stated on the wiki. 

Suggestions or ways to do this more efficiently would be appreciated.

**Comment by Max-CGN** [comment]
Ok i think i found the missing Reactions... TGs reagents reactions are stored in these files(i think) and not all are in the json file... 

- [medicine.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/medicine.dm) is in
- [toxin.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/toxins.dm) is in
- [others.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/others.dm) is in
- [pyrotechnics.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/pyrotechnics.dm) is missing
- [slime.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/slime_extracts.dm) is missing
- [special.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/recipes/special.dm) is some strange code... i think its used to make some special and secret recipes 

i could and would add them but i am not very experiensed with unity, git and this whole project, so it would nice if someone could tell me if i am rigth and just need to add the missing things like that:

```
{
        "Name": "stabilizingagent_from_iron_oxygen_hydrogen_at_0K",
        "Results": {
            "stabilizingagent": 3
        },
        "Reagents_and_ratio": {
            "iron": 1,
            "oxygen": 1,
            "hydrogen": 1
        }
},
```

Edit: never mind... someone is allready working on that...
