### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#1814]
# Description
It is unclear to me what license the code is under, the README states:
> All code after commit 44695c862d6d84cfc99354d6dfba1f0b70f20407 on 2017/03/12 at 11:39 PM CET is licensed under GNU AGPL v3. All code committed after cd3e5a7, also grants project administrators the right to ammend this licence on a case-by-case basis, including, but not limited to, exemptions from the AGPL licence limitations.*

So from what I can read the code is under a GNU AGPL v3 license however, "project administrators" can change this at will? If so, doesn't this break the whole point of the GNU AGPL v3 license, considering the fact the project could become close sourced whenever a "project administrator" decides that they want to apply an exemption?
In addition, I don't see how this would be compatible with the code before cd3e5a7?

I'd love to see this resolved/explained so I can decide to contribute to the project. :)

**Comment by ghost** [comment]
@Ornias1993 I see you made the change (https://github.com/unitystation/unitystation/commit/8e75e76d46d29724c25f27a21245b8078453b68b) regarding these terms, could you perhaps assist in resolving this issue?

**Comment by DooblyNoobly** [comment]
Exemption clause has been removed. Closing this ticket.
