### ISSUE TITLE
Temporarily allowing connections with invalid SteamIDs

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#1819]
# Description
We are temporarily allowing connections with no or invalid SteamIDs.
## Category
TODO
## Detailed Bug Report
https://github.com/unitystation/unitystation/commit/b5cec08ebb3ae540869a56fe5691011d20e6092d#diff-e39eeae28bdf90e53e3527b11ede737fR90

**Comment by fomalsd** [comment]
fixed by #1822
