### ISSUE TITLE
Large amount of unhelpful log messages

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#1820]
# Description
There are a number of unhelpful log messages added in https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0. I'd love to correct this, but I have no clue what they are supposed to be doing.

## Category
TODO

## Detailed Bug Report
The ones that are the least useful:
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-303b2589ad5f32ef1db03fec8f40c87dR157
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-b3058f4d18503993b127a5e3c5c5aaa4R18
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-eeca8484590f41aaae78cf1cf6aced79R8
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-0b2a13cafa0dd324db2c0361bb1ab848R8
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-ecc26f825674ed675ab4daf65b5a7f4fR109

There are various slightly more useful ones as well, but these are really not helpful.

Example of one of the Log messages: HEYEYEYYEYEYE

**Comment by RedlineTriad** [comment]
They are most likely just tracing messages. You can either replace them with more sensible ones or remove them entirely.

**Comment by ghost** [comment]
Will do. Thank you.

**Comment by Bod9001** [comment]
https://github.com/unitystation/unitystation/pull/1764/commits/9d311c634b0874c144fa1374f7a6c20daa4575d1

was  Meant to clean up a few of the  logger.log but I obviously missed some
There's probably a few that have been commented out  On my branch that I'm working on Currently

https://github.com/Bod9001/unitystation/tree/Electrical-things

**Comment by ghost** [comment]
Nice, I just wasn't sure why they were there, that's why I made the issue 😄.
