### ISSUE TITLE
Girder deconstruction doesn't make tile passable on serverside B: 40

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1824]
## Detailed Bug Report
https://cdn.discordapp.com/attachments/443317202179981322/574252147642728478/Scr_2019-05-04_18.09.25.mov

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host as build, join from editor as engineer
2. Weld a wall, wrench off girder
3. Try walking onto that tile

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 40usd on a successful merge of a solution that satisfies the criteria above.

**Comment by JaytleBee** [comment]
I'll have a look at this one

**Comment by JaytleBee** [comment]
Alright, I think I got a fix. Testing it now
