### ISSUE TITLE
Previously contained items remain parented to container's current matrix after leaving container

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1825]
# Description

## Detailed Bug Report
![GIF](https://user-images.githubusercontent.com/10403536/57224743-e0c41f00-6ff9-11e9-8941-81e8c3b5c665.gif)

## Steps to Reproduce

1. Spawn a crate on non-station matrix (controllable shuttle) with items in it
2. Pull the crate out to the station matrix (including space)
3. Open it and **pull it back** onto previous matrix (so items are left behind on station matrix) 
4. Start moving shuttle - items will follow

**Comment by VitrescentTortoise** [comment]
I'm gonna check this out.
