### ISSUE TITLE
Multiple Pages support for NetTab system B: 100

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1837]
# Description
There are a lot of interfaces in original game that use different html pages for navigation. 
Pages can have totally different layout and element sets.
Trying to recreate such interfaces with a single screen and one dynamic list can be hard or impossible (I don't think PDAs will be possible without this)

So a support for page switching must be added. 

## Criteria
1. Hidden page updates shouldn't be sent to observers
2. Nesting of pages must be supported
3. Page switching should be reliable and easy to use

**Comment by fomalsd** [comment]
Should also add support for multiple dynamic lists per tab

**Comment by DooblyNoobly** [comment]
A bounty of 100usd will be awarded to the contributor on a successful merge of a solution to the criteria above.
