### ISSUE TITLE
Unable to attack with bare hands B: 40

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1845]
# Description
You can't attack other players/mobs/windows with your bare hands while in the harm intent.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Set intent to harm
2. Attack Ian/runtime/windows/another player
3. Notice nothing happens

**Comment by Aranclanos** [comment]
technically a todo rather than a bug

**Comment by Jibbajabbafic** [comment]
I suppose, I assumed it had already been implemented at some point but maybe that's not the case

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 40usd on a successful merge of a solution that satisfies the criteria above.

**Comment by Itsnotjames** [comment]
Working on this

**Comment by dapocalypse** [comment]
Its been 2 weeks, can i do this @Itsnotjames

**Comment by Itsnotjames** [comment]
I am still making steady progress on this. Sorry about taking so long.

**Comment by chairbender** [comment]
@Itsnotjames just warning you, I have some changes to MouseInputController in upcoming PR. Refactoring Guns to IF2 and adding other interaction types into it. I don't think it should step on your toes too much but just be aware. I'll update you once the PR is submitted so you can see.

**Comment by chairbender** [comment]
Okay @Itsnotjames , here's the PR I was talking about: #1936

**Comment by Itsnotjames** [comment]
Thanks for the heads up mate

**Comment by chairbender** [comment]
the PR I mentioned is merged
