### ISSUE TITLE
Research: Investigate suitability of Mirror networking system B: 55

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1846]
# Description

This job is to research the suitability of replacing unet in the project with Mirror.

Create a new branch on your fork and begin the process of removing unet and replacing it with Mirror. Try to understand all of the obstacles we will face to convert the whole project to mirror and list them below in the comments. Be really thorough as your research will help us decide if we should do the conversion or not.

The link to the mirror networking system: https://github.com/vis2k/Mirror
Documentation here: https://vis2k.github.io/Mirror/
Unity forum thread: https://forum.unity.com/threads/mirror-networking-for-unity-unet-replacement.425437/

### Some notes: 

They apparently have a unet -> mirror conversion tool so that would be worth investigating for this ticket.

If you have any questions about Mirror the team also have a discord, ask Mr_SquarePeg in discord for the link.

A bounty of 55usd will be awarded to the contributor on completion of research based on the above criteria and reported to the comments below. Only one contributor to apply. Please mention in comments below if you are taking on this ticket.

**Comment by JaytleBee** [comment]
Since nobody else seems to be doing this I think I'll have a look.

**Comment by JaytleBee** [comment]
Alright, bit of an update:
I tried importing Mirror into the project and it doesn't work. It seems that it's not seeing the classes in its *Runtime* folder and therefore spewing a lot of "type or namespace not found" errors. I have asked for help in their discord but haven't received a reply yet.

Note that just importing mirror into a fresh project doesn't produce this error which suggests that there's something in our project that's preventing it from loading correctly.

I have also had a look at their [List of deprecations](https://vis2k.github.io/Mirror/General/Deprecations) and checked each one for whether we use them. The list of all that might need at least some adaption is as follows:

- networkPort: Mirror uses Transports instead, might be an easy fix
- Couch Co-Op: Probably fine, I couldn't actually find any documentation for this
- Network Transform: Might be a head-scratcher, they didn't remove it but it now only syncs position and rotation. Haven't done a deep dive yet but it appears we use this one quite a bit
- Quality of Service Flags: We only use these in CustomNetworkManager.cs and Mirror does offer an alternative so it seems fixable

It should also be noted that mirror uses TCP by default, but it seems that UDP transports do exist.

Overall, if we can find a solution to this very strange bug then I think migration might be very possible. NetworkTransform seems to be the biggest problem while porting (though I've only really had a shallow look at that)

**Comment by fomalsd** [comment]
we don't use NetworkTransform, we use our CustomNetTransform that doesn't rely on NetworkTransform at all

**Comment by JaytleBee** [comment]
Alright, with a little nudge from @RedlineTriad I managed to fix that error and get Mirror to produce some useful errors. The migrations tool seems to work for scripts but removing components gets us these errors:
![image](https://user-images.githubusercontent.com/7951887/57838183-80d13380-77c4-11e9-8e4c-86282926fab4.png)

Another hurdle is that our CustomNetworkManager.cs would need to see some changes.

EDIT: Slightly future Jaytle here, I think the RegisterItem thing is actually relatively easily fixable? Anyway, I've been at it for a while now, I'm going to have another look after a short break

**Comment by fomalsd** [comment]
Does Mirror handle NetIDs differently?

**Comment by JaytleBee** [comment]
~~Doesn't seem like it, seems to me that the migration tool is a bit weird. I'll have another look at it now~~

Yup, NetIDs are uints for them. This opens a pretty big can of worms that I'm looking at right now, most notably that they don't have NetworkInstanceId.invalid

**Comment by JaytleBee** [comment]
Alright, the main problems seem to be converting to the different netIDs, refactoring our server and finding a way to get the components replaced (the converter seems to not really like doing that). Seems like a little bit of work but nothing out of the ordinary

**Comment by JaytleBee** [comment]
Some more findings:
- NetworkMessages seem to work as expected
- An LLAPI transport seems to exist (though it is deprecated)
- [Using multiple transports might work, though that may not be exactly what we need](https://forum.unity.com/threads/mirror-networking-for-unity-unet-replacement.425437/page-21#post-4067056)

**Comment by JaytleBee** [comment]
For reference, you can find what I currently have here https://github.com/JaytleBee/unitystation/tree/mirror
