### ISSUE TITLE
Station report runtimes if theres a player on the lobby

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1850]
# Description
![image](https://user-images.githubusercontent.com/701959/57602356-49992300-7535-11e9-8845-589bbcea9433.png)
```NullReferenceException: Object reference not set to an instance of an object
ChatRelay.PropagateChatToClients (ChatEvent chatEvent) (at Assets/Scripts/Chat/ChatRelay.cs:99)
ChatRelay.AddToChatLogServer (ChatEvent chatEvent) (at Assets/Scripts/Chat/ChatRelay.cs:62)
CentComm.SendReportToStation () (at Assets/Scripts/Managers/CentComm.cs:93)
CentComm+<WaitToPrepareReport>d__8.MoveNext () (at Assets/Scripts/Managers/CentComm.cs:76)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```
Station report throws a  runtime if theres a player on the lobby

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Start hosting
2.Stay on the lobby and do not join as a human player
3.Wait until the runtime pops out

**Comment by fomalsd** [comment]
yes, it's annoying. better be fixed as a part of #1727

**Comment by krille90** [comment]
@fomalsd Was this fixed?

**Comment by fomalsd** [comment]
I think so, yeah
