### ISSUE TITLE
There are two trees of prefab folders

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1851]
# Description
There are two trees of prefab folders:
`UnityProject\Assets\Resources\Prefabs`
`UnityProject\Assets\Prefabs`

They need to be merged into one, by personal preference, keep them under Assets\Resources
note: the prefabs under Assets have a lot of subfolders called Resources so unity can load them

## Category
TODO

**Comment by chairbender** [comment]
fixed by Jibby
