### ISSUE TITLE
Engine particles can be seen through walls

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1852]
# Description
![image](https://user-images.githubusercontent.com/701959/57602754-641fcc00-7536-11e9-813c-3e9d8929d61e.png)
Engine particles can be seen through walls (white circles on the top of the image)

## Category
BUG

**Comment by JesterX666** [comment]
![image](https://user-images.githubusercontent.com/32009105/71751418-7645d600-2e49-11ea-847a-2f7903d1b8ab.png)

Walls are now completly opaque.  Probably we can close this one.
