### ISSUE TITLE
Destroying windows/walls sucks in items

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1856]
# Description
Destroying window:
![iMRB940WlM](https://user-images.githubusercontent.com/4493127/57724228-2fb92680-7682-11e9-8815-923fa2acb69b.gif)

Destroying wall:
![pax3XUGwSE](https://user-images.githubusercontent.com/4493127/57724233-321b8080-7682-11e9-8873-3b7aaa553f4a.gif)

Expected behaviour would be for items to stay where they are

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Gather items around a window/wall
2. Smash window/weld wall
3. Watch items get sucked in

**Comment by Aranclanos** [comment]
The turfs spawn with no gas at all so they suck from the ones next to it
First time it happened it spooked me

**Comment by fomalsd** [comment]
I kinda like it to be honest

**Comment by Jibbajabbafic** [comment]
It's kinda cool, but also makes the game seem a bit unfinished, like we couldn't be bothered to implement a fix
