### ISSUE TITLE
Sounds and sprites for buckling people into chairs B: 40

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1858]
# Description
There should be audible and visual feedback when buckling someone/being buckled into a chair

**Note**: there is a buckled icon for the person buckled into the chair, but it's impossible to tell for anyone else based on the sprites

## Category
TODO

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Buckle someone into a chair
2. Notice there is no sound and the chair sprite doesn't indicate if someone is buckled or not

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 40usd on a successful merge of a solution that satisfies the criteria above.

**Comment by JaytleBee** [comment]
To be clear though, buckling and unbuckling doesn't seem to make a sound on /tg/ and the only change is that the chair is partly in front of the player. So we would need a new sound for that
![image](https://user-images.githubusercontent.com/7951887/58474261-e91bff80-814a-11e9-9690-1f9b9f2fbbee.png)

**Comment by Aranclanos** [comment]
thats only for "comfy" chairs, the normal metal ones that we have act exactly like /tg/ besides the fact that they dont turn you towards the chair's direction

**Comment by JaytleBee** [comment]
Yeah, so if we are sure we want this issue we'd need a new sprite and a new sound

**Comment by JaytleBee** [comment]
Seeing as nobody seems to be working on this I think I may have a go at it

**Comment by JaytleBee** [comment]
Quick update:
- I got the sound working
- I got the orientation partly working

One minor roadblock is that there's a very strange bug with the sync (if the client buckles themself to a chair then the players orientation is set correctly on all other clients but not on the own client)

**Comment by JaytleBee** [comment]
I took a bit of a break because I had another things to do, I'm going to continue work on this tomorrow

**Comment by DooblyNoobly** [comment]
JaytleeBee has met the criteria here. Closing this issue. Further buckling work is required but that is on the chair buckling logic itself not the visual feedback stuff.
