### ISSUE TITLE
Emergency oxygen tank doesn't fit in belt slot

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1859]
# Description
You should be able to equip the emergency oxygen tank in your belt slot

This should also make sure that auto equipping (pressing E) can equip it into the belt slot too.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Grab emergency oxygen tank from O2 locker
2. Click belt slot

**Also:**
1. Fill up pockets and suit storage with items
2. Hold emergency oxygen tank
3. Press E
4. Notice it doesn't go into the belt slot

**Comment by Schneckenhof** [comment]
Replicated Issue. Posting images for reference.

1) Grab Emergency O2 tank.
2) Click Belt Slot

Em O2 tank on ground.

![Em o2 Tank on Ground](https://user-images.githubusercontent.com/52392397/60481393-1f253580-9c5b-11e9-9496-6f1af95c6ec6.PNG)

Em O2 tank in Right hand

![Em o2 Tank in right hand](https://user-images.githubusercontent.com/52392397/60481419-40862180-9c5b-11e9-9a2f-2b3e74475301.PNG)

Noted that Em O2 tank will go on the **suit storage** slot if that slot is free and you manually click it.
However, Pressing E or clicking to move it to the **Belt slot** does nothing.

Other Verification:

Filled Pockets and suit storage up with random items to produce appropriate clutter. Emergency O2 tank in right hand. Belt Slot Empty.

![Em o2 Tank in right hand small and suit storage appropriately cluttered](https://user-images.githubusercontent.com/52392397/60481530-affc1100-9c5b-11e9-85c7-3979373b0cbc.PNG)

With the Em O2 tank selected, and the Belt slot empty, Pressed E. No result.

**Comment by chairbender** [comment]
Should be easily fixable after #2245

**Comment by cvdva** [comment]
Currently working on a fix for this issue now

**Comment by chairbender** [comment]
@cvdva just to help make sure you're on the right track, all that should be needed for this basically is to give the small oxygen canister prefab the "Belt" ItemTrait in its itemattributes component, there shouldn't need to be any code changes.

**Comment by jackpotttt** [comment]
Oh my bad, didn't realize someone was working on this

**Comment by RedlineTriad** [comment]
@jackpotttt are you already on the discord? makes communication easier.

**Comment by jackpotttt** [comment]
@RedlineTriad I am, but I haven't used it much yet. Still learning the ropes!
