### ISSUE TITLE
Bag slots aren't aligned properly with UI

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1861]
# Description
The bag slots should be shifted to the left to be above the backpack instead of off to the side.
![image](https://user-images.githubusercontent.com/4493127/57725965-537e6b80-7686-11e9-8468-a2a09977760c.png)

(perhaps align it to the third or fourth bag slot if it fits)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open backpack
2. Notice the slots aren't aligned properly

**Comment by fomalsd** [comment]
would also be nice to get rid of this bunch of warnings about using deprecated transform methods every time when backpack is opened

**Comment by StrawberryMoses** [comment]
Did this get shadow fixed somewhere? Booting up on develop and putting it in full screen: 
![Screen Shot 2019-09-28 at 10 35 35 AM](https://user-images.githubusercontent.com/8854773/65818912-c7f01c00-e1db-11e9-9fa9-ad901fd83fdb.png)

**Comment by fomalsd** [comment]
Bod probably sneaky fixed it during sprite refactor
Warnings are still present though
![image](https://user-images.githubusercontent.com/10403536/66196939-e9904e00-e688-11e9-9dde-fa9a4463945c.png)
