### ISSUE TITLE
Shards ejected from window get stuck on you and kill you

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1865]
# Description
When breaking a window from space the shards continuously pummel you until you drop dead like so:
![blqpgULCbO](https://user-images.githubusercontent.com/4493127/57728544-1321ec00-768c-11e9-8bd8-8ad487792c9a.gif)

They should hit you once and continue flying past you.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go into space
2. Bash window until it smashes
3. Die

**Comment by VitrescentTortoise** [comment]
I'm going to see if I can fix this.
