### ISSUE TITLE
Masks don't autoequip into other slots

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1866]
# Description
Auto equipping a mask when you already have a mask on should put the mask into a different free slot.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get 2 masks
2. Equip one
3. Autoequip the other (with E)
4. Notice it stays in your hand even though pockets are free

**Comment by vgwiss** [comment]
I can work on this! I need a good first bug to work on.
