### ISSUE TITLE
Stacking system for Items

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#1870]
# Description
This is so you can carry multiple floor tiles/whatever you need in one item, this should only apply to certain items, 

## Category
TODO
Some of the expected behaviour, 
they should automatically stack when dragged over others on the floor,
they should return one if you click on them with an empty hand when the stack is on the other hand, 
allow for different sprites according to the amount in the stack
combine with other stacks if you click on them with the stack in your hand

**Comment by Aranclanos** [comment]
oinments and bruisepacks need it too

**Comment by Jibbajabbafic** [comment]
I think it'd be nice to have a little number in the corner to show how many items are in the stack too
