### ISSUE TITLE
Make some suits able to hold big oxygen tanks in suit storage

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1877]
# Description
Only some specialised suits can hold big oxygen tanks in their suit storage.

There should be some kind of flag on all exosuits to allow them to hold certain special items such as big oxygen tanks.

Example of some of the suits that should be able to (might be missing some):
- Any hardsuits (EVA, engineering... etc)
- Bio suits
- Bomb suits

You should also ensure the feature works correctly with autoequip.

## Category
TODO

**Comment by Chachitataya** [comment]
Can't seem to replicate with Captain's hardsuit (roundstart suit) and Mining hardsuit. 
Is this still an issue?

Edit: You can wear a large tank regardless of exosuit or clothing slot item - or lackthereof. 
Should this be a feature request to disallow large tanks from being equipped without an appropriate exosuit?

**Comment by DooblyNoobly** [comment]
Yep, the behaviour should match TG. So if players can equip large tanks without a suit then that needs to be fixed. Detecting exosuits will be tricky tho because of the way unicloth is set up, so that will need to be sorted out.

**Comment by chairbender** [comment]
This should be covered by #2248

**Comment by PerfectTangent** [comment]
fixed with #5684
