### ISSUE TITLE
Player can get stuck while walking on headless server B: 120

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1898]
# Description
Player can randomly get stuck after walking for a while on steam server.
Seems like a clientside issue because restarting game and rejoining helps (until you get stuck again).
I'm not sure it's exclusive to steam server, but for some reason it's easiest to reproduce there.
Was likely introduced after #1791 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join steam server
2. Run around station

**Comment by chairbender** [comment]
I had an issue like this playing locally as client against server hosted in editor. It happened when I encountered some wind while walking down a maint tunnel and was pushed back against a crate. I fixed it by grabbing the client as the server player and dragging them a bit. So confirming it may be related to wind.

**Comment by DooblyNoobly** [comment]
Yeah I have a feeling this might be related to wind push. Either way, its pretty bad now on current steam build. I'm going to put a decent bounty on this to see if we can get it sorted out asap. 

Btw my ping to the steam server was 332ms when I was testing earlier. Not sure if the bit of lag is causing the problem to happen more often. I can walk around for about a minute before I get stuck.

Contributor will receive a bounty of 120usd on a successful merge of a solution that resolves the issue above.

**Comment by Aranclanos** [comment]
I'll take a look

**Comment by Emma3DSS** [comment]
Im also takin a look

**Comment by Emma3DSS** [comment]
This issue seems to occur more frequently when entering a room, could this have to do with Gases inside closed airlocks being frozen?

**Comment by DooblyNoobly** [comment]
Issue was fixed in #2048
