### ISSUE TITLE
Assemble item and machine prefabs

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#19]
This is the first basic run of item and machine prefab assembly. 

Basically you just need to find a kitchen or bar related sprite, create a GameObject, add the sprite as a child and turn this into a prefab. Create any folders that are needed to organize all the items / machines. 

Then we will go back and work on each item specifically as needed with some items sharing components etc. This job will be assigned to everyone, if you have a spare 10 minutes then please help by contributing to the item/machine prefabs.

**Comment by DooblyNoobly** [comment]
![kitchenref](https://cloud.githubusercontent.com/assets/20813925/20636893/fe15980a-b3c1-11e6-9865-bf49cad2001f.png)

**Comment by kaffo** [comment]
Dunno why the entire cast was assigned to this.
@DooblyNoobly Haven't you already pretty much done all this?

**Comment by DooblyNoobly** [comment]
@kaffo This was just an ongoing thing if people were looking for easy things to do to help out. There is still heaps of items needed: Donuts, water, milk, donk pockets, glass beaker, salt / pepper shaker etc

**Comment by kaffo** [comment]
@DooblyNoobly Roger!
