### ISSUE TITLE
Missing/old UI elements

### ISSUE THREAD

**Issue by KyleFN** [unitystation/unitystation#1904]
# Description
There are several buttons missing that are present on modern /tg/ and goon code, and also some icons have been changed so their meaning is more clear.

## Category
TODO

## Detailed Report
![](http://i.imgur.com/wFDKbqw.png)
The right side of the UI in modern /tg/ has a few additional buttons for helpful features:
- Rest - lying down for surgery, fitting many people onto one tile in escape pods, getting past people who have on Disarm/Grab/Harm intent, etc
- Languages menu - for cyborgs changing default language to binary, etc
- Create an area - not used this personally but it's a feature
- Crafting menu - for food, improvised weapons etc

Different icons (Done):
~~- Throw and Drop are text rather than icons. This is more clear than the icons were plus it saves on UI space~~
~~- Resist is text as well which is again more clear than the icons were (especially since it could mean drop and roll to put out a fire, as well as breaking out of grabs)~~

**Comment by Bod9001** [comment]
I would add an update category to this but I don't know what to name it, 

out of date from source?
Need update for source parity?

**Comment by PerfectTangent** [comment]
Since we've moved on from the classic UI to our new version, and we've made some slight gameplay changes (and /tg/, too, for that matter, like combat mode), and the remaining desired elements are or can be covered by their own issues (like #6158), I am closing this issue.
