### ISSUE TITLE
Player keeps sliding when slipped indoors

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1919]
# Description
Players stunned by slip keep sliding with original speed until they encounter a solid object or stun is removed
It's appropriate for space, but not indoors

## Steps to Reproduce
![GIF](https://user-images.githubusercontent.com/10403536/58889250-1ed76000-86d8-11e9-8102-8904721b366f.gif)

## Note
When fixing this bug, make sure that high pressure ejection into space works as it did before:
![pressure_ejection](https://user-images.githubusercontent.com/10403536/64586241-6559ec00-d3a4-11e9-8d3c-dffe1a476112.gif)

**Comment by fomalsd** [comment]
Also there is a regression: walking slowly on wet floors still makes players slip

**Comment by chairbender** [comment]
just a note - this should be fixed by #1935

**Comment by chairbender** [comment]
This didn't get fixed in that, removing In Progress
