### ISSUE TITLE
Buckling to a chair doesn't update the direction you are facing on client B: 25

### ISSUE THREAD

**Issue by JaytleBee** [unitystation/unitystation#1931]
# Description
![chair_netbug](https://user-images.githubusercontent.com/7951887/59150908-e9f64080-8a2a-11e9-993c-7156f1716ec6.gif)
(client on the left, server on the right)

When buckling yourself to a chair on the client, the direction you're facing is updated for all other clients and the server but not for you.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start the game with a separate server and client
2. On the client, buckle yourself to a chair while not facing the direction the chair is facing
3. Notice that you are still facing that direction.

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 25usd on a successful merge of a solution that resolves the issue above.

**Comment by dapocalypse** [comment]
I guess I'll do this one

**Comment by dapocalypse** [comment]
Actually nvrmd

**Comment by dapocalypse** [comment]
Actually yes

**Comment by dapocalypse** [comment]
cant replicate

**Comment by chairbender** [comment]
I can. I'll take a look since I worked on buckling and player direction sync
