### ISSUE TITLE
TODO: Finish Medbay Cloner functionality B: 300

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1933]
# Description

The computer system to control the Medbay Cloner has been finished. Now we need to add the ability to scan bodies and store their DNA as records in the computer system (screens have already been completed) and to clone somebody from the DNA records (DNA strings can be retrieved from the Health components on the player).

## Criteria:

- Add the ability to drag and drop a player into the cloner tube (drag and drop has been implemented for chairs, so look at the logic there to enable the action on the cloner)
- Determine all possible states of the cloner (empty, occupied, cloning, powered off) and change the sprites/animations to reflect these states
- Add the ability to lock the cloner 
- Add the ability to scan someones blood to retrieve their DNA and create a record for them in the records list
- Check to make sure a DNA record does not exist before adding a new one to prevent duplicates 
- Add the ability to clone someone if they are dead. You will need to come up with some way that allows the dead player to accept the request to return to their body. You could do this anyway you seem fit just as long as the functionality is there.
- While cloning someones dna and after some time has passed, spit out a new, alive, naked spessman with the cloned player in full control of it

Notes:
We will cover DNA damage at a later date

Contributor will receive a bounty of 300usd on a successful merge of a solution that satisfies the criteria above.

**Comment by Aranclanos** [comment]
Gonna do this one

**Comment by dapocalypse** [comment]
Are you still doing this?

**Comment by Aranclanos** [comment]
aye

**Comment by DooblyNoobly** [comment]
Increasing bounty to 300 as this is now a high priority

**Comment by dapocalypse** [comment]
Are you still doing this?

**Comment by Aranclanos** [comment]
This is finished and working in develop, but before closing please make sure I didnt misinterpret any point or if there's any bug or issue with it that I should tackle

**Comment by chairbender** [comment]
Oh, I thought it wasn't fully working. When I tried to scan host as client it didn't seem to do anything.

**Comment by Aranclanos** [comment]
on current develop? I commited the references from the console to the scanner in the map four days ago

**Comment by DooblyNoobly** [comment]
Ill do some thorough testing today and get back to you with results

**Comment by DooblyNoobly** [comment]
@Aranclanos nice work! This is really cool.

Few issues I want fixed up before closing this ticket:

1: Once you have been cloned you cannot drag your body out of the DNA scanner. Infact just moving around makes your old body go in and out of the DNA scanner for some reason:

![dnascanner](https://user-images.githubusercontent.com/20813925/60774756-67ad8900-a15c-11e9-8433-0e6b3ce467e1.gif)

2: Dragging and dropping a corpse does not add it to the DNA scanner.

3: Corpses that have been scanned and cloned cannot be dragged out of the scanner. Well they can but they are not being updated over the network so they remain on the scanner for everyone else (Host cannot drag the corpse for some reason but the client can. Client is dragging it in this gif):

![NoNetworkT](https://user-images.githubusercontent.com/20813925/60774795-ed313900-a15c-11e9-9da8-04b5af99c439.gif)

I tested with scanning the host as client and it all seems to work for me. So Chairbenders comment might be from playing an older version.

I think once this is all finalized I'll make a bounty for stripping clothes and items so you can get your stuff back after being cloned.
