### ISSUE TITLE
TODO: Security Records Console B: 280

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1934]
# Description

This job is to create the Security Records Console prefab, the NetTab GUI and the security records system itself. 

![image](https://user-images.githubusercontent.com/20813925/59155367-195c8a00-8acb-11e9-8788-78cec2c01a71.png)

## Criteria:

- Create a Security Records Console prefab (see other consoles on what components are needed to build it)
- Map the new console somewhere in security on outpost station (you may want to PR this change as soon as you do it to avoid scene conflicts later on)
- Develop a central place to store all security records for the map/round. Each time a security console is opened, records will need to be updated from this data store on the server
- Create the Security Records Locked screen
- Add the ability to insert an ID card to allow access to the records and to change records
- Add the main page that shows a list of all the player records and a color code to quickly show their status
- Add the ability to search for player records
- Add a player record to security when a new player joins. Capture their appearance, job title and name for the record
- Add the ability to change and update records
- Determine the possible security states a player can have and add the state value to the security records
- Add the ability to leave notes on a players record
- Add ability to log out of the records at any moment

For reference here are some screenshots of current sec records GUI from byond:

Login screen:
![image](https://user-images.githubusercontent.com/20813925/59155482-c0422580-8acd-11e9-8bcf-a34b7ba07b4f.png)

Records list with search bar at the top:

![image](https://user-images.githubusercontent.com/20813925/59155502-f67fa500-8acd-11e9-92e6-fcb44690dc8f.png)

An individual record:

![image](https://user-images.githubusercontent.com/20813925/59155505-229b2600-8ace-11e9-9a7b-2adab1ce091a.png)

Contributor will receive a bounty of 280usd on a successful merge of a solution that satisfies the criteria above.

**Comment by vlandemart** [comment]
I'll do this one

**Comment by dapocalypse** [comment]
Are you still doing this?

**Comment by vlandemart** [comment]
Yes.
Hope to finish it before 25th with Stritirok's art

**Comment by DooblyNoobly** [comment]
Increasing bounty to 280 as this is now a high priority

**Comment by dapocalypse** [comment]
Are you still doing this?

**Comment by vlandemart** [comment]
Yes, currently finishing it.
