### ISSUE TITLE
Switch Chat System to use Text Mesh Pro for styling capabilities

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#1937]
# Description
Text mesh pro has the ability to let us define a set of global styles we can apply in chat messages by doing "<style name=stylename>Here is my text!</style>". Additionally, TMP is supposed to be a best practice to use instead of Text, from what I gather.

This will be very useful for maintaining consistent styling across the game, since each chat message that wants to use a particular style can simply name the style, and we can globally tweak how it looks without having to edit each string that's using that style.

A working example of this is in tmp-styling branch
https://github.com/unitystation/unitystation/tree/tmp-styling

Done when the chat system supports using it and there are some examples of styles defined for common types of messages. Ideally we should also find any strings which use HTML tags and replace them with styles so they can be controlled globally.

**Comment by daalta** [comment]
Chat bubbles have been switched to TMP a few weeks ago.

**Comment by NoooneyDude** [comment]
Does the chat system now use Text Mesh Pro? #2532 seems to allow it now, at least.

**Comment by ThatDan123** [comment]
Chat entries are now TMP
