### ISSUE TITLE
CPR for unconscious players

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1941]
# Description
At the moment there's no way to recover players from deep crit, oxygen loss keeps rising and they die eventually.
Need to add ability to CPR crit players to make them breathe again, preferably with a progress bar

**Comment by chairbender** [comment]
How do you trigger this interaction? Right click menu? Left click on help intent for a deep crit player?

**Comment by fomalsd** [comment]
I'd say left click w/help intent
