### ISSUE TITLE
Opened lockers can appear closed for late joiners

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1951]
# Description
![image](https://user-images.githubusercontent.com/10403536/59683170-26fac980-91c7-11e9-8a78-315d8a130cb9.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host from build, open some lockers
2. Join from editor, look at lockers

**Comment by chairbender** [comment]
Looking into it
