### ISSUE TITLE
Bodies appear underneath lockers

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1952]
# Description
![image](https://user-images.githubusercontent.com/10403536/59683335-85c04300-91c7-11e9-9c4f-70fffac3cf8d.png)
Player corpses appear underneath lockers when they are opened (instead of being above)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in build, join in editor
2. Let one of players onto opened locker, stab him into crit (but not to death)
3. Close locker
4. Wait till he's dead
5. Open locker
^ Reproduction can likely be simpler, but I only tried following scenario

**Comment by chairbender** [comment]
Bodies go in the blood layer. Probably need a new one so it's above the machines layer.

**Comment by chairbender** [comment]
Lookin into it
