### ISSUE TITLE
Help intent predictive swap needs rollback for swappee

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1953]
# Description
![GIF](https://user-images.githubusercontent.com/10403536/59695976-a8a82280-91da-11e9-9417-77360972b08c.gif)
When player you're trying to swap with is pulling something, his position isn't reverted for you

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. As Player 2, start pulling a mob and come next to a wall
2. Approach with Player 1 like on the gif and try to swap with Player 2
3. Your Player (1) will be rolled back but other player won't and will remain in incorrect position until moved

### Note
But if there was something solid like a locker then **predictive swap should be reverted for both parties**

**Comment by chairbender** [comment]
It was my intention to not allow swap when someone is pulling something, period. Complicates things otherwise.

**Comment by fomalsd** [comment]
should revisit this for 0.4
