### ISSUE TITLE
Clean up and fixing DoorController Code

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#197]
- [x] Make the code more presentable
- [x] fixing doors animation, e.g. pub door losing glasses

**Comment by DooblyNoobly** [comment]
Well at least DoorController is cleaned up. I will clean up my coroutines when I get around to it, at the moment they are just mapped to the old keyframe values. I will put in a while loop for door open and handle light flash separately. I also need to create a separate component for vertical opening doors. These two components will also handle the door broken and door hacked animations (eventually).
