### ISSUE TITLE
Player sprite blinks when going out from a closet

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1970]
# Description
When leaving a closet, the player sprite appears, disappears and re-appears in a quick succession 

## Category
BUG

## Detailed Bug Report
https://cdn.discordapp.com/attachments/312454684021620736/593202325229797377/uC477BeUXn.mp4
.mp4 files are too high tech for github, a small video of it happening

**Comment by vladb99** [comment]
Working on it.
