### ISSUE TITLE
Having the player prefab open brings up errors

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1986]
# Description
![image](https://user-images.githubusercontent.com/701959/60535837-5fc49380-9cdb-11e9-977a-a6120377f661.png)

## Category
BUG

## Detailed Bug Report
If you open the player prefab on the editor, the console will slowly spam you with errors

**Comment by chairbender** [comment]
It's due to the gizmo being on, trying to access registerTile.WorldPosition when I'm guessing registerTile is null:
Vector3 regPosS = registerTile.WorldPositionServer;

**Comment by NoooneyDude** [comment]
I couldn't reproduce this, with all gizmos being on. Perhaps it has been fixed?
