### ISSUE TITLE
TransferBody() generates a warning

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1987]
# Description
due to #1985 now transfering bodies will generate warnings

## Category
BUG

## Detailed Bug Report
This line was added:
NetworkServer.ReplacePlayerForConnection(new NetworkConnection(), oldBody, 0);

it creates a fake networkconnection to replace the original/old body in TransferBody()
Without it, the connectionToClient variable of the old body's NetworkIdentity component would still reference to the client, causing errors in the game.

Example: closing a locker on top of a human makes the camera move on top of the locker, because the old body still references their old client player, if you closed a locker on top of its old corpse, his camera will suddenly teleport on top of the locker, even if he was in another part of the station.

**Comment by fomalsd** [comment]
I think it's been fixed
