### ISSUE TITLE
TextureDataRequest error when using the devspawner

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1988]
# Description
![image](https://user-images.githubusercontent.com/701959/60536938-bd59df80-9cdd-11e9-9ce0-ccb8d79ab968.png)
When using the devspawner this error seems to come up, it doesnt seem to affect anything 

## Category
BUG

**Comment by Jibbajabbafic** [comment]
Happens even without using the dev spawner, seems quite random. I think it started after #1879

**Comment by NoooneyDude** [comment]
I don't think this error occurs anymore. This issue could probably be closed.
