### ISSUE TITLE
Add version checks for clients connecting to a server

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1993]
# Description
The server should be able to check clients have the same version of the game when they connect using a checksum/crc. 

If they fail the check they should be kicked and shown an appropriate error message, and how to update their game to the right version.

## Category
TODO

**Comment by Bod9001** [comment]
Is it necessary to do a checksum?
Surely just checking the version Number Would be all that's needed?
since you could spoof a checksum If you wanted to be naughty

**Comment by Jibbajabbafic** [comment]
Yep you can still spoof it but I guess it's a little more difficult than simply changing the build number, Doobly suggested checksums/crcs  so I figured he had something in mind

**Comment by Bod9001** [comment]
Having a little bit of flexibility with client side mods would also be cool, like Texture packs Since you'd only need to change the Atlas and make sure it's packed the same way as the current version

**Comment by Jibbajabbafic** [comment]
That said, the way we're setting up the networking should mean that even if the client is hacked they shouldn't see any extra info that they're not supposed to have so a basic build number check would be enough for now

**Comment by Bod9001** [comment]
yeah, Sounds good

**Comment by Bod9001** [comment]
from looking through the code looks like it's partially implemented already, you just need to make an automatic kick and fix the dialogue box since that's broken currently, the only references seem to be commented out and it doesn't exist where it thinks it should be if you uncomment the 
dialogue box pop-ups
