### ISSUE TITLE
Add admin auth system B: 70

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1994]
# Description
The server needs a way to tell admins and non-admins apart to restrict access to debug/admin tools.

Ideally this will use our own account system or the steam one, and there should be a list of admins stored in a file on the server initially.

An admin panel and commands will come later.

Related to #2273.

## Category
TODO

**Comment by Expedition13Admin** [comment]
Copied this issue to [expedition13/Core](https://github.com/expedition13/Core/issues/12)

*edit*
It would be nice when one uses a plugin to copy an issue, said plugin actually informs you when it is going to post comments.

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 70usd on a successful merge of a solution that resolves the task request above.
