### ISSUE TITLE
Map Manager

### ISSUE THREAD

**Issue by unitystation** [unitystation/unitystation#2]
This will be the Controller of all the maps

Update: Eventually map loads will be handled by photon, at the moment everyone just appears in the kitchen-construct scene and this is fine for the prototype.

**Comment by tgstation-unity** [comment]
Reference img:

![kitchenref](https://cloud.githubusercontent.com/assets/23096507/19833663/95f91484-9e8d-11e6-83ac-1e2a0baac05e.png)

**Comment by kaffo** [comment]
Unassigned myself from this one.
While the tile stuff I did day one was a hack, it worked alright. But we really badly need a proper map maker/parser.
To that end we either need:

- A standalone map creator which saves to a file we can parse ingame
- A script to extend Unity to allow us to generate a map file/prefab

Regardless, we ***cannot*** ask people to have to recompile the game to edit a map, this isn't 2004.
Whoever ends up doing this, it's likely going to end up a project on it's own.

**Comment by DooblyNoobly** [comment]
Yup, at the moment each map needs to be in its own scene for photon. Then when we eventually set up asset bundles, each scene will be added to a bundle. This way you can avoid having to rebuild a new client each map alteration etc and the unity editor itself becomes the quasi map editor.
