### ISSUE TITLE
Test map movement system a little wonky

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#200]
the issue of the old system comes back, but instead of walking inbetween tiles, it teleports you to the right tiles and you continue walking, but the issue with it is that that teleportation is quite wonky, and not pretty to look at, since  a lot of ss13 taser evading maneuvers require a lot of running in circles.

**Comment by krille90** [comment]
sounds like it could be fixed by an interpolation

**Comment by TheBimmer231** [comment]
define interpolation

**Comment by krille90** [comment]
https://en.wikipedia.org/wiki/Interpolation

e.g. player position starts at 0 and ends at 1, instead of "teleporting" the player, we move him incrementally (per frame) closer to 1.

**Comment by DooblyNoobly** [comment]
new clamp method implemented with interpolation :)
