### ISSUE TITLE
You can pick up wrenched down pipes

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#2013]
# Description
![image](https://user-images.githubusercontent.com/701959/60889203-e8d55080-a22e-11e9-9ea6-84da14f05735.png)
Spawn and try to pick up any pipe, you'll be able to hold it, unwrenching/wrenching them down doesnt seem to change anything

## Category
BUG

**Comment by RealPlanet** [comment]
Working on it.

**Comment by badbon** [comment]
You can also pick up the oval thing that looks like that. Basically you can pick up floor fixings or whatever the heck theyre called.

Was about to open this issue yesterday.

**Comment by badbon** [comment]
If you go south of station you can pick it up, so you don't even need to spawn it there.

**Comment by chairbender** [comment]
as requested by @Aranclanos I will take a look at this

**Comment by chairbender** [comment]
should be as simple as removing pickupable (Narrator voice: "It wasn't")
