### ISSUE TITLE
Large Fires Cause Large Lag

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2015]
# Description
With the recent changes that make things capable of being damaged by fire, large fires are causing quite a bit of lag.

# How to cause large fires
1. Go to atmos and pull an atmos canister out into the hallway.
2. Open the canister and let plasma fill the hallway. Wait 10-20 seconds.
3. Spawn some welders. Ignite and immediately throw them to help spread the hotspots.

When the fire starts growing and spreading that's when you know you're about to get lag.

# Initial Analysis
I've gone through and profiled some things. The bottleneck is in **ReactionManager.Expose**, specifically where it gets the IFireExposable objects at the specified location and calls OnExposed on each of them. This creates lots of GC and takes lots of time.

Trying to get the objects using matrix.Get appears to create lots of GC, probably because matrix.Get creates a new List with each invocation. We should find a way to avoid this. The big complication I ran into with trying to avoid this is that you can't safely iterate through the value returned from matrix.ServerObjects.Get or matrix.ClientObjects.Get without getting the InvalidOperationException "collection was modified" error. This is most likely because atmos is happening on a different thread - so as it tries to iterate through those collections while they are being modified by a different thread. If we can find a way to iterate through these objects without getting this error it might eliminate some GC. We don't need to save them in a list - all we need is to call OnFireExposed on each object.

Another issue is the Integrity.OnWillDestroy logic being called a bunch when there's a big fire burning things up. Spawning ashes is eating up some performance. Precaching the ashes could help (PoolManager has a method for doing this).

Doobly suggested possibly creating a new job for the damage, but I'm not quite sure how that would work.

It might be easier to solve this in 2019 using DOTS / ECS. There's lots of resources on using these things. I'm less sure how we can do something similar in 2018.3.

**Comment by RedlineTriad** [comment]
It is also important to turn down the log levels when testing as they can actually become the bottleneck, and in my case even lag the computer so hard that audio starts repeating and a forcefull power-down is necessary.

**Comment by chairbender** [comment]
it's possible this has been somewhat improved with the shuttle collision PR, haven't tested it out yet

**Comment by fomalsd** [comment]
Performance during large fires got decent:
![6V9HpPt4Mf](https://user-images.githubusercontent.com/10403536/69720636-ff5f4400-110a-11ea-91fb-31b9bb189087.gif)
