### ISSUE TITLE
When on OpenGL renderer, the scale option is set in to an invalid Setting On first Start

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2016]
# Description
This results in wonky Non-pixel perfect scaling
## Category
BUG

## Detailed Bug Report
This results in wonky Non-pixel perfect scaling
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go into unity and change the renderer for your platform to OpenGL  Core
2. Build it
3.Load up the game and observe the scale option slider Giving incorrect values

**Comment by NoooneyDude** [comment]
Is this still relevant since #4234, #4245 and #4261?

**Comment by jamessimo** [comment]
I have been testing open GL a lot recently and I cannot replicate this issue
