### ISSUE TITLE
a standard way to test if a game object is a certain object E.G. a crowbar

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2022]
# Description
So you want to test if someone has a fire extinguisher in there inventory, 
 Currently the only ways to observe what the item is, is to
A Get component for a component that's only on that item
B Test the name of the game Object

## Category
TODO

## Proposal
I say to have some type of standard systems items like item attributes that is unique to every prefab item, so you can easily tell that yes this is a clownmask/Fire extinguisher/any other item you could think of

Is only meant for doing generic interactions, like construction you just want a fire extinguisher (As one of the parts needed for the construction), you don't want to have to add custom code for that simple interaction

**Comment by Bod9001** [comment]
ok, What do you guys think about adding 
PoolPrefabTracker 
to every object/item Prefab?

I've tested it and it does allow a reference for itself
This would make it easier to do tests like I was Talking about earlier
And it Already gets added to Game objects that are spawned in runtime

**Comment by chairbender** [comment]
Not sure if this is the way to go. 

I think the Unity philosophy kind of is, an object IS what its components are. So if you are trying to indicate that an object has a particular capability, it should be part of a component. Furthermore, there are probably some objects which can be used to perform the same task, so it wouldn't be right to check the exact object type - rather, check if the object has the capability to be used in that interaction. For example, you mention clown mask, maybe other types of masks could be used, so it wouldn't make sense to check if an object is a clown mask, rather you'd want to check if the object was "mask like".

I did this with the Tool component. I'm sure something similar can be done for construction. Maybe a ConstructionMaterial component? It also provides a good way to encapsulate logic related to construction.

**Comment by chairbender** [comment]
this is implemented now in the Traits system https://github.com/unitystation/unitystation/wiki/Item-Traits-System

**Comment by chairbender** [comment]
...which isn't merged yet, so reopening.

Will be fixed in #2245
