### ISSUE TITLE
BUG: Taking an Object Image Snapshot of a player causes NRE B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2024]
# Description:

When taking an image snapshot (for things like the security records) an NRE is thrown because the method [TakeObjectSnapShot(GameObject, Vector3, Quaternion, Vector3)](https://github.com/unitystation/unitystation/blob/4b26e52701d0d6628b13361e0e78c7028db29842/UnityProject/Assets/Scripts/Util/ObjectImageSnapshot.cs#L50) instantiates a completely new Player object and then Destroys it at the end of its use. Causing the PlayerSync script that was on it to throw an NRE.

## Critera:

- Develop an alternative way to capture the source textures to use in the creation of the new object image texture
- Test in multiplayer with 2 clients on the Security Records console to confirm that no NRE exists

## Extra info:

Some obstacles you will face:
- The object you are taking a snapshot of could be facing in a direction that is not suitable for your needs (like a player object facing right instead of down). That is why the current method instantiates a copy of the target object and then destroys it, so that the images are always facing down. You will need to come up with a way to force the sprites to show the down sprites on all of its SpriteRenderers. Creating a public method on the PlayerSprite system that returns all of the down sprites would be useful here.

Contributor will receive a bounty of 50usd on a successful merge of a solution that satisfies the criteria above.

**Comment by Aranclanos** [comment]
I'll take a look
