### ISSUE TITLE
Energy weapon projectiles arc way too much

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2031]
# Description
I think the idea was to simulate the range dropping off, but the arc is way too much.

![](https://cdn.discordapp.com/attachments/312454684021620736/601481959402635334/AeMLGuvhuR.gif)

Ideally the projectile shouldn't move onto the tile below the target when firing in a straight line. Instead, the projectile should fly straight until it reaches the end of the gun's range, and then the projectile should arc a a small amount with the projectile disappearing once it hits the imaginary 'floor'.

![](https://cdn.discordapp.com/attachments/312454684021620736/601487827989037056/unknown.png)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Grab energy weapon (like the tazer)
2. Shoot in a straight line
3. Notice ridiculous arcing

**Comment by DooblyNoobly** [comment]
I don't like the drop at all. It is actually veering off to the right which a bullet does not do in real life. If it were to drop here then the size of the bullet should shrink until it hits the floor and leave a mark or a spark or something to show it has hit the ground. IMO this isn't a good feature and should be removed all together. Keep it basic ss13. The taser bullets move slow enough that the target has a chance to get out of the way so its pretty balanced as it is.

**Comment by DooblyNoobly** [comment]
I actually think someone turned on the gravity flag by accident and committed it to the prefab
