### ISSUE TITLE
Right-click shows items that are obscured by a floor tile

### ISSUE THREAD

**Issue by 0xJoey** [unitystation/unitystation#2041]
# Description
Right clicking any tile containing a hidden cable will reveal the cable in the right-click menu.

## Category
BUG

## Detailed Bug Report
A cable is hidden if the tile it is on is does not have `LayerType.Base` as LayerType, which there currently is a correct check for. However, cables occur on layer 22, which the check does not correctly do, currently(instead, it checks if `obj.layer < 1`).

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Right-click on any tile that is covering a cable

**Comment by Bod9001** [comment]
similar to #1797
