### ISSUE TITLE
Compatibility of Unity and (A)GPL

### ISSUE THREAD

**Issue by raymoo** [unitystation/unitystation#2057]
I'm not a lawyer and this isn't legal advice.

The GPL and AGPL require that when you redistribute a work, you license the complete work under the same license (GPL or AGPL, whatever the original license was). Since Unity games include Unity and link against Unity, the complete work includes the components of Unity that are included in the game. Unity does not allow you to relicense it.

If you release a Unity game under GPL, it doesn't cause any immediate problem, since the terms of the GPL are restrictions on the recipient of the software, not on you as the author. However, if that recipient now wants to redistribute your game or modifications to it, they are required to also redistribute Unity engine under the GPL, which they can't do. So they can't legally redistribute your software.

The larger problem happens once contributors start contributing back to the main codebase. The contribution itself may be an infringement since the contributor is sending their change back. I am pretty sure though that once the contribution has been integrated into the repository, it is an infringement to distribute the repository since it then contains software licensed from the contributor, under the GPL. Either Unity is relicensed, violating the Unity license, or it isn't relicensed, making it violate the GPL instead.

The practical consequence is that Unitystation contributors or Unity may have standing to file copyright complaints (like DMCA takedown requests) or to sue. I don't think it's likely that Unity will care, but it's plausible that a contributor with a grudge or some other motivation might make takedown requests, since it's happened before in SS13 codebases.

I think that the current state of the codebase is that it is infringing the contributors' copyrights, and resolving it would require relicensing, either getting permission from or removing the code contributed by each contributor. Relicensing could be to a more lax license, or it could mean keeping the AGPL but adding a license exception allowing combination with Unity without having to relicense Unity or make available its source code. However, adding an exception would still require the permission of the contributors, since the GPL without exceptions does not allow adding new exceptions.

And before you ask, I do know that there has been drama with SS13 forks related to licensing. Same as here, I believe that the GPL is incompatible with Byond. I am not super familiar with the drama though and the goal of this issue is not to stir it back up.

**Comment by DooblyNoobly** [comment]
Thanks for the detailed answer @Ornias1993, closing this issue now.

**Comment by raymoo** [comment]
Not sure if I understand, are you considering unitystation itself to be a plugin for the Unity engine (or Unity engine as a plugin for unitystation)? Or are you talking about plugins a server operator might use on top of unitystation to provide additional functionality? I'm asking because I know the latter has come up as an issue before, and this issue is not concerned with those, only with unitystation itself.

**Comment by freezy** [comment]
@Ornias1993 We have the same problem for a GPL-licensed Unity game (see referenced issue above). If you have a minute, would you mind pointing me to where the GPL defines that "With GPL its clear that plugins are not required to be GPL compatible."?

[In the FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF) it seems pretty clear that we would need to add an explicit exception for Unity:

> If they form a single combined program this means that combination of the GPL-covered plug-in with the nonfree main program would violate the GPL. 

Additionally, [the definition of plug-in](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins) doesn't seem to apply in my (non-lawyer) understanding, since we're not even forking a process but *compiling* our code into Unity, so there is definitely "intimate communication" going on.

**Comment by freezy** [comment]
Thanks, that was helpful. I wasn't aware about the compatibility changes in v3, so it would probably make sense for us to relicense under GPLv3.

Cheers!

**Comment by freezy** [comment]
Yes, that's what I did after your comment, and the *System Libraries* part is reassuring.

**Comment by raymoo** [comment]
EDIT: I'm still not a lawyer and this is not legal advice.

According to that section, for Unity to be a "system library" it would have to satisfy two conditions. This is the first one:

> (a) is included in the normal form of packaging a Major Component, but which is not part of that Major Component

Is Unity in the standard packaging of "Major Component"? What is one? The following sentence in the license text gives a definition:
> A “Major Component”, in this context, means a major essential component (kernel, window system, and so on) of the specific operating system (if any) on which the executable work runs, or a compiler used to produce the work, or an object code interpreter used to run it.

There are a few categories of things that are considered major components:
- Major Component = OS? - Unity is not packaged with a major essential component of any operating system, as far as I know. It's conceivable that you could have a gaming console tightly integrated with Unity, but this isn't the case for a PC operating system.
- Major Component = A compiler? - Unity could be considered a compiler for Unity projects. However, for something to be a System Library, it must not be part of the Major Component in question (see the quote of (a)), just packaged with it.
- Major Component = Object code interpreter? - Similar to above.

Unity already fails (a), but there is a second requirement:
>(b) serves only to enable use of the work with that Major Component, or to implement a Standard Interface for which an implementation is available to the public in source code form.

Unity exposes an interface, but it's not necessary to discuss whether it is a Standard Interface, because there is no publicly-available source of Unity's core engine (I think). ~~Even if you had an operating system tightly integrated with Unity, as in the discussion of (a), Unity would still not be a System Library in that instance because of this.~~ Previous sentence is a mistake, because in that case there would be a major component that Unity is packaged with. It would still not be a Standard Library though, since Unity would be doing more than just allowing use of the OS, it would also be providing a game engine.

Since Unity is not a System Library, the exclusion of System Libraries from the Corresponding Source does not apply to it.

For the purpose of clarification, the license text includes some examples of things that would be considered Corresponding Source:
>For example, Corresponding Source includes interface definition files associated with source files for the work, and the source code for **shared libraries and dynamically linked subprograms that the work is specifically designed to require, such as by intimate data communication or control flow between those subprograms and other parts of the work.**

I have bolded the part that particularly applies to Unity. Unity games are designed to require Unity, and control passes between user code and the Unity engine in a complex way.

**Comment by raymoo** [comment]
Sorry, I wasn't intending to engage with the original argument. I'll cede every point of that to you. I just wanted to clarify how Unity does(n't) fit into the definition of "System Library", for @freezy's purposes. I agree that it is not worth arguing about compatibility of Unity and AGPL in here.

**Comment by freezy** [comment]
Unitystation still distributes binaries through Steam and VPE will probably do the same at some point (probably not Steam, but directly). So *if* it's a violation, then *anyone* with enough money could sue the project, no? Don't have to be contributor, the mere fact our binaries are distributed by us would put us into a potentially vulnerable situation?

**Comment by raymoo** [comment]
It would have to be somebody whose copyright was infringed, so a direct contributor or the copyright holder of a library that was used (and whose license was violated).
