### ISSUE TITLE
NRE on round restart

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2063]
# Description
![image](https://user-images.githubusercontent.com/27101670/61966852-aef4a000-afcb-11e9-826f-e5086045984a.png)

## Category
BUG 

## Detailed Bug Report
MissingReferenceException: The object of type 'Tilemap' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Tilemaps.Tilemap.GetTileAsset (UnityEngine.Vector3Int position) <0x4404dec0 + 0x0005a> in <fbd6c6a3ec194a76ab38d25bd514263c>:0
UnityEngine.Tilemaps.Tilemap.HasTile (UnityEngine.Vector3Int position) (at C:/buildslave/unity/build/Modules/Tilemap/ScriptBindings/Tilemap.bindings.cs:141)
Layer.IsAtmosPassableAt (UnityEngine.Vector3Int from, UnityEngine.Vector3Int to, System.Boolean isServer) (at Assets/Scripts/Tilemaps/Behaviours/Layers/Layer.cs:93)
MetaTileMap._IsAtmosPassableAt (UnityEngine.Vector3Int origin, UnityEngine.Vector3Int to, System.Boolean isServer) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:99)
MetaTileMap.IsAtmosPassableAt (UnityEngine.Vector3Int origin, UnityEngine.Vector3Int to, System.Boolean isServer) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:91)
MetaTileMap.IsAtmosPassableAt (UnityEngine.Vector3Int position, System.Boolean isServer) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:83)
MetaDataSystem.UpdateAt (UnityEngine.Vector3Int position) (at Assets/Scripts/Tilemaps/Behaviours/Meta/MetaDataSystem.cs:72)
SubsystemManager.UpdateAt (UnityEngine.Vector3Int position) (at Assets/Scripts/Tilemaps/Behaviours/Meta/SubsystemManager.cs:44)
MetaDataLayer.UpdateSystemsAt (UnityEngine.Vector3Int position) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaDataLayer.cs:89)
AirVent.CheckAtmos () (at Assets/Scripts/Tilemaps/Behaviours/Objects/AirVent.cs:43)
AirVent.UpdateMe () (at Assets/Scripts/Tilemaps/Behaviours/Objects/AirVent.cs:32)
UpdateManager.Update () (at Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:95)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Spawn as nuclear operatives
2. Explode station With Nuclear codes
3. Round automatically restarts
4. Observe NREs in log

**Comment by Bod9001** [comment]
yeah that's good suggestion

**Comment by Jibbajabbafic** [comment]
I think this is fixed now, haven't noticed it happening anymore
