### ISSUE TITLE
Shuttle radar is broken, no station/other shuttle display icons

### ISSUE THREAD

**Issue by badbon** [unitystation/unitystation#2068]
# Description
Same as title. there used to be icons for each shuttle and the station itself, theyre not being shown now.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick syndicate team
2. Go into shuttle console
3. ??? profit

**Comment by fomalsd** [comment]
Duplicate of #2066
