### ISSUE TITLE
Object Lifecycle - Consistent Spawn and despawn logic / hooks

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2070]
# Description
Currently many items which are pooled will not reset to their correct initial state when spawned because their state is initialized only in Start / Awake or in their initial settings. 

Due to us using a custom object pooling technique, the standard Unity lifecycle methods like Start / Awake are not sufficient.

We should create a method that is invoked when the object is spawned regardless of if it's via the pool, via Object.Instantiate, or scene loading. Then initialization logic for each component should be moved there. For consistency, we should also have a method that is called when an object is going to be destroyed or despawned. Make sure its possible to have the logic distinguish between client and server. 

As a way to more easily test this, also add a way for a dev to despawn and respawn a given object immediately as if it was taken from the pool, so it can be obvious if it's state isn't being reset. 

Overall we should just have our "lifecycle" methods for our objects which is separate from Unity's lifecycle (due to our custom object pooling), and should document how it can be hooked into.

**Comment by Bod9001** [comment]
There is currently goingoffStage Broadcast in poolNetworkdestroy, That could be expanded on
