### ISSUE TITLE
Spacewalking doesn't cause damage or Alerts

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2073]
# Description
You no longer take damage from spacewalking

## Category
BUG or TODO?

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Develop
2. Run out in space
3. Observe no damage taken

**Comment by fomalsd** [comment]
can confirm, feels almost like someone disabled space damage and forgot to re-enable it back – but no recent code changes in LivingHealthBehaviour or RespiratorySystem were detected, weird. you definitely can die from other causes
