### ISSUE TITLE
TODO: Communications Console B: 150

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2075]
# Description

This job is to create the NetTab GUI and operating system for the Communications console

![image](https://user-images.githubusercontent.com/20813925/62504362-73639c80-b83b-11e9-872b-7e4b08257f70.png)

## Criteria

- Create the Communications Console locked screen
- Add ability to insert an ID card to allow access to the system
- Only allow ID cards that have the correct permissions the ability to log into the console
- For this iteration we only want the ability to Call the Emergency Shuttle and to broadcast an Announcement to the Station
- Create a screen to call or cancel the Emergency Shuttle from
- Create a screen to allow the broadcast of Station Announcements
- Broadcast any announcements to all players who are on the station
- Add ability to log out the user at any time
- Ensure system works over multiplayer (test with 2 clients)

For reference here are some screenshots of the current Comms Console from byond:

Logged in main menu:
![image](https://user-images.githubusercontent.com/20813925/62504632-bbcf8a00-b83c-11e9-8784-118adf0ab237.png)

Emergency evac screen:
![image](https://user-images.githubusercontent.com/20813925/62504647-cbe76980-b83c-11e9-98d9-2aea13fb47ee.png)

Annoucement window:
![image](https://user-images.githubusercontent.com/20813925/62504660-de61a300-b83c-11e9-9e04-a29874d6bd75.png)

Contributor will receive a bounty of 150usd on a successful merge of a solution that satisfies the criteria above.

**Comment by dapocalypse** [comment]
Hecking claim, i unclaim chat one

**Comment by DooblyNoobly** [comment]
I'm not giving this one to you, you don't have the experience to be able to complete it and I need this done this month.  If you manage to PR something though I'll review it but I'm leaving the 'in progress' tag off it for someone who has a track record of completing jobs.

**Comment by dapocalypse** [comment]
Alrighty that works
