### ISSUE TITLE
TODO: Identification Console B: 150

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2076]
# Description

This job is to create the Identification Console prefab along with the the NetTab GUI.

![image](https://user-images.githubusercontent.com/20813925/62506288-68146f00-b843-11e9-9fad-3fc137669463.png)

## Criteria:
- Create the Identification Console prefab (see other consoles on what components are needed to build it)
- Map the new console somewhere in the HoP's office on Outpost Station (you may want to PR this change as soon as you do it to avoid scene conflicts later on)
- Create the Identification Locked Screen
- Add the ability to insert two ID's. One to log into the system and one to change Access permissions
- Add the Access Permission modification screen
- Update the ID card that is being modified with new permissions as they are added / removed
- Create permission shortcuts for each role (e.g. HOP can click on Janitor shortcut and ID will be updated with all of the Janitor default permissions)
- Add ability to change the ID card name
- Add ability to eject the modified ID card
- Add ability to log out of the ID console
- Test in multiplayer with 2 clients

For reference here is the modification screenshot from byond version:

![image](https://user-images.githubusercontent.com/20813925/62506543-5e3f3b80-b844-11e9-9b09-62cba67a0c9e.png)

![image](https://user-images.githubusercontent.com/20813925/62506556-67c8a380-b844-11e9-8943-dba3fbb3db3a.png)

Contributor will receive a bounty of 150usd on a successful merge of a solution that satisfies the criteria above.

**Comment by chairbender** [comment]
I think someone in Discord said they were working on this

**Comment by vlandemart** [comment]
Yes, I'm currently working on it.
