### ISSUE TITLE
TODO: Add small storage boxes B: 70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2080]
# Description

We need the ability to be able to store things in small boxes and have that box be stored in your bag inventory.

![image](https://user-images.githubusercontent.com/20813925/62509861-2b02a980-b850-11e9-8159-3144abe87c95.png)

## Criteria:

- Create the box prefab item
- Add storage slots to the box item (see how the bag works: i.e. Add the Interactable Storage component and the Storage Object component and adjust accordingly)
- Develop a way to modify and display the box inventory when interacting with it in all conceivable scenarios (i.e. drag and dropping the box while it is near you and showing the inventory or displaying the inventory when the box has been clicked on while it is stored in a backpack)
- Add the box with oxygen mask and small air canister to the default inventory of the UniBackpack prefab (You will need to spawn the box prefab and add it to the inventory after the bag itself has instantiated. This is because both items will have a network identity on them. You will need to do the same with the mask and oxygen tank)
- Make sure all contents are updated correctly in a multiplayer environment (with 2 clients)

## Notes:
- Inventory slots system has been completed and most of the functionality should already be working
- When this job is complete then we can create the body bag TODO

A bounty of 70usd will be awarded to the contributor on the successful merge of these features.

**Comment by fomalsd** [comment]
how about using that one instead?
https://github.com/unitystation/unitystation/issues/1698

**Comment by DooblyNoobly** [comment]
@fomalsd plan is to get a simple box up and working first (along with a system to add inventory on spawning) and then evolving it to uni containers.

**Comment by chairbender** [comment]
IIRC someone is making big changes to how inventory works currently so might conflict if someone starts this now

**Comment by chairbender** [comment]
planning on working on this, just checking if it's okay to do now

**Comment by chairbender** [comment]
Looks like #2129 might conflict with this, should wait until it's fixed.

**Comment by chairbender** [comment]
this should be okay to work on now
