### ISSUE TITLE
Chair buckled sprites dont show up on clients

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#2087]
# Description
![image](https://user-images.githubusercontent.com/701959/62637747-7f6e5d80-b912-11e9-918a-39ce0a349335.png)
Chair buckled sprites dont show up on clients

## Category
BUG

## Detailed Bug Report
im talking about the "temporal" black seatbelt line, the image is from the steamserver

**Comment by chairbender** [comment]
Can't reproduce locally, maybe only happens on steam server?

**Comment by chairbender** [comment]
@Aranclanos are you still able to reproduce this? Wasn't clear from your description if this was only on headless. I can't reproduce locally.

**Comment by chairbender** [comment]
working fine on Steam and local
