### ISSUE TITLE
ClosetControl.cs SyncSprite Seems to be constantly Being updated

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2095]
# Description
I don't see why it would be needed to be constantly updated, surely you would only need an update every time the state changes, this could help with performance issues
## Category
Performance issue

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Put a log statement in the SyncSprite 
2. Play in the editor
3. Watch as it continuously updates

**Comment by chairbender** [comment]
This is actually happening in DNA Scanner, NOT closet control
