### ISSUE TITLE
Refactoring inventory for UniBackpack

### ISSUE THREAD

**Issue by SantaGitHub** [unitystation/unitystation#2129]
# Description
Accidentally found this bug. Allows to duple objects. Here is the video https://youtu.be/nK2JsScZ5X8
## Category
BUG 

## Steps to Reproduce
1.Please enter the steps to reproduce the bug or behaviour:
2.Take thing in hand
3.Put in a backpack
4.Take another thing in your hand
5.Put in backpack
6.Take another item from the backpack
7.Drop it and take it again
8......
9.PROFIT

**Comment by fomalsd** [comment]
how fresh is the branch this was performed on — before or after latest inventory refactor #2120 3 days ago?
it looks like #1699 bug which isn’t a dupe but a general fuck up (possibly clientside only)

**Comment by SantaGitHub** [comment]
it's last branch "develop"
May be clientside only, but i try fix it

**Comment by Aranclanos** [comment]
whoops

**Comment by SantaGitHub** [comment]
The problem with this parameter is https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs#L44
When a thing drops, the InventorySlot in Inventory is not updated and retains its old value.

UPD: The problem is related to UniBackPack inventory. looking for a reason

**Comment by fomalsd** [comment]
Any progress?

**Comment by chairbender** [comment]
looks like it's not in progress anymore, this really needs to get worked on so inventory-related stuff can be worked on again
