### ISSUE TITLE
TODO: Asteriod Mining and Matrix Fixes B: 70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2135]
# Description
Two tasks for this job:
1) Fix the matrix offset bug (at the moment it is offset by 1 tile, so you run into invisible walls)
2) Add the ability to mine plasma from rocks

## Criteria
- Diagnose and fix the matrix offset problem on the asteroids
- Add the ability to use the mining pick axe on an asteroid rock, display the progress bar over the rock and remove the rock tile after it has completed
- Add random spawning of plasma. Experiment with the balance here. Maybe start with 50% chance to spawn solid plasma and see how that goes
- Test in multiplayer with 2 clients and ensure everything works

**TIP:** To get to the asteroids get the print out paper from the command console that lists expected co-ords of the asteroids then use a shuttle to fly there.
Alternatively map an asteroid close the station and remove it from the random positioning logic.

Contributor will receive a bounty of 70usd on a successful merge of a solution that satisfies the criteria above.

**Comment by chairbender** [comment]
pretty sure the offset thing is fixed, probably I fixed it months ago when I was yet again fixing various matrix bugs

**Comment by chairbender** [comment]
nvm I can see this happening in some situations

**Comment by chairbender** [comment]
It appears to just be some mapping issues on the Large asteroid, haven't seen it show up on the others yet. There's a bunch of these problems along the asteroid border, they are not marked as being on the same matrix (marked as empty space)
![image](https://user-images.githubusercontent.com/1329062/64502489-34ca6300-d27b-11e9-81da-5be705c97045.png)

**Comment by chairbender** [comment]
all that's left is some sfx. The issues with progress actions are already in other tickets (which I plan to work on next and have already assigned to me)

**Comment by DooblyNoobly** [comment]
thanks chair : )

**Comment by chairbender** [comment]
oops, want to reopen so @DooblyNoobly has the final say
