### ISSUE TITLE
TODO: Body bags B:70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2137]
# Description
- Dead bodies can't just be left around on the station to rot. Put them in body bags!

## Criteria:

- Create the Bodybag prefab and add a bunch of body bags in one of the closets in Medbay
- Add the ability to open and close body bags
- Add the ability to put a body into a body bag
- Hide the body when the body bag has been zipped up
- Allow body bag to be dragged around on the station
- Make sure all actions work of multiplayer and test in a mp game with 2 clients

Contributor will receive a bounty of 70usd on a successful merge of a solution that satisfies the criteria above.

**Comment by fomalsd** [comment]
are alive players supposed to be put in the bag?
if so, can they zip/unzip themselves into/from the bag if they're conscious?

**Comment by krille90** [comment]
> are alive players supposed to be put in the bag?

imo that should be possible, you should be able to put them in a body bag. Maybe restrict it to players that are lying down?
> if so, can they zip/unzip themselves into/from the bag if they're conscious?

Hm, I would say so.

**Comment by JaytleBee** [comment]
Just tested it, you can zip yourself in it on /tg/ (even while standing), but there isn't a sprite to indicate whether the bag has someone in it (only whether it's opened or closed), so we may need a sprite for that.

**Comment by DooblyNoobly** [comment]
I've removed the criteria for a full body bag sprite. It's not needed at the moment if its not part of TG.

**Comment by StrawberryMoses** [comment]
Some additional notes on body bag behavior: 

- Body bags can carry items, it is not limited to bodies.
- Body bags can not be pushed.
- You can zip and unzip yourself from a body bag.
- Moving while in a body bag opens it up first, then allows you to walk.
- Dragging yourself onto the body bag does not place you in it.
- Placing a folded body bag on the ground opens it.
- Placing a folded body bag on a table leaves it folded.
- When a body bag is opened, all objects inside appear on top, similar to a crate.
- Bags can be refolded by dragging it onto your body, but only if nothing is inside, and only while it is zipped up. "You wrestle with the body bag, but it won't fold while unzipped." "There are too many things inside of the body bag to fold it up!"
- Folded body bags can fit in boxes.
- Closed body bags do not impede movement, even if there is a body inside them
- The opened body bag sprite is not the full bag, just an overlay like a closet door.
- Body bags can only carry two mobs. Bluespace body bags can carry 15.

**Comment by StrawberryMoses** [comment]
I'm going to try and work on this one

**Comment by astralenigma** [comment]
Oh, didn't know about the placing on the floor behaviour.
