### ISSUE TITLE
TODO: Game mode system B: 150

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2138]
# Description
- We need to finish the game mode system which randomly chooses a game mode on server round start and assigns secret syndi roles to players
- All this should be done in the GameManager on the server

## Criteria:

- On round start determine the game mode but keep it secret (i.e at the moment the server reports NukeOps to the Server Hub, this should be hidden) the current available game modes are: Extended and NukeOps
- Create a system that determines whether a newly joined player is from the syndicate or not (keep the chance of random assignment low enough that only a small percentage are syndi)
- Create a system to assign at least two random goals for the syndi player (i.e. kill this player or steal this item)
- Communicate these goals to the player via chat feed
- Create the server side logic to determine if player has met their targets when the escape shuttle has reached its destination for round end
- Display the syndicate success results to everyone at round end
- Test the system in multiplayer with 2 clients. Also test that it resets itself properly on round restart

Contributor will receive a bounty of 150usd on a successful merge of a solution that satisfies the criteria above.

**Comment by DooblyNoobly** [comment]
Syndi PDA's will come when we work on PDA's after 0.4

**Comment by Jibbajabbafic** [comment]
I'm looking into this
