### ISSUE TITLE
TODO: Clean up the Outpost station map in prep for 0.4 beta B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2139]
# Description
- The outpost station map needs another iteration to make sure it is suitable for the 0.4 release

## Criteria:

- Put the nuke in a secure location
- Make sure the map has sufficient items for a proper Low RP game
- Remove any weapons that are easily accessible to station staff (you can stock up the armory with a bulk load of weapons, just make sure an assistant can't get their hands on a deadly weapon)
- Make sure lighting works correctly on round restarts
- Make sure Console Screens toggle on and off correctly
- Assess every area of the station and Add / Remove tiles where needed to support fun game play!
- Expand any departments if they are needed (maybe a bigger armory etc)
- Add furniture where needed, or decorations like plants etc
- Make sure lighting is sufficient in all areas
- Test in multiplayer with 2 clients and ensure everything works fine after round-restart

Contributor will receive a bounty of 50usd on a successful merge of a solution that satisfies the criteria above.

**Comment by fomalsd** [comment]
might be wise to wait for @Bod9001's #2008 PR to be merged first, I highly suspect that it changes the map somehow

**Comment by Bod9001** [comment]
so Should maintenance have lighting?
I feel like working on this

**Comment by fomalsd** [comment]
imo it shouldn't

**Comment by Bod9001** [comment]
done in #2171
