### ISSUE TITLE
Inventory inspection, Cloth stripping/stealing functionality

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2144]
# Description
Would be nice to be able to see a list of other person's equipment with ability to take it off,
because at the moment there's no way to retrieve dead person's belongings

**Comment by chairbender** [comment]
I think this is a high priority for release. Important for being able to take things from players such as for traitors.

**Comment by chairbender** [comment]
not started it yet but I'm going to preemptively assign this to me because I think I can get it done most quickly due to experience with the inventory system and UI
