### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2148]
# Description
There are some missing sprites after #2008 refactor
~~- Glass cracks~~
~~- Radar icons~~
~~- Shuttle thruster particles~~
- (add more)

**Comment by fomalsd** [comment]
~~- Fire tiles~~

**Comment by DooblyNoobly** [comment]
- Shutters

**Comment by StrawberryMoses** [comment]
~~Fire Extinguisher foam~~

**Comment by fomalsd** [comment]
I think it's just shutters that are missing now (#2319), so I guess this one can be closed
