### ISSUE TITLE
Cannot close Fire Extinguisher cabinet with Extinguisher inside

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2157]
# Description
After opening the fire extinguisher cabinet, it's not possible to close it again after replacing the extinguisher. Clicking the cabinet only retrieves it again. It is still possible to close it when the extinguisher is not inside. On /tg/, this behavior can be done with Alt-Click.

## Category
TODO

## Steps to Reproduce
1. Open a fire extinguisher cabinet.
2. Use an empty hand on the open cabinet.
3. Observe that the cabinet can close.
4. Click on the cabinet with the fire extinguisher in hand to replace it.
5. Click anywhere on the cabinet.
6. The fire extinguisher will only be retrieved- clicking on the cabinet will not close it again.

**Comment by jaredkoenig** [comment]
I am working with a group at Christopher Newport University and we attempted to recreate this problem and we were unable to recreate this bug. The cabinet worked properly.

**Comment by fomalsd** [comment]
@jaredkoenig it's quite easy to reproduce, it doesn't close once opened
![scr](https://user-images.githubusercontent.com/10403536/68889864-d9ab6580-072e-11ea-8dc9-8ea337e18634.gif)

**Comment by krille90** [comment]
Also the extinguisher shouldn't be retrieved already when opening the cabinet.

**Comment by Fiftyllama** [comment]
I'll flip it around, make you not retrieve the fire extinguisher when opening the closet, but closing the closet automatically when returning an extinguisher

**Comment by Fiftyllama** [comment]
It is already possible to close it if your active hand is holding an item.

**Comment by KuzyXD** [comment]
Need to close that issue.
