### ISSUE TITLE
Lockers can pickup vents and scrubbers

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2166]
# Description
Pulling a locker on a square with a vent or a scrubber, then closing, will bring the vent or scrubber with.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start pulling a locker.
2. Pull the locker to a tile with a vent or a scrubber object.
3. Close the locker so the vent or scrubber is inside.
4. Pull the locker to a new tile.
5. The vent or scrubber will move with the locker.

**Comment by chairbender** [comment]
I see a pr for this so marking it in progress #2282
