### ISSUE TITLE
Need a way to simulate ping

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2172]
# Description
in Unet HLAPI there was a way to turn on network simulator that was quite useful. Need a way to do it with Mirror.
This functionality is crucial for stress testing movement, push/pull and other predictive things

**Comment by chairbender** [comment]
Mirror people talked about this here:
https://github.com/vis2k/Mirror/issues/878

On windows, a tool called "Clumsy" can be used.

Looking into options on OSX.

**Comment by chairbender** [comment]
OSX has some options, discussed here: https://apple.stackexchange.com/questions/24066/how-to-simulate-slow-internet-connections-on-the-mac

**Comment by chairbender** [comment]
In a feat of unbelievable stupidity, Network link conditioner doesn't appear to work on localhost connections, despite the approxmiately 1 million posts on the internet saying how it's the best tool ever for ping simulation. How useful! I'm looking for an alternative.

**Comment by chairbender** [comment]
This answer works for OSX.
https://apple.stackexchange.com/a/331407/355957

**Comment by chairbender** [comment]
Documented here: https://github.com/unitystation/unitystation/wiki/Simulating-Lag
