### ISSUE TITLE
Extra ghosts spawns when you leave your dead body

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2174]
# Description

![image](https://user-images.githubusercontent.com/10403536/65506249-aed52b80-deba-11e9-81ee-3e74d132528c.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Die
2. Leave your body
3. Observe extra ghost above body while you're controlling the other one

**Comment by StrawberryMoses** [comment]
I'm not able to reproduce this one. If you remember, was there anything you did beforehand or any special way you died? Was this in editor?

![Screen Shot 2019-10-05 at 5 11 53 PM](https://user-images.githubusercontent.com/8854773/66261467-3eb88680-e793-11e9-93d5-4a35a74ce5c9.png)

**Comment by fomalsd** [comment]
Hm, yes, it was in editor
Will try to reproduce it again

**Comment by fomalsd** [comment]
can't reproduce it anymore – probably was fixed in #2180

**Comment by fomalsd** [comment]
eh, apparently it can still happen on very rare occasions
![img](https://user-images.githubusercontent.com/10403536/67580452-e6432c00-f735-11e9-98bf-e41b3e55d6cc.png)

**Comment by chairbender** [comment]
not sure if this is just a regression in my branch, but I noticed that the client's ghost is not getting destroyed on the client side when they re-enter their body or respawn, so I think that can be included as part of this ticket.

**Comment by fomalsd** [comment]
Haven't seen it in a while, closing for now
