### ISSUE TITLE
Butchering players spawns their ghost at 0,0

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2182]
# Description
Ghost should spawn where the body was butchered/destroyed

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get 2 clients
2. Stab one with knife until you butcher them
3. Notice the dead player's ghost spawns at 0,0

**Comment by fomalsd** [comment]
yes, very annoying
