### ISSUE TITLE
IF2 + Right Click improvement, remove "specificComponent" from IF2

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2188]
# Description
Now that people have been using IF2 for a bit, a few problems are emerging:
1. Dealing with IC precedence is proving challenging. People are having trouble figuring out how to create / place ICs in order to ensure their particular interaction fires under the right circumstances.
2. Amount of components on each object is growing as people are implementing one component per interaction in some cases. Not necessarily an issue, but it might be better if we can consolidate these somehow.
3. Want ability to trigger interactions at will, which IF2 doesn't really support (as documented below) #2181 added "specificComponent", which was needed for the right click -> Pickup option to work properly. Otherwise, it would end up triggering the wrong component when pickup was attempted, because pickup sent a HandApply message rather than directly triggering the pickup interaction logic. We should refactor so this string isn't necessary.

See what can be done to fix the above issues.

**Comment by chairbender** [comment]
random idea, what if actions themselves are first class citizens? I.e. actions are classes, an instance of an action class is an attempt to perform that action. You define what the action does, with some possible server / client side logic, prediction ,etc... then you can just invoke it from anywhere. Right click, interactable, etc...and all logic related to the action would be properly triggered, including client / server communication. Actions would share a common interface or abstract base class which defines overridable methods, similar to how interactable components work.

This could have some benefits as the amount of possible actions grows.

Possible challenge with this would be the networking aspect of actions - actions may have arbitrary parameters associated with them which could make serialization tedious to implement. Ideally we should not have to implement a net message for each possible action. Perhaps they could just re-use the existing interaction net messages, but we could add an enum or some other id which identifies which action it is trying to perform. So now each interaction message would need to say which action is being attempted, and it would automatically trigger the correct component.

Now that mirror is involved we may be able to have generic NetworkComponent classes, idk.

**Comment by StrawberryMoses** [comment]
So would each action have it's own component on the prefab?
How would the naming convention for this work? For example, on the Rack Parts object- we can deconstruct it either by clicking on the object in the world or in the inventory. Would we have scripts for both RackPartsPositionalHand and RackPartsInventory?
(I may not be understanding this correctly)

**Comment by chairbender** [comment]
Changing this to be more general about IF2. Now that people like @StrawberryMoses are working with it more we can see some of the issues that are cropping up. Not entirely sure they are solvable but definitely will look into it.

**Comment by chairbender** [comment]
as far as precedence, a simple way that might help make it more clear is to add more detailed debug messages that can be turned on for IF2. Whenever an interaction happens, it would log each object that is being checked (via WIllInteract) and each component that is being checked, and log the one that ultimately fires. This will make it more clear what the order of precedence is.

Ideally we wouldn't even need to log this, but this can be an incremental improvement
