### ISSUE TITLE
cable sprites do not update in the editor if you change the direction in the editor

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2190]
# Description
Reason why it would be nice to see the Cable layout in editor If you change it via the editor
( four now you can just use the tile palette )

## Category
TODO
add Running editor mode parameter and
ensure there's an update/start function to set the Sprite to the correct one

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Change direction of cable
2.Watch as Sprite doesn't change
3. Watch as already Changes in runtime

**Comment by NoooneyDude** [comment]
Cables are no longer object prefabs but are tile SOs, so I don't think this issue is still relevant.
