### ISSUE TITLE
Progress Actions need to be interrupted in more situations

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2204]
# Description
Currently they are interrupted if you move. But they aren't interrupted by dropping your in hand item, which can cause glitches in several cases (try constructing a Rack and drop the item before it's complete).

Think of other cases where progress needs to be interrupted and try to add the interrupt call for those. Please add to this list if you think of something. Otherwise just try to implement interrupts for these things:

- [ ] When dropping the item being used to perform the action
- [ ] When moving the item being used to perform the action to a different inventory slot
- [ ] When doing something with bare hands and picking up an item in the active hand
- [ ] When doing something with bare hands and moving an item into the active hand from an inventory slot
- [ ] When downed due to falling over or going crit
- [ ] When pushed or pulled (this might already interrupt)

**Comment by fomalsd** [comment]
welding should be interrupted when welder is turned off as well, but it's a specific case

**Comment by Bod9001** [comment]
I think it interrupts when you change direction it's not supposed to do that I think?

**Comment by chairbender** [comment]
yup, we have another bug for that problem in #1780

**Comment by chairbender** [comment]
Needs to be interrupted if thing being worked on (such as a tile position, or a movable object) moves. Also needs to support cross matrix - if standing in space and working on a shuttle tile from the outside, progress should stop if shuttle starts moving.

**Comment by chairbender** [comment]
Actually as far as active hand goes, the action should probably always be interrupted if active hand changes in any way - either swapping active hand or putting something into (if empty) or out of (if occupied) it.

**Comment by chairbender** [comment]
Several of these cases will be completed as part of #2245  - anything related to inventory slot changes has logic in place for cancelling the progress

**Comment by DooblyNoobly** [comment]
@chairbender can this ticket be closed ?

**Comment by chairbender** [comment]
It's close to being done, but the stuff mentioned needs to be tested to make sure, and I don't know if welder had custom logic added to it either for interrupting when turned off.
