### ISSUE TITLE
Right click respawn spawns some things at hidden pos

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2205]
# Description
Build a Rack, then right click and respawn it. The rack should appear at the same location but it instead seems to teleport away to hidden pos. This probably affects some other items. Probably the position for respawning is somehow not being respected in these cases.

**Comment by fomalsd** [comment]
also applies to gas canisters

**Comment by Jibbajabbafic** [comment]
Everything I've tried to respawn has disappeared so I think it affects most objects

**Comment by fomalsd** [comment]
I think I've (accidentally?) fixed it on my branch. 
At least canisters certainly don't disappear. Might have been something with AssumedPosition.
However I'm getting lots of `Assumed World Position is HiddenPos, something might be wrong` warnings for freshly spawned stuff on my branch...
