### ISSUE TITLE
Cross-matrix collisions B: 200

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2208]
# Description
Shuttles going through station like ghosts are boring.
Need to develop a way for moving matrices to collide with others and apply damage/destroy tiles correspondingly.

**Comment by DooblyNoobly** [comment]
Criteria:

- Detect when two matrices have collided
- Calculate the velocity of the collision (will need to keep track of the last position of both matrices on the previous frame and calculate the magnitude)
- Determine damaged area based on collision points and the magnitude of the collision and apply damage to tile / objects / livinghealthbehaviours
- Make sure it all works in mp

I think for this you can just destroy the tiles on the tile map for the mean time and explosions or damage sprites can come after.

I'll put a bounty of 200 on this as it would be good to have this working at the basic level before alpha launch and the level of difficulty especially with the matrix tile to matrix tile detection part is high.

Contributor will receive a bounty of 200usd on a successful merge of a solution that satisfies the criteria above.
