### ISSUE TITLE
PlayerLightControl does not remove light when object is thrown

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2211]
# Description
While holding an item that emits light, such as a handheld torch, it adds itself to a list on the player for lightsources. PlayerLightControl listens for pickup and drop to determine when to add and remove the light from the player. However, it does not listen for throws, meaning that the light it was giving will stay on the player.

## Category
BUG

## Steps to Reproduce
1. Spawn a Handheld Torch
2. Optionally, go to maint or break lights to see effect better
3. Throw the torch
4. Observe that you will still be radiant

**Comment by fomalsd** [comment]
perhaps throwing should broadcast `OnRemoveFromInventory`, too

**Comment by chairbender** [comment]
I'll fix it as part of the inventory work
