### ISSUE TITLE
Pushing containers into walls does not stop pulling

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2214]
# Description
Grabbing a container and pushing it into a wall should stop the user from pulling it.

## Category
TODO

## Steps to Reproduce
1. Grab a crate or any container
2. Start pulling
3. Try to push the crate into a wall
4. You will not stop pulling the crate

**Comment by fomalsd** [comment]
last time I tried it on /tg/ bumping pullable into the wall didn't break pull.
it annoyed me though, so I guess it's still worth doing
