### ISSUE TITLE
items with transparency in the textures in the world don't show properly

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2225]
# Description
items with transparency in the textures in the world don't show properly
## Category
BUG

## Detailed Bug Report
![image](https://cdn.discordapp.com/attachments/312454684021620736/637045014462988299/transparency.gif)
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.get an item with transparency
2.placing world on table
3.observe lack of transparency

**Comment by NoooneyDude** [comment]
I believe this has been fixed.

![amaritaj](https://user-images.githubusercontent.com/6926225/88158299-fc97fd00-cc5f-11ea-9fcf-fafe95b6b6e6.png)
