### ISSUE TITLE
When grenade blow-ups in hand, it doesn't destroy itself 

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2231]
# Description
There seems to be an error in grenade destruction mechanism. It doesn't destroy itself after explosion in hands or inventory. It also can't be activated again and freeze in ticking state

## Category
BUG

## Detailed Bug Report
![handGrenade](https://user-images.githubusercontent.com/6161335/67705433-0722b000-f9c8-11e9-8e04-411f7c685761.gif)

## Steps to Reproduce
1. Activate grenade in hand
2. After explosion and respawn your character
3. Grenade will be laying on the ground

**Comment by chairbender** [comment]
The new inventory system in my upcoming PR should make this sort of thing much easier to do

**Comment by chairbender** [comment]
This might be fixed in #2245 , but needs to be tested
