### ISSUE TITLE
When loading station, all pre-placed object positions get forcefully rounded

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2241]
# Description
When loading the station, objects placed move to their rounded coordinates instead of their exact positions. This does not allow mappers to do stuff like the following:
![Screen_Shot_2019-11-02_at_4 05 45_PM](https://user-images.githubusercontent.com/8854773/68169964-9cc3bf80-ff33-11e9-97c3-514f3be97961.png)

## Category
TODO

**Comment by CodeKalias** [comment]
This is possible as of #4311 , for any items you don't want to snap - turn a checkbox off
