### ISSUE TITLE
Restructure Guns to use Prefab Variants

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2246]
# Description
Any time you need to make changes to gun prefabs, it's really tedious because you have to edit them all. Guns should be restructured to have a base Gun prefab and prefab variants for each different kind of gun. 

After doing this, you will probably need to edit the related tile palette assets to point to the new prefab variants, and probably need to remap any guns that are mapped in the scene.

**Comment by NoooneyDude** [comment]
It looks like this has been completed. There are several prefab parents; Generic Ballistic Gun, Generic Energy Gun and Generic Melee Weapon and it seems all relevant weapons are children of these.
