### ISSUE TITLE
Restructure lockers and crates to be prefab variants

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2247]
# Description
We have a lot of lockers and crates, all of which are separate prefabs, which creates maintenance issues / tedium. Restructure them to have one base Locker and Crate prefab and each different locker / crate can be a variant.

Will require editing the tile palette asset and remapping.

**Comment by chairbender** [comment]
adding this to 0.4 because some of the 0.4 tickets ultimately depend on this

**Comment by chairbender** [comment]
hmm, actually I don't think this is essentially anymore now that I have a better idea how to do the other 0.4 tickets. This is more just a convenience thing than anything and it won't actually make a big difference for 0.4 effort now that I think about it, as most (all?) of the lockers don't really have overrides other than their starting items and sprite.

**Comment by PetMudstone** [comment]
I would like to work on this eventually. Shouldn't be too hard to make the variants, but replacing all the lockers and closets in scenes might be a hassle even with tools.
