### ISSUE TITLE
Suit Storage Slot Logic

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2248]
# Description
Also related to #1747 , there are other slots which are tied to the suit. Might be good to do them together.

Current suit storage slot doesn't function like an actual suit storage. You can put stuff into it even when not wearing a suit, and removing suit has no effect.

Instead it should work like this (correct me if I'm wrong):
1. You can only use the slot when you're wearing a suit.
2. The suit should have a suit-specific slot capacity defined. This will most likely need to be added as a new field to ClothData, or a subclass of ClothData which adds a slot capacity field. When the suit is worn, the suit's defined slot capacity should be used to determine what can go in the slot.
3. When the suit is taken off, the item in the suit storage should drop.

**Comment by PerfectTangent** [comment]
fixed with #5684
