### ISSUE TITLE
Cable direction isn't synchronised on new join players

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2252]
# Description
If you place cables then someone joins they are not set to any direction on client that recently joined

## Category
BUG

This was a bit more tricky than it seems since you don't want a lot of network Chatter over Cable direction

**Comment by JesterX666** [comment]
I don't believe you can accomplish this without at least some networking.  However, when the server pushes the state of the station to the client it should be one of the numerous things it should push.

**Comment by Bod9001** [comment]
fixed in latest update
