### ISSUE TITLE
Mining Satchel B: 50

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2256]
# Description
Depends on #1870 as stacking is used in the mining satchel
Depends on #2301 as we need ores to pick up.

A Mining Satchel should be developed matching the tgstation behavior. You should automatically pick up ores on the ground into the satchel if you walk over them while the satchel is in your belt or pockets. They should go into the mining satchel and should be stacked.

TODO: Feel free to fill in details of this if you know more about how this stuff should work.

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 50usd on a successful merge of a solution that satisfies the requested criteria above.

**Comment by chairbender** [comment]
I definitely suggest creating an event (if one doesn't already exist) which fires when player moves to a new tile, probably this would be in RegisterTile. Then the stachel could hook into this and when the event fires, check if player is over a mineral in their new position and do the pickup. I imagine there will be other logic which would want to hook into this event. It might even already exist.

EDIT: And make sure it only fires on local moves - it shouldn't fire when they are stationary on a moving matrix.

**Comment by fomalsd** [comment]
There's an OnTileReached event for both players and items

**Comment by Bod9001** [comment]
am on this. Though Will be finished after Christmas Due to Christmas break, Already have the interface for satchel code Getting updates with unity events, Currently working on why The pickup stuff is offset
