### ISSUE TITLE
Ore Box

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2258]
# Description
Implement the Ore Box functionality, just like how it works in tg. When you drag the box behind you and step over ores on the ground, they should go into your ore box.

There should be a way to view its contents and a way to dump stuff out, and dump your mining satchel into it

TODO: Someone with more knowledge fill in details if I missed anything.

**Comment by chairbender** [comment]
I don't think this is essential for release, as long as we have mining satchel.

**Comment by PerfectTangent** [comment]
closing in favour of #6151
