### ISSUE TITLE
Add More Cargo Data (stuff you can buy)

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2260]
# Description
~Depends on #2259 or else there will be a lot of rework when it comes time to implement that.~ Done.

Currently you can't buy much, so there's not much fun to be had in amassing a large amount of wealth.

This ticket covers adding content to the CargoData asset so you can buy all of the various fun stuff we've built. Need to be careful about costs and what comes in each crate, but at the very least we just need more stuff that you can buy, so people actually have a reason to try to make money.

**Comment by StrawberryMoses** [comment]
https://github.com/tgstation/tgstation/blob/99555adc393619c54314e3b99c5c0e5cef2eff5b/code/modules/cargo/packs.dm

Now that items are going to start using their normal prices, I would say it's fine to use the prices listed for these crates.

**Comment by Bod9001** [comment]
I've added a bit not sure if it needs more? probably best for Multiple people to go over it and add what they think is necessary

**Comment by Emma3DSS** [comment]
Going to add some more stuff, making a branch called cargo data

**Comment by Emma3DSS** [comment]
Added Crates:

Service -> Storage Crate 
Emergency -> Internals Crate
Emergency -> Firefighting Crate
Botany -> Hydroponics Crate
Miscellaneous -> Monkey Crate
Miscellaneous -> Robusting Crate
Mining -> Mining Tools Crate
