### ISSUE TITLE
Cargo: Add ability to check prices and sell things

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2261]
# Description
In order to be able to make money from mined ores so you can buy fun stuff, we need to be able to sell things by sending them back on the cargo shuttle.

As part of that, we should add a scanner item that tells you the sell price of something (if it has a value).

At the very least, you should be able to put things onto the shuttle and when the shuttle docks at centcomm it should despawn them and add their sell price to the current money (not sure where this is tracked).

This will require a way to define a sell price of things, which most likely would be a good fit for ItemAttributes.

TODO: Someone who knows more can fill in any important details for how this should work

**Comment by fomalsd** [comment]
I think it already despawns everything on the cargo shuttle and pays 50 credits for each item

**Comment by StrawberryMoses** [comment]
The item you're looking for is an export scanner.
https://github.com/tgstation/tgstation/blob/master/code/modules/cargo/export_scanner.dm

**Comment by StrawberryMoses** [comment]
I'll give this one a shot
