### ISSUE TITLE
Thoroughly test round restarts / rejoining / relogging

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2262]
# Description
Want to keep this one open pre- 0.4. We need to ensure that round restarts don't break the game. Many of us never test our features after a round restart. A restart can be simulated AFAIK using the Networking > Restart Round feature. I will add this to the PR template as well to remind us to test it.

**Comment by Mantle-Wanderer** [comment]
Related issue and was pointed to here by chairbender on the discord in _#general-dev_:

_This issue found on Bod's recent Unitystation build on the discord server._

Localhost start game, then log out, localhost start game again. When you join you'll see the occupations window is open long enough for you to click it several times (probably depends on speed of computer) leading to multiple clones and a mess of NRE's. This happens both logged-in and logged-out.

Here's a low-quality (sorry) clip of it in action, just as I press localhost start game a second time. Also note the top-right window and how it seems to flick between Cuban Pete2 and Cuban Pete3 repeatedly:
https://i.imgur.com/cZdPAOP.mp4

This was done in a build and I don't think it has any form of .txt error logs, so here's an imgur album full of some NRE's from a separate (logged-in) recreation on the same build, although I don't know how much use this'll be for you lot except an exercise in suffering and torment:
(Edit: This is out of order. Not in the same order as it was in the logs.)
https://imgur.com/a/9w54hb9

Most were naked, some were partially clothed, some seemed pretty much fully clothed best I could tell. They would all turn to face the same direction as I clicked around, and the game very much was not happy whenever I tried punching or disarming my self-clones.

**Comment by chairbender** [comment]
I think this is good to close once we merge the computer construction PR (including the PR I already merged which resets inventory system on restart), we should do some more testing on the server and confirm.

**Comment by chairbender** [comment]
Noticing an issue when trying to rejoin after a restart, at least on headless, it doesn't put me back into my body and instead I can spawn as a new player, then I get spammed with lots and lots of NREs.

Might be related to #2443 

EDIT: And in the terminal I saw a firebase auth error, something about server refresh credentials failing. In the logs when I finally connect I'm spammed with NRE's coming from PlayerSync

**Comment by chairbender** [comment]
still getting the issue mentioned in the above comment even after my fix, but ghosting and rejoining is working better now still

**Comment by chairbender** [comment]
It's now possible to reproduce the NRE spam just by logging out and rejoining, no need for round restarts or anything or even closing the app.

EDIT: So far only on the dev server, even a local headless doesn't have this issue so I'm thinking it's somehow related to auth logic?

**Comment by chairbender** [comment]
Actually scratch that, the issues go away on a fresh server restart and only show up after a round restart. Probably something needs to reinit on round restart that isn't getting reinitid, and it's related to joining or it's an NRE somewhere that's preventing full join logic from running.

**Comment by chairbender** [comment]
...even then it's not happening reliably, it only happened the first time I rejoined dev server after a restart and then after that rejoining worked totally fine

EDIT: Then restarted round again with client logged out first, spawned in, relogged and got NRE spam upon rejoining, and I saw one NRE before that coming from PLayerSync.Start at PlayerState.set_WorldPosition on MatrixManager.Get

**Comment by chairbender** [comment]
I'm now able to reproduce this on a local headless. All that needs to be done is to run headless, connect with a client, relog, then restart round on headless, spawn in, relog, and the issue happens.

**Comment by chairbender** [comment]
it's apparently fixed now!

Only thing left is that client gets a bunch of NRE spam when they are connected during a round restart, but so far I don't see any actual problems caused by this, and it only happens on round restart - the errors don't show up on relogging. And the NRE spam stops once the round restart process completes

**Comment by chairbender** [comment]
I'm going to mark this done since it seems we've dealt with all the round restart issues currently known.
