### ISSUE TITLE
Shuttle Rotation Glitches

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2263]
# Description
Apparently there are still some glitches with matrix rotation.

Try spawning a canister using the dev spawner on a rotated matrix. It will appear sideways. Instead it should appear upright.

This most likely has to do with some failure within the rotation init logic, not properly keeping the canister upright.

Additionally, on client side, none of the objects rotate upright at the end of matrix rotation, making it look really weird (upside down chairs). This used to work fine so must be a pretty easy fix.

**Comment by fomalsd** [comment]
I think this is also related to incorrectly rotated xenos. Must have something to do with how they get initialised when asteroids get randomly distributed and rotated. "Always upright" option didn't work for them

**Comment by chairbender** [comment]
making it more general about rotation glitches
