### ISSUE TITLE
Atmos breaks due to oxygen NaN infection

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2264]
# Description
Oxygen levels can become NaN:
![GIF](https://user-images.githubusercontent.com/10403536/68569453-07a25880-0456-11ea-9966-2acfea38feaf.gif)
![image](https://user-images.githubusercontent.com/10403536/68569889-310fb400-0457-11ea-99b6-1ce16b0e02d7.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
Exact steps are unknown. Try exploding stuff and perhaps crashing matrices
Note that pressure is unaffected by NaNs

**Comment by chairbender** [comment]
@fomalsd are you still able to reproduce this? We are having trouble getting this to happen.

**Comment by fomalsd** [comment]
No longer seems to happen on my branch – no idea why because I don't recall atmos code being changed. Will close this unless it decides to reemerge

**Comment by fomalsd** [comment]
It's still a thing, but exact steps to reproduce are unclear. Very nasty

**Comment by fomalsd** [comment]
Crash escape shuttle into station to reproduce

**Comment by chairbender** [comment]
Adding a bounty of 50

**Comment by chairbender** [comment]
Drakelor in Discord identified the cause of this in the atmos channel, caused by CalcMeanGasMix targetCount being 0 and causing a Nan.

**Comment by JesterX666** [comment]
I'll take a look at this tonight to see if I can reproduce and fix it.  I'll keep the team informed if I can fix it.

**Comment by JesterX666** [comment]
This is caused by some tiles with z coordinates of -1 after a crash with another matrix.
The tile has no "neighbours" and it causes a division of 0 by 0 (NaN) for Pressure and Moles of Gazes.

First of all, I'll find out what a Z coordinate of -1 means and fix it if possible.
I'll also protect the code so it would not be possible to happen.
