### ISSUE TITLE
Player can get stuck on non-station matrices B: 25

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2265]
# Description
Server movement can somehow stop working on non-station matrix, leaving player with predictive movement and either making him stuck or moving/floating forever without letting him know that something is wrong
![image](https://user-images.githubusercontent.com/10403536/68571025-e17eb780-0459-11ea-986f-f6e61260df34.png)
![GIF](https://user-images.githubusercontent.com/10403536/68571859-e9d7f200-045b-11ea-8a9b-e60eef276303.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Repeat the trick from the GIF. Only engages when you walk across the top right corner of syndie shuttle

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 25usd on a successful merge of a solution that resolves the issue above.
