### ISSUE TITLE
Lockers no longer keep floating in space after pushing B: 25

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2266]
# Description
Space interaction physics got messed up :(
![GIF](https://user-images.githubusercontent.com/10403536/68572201-ba75b500-045c-11ea-91e5-62bb85f4b4fe.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Drag a locker into the space and play around with it

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 25usd on a successful merge of a solution that resolves the issue above.

**Comment by nikopetr** [comment]
Hey does anybody work on this ?

**Comment by fomalsd** [comment]
not as far as I know, this one might be tricky though

**Comment by chairbender** [comment]
still happening, I'll take a look

**Comment by chairbender** [comment]
No bounty please
