### ISSUE TITLE
Players can predictively initiate walk when they're not supposed to B: 30

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2267]
# Description
...that results in rollback after a while. But clients shouldn't even try to walk when they're not sticky, as only throwing things should work in such situations
![GIF](https://user-images.githubusercontent.com/10403536/68572437-4982cd00-045d-11ea-9687-0399ac44d623.gif)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Spawn yourself in a void (either move spawnpoint to space or clear up room where you're supposed to spawn in with a few asteroids) to end up in a situation when you can't walk in space. 
Enable `Matrix Check-Matrix-Sticky` gizmo and that you're on non-sticky tile
2. Try walking around, your predictive (green) gizmo will increase step count while red (server) ones stay in place. Eventually you'll get rolled back.

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 30usd on a successful merge of a solution that resolves the issue above.
