### ISSUE TITLE
Certain zoom values are not pixel perfect

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2269]
# Description
Zoom slider (that multiplies zoom factor) currently goes  from 1 to 10.
Certain commit changed base zoom of 1x down to to 0.5x, so instead of `1, 2, 3... ` it now goes `0.5, 1, 1.5...`
Need a custom zoom slider sequence, preferably modifiable through inspector, that would have a following set of values:
1, 2, 4, 6, 7, 8, 10, 12, 14, 16
instead of a simple 1 to 10

**Comment by JesterX666** [comment]
Comment deleted.

**Comment by JesterX666** [comment]
Seems fine for me.  Maybe it has been fixed since then?  Can someone confirm?

**Comment by Bod9001** [comment]
There is some, Scaling sprites somewhere 1 px of Purple  1 px of Black, In stripes in each direction They should be useful

**Comment by fomalsd** [comment]
find the ugly one:
![1x](https://user-images.githubusercontent.com/10403536/71343114-b7d7a680-2556-11ea-98f8-4a52a4f51233.png)
![2x](https://user-images.githubusercontent.com/10403536/71343147-d50c7500-2556-11ea-9673-6d6da89f259d.png)
![3x](https://user-images.githubusercontent.com/10403536/71343183-eb1a3580-2556-11ea-9d12-d8479ee1062e.png)

**Comment by voidel** [comment]
It's 2x, when 2x and 4x should be straight up doubled pixels as per title. Is it because 3x here is actually 2x and 2x is some weird decimal value?

**Comment by fomalsd** [comment]
oh shit, you're right! didn't realize "3x" was 2x...
commit in question changed base zoom from 1x to 0.5x, which affected increments, too. 
I don't think we need these non-integer zooms except for 0.5x which is sometimes useful for testing

**Comment by Emma3DSS** [comment]
Ill just fix this with my cargo commit :)

**Comment by chairbender** [comment]
What needs to be done here?

**Comment by fomalsd** [comment]
Updated the description

**Comment by dargonforce** [comment]
Currently working on this

**Comment by daalta** [comment]
@dargonforce Any progress? I have fixed this on my branch by not allowing odd numbers as zoom values. I think it works quite well.

Allowed zoom values are 2, 4, 6, 8 and 10. Should I post some screenshots?

**Comment by dargonforce** [comment]
I've been trying to rewrite the entire Zoom handler, unsuccessfully so far. That sounds like a much simpler and more elegant solution than mine.  If the screenshots solve the issue then it sounds like you've gotten this one.

**Comment by daalta** [comment]
@dargonforce You can check out my pull request if you like: https://github.com/unitystation/unitystation/pull/2578

Here's the new zoom (2x magnified, zoom 2, 4, 6, 8, 10 in order)
![zoom](https://user-images.githubusercontent.com/9169275/72196813-2e134e80-341b-11ea-8b95-3463b22227cf.png)
Looks perfect to me!

**Comment by dargonforce** [comment]
Looks awesome! Nice 😄
