### ISSUE TITLE
Admin commands B: 140

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2273]
# Description
Create commands so that admins can:
- [x] Change game mode
- [x] Toggle if game mode is secret
- [x] Kick
- [x] Ban (permanent and temporary)
- [x] Unban
- [x] Change permissions/roles
- [x] Respawn dead player
- [x] Admin PM *bwoink*
- [x] Restrict VV and Dev spawner to Admins only
- [x] Toggle admin only commands in right click menu

For now make it so only the server player can do these until #1994 is done.

Related to #1574 .

## Category
TODO

**Comment by DooblyNoobly** [comment]
Increased to B45 as there is some UI work involved as well (with the bwoink and direct player chat)

Contributor will receive a bounty of 45usd on a successful merge of a solution that meets the criteria above.

**Comment by Bod9001** [comment]
an admin respawn command?

**Comment by Bod9001** [comment]
To add to my previous comment The ability for admins to respawn players?

**Comment by DooblyNoobly** [comment]
Increase bounty to 140. Discussed and voted on in discord #bounties

**Comment by DooblyNoobly** [comment]
> To add to my previous comment The ability for admins to respawn players?

yep bod, I'll have a respawn button

**Comment by DooblyNoobly** [comment]
unban I think will have to happen by editing the banlist json itself. Make it difficult to do so there is a lot of discussion when revoking a ban and a bit of effort to do it. Just going to tick it off the list

**Comment by JesterX666** [comment]
For the cost/benefit, I totally agree.  Perhaps opening another ticket to do it later?
