### ISSUE TITLE
Shuttle crashing into station doesn't update atmospherics properly B: 100

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2291]
# Description
It seems that atmospherics isn't properly notified about the destruction of tiles resulting in with behaviour like

![image](https://cdn.discordapp.com/attachments/312454684021620736/646467316263026710/unknown.png)
![image](https://cdn.discordapp.com/attachments/312454684021620736/646466424109400092/unknown.png)
![image](https://cdn.discordapp.com/attachments/312454684021620736/646466274683256833/unknown.png)
![image](https://cdn.discordapp.com/attachments/312454684021620736/646465960081096715/unknown.png)

## Category
BUG 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Get on mining shuttle 
2.smash in to station
3.Open up Matrix checker
4 Observe strange space values In atmospherics

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 45usd on a successful merge of a solution that resolves the issue above.

**Comment by Bod9001** [comment]
https://cdn.discordapp.com/attachments/300754633863725067/658329120979156992/GohIF.gif

ok,  turns out atmospherics can do updates even though pressure are temperature zero, resulting in this strange behaviour where the moles of gas are getting reset every second

simply stop updating if pressure or temperature is zero

**Comment by fomalsd** [comment]
FYI I'm not actively working on this at the moment – it turned out to be too complex and I'm a bit busy these days. Suggesting to bump the bounty to 100+, and everyone is welcome to look at my https://github.com/fomalsd/unitystation/tree/atmobughunt branch and salvage whatever they find useful.
I might get back to this eventually, but no timeframes, sorry

**Comment by chairbender** [comment]
Updating bounty to 100 because it's a complicated one.

**Comment by krille90** [comment]
I will try my luck on this one.

**Comment by JesterX666** [comment]
![image](https://user-images.githubusercontent.com/32009105/73231455-6b334c80-414e-11ea-9bc2-a42fa893aa1f.png)

Connected to Space and moles are still weird.  See those 2 "6.829" moles tiles?  They are not loosing gaz component at all.
