### ISSUE TITLE
NRE When launching outpost station directly

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2292]
# Description
![image](https://user-images.githubusercontent.com/27101670/69190363-2967a380-0b18-11ea-9c4d-d4a8b99beb84.png)

## Category
BUG 

## Detailed Bug Report
I think the issue is caused by
LobbyManager.Instance.lobbyDialogue.ShowLoggingInStatus($"Loading user profile for {FirebaseAuth.DefaultInstance.CurrentUser.DisplayName}");
Since you bypass the login by loading Outpost station directly there is no login status/authentication
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Load up outpost station
2.Press play
3.Observe error When game starts

**Comment by RedlineTriad** [comment]
This is fixed.
