### ISSUE TITLE
NRE when entering outpost station from lobby in ControlDisplays

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2293]
# Description
![image](https://user-images.githubusercontent.com/27101670/69193104-ee686e80-0b1d-11ea-9787-06e4da72e834.png)

## Category
BUG

## Detailed Bug Report

on 
panelRight.gameObject.SetActive(true);
in HumanUI()
in ControlDisplays

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.login
2.host server
3.play
4.Choose captain
5.Observe error

**Comment by RedlineTriad** [comment]
I don't think this happens anymore.
