### ISSUE TITLE
No way to uncuff yourself or see if you are cuffed

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2294]
# Description
Currently there's no indication of whether you are currently cuffed, and no way to try to uncuff yourself.
Also perhaps help intent interaction on other player should trigger uncuff?

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Spawn handcuffs
2. Cuff yourself

**Comment by chairbender** [comment]
@fomalsd you can uncuff using a right click menu option on another player, but you can't do it on yourself

**Comment by chairbender** [comment]
also I can;t find it right now, but someone posted a screenshot showing how it's supposed to look when cuffed, your hand slots change to have cuffs joining them. We might already have this sprite in the project

EDIT: And I think we would need the player sprite also to change to indicate to others you are cuffed, but not sure how that's supposed to look

**Comment by fomalsd** [comment]
Changed the title

**Comment by chairbender** [comment]
Iirc the way self uncuffing works in tg is you get a "restrained" alert while cuffed and you click it, get a message saying you try to escape, get a long progress action (it's like at least 30 seconds) and probably it randomly fails like 50% of the time at the end.

**Comment by fomalsd** [comment]
yeah, the Resist button (which we don't have atm) triggers the escape progress as well

**Comment by JesterX666** [comment]
Here is the look on TG:

![image](https://user-images.githubusercontent.com/32009105/71317618-0f401e80-2452-11ea-95cb-ce61e9710b90.png)

**Comment by JesterX666** [comment]
For the "hands" effect in the bottom bar actions, in TG source, there are found here:
icons/mob/screen_gen.dmi
Fun fact : the icons are named "Markus" for the R hand and "Gabrielle" for the L hand.

In unitystation, they are found here:
"\unitystation\UnityProject\Assets\Textures\interface\UI\player hud\screen_gen\screen_gen_markus.png"
and
"\unitystation\UnityProject\Assets\Textures\interface\UI\player hud\screen_gen\screen_gen_gabrielle.png"

There is a special inventory slot for being Handcuffed : NamedSlot.handcuffs

**Comment by JesterX666** [comment]
Since my diagnosis/exploration is well advanced, please assign me to this feature and put it in "In progress" status.

**Comment by DooblyNoobly** [comment]
done, thanks

**Comment by JesterX666** [comment]
That's a little bigger/harder than I originally tought :(

I'll ask for a partial pull request for what's done (the icons appears on the hand in the UI) but the "click to remove" isn't done yet and should be done by someone already familiar with the project and Unity
