### ISSUE TITLE
Automatic Mining Scanner

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2300]
# Description
Implement the automatic mining scanner. This can be turned on and off by activating it.

When it is on, it periodically reveals the ore contents of each mineable tile. They appear for a moment and then gradually fade away.

This will require changing how ore works so that the contents of the rock are determined ahead of time rather than when the rock is mined.

It looks like this:
![image](https://user-images.githubusercontent.com/1329062/69371325-7d77a280-0c54-11ea-8f1c-4194e4e07d9e.png)

You can see it in action here: https://youtu.be/KOtfRZt6F3s?t=638

**Comment by PerfectTangent** [comment]
added in #8920
