### ISSUE TITLE
Minerals B: 70

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2301]
# Description
Change the logic for mineable rocks so that the minerals they contained is determined randomly on map load, not when the rock is mined.

Add all the different kinds of minerals and ores that can be mined with their appropriate rarity. This should use a prefab variant most likely. The ores should also be stackable (add Stackable component).

You can skip gibtonite for this ticket.

In TG, logic for minerals can be found in minerals.dm, for example spawn chance config is in mineralSpawnChanceList . It looks like there are multiple spawn chance lists defined so they can either be randomly swapped between or configured for a server. 

Accordingly, the spawn chance list for unitystation should be defined using an SO so it can be swapped out with others. It can be referenced from a singleton SO or manager to define which one to use when the map loads.

**Comment by DooblyNoobly** [comment]
This will be a bit involved so don't take this up unless you think you can finish it.

Contributor will receive a bounty of 70usd on a successful merge of a solution that satisfies the requested criteria above.

**Comment by Bod9001** [comment]
Funny enough I was already planning to work on this before the bounty, Might do #2412 as well as part of the PR If it's something easy to fix

**Comment by DooblyNoobly** [comment]
setting it to in progress
