### ISSUE TITLE
Proto-kinetic Accelerator

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2302]
# Description
Implement the proto-kinetic accelerator. This should include all sounds / sprites / logic so that it matches how it works in tg.

some additional details on it here: https://tgstation13.org/wiki/Shaft_Miner

You can see it in action in this video:
https://youtu.be/KOtfRZt6F3s?t=681

in TG, logic for this is in kinetic_accelerator.dm

**Comment by RedlineTriad** [comment]
Added in #3584
