### ISSUE TITLE
Basic Lavaland / Multi-map System

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2306]
# Description
This is a high effort ticket. We need a way so that we can basically be taken to a different map which is not reachable from the main OutpostStation scene. We will need to work out how this can be done since all of our current logic all takes place in a single scene. Not sure if we'd want to just "hide" lavaland in the main scene somehow or else have a way to change the client's scene (IDK if Mirror can have clients in different scenes).

We can use lavaland to help prove this out. We need to be able to get on a shuttle and be transported to lavaland. Lavaland for now can just be a simple map with some mineable rocks and with a place for the shuttle to dock and be taken back to the station.

**Comment by chairbender** [comment]
Just to add, it might be possible to do this without just having a really big scene with unreachable areas (instead use additive scenes each with their own physics scene):
https://learn.unity.com/tutorial/multi-scene-physics#5d2cd103edbc2a62042552c6

unity now allows multiple physics scenes, so by using additive scenes, and coupled with updating our internal systems to support z levels, we can have separate physics scenes for each z level (even turn them off when nobody is on them or at least set them to a low tick rate), and we can simply overlay the z levels at the origin so we can have infinite space and not get physics quirks by moving too far from origin.

EDIT: Better link https://forum.unity.com/threads/separating-physics-scenes.597697/

**Comment by NoooneyDude** [comment]
This feature has been now been implemented as subscenes. Closing.
