### ISSUE TITLE
Butchering

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2309]
# Description

Add ability to butcher hostile mobs by attacking a dead mob with a knife in hand and configure their drop tables for what they can drop. Each mob's drop table should be an SO with a list of prefabs and a drop rate for each prefab. Do NOT hardcode the drop table into a prefab, because it is highly likely we want to be able to easily swap out drop tables!

Configure a drop table for whatever mobs we already have (Xenos only at the time of writing).

**Comment by fomalsd** [comment]
It actually used to work back in the day, but stopped working for both players and NPCs

**Comment by JesterX666** [comment]
@ziiplock , You said "Partially" fixes the issue.  What is still missing?

**Comment by ziiplock** [comment]
@JesterX666 Butchering of hostile mobs (Xenos)

**Comment by ziiplock** [comment]
Actually, nevermind. Implementing this for Xenos is trivial since they have a SimpleAnimal component. I'm working on a couple of small fixes right now and will just include this in my next PR.
