### ISSUE TITLE
Consider Converting Cloths to be prefabs (and use prefab variants)

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2315]
# Description
For many things, we've had to implement custom logic specifically for handling cloths. For example, prefabs have the capability to do prefab variants, but cloths don't unless we build it.

I personally have spent many hours dealing with cloth-specific logic due to them not using prefabs. We should decide if we're really going to stick to this system or refactor them to use prefabs / prefab variants.

IMO we would save a lot of trouble if we just moved them to prefabs / prefab variants. So many features we want to develop are hindered by having to account for unicloths.

EDIT: As far as space usage goes, it should be noted that prefab variants only store their modifications upon their base prefab (as you would expect), so they don't duplicate unnecessary data, see https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Resources/Prefabs/Objects/Canisters/PlasmaCanister.prefab

Also worth noting that the new Spawnables at least provide a standardized way to spawn a prefab or a cloth, but I view this only as a temporary stopgap measure as all the difficulties I mentioned in understanding and creating the cloths still apply.

In fact, by using the prefab variant system, we could do away with the need for spawnables, which adds a bit of convenience into the editor configuration due to not needing to create a Spawnable asset. Basically removing an unnecessary layer of indirection, thus making it easier to configure things which need to be able to reference other objects. Currently it's a little tedious having to create a SpawnablePrefab, reference the prefab, then reference the Spawnable in whatever you wanted it for (like an inventory populator). With prefab variants, you'd just directly reference the prefab you wanted to populate the slot with, and if you wanted any custom initial state, you could make a variant of that prefab and modify the state in the components and use that variant to populate the slot.

**Comment by chairbender** [comment]
after some discussion on Discord, the idea of moving them to prefab variants seems okay, but we should still give it some more though / discussion and we are wondering if having so many prefab variants (one for each possible article of clothing) would cause performance issues.

EDIT: See my edit above about how prefab variants only store the modifications from the parent, which alleviates some of my performance concerns

**Comment by chairbender** [comment]
Just to note, I think the biggest reason to move to prefab variants is so that you know the prefab variant for a particular item is the central definition of what that item is. No confusion about whether the object is defined as an SO or a prefab. Then from there you can view its components and navigate its SO references to look up all the data that item is configured to use. And when you want to create something new you know you just need to create a new prefab and fill in the stuff you want.

It also means we won't need to keep adding fields to the cloth data assets so that they can be used to populate all the components on the UniCloth prefab they are going to be loaded into - that stuff can just be put directly on the prefab. Eventually if the trend continues we are going to end up with ClothData assets having a lot of fields or having to use the prefab override field which creates a confusing indirection (you have this prefab sitting around that can't be spawned by itself and instead needs to be spawned via its cloth).

**Comment by chairbender** [comment]
@DooblyNoobly @fomalsd if you get a chance, would like to hear your thoughts on this. IMO prefab variants are the right choice for this sort of thing as long as it's not going to create some sort of performance issue. Otherwise I think we will continue to find ourselves having to re-implement logic that is already provided OOTB with prefab variants and re-implement a cloth version of any prefab-based logic. And we will find contributors not wanting or being able to figure out how to do what they want with cloths. 

Also better to make this change sooner (though it seems like a pre 0.4 sort of change) rather than later because the more objects we add the more effort it becomes.

**Comment by fomalsd** [comment]
I don't mind swapping cloth scriptableObjects with prefab variants unless it makes performance/load times worse when there are around 800 different clothes (see [this](https://github.com/unitystation/unitystation/blob/a7ab52b2a4b11c3433d8864e4060ef38c4eaba90/UnityProject/Assets/Scripts/Items/ClothEnum.cs) to have an idea)

**Comment by chairbender** [comment]
Honestly the load times / memory usage of the current cloth data system is probably worse than using prefab variants, as it requires loading and caching every single cloth data asset at startup in a set of dictionaries. With prefab variants those dictionaries and loading logic can all be removed, as each prefab variant already has all the data it would need. The logic of syncing the unicloth data can also be removed, because the client knows what to display based on the config in the prefab variant.

**Comment by chairbender** [comment]
looking into this a bit more, as I think it would end up allowing us to have more stuff built out for 0.4 and I am concerned that the amount of content we might add for 0.4 will cause a lot more rework to be needed if we put this off

**Comment by chairbender** [comment]
One interesting limitation I discovered with prefab variants is you can't rearrange the order of components in a child, other than the ones you added. Our interaction framework uses the ordering of components to determine what to check first, so if there is a situation where we want something in the variant to override the interactions higher up in the parent, we would need to add a way to do that. It wouldn't be hard to change how the precedence checking works so you could explicitly define the precedence rules (such as making an InteractionPrecedence component) to support this case as an alternative to using the default precedence logic of component order.

**Comment by StrawberryMoses** [comment]
Was my hacky workaround for selected interaction / component or whatever fixed? If not it might be worth looking into both at the same time

**Comment by chairbender** [comment]
@StrawberryMoses it was! See here: https://github.com/unitystation/unitystation/wiki/Implementing-Interactions#how-can-i-trigger-interactions-manually-such-as-for-right-click-options
