### ISSUE TITLE
Add Coins

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2320]
# Description
This is a low priority addition, but it does add some flavor to the station. Coins are made out of ore and act as the value of their materials. 
Notes:
- Coins can be flipped to show head or tails
- They can be examined to show their value
- It is possible to attach a string (wire) to the coin, but this no longer has any effect on the game
- Coins can be made out of the following:
	- Iron
	- Gold
	- Silver
	- Diamond
	- Plasma
	- Uranium
	- Titanium
	- Bananium
	- Adamantine
	- Mythril
	- Plastic
	- Runite
- They have 400 units of the listed materials
- Coins can also be two headed, which only lands on heads
- Coins also have a variety for ‘antagonist token’, which is made of plastic and lands on either ‘valid’ or ‘salad’

https://github.com/tgstation/tgstation/blob/4296357b3f0d43069a27834c19cd244735bcf1ea/code/modules/mining/ores_coins.dm

## Category
TODO

**Comment by corp-0** [comment]
@NoooneyDude would you consider this done with your coins pr?

**Comment by NoooneyDude** [comment]
Oh nice, I didn't see this issue. Hmm, only thing not done is them having 400 units of the listed materials and attaching a wire.

**Comment by corp-0** [comment]
Wire part sounds weird. It says there it doesn't do anything, then why bother to implement it? If someone adds the units thing, we close.

**Comment by PetMudstone** [comment]
I believe the wire part is for doing [this kind of thing](https://tvtropes.org/pmwiki/pmwiki.php/Main/CoinOnAStringTrick) (I apologize for posting a link to TV Tropes).

**Comment by corp-0** [comment]
That makes sense, but we can do it later if we ever decided we want vendors to use coins.

**Comment by NoooneyDude** [comment]
Oh, and the two-headed coin. I guess the 400 units thing is just for selling the coin, right? If so, the coins do have an export value based on the material. Unless - can you grind coins?

**Comment by PetMudstone** [comment]
I think the 400 units of material thing is for selling coins, but it also relates to material redemption/reclamation using autolathes, recyclers, and destructive analyzers. See #4388.

**Comment by PerfectTangent** [comment]
This was finished. Coin material values can be addressed in #4388.
