### ISSUE TITLE
Add Bounty Console and Bounty System

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2323]
# Description

Bounties are a way for Cargo to make additional money by snooping through the station or asking other departments for assistance. Each bounty has a name, description, reward in credits, and a high priority marking. High priority bounties multiply the reward, with a default of 2.

Bounties are split into categories to get a distribution of bounties across different departments.

The bounty console lists all of the available bounties. It can print paper listing every bounty available. Bounties that have been fulfilled can be claimed with the console- money is not added to the cargo account until they are claimed. After 5 bounties are claimed, additional ones are added to the list.

Bounty Generation: https://github.com/tgstation/tgstation/blob/fa47976cbedc44cf41751d5a0db5701f69412eaa/code/modules/cargo/bounty.dm
Bounty Console: 
https://github.com/tgstation/tgstation/blob/2029163d335356dc5f78ddf04f0750c4fa06c429/code/modules/cargo/bounty_console.dm
List of Bounties:
https://github.com/tgstation/tgstation/tree/2591ce17a6609002109fc8eafa48ae0479fc0b8e/code/modules/cargo/bounties

## Category
TODO

**Comment by PerfectTangent** [comment]
closing in favour of #6150
