### ISSUE TITLE
Add Request Console

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2324]
# Description

Request console are wall mounted computers that send messages to different departments across the station. Messages are sent using the same system as the PDA server.

The request console can:

View Messages from the other departments
Request assistance from other departments, at either normal or high priority 
Request supplies from other departments, at either normal or high priority
Relay anonymous information, at either normal or high priority 
Can call for security / engineering / medical emergencies
Can turn the speaker that beeps on a message off

https://github.com/tgstation/tgstation/blob/4057c7b22c85a719cc65852fe54c1b6397fd1596/code/game/machinery/requests_console.dm

**Comment by PerfectTangent** [comment]
completed with #8808.
