### ISSUE TITLE
Add folders and file cabinets

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2327]
# Description

Folders and file cabinets hold paper to be grouped together. When used, they display a popup where paper can either be removed or viewed.

- [x] add folders
- [x] add file cabinets

https://github.com/tgstation/tgstation/blob/cc1f39661c1cda8de1caa005ea199bb3d8ca591f/code/modules/paperwork/folders.dm
https://github.com/tgstation/tgstation/blob/dd6fa5ededb15c36bb0f0663a4f37c8c699036a5/code/modules/paperwork/filingcabinet.dm

**Comment by dapocalypse** [comment]
Ill take this up
