### ISSUE TITLE
`CustomNetworkManager.IsServer` can give NRE in Awake()

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2329]
# Description
`CustomNetworkManager.Instance` can be null during Awake()/Start(), which causes `Instance._IsServer` to throw an NRE.
A workaround is to create a waiting coroutine in places where you need to evaluate it, [like here](https://github.com/unitystation/unitystation/blob/3c2bb3de6dc58ee7f1b74b83eca1d18a005c3366/UnityProject/Assets/Scripts/Spawners/NPCSpawner.cs#L35), but it's not very pretty

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
At the moment it's reproducible with Stackables, just start the game and see a bunch of exceptions:
```
[13:18:07:244] NullReferenceException: Object reference not set to an instance of an object
CustomNetworkManager.get_IsServer () (at Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs:15)
Stackable.Awake () (at Assets/Scripts/Items/Stackable.cs:42)
```

**Comment by fomalsd** [comment]
how do you feel about a solution like this? suitable for stuff that can be done asynchronously
```cs
	private void Awake()
	{
		pickupable = GetComponent<Pickupable>();
		prefab = Spawn.DeterminePrefab(gameObject);
		amount = initialAmount;
		pushPull = GetComponent<PushPull>();
		registerTile = GetComponent<RegisterTile>();

		this.WaitForNetworkManager(() =>
		{
			if (CustomNetworkManager.IsServer)
			{
				registerTile.OnLocalPositionChangedServer.AddListener(OnLocalPositionChangedServer);
			}
		});
	}
```
– WaitForNetworkManager is an extension method available for every MonoBehaviour

**Comment by DooblyNoobly** [comment]
Ooo I like that
