### ISSUE TITLE
Clothes fail to sync on client when "EVA ready" command is executed

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2332]
# Description
Getting `No Cloth Data found for clothname` exceptions on client after debug command is invoked:
<img width="1145" alt="Scr 2019-11-22 в 23 41 18" src="https://user-images.githubusercontent.com/10403536/69459099-0c360d80-0d82-11ea-8688-10b61cfe8645.png">

cloth setting code is basically like this:
```cs
var suit = Spawn.ServerCloth(Spawn.ClothingStoredData["mining hard suit"]).GameObject;
Inventory.ServerAdd(suit, player.Script.ItemStorage.GetNamedItemSlot(NamedSlot.exosuit), ReplacementStrategy.Drop);
```

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host from editor, join from client. Find each other
2. Execute `Networking>Make players EVA-ready` command from editor
3. Notice new clothes aren't synced on client

**Comment by chairbender** [comment]
@fomalsd this still happening?

**Comment by fomalsd** [comment]
not sure, will recheck

**Comment by fomalsd** [comment]
seems fine now
