### ISSUE TITLE
Add cloak cosmetic items

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2335]
# Description

The heads of staff have cloaks, cosmetic items that are specific to the role and are worn on the neck slot. There are also cloaks made out of monsters, but it's fine to only do the heads of staff. These are pretty much only cosmetic, but they can also hide the backpack slot.

https://github.com/tgstation/tgstation/blob/master/code/modules/clothing/suits/cloaks.dm

First issue notes:
There are a few different parts of code that you'll need to touch to get this to work.
First, you'll want to make a cloak prefab that inherits from (I think) neck wearable, or the wearable prefab for the next slot.
Then, for each cloak, make a child prefab that inherits from the first one. These will each need to have their in hand and world sprites defined- check any of the clothing prefabs to see how to do this.
Finally, for extra credit, the cloaks will need to hide the backpack slot when they're worn. This may be a little harder- I would suggest making a new component that would do this and attaching it to the base cloak prefab.

**Comment by daalta** [comment]
https://github.com/unitystation/unitystation/pull/2707 implemented this, I think.
