### ISSUE TITLE
Better Examine System

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2340]
# Description
We need the ability to let components on an object customize that object's examine text. For example, this is used often during construction to give hints about what you need to do next or to see what state an object is in for objects that don't have different sprites for each construction state.

We need to support components adding arbitrary lines to the examine message. For tooltips on mouseover I think it would be fine to just display the item attributes name + description, but when you actually perform the examine action on it and see the message in chat it should fire off this examine system logic so you can display more information about the object.

This also needs to be supported on tiles, though I think each tile can pretty much just have a name + description and might not need any dynamic logic at the moment (since each construction stage of a tile is its own tile asset).

The examine logic should most likely be server-side, as there are things the client wouldn't be able to know since it's not synced to them.

I might suggest just adding another interface hook, IExaminable, which has a method that allows the component to "add on" to the examine message. It would be called on server side when client requests to examine.

And as a proof of this system, please add examine logic for reinforced wall construction / deconstruction (for tile-based) and computer construction / deconstruction (for object-based)

**Comment by fomalsd** [comment]
they did have proper descriptions when dm data was a thing, maybe there’s still some way to automate it

**Comment by chairbender** [comment]
I'm doing this for all the cloths as part of #2312

**Comment by chairbender** [comment]
I will eventually be migrating the itemattributes component users to the new and improved "ItemAttributesV2" so I'll also just look up the names / descriptions when I do that and that should fix this ticket, but that won't be until a later PR.

EDIT: So I'll assign this to me.

**Comment by chairbender** [comment]
going to make this more general

**Comment by StrawberryMoses** [comment]
This should also support hovering over items that are in inventory as well
