### ISSUE TITLE
Rounds can't end properly if you park something in front of the emergency shuttle B: 25

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2345]
# Description
If you Park mining shuttle in front of the escape area, the escape shuttle will crash into it and get stuck, resulting in the round never ending

## Steps to Reproduce
1.Grab mining shuttle
2.Fly around to departures
3.Place in front of departures where Emergency escape Shuttle would be
4. Call emergency shuttle
5. Watch as it crashes and get stuck

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 25usd on a successful merge of a solution that resolves the issue above.
