### ISSUE TITLE
Posters are invisible

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2354]
# Description
Posters became invisible after #2316 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Open Outpost scene in editor
2. Search for "Poster-Random", for example
3. See that none are visible

**Comment by chairbender** [comment]
we briefly discussed this in discord, reason for this is the texture move and the poster textures were relying on loading from the textures folder. They need to be modified to load using the sprite atlas I'm pretty sure, as previously they were loading the assets directly bypassing the atlas.

**Comment by DooblyNoobly** [comment]
this was fixed last week
