### ISSUE TITLE
item sprites changing with stack amount

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2355]
# Description
In byond, stackables have their name and sprite changed depending on the stack amount:
![image](https://user-images.githubusercontent.com/10403536/69625254-1c7a1100-103e-11ea-818a-bcf9f5f0f6d4.png)
I recently added a simple EmptyFullSync script for sync of empty/full container looks, but it only accounts for either empty or full state – in case of stackables there are always from 3 to 5 states

**Comment by chairbender** [comment]
should be super easy, just add a configurable list of serializable entries to Stackable, where each entry has a sprite and a range, then in the SyncAmount method determine the correct sprite to show and switch the sprite renderer to it before calling RefreshUI
