### ISSUE TITLE
Add the Hand Teleporter

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2357]
# Description

The Hand Teleporter is a High Risk item that may be a thieving objective of traitors. One spawns in the Captain's Office, and another spawns in the Teleporter Room. 

Notes:
- The hand teleporter is used to open portals between two places.
- When using the teleporter in hand, the user is given a list of all active teleporters on the same z-level, along with the option of "None (Dangerous)"
- Selecting a destination will open a portal in front of the user, along with 3 sparks and a sound effect
- Selecting None will open a random portal within 10 tiles of the user in any direction, along with the entrance portal
- Clicking on an active portal with the hand tele will dispel it, along with it's destination if it exists
- Only 3 portal pairs can exist at one time. If the teleporter is used while there are 3 or more, it tells the user it is recharging
- Portals dispel by themselves after 300(?) seconds

https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/teleportation.dm

**Comment by MaxIsJoe** [comment]
I think Dan finally added this item in

**Comment by eurtod** [comment]
this is in and can be closed.
