### ISSUE TITLE
Fake Walls/Hidden Doors B: 65

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2358]
# Description
I think these are rather important for gameplay:
![False_Wall](https://user-images.githubusercontent.com/10403536/69636257-17bd5900-104e-11ea-9314-632dfd7c7f7e.gif)![False_Wall_r](https://user-images.githubusercontent.com/10403536/69636305-2f94dd00-104e-11ea-8672-1ced75e98b6e.gif)

https://tgstation13.org/wiki/Guide_to_construction#Normal.2FReinforced_Hidden_Door

Implementation thoughts:
When built, these should probably still be pure wall tiles in closed state (but with a flag in metadata to indicate that it's a fake wall).
Then check for such flag when clicking wall and replace wall tile with an airlock-like object while it's open (and turn into wall tile again when it's closed).
Since everyone can see all the walls at the moment (and gets all the tile updates and object spawn/despawn messages) it won't be 100% secret (nearby people will see wall tile disappear), but we can't do much in that regard until we introduce network culling anyway. At least it will remain a secret while it's closed.

**Comment by chairbender** [comment]
Adding a bounty of 65. Foma mentioned these are important for gameplay and they're cool. I think it'll be a little complicated due to it needing to act like a wall tile until it's bumped, then turning into an airlock when opened. But foma outlined a reasonable approach to it which helps.

**Comment by CykaGuy** [comment]
I'm working on it

**Comment by Robustin** [comment]
I'm testing a couple of approaches here. I'm leaning toward adding a "dumb door" prefab that would function much like the basic stone & wood doors in /tg/code and the false-wall would just be a variety of that prefab with a different animation and a couple unique interactions with tools so that it completely imitates the behavior of the original.

**Comment by fomalsd** [comment]
fixed in #3370
