### ISSUE TITLE
Utility Suits - Fire Suit, Bomb Suit, Radiation Suit

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2361]
# Description

Some suits on the station are designed to help the wearer with certain environmental hazards. These suits may require adding some additional fields of components- do what you think is best, if anything is missing please open a new issue so they can be tracked.

Full List of Suits:
- Standard firesuit
  - Firefighter firesuit (only different sprite)
  - Heavy firesuit (slows down user)
  - Atmos Firesuit (grants total immunity to fire)
- Bomb Hood
  - Security Bomb Hood
  - White Bomb Hood
- Bomb Suit
  - Security Bomb Suit
  - White Bomb Suit
- Radiation Hood
- Radiation Suit

Some attributes on the suits that may not be in the codebase:
- gas_transfer_coefficient : This does nothing! (as far as I can tell). Feel free to ignore!
- permeability_coefficient : This var determines how easy it is for diseases (?) to get within the suit and infect the wearer. This may be better to wait until Virology role is added.
- body_parts_covered : List of body parts that the clothing item covers. It's used in certain checks such as combat or stepping on glass.
- allowed : Looks to be a whitelist of what items can fit inside the external suit storage slot
- slowdown : Adds some amount of slowdown to the mob wearing the item (https://github.com/tgstation/tgstation/blob/b5fa054347b0c16d79125348c492166a8ac86735/code/modules/mob/mob_movespeed.dm). Depending on how move speed is already calculated within our codebase, this may also be worth waiting for another story.
- flags_inv : Which clothing items this hides- such as not showing shoes or jumpsuit.
- clothing_flags : Additional attributes that the suit gives, such as stopping pressure damage. 
- temperature protection vars
- strip_delay and equip_delay : How much longer it takes to add or remove this object from someone else
- rad_flags : Helpers for radiation. Can probably wait until radiation is implemented

https://github.com/tgstation/tgstation/blob/5fae07158264a8ec053c16ce3c9af24ba2680771/code/modules/clothing/suits/utility.dm

**Comment by chairbender** [comment]
Nice, thanks for tracking down all the settings, that'll save a lot of time on this. I think these would probably be added as fields to ItemAttributesV2 for anything that is general to all items, and we can subclass ItemAttributesV2 to make a clothing-specific one, like ClothingAttributes for the clothing-specific fields. Most of the fields you listed here seem to be clothing specific.

**Comment by fomalsd** [comment]
don't we already have some of these in?

**Comment by PetMudstone** [comment]
I added utility suits (and bio suits) in #3402 three months ago, but not all the "attributes" above are integrated into Unitystation at the moment. At the very least, firesuits and bombsuits are useful now since armor works. They help protect you in case of fire or bomb.

**Comment by PerfectTangent** [comment]
I think this has been satisfied. The remaining features should be put into their own issues.
