### ISSUE TITLE
Soft Hats

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2363]
# Description

Fashionless accessories mostly seen in cargo. Hats can be alt-clicked to flip them around and making you look like a rad dude.

Hat variants include:
- Cargo Cap (should be used as a base prefab)
- Red
- Blue
- Green
- Yellow
- Grey
- Orange
- Mime
- Purple
- Black
- Rainbow
- EMT
- Sec

The sec hat provides armor and has a delay on taking it off of another player.

https://github.com/tgstation/tgstation/blob/58fd5ff8a4db0219e5e6914c7e2c01d2115947aa/code/modules/clothing/head/soft_caps.dm

**Comment by NoooneyDude** [comment]
All of these caps seem to be added except for the special properties of the `SecurityCap`. They don't seem to be flippable, either.
