### ISSUE TITLE
Door Remotes

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2364]
# Description

Door remotes are exactly as they sound. They are remote controls for doors within a department. They have three modes that they can be switched between: Opening / Closing Doors, Toggling the Bolts, and Emergency Access. Emergency Access removes access restrictions. The effect will be applied to any door the player clicks while the remote is in their hand. They do not need to be next to the door to use the remote, (I think) it just needs to be visible.

Variants:
- Omni (any door on the station)
- Command
- Engineering
- Research
- Security
- Supply
- Medical
- Civilian

Most spawn in the appropriate heads of staff locker, including the quartermaster.

https://github.com/tgstation/tgstation/blob/f5bd6a381d18765624b81b4aca7fa4126b9dc2ca/code/game/objects/items/control_wand.dm

For access on these, see:

https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/access.dm

**Comment by PerfectTangent** [comment]
closing in favour of #5819
