### ISSUE TITLE
Sloths

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2366]
# Description

Add sloths as a simple animal. In addition to the base sloth, two exist specifically for cargo- Paperwork and Citrus. Citrus wears a horrible sweater.

- [x] Add Paperwork

- [x] Add Citrus

- [x] Add sloth simple mob

https://github.com/tgstation/tgstation/blob/39fead370a157b78e7aaa9493a7a20938441935a/code/modules/mob/living/simple_animal/friendly/sloth.dm

**Comment by NoooneyDude** [comment]
Completed by PR #5369.
