### ISSUE TITLE
Conveyor Belts

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2369]
# Description
What's Cargo without conveyor belts?
![image](https://user-images.githubusercontent.com/10403536/69713196-06328a80-10fc-11ea-9063-b80d692438a0.png)

https://tgstation13.org/wiki/Guide_to_construction#Conveyor_Belt
https://github.com/tgstation/tgstation/blob/99555adc393619c54314e3b99c5c0e5cef2eff5b/code/modules/recycling/conveyor2.dm

It sure adds a lot to the gameplay thanks to traps and other wild contraptions that become possible with these.

Should also:
- use power
- have a switch
- be able to go reverse
- be able to vary speed (?)
- support corners
- change direction when hit with a wrench

**Comment by fomalsd** [comment]
I think this one needs a solid implementation and deserves a bounty

**Comment by RedlineTriad** [comment]
Added in:  #3921
