### ISSUE TITLE
Replace stray Resource.Loads with GameObject references

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2373]
# Description
Replace any random Resource.Load uses with GameObject referenced through the editor instead.
This doesn't apply in places where there are a lot of objects to be referenced, like clothing data or sprites.

eg remove this kind of logic and add the reference through the inspector:
![image](https://user-images.githubusercontent.com/4493127/69769323-4c2f3300-117c-11ea-8273-92d2e0716f07.png)

Then you can safely move the prefab out of its nested 'Resources' folder.

**Comment by Jorge1o1** [comment]
I will do this

**Comment by RedlineTriad** [comment]
@Jorge1o1 are you still working on this?

**Comment by corp-0** [comment]
I'm unassigning this to make it clear it is free for anyone who wants to give it a try.

**Comment by corp-0** [comment]
we already moved prefabs outside of Resources folder, closing.
