### ISSUE TITLE
Fill out the build menus for all materials

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2376]
# Description
Currently only Metal has a build menu.

Use this as a reference: https://tgstation13.org/wiki/Guide_to_construction

Create prefabs and fill out the rest of the build menus for all of the materials. Make sure that any new prefabs you create use prefab variants and inherit from the proper parent [as documented here](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants). Make sure to at least fill in the ItemAttributesV2 name and description. You don't have to implement the actual logic for the new objects unless you feel inspired, just set them up so they show up and have the correct sprite. Some objects might even be possible to implement just by selecting the right components. But check first to see if the object has already been implemented, since some already have (in that case you don't need to refactor the object to use prefab variants, that will come after 0.4).

**Comment by PerfectTangent** [comment]
Several other materials have since gained construction lists with items to construct. Closing this issue.
