### ISSUE TITLE
Set up all the belts

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2378]
# Description
Set up all the belts so they have the correct structures, capacities, and initial items (in their Full variants).

You should use prefab variants for each different type of belt. Use the existing belt prefabs as a reference. You can find the folder with all the belt sprites / existing belt data assets at Assets/Textures/clothing/belt/. Set up the other belts that we have sprite sheets for, create an empty and full variant for each one and make sure any occupations which start with those belts will spawn with the correct belt. Make sure any prefabs you create follow the guidelines here: https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants

**Comment by NoooneyDude** [comment]
It seems all belts are variants of the Beltwear prefab, and the only belt that doesn't have a populated prefab version is the medical belt.

Update: actually, the medical belt is populated, there is just no empty variant.

**Comment by PerfectTangent** [comment]
This has been done for quite some time, correct? I'm going to close it until otherwise noted.
