### ISSUE TITLE
Create crit and death overlays (black screen shroud) B:25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#238]
Create the death and crit overlay sprites and animate them. (The circle that surrounds the body)

**Comment by TheBimmer231** [comment]
icons/mob/screen_full.dmi

**Comment by DooblyNoobly** [comment]
Criteria:

- Implement the overlay screen animations for Crit
- Implement the heart rate animations
- Handle the soundfx correctly (heart pumping, any other ambient sounds that are heard while crit)
- Make sure all changes can be reset easily and globally

Bounty: 25 usd paid via paypal on successful merge
