### ISSUE TITLE
Proper Limb-Based and Environmental Damage Calculation

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2381]
# Description
Probably depends on #2361 

Basically just making sure the damage logic matches the tg logic. Make sure the logic for checking what damage should be applied to a given limb will check the equipped clothing to determine what the armor / resistances are. Remember that some items, such as exosuit, can provide protection to multiple body parts.

Additionally make sure that the way environmental damage (such as fire) is applied is correct, such as ensuring it damages the correct equipment / body part and is spread out over the body as it should be according to tg logic.

**Comment by PerfectTangent** [comment]
This seems like a really outdated issue, since we've had these functions for a long time and we've also reworked them slightly. Closing.
