### ISSUE TITLE
Figure out / fix all the stuff that keeps showing as modified

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2384]
# Description
There's a lot of stuff that makes people "afraid to even open Unity", showing as changed when it hasn't been touched at all. Investigate what of this can be ignored from git, fixed so that it doesn't get constantly changed, or figure out what practices can be done to avoid it showing as changed. Probably need to start by making a list of what we keep seeing as changed.

There may be some things that should just be removed entirely from git if they are auto-generated by unity.

List of stuff that seems to change for no reason (please add to this):
- [ ] Sprite Atlases
- [ ] Occupations (covered by #2374 )
- [ ] Firebase/Plugins (some stuff in there always shows as removed for me)

**Comment by fomalsd** [comment]
also these
![image](https://user-images.githubusercontent.com/10403536/69799555-62b0ab00-11cb-11ea-9708-373ad4633f14.png)

**Comment by corp-0** [comment]
There is no way around this. Maybe this issue should be closed.

**Comment by ThatDan123** [comment]
Its only a few things now, so im gonna close this.
