### ISSUE TITLE
Editor tool for migrating prefab instances in scene

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2386]
# Description
With the move towards prefab variants and possibly for other future situations, there will be some cases where we want to create a new prefab for a particular object and migrate all the instances of the old prefab in the scene over to using the new one.

Create a tool which automatically does this.

It should have the ability to automatically copy over any fields from the old instance to the new instance, for any component which still exists on the old and new prefab. For example, for wallmounts, it should preserve the Directional settings. By iterating through each of the serialized fields on each of the components, I think it should be possible to do this automatically without having to write specific logic for each component. Or maybe there is a built in way to do this already in one of the APIs?

There may be some code that can show how to do this here: https://forum.unity.com/threads/a-script-replacing-one-prefab-with-another.681805/

**Comment by NoooneyDude** [comment]
I believe PR #4415 solves this issue.
