### ISSUE TITLE
Base attributes that item attributes inherits from

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2387]
# Description
so It would be nice to be able to define attributes that cover items and objects, 
currently we only have item attributes
So what I'm proposing is we have This base attribute, That item attributes inherit from and object attributes inherit from, so let's say if you wanted to add cell price you could easily add it by adding it to the base attribute, And it would apply to every thing in the game, From wall mounts to items
Some more discussion is needed

**Comment by chairbender** [comment]
Makes sense. Note that some objects currently use Item Attributes. Also we are migrating over to Item AttributesV2 so would suggest waiting for #2380 for that

**Comment by chairbender** [comment]
@Bod9001 isn't this done now?

**Comment by Bod9001** [comment]
yeah well a lot of stuff uses Item Attributes and most objects don't have the object attribute yet

**Comment by chairbender** [comment]
I think it's fine to close this, the basic components are already in place, it's just a matter of continuing to use them like we already have.
