### ISSUE TITLE
More traditional throwing

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2388]
# Description
At the moment thrown items always miss the clicked position, sliding farther than expected. 
It's impossible to make things stop closer than like 2.5 tiles away (with standard throw range and speed).
Also while technically more realistic, rotated items aren't too pretty and are harder to pick up.

Thrown items should: 

- land on the designated tile (if within range) with minimal residual movement
- if rotated during flight, they should become upright after landing (in a nice looking way)
- if flight is abruptly stopped by a wall, item should slide along the wall for a bit
- perhaps a hitbox should be increased from just a central point to something like 0.5x0.5 square to avoid items partially covering the walls:

![image](https://user-images.githubusercontent.com/10403536/69809914-a1059480-11e2-11ea-97bd-bd323341de6b.png)

**Comment by fomalsd** [comment]
Related issues: #1779, #1733

**Comment by corp-0** [comment]
maybe add a variable slideAmount property? So you could have objects that given their shape/nature, slide/roll farther.

**Comment by PerfectTangent** [comment]
Throwing reimplemented in #8335. Closing.
