### ISSUE TITLE
Pod Doors

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2389]
# Description

Pod Doors are essentially shutters, but with additional armor and resistance. They are opened using buttons. They are additionally heat proof, able to block some explosions, and have a ton of armor for most attacks. These are most commonly seen in the cargo bay, to keep the air inside, and the incinerator.

https://github.com/tgstation/tgstation/blob/4057c7b22c85a719cc65852fe54c1b6397fd1596/code/game/machinery/doors/poddoor.dm

**Comment by RedlineTriad** [comment]
Was told they were in but not sure which PR.
