### ISSUE TITLE
Autodrobes

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2391]
# Description

Autodrobes are vending machines that vend clothing items related to the department's position.
For example, the "CargoDrobe" dispenses cargo tech jumpsuits, jumpskirts, gloves, hats, etc. These should inherit from the vending machine prefab, but should also have a base wardrobe prefab that can be used to define a few common behaviours. Additionally, if not implemented, vending machines should define a department to be linked to, with a default setting to link to no department. In TG code this is "NO_FREEBIES" (commies go home).

Products for each autodrobe should be defined in a list. The default price of items in this list is $50, unless the item has a custom price (potentially defined in it's itemattributes). For example, the CargoDrobe sells cargo jumpsuits for $50, but fingerless gloves sell for $10. If department accounts are implemented, the money will go into the department account.

An additional list should be defined for "Premium" items, cost at $75. For example, the SecDrobe sells formal and navy uniforms for a premium price.

When the player is in the same department that the autodrobe is linked to, all normal products are given for free (premium items are still charged for).

Players can also insert non premium items back into the autodrobe to return them. These appear in a list at the top on TG, and have a price reflecting the original. Premium items cannot be returned. This may be skipped over for this story, if a new one is opened to take care of it later. 

These venders all have custom names, descriptions, and ad reads.

https://github.com/tgstation/tgstation/blob/67c16e8af2e7de488b9353e756995500cf175811/code/modules/vending/wardrobes.dm

**Comment by RedlineTriad** [comment]
Added in #3965
