### ISSUE TITLE
Significant Startup Delay in Editor

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2393]
# Description
It has started happening more often. Clicking Play in the editor causes sometimes as much as a 10 minute editor freeze. Get to the bottom of this and see how to fix it. Recommend looking at the profiler since it can show what's happening in the editor.

We have speculated it has to do with generating the preview sprites (PreviewSpriteBuilder), but I don't see those being generated and I still get this delay.

I also previously thought it only happened when changing prefabs, like moving or adding them, but I get it even when I don't do that.

**Comment by chairbender** [comment]
Despite the fact that it isn't generating any new sprites, I still suspect PreviewSpriteBuilder because it has logic which runs when you hit play that seems to do a lot of scanning.

**Comment by fomalsd** [comment]
Researched the problem and turns out it's just atlases. 
With sprite packing disabled, first launch is 17s. With sprite packing enabled, it's more than 10 minutes!
