### ISSUE TITLE
Disposals System

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2398]
# Description

The station's jobs generate a surprising amount of waste, so disposals is needed to get rid of it all. The Disposals system is also used to escape trouble, and can grind up trash to make metal and other materials. First, all disposal bins on the station route to a room in the cargo bay, shot onto a belt. The belt feeds back into a new disposals loop that leads to the trash room in maintenance. From there, it is either ground up and recycled or shot into space.

This can probably be split up into multiple parts.

Disposal bins are placed in almost every room and hallways on the station. They function by taking in air from the room, and using it to flush the contents. When being flushed, TG code places everything (including the gas) into a container object to better track it (https://github.com/tgstation/tgstation/blob/88df5adb7773ee9e28cc5db9217f06645e8a2944/code/modules/recycling/disposal/holder.dm).

https://github.com/tgstation/tgstation/blob/88df5adb7773ee9e28cc5db9217f06645e8a2944/code/modules/recycling/disposal/bin.dm

Disposal pipes are underneath the floor tiles and run through maintenance. Then can be placed by wrenching one to the floor and then welding it.

https://github.com/tgstation/tgstation/blob/88df5adb7773ee9e28cc5db9217f06645e8a2944/code/modules/recycling/disposal/pipe.dm

After traveling through the pipes, they are expelled from an outlet.

https://github.com/tgstation/tgstation/blob/88df5adb7773ee9e28cc5db9217f06645e8a2944/code/modules/recycling/disposal/outlet.dm

**Comment by NoooneyDude** [comment]
This can be closed as of #4524.
