### ISSUE TITLE
General purpose standard way to make sparks

### ISSUE THREAD

**Issue by StrawberryMoses** [unitystation/unitystation#2410]
# Description

On the station, lots of things spark- cutting wires on doors, using a teleporter, changing RCD mode, every once in a while from a broken light, etc

We need a way to spawn sparks that can light fires and give a little tiny bit of light.

**Comment by fomalsd** [comment]
Suggest using `Effect` class for this, so that usage is as simple as `Effect.Sparks(worldPos)`
