### ISSUE TITLE
Hand gun won't go in the belt slot

### ISSUE THREAD

**Issue by alexanderbalsamo** [unitystation/unitystation#2414]
# Description
Hand guns (small and medium) will not go in the belt slot. 

## Detailed Bug Report
Attempted with the captain. 
![gunError](https://user-images.githubusercontent.com/51460228/70176250-2a670c00-16a6-11ea-8569-66972b3cefb0.png)

## Steps to Reproduce
1. Pick up hand gun.
2. Attempt to put in belt slot.
3. Note that it will not fit, and get errror "gun can't go in that slot"

**Comment by christmoore** [comment]
@cvdva  is this still being worked on?

**Comment by chairbender** [comment]
no longer worked on, feel free to take this

**Comment by christmoore** [comment]
I will work on this

**Comment by christmoore** [comment]
@chairbender 

Please close. All handguns have the belt trait and can go in the belt slot.
