### ISSUE TITLE
Develop a way to send a server update message when a player has entered the visible proximity of a network object B: 140

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2421]
# Description
At the moment we have two proximity based Server Send Messages: SendToAllVisiblePlayers and SendToNearbyPlayers. We need a way to send a server update message when a player comes into visible range of a network object.

## Criteria: 

- We need a way for a server message to send an update message automatically when a player on the server enters the visible proximity of a network object for the first time (like an OnTriggerEnter event). 

- Develop a performant reusable solution this is easy to add to any network script

Contributor will receive a bounty of 70usd on a successful merge of a solution that resolves the task request above.

**Comment by DooblyNoobly** [comment]
Updating the bounty to 140 as this is quite a complex problem to solve

**Comment by stavrohristo90** [comment]
was this done already?

**Comment by fomalsd** [comment]
no, it wasn't

**Comment by stavrohristo90** [comment]
hit me up in discord stahrBTW#6829
i'll do it for free

**Comment by Macoron** [comment]
Wanna try this one. Will come back if get any results.

**Comment by DooblyNoobly** [comment]
NetworkProximity component does the trick. We can just override it for specialized behaviours. Closing this now
