### ISSUE TITLE
Can shoot through walls

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2424]
# Description
Raycasts are wonky™
![GIF](https://user-images.githubusercontent.com/10403536/70227396-6c498e00-174a-11ea-9cda-c7cae5d65aa4.gif)
Yes, this happened before (#550)
Perhaps using tile checks instead will avoid this

**Comment by Bod9001** [comment]
![image](https://cdn.discordapp.com/attachments/312454684021620736/654358619336212480/sdadasdasdGIF.gif)
Replicated with asteroids

**Comment by ThatDan123** [comment]
Seems like this was fixed in #4276
