### ISSUE TITLE
Develop the foot step soundfx logic B: 60

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2426]
# Criteria:

- Create a way to play 3d foot step sound effects whenever a player is moving
- Make sure the walking soundfx feels natural to the source player (if the movement is quick then make the tempo of the footsteps faster)
- Take into account when to play the soundfx to other players based on if the other player is visible or not
- Set up a way to apply custom reverb effects to the footstep sound effect based on the tile or area that the source player is in
- Try to be creative with the reverbs and effects to a state where the overall soundfx system adds to the overall atmospherics of the game experience itself
- Test in MP thoroughly with 2 or more clients

Contributor will receive a bounty of 60usd on a successful merge of a solution that resolves the task request above.

**Comment by fomalsd** [comment]
- Make sure it's easy to swap footstep sounds (e.g. for squeaky shoes)

**Comment by chairbender** [comment]
This will most likely require touching floor tile assets, so please hold off on this until my next PR which is making quite a few changes to floor tiles.

**Comment by chairbender** [comment]
Should be good to work on once #2429 is closed

**Comment by chairbender** [comment]
I think bod is looking at this right now
