### ISSUE TITLE
Unity doesn't compile game properly for the first time after first import/full reimport

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2430]
# Description
Game starts up broken for the first time after import/reimport. This didn't happen in 2018.3/without Mirror.
You have to either change a random line of code or make a standalone build to make Unity recompile forcefully.
This certainly affects new potential contributors that just want to check out the game and instead are greeted with exceptions and "0 players".

Need a way to make Unity do a proper recompile after first import to make it work out of the box.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Do a full reimport
2. Try launching game

**Comment by Bod9001** [comment]
There was one person who is still having bug even after build

**Comment by corp-0** [comment]
I don't know of any of the new devs having this problem anymore. I think this is safe to close.

**Comment by corp-0** [comment]
closing since this doens't seem to be a thing anymore. Feel free to reopen if anyone experiences it again.
