### ISSUE TITLE
Facing direction hicups on high ping clients B: 45

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2432]
# Description

The gif below was recorded on a connection with a ping of 380ms.
The blue squares show when the facing direction gets updated with a wrong value

![facingdirbug](https://user-images.githubusercontent.com/20813925/70371080-1d525300-191a-11ea-9b18-b9ad4d3d5418.gif)

Contributor will receive a bounty of 45usd on a successful merge of a solution that resolves the issue above.

**Comment by chairbender** [comment]
just to note, it only seems to show up when you are bumping into things or rubbing against walls
