### ISSUE TITLE
Top right window gets stuck after Server restart on client

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2435]
# Description
![image](https://user-images.githubusercontent.com/27101670/70375564-fd5d6800-18f6-11ea-830f-c6fcca691fe2.png)

## Detailed Bug Report
It can't expand open

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. join headless server
2. open menu
3.Close headless server/restart
4. Observe menu being broken?

**Comment by NoooneyDude** [comment]
While the drawer window is still open when rejoining, I couldn't reproduce the menu being broken. It seems to works fine now.

**Comment by Aranclanos** [comment]
cant reproduce either
