### ISSUE TITLE
Large fires no longer happen?

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2438]
# Description
Fires no longer expand regardless of plasma/oxygen amounts in the room.
Reproducible locally.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Spawn in atmosia
2. Open plasma and oxygen tanks
3. Turn on a welder or artificially hotspot some item via right click menu
4. Observe a small fire that dies down in a second, while it should spread like hell and take over the station

**Comment by Bod9001** [comment]
Once you get the fire started it's okay, the main issues getting it ignited, 

It needs to get to the critical temperature so probably best way to do this is reduce the ignition temperature or make it so it heats up quicker

**Comment by Emma3DSS** [comment]
I'ill reduce the ignition temperature so that we can close this issue :) otherwise once it gets started it is fine
