### ISSUE TITLE
Locker/crate content appearance order doesn't reflect pick up order

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2439]
# Description
Easy to reproduce in botany crate: you'll see grape seeds on top, but will get other seeds when clicked
![crate_annoy](https://user-images.githubusercontent.com/10403536/70382246-d429ef80-1969-11ea-8e2c-8d8000f75b88.gif)

It should be "WYSIWYG"

**Comment by chairbender** [comment]
Brought this up in Bod's PR, it's because of z fighting - they all have the same sorting layer and order in layer. Need to make them different depending on the packet.

**Comment by JesterX666** [comment]
Because of the Z-Fighting, just walking around seeds packs on the floor on the same tile, sometimes even change the sprite displayed on top.  There seems to be a unity component for that sort of problem : "Sorting Group"

https://docs.unity3d.com/560/Documentation/Manual/SortingGroup.html
