### ISSUE TITLE
Shuttle console sometimes closes during ship rotation

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2441]
# Description
Rotating ship while staying adjacent to shuttle console sometimes triggers tab closing.
Consider switching to `SpatialRelationship` system and see if it helps

**Comment by Bod9001** [comment]
As a bit of funkiness going on with the update for player position on matrices, If you are on the emergency shuttle and stand next to 1 of the walls, you will occasionally glitch inside of it then pop back to your original position

**Comment by chairbender** [comment]
also seems to become difficult to interact with if you set a low speed, sometimes even downright impossible to interact with, I have to resolve this for my current PR

EDIT: More reproducible  when you are moving laterally from the shuttle's mapped facing direction
