### ISSUE TITLE
ID weirdness on headless

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2444]
# Description
There are a few things wrong with IDs that we have encountered while testing build 3930 on dev server:

- Any ID picked up by captain became all access (!), and even started looking golden when on floor, while name and role name remained the same
<img width="476" alt="img" src="https://user-images.githubusercontent.com/10403536/70382566-64b6fe80-196f-11ea-8aa3-0fa1dce2b83f.png">

- Any picked up ID became recolored to player's own initial ID while in local inventory:

![img](https://user-images.githubusercontent.com/10403536/70381964-a8f0d180-1964-11ea-8ca0-4affe2891a75.gif)

- After round restart players spawned without IDs (but that might be a round restart-related bug)

Also: if you have an ID in your ID slot and another one in your hand slot, ID slot one is used for door access check. Not sure if this is right.

**Comment by chairbender** [comment]
oops, forgot to set the auto id to only auto-init once.
