### ISSUE TITLE
Make computers eject contents upon disassembly

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2451]
# Description
Computers should eject anything they might have inside (like IDs) upon disassembly, currently you just lose them

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Put your id into comms console
2. Screwdriver it
3. Your id is gone forever

**Comment by chairbender** [comment]
all this needs is to add logic to Computer when deconstructing to a computer frame, it should get ItemStorage component and call Inventory.ServerDrop on all slots. Probably best to add a new method to ItemStorage called ItemStorage.ServerDropAll which does this.

**Comment by chairbender** [comment]
ehh I might do this as part of the PR since it's so easy
