### ISSUE TITLE
Lobby Music Additions B: 45

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2454]
# Criteria:

- Determine when a track ends (checking AudioSource.isPlaying is one way to do it) and play another random track after it stops (make sure not to play the last song that just played)
- Show the Name of the song and the Artist somewhere on the lobby screen. Make sure it updates correctly when a new track is played
- Make sure the placement and size of the text fits in with the overall layout
- Add the Space Asshole song to our lobby music list rotation: https://www.youtube.com/watch?v=GISnTECX8Eg Chris has given us permission to use it

Contributor will receive a bounty of 45usd on a successful merge of a solution that meets the criteria above.

**Comment by StrawberryMoses** [comment]
Going to give this one a shot

**Comment by chairbender** [comment]
I think someone is working on this, not sure if it's still Moses

**Comment by nikopetr** [comment]
Its me !

**Comment by nikopetr** [comment]
Almost finished, the only issue I currently work on is to find a way to determine when the tracks which are played by the sunvox end, since they are not AudioSource objects.
