### ISSUE TITLE
Floor punching really disrupts combat

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2460]
# Description
90% Of the clicks in combat are Misses, The short pause when hitting the floor really disrupts the combat flow

## Detailed Bug Report
in the byond Version floors and walls don't have a default interaction

## Steps to remedy
New combat system compared to the old version
Removing the interaction
Change up the combat system to include this

**Comment by chairbender** [comment]
Is there any situation in which you should be able to attack the floor?

**Comment by Bod9001** [comment]
humm I don't think there is any, 
Stuff like mops interact with the floor but That's probably an override on the mop end

**Comment by chairbender** [comment]
I'll do this along with my next PR

**Comment by Bod9001** [comment]
IMO The current combat system is a bit terrible in the byond version, so something new would be nice but I think there is more important stuff to focus on
