### ISSUE TITLE
Add Propulsion from Handheld canisters

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2461]
# Description
This is meant for when the player gets stuck in space and do not have any items to throw,  They could use a bit of their Oxygen to give them a little nudge Roughly 5 seconds of breathing, 
Every station Race should Spawn with a tank Including cyborgs in a way

If you're a race that doesn't breath, And you go out Without a tank you are risking yourself getting stuck

**Comment by fomalsd** [comment]
how do you propose it to work exactly?
we could make a NetUI for holdable gas tanks to allow opening/closing them and adjusting release rate like in big ones (I recall this being a thing in byond, but it was mainly used for internals), then releasing gas while holding them could push player against their current facing direction

**Comment by Bod9001** [comment]
Could be just simple and activate the tank in your hand and it releases a small amount

**Comment by PerfectTangent** [comment]
related to #6052
