### ISSUE TITLE
Upgrade Mirror to latest asset store release

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2462]
# Description
A new asset store release of mirror just came out, we should upgrade as these releases are supposed to be stable.

I will probably take this on after my next PR since I've already done a fair bit of work with previous mirror upgrade attempts.

**Comment by Bod9001** [comment]
yeah, Mirror uses a lot of performance Checking network objects to see if they've changed, So I want to see what it's like in the new version, To see if it's been sorted,  if it's still an issue then Solutions can Start being developed and implemented

**Comment by chairbender** [comment]
doin it!

**Comment by chairbender** [comment]
notes https://github.com/unitystation/unitystation/wiki/Mirror-Upgrade-Customization-Notes
