### ISSUE TITLE
when there is a station wide fire, after the fire is finished update manager consumes a lot of processing time

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2480]
# Description
it made the FPS like 3 but after a bit it went up to 20

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.open canisters of plasma and oxygen
2.get a station wildfire
3.observe the lag after it's finished burning

**Comment by RedlineTriad** [comment]
Closing for now since fire performance is better.
