### ISSUE TITLE
Lights and Light Switches Inconsistencies B: 60

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2485]
# Description
The way that lights and switches work need to be more consistent. Here's how they work now:

1. Nothing in the editor indicates which light are connected to which switches, nor which lights are powered by a given APC.
2. When the round starts, switches determine which lights they are connected to based on proximity and facing. It's janky and oftentimes the client and server don't agree, especially if client joins when there's a rotated matrix.
3. When a switch determines it is connected to a light, it broadcasts Received and the light then knows what APC it's connected to.

The jank is most noticeable when client joins while a matrix has been rotated:
1. Add syndicate to AllowedOccupations.
2. Build and host in build. Spawn as syndie.
3. Rotate syndi shuttle facing down (2 rotations)
4. Join from editor as client.
5. On server, cockpit lights appear on but on client they appear off

There were some solutions suggested such as requiring that lights be manually mapped to indicate what they are connected to or using a wiring-based system to determine which lights are hooked up to which switches / apc. Can discuss this in #electricity in discord. 

For this ticket even a simple fix which guarantees client / server consistency of lights would be acceptable as well. Perhaps a synclist or net message would be better. Current system requires that client and server both calculate it themselves and agree.

**Comment by Ranzarth** [comment]
You can already set the Lights to use a certain APC and Light switch manually.

**Comment by ReiderJack** [comment]
working on it

**Comment by DooblyNoobly** [comment]
Reider was the emergency lighting problem fixed?
