### ISSUE TITLE
Round join occupations Don't update

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2490]
# Description
When you join It shows all Roles as available, No matter if they have been taken already Resulting in being able to have multiple captains on a station

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Host server
2.Join on one client and play as Capt
3.Join on Other client and Notice the free captains Slot

**Comment by Jibbajabbafic** [comment]
Duplicate of #1580

**Comment by Bod9001** [comment]
dam, Searched for player and occupation xD

**Comment by Jibbajabbafic** [comment]
Added some more words to the title and copied the description to the other issue
