### ISSUE TITLE
Setup better wiki page

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2491]
# Description

The current problem is that you need write access to the repository to add stuff
It makes it a pain to add stuff from Part-time devs

There are suggestions of using hackmd.io for the wiki page, But going through the current github PR system might be good as well

**Comment by voidel** [comment]
Is hosting a wiki-like out of the question?

**Comment by Bod9001** [comment]
could do, it's just making something to make it easy to add content to and manage,
like in a perfect world it would be some HTML on the github then you can go through the same system you used to make pull requests

**Comment by voidel** [comment]
Ah, you can do that with GitHub. It's called GitHub Pages.

**Comment by Bod9001** [comment]
that seems good

**Comment by Jibbajabbafic** [comment]
Related to #2450

**Comment by christmoore** [comment]
Not sure if you're aware, but it's possible to give write privileges for solely your documentation to the community. But if you want to keep things through pull request, @chewbyte  is correct, GitHub Pages, they edit things within the /docs folder.

![image](https://user-images.githubusercontent.com/8658239/71627604-ff92a980-2bb8-11ea-9a6c-72e87a8e7d74.png)

**Comment by christmoore** [comment]
https://unity-station.readthedocs.io/en/latest/

Build webhook into https://github.com/MrManicotti/unitystation-wiki

@Bod9001  I believe something like this is what you're looking for.

**Comment by SweptWasTaken** [comment]
We used this website called hackmd. It might be what you're looking for.

https://hackmd.io/@ss14/docs

**Comment by christmoore** [comment]
Thank you @SweptWasTaken !

Based on discussions in General Dev, it looks like we'll be going in the direction of readthedocs hosting our documentation wiki like in the link above.

There's some hesitation on a publicly modifiable wiki page. It also seems you have to pay for non personal usage. You may be able to provide some more insight into this, however.
