### ISSUE TITLE
Automatic ending of Rounds where It is impossible to call the shuttle

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2498]
# Description

Since I suspect that there will be a lot of Rounds where everything gets burnt to a crisp, There needs to be a case of handling this so everyone isn't stuck in limbo, 
These should get roughly triggered around
A everyone is dead 
B consul gets destroyed
C No one has the right access level to call the shuttle who is alive
Basically a way to prevent Limbo 
( other option is just a round Restart Vote)

**Comment by daalta** [comment]
A restart vote seems like the best option.

**Comment by chairbender** [comment]
2 questions:
1. What's to prevent a bunch of bored or vengeful ghosts doing a restart vote when there's still players alive?
2. How is this situation handled in tg?

**Comment by ghost** [comment]
tg code auto-calls a slow shuttle when the last comms console is destroyed

I'm looking for something straightforward to try as my first contribution, I'll try implementing that, if that's okay

edit: it also checks for a surviving AI; calls the shuttle when all comms consoles AND ais are dead

**Comment by chairbender** [comment]
Yep, go for it!

**Comment by ghost** [comment]
I'm having a shit time with VSC technical issues. I'm gonna keep trying but if someone else wants to step in and do this one I wont complain.

**Comment by Coolsurf6** [comment]
Yeah this would be neat, also sup mith

**Comment by ghost** [comment]
hey brew

**Comment by DooblyNoobly** [comment]
added restart voting in #2705
