### ISSUE TITLE
Visual indication for plasma B: 60

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2499]
# Description
In the byond version there is a purple haze , That appears when there is plasma Present in the atmosphere, the more percentage of plasma the thicker the haze is, This is very much needed to indicate for the player If there is plasma

**Comment by krille90** [comment]
Hey, are these are the right sprites?

![atmospherics_plasma](https://user-images.githubusercontent.com/7312905/73340450-06c1db80-427b-11ea-830e-1d508b8208b5.png)

You can find them in /Textures/effects/atmospherics/atmospherics_plasma.png

**Comment by DooblyNoobly** [comment]
yep thats the ones

**Comment by fomalsd** [comment]
yeah, though I only remember game when it used atmospherics_plasma_old

**Comment by DooblyNoobly** [comment]
After looking at the old one, I like the old one much better. Link to it is here: https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Textures/effects/atmospherics/atmospherics_plasma_old.png

**Comment by Misterixmax** [comment]
Ok, will work on it. Also wanna try to move fire effects from obj base to shader.
Upd: No, too hard for me with my ill eyes right now.

**Comment by fomalsd** [comment]
there's no "shader base", fire tiles are already just animated tiles and not objects.
there is an old unused code for object based fire here, but it's not referenced by anything:
https://github.com/unitystation/unitystation/blob/be2d443d04311ef14da7d279c7c58c1f1c0b635a/UnityProject/Assets/Scripts/Factories/EffectsFactory.cs#L41

**Comment by tmblessing** [comment]
Currently taking a crack at this
