### ISSUE TITLE
Tidy up

### ISSUE THREAD

**Issue by kaffo** [unitystation/unitystation#25]
Before we can put the "Done" stamp on the prototype, everything must be cleaned up so it's presentable to the public.

- [x] Scripts
- [x] Prefabs
- [x] Scenes
- [x] Managers
- [x] Plugins
- [x] Project Structure/Assets
- [x] AssetBundles and cut down of Resources folder (Please note Photon requirements)

**Comment by DooblyNoobly** [comment]
fyi anything that needs to be instantiated on the photon network needs to be in resources folders, so don't remove them

**Comment by kaffo** [comment]
Edited to make sure whoever reads this in the future doesn't mess up Photon :)

**Comment by DooblyNoobly** [comment]
no asset bundles for awhile yet, this is good enough for project closure
