### ISSUE TITLE
"Buckled" alert isn't cleared upon death / respawning / going ghost

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2503]
# Description
When you die while buckled, the buckled alert doesn't go away. When you respawn either via the cloner or the "respawn local player" command, it still doesn't go away and you can't click it to dismiss it. If you then go and buckle in, you'll see a second buckled icon showing up alongside the first.

Haven't tested it thoroughly but it might also have an impact on gameplay after you respawn - your character is still in a "buckled" state and you can't pick anything up despite being able to move around.

Expected behavior - after you respawn you should not be in a buckled state and you should not see the alert for it. As for how it works while you are currently dead, there's 2 options of varying difficulty:

1. When you die, you should only see alerts (like Buckled) when you occupy your corpse. The alerts should reflect the state of your corpse but should not be clickable (unlike how some of them are clickable when you are alive). When you are a ghost, not occupying your corpse, you should not see any alerts.
2. Don't show any alerts when you are dead or a ghost, regardless of if you are occupying your corpse.

2 is much easier, but 1 is ideal. Either is acceptable.

![image](https://user-images.githubusercontent.com/32009105/71566998-f2c36800-2a89-11ea-98d7-8853a50ddcef.png)

**Comment by Bod9001** [comment]
I was having issues with it showing the ghost UI And not showing the player UI
Could be related ?

**Comment by chairbender** [comment]
@Bod9001 what you mentioned specifically should now be fixed. But not clearing the buckled icon might not be fixed.

**Comment by chairbender** [comment]
decided this is a bit tricky, since also need to think about the case for when you rejoin while buckled, reentering body while dead corpse is buckled, etc...

**Comment by JesterX666** [comment]
Cloning also don't clear the buckled icon and ... You can't pick anything for the rest of the round.

**Comment by chairbender** [comment]
updated to make it more general / descriptive

**Comment by corp-0** [comment]
not an issue anymore.
