### ISSUE TITLE
Players can spam click with help, disarm and grab intents

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2515]
# Description
Help/disarm/grab intent clicks need a cooldown like with harm intent clicks (melee attacks).

Ideally all intents will share the same cooldown so you can't still spam clicks by changing intents really quickly.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Select help/grab/disarm intent
2. Spam click window
3. Notice it's really fast
4. Select harm intent
5. Spam click window again
6. Notice how there's a reasonable cooldown between clicks

**Comment by nikopetr** [comment]
Hey I can take this

**Comment by chairbender** [comment]
@nikopetr still on this?

**Comment by nikopetr** [comment]
I would love to do it myself but it's gonna take me some more days because of work.  Otherwise if it's an emergency you can have it!

**Comment by chairbender** [comment]
@nikopetr this is for 0.4 release and I've run out of other tickets to work on right now so I'm going to take this over if you haven't started yet

**Comment by nikopetr** [comment]
Yes mate
