### ISSUE TITLE
Wallmount text is broken

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2516]
# Description
Players shouldn't be able to see wallmount text from the wrong side of a wall:
![image](https://user-images.githubusercontent.com/4493127/71645930-4d9dcf00-2cd7-11ea-81fb-cebeb8d79122.png)

From the other side:
![image](https://user-images.githubusercontent.com/4493127/71645929-4aa2de80-2cd7-11ea-9f89-709f78e08b61.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Call the shuttle (F5 and then use `call-shuttle` command)
2. View a wallmount screen with text on it
3. Notice how you can see the text even when you can't see the screen anymore

**Comment by daalta** [comment]
I'll see if I can fix this.

If I can't I'll make it so the screen is always visible. This won't resolve the issue but the panel will look nicer for the time being.

**Comment by fomalsd** [comment]
it needs a shader for text that supports FoV, currently there is none

**Comment by daalta** [comment]
I'm also slightly confused by how the spriteRenderer is hidden. WallmountSpriteBehavior.cs sets the sprite renderer's visibility to 0 on OnWillRenderObject(). Not sure that's the best approach.

Edit: I guess I'll let someone else fix this 😉
