### ISSUE TITLE
Can't pick-up/combine stackable item

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2518]
You can't pick-up a stackable item when holding an item of the same type.

Please enter the steps to reproduce the bug or behaviour:
1. Spawn a metal plate
2. Pick-up the metal plate
3. Spawn a second metal plate
4. With the hand holding the first metal plate, try to pick-up the second metal plate.

**Comment by chairbender** [comment]
probably my doing

**Comment by chairbender** [comment]
@JesterX666 are you sure? It works fine for me. Make sure you spawn the same type of metal and not the debug "speedy metal"

**Comment by JesterX666** [comment]
It's weird, I can't reproduce it on my rig.  I had the bug on the Hub Server earlier.  Related maybe to something I did before?  Or is the hub server not on par with current code?

**Comment by chairbender** [comment]
okay, headless might've gotten into a broken state somehow so I'll mark this with needs reproduction for the time being

**Comment by DooblyNoobly** [comment]
I think bod fixed this just by saving the outpost station scene and committing it.
