### ISSUE TITLE
Applying bruise pack heals damage but doesn't update health icon.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2519]
Applying a bruise pack on character heals damage but doesn't update health icon.

![image](https://user-images.githubusercontent.com/32009105/71649369-2990bc80-2cdc-11ea-82b1-9c5ceb23ec0f.png)

Please enter the steps to reproduce the bug or behaviour:
1. Hurt yourself
2. Use medical scanner to see your damage (You can see the damage)
3. Use bruise kit to heal the damaged zone
4. Use medical scanner to see your damage (No more damage)
5. You health icon on the right still is yellow

**Comment by chairbender** [comment]
Might be a good first issue, probably on the harder side. This logic is handled in PlayerHealthUI, which is used in the PlayerHealth_UI_Hud.prefab. Each of the body parts in the damage indicator is assigned in editor to the body part listeners field.  Somehow the body part sprite is not being updated when healing occurs and is only being updated when damage occurs. 

This is supposed to be triggered when BodyPartBehaviour.UpdateSeverity is called - it calls PlayerHealthUI.SetBodyTypeOverlay. UpdateSeverity should be getting called when you take damage or heal.

**Comment by Bod9001** [comment]
Notice that the Health dole is swapped around left-to-right

**Comment by CykaGuy** [comment]
can't reproduce

**Comment by JesterX666** [comment]
Probably due to total server breaking on headless back then.

**Comment by DooblyNoobly** [comment]
can confirm, its broken for clients
