### ISSUE TITLE
Docker image for a dedicated server host

### ISSUE THREAD

**Issue by dargonforce** [unitystation/unitystation#2520]
# Description

A Docker image for hosting the server would be nice.  /tg/station provides one that sets up dream daemon.  Assuming the application can be run in a "headless" mode that would be pretty easy.

**Comment by jnms-me** [comment]
I'm new here but quite experienced in web backend. The /tg/station Dockerfile builds the server from source, then sets up the server environment.
I doubt we can build it in docker with Unity requiring a licence and going through the editor to press build.
If we had release builds being published or maybe even CI (don't know if we have this) this would be much easier.
Right now the best i can do is building the latest release/commit and creating instructions for doing so yourself (build for linux to build/ss13, run docker build).

**Comment by RedlineTriad** [comment]
@Reavershark we previously had Travix CI, and building Unity in docker isn't a problem.
If we add Docker images it would most likely be using Github Actions that build the project and then creates a Docker image with the build artifacts.
I don't think it is worth worrying about it yet though.

**Comment by Jibbajabbafic** [comment]
We used to have Travis setup but it became too much of a pain to maintain, and it used a Docker image of Unity (using https://gitlab.com/gableroux/unity3d) and an encrypted licence file (Unity_v2018.x.ulf.enc) to run.

Now that we have GitHub Actions available it could be worthwhile switching over to that as there's a collection of Unity related ones which can handle the licence file, building and testing: https://github.com/webbertakken/unity-actions

Old Travis setup if you want to check it out: https://travis-ci.com/Jibbajabbafic/unitystation

**Comment by jnms-me** [comment]
Made a working github action. Last run has a linux artifact [here](https://github.com/Reavershark/unitystation/commit/7ac4f17d0a2f1f7f517e33d762df34929e372001/checks?check_suite_id=383762469). The entire process takes 22 mins.

The license file is stored in a Github secret.
I tried to use https://github.com/webbertakken/unity-actions but the build process is kinda(very) broken so i rewrote that using the Travis scripts as an example. The license actions are great though and it's using that.

Still needs some work like removing unity-return-license as it's only for pro, adding test jobs, building for multiple platforms and figuring out how to make a headless build.

The issue should probably be renamed if i'm allowed to continue with this.

**Comment by RedlineTriad** [comment]
It may be possible to speed it up using the cache action: https://github.com/marketplace/actions/cache.
Also, it would be nice if your build actions took the version of Unity to use as a parameter.
Is using docker necessary btw? Why not do it directly in the runner?
Not meant in an accusatory way just wondering.

**Comment by dargonforce** [comment]
One benefit of using docker is that our build process isn't dependent on Github, and people can use it locally to automatically run tests, etc.

**Comment by RedlineTriad** [comment]
Pretty sure we left that benefit at the door when we started using Github Actions...

**Comment by jnms-me** [comment]
I'll definitely try to use the cache action then.
As `gableroux/unity3d` images exists for all unity versions and the image tags are simply the unity version ex. `2019.2.11f1`. But i don't think i can use docker `FROM ARG` with github actions. Multiple copy pasted actions would work though.
I'll probably make a build folder in this repo with the Dockerfile, entrypoint and action.yml.

If you don't want to use docker i believe you have to use node12. Then you'd have to extract files from a unity docker container you start in js and have an entire npm and jest setup including committing node_modules.

> One benefit of using docker is that our build process isn't dependent on Github, and people can use it locally to automatically run tests, etc.
Might be difficult to keep the same Dockerfile for Github Actions and local runs.

Also i ran both editmode and playmode tests from command line and put the results in a report viewer. There are only 4 tests though.
