### ISSUE TITLE
 Text Mesh Pro Classes aren't found by unity

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2531]
# Description
We have  Text Mesh Pro But no way of interacting with it through code, And with Unity's finicky scalingOddities with UI is very much needed

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Try referencing a Text Mesh Pro Classe 
2. Observe errors

**Comment by chairbender** [comment]
I had a branch a long time ago where I made it possible to reference TMP classes from code. Never merged it. It just requires adding / updating an asmdef somewhere

**Comment by chairbender** [comment]
https://github.com/unitystation/unitystation/commit/49cba14bca34b384b5f2d1e2929203e5f88df068

**Comment by Bod9001** [comment]
nice Thanks will PR

**Comment by daalta** [comment]
Still having issues with this, unfortunately :(

What's the proper way to import and use TMP?

Edit: Nevermind, found the mirror.
