### ISSUE TITLE
Some crate descriptions do not appear when hovering over them

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2535]
# Description

Hovering with the mouse cursor over certain crates does not display their object attribute description.

This seems to affect the crates in Resources/Prefabs/Objects/Crates (except crates_59). 

## Detailed Bug Report

Discovered this while going over item descriptions. I will update the issue if I notice any other crates that misbehave. Not all crates are affected, so I suspect there is an issue with a copy & pasted prefab.

## Steps to Reproduce
1. Hover your mouse over a radiation crate while playing the game. 
2. The object name is displayed in the lower-left of the screen ("radiation crate"), but the description is not shown ("A crate with a radiation sign on it.")

**Comment by StrawberryMoses** [comment]
I refactored crates not too long ago to inherit from a base prefab / each other- I'd start by looking at the base crate prefab

**Comment by daalta** [comment]
You're right @StrawberryMoses , I think. The various crates inherit from "Crate", and "Crate" inherits from "Object". I think the issue is that there's something wrong with "Object".

Lockers, for example, do not inherit from anything.

**Comment by StrawberryMoses** [comment]
I'll take a look at object then

(if I don't complete within the week feel free to take me off)

**Comment by daalta** [comment]
I've compared crate and locker, and they seemed very similar. It's also possible that I missed something. I'm sure that if we recreated crates the issue would disappear, but... ugh

**Comment by StrawberryMoses** [comment]
The thing is that all new object prefabs should inherit from Object to try and recreate the similar structure that tg has. If something is up with the base prefab then it'll affect much more down the line

**Comment by StrawberryMoses** [comment]
closing since merged
