### ISSUE TITLE
Fire destroys objects and items too quickly

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2536]
# Description
as compared to TG items on TG are a lot more resilient to fire than unity station
about 10 times I would say stronger

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.make plasma flood on TG, observe speed of damage to things
2.make similar flood on unity station , observe speed of damage to things

**Comment by daalta** [comment]
I'm currently working on object names and descriptions. I've already corrected the durabilities of some objects. Going over all objects will probably be a group effort.

**Comment by Bod9001** [comment]
I think it might be some code adjustments needed

**Comment by chairbender** [comment]
In addition to setting appropriate armor, probably the amount of base damage dealt by fire exposure is too high or it triggers a lot more often than it does in tg. I think I used the same value as in TG but I think our atmos ticks faster, thus causing more damage.

**Comment by chairbender** [comment]
marking as good first issue because this should only require tweaking Integrity, possibly even just changing the base damage dealt by fire exposure.

**Comment by Basipek** [comment]
Should it be adjusting the damage or the frequency? I'm thinking that adjusting the frequency would end up not very fluent or fair at times so halfing the damage seems crudely appropriate.
