### ISSUE TITLE
stacking interaction code broke on headless

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2539]
# Description
 when testing out the headless serverThe stacking Interaction was broken, the only way I found of making them stack properly was Placing one stack on the floor then dragging the other stack over it and That made them stack

## Steps to Reproduce
IDK If it's easily reproducible

**Comment by JesterX666** [comment]
Likely a duplicate of Can't pick-up/combine stackable item #2518

**Comment by Jibbajabbafic** [comment]
Fixed if #2518 is fixed already
