### ISSUE TITLE
Pixel Perfect Collision

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#254]
use case: Bullets should only hit something if it really hits a pixel of the object, and fly more further when it's not hit. This could be solved with Polygon colliders, which isn't pixel perfect.

These also have to be adjusted manually, but maybe there is a nice way to check pixels for collision.
e.g. https://timeshapers.com/2014/05/09/pixel-perfect-collision-in-unity-2d/

**Comment by DooblyNoobly** [comment]
already working off collider collision. Perfection not needed for awhile so closing for time being
