### ISSUE TITLE
Strange auth/body assignment issues

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2540]
# Description
Here’s what I encountered on build 3954:
 
Joined game for the first time using my main `foma` account, and was surprised to see that character wasn’t mine, instead it was a body of someone else called Chuck Howard, floating in space.
Asked Bod to come check and he joined alright.
Meanwhile I made a new account `foma2` and joined alright (second window) while keeping original window open. However I had a shit connection so both windows got disconnected soon. I closed the first game window and rejoined from the second one — I got into wrong Chuck Howard‘s body again (this time with a different account). 
Then I started another game instance from the same foma2 account and joined proper foma2’s body this time:
![4CC66C92-FD0F-4831-9FFE-1D837041E20C](https://user-images.githubusercontent.com/10403536/71780912-855b8e00-2fd9-11ea-95df-3a016eaa52e1.jpeg)

So the issues are:
— Being handed the wrong body
— Being able to join multiple times from the same account, simultaneously

**Comment by chairbender** [comment]
according to @DooblyNoobly he enabled being able to join with a different body temporarily for testing purposes, this still might be a bug somehow though

**Comment by fomalsd** [comment]
umm, did this fix actually address being handed the wrong body? that's the more important issue here than being able to join twice

**Comment by DooblyNoobly** [comment]
the weird body could of been a product of some issues earlier on with the firebase changeover where I messed up the storage of some users when they logged in. When was the last time you logged in with that account before logging in and experiencing the bug?

**Comment by fomalsd** [comment]
a couple weeks before logging in I guess.
But! I mentioned creating a brand new account 11 days ago and having assigned the same wrong body after re-joining

**Comment by DooblyNoobly** [comment]
alright reopen if it happens again. I'll see if I can repro again today

**Comment by DooblyNoobly** [comment]
Reopening. There is a problem with how JoinedViewer is checking for a logged off player on the server. It is checking if two NetworkConnections are equal but a logged off player will always have a null NetworkConnection because Mirror destroys them for logged off connections.

**Comment by DooblyNoobly** [comment]
Refactored the way PlayerList records connected players. This should be fixed now
