### ISSUE TITLE
Sound effects in world space lag behind shuttles

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2543]
# Description

Sound effects that are spawned in world space do not properly work on shuttles.

As the shuttle moves it quickly 'outruns' the sound effects, leading to the sounds not being audible

We could fix this by, for example, always attaching spawned sound effects to an object (such as the floor tile that was stepped on).

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Call the emergency shuttle, enter it and wait for it to start moving.
2. Footsteps are no longer audible.

**Comment by fomalsd** [comment]
we could pass a parent network entity id in PlaySoundMessage for such cases, but keep in mind that in the future players won't be getting position updates for other players they're not supposed to see (but can hear)

**Comment by corp-0** [comment]
I think this was fixed when we introduced the game object source to parameters of the method
