### ISSUE TITLE
Set text bubbles Default on

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2544]
# Description
I never Saw them until someone told me you could turn them on

**Comment by chairbender** [comment]
you just need to turn them in options

**Comment by daalta** [comment]
I agree with @chairbender that it's not a bug, but I also think they should be on by default. Maybe.

Though I feel like there are some kinks that could be worked out. There's some heavy aliasing going on, which I might take a look at.

Here's a picture after zooming out a bit.
![2020-01-06_23-52-57](https://user-images.githubusercontent.com/9169275/71854840-b1613700-30df-11ea-8fde-0b543cb3d78e.png)

(Edit: We could also call that a feature, hehe. Can't hear people who are far away, right? 😉)

**Comment by fomalsd** [comment]
it only starts looking good at 2x zoom. nothing will look good at 1.5x zoom (see #2269) and fonts are a bit too big to look good at 1x
same applies to status display text

**Comment by fomalsd** [comment]
<img width="99" alt="Scr 2020-01-07 в 1 59 48" src="https://user-images.githubusercontent.com/10403536/71855291-ae6f4200-30f1-11ea-9880-b40a2b31df22.png">
<img width="110" alt="Scr 2020-01-07 в 2 00 16" src="https://user-images.githubusercontent.com/10403536/71855298-b333f600-30f1-11ea-85d3-248537d0a715.png">
<img width="128" alt="Scr 2020-01-07 в 2 00 56" src="https://user-images.githubusercontent.com/10403536/71855306-ba5b0400-30f1-11ea-86b3-bb6c5db07078.png">

**Comment by daalta** [comment]
Well, we could fix that with texture filtering. We'd lose the pixel perfect look though!

Unfiltered:
![Unity_2020-01-07_00-06-57](https://user-images.githubusercontent.com/9169275/71855622-d656a980-30e1-11ea-8333-b8aaf48e0109.png)

Bilinear filter:
![2020-01-07_00-07-02](https://user-images.githubusercontent.com/9169275/71855623-d787d680-30e1-11ea-923c-cddd684322b4.png)

It's definitely an improvement I think. Honestly I'm not too attached to the pixel font anyway - I wouldn't mind replacing it with something more readable.

**Comment by StrawberryMoses** [comment]
Would this be changed with the other filtering issue anyway?

**Comment by daalta** [comment]
@StrawberryMoses I don't think the other issue mentions changing how text is rendered. Maybe I'm misunderstanding something.

Here's what chat bubbles could look like.

![Unity_2020-01-07_00-14-11](https://user-images.githubusercontent.com/9169275/71856103-2eda7680-30e3-11ea-8cd9-460d383910c1.png)
![2020-01-07_00-14-18](https://user-images.githubusercontent.com/9169275/71856105-300ba380-30e3-11ea-9316-b229787e80cd.png)
![2020-01-07_00-14-56](https://user-images.githubusercontent.com/9169275/71856108-313cd080-30e3-11ea-93d0-1dad3634bb7a.png)

**Comment by daalta** [comment]
Refer to https://github.com/unitystation/unitystation/pull/2561 for chat bubble improvements. After that we can re-evaluate turning on chat bubbles by default, improving them further or keeping them off.

**Comment by chairbender** [comment]
Now with the latest batch of improvements, I think we should default them on. Please vote using reactions (thumbs up = default on, thumbs down = default off)
