### ISSUE TITLE
Fire tile FX can get stuck

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2553]
## Description
It is possible to get situations where tiles appear on fire but then the fire effect never goes away. The tile doesn't damage you at all but the effect is still there. So far only noticed on our headless server as a client.

Might only happen with grenades?

**Comment by Macoron** [comment]
Yep, this bug was first described in rejected PM #2274. It only affects grenades that were in scene, spawned one works right.
I'll will soon make PM that fixes that, and other nasty bugs with grenades.

**Comment by Macoron** [comment]
PR #2562 have resolved this
