### ISSUE TITLE
Change hotspot code to update gas mix on the atmospheric thread

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2559]
## Description

Due to how it's coded, It removes gas from the tile then applies reaction to it
Then add it back, but in this small time zone where the gas is removed but not added back , The atmospheric thread can come from an update it to average it with the tiles around it, So resulting when it gets added back in , It being pretty high pressure In that one spot causing an atmospheric flick, luckily no gases are lost in this process, it's just erroneous pressure differences that are made

**Comment by Bod9001** [comment]
Make sure to note that the current atmospheric hotspot Calculations are meant for slower Updates

**Comment by Aranclanos** [comment]
the plasma fire reaction is now under the atmos thread
