### ISSUE TITLE
Shooting down a door doesn't make it passable for clients

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2564]
## Description
As per title. 
![i](https://user-images.githubusercontent.com/10403536/71998420-a548b700-3250-11ea-85c6-d9c494a66ecd.gif)
Serverplayer can go through the door alright.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Host in editor, join from build as a client
2. As a client, spawn a gun and shoot a door until it's destroyed
3. Try walking though it

**Comment by daalta** [comment]
Oh wow, that seems important. Wonder if that only happens when shooting it down.

**Comment by chairbender** [comment]
this is probably really easy to fix so I'll include it with my next PR

**Comment by chairbender** [comment]
lol I know the issue. Doors had both RegisterObject and RegisterDoor
