### ISSUE TITLE
Traitor steal objectives unclear and unreliable B: 40

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2565]
## Description

```
[Antags] Created new antag. Made Sydney J Zadovsky a Traitor with objectives:
1. Steal 1 
2. Steal 1 
3. Stay alive until the end!
```
what exactly are you supposed to steal?

EDIT: Additionally, the CheckCompletion method only checks the article name and doesn't work properly for stackables. The logic should check the prefab of the items they picked up, and in the case of stackables should check "StacksWith" and also respect the count of items in the stack when checking the count.

**Comment by chairbender** [comment]
These messages come from Steal.cs. The logic for generating the ItemName needs to handle cases where the ArticleName is empty. On some of our items, the article name is not filled in. A good alternative might be to use ExpensiveName(). It's an extension method which can be invoked on any GameObject.

**Comment by chairbender** [comment]
this is important to fix for 0.4 and really easy so I'll do it in current PR

**Comment by chairbender** [comment]
turning out to be not so easy, the checkcompletion method was relying on article name rather than a more robust approach. Making this a little more general...

**Comment by daalta** [comment]
Would it help to add missing item names?

**Comment by chairbender** [comment]
@daalta yes, if every item had a name filled in it would actually solve this without coding effort

**Comment by chairbender** [comment]
Adding a bounty of 40.

**Comment by chairbender** [comment]
I would even suggest, just going through and adding names to things and/or using a script to auto-populate them if they are empty (just use the prefab name), then adding failsafe logic so that an item won't be selected as a steal objective if it has no name. Using ExpensiveName() as suggested above MIGHT work instead, but obviously it would be best if we just entered in the content so we don't have anything with missing names, and my early experiments with ExpensiveName showed it can be inconsistent. Also using a prefab-checking approach can work, but keep in mind we have some prefabs that are just stacks of different amounts, so they will need to use the Stackable.StacksWith logic to check if they are the same.

**Comment by Jibbajabbafic** [comment]
FYI there are only 4 possible items to steal which can be found in Steal.asset, so if you fix their names and make check completion work with the new stackable system then it should be pretty easy to fix

**Comment by Emma3DSS** [comment]
Ill do it now then unless its already claimed

**Comment by fomalsd** [comment]
Keep in mind that fixing just these 4 names isn't a future proof solution, it'll break again if someone decides to change stealable item list

**Comment by Jibbajabbafic** [comment]
Properly adding names to all items should be a separate issue and will be a much bigger task than this

**Comment by JesterX666** [comment]
Do we have a Component that can indicate if the item is "stealable" or not?  Can an item register itself in a list of stealable item at server start?

**Comment by Jibbajabbafic** [comment]
You just add items to the item pool in Steal.asset (it's a scriptable object)

**Comment by chairbender** [comment]
I would say it's at least "future proof" if you 
1. Name the items that are currently in pool.
2. Add a validation when picking from the items that are in the pool to not select items that have no name as a failsafe.

We should not have unnamed items at all, eventually. In fact, quite a few items have been named as the result of lots of recent content PRs.

**Comment by fomalsd** [comment]
Logging an error and skipping item if it doesn't have a name is sufficient future-proofing in my opinion

**Comment by Emma3DSS** [comment]
I dont really care about the bounty so if someone else who has more free time would rather go for it

**Comment by DooblyNoobly** [comment]
Will fix this one up today

**Comment by DooblyNoobly** [comment]
Hmm all of the items loaded in the Steal Asset had their names filled out. So it can't be that
