### ISSUE TITLE
Grenade doesn't destroy after explosion in closet

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2566]
# Grenade doesn't destroy after explosion in closet

## Description
After explosion grenade doesn't destroy itself in closed closet. After you open a closet door, grenade is ready to be used again, like nothing happen. If the player will close himself with an activated grenade, he won't receive any damage.

### Detailed Bug Report
![closetGrenade](https://user-images.githubusercontent.com/6161335/72016358-b0154300-3274-11ea-9c40-83cad01259a3.gif)

### Steps to Reproduce
1. Activate grenade
2. Throw it in any closet and close the door  
3. After explosion open door again
4. The grenade won't be destroyed and you can use it again

**Comment by NoooneyDude** [comment]
It seems the grenade is despawning now, and the grenade damages its surroundings (except for the locker and its contents). So I think this issue should be closed in favour of #4690.
