### ISSUE TITLE
Players current have no way to whisper

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2568]
## Description

Players can currently not whisper to quietly talk to nearby players.

Whispering should allow players to only be heard if listeners are a single tile away. 

*Chat bubbles should already support whispering once it is implemented, as only received chat messages spawn chat bubbles. Chat bubbles (soon) support player whispering, which is initiated by startin a message with a "#".*

**Comment by daalta** [comment]
Note: Our fullscreen is currently a borderless window ("fullscreen window"). However, switching to exclusive fullscreen has the same issue described above.

**Comment by JesterX666** [comment]
@daalta can you explain how it's related to the fullscreen/borderless window with a screenshot please?  (How it behave in each mode?)

**Comment by daalta** [comment]
@JesterX666 wrong issue, whoops! moving / deleting the comment.

**Comment by daalta** [comment]
On my fork the chat modifier for whispering can now be manually triggered. Once that's merged we can introduce a distance check depending on the chat modifier. This will also be useful for yelling.

**Comment by NoooneyDude** [comment]
Whispers are now possible with `/w [message]`. However, distance is not taken into account and so this issue should be closed in favour of #4405.
