### ISSUE TITLE
Chat Bubbles Offset on Rotated Matrix

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2569]
Get on a shuttle and turn once. Turn on chat bubbles. Say something. See that the chat bubble is a bit off from where it should be. In the below picture it's too far to the right of my player.

![image](https://user-images.githubusercontent.com/1329062/72042151-6facc980-3262-11ea-8b4b-5e72cf7dc592.png)

Additionally, there's a TODO comment in PlayerChatBubble.Update saying the euler angle stuff can be removed.  This logic actually ensures that chat bubbles stay upright when on a rotating matrix so it actually is necessary, so this comment should be removed.

**Comment by daalta** [comment]
I'll check it out later, feel free to assign me.

We might be able to solve this by changing the bubble's pivot, actually. Then we can take the rotation code out of Update.

**Comment by daalta** [comment]
Fixed it by changing the pivot and the position in the player prefab. Will include the fix in my next PR.
https://i.imgur.com/Xoe5NAS.mp4

**Comment by fomalsd** [comment]
still the case as of build 3982
![unknown-13](https://user-images.githubusercontent.com/10403536/73126589-b1a96f80-3fc5-11ea-9948-f92550bcc4a2.png)

**Comment by daalta** [comment]
You're right, thanks for bringing this up.

The chat bubbles containing text still work, just tested it. I've created a new issue.

**Comment by daalta** [comment]
Fixed in https://github.com/unitystation/unitystation/pull/2739

**Comment by daalta** [comment]
Has since been merged.
