### ISSUE TITLE
Fullscreen resolution uses windowed resolution

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2575]
## Description

When switching from windowed to fullscreen (using ALT + ENTER) the windowed resolution will be used (instead of using the highest possible screen resolution).

Windowed:
![unitystation_2020-01-10_21-48-38](https://user-images.githubusercontent.com/9169275/72185383-f7294280-33f2-11ea-9bf8-8caee1266daa.png)

Fullscreen:
![2020-01-10_21-48-56](https://user-images.githubusercontent.com/9169275/72185486-2d66c200-33f3-11ea-9c7a-c2042a469abb.png)

Take note of the Radeon Software prompt, which is overlayed in perfect resolution.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Start the game in windowed mode. 
2.  (Optional) Resize the window to a small size. This will make the issue more obvious.
3.  Enter fullscreen by holding the ALT + ENTER keys.
4.  The screen resolution will be too low and blurry.

**Comment by daalta** [comment]
Working on making a quick fix. Trying to figure out why ESC exits fullscreen.

**Comment by daalta** [comment]
Reason fullscreen got closed: ResponsiveUI.cs, lines 89 to 91
```
			if(KeyboardInputManager.IsEscapePressed()){
				Screen.fullScreen = false;
			}
```

Don't understand why that's there, maybe someone can help me understand 😉

**Comment by Jibbajabbafic** [comment]
I think that's leftover from before when the game always used to be fullscreen by default. Can probably be removed for now. In future we can add fullscreen options to the options menu

**Comment by daalta** [comment]
That explains it, thanks.

#2601 is going to let users enter fullscreen without running into this issue.

**Comment by Jibbajabbafic** [comment]
Sweet!

**Comment by daalta** [comment]
#2601 is now in the game. If we disable ALT+ENTER fullscreen (or fix it) this issue can be closed.

**Comment by CodeKalias** [comment]
Working on this to solve alt-enter issues
