### ISSUE TITLE
Holding the middle mouse button in-game continuously produces sounds

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2576]
## Description

*(Feel free to tag this as non-intrusive and low priority)*

Pressing the middle mouse button while in-game produces a sound (even when the game is muted in the Unity editor).

If a player drags the mouse while holding the middle mouse button, every frame the sound is played from the beginning.

### Steps to Reproduce
Only tested in the editor:

1.  Enter a game
2.  Hold the middle mouse button
3.  Drag your mouse across the screen

**Comment by chairbender** [comment]
I honestly thought this was intended as a fun easter egg.

**Comment by Jibbajabbafic** [comment]
I think the problem is a lot of people use middle mouse to switch hands so it's gonna get annoying real fast for those people
