### ISSUE TITLE
Add the option to toggle 'far select' and 'shift assist' to radial menu. Add option to toggle classic and radial menu

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2584]
# TODO:

- Develop classic right click menu
- Develop far select and shift assist for radial menu
- Add some customization toggles to the options menu to allow the far select and shift assist features for the radial menu
- Add an option toggle to switch between the radial menu and the classic menu list for right click menu

Assigning this to myself.

**Comment by CdrCross** [comment]
I heavily recommend that instead of a choice between classic and radial, you frame it as "Drop-down" vs. "Radial". We want people to judge their options based on what they fancy, not what they know from BYOND.

**Comment by NoooneyDude** [comment]
Related to #2047.

**Comment by PerfectTangent** [comment]
This functioned as a personal TODO for Doobly, and doesn't reflect the changes incorporated in the new radial menu. I'm closing and opening a new issue for the classic drop down menu.
