### ISSUE TITLE
Usable Sprite Animation System - Simple Inventory Icons B: 30

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2592]
Sub-task of #2311
Refer to that ticket for guidance / overview of the plan for the sprite animation system.

Expand on #2590 to support simple inventory icons (how an object looks in an inventory slot). The requirements are simple - the object's inventory icon should reflect whatever the object's current animation is. So, its appearance in inventory should match how it would appear if it was in the world.

This only needs to support simple (single sprite) icons. Composite icons will be done in #2593 .

Following criteria need to be met:

- [ ] Objects in inventory should have the same appearance as if they were in the world, based on what animation is currently playing.
- [ ] The design should be flexible so it can support future use cases.
- [ ] A few objects should be migrated to use this new system to prove it out.
- [ ] Dev team agrees that it meets our needs as far as usability is concerned. Expect some feedback and iteration.

You don't need to completely migrate everything to this new system, it can be set up to coexist alongside the old system so it can be migrated in a piecemeal fashion.

Refer to the suggestions in #2311 for guidance on the design / implementation.

**Comment by chairbender** [comment]
Adding a bounty of 30.

**Comment by Bod9001** [comment]
return to pool
