### ISSUE TITLE
Usable Sprite Animation System - Composite Inventory Icons B: 80

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2593]
Sub-task of #2311
Refer to that ticket for guidance / overview of the plan for the sprite animation system.

Expand on #2591 / #2592  to support composite inventory icons (how an item looks in an inventory slot). Just like simple inventory icons, whatever animations are playing on the object should also play when the object is in inventory.

This will require modifying how the Panel_Hud_Bottom.prefab works, as currently it only supports 2 sprites for inventory items. It needs to support multiple sprites.

Following criteria need to be met:

- [ ] Objects with composite icons in inventory should have the same appearance as if they were in the world, based on what animation is currently playing.
- [ ] The design should be flexible so it can support future use cases.
- [ ] A few objects should be migrated to use this new system to prove it out.
- [ ] Dev team agrees that it meets our needs as far as usability is concerned. Expect some feedback and iteration.

You don't need to completely migrate everything to this new system, it can be set up to coexist alongside the old system so it can be migrated in a piecemeal fashion.

Refer to the suggestions in #2311 for guidance on the design / implementation.

**Comment by chairbender** [comment]
Setting a bounty of 80.

**Comment by Bod9001** [comment]
return to pool
