### ISSUE TITLE
Usable Sprite Animation System - Full Migration B: 30

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2597]
Sub-task of #2311
Refer to that ticket for guidance / overview of the plan for the sprite animation system.

Once all of the pieces of the animation system are in place, migrate everything over to it from the old SpriteHandler / SpriteDataHandler system.

**Comment by chairbender** [comment]
Setting a bounty of 30

**Comment by Bod9001** [comment]
am, going to close this the only thing left to do is in hands
