### ISSUE TITLE
New player announcement is played when you leave your dead body

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2598]
## Description
As per title:
![img](https://user-images.githubusercontent.com/10403536/72244433-2b188980-35e6-11ea-9c6a-dcda0d098b1f.png)
That TTS welcome announcement is legacy code which never worked well with more than one player and should be disabled until we come up with a local TTS solution

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Host from editor, spawn
2.  Die
3.  Fly out of your dead body

**Comment by JesterX666** [comment]
In AnnounceNewPlayer, check for newPlayer.PlayerScript.IsGhost

**Comment by fomalsd** [comment]
Just remove the announcement code – TTS implementation is quite unrobust
Also it looks like that RequestSyncMessage aren't really needed anymore either – data gets synced to client in `JoinedViewer.ServerSetUpPlayer()` anyway
