### ISSUE TITLE
Plasma generator generates power regardless of where it's anchored

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2600]
You can unwrench the plasma generator, take it anywhere, wrench it, and start it up. It provides power to the station regardless of where it's wrenched.

I believe the intended behavior would be that it needs to be in a special place / on top of a wire in order to provide electricity to the station. Someone with more electricity system knowledge can fill this in more.

**Comment by fomalsd** [comment]
that thing above seems to only happen on round start, further wrenching fixes its behaviour
Old discord discussion:
https://discordapp.com/channels/273774715741667329/409351620220944386/652850911546179584
