### ISSUE TITLE
Variable viewer has white text on white background

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2603]
## Description
Variable viewer has white text on white background

why?
Because the text mesh pro asset it's using is the same as the Other fields in the game and someone set them to be white

**Comment by NoooneyDude** [comment]
I don't think this is an issue any more?

![vv](https://user-images.githubusercontent.com/6926225/88247973-b42a1f00-ccf3-11ea-97fa-33ce1f68fa78.png)

**Comment by PerfectTangent** [comment]
I agree with Noooney, this is no longer an issue.
