### ISSUE TITLE
Player teleportation after step on shuttle

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2604]
# Player teleportation after step on shuttle

## Description
Met this bug playing on remote server (AUS). It was late round, I stepped on a shuttle and was  immediately teleported to different location. From supposed cord in (78, 71), my player got to (82, 133). Player wasn't able to move. Dropped items also showed weird behavior (see video).

I will investigate more and try reproduce it.

### Detailed Bug Report
![unknown](https://user-images.githubusercontent.com/6161335/72456591-0256e680-37d6-11ea-9057-b37ea168f31b.png)

Dropped items behavior:
![ezgif-3-ad1f9d6fb703](https://user-images.githubusercontent.com/6161335/72456547-e8b59f00-37d5-11ea-9d97-b180d82ba240.gif)

**Comment by chairbender** [comment]
huh, looks like all the items are in the right place but the shuttle itself isn't, like you never got the message for moving the actual shuttle into position

**Comment by Macoron** [comment]
Still a thing and no idea what cause it or how to reproduce
![image](https://user-images.githubusercontent.com/6161335/74466360-16126d00-4ea8-11ea-8c2f-aa4814bb1b21.png)

**Comment by Macoron** [comment]
Restarting the client teleport you back to the proper location. This bug is really annoying and can ruin game for many players. 
There are also reports that late join nuke ops can be left behind their ship like that.

**Comment by chairbender** [comment]
i'm getting this locally now, it can even happen on roundstart if you spawn on a docked shuttle

**Comment by pyrosshade** [comment]
Similiar issues exist on staging, however this issue as seen in the provided media doesn't happen anymore, and i'd wager this is outdated.

**Comment by corp-0** [comment]
this isn't a issue anymore or hasn't happened in years.
