### ISSUE TITLE
Directional lose orientation sync if player not on rotation matrix

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2605]
## Description
There seems to be an error in directional sync. If player not on rotation matrix, directional syncs incorrectly.

### Detailed Bug Report
![image](https://user-images.githubusercontent.com/6161335/72469495-92a22500-37f0-11ea-8f9c-2a68011e5a62.png)

### Steps to Reproduce
1. As Player 1 go to mining shuttle
2. Rotate shuttle to the right
3. As Player 2 look at the shuttle
4. All rotations are messed up
5. As Player 2 go to mining shuttle
6. Now if Player 1 rotates shuttle it all works correctly

**Comment by Jibbajabbafic** [comment]
Got any screenshots to show how it looks when the bug happens?

**Comment by Macoron** [comment]
Attached to issue description. It not always reproduces though.

**Comment by pyrosshade** [comment]
Is this still a thing?

**Comment by ThatDan123** [comment]
Closing as this in an old issue and the rotational stuff was redone a bit ago.
