### ISSUE TITLE
Aliens are flying around space

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2619]
## Description
Is this intentional?

![J96Hfxgtrw](https://user-images.githubusercontent.com/4493127/72569514-8a122300-38b2-11ea-9ee3-4ba12acf9421.gif)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Start game
2.  Open scene tab
3.  ???
4. See aliens flying around!?

**Comment by DooblyNoobly** [comment]
looks like they escape the asteroids and run off. I've made it so they can move in space to attack shuttles. I'll see if there is a way to persuade them to go back

**Comment by DooblyNoobly** [comment]
Nevermind, found the problem. Those xenos are on outpoststation matrix for some reason

**Comment by DooblyNoobly** [comment]
scrap that, looks like outpoststation is the space matrix. Ok they are just walking off the side of the asteroid and going for a fly. I'll put some checks in to stop that

**Comment by DooblyNoobly** [comment]
alright they attempt to avoid edges now but when they are in areas like the screenshot below they get confused backing away from edges and end up falling off. So there may be a xeno in space but the number of space xeno's has been greatly reduced. I think its good to have the possibility of a xeno making it to the main station anyway.

![image](https://user-images.githubusercontent.com/20813925/72573915-f45ab000-3912-11ea-8768-a0770f1a35ef.png)

**Comment by Bod9001** [comment]
I thought that's where you found aliens  : P

**Comment by DooblyNoobly** [comment]
ok this bug has alerted me to a lot of other small unnoticeable bugs to do with matrix rotations. The xenos are checking their tiles as if the matrix was rotated in the default orientation so everything is out. Even the direction sprites. Will need to incorporate the rotation offset into the MobAI itself

**Comment by DooblyNoobly** [comment]
I fixed the rotation bugs and some of the xenos can still escape into space. But it has added an element of surprise when a xeno just starts tapping on the window to cargo or launches at a shuttle mid flight. Which I think adds to gameplay. So going to close now
