### ISSUE TITLE
Lockers aren't spawning their contents

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#2620]
## Description
Most of the lockers have their contents defined but they aren't spawning for some reason.

![image](https://user-images.githubusercontent.com/4493127/72570276-64861900-38b4-11ea-8e53-67150b6f4cfd.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Open some default lockers (e.g. oxygen or janitor ones)
2.  See nothing inside
3.  :(

**Comment by Bod9001** [comment]
Might be the issue that chair Bender mentioned, Since it seems to be fine for me

**Comment by Bod9001** [comment]
![image](https://user-images.githubusercontent.com/27101670/72574016-833ddd00-38bf-11ea-9d1a-30e297b1284e.png)

**Comment by chairbender** [comment]
Click through that field and see if there's missing prefab references

**Comment by DooblyNoobly** [comment]
working fine for me on latest develop: 
![image](https://user-images.githubusercontent.com/20813925/72575245-78af3200-3917-11ea-9c04-13837f181e5a.png)

**Comment by chairbender** [comment]
Oh and also check for exceptions during startup

**Comment by chairbender** [comment]
works fine for me too. Jibby, you might want to try the workarounds in #2551

**Comment by Jibbajabbafic** [comment]
Ok yeah it's probably that then
