### ISSUE TITLE
atmospherics has a tendency to break on headless server

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2628]
# Issue Template
it doesn't update at all, probably the best way to see if it's doing it is to look at the logs and save the station pets are suffocating to death
  

1.  idk try headless server maybe
2.  
3.

**Comment by fomalsd** [comment]
https://github.com/unitystation/unitystation/issues/1670

**Comment by Bod9001** [comment]
yeah, went on to the German server if you want to test it

**Comment by RedlineTriad** [comment]
Seems to be pretty stable now.
