### ISSUE TITLE
shuttles have no reverse gear

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2629]
## Description

it makes it incredibly hard to park them, it's just a quality-of-life thing

**Comment by chairbender** [comment]
YES PLEASE! Even if they don't have thrusters on the front maybe just a really slow reverse mode would be nice. Shuttles already do have the possibility to move in a different direction than they are facing (it's used for auto-parking escape shuttle).

**Comment by Bod9001** [comment]
Remember you have to change the magnitude of speed to an absolute for the plasma consuming Calculations

**Comment by NoooneyDude** [comment]
I think this should be be closed in favour of #3070 or #3889.
