### ISSUE TITLE
APC UI isn't changing states properly

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2630]
## Description

APC battery left Bar doesn't scale at all with percentage,
 it also doesn't change colour when it is charging for the wall Sprite

![image](https://user-images.githubusercontent.com/27101670/72614096-4c041600-3929-11ea-9bdd-dbff30b2a009.png)

![image](https://user-images.githubusercontent.com/27101670/72614294-cd5ba880-3929-11ea-98c1-4a866d60ef14.png)

**Comment by Jibbajabbafic** [comment]
Yeah I left the APC tab in a bit of a mess. Since we updated the sprites the UI doesn't even match it so I think it could do with an overhaul

**Comment by Bod9001** [comment]
yeah, Keep the old status overlay sprites, Since new ones I think look a bit bad (That thing that goes inside the frame Sprite Wise)

**Comment by ThatDan123** [comment]
Pretty sure this has been fixed.
