### ISSUE TITLE
Shuttles Don't Repressurize (Fix AirVent / Scrubbers?)

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2639]
## Description

Some (all?) shuttles don't repressurize after opening the doors into space and letting them depressurize. For example, command escape shuttle has this problem. I think all shuttles should recover their atmosphere after venting.

Maybe this is just as simple as mapping in an AirVent and Scrubber to each shuttle?

EDIT: For this issue it's fine to just fix it so that they repressurize as long as atmos is working. You don't need to fix the issue where atmos dies.

**Comment by chairbender** [comment]
Excuse my indulgence, but I'm putting this into 0.4 because it makes shuttles annoying to use if you have to always wear a hardsuit.

**Comment by fomalsd** [comment]
fyi neither AirVent nor Scrubber work at the moment

**Comment by Bod9001** [comment]
Maybe you could bring a canister with you as a Stand in?

**Comment by chairbender** [comment]
Ah, so maybe fixing airvent / scrubbers would be a good solution, and mapping them in

**Comment by JesterX666** [comment]
On a server for which the atmos system is working (not stopped), the pressure is getting back.  However when I examined the gas mix, it was my plasma canister leaking even if it was secured to the fuel connector.  Not sure it's supposed to leak like that when secured.

Also, the fuel connector flew right in my face when I reopenned the door and lost pressure again.  Fuel connectors are not supposed to move from the floor arn't they?

**Comment by chairbender** [comment]
Ah ok. So this is probably just #2628 

I believe canister shouldn't leak unless you actually open it. It's not required to open the valve when connecting it to the fuel port. When piping stuff is more thought out we need to revisit how this works.

**Comment by chairbender** [comment]
@JesterX666 I'm talking about when the shuttle is away from the station...I'm not seeing it repressurizing in those circumstances. Even when atmos is working fine. I tested this on mining shuttle btw, not sure if we are talking about the same thing.

EDIT: And there's nothing to my knowledge that would cause it to repressurize unless you map in a scrubber / air vent

**Comment by chairbender** [comment]
TODO: I also need to ensure shuttle connector is anchored and not pullable / able to be blown around

**Comment by JesterX666** [comment]
@chairbender It was just an observation that my shuttle was getting repressurized but it was caused by plasma leaking.  (Which imo is another bug, that I will log on my lunch break with video proof).  Plasma pressure isn't good since it's toxic :p

If O2 and N2 air mix would be injected, it would repressurize the shuttle.
