### ISSUE TITLE
Enter key when writing a memo open the chat window

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2640]
While writing a memo, using the enter key should do a carriage return but instead open the chat window.

Reproduction:
1.  Get a sheet of paper in one hand
2.  Get a pen in the other hand
3.  Write on the sheet of paper
4.  Use the enter key to do a carriage return.
5.  You enter the "Say" mode (chat window).

**Comment by Mantle-Wanderer** [comment]
Probably related to #2347, that one is on the security records console.
