### ISSUE TITLE
Security officer spawn without clothes.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2641]
I connected to the German server as a security officer.
I spawned without my clothes.
Still had my backpack though.

Happened Jan. 18 at approx 00:20 GMT - 5 (might have some info in the log files for missing prefabs and such)

Steps to Reproduce
1.  Connect as a security officer

**Comment by fomalsd** [comment]
can confirm, probably just messed up equipment loadouts.
need someone to look through all of them and fix the mismatches
<img width="398" alt="Scr 2020-01-18 в 13 55 39" src="https://user-images.githubusercontent.com/10403536/72662625-44f90880-39fa-11ea-9842-261c8d84f471.png">
