### ISSUE TITLE
After the atmospheric update, space wind is really buggy

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2644]
With fires it seems to push you around randomly and push items across the station for no reason, I think this is due to the fact that it's changing from 1000 kpa to 900Kpa that would be a massive change compared to 101Kpa but it's nothing to the Atmospheric system at that pressure, so Maybe have it as a proportion of gas changed?

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Set fire
2.  Run around and fire
3.   observe Strange wind forces

**Comment by chairbender** [comment]
Ha, I guess I'm not crazy. I've been noticing recently that sometimes when I open the door out of an airlock without waiting for door behind me to close, I get sent screaming out into space, but sometimes I don't get pushed at all. Even when starting from apparently the same initial conditions.

**Comment by PerfectTangent** [comment]
this appears to have been dealt with by #5142
