### ISSUE TITLE
Re-logging breaks player sprites for all equipment.

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2647]
# Issue Template

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  join headless 
2.  put on mask and tank
3.  take it off
4. relog, and put it on again and see the problem

**Comment by JesterX666** [comment]
Doesn't seem to break the oxygen toggle UI anymore but I'm gonna fix this :

![Gas mask](https://user-images.githubusercontent.com/32009105/73612847-845c5300-45bd-11ea-8aa0-90cbea32eb01.gif)

**Comment by JesterX666** [comment]
In fact, the problem is reproductible with ANY clothing item.

1. Log on a headless server
2. Remove your suit
3. Drop it on the ground
4. Log out
5. Log back on
6. You have 1 suit on the ground, 1 suit on your hand and appear fully clothed!

**Comment by JesterX666** [comment]
The clothing was not even removed from clothingitem equipment.  It was merely hidden.  Making it reappear when re-logging.
