### ISSUE TITLE
Monkey Cubes

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2655]

**Comment by fomalsd** [comment]
I think lockers are currently designed to only store items and players, and not mobs
and you normally can't get into a crate since they're always solid (but likely can get out)

**Comment by pyrosshade** [comment]
Lockers and their derivatives can in fact contain animals. In fact when you contain an animal in a locker, each attempt at movement they attempt to escape. They cannot escape if locked or welded however.

**Comment by MaxIsJoe** [comment]
has this been fufflied with #9924 ? @Bod9001

**Comment by AtnerNT** [comment]
We got monkey cubes now
