### ISSUE TITLE
Antags aren't being notified of their antag status

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2659]
## Description

Only seen on headless so far after some round restarts and possibly server-breaking errors.

When we started a new round and everyone joined in, nobody saw a message saying they were an antag. But after calling the antag-status admin command, one of us was marked as an antag and it told us our objectives.

Marking high priority because...it's kind of important to know if you're an antag.

**Comment by chairbender** [comment]
0.4 because it's essential for gameplay

**Comment by chairbender** [comment]
not currently able to reproduce, will test on headless after latest build

**Comment by DooblyNoobly** [comment]
could be related to all of these ghost ConnectedPlayer entries that I managed to clean up recently. Will close this and reopen if it reoccurs
