### ISSUE TITLE
Fire Resist Action B:20

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2660]
## Description

Currently when on fire there's no way to resist it. Add a way so you can resist and remove fire stacks by dropping and rolling or however it works on tg.

**Comment by Bod9001** [comment]
Doesn't need the animation, Just need to have cool down if you're doing it yourself  added to the resist button to do it yourself, And if you do Help intent on someone who is on fire you put them out as well, It's quicker than doing it yourself

**Comment by daalta** [comment]
Yep, a fire resist button is needed.

... Though I can think of another way to remove fires from a player?
How about players being able to pat fires, either on themselves or on other people.

~~We might even be able to wrangle it into the hug code we already have.~~
```
if (lhb != null && lhbOther != null && (lhb.FireStacks > 0 || lhbOther.FireStacks > 0))
{
    lhb.ApplyDamage(huggedPlayer, 1, AttackType.Fire, DamageType.Burn);
    lhbOther.ApplyDamage(gameObject, 1, AttackType.Fire, DamageType.Burn);
    Chat.AddCombatMsgToChat(gameObject, $"You give {hugged} a fiery hug.", $"{hugger} has given {hugged} a fiery hug.");
}
```
~~Lines 543-548 of PlayerNetworkActions.cs already checks if the player is on fire. By doing the reverse we could remove fire stacks.~~
EDIT: ...Aaaaand @Bod9001  did a quicker writeup than me 😁

**Comment by daalta** [comment]
I'm investigating the option I just mentioned. I'll leave resisting fires via the resist button to someone else.
So another person can feel free to assign themselves to this issue! 🎉🎉🎉

**Comment by daalta** [comment]
The PR above introduces **FIRE PATTING**! Pat yourself, pat yourself and watch those flames **disappear**.

Though it's not fire resisting. Dropping and rolling might be (should be?) easier and more effective than patting out yourself. Buuuuut now other players can help you.

**Comment by daalta** [comment]
https://github.com/unitystation/unitystation/pull/2830 has been closed (for now), so this feature still needs to be implemented. I'd need some more PR feedback before reopening it.
