### ISSUE TITLE
Microwave Doesn't Spawn Meal

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2661]
## Description

On headless, we went to the microwave in the lobby and tried cooking some meat. It played the animation but when it was done, it didn't spawn the cooked meal.

**Comment by daalta** [comment]
Huh, odd. Inserting meat into the microwave yields the 'The microwave is empty' interact prompt. Normally this shows the remaining time.

**Comment by daalta** [comment]
Yeah tried this myself in the editor (with 2 clients), it really is a headless-only issue. Bummer, wouldn't really know how to investigate this.

I made the most recent microwave changes, but I don't think I touched anything network-related.

**Comment by chairbender** [comment]
@daalta it is possible to run a server in headless mode locally by enabling GameData.TestServer. However, some of these headless issues might be caused by other things happening on our headless server which only happen after a bit of gameplay / round restarts, such as breaking atmos / UpdateManager.

**Comment by daalta** [comment]
@chairbender Thanks! Good to hear that it might not be the fault of whoever worked on microwaves! Wink wink

**Comment by DooblyNoobly** [comment]
still doesn't work on stable headless

**Comment by daalta** [comment]
~~https://github.com/unitystation/unitystation/pull/2732 supposedly fixed this, but... I think microwaves are still broken on headless?~~

Nevermind! It's a graphical issue with the sprite not resetting. @JesterX666 fixed the issue nicely though, my bad 👍

![Unitystation_2020-01-26_00-43-21](https://user-images.githubusercontent.com/9169275/73128810-51222e80-3fd5-11ea-8cfa-a36f25b67cd8.png)

**Comment by JesterX666** [comment]
The now don't turn off.  Repairing.
