### ISSUE TITLE
Status display message is visible through walls

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2665]
## Description
You can see text on status display through walls. Looks like frustum or sprite sorting problem. 

### Detailed Bug Report
![image](https://user-images.githubusercontent.com/6161335/72680868-c1115000-3acf-11ea-9274-780534527aae.png)

### Steps to Reproduce
1.  Set display message on captain console
2.  Go to the kitchen part of the outpost station

**Comment by JesterX666** [comment]
Duplicate of #2516 
Maybe we should keep only one of the two issue?
