### ISSUE TITLE
Missing user experience feedback while server is starting.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2666]
Clicking "Apply" in the character settings while the server is still starting gives no output.  (And changes the song).

Reproduction
1.  Restart the server or wait for the server to restart.
2.  On the character settings screen, click apply.
3.  The character screen closes and re-open and the song changes.

Suggestions for corrections:

- Get a message "Server isn't available" or something.
- Stay on the same song.

**Comment by corp-0** [comment]
is this still relevant? I think we have error messages now.

**Comment by JesterX666** [comment]
Will look if it's still an issue after work.

**Comment by JesterX666** [comment]
It is fixed.  You can stay in the character settings screen as long as you want even if the server restart.
