### ISSUE TITLE
Applying plates to girder sometimes get interrupted

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2667]
In multi-players, applying metal plates to wall girders is often stopped for no visible reasons.

1.  Play on a server with a lot of players.
2.  Try to apply plates to a wall girder
3.  Sometimes it gets interrupted

My opinion is that the client receive a network message that stops this action.

**Comment by JesterX666** [comment]
Related to #2656 (Possibly the same issue)

**Comment by chairbender** [comment]
this should be fixed due to my pr for #2656
