### ISSUE TITLE
Text Bubbles are hidden in darkness

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#2668]
# Description
As the title says, speech bubbles, at the very least in dark bubble mode, are hidden if you're in darkness, as such giving the effect of hearing impairment because you're in the dark.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Set your text bubbles to dark mode
2.  Go to an area of complete darkness or go unconscious.
3.  Speak, your text bubble is now truncated by the darkness.

**Comment by daalta** [comment]
I've been previously told that this can (will?) be fixed by applying a different shader to text bubbles. But I'm glad @JesterX666 's taking care of it!

**Comment by JesterX666** [comment]
@daalta I know absolutely nothing about shaders and materials.  If you want to take it, go ahead.

**Comment by fomalsd** [comment]
I'm not sure it's a good idea to give out exact position of the speaker in complete darkness

**Comment by daalta** [comment]
@fomalsd That's correct. Giving out the speaker's location is bad, I think we should make that a separate issue.

If a player stands below a dark room we cannot read their chat bubble. And on the flipside, if a player is in complete darkness but stands below a bright room, we can read their chat bubbles.

The brightness of the chat bubble should not depend on the size of the chat bubble, but on its location. So this is definitely a bug.

Easiest way to fix this (for now) is making chat bubbles always visible. Chat will see some other changes in the future, such as being able to hear a player, but not see them. So we will have to change how chat bubbles work to make those cases work.

**Comment by daalta** [comment]
By the way, the chat icon (the one with three dots) is also affected. Might fix this along with #2735

**Comment by corp-0** [comment]
this was fixed when we changed bubbles from being part of player gameobject to their own thing.
