### ISSUE TITLE
hub builds shouldn't have hardcoded IP addresses

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2671]
They should also be allowed to host their own servers as well, So if the main server break for whatever reason you can host your own and let people connect

**Comment by RedlineTriad** [comment]
This is not a hub specific thing, all clients from the build server work this way, steam client also.

**Comment by DooblyNoobly** [comment]
```
So if the main server break for whatever reason you can host your own and let people connect
``` 
you can already, you just need a hub account which I generate for you after vetting the fork or the users intentions. Also IP addresses are not hard coded they are updated by the servers themselves

**Comment by Bod9001** [comment]
I mean as in, Friend hosting a server And you connect to it

**Comment by Jibbajabbafic** [comment]
I agree with bod, I think the option of connecting to a custom ip and port, and self hosting would be useful for messing around with your friends on a private server. The server doesn't need to appear on the hub, we just need to be able to launch an already installed fork and build and use the regular lobby screen that we already have.
