### ISSUE TITLE
A way to run the editor and builds in off-line mode so you can test multiplayer features

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2672]
Without having to make separate logins for each client

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Host gaming editor
2.  Try joining with the client 
3. Observe being kicked

**Comment by Bod9001** [comment]
I need this to fix cloning

**Comment by Bod9001** [comment]
![image](https://user-images.githubusercontent.com/27101670/72689163-7c54db80-3b06-11ea-82b6-fb67d0bdfeeb.png)

**Comment by chairbender** [comment]
This should be already fixed. Enable GameData.OfflineMode before building the client. Keep it on as well when starting in editor.

**Comment by Bod9001** [comment]
how you do that?

**Comment by chairbender** [comment]
Enable GameData.OfflineMode.

Open GameData.prefab. Enable OfflineMode.

**Comment by Bod9001** [comment]
oh ok, make sure to tell doobly about it

**Comment by chairbender** [comment]
Another way to do it is, just create a second account. That's what I do. It's trivial to make a new gmail.

**Comment by Bod9001** [comment]
it works, make sure to have it as part of the contributing/testing guide   thanks chairbender
