### ISSUE TITLE
Eating sounds do not follow player

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#2674]
## Description
When you pick up and eat something, the munching sound will play wherever you started eating, if you start to move away from that position, you'll hear the sound continue from the direction you were in previously.

### Detailed Bug Report
Noticed when on headless, picking up the nearby donut and eating it

expected behavior is the sound should move with the player.

### Steps to Reproduce

1.  pick up and eat something
2.  start moving in any direction
3.   notice that sound is coming from the direction you were in previously

**Comment by daalta** [comment]
Related: https://github.com/unitystation/unitystation/issues/2543

**Comment by corp-0** [comment]
this was fixed when Doobly added a ``source`` argument to the play sound methods.
