### ISSUE TITLE
Ghosts / cloned players can be cuffed 

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2692]
# Issue Template

https://cdn.discordapp.com/attachments/667287667121061908/669220894153113610/unknown.png

When you die when you're cuffed you still are cuffed when you are a ghost

EDIT: And if you are respawned using the cloner after being cuffed, you still appear in the UI as cuffed and attempting to uncuff doesn't work.

**Comment by chairbender** [comment]
Added info about cloned players being cuffed as well
