### ISSUE TITLE
Tactical handgun sprite is half invisible when on floor.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2695]
![image](https://user-images.githubusercontent.com/32009105/72859235-15176280-3c91-11ea-9759-7e93633a29b6.png)

**Comment by NoooneyDude** [comment]
I think this gun no longer exists or has been renamed as I couldn't find it in the dev spawner. Regardless, I don't think this issue occurs with any of the other guns so the issue could probably be closed.
