### ISSUE TITLE
Trying to reconnect after a round ends, bugs out future connections (Lobby Limbo)

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2697]
I haven't seen a issue describing this posted here, this is a placeholder until more information is acquired. 

After a round ends there is a chance that you will be unable to reconnect. Whether this only applies to dead people is unknown. Logging off and back in does not work, exiting and reopening Unitystation does not work. Switching servers to GER, that server works fine. Going back, the issue persists. After switching back to AUS, I was kicked, the error message saying I was already logged in. 
More information will be posted when I am able to join back into the server again.

The game logs in, then to character creation. From here two things can happen: It will log in again or you will be placed into a limbo state where you are kind of in the game, but cannot hear anything like OOC or talk. Players will not be shown to connected, even if there are players, this is what that screen looks like:
![Lobby limbo](https://user-images.githubusercontent.com/60084963/72861305-6e2ad900-3d19-11ea-943a-dd1bd31180fa.png)

**Comment by mudzbe** [comment]
I was able to reenter the game, this was after a server reset.

**Comment by NoooneyDude** [comment]
I have seen this recently happen. Might be related to issues #4254 and #4255.

**Comment by pyrosshade** [comment]
Is this still happening?
