### ISSUE TITLE
Lobby Limbo - auto-reconnecting when existing character menu

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2698]
## Description
Thanks to Robotonic on Discord for reporting this!

Happens in release build only.

When you logout, then hit exit on the character menu, it connects you back again automatically. Instead it should exit.

**Comment by DooblyNoobly** [comment]
removing from 0.4 project. I looked at this today and didn't deem it important enough for the release. Will sort it out soon after.
