### ISSUE TITLE
Vents have the option to be pulled when they cannot be

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2699]
Right clicking on vents or scrubbers or the tile they are on gives the option for vents to be pulled. Trying to do this however will not move the vent.

Expected Behaviour: The option to pull the vent should not be there.

![image](https://user-images.githubusercontent.com/60084963/72862020-9287b500-3d1b-11ea-9bf8-43ef7919bfcf.png)

**Comment by NoooneyDude** [comment]
Although these vents don't exist anymore, #4671 fixes this by not showing the pull option on ObjectBehaviours that can't be pushed.
