### ISSUE TITLE
Plants spawned on asteroids have the "oops" description

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2711]
## Description
As client, go out to asteroid and look for a plant. Examine it and see the "Oops, someone spawned something they shouldn't" examine text.

Expected behavior - see the correct examine text for that plant.

![](https://cdn.discordapp.com/attachments/667287667121061908/669764218290962432/unknown.png)

This probably has to do with how plants are set up to use a generic Food.prefab and then populate it with plant data. If all plants were just prefab variants this wouldn't be an issue, but that's probably too much effort for this ticket. Most likely the new examine text (in ItemAttributesV2) is not being synced or updated when the plant data is populated.

**Comment by PerfectTangent** [comment]
is this still an issue?

**Comment by PerfectTangent** [comment]
Closing for now. Can be reopened if it's found to still be a problem.
