### ISSUE TITLE
Revise loadouts for each job

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2713]
– HOP wears a Detective's coat and vice versa
– Clown has a grey backpack and no horn or peels
– Janitor spawns with engineering tools in his belt
...who knows what else?
Need someone to look through each job loadout and make them match /tg/-2017 or bee

**Comment by fomalsd** [comment]
I'd love to see this addressed before release

**Comment by smugmann** [comment]
i might do it

**Comment by DooblyNoobly** [comment]
pretty much done
