### ISSUE TITLE
Rods no longer build lattices

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2714]
As per the title, holding plenty of rods in your hand and clicking a space tile off the side of the station does not lay a girder. 

Reproducible in build 3980

**Comment by fomalsd** [comment]
did you mean lattice or catwalk?
![img](https://user-images.githubusercontent.com/10403536/72986391-fbd0fc00-3ddf-11ea-8ab5-4b82c9767bec.png)
girders (for walls) are only built with metal sheets

**Comment by JesterX666** [comment]
Catwalk do work.  It's the Lattice that is broken
