### ISSUE TITLE
Able to punch and destroy electrical machine connectors through the floortiles

### ISSUE THREAD

**Issue by Mantle-Wanderer** [unitystation/unitystation#2715]
# Issue Template

### Detailed Bug Report
It's possible to hit the electrical machine connectors that connect the power cables with the machines themselves through the floortiles, without needing to pry them off of the ground first.

![VIR MediumMachine character - Able to punch it](https://user-images.githubusercontent.com/12883734/73020955-8b959b00-3e1e-11ea-9551-c1205a2f34ae.png)

It's also possible to smash it to pieces and permanently disable power.

![VIR MediumMachine character - Able to punch it #2](https://user-images.githubusercontent.com/12883734/73021015-a536e280-3e1e-11ea-8572-3d81fa847c1c.png)

This doesn't affect power cables, just the connectors. It seems to affect all of them regardless of the voltage level of the connector.

![Unitystation -- Electrical Machine Connector #1](https://user-images.githubusercontent.com/12883734/73022470-8f76ec80-3e21-11ea-9f08-26defae9181e.gif)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Set harm intent.
2.  Click near the centre of a tile next to an SMES or department battery. Example location included in the screenshot.
3.  You will start punching or bashing the electrical connector, and it's possible to destroy it this way.

### Note:
The easy solution is to make them unpunchable until the floortiles are pried off, but it might be best to make them unpunchable at all like the power cables already are since we can't rebuild them right now.

**Comment by chairbender** [comment]
those probably shouldn't even be hittable as there's no way to rebuild them I think
