### ISSUE TITLE
Security Console does not reset records on new round

### ISSUE THREAD

**Issue by RealPlanet** [unitystation/unitystation#2716]
The security console, currently, hold records for old crew members from different rounds, multiple entries have the same name / different jobs, or even multiple captains. It seems to never erase.

**Comment by Mantle-Wanderer** [comment]
![Unitystation -- Security Records Persistence #1](https://user-images.githubusercontent.com/12883734/73023823-352b5b00-3e24-11ea-96eb-a681643ffd47.gif)

You can also see previous versions of me in the records list, such as Eric Penton (Captain). I (assume) I can set my alternate dimension doppelganger to arrest, as The Law knows no bounds or limits of time and space.
