### ISSUE TITLE
Holding an item doesn't allow you to switch to the respective hand with the mouse cursor.

### ISSUE THREAD

**Issue by RealPlanet** [unitystation/unitystation#2724]
If you are holding an item the only option is to use the keybind to switch hands, you cannot simply click on the ui hand to switch to it.

**Comment by JesterX666** [comment]
Was not reproduced

**Comment by RealPlanet** [comment]
> Was not reproduced

If you have an empty hand and you click to switch on a hand that holds an item, the item will switch hands if you have both hands full nothing will happen. In both cases it's not behaving as expected.

**Comment by PerfectTangent** [comment]
Could not reproduce, and changes to the hand UI has made it easier to switch hands, because you can click the rim of the hand slots. Closing.
