### ISSUE TITLE
Office chairs are bullet proof??

### ISSUE THREAD

**Issue by MNarath1** [unitystation/unitystation#2726]
If you try to fire your weapong while you are on top of an office chair (same tile) then the bullets won't spawn in and if you try to shoot a target with an office chair in the line of fire the office chair will block the bullet.
Edit:Small change it turns out that you can still damage (windows/lockers) that are directly next to your tile(if you are on the same tile as the office chair).

**Comment by daalta** [comment]
Hmmm, weird. After testing this it only seems to happen with office chairs. Stools and metal chairs work fine, so this is probably a bug.

EDIT: Only difference between the prefabs I could find: Office chair's don't have "is trigger" in their box collider checked. Trying it out now.

**Comment by daalta** [comment]
Maybe this is related to #2586 (being able to strap people to office chairs and rolling them around). 

After checking "is trigger" the chairs become breakable again, but they still block the occupant's bullets.

Maybe I'm missing something obvious? Couldn't find a way to fix this.

**Comment by krille90** [comment]
additionally to setting IsTrigger=true, the layer of the office_chair needs to be set to "Unshootable Machines", as the bullets ignore collision with objects with that layer. See PR #2769

**Comment by daalta** [comment]
Thanks @krille90 , glad you figured it out!
