### ISSUE TITLE
Chat breaks on death B: 30

### ISSUE THREAD

**Issue by MNarath1** [unitystation/unitystation#2728]
If you die at least by using the shuttle and crashing into the station or when you die by igniting gasses and getting flung into a wall then OOC and Ghost chat stop working you won't be able to write anything in there except for blank messages had to vote restart to fix it.
Suicide command works too.
Edit:Small change ok if you get revived somehow it seems that you can write normal again at least that worked with only a death trough beeing stabbed also for some reason OOC broke already before i saw myself death i was in crit but still barly alive for some reason that already seems to have been enough for my chat messages to be only blank. Also after Server restart during the time until the next round is ready and if you have still not choosen your job you also are unable to write in OOC

**Comment by daalta** [comment]
Might be able to fix this!
