### ISSUE TITLE
As a clown you honk even in OOC

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2736]
## Description
As a clown you make HONK! HONK! every message in OOC. 
Well, I kinda like it actually...

### Detailed Bug Report
![image](https://user-images.githubusercontent.com/6161335/73126948-41e9b380-3fca-11ea-9aad-a71bd554f7c0.png)

### Steps to Reproduce
1.  Be a clown
2.  Say something stupid in OOC
3.  HONK!

**Comment by daalta** [comment]
Uh. Heh! That was me.

https://github.com/unitystation/unitystation/pull/2708

I moved the HONKs from the chat log into the actual message. This ensures that they show up in the chat bubbles, but I guess I forgot to check for death & ooc.

I'll... uh... I know how do fix it, but maybe I'll leave this for now... 😉

**Comment by daalta** [comment]
Fixed on my branch. Due to be merged.
