### ISSUE TITLE
Server messages going to dead cloned players 

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2749]
## Description
@DooblyNoobly might know more, just reporting this from issues channel.

Dead players who have been cloned are still being sent server messages. I assume this means the server messages are going to the corpse?

I could be wrong but I suspect this is causing the issue where sometimes dead players can't be stripped, their inventory shows up empty. This seems to happen when relogging, dying, and getting revived (then try to examine your old corpse I guess?)

**Comment by DooblyNoobly** [comment]
the code has to specifically target the player object that no longer has a player controller on the server for the error to occur. I just added some connectId and NetworkConnection null checks to ForceDir change

**Comment by DooblyNoobly** [comment]
![image](https://user-images.githubusercontent.com/20813925/73132631-71033200-4069-11ea-862d-e603b7a8547b.png)
