### ISSUE TITLE
Fires no longer start and atmos wind push players through walls

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2755]
You can no longer start a fire in build 3984. Also when there are canisters venting gases at max pressure in a hallway or room you can move through walls.

Gif of the move through wall bug (there were 3 canisters up the hall venting at 1000kpi):

![atmoswindbug](https://user-images.githubusercontent.com/20813925/73146856-49ab7400-4100-11ea-98f8-0509cb62a54c.gif)

**Comment by DooblyNoobly** [comment]
@fomalsd any ideas what could be happening?

**Comment by fomalsd** [comment]
no idea, walking through walls is certainly not related to my PR as it was reported a day before #2731 was merged

**Comment by DooblyNoobly** [comment]
roger, removed the related to comments

**Comment by DooblyNoobly** [comment]
not reproducible on build 3985 closing

**Comment by fomalsd** [comment]
Might have had something to do with introduction of air scrubbers/vents, so it's harder to make fires now
