### ISSUE TITLE
Crates in sec amory appear closed and open

### ISSUE THREAD

**Issue by MNarath1** [unitystation/unitystation#2764]
![Anmerkung 2020-01-27 150848](https://user-images.githubusercontent.com/47279840/73181325-4b346680-4117-11ea-9d58-abbfb529861f.jpg)

This seems to only occure when the red emergency light is on (so with no power on the station) and only for the Security crates that are empty i tried to bring other crates into the same room but they are not affected by it.
I encircled the different crates
Blue:Empty Sec Crates(the crates are actually open)
Brown: full closed Sec Crates(If you open them it affects the blue Circled Crates some suddenly appear normally open but not always all of them)
Green: Crate from engineering(unaffected)

**Comment by fomalsd** [comment]
likely caused by #2833

**Comment by fomalsd** [comment]
I think this can be closed unless it appears again. Duplicate crates have been removed form armoury
