### ISSUE TITLE
Atmos Values dont show in percentage

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#2770]
### Detailed Bug Report
When using the at Atmos Analyser, the values aren't shown in percentage, but as a value between 0 and 1. Easy fix is to multiply these values by 100.

![image](https://user-images.githubusercontent.com/7312905/73245686-17a41b80-41ad-11ea-9dd4-3cb251959eb4.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Take Atmos Analyser
2.  Click Atmos Analyser
3.  Wonder, why the values don't sum to 100, but 1.

**Comment by Bod9001** [comment]
but Mathematical percentages is so useful : P 
Simple fix, Also isn't it 50% Instead of %50?

**Comment by chairbender** [comment]
Adding some info from a related ticket from @mudzbe

When the atmospheric scanner is used in a normal room inside the station:
1. Percentages do not add up to 100%
2. Showed percentages seem to be 100x less than what would be normal in a average room except for carbon dioxide which seems to be ok.
3. Too many decimal points on every reading - 2 or 3 would be fine

![image](https://user-images.githubusercontent.com/60084963/73602398-78738f80-45c3-11ea-8ecb-7472a3cda479.png)
