### ISSUE TITLE
Ghosts don't always spawn over their dead bodies

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2780]
For some reason you can end up spawning at your spawn point instead of the dead body point as a ghost. This is annoying as a nuke ops as you are spawned in the middle of no where. 

We need to a solution to ensure it always spawns over the dead body

**Comment by Mantle-Wanderer** [comment]
I think this usually happens when your body was gibbed, since I've mostly seen it whenever I crash a shuttle into the station and get turned into a fine mist.

**Comment by fomalsd** [comment]
yep, when your body is gibbed you start following a meat slab that's left of you, but when it's gone ghost only spawns at your last body's position (I think)

**Comment by JesterX666** [comment]
It's curious, I can't reproduce it anymore.  My body is no longer vaporized when I crash into the station.

It is possible that I merged some code that prevents it from happening.
