### ISSUE TITLE
Meat can no longer be microwaved

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2784]
## Description

Meat was recently https://github.com/unitystation/unitystation/commit/dbaf9bfa0b8918c14c4912be41080ea30dde7175 changed to a prefab variant. The microwave can no longer cook it because the recipe has not been adjusted.

The recipe has to be changed to allow the microwaving of meat again.

Has only been tested on GER.

**Comment by DooblyNoobly** [comment]
high priority. Eating raw meat is bad
