### ISSUE TITLE
Loading screen - Game does not indicate loading and freezes instead

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2787]
## Description

Joining a server from the menu or the hub freezes the game for several seconds. This is problematic because:

* Players have no indication that loading has started (except music continuing to play in the background).
* Hub users are shown a grey, blank screen.
* Joining an IP from the menu freezes the menu.
* Menu music immediately starts playing for hub users, even before the game has rendered a single frame. Music can not be disabled until loading is finished. (The main menu has a mute button which hub users will not get to see)

The game also freezes / loads on round restarts or when exiting a round.

## Proposed solution

A simple loading screen would solve the issue. It should indicate that Unitystation is loading. A loading progress bar would be a nice addition, but is not necessary.

Hub users should either get the option of disabling music before joining, or music should be muted if the main menu is never seen.

**Comment by Bod9001** [comment]
When adding loading screen remember to add  the classic spinning thing, we Were thinking underscored stuff like, running jobs, random Antagonists, Random important items, Anything cool you can think of

**Comment by daalta** [comment]
https://github.com/unitystation/unitystation/pull/2820 should fix this issue, by the way. Though a spinner would be nice.

**Comment by DooblyNoobly** [comment]
no spinner until we tackle the awake initializations from all of the managers in the lobby. Will close this as there is a minimum solution in place in the mean time. I'll make a job for the start up optimization after release.
