### ISSUE TITLE
AirVents and Scrubbers aren't anchored on headless

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2790]
People mention that none of AirVents and Scrubbers are anchored on our test servers.
Exact steps to reproduce are unknown (for me), please share if you know something about it

**Comment by daalta** [comment]
Maybe this is related? https://github.com/unitystation/unitystation/issues/2699

**Comment by fomalsd** [comment]
Nope, not related
Bloodsplats also show "Pull" right click item but that's not relevant

**Comment by JesterX666** [comment]
This one is usually easy to reproduce.  Filling the mining shuttle with plasma, augmenting the pressure and then opening the shuttle door to create a vaccuum.

![Not hooked](https://user-images.githubusercontent.com/32009105/73505066-6a452980-439f-11ea-88c2-1320f6dc2375.gif)

**Comment by JesterX666** [comment]
Air vents, scrubber and fuel connector... They all flew around :p

**Comment by chairbender** [comment]
you can also just try picking them up to see if they are anchored. Unanchored ones can be picked up.

Doobly mentioned this seems to be caused by an issue where headless doesn't finish initializing properly

**Comment by fomalsd** [comment]
Looks like it's fixed, will reopen if it occurs again
