### ISSUE TITLE
 UprightSprites. OnDisable() is really slow when starting scene in editor

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2799]
# Issue Template
https://cdn.discordapp.com/attachments/312454684021620736/672894965109620764/unknown.png

UprightSprites. OnDisable()
 is really slow and unity destroys the scene before loading thegame when you press play so it really adds to the start time it does, 

	public void Remove(Action updatable)
	{
		UpdateAction -= updatable;
	}
apparently UpdateAction -=  it is really slow
it is suggested to use WeakEventManager   instead
https://stackoverflow.com/questions/24238897/unsubscribing-from-events-performance-hit 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. press play a few times 
2. open profile
3. profile editor one starting  
4.  observe large time sink of UprightSprites. OnDisable()

**Comment by Scorr** [comment]
Should be fixed by #3155
Lemme know if it still happens if this gets merged

**Comment by NoooneyDude** [comment]
I see that `UpdateManager.Remove()` has been refactored and so no longer uses `UpdateAction -= updatable;`. I think this issue could be closed.
