### ISSUE TITLE
Pipe Dispenser

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2808]
## Description
For #2805 . Depends on #2806 

Create a pipe dispenser object. This should be a simple UI that allows dispensing the various kinds of pipes. Might even be able to use the existing vendor or other vending-type objects to implement this logic, except I think it should be infinite?

Map this into atmos in the station.

**Comment by NoooneyDude** [comment]
This was completed by #4524. This issue can be closed.
