### ISSUE TITLE
Pipenets + Gas Canister Connector Distribution

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2809]
## Description
For #2805 . Depends on #2806 .

Implement the logic for how gas propagates through pipes via Gas Canister Connectors.

Requirements:
- [x] Pipenets - have a system in place so that it's possible to know how wrenched pipes / connectors are connected to each other.
- [ ] Pipes should be able to connect between the floor and base layers - the pipes connect based on their adjacent openings only, their layer doesn't affect what they are connected to.
- [x] Ability to hook multiple gas canister connectors with canisters on them to a pipe network.
- [x] Gases should propagate through the pipes - it should be possible to transfer gases between 2 canisters via a pipe or passively vent the gases out through the open end of a pipe (even if the open end is beneath a floor tile).

**Comment by corp-0** [comment]
closing since piping work is done and this issue referes to an old task that is not relevant anymore.
