### ISSUE TITLE
Atmospheric Scanner Displayed Percentages Are Wonky

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2814]
When the atmospheric scanner is used in a normal room inside the station:
1. Percentages do not add up to 100%
2. Showed percentages seem to be 100x less than what would be normal in a average room except for carbon dioxide which seems to be ok.
3. Too many decimal points on every reading - 2 or 3 would be fine

![image](https://user-images.githubusercontent.com/60084963/73602398-78738f80-45c3-11ea-8ecb-7472a3cda479.png)

**Comment by chairbender** [comment]
Thanks, I'll add this to related issue  #2770
