### ISSUE TITLE
Coloured Wire Displays White

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2816]
When examining wire teal and red wire it displays as white wire. Orange displays as orange wire. The teal and red wires have different sprites to the orange wire which is thicker. This likely has something to do with it. No other wires have been tested.

![image](https://user-images.githubusercontent.com/60084963/73602551-e751e800-45c5-11ea-8bb4-28b525d8340a.png)

**Comment by chairbender** [comment]
yep, those little preview image thingies look weird on quite a few items

**Comment by corp-0** [comment]
this doesn't seem to happen anymore, closing
