### ISSUE TITLE
Welders do not automatically turn off after splashing their liquid.

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2828]
Welders behave strangely after spilling the contents on oneself. ~~They cannot be re-enabled after spilling them and turning them off.~~ They remain on, even though the liquid is missing.

### Steps to Reproduce

1. Pick up a welder
2. Press Z to turn it on. (Welder frame in icon turns on)
3. Switch your intent to "Harm".
4. Click on yourself, which will spill liquid on you. (Welder flame in icon stays on)
5. Turn off the welder. (Welder flame turns off and cannot be re-enabled at all)

Dropping the welder instead of turning it off will set the player on fire.

I have not tested this in multiplayer, but I expect the issue to occur regardless of who the liquid was spilled on.

**Comment by fomalsd** [comment]
Have you tried filling it with fuel first? It's not supposed to turn on if there's no fuel

**Comment by daalta** [comment]
@fomalsd The issue occured when using one of the welders that are present on the station at the start of the round. I assume they are already fueled, but you're right - if they aren't then they should turn on.

**Comment by fomalsd** [comment]
I mean, if you spill its contents it’ll become empty, so it’s quite logical that they refuse to turn on afterwards

**Comment by daalta** [comment]
Yes, I suppose I could reword the issue:
Welders remain turned on even after spilling their liquid.
