### ISSUE TITLE
You can close opened locker below another closed locker

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2835]
![image](https://user-images.githubusercontent.com/32009105/73614849-f68a6300-45d0-11ea-87b9-a8938e0c514c.png)

Steps to reproduce

1.  Open a locker
2.  Push or pull another locker on top of it
3. Click opened locker to close it

– you have two closed lockers on the same tile

**Comment by ThatDan123** [comment]
Pretty sure you can do that on normal ss13 code, whether it needs to change though is a different argument.

**Comment by fomalsd** [comment]
@JesterX666 rephrased the issue since what you originally described wan't a bug

**Comment by pyrosshade** [comment]
Fixed by #7767

**Comment by jamessimo** [comment]
I think this can be closed
