### ISSUE TITLE
When player stab someone with a knife, knife is placed in a victim pocket

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2836]
##  Description
Second hit by a knife in a chest places knife in a victim pocket. Happens only on a client, host works correctly. 

### Detailed Bug Report
https://youtu.be/7B7B3DRxfY0

**Comment by Macoron** [comment]
Damn. It works with ANY melee weapon. So I guess it's a high priority

**Comment by JesterX666** [comment]
Ok, was able to reproduce it.  With the 4th hit, while on "HELP" intent.  Doesn't seem to be reproductible in "HARM" intent.
