### ISSUE TITLE
Sliding glass doors don't block player on syndie shuttle

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2837]
## Detailed Bug Report
Doors can be activated manually, but doesn't block player.
Station glass doors works okay.

![lighting](https://user-images.githubusercontent.com/6161335/73615424-cb2b6680-4618-11ea-984f-6d389fc2b0e1.gif)

**Comment by chairbender** [comment]
Yeah, the IsPassable logic for these needs to be modified to respect their Directional facing.

**Comment by ThatDan123** [comment]
Has been fixed.
