### ISSUE TITLE
Don't allow selling of players

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2839]
## Description

Currently it's possible to sell players if they are on the cargo shuttle when it reaches the station. This causes them to basically die. It might also cause additional problems since it's an unusual way to despawn a player.

Make it so players aren't sellable. At the very least just skip them over when selling items on the shuttle and just leave them there. It should be as easy as modifying the cargo selling logic to check if it's a player and skip it.

Make sure players inside of lockers are also not sold. Just bump them out of the locker prior to selling the locker itself.

**Comment by Mantle-Wanderer** [comment]
I just found this whilst searching for a different cargo bug:
https://github.com/unitystation/unitystation/issues/2427

**Comment by chairbender** [comment]
ah thanks @Robotonic I'll close this as duplicate
