### ISSUE TITLE
Framerate is always unlocked

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2840]
![2020-02-02_22-58-06](https://user-images.githubusercontent.com/9169275/73616108-7e8f5d80-460f-11ea-93a1-10ffb1316dc9.png)

## Description

The game's framerate is always unlocked, going above the display's maximum refresh rate.

This makes the computers of users go *WRRRRRR*, even in very simple scenes such as the character creation menu.

Thanks to ThatDaniel for reporting the issue.

## Suggested fix

* Automatically cap the refresh rate to the monitor's maximum refresh rate

or

* Add a refresh rate option to the options menu (This could be done along with https://github.com/unitystation/unitystation/issues/2575)

https://github.com/unitystation/unitystation/issues/2704 is also related to this issue.

**Comment by DooblyNoobly** [comment]
Added a target frame rate option:

![image](https://user-images.githubusercontent.com/20813925/73628201-4e8d9c00-469b-11ea-8b05-544e96e396ea.png)
