### ISSUE TITLE
ClothingItem causes client side NRE when joining while player is holding a uniform

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2849]
## Description

Host in editor, start the game and spawn. Unequip your suit and hold it in a hand.

Now join as client. Observe a clientside NRE in ClothingItem.SetReference due to GameObjectReference being null.

**Comment by chairbender** [comment]
got other higher priorities to work on

**Comment by NoooneyDude** [comment]
I couldn't reproduce this issue. Seems fine now.
