### ISSUE TITLE
Cargo pooling issues

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2854]
## Description

Use dev spawner to spawn a bunch of empty crates on cargo shuttle. 
Place an order and send it back to centcomm. You should be properly credited.
Send it back to station.

Take the crates off the shuttle, take the stuff out, then push the crates back onto the shuttle. Leave them open.
Place another order and send it to centcomm.
Note that it credits you incorrectly for lots of crates, more than you returned.

Then return the shuttle to station. Note that the crates appear open and your orders don't show up in them until you close and reopen them.

Probably it's related to the dev spawner spawned crates still being seen as existing on the cargo shuttle despite being already sold and despawned. Either the crates are not despawning properly or the logic for checking if crates are on the shuttle is wrong. 

Also due to closets not having reliable pool-safe behavior.

**Comment by chairbender** [comment]
made more general as I noticed other pooling issues

**Comment by fomalsd** [comment]
related comments in https://github.com/unitystation/unitystation/issues/2400
