### ISSUE TITLE
Typing suicide command into console makes you invincible

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2859]
as per the title:

![image](https://user-images.githubusercontent.com/20813925/73632106-9665f080-46a6-11ea-8f3d-108ae4f1e97f.png)

**Comment by DooblyNoobly** [comment]
I made a new Server Gib method on player health. Maybe it just needs to be adjusted to use that

**Comment by chairbender** [comment]
yep. There was an old suicide method that doesn't follow the proper logic. Calling the same logic as right click Smash should do.

**Comment by DooblyNoobly** [comment]
I added a new method actually that calls the correct logic. Check it out
