### ISSUE TITLE
Guns spawn hot gas that in a normal room will likely kill you

### ISSUE THREAD

**Issue by mudzbe** [unitystation/unitystation#2860]
Guns when shot spawn a tile of hot gas on the tile next to you depending on where you are shooting. Shooting north will spawn it north of you, shooting south will spawn it south of you.

When shot in a room with normal atmos you will likely be set on fire and slipped around the room probably due to the high pressure difference. Shooting in vacuums still spawn the gas but wont kill you *most* of the time.

**Comment by mudzbe** [comment]
Issue seems to be fixed, flaming gas is no longer spawned

**Comment by fomalsd** [comment]
I don't think guns ever spawned gas, but they certainly produce hotspots. You must've been in a plasma filled room
