### ISSUE TITLE
Refactor DNAscanner

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2870]
## Description
DNAscanner component is a bit of a mess. In particular I'd like to remove the need for ClosetStatus.ClosedWithOccupant and the bespoke logic in ClosetHandler that's added just to support DNA scanner. Remove that enum value and move occupancy / non-occupancy status to a bool syncvar in DNAscanner.

Once that's removed, also modify the ServerSetIsClosed method so it calls ServerHandleContentsOnStatusChange AFTER updating the syncvar, and remove the "force" parameter in ServerAddInternalItemInternal as it was added only to work around this issue

Also consider whether something other than inheritance can be used for DNAscanner, as inheritance just makes DNAscanner more hard to make sense of.

**Comment by fomalsd** [comment]
also: not code-related, but dna scanner cabin lost its opened sprite

**Comment by DooblyNoobly** [comment]
> 
> 
> also: not code-related, but dna scanner cabin lost its opened sprite

Nope thats all fixed now
