### ISSUE TITLE
On/off sprites for AirVent/Scrubber

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2877]
Scrubber and AirVent should have different sprites when unanchored and not working vs. anchored and working. At the moment they look like they're always off so it's hard to tell what's their state.

**Comment by bonette** [comment]
Update from foma: These sprites are already imported, they just need to be assigned in Unity.

**Comment by bonette** [comment]
Finished on, used the blue version (wide).  Animation's done and coupled with a single scrubber for now.

**Comment by bonette** [comment]
I have both Scrubber and AirVent ready to go, however...  Getting an error that makes little sense to me. 

MissingReferenceException: the object of type 'SpriteRenderer' has been destroyed but you are still trying to access it.  Your script should either check if it is null or you should not destroy the object.

It is happening for AirVent.  I've not destroyed any objects unless it's considering the test one I made before I turned it into a prefab.  Thoughts?

**Comment by bonette** [comment]
Upon reopening Unity, this error was gone.  Committing the files to a Pull Request.

State of files:
Scrubbers now have three states
- Off (Generic non-working state)
- On (Blue lights, clockwise rotating light)
- Purge (Red lights, inward animation) Some refer to it as siphon, but I kept its initial filename

Air Vents now have three states
- Off (Generic non-working state)
- On (Blue lights, clockwise rotating fan)
- Welded (Welded shut, damaged exterior)

**Comment by corp-0** [comment]
closing since we now have the sprites implemented
