### ISSUE TITLE
Issues with v0.1.2

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#288]
1. When you run diagonaly into airlocks you open two of them.
2. When you press two opposite keys (left/right or up/down) you stop moving entirely, the second input should override the first input.
3. sometimes when someone is crit they can still move while on the ground, no idea how to replicate it.
4. misssing tile in brig solitary confinment cell 2, and execution room.
5. The janitor jumpsuit has the hazmat suit sprite (inhand).
6. The engineer shoes have syndicate rollerskate sprites ???

**Comment by DooblyNoobly** [comment]
Will be breaking these up into individual bug reports for the new  bug cleanup project soon
