### ISSUE TITLE
Hitting enter causes the last pressed button on the UI to be pressed again

### ISSUE THREAD

**Issue by Mantle-Wanderer** [unitystation/unitystation#2897]
# Issue Template

### Detailed Bug Report
Anytime you hit a UI button when you hit the enter key afterwards it will press that same button again once.

Here's a ~200KB gif on **_GER_** showing it off. First I press enter a couple times, and hit the Toggle Light button a couple times just to show those work as normal. Then I hit the Toggle Light button once, hit enter, and repeat that a few times. Notice that it toggles off again as soon as I hit enter.
![Unitystation -- Enter key presses UI button last pressed #8](https://user-images.githubusercontent.com/12883734/73839115-202fce00-480d-11ea-8e1f-a3ac052f6429.gif)
_Reproduction_

I've confirmed this same bug happens with the turning buttons on the shuttle console too.
![Unitystation -- Shuttle Turning Keys](https://user-images.githubusercontent.com/12883734/73839410-d4c9ef80-480d-11ea-8fac-ddd4528933ad.png)
_Shuttle turning keys_

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

For sake of ease-of-reproducing I went with this specifically. As said earlier it seems to work on atleast the shuttle U.I. turning buttons too. Ping has no effect on this, it seems entirely client-side.
1.  Die, and ghost.
2.  Hit the mining lamp button 'Toggle Light'.
3.  Hit enter, see that the button is toggled again.

**Comment by daalta** [comment]
Alright, this seems to happen when Navigation is set to a value such as "Automatic" in the button's inspector. Setting it to "None" should fix the issue, but... there's a lot of buttons!

![2020-02-07_21-23-45](https://user-images.githubusercontent.com/9169275/74063201-3ea1ef00-49f0-11ea-8b39-b5012ed8abcf.png)


I'll over over some of them to prevent the enter key being overridden for chatting.
