### ISSUE TITLE
players don't take damage from cold

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2903]
in the byond version players take damage from the cold, it's burn damage if I remember

**Comment by PerfectTangent** [comment]
was this completed?

**Comment by NoooneyDude** [comment]
No, damage from hot/cold is not implemented (or - at least - not working) yet.

**Comment by jamessimo** [comment]
Please add this to type: health

**Comment by corp-0** [comment]
Bod fixed this on god knows what PR
