### ISSUE TITLE
Using scrollwheel to zoom is reversed on Linux

### ISSUE THREAD

**Issue by jessicamaybe** [unitystation/unitystation#2908]
In the Linux version, zooming using the scroll wheel is reversed. Scrolling down zooms in, scrolling up zooms out. Scrolling is also reversed in the settings menu.

**Comment by Coolsurf6** [comment]
Met the lad who talked about that in game. Seems a bit wacky.

**Comment by jessicamaybe** [comment]
Yea that was me, lol

**Comment by Nutjob** [comment]
I can confirm this, got the same bug on Ubuntu 18.04; the same also happens while scrolling in the options menu.
The same bug also happens on others Unity games as Tabletop Simulator.

**Comment by x10an14** [comment]
Same here, on Debian 10.

**Comment by jessicamaybe** [comment]
It looks like this bug has been fixed on my end, it may have been a Unity issue?

**Comment by corp-0** [comment]
If we get another confirmation, we close

**Comment by Nutjob** [comment]
Seems to be fixed on my side too.

**Comment by corp-0** [comment]
Awesome. No idea how or when it was fixed but good to know it was. Closing.

**Comment by x10an14** [comment]
What game was this again? Space Heaven?
