### ISSUE TITLE
With lag, multiple people can select the same role.

### ISSUE THREAD

**Issue by kylanpl** [unitystation/unitystation#2909]
## Description
If multiple people click roles like Captain in the beginning of a round, if there's enough lag you get 2+ 
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Have a lot of people online
2.  Have multiple people click captain at round start.
3.  Observe captains.

**Comment by Coolsurf6** [comment]
![Unitystation_2ur2Sbl5OW](https://user-images.githubusercontent.com/16472329/73908212-ad018700-48f4-11ea-9593-c937b9759827.png)

Usually happens when the round starts, and more than 1 person clicks captain before the server can tell the client that there is already a captain.

**Comment by krille90** [comment]
From #2965 :
![image](https://user-images.githubusercontent.com/7312905/74085503-c718a200-4a79-11ea-97a4-bebd2f58ac60.png)

**Comment by chairbender** [comment]
Also, there is no server side check about what occupation / job they should get, it just gives them whatever they asked (unless they are going to spawn as an antag), regardless of occupation limits!

Logic for this should be added to JoinedViewer.CmdRequestJob. Should be pretty easy.

**Comment by daalta** [comment]
I've seen reports of this happening again, needs replication though.

https://github.com/unitystation/unitystation/pull/3114 should have fixed latency-related problems, but maybe something goes wrong if players choose the same role on the same server tick?

**Comment by ThatDan123** [comment]
Should be fixed #4083, #4363
