### ISSUE TITLE
Local events (chat, sounds) can be heard outside of range B: 120

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2915]
Sometimes you get event messages and sounds from the station while you're e.g. far away mining on a shuttle. This should be addressed.

**Comment by fomalsd** [comment]
uh, still a thing

**Comment by fomalsd** [comment]
I really think this needs a bounty since it's much trickier than it looks for whatever reason

**Comment by DooblyNoobly** [comment]
This is a complicated bug and is hard to recreate locally. Its urgent as well so placed a bounty of 120 on it
