### ISSUE TITLE
Two Tiles in Research Are Impassable

### ISSUE THREAD

**Issue by LonelyHowls** [unitystation/unitystation#2916]
# Issue Template

## Description
https://i.imgur.com/pQH3Jcl.png The two tiles I am pointing at are impassable. Not sure why? The game doesn't show anything in these tiles. 
### Detailed Bug Report
I cannot push things into that area nor see anything special there when I examine what's on the tile with alt-click. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Spawn in as a scientist/go to science
2.  Try and enter those tiles
3.  Cry.

**Comment by SalmonidJester** [comment]
So, this popped up into my mind while doing some testing and decided to attempt to shoot the spots, in which it appears the two tiles are occupied by "virology 10" and "virology 16". My guess is leftover mapping stuff that was never deleted.
