### ISSUE TITLE
Plasma fires make server lag hard when there are many players connected

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2917]
Players experience rubberbanding and can't do much when there's a large fire spreading throughout the station. Server lag is quite possibly caused by vast amount of update messages sent to all players for each fire tile

**Comment by chairbender** [comment]
Yeah ane ither things that cause lots of tile updates cause lag as well.

I'm thinking the way to go would be to batch the tile updates, perhaps at some interval. Right now we only batch the initial state when joining and iirc all tile updates after that are one network call per tile.

**Comment by chairbender** [comment]
Yeah actually thinking about how much networking calls we make when it's not needed... Proximity based priority seems to be commonly used for a game like this to improve network performance. Not even having to calculate fov, at least just have a distance based approach. We may want to restrict max zoom for this reason (make exception for ship piloting).

Also perhaps using priority to decide how much time we'll allow the server to spend on networking calls, at a certain point we would just skip the networking calls for that tick.

**Comment by chairbender** [comment]
Oh, keep in mind fires are game objects, not tiles. So it's not actually tile updates until tiles start getting damaged, it's just a lot of object spawning.

**Comment by krille90** [comment]
I am pretty sure fires are actual tiles.
You can't select them in the editor and they are spawned via 
`tileChangeManager.UpdateTile(position, TileType.Effects, "Fire");`

**Comment by chairbender** [comment]
yeah got confused because we actually have 2 kinds - actual fires are doing via tiles, then there's a fire gameobject you can spawn via EffectsFactory.

**Comment by chairbender** [comment]
![image](https://user-images.githubusercontent.com/1329062/74207304-e52a0200-4c33-11ea-833a-09584f629ad1.png)

**Comment by chairbender** [comment]
So, we are discussing significant atmos changes right now. Our current thinking is using a double buffer with a pointer to the readable one and a thread safe command queue so main thread can tell atmos what changes it wants to make.

Another thing I noticed is that hotspot processing (in ReactionManager) all takes place on main thread - not just creation/removal of the fire tiles and application of damage, but also the checking and updating of hotspot temperatures, consumed gases, and volumes. This creates even more potential for concurrency issues.

Most of that GC is also coming from a big array copy that happens so current hotspots can be iterated through while updating the dictionary that stores where the active hotspots are.

Plan is to hold off on fixing this until atmos is reworked, though I might experiment with a simple fix to try to avoid this GC as I think it can be done with minimal code changes.

**Comment by chairbender** [comment]
Actually I think its worth still trying to fix this issue in the meantime, as it also should help avoid the issue where plasma fires are so easy to cause and so destructive and unstoppable.

**Comment by chairbender** [comment]
slowly but surely making my way through this. Lots to do to reduce GC, still quite a ways to go.

It was 2.1 MB GC spikes in that screenshot, I have it down now to 0.5 MB, and I know we can get it much lower, within the kb range
