### ISSUE TITLE
You can have empty slots between items in containers

### ISSUE THREAD

**Issue by VictorVow** [unitystation/unitystation#2921]
Reproduction:
- Pick up item
- Put it in backpack slot 3
- You'll have slot 1 filled by your internals, slot 2 empty, slot 3 filled by the new item

**Comment by PerfectTangent** [comment]
Not sure if this is a bug report, as it has reproduction steps but is tagged as a feature. I assume it's about how items do not shuffle to the leftmost slots when a bag is opened and there are empty slots in between. I personally don't see this as a problem, so closing. If we move towards a bulk or volume-based inventory, then it would be useful, but with our current dedicated indexed slots, this isn't needed.

**Comment by VictorVow** [comment]
It was a bug report, I had assumed SS14 was going to follow SS13's inventory model but it seems not.

**Comment by PerfectTangent** [comment]
this is unitystation, not ss14.
