### ISSUE TITLE
Bug while you travel the space and character won't revive

### ISSUE THREAD

**Issue by constantinosloizou** [unitystation/unitystation#2932]
**Detailed Bug Report**

- Character won't move on space even when you use the arrow keys. Keeps moving on a straight line until you die.

- When you are a ghost it won't let you revive.

**Comment by krille90** [comment]
> Character won't move on space even when you use the arrow keys. Keeps moving on a straight line until you die.

you are not supposed to be able to move in space. You can throw items to move u in a different direction though.

> When you are a ghost it won't let you revive.

You can't revive yourself as a ghost. Only way to be revived is if somebody clones you.
