### ISSUE TITLE
chat / radio shortcuts

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#2937]
Chat shortcuts existed as an option in SS13 and are very effective when used properly.

by pressing enter and prefacing your message with a radio channel prefix, you'd speak on that channel, otherwise you'd speak in local chat:
"i am speakin in local chat"
"; I am speaking on public radio"
":s I am speaking on security radio"
so forth based on https://tgstation13.org/wiki/Radio_channels

**Comment by daalta** [comment]
Hmmm, I think we may already have some shortcuts, let me check...

EDIT: Nope, we don't. I guess this should be processed before sending the message to the server. Either PostToChatMessage.cs or ChatUI.cs should change the list of channels for the message. To detect which channels the user typed ( `; :s` et cetera) we could add a method to Chat.Process.

With the amount of bugs currently floating around I'll probably get around to implementing this *eventually*. But if anyone wants to have a go at it I won't stop you :)

**Comment by daalta** [comment]
Implemented by #2972
