### ISSUE TITLE
Xeno infestation game mode 

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2938]
## Description
Suggested by Misterix_max, a game mode where a xeno nest spawns somewhere (predefined possible spawn points even), spawns xenos from it and must be destroyed. 

We have xenos so why not let people actually see them. 

Should be pretty straightforward to add given the current game mode system hooks. Just need to create the xeno nest object, spawn point, and the game mode logic.

**Comment by NoooneyDude** [comment]
I think there's a situation where xeno eggs can spawn in maintenance. Is the same thing? Issue #3966 or #4039?

**Comment by corp-0** [comment]
This could be an event with the new event system

**Comment by corp-0** [comment]
closing in favor of #4719.
