### ISSUE TITLE
Window / Grille construction and deconstruction 

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2939]
## Description

Add ability to construct / deconstruct windows, grilles, and reinforced windows. You can reference the reinforced wall construction logic (and reinforced girder) to see how this can be accomplished. Note that when it is turned into a tile, logic switches from Interactable component to Tile Interaction system.

**Comment by fomalsd** [comment]
partially implemented: clicking with rods on plating for grille, clicking with glass on grille for reinforced window

**Comment by NoooneyDude** [comment]
I think this has been implemented by PRs #2996, #3384 and #3427 and so this issue can be closed.
