### ISSUE TITLE
pressing respawn enters login loop, cannot exit or continue past character creation

### ISSUE THREAD

**Issue by MitztheKat** [unitystation/unitystation#2946]
# Issue Template

## Description
I got ghosted (see discord screenshot) and decided to try the respawn button. I then logged back in and got sent to character creation (character was in tact) I tried continuing and exiting, but lo and behold, I got sent back in a loop.
### Detailed Bug Report
after tabbing in and out, bug disappeared. no footage possible.
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
optional steps:
>turn off and on screen (i closed and opened lid)
>death by spaceship
>extended server
>USA2
>alt tab in and out once or twice
1.  get ghost'd
2.  press respawn button
3.  get sent to character creation screen
4. if loop happens, you got the bug.

I wonder how long this'll take

**Comment by NoooneyDude** [comment]
I don't think non-admins have the option to respawn anymore. Could probably close this issue.
