### ISSUE TITLE
server lag accumulates Across round restarts

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2948]
# Issue Template
 
1.  Join one of the popular servers 
2.  Observe lag 
3. Hard  Restart it
4. Observe the lack of lag

**Comment by PerfectTangent** [comment]
Honestly, I haven't seen much of an accumulation of lag over time in a while. There is still issues with memory leaks and accretion of performance degradation, but not specifically lag and slowly increasing ping. Lot's of work has been done lately to cut down on potential causes. Should this be closed?
