### ISSUE TITLE
Players can spam the chat.  Create a protection against that.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2957]
Players can spam the chat with the same shit again and again.

We can put a protection against that.

**Comment by daalta** [comment]
You mean spamming large walls of text, right?

I imagine that this would involve putting an upper limit on the length of chat messages. Limiting the input box might be enough.
Any suggestions on what the max length should be?

**Comment by Bokkiewokkie** [comment]
Since the game itself spams textwalls aswell (like roundend reports etc.) maybe also add a whitelist for people or entities that are excluded from the limit.
And for a chat length maximum I think around 200-250 characters sounds reasonable.

**Comment by daalta** [comment]
Thank you, that sounds reasonable like a reasonable limit. The whitelist idea made me think of something else...

Users might split up their messages to circumvent the limit! We could fix that by limiting the maximum amount of text? Per minute, maybe?

**Comment by daalta** [comment]
I'm implementing this in PostToChatMessage.cs . Players will be allowed to type 500 characters per minute, which translates to 100 WPM. This should be enough for most players.

If a player goes above that limit I might make them stammer instead, showing shomething like "Player is speaking too fast to understand."

EDIT: Perhaps I will have to do this in another class, hmm...

**Comment by Scorr** [comment]
That would still allow someone to spam 500 messages with 1 character. Also I wouldn't go for such a large timeline because in the case someone does reach it through normal means, they'd have to wait a full minute before they can type again.

I'd suggest just limiting messages sent. If you send more than that you'd have to wait x seconds before you can type again. I don't know what values other games use but it could for example be 4 messages in 5 seconds.

**Comment by daalta** [comment]
Oh, I thought we already had some sort of cooldown for chat messages. I can do that too, thanks for suggesting it.

**Comment by daalta** [comment]
I'm fairly close to finishing this, but I need some sleep. I think what I ended up making is a good solution *for now*, but it's all client-side. We might want a serverside solution in the future, buttt ooooh wellllll

My progress:
 https://github.com/daalta/unitystation/commit/9e1d2ea363282c49977c02ec3563e99c50547d42#r37192437
