### ISSUE TITLE
Fix Bans | Make it IP-Ban

### ISSUE THREAD

**Issue by Emma3DSS** [unitystation/unitystation#2958]
# This is probably something we should get onto

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Be Admin
2.  Ban person

**Comment by Misterixmax** [comment]
Suggest adding also a hwid ban

**Comment by BaronBW** [comment]
Will take a look at this when I get a mo

**Comment by BaronBW** [comment]
https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Managers/PlayerList.Admin.cs

Looking at the above it looks to me that banning is based on a Users Id, which I believe is from the data store, so if anything this should be a pretty solid ban for that users account. 

Probably best idea to stick to the HWID. No need for the addition of an IP as who doesn't use VPN's in this day and age (except for kids).
https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html

Can't get the game to actually work so me testing this is not going to work out for now, anyone else wants to make these edits feel free, will come back when I can get things on my end to work. Even unity is being a bit of a pain. Thought a restart and reinstall would settle things but its deeper than that.

**Comment by fomalsd** [comment]
done
