### ISSUE TITLE
Sometimes unconscious players can still move

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#296]
Sometimes when a player is in crit his body still processes movement actions in playersync. Seems to mostly happen with knife fights.

Suggestion:
Clear all movement actions in playersync if player is in crit.

**Comment by krille90** [comment]
is that still a thing?

**Comment by fomalsd** [comment]
Crit is currently off, and this hasn't been reproduced in quite a while. 
You can close this for now, I think

**Comment by DooblyNoobly** [comment]
Will rereport if bug is seen again

**Comment by fomalsd** [comment]
Just knifed myself to death while moving, was able to move in crit until I turned into a ghost.

**Comment by fomalsd** [comment]
this is still a thing. should open again

**Comment by fomalsd** [comment]
It shows up once in a while in medium-scale multiplayer deathmatch tests, hard to reproduce on your own

**Comment by Necromunger** [comment]
Would [NetworkEmulation](https://docs.unity3d.com/Manual/NetworkEmulation.html) assist in identifying this bug? Or possibly not reproducible for host and needs to be tested from a client with high latency emulated?

I don't have access to a testing environment currently.

**Comment by fomalsd** [comment]
Last time I reproduced that when testing new health system with damage zones, knifing myself in multiplayer environment many, many times. There was no artificial ping involved.
I guess we could close this until next big multiplayer test, and open this again if this issue persists
