### ISSUE TITLE
Multiple players in one profession over the limit.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#2965]
Reproduce:
- All the players who want that profession must select it at the relative same time as the other players.

Description:
- We once had about 12 players as security in one round, in another we had 3 captains.

Solution(?):
- As is with the OG SS13 on BYOND, players should choose what professions they want, what they're ok with, and what they absolutely want to avoid having, then when the round starts the server chooses who is what as well as limiting the number of players for each profession.

**Comment by krille90** [comment]
Already mentioned #2909 
Will copy suggested solution and close this issue
