### ISSUE TITLE
The health doll on the right hand side of the screen is mirrored to the health doll that the player can select to heal.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#2966]
Reproduce:
- Get shot in left leg.
- Select left leg.
- Try to heal left leg.
- "Your left leg is not injured."
- Do the same for the opposite leg, heals up just fine and dandy.

Haven't been able to test this with arms yet, will comment here if I can find anything.

**Comment by chairbender** [comment]
thanks for the report, this is a good first issue
