### ISSUE TITLE
Windows and walls are far too easy to break.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#2967]
With a small bit of know-how and selecting the right job, a player can get anywhere.

Takes under a minute to break a window and it's grille with a crowbar or similar, they should at least be more reinforced on exterior windows and ones that lead to important areas such as the medbay (Of which gets overrun easily).

Likewise, interior walls are far too easy to get through. Start off as an engineer to access to all of the right tools then head straight below the armory in maint. Now you're armed and have all the tools you need.

**Comment by daalta** [comment]
This should be easy to change. Do you have a suggestions and what the values should be? Objects can also have various resistances, so increasing melee resistance is also an option.

**Comment by Evan-R-Rogers** [comment]
@daalta 

Well, I don't think this should be entirely left up to me but the window's themselves should have at least twice the health and the grilles maybe 2.5 times the health. Furthermore, certain objects should not be able to break through the grilles and/or windows easily if at all. Examples:

- Fire extinguishers, able to break through windows but not grilles as easily if at all
- Knives, able to break neither
- Screwdrivers, nada
- Wrenches, crowbars, batons, bats, other heavy swinging or pry-bar type objects should be able to break through both rather easily (Values should be tuned depending on the weapon such as crowbards would break through both quicker than a baton)

Personally I think almost anything should be able to break through both but not as easily as others. The knives for example should take such a while that it isn't quite worth it but it is possible with determination.
__________________________________________________
As for walls, they should take more specialized tools to disassemble and break down. Maybe add reinforced walls/doors/windows to security, medbay, HoP room, Captain's quarters.

**Comment by daalta** [comment]
Upping the health by a factor of 2.5 sounds reasonable. I like the idea of sharp and blunt objects, but that would require adding new resistances.

![2020-02-09_11-35-55](https://user-images.githubusercontent.com/9169275/74100520-597b7d00-4b30-11ea-8ba1-9ae7da9418fa.png)

**Comment by fomalsd** [comment]
How do current values compare to /tg/? they should match byond equivalents, but not be stronger than that.

**Comment by daalta** [comment]
A few weeks ago I updated the values to roughly match /tg/, but I never verified if doors break in the same amount of time. I'm sure there are some differences in how we handle damage that might make door integrity feel different, even though the numbers are the same.

**Comment by voidel** [comment]
You can shoot a door down with about 10 uzi bullets, I agree it doesn't seem quite right.

**Comment by fomalsd** [comment]
it's fine until we have other means to deconstruct airlocks.

**Comment by daalta** [comment]
I'm changing the values right now. Here are the changes.

**Integrity**
`350 --> 875 Doors`
`100 --> 300 Walls`
`100 --> 250 Windows`
`60 ---> 250 Grills`

So walls, windows and grills are now slightly more easy to break than our previous doors, and doors are now. 

Windows take 5 Uzi shots to destroy, grills 11. Doors take quite a while to shoot through, but here's a screenshot.

![Unity_2020-02-09_19-40-25](https://user-images.githubusercontent.com/9169275/74107846-7b96ee80-4b74-11ea-8bcd-64d387b229cd.png)

**Comment by Misterixmax** [comment]
@daalta no no no no no, please no. Check first how many kicks can window and grille survive on tg13 first.

**Comment by fomalsd** [comment]
Please don't rush balance changes just because one person complained about something. refer to /tg/ values first and foremost!

**Comment by daalta** [comment]
Cool, I'll hold off for now. When someone has tested values for health changes I can implement them.

EDIT: Just checked, our integrities and resistances of windows and grilles are already very similar to tgstation. As @chewbyte and @Evan-R-Rogers mentioned objects are still fragile though. So why do they still break to easily? Are our weapons too strong?

**Comment by Evan-R-Rogers** [comment]
@daalta 
It could be a lag issue, maybe some values are wrong, or simply some sort of bug.

Just a thought: try, very slowwwwly, hitting a window and count how many clicks it takes to break it. Then, on another window, click as fast as you can trying to count as many times as you clicked as before. From what it seems attacking has a certain cooldown and what I'm wondering is if the animation for attacking isn't synched to the actual damage caused; if the number of times you clicked equal eachother then it seems it would be this issue.

**Comment by daalta** [comment]
Would be good if someone could follow @Evan-R-Rogers 's suggestions. Though I wouldn't be opposed to increased integrities and seeing how players react.

**Comment by Evan-R-Rogers** [comment]
I still think we should increase integrity values, at least do a test run on the staging server.

In my mind, its either that or we get new windows/doors that are further reinforced.

**Comment by bonette** [comment]
With hand, a window takes forty animations to break in UnityStation, regardless of how many clicks are taken in the build I am on.
In TGStation, setting your Intent to red and clicking a window merely has you tap on it.

With the Chain of Command (which does 10 brute as far as I'm aware?) it takes 20 animations to break, regardless of how many clicks are used.  

In TGStation, attacking a window with an emergency oxygen tank takes 13 hits to destroy, but has a longer cooldown than in Unitystation.  The metal grill takes 15 hits to destroy.

In Unitystation, attacking a window with an oxygen tank takes 20 hits to destroy, but has a decently shorter cooldown between attacks.  The metal grill takes 6 hits to destroy. 

---

In TGStation, the reinforced glass that protects significant areas of the station simply cannot be broken by some weapons.  With the emergency oxygen tank used by previous tests, I hit a reinforced glass with a grill underneath 100 times without the cracked glass sprite appearing.  Meanwhile, an emergency toolbox would shatter the glass in 63 hits.  Afterwards, an electrified grill prevented me from determining the necessary damage to break it.  

I have not looked at the source code for TGStation, but potentially some objects may have a hidden 'hardness' rating, in which it nullifies damage unless it goes over a certain threshold.  It may just nullify a static amount of damage and anything that bleeds over is dealt, or it may nullify only damage under a certain amount and anything over is taken at full value.

If we want to have windows that feel more akin to SS13, it's just a matter of either increasing health or adding a hardness feature, as well as adding the other obstacles such as electricity that would generally prevent access to high-security areas.  I hope this was helpful!  Let me know if there's something I'm missing.

**Comment by Evan-R-Rogers** [comment]
Wonderful comment and hats off to you for the thorough testing!


> I have not looked at the source code for TGStation, but potentially some objects may have a hidden 'hardness' rating, in which it nullifies damage unless it goes over a certain threshold. It may just nullify a static amount of damage and anything that bleeds over is dealt, or it may nullify only damage under a certain amount and anything over is taken at full value.

To me this seems to be the most likely cause for the damage differentials between the games.


EDIT:
- Through some later testing I found that the fully reinforced windows have the exact same health as the regular windows: 20 hits with a fire extinguisher, the grilles underneath both takes 6 hits.

**Comment by voidel** [comment]
I don't think it's hidden, I remember seeing it when inspecting object attributes. It was something like threshold or resistance, and like you said the attacks need to breach this in order to actually cause damage.

Meaning you can't fist a door to death like I remember doing previously on unitystation.

**Comment by bonette** [comment]
> I don't think it's hidden, I remember seeing it when inspecting object attributes. It was something like threshold or resistance, and like you said the attacks need to breach this in order to actually cause damage.
> 
> Meaning you can't fist a door to death like I remember doing previously on unitystation.

By hidden I was referring to testing without examining the game files, with no in-game reference to it.  Without looking at the files, the only hint that it had a damage threshold is by the term "reinforced".  Sorry for the confusion.

**Comment by bonette** [comment]
Update:
I do not think armor currently works on tilemaps such as windows and grills.  I tested it earlier and adding armor via our built-in Integrity system didn't seem to do anything.

**Comment by daalta** [comment]
@bonette Huh, that might explain some things. Would you be able to sumbit an issue showing how to reproduce it?

**Comment by RedlineTriad** [comment]
Fixed in:  #3528

**Comment by daalta** [comment]
@RedlineTriad You sure? In this issue we discussed issues with guns and other weapons as well. The health and damage values are still wonky, despite #3528

**Comment by RedlineTriad** [comment]
I think this issue should be split anyways into deconstruction and destruction issues anyway.
Also, this issue hasn't led to anything productive yet.

**Comment by daalta** [comment]
Hmm, you're right!

Here's one. https://github.com/unitystation/unitystation/issues/3830
