### ISSUE TITLE
Cannot pet ian

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#2969]
Description
You cannot currently pet ian.

Steps to Reproduce:  

1.  switch to help intent
2.  click ian
3.  cry

**Comment by DrSirKnight** [comment]
This is clearly a high priority issue that must be fixxed ASAP

**Comment by daalta** [comment]
Well... *technically* you could type `/me pets Ian gently`.

*daalta pets Ian gently*

chairbender mentioned we wanted to work on NPC AI in the future, so maybe he'll add petting, too.
