### ISSUE TITLE
Nuclear authentication disk non existant and other nuke issues

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#2971]
There is currently no disk meaning the nuke blows the seccond a nukie says the code to the nuke because theres always a shitter arround to blow it.

**Comment by vortex1942** [comment]
My suggestion
The nuke lightly shocks any non syndicate members that try to enter the detonation code
As it is very simple for a nukie to broadcast the code over the radio. 
EDIT: As i was writing this a Secoff detonated the nuke

**Comment by Evan-R-Rogers** [comment]
My suggestion is to take away the common comms that the Nukies have and instead only allow them to talk on Syn channels to prevent being a shitter, other suggestions regarding wall/windows/door integrity would help remedy shitters getting to the nuke too easily.

**Comment by The-Scout** [comment]
Also currently everyone can hear nukies regular speech for some reason

**Comment by corp-0** [comment]
> Also currently everyone can hear nukies regular speech for some reason

that's because of #2915
