### ISSUE TITLE
Document How to Set up a Server

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2977]
## Description
Self explanatory, lots of people asking for this.

**Comment by PerfectTangent** [comment]
this issue was satisfied by this section https://unitystation.github.io/unitystation/development/Hosting-a-Server/ of the development guide, correct?

**Comment by PerfectTangent** [comment]
This has been satisfied by the link above, at least to a minimum. Now that there's a section in the wiki for it, it can be expanded upon if it needs it.
