### ISSUE TITLE
Bloodsplats prevent construction

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#2984]
# Issue Template

## Description
If you try to construct a wall where there's a bloodsplat, it won't let you.

### Detailed Bug Report
It helps if you include any relevant DM code / config (for describing how new features should work), images, gifs, or youtube videos!

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
1. Construct a wall above a bloodsplat

**Comment by daalta** [comment]
@ReiderJack has posted some videos showing the issue. https://github.com/unitystation/unitystation/issues/3374
