### ISSUE TITLE
Slashing own body after being cloned "kills" you

### ISSUE THREAD

**Issue by SayaMadness** [unitystation/unitystation#2989]
## Description
If you try to destroy your own body with a weapon while alive, you'll become a ghost and wont be able to enter your body back. It'll just stand there in front of the meat you just made from your old body

### Steps to Reproduce

1.  Die and let someone clone you
2.  Get a melee weapon
3.  Cut your own body
4. Become a ghost after doing so.

**Comment by fomalsd** [comment]
See  #3165
