### ISSUE TITLE
Build the first generic networked prefab

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#299]
The idea is to have a generic network prefab for different types of network items. We will start with clothing.

Steps:
1. Create a generic network prefab for clothing with all of the required components
2. Create a component that will retrieve clothing and sprite data from the DMI icon database (being created by foma)
3. Put the prefab into NetworkManager spawnable prefab list
4. Implement use of new generic prefab in a test (possibly with the equipment loadout on the playerprefab)

After the process is proven then we will move on to other types.

**Comment by fomalsd** [comment]
Done, too!
