### ISSUE TITLE
You can remove your handcuffs when dead

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#2993]
## Description

When you're dead or unconscious, you can remove handcuffs. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Die handcuffed.
2.  Stay in your body
3.  Uncuff yourself normally.

**Comment by The-Scout** [comment]
I just attempted this and was unsuccessful its strange, it may have been because i was stunned when i died?

CONFIRMED, being stunned when you die disallows this bug.
