### ISSUE TITLE
Many items near a broken window are a death trap

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#2994]
### Detailed Bug Report

If you have lots of items near a window and the window gets broken but the grille stays, due to the force of the air leaking out, the items kind of stay in a perpetual motion back and forth in front of the window, dealing potential throwing damage. Anyone who approaches (most commonly in attempt to repair the window) just fucking dies instantly after getting hit by dozens of items flying back and forth. 

This happens most often with things like L6SAW bullet casings of which there are many. This can lead to hilarious situations when someone dies this morbid way and people attempt to rescue him, they too get instantly killed by the hailstorm of bullet casings, shards, and other miscellaneous items.

**Comment by NoooneyDude** [comment]
This was alleviated by #4294 and so this issue could probably be closed.
