### ISSUE TITLE
Add systems for handling multiple maps

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2997]
there seems to be a lot of issues with making a new map currently and getting it to run so investigate and set up an appropriate system

**Comment by Evan-R-Rogers** [comment]
I'll get to work on this. From what I'm imagining this shouldn't be all too hard to implement.

**Comment by NoooneyDude** [comment]
Does PR #4166 solve this?

**Comment by ThatDan123** [comment]
Gonna close this for now, when addressables are being worked on this might come up again but for now we have a usable system.
