### ISSUE TITLE
Develop space movement (floating off from station) B:30

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#300]
Develop a way to create the floating movements when you are drifting in space. At the moment there is already a check that determines if you are in space or not. The check is on playersync (or playermove?) and is called inSpace. 

The condition must also check if you are walking along side a wall so you can simulate walking on the outside of the station. For this you could use physics overlap circle or raycasting or use the matrix to see if there is any isPassable() == false conditions in the tiles circling the player. 

Otherwise the player must drift if he attempts to move while in space and not near a wall.

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

- Do the things above

Contributor will receive the bounty after merge (paypal)

**Comment by DooblyNoobly** [comment]
The exact behaviour that we require for space movement can be observed in the server player bug. When the server player is visible, attempt to run through him and your player will continue to follow the direction you are running and you won't be able to change course until you hit a wall. If we can find out what is happening here then we just need to apply it to the player when the isSpace flag is true on playermove. And then you have space move

**Comment by krille90** [comment]
I also observed the bug with other players, not just the server player.

**Comment by DooblyNoobly** [comment]
I know that we do not have a throwing feature yet to turn the player around. But I think we should just get this feature implemented first and then focus on throwing straight after as there will be an immediate need then to get it done.

Criteria:

- Move player in direction of travel if they slip off a station/shuttle
- Detect walls nearby and turn off space move if they are 1 tile away from a wall

Bounty: 30 usd paid via paypal on successful merge
