### ISSUE TITLE
Creating a large amount of new records in the Security Records Console

### ISSUE THREAD

**Issue by etoZen** [unitystation/unitystation#3002]
## Description
Large amount of new (added by the player) records in the Security Records Console may lead the server to very serious lags and even crash the whole server. But if server stopped lagging player who put his ID to the Console is unable to use the Console again and return his ID from this every Security Records Console.

### Steps to Reproduce
1.  Create 100-100000 new records in the Security Records Console.

**Comment by fomalsd** [comment]
thanks for reporting this!

**Comment by JesterX666** [comment]
To reproduce easily : just click on "New Record" non-stop.  They get slower and slower.

**Comment by JesterX666** [comment]
Will leave that one to a pro, it's not as nearly as easy as I tought it would be,
