### ISSUE TITLE
Player can spawn late as a nukie / Nuke duplicates with the late player

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3003]
Just played a round and after some time loading I chose to play Captain. I ended up spawning as a nukie very late into the game, and as I spawned another nuke spawned with me.

Possible ways to reproduce:
- Load into game but don't choose a career
- Wait until Nukie friends move nuke and clear shuttle
- Now spawn in, a new nuke should be there.

**Comment by corp-0** [comment]
is this still relevant?

**Comment by Jibbajabbafic** [comment]
Fixed in #3900
