### ISSUE TITLE
Spacewind is too deadly, we need magboots. B: 30

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#3011]
Description 
Currently there is essentially no way to deal with space wind as magboots are not in.

Proper magboots need 5 things

- Apply a speed reduction to wearer when toggled on unless outside of gravity IE space.
- Make the user unable to be slipped.
- Make the user unable to be force-ably moved by space winds.
- Ability to be toggled on and off via clicking the boots some way IE control or alt clicking.
- User cannot be pushed nor pulled unless via grab intent, speed when grabbed should be very slow.

Contributor will receive a bounty of 30usd on a successful merge of a solution that meets the criteria above.

**Comment by Bod9001** [comment]
humm Could we include part of this Fixing the back-and-forth of the Wind system, that makes a super grinder?

**Comment by craftxbox** [comment]
i'll attempt to yoink this if nobody else has

**Comment by craftxbox** [comment]
already in progress by @ReiderJack
