### ISSUE TITLE
Mining stopped working

### ISSUE THREAD

**Issue by Nutjob** [unitystation/unitystation#3012]
## Description
While it was working perfectly yesterday, today using a pickaxe against a rock tile did nothing at all.
I'm on Linux Ubuntu, but it was the same for the miners I've played with.
This happened on the USA 3 server with Build 4010.

### Steps to Reproduce
Grab a pickaxe and click a tile with a rock.

**Comment by RedlineTriad** [comment]
This is most likely fixed with a server restart, see: #2995, #2898.
Closing this in favor of #2898.
