### ISSUE TITLE
South Security Door has incorrect access permissions

### ISSUE THREAD

**Issue by myrmecoleonn** [unitystation/unitystation#3014]
The door leading to maints in the south of security can be opened by all crew, allowing them into the security office(but thankfully not the armoury).

Steps to Reproduce
1.  open the door from/to maints in the south of security playing as a job who should not have access, such as assistant
2.  watch in amazement as your feeble access level opens the door

This issue can be resolved by modifying the maintdoor prefab at x: 60, y: 43 on the OutpostStation scene from maintenance access to security access.

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/74168896-52cd3280-4c22-11ea-9800-4737ab34a3c1.png)

Change this variable not the Door Type, when fixing this.

**Comment by Raptorizer** [comment]
This issue has been fixed already, not sure who did it though.
