### ISSUE TITLE
Emagging Shuttle should send an admin alert

### ISSUE THREAD

**Issue by RedlineTriad** [unitystation/unitystation#3017]
# Description
Currently it is hard to track down shuttle suiciders as admins.
It would help if emagging shuttle would cause an alert similar to the plasma canister release alert containing coordinates and the emagger's name.

**Comment by pridit** [comment]
imo the meta for this is too strong, for admin tracking and such there should absolutely be a log generated that contains that but not announced to everyone - that solves it for admins, but to solve it for players the impact a suicide shuttle has should be significantly reduced so it's not that much of a threat (#2912)

**Comment by DooblyNoobly** [comment]
yeah I think admin should just get a log. Shuttle ramming is ok if you are antag and I've seen nukies use it as a good decoy
