### ISSUE TITLE
Playing offline should not require being logged in.

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3018]
Sometimes you just want to play by yourself and These times maybe don't have the Internet, Long train journey something like that, 
Add the ability to play "Single player" without log in

**Comment by MaxIsJoe** [comment]
Wasn't this done recently?

**Comment by AtnerNT** [comment]
![Capture](https://user-images.githubusercontent.com/48405920/203546814-8902aa24-c475-4fbf-9c15-846dbf6e7b8f.PNG)
Doesn't look like there's an offline play option??

**Comment by MaxIsJoe** [comment]
I was sure that we had a PR open that added it like a couple of weeks ago? Or was this something else entirely?

**Comment by AtnerNT** [comment]
https://github.com/unitystation/unitystation/pull/9305

Maybe its not working?

**Comment by corp-0** [comment]
> ![Capture](https://user-images.githubusercontent.com/48405920/203546814-8902aa24-c475-4fbf-9c15-846dbf6e7b8f.PNG) Doesn't look like there's an offline play option??

To go into offline mode, logout and then run the game without joining a server.

**Comment by AtnerNT** [comment]
Completed?
