### ISSUE TITLE
Add door welding

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#3020]
## Description
You should be able to weld and unweld doors shut with a lit welder. This includes regular doors and airlocks.
Make sure you use progress actions and play the welding sounds during the action, and change the door sprites to be welded/unwelded as needed.

**Comment by Tjarr737** [comment]
Just noting, that I am working on this.

Progress: Has survived rudimentary multiplayer tests. 
I have some gripes with the code, but I hope they can be resolved in the review process.
I may wait for an ongoing PR to finish before submitting this.
