### ISSUE TITLE
very annoying admin tools issue, Variable viewer gets stuck after restarts.

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#3023]
Description
Variable viewer gets stuck. this persists until client restart

Steps to Reproduce
1.  Open variable viewer, select a tile with "VV For Objects On Tile"
2.  Restart server
3.  Open variable vewier and see that it is stuck

Example webm https://cdn.discordapp.com/attachments/668605946691452949/676540411484962866/dXPtibXLDc.webm

**Comment by craftxbox** [comment]
can reproduce ~~AAAAAAAAAAAAAAAAAAAAA~~

**Comment by hecksadecimal** [comment]
This is still incredibly annoying, but VV probably needs a whole rework.

**Comment by NoooneyDude** [comment]
I think this has been fixed and so this issue can be closed.

![variable viewer fixed](https://user-images.githubusercontent.com/6926225/88258053-53124380-cd13-11ea-912f-b188814d6d2b.png)
