### ISSUE TITLE
Loading screen is interpreted as application freeze on Windows

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3025]
![WerFault_2020-02-10_23-27-56](https://user-images.githubusercontent.com/9169275/74196179-fb988380-4c5c-11ea-9abe-0f6daf8537cd.png)

### Description
Our current loading screen is cool! But it makes Windows think the application has frozen, showing the "Not Responding" pop-up.

Despite the warning in the top-right of the loading screen, some users are confused by the freeze.

The loading screen should be adjusted to keep it responsive (to Windows). If other operating systems also experience this issue, please leave a comment below.

### Steps to Reproduce

1.  Join a server!
2. Behold.

**Comment by DooblyNoobly** [comment]
nothing we can do until we optimize awake on all of the Managers

**Comment by daalta** [comment]
Solved with the new loading screen
