### ISSUE TITLE
Add a basic ahelp system B: 200

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3026]
At the moment its really hard for players to contact admins. What we need is a basic way for players to contact admins. 

I propose the /ahelp tag in chat input. If they type /ahelp <message> then it gets sent to the screen of all admins (a pop up like the restart vote pop up) and as soon as an admin clicks on it to reply it disappears off the screen of all the other admins. 

Criteria:
- Add the /ahelp functionality to chat
- Create a new ahelp network message that is sent to the server and then a message is sent to all of the admins
- When the message arrives on the admins client they get a pop up somewhere on screen that they can reply too. 
- Replies will just use the Admin bwoink system (could even auto open it to the admin bwoink page with the players name already selected) 
- If an admin claims the ahelp then send a message that makes it disappear from the screen of the other admins
- in addition to this when an admin bwoinks someone, a dedicated chat dialogue is opened up on their screen. A lot like what admins see in the bwoink menu, but limited to just speaking with that specific admin that initiated the conversation.
- Also add a way for players to send prayers to admins

Contributor will receive a bounty reward of 200 usd for a successful merge of a solution that satisfies the criteria above

**Comment by The-Scout** [comment]
also reliability of ahelps needs to be improved i have noticed sometimes they are not sent or replies are not sent.

**Comment by hecksadecimal** [comment]
Chat is still going to be chaotic in highpop servers. Even after proximity is fixed. People will start using comms more frequently, and admin bwoinks may end up getting drowned out in our current chat implementation. 

So in addition to this I would also propose that when an admin bwoinks someone, a dedicated chat dialogue is opened up on their screen. A lot like what admins see in the bwoink menu, but limited to just speaking with that specific admin that initiated the conversation.

**Comment by DooblyNoobly** [comment]
not a bad idea actually

**Comment by DooblyNoobly** [comment]
Added it to the criteria and increased bounty to 150

**Comment by fomalsd** [comment]
what do you think about ahelp discord integration? ss14 has OOC routed to their discord and it's pretty convenient

**Comment by hecksadecimal** [comment]
That sounds really nice.

**Comment by Jibbajabbafic** [comment]
I think a dedicated menu button, or hotkey like F1 would be good to have too.

**Comment by DooblyNoobly** [comment]
changing from b150 to b200. Bigger job then I thought

**Comment by DooblyNoobly** [comment]
> 
> 
> what do you think about ahelp discord integration? ss14 has OOC routed to their discord and it's pretty convenient

I wanted to get this feature in but all my time has been consumed by the new system itself. I'll make a separate job to do this after admin chat is finished

**Comment by DooblyNoobly** [comment]
`Also add a way for players to send prayers to admins` this needs to be its own job. I've created a button, notifications and window for it but I don't want to rush it in and have it bare bones so I'm leaving the window blank and creating a new bounty for it. The prayer requests need to have buttons on them for different ways to respond and to also have a button to easily teleport to the player doing the praying. I might combine this job with discord webhooks so ahelp and prayer requests get sent to a discord channel when no admins are online. Also the admin chat and ahelp system took damn near 6 days to complete and I want this job done for my own sanity

**Comment by DooblyNoobly** [comment]
I also forgot to mention that I added an admin to admin only chat where admins can talk during the game
