### ISSUE TITLE
Chat is cut in half at certain resolutions

### ISSUE THREAD

**Issue by Ranzarth** [unitystation/unitystation#3029]
# Description

Chat cuts out halfway at certain resolutions, for example at 3840x2160 it looks like this:
![](https://i.imgur.com/FnU7pdi.png)

Only solution is to decrease window size and not play at fullscreen.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Play on a 4k Monitor.
2.  Observe.

**Comment by voidel** [comment]
I can confirm that this happens at 3440x1440 too.

**Comment by Ninjaboi8175** [comment]
Been noticing this as well and thought it was odd. Going to check it out now and see if I can fix it.
