### ISSUE TITLE
[SUGGESTION] Add shutters to close infront of HoP windows.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3030]
Add shutters that close in front of the HoP's windows when the side panel is pressed. Time and time again some naked man with a crowbar smacks through the front windows then the inner windows without much resistance at all.

This could similarly be applied to other areas such as the Captain's quarters for a pseudo lockdown mode.

**Comment by Raptorizer** [comment]
Good idea, i'll get to work on it.
