### ISSUE TITLE
Botany door and windoor interaction bug

### ISSUE THREAD

**Issue by Misterixmax** [unitystation/unitystation#3031]
Doors and windoor won't open upon walking on them with higher than botanist access (chain of command bug?).
Windoor won't open up for anyone while you walking against it (collision bug?).
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Move towards door or windoor in botany with higher than botanist access.
2.  It won't open

They open up only by clicking on them. Windoor in captain's room work fine when you walk against them, but they are not on table like botany room one. 
Small bug with doors, huge problem with windoors

**Comment by Misterixmax** [comment]
Also saw other doors with such problem, but can't remember which doors. Actually I will take a look on fixing this issue .

**Comment by Raptorizer** [comment]
The windoor is an issue entirely different from what I can fix. A scripter will need to look at it.

**Comment by chairbender** [comment]
@Raptorizer yes, their scripting is bugged as all heck and has been for at least 1.5 years
