### ISSUE TITLE
Plasma won't stop burning if it's under a door

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#3035]
# Issue Template

## Description
![image](https://user-images.githubusercontent.com/19640077/74212660-25947a80-4c4a-11ea-9399-23f3ad458c71.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behavior:  

1.  Burn plasma
2.  Close door

**Comment by NoooneyDude** [comment]
I couldn't reproduce this issue. It may have been fixed.
