### ISSUE TITLE
[Issue] Wallmounts override on tiles

### ISSUE THREAD

**Issue by Raptorizer** [unitystation/unitystation#3036]
# Issue Template

## Description
Wall mounts override each others coordinates when on same tile

### Detailed Bug Report
Attempting to place two switches onto the same tile will cause both to overlap onto each other, this makes it very annoying when wanting to place multiple wallmounts onto the same tile.

![Unity_XQk1GytlaF](https://user-images.githubusercontent.com/44679539/74213118-65b12880-4c5d-11ea-88b1-d35e5d710033.png)
![Unity_Ec6eBtLPNE](https://user-images.githubusercontent.com/44679539/74213119-6649bf00-4c5d-11ea-9603-71cba7c34921.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Place two Wallmounts onto same tile
2.  Move one off the others sprite but still staying on the tile
3.  Test run
4. Get annoyed that the sprites move

**Comment by Misterixmax** [comment]
This is not only about wallmounts. In original game there was possible to configure the pos offset of every object on a tile. If it was moved too far from initial tile - it snaps to another tile. We need such system.
