### ISSUE TITLE
Handcuff icons stay even after death

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#3039]
# Issue Template

## Description
![image](https://user-images.githubusercontent.com/19640077/74216498-84adbb80-4c59-11ea-9be6-ebdf4791e70a.png)

### Detailed Bug Report
It helps if you include any relevant DM code / config (for describing how new features should work), images, gifs, or youtube videos!

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Get handcuffed
2.  Die
3.

**Comment by daalta** [comment]
Related: https://github.com/unitystation/unitystation/issues/2993
