### ISSUE TITLE
Helmets disappear if you try to pick them off a rack 

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#3041]
# Issue Template

## Description

![ezgif-6-e5d8467668d5](https://user-images.githubusercontent.com/19640077/74218050-0acc0100-4c5e-11ea-8acf-8b5ca3db29b6.gif)

### Detailed Bug Report
It helps if you include any relevant DM code / config (for describing how new features should work), images, gifs, or youtube videos!

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Try to take a helmet off a rack

**Comment by StrikS** [comment]
update: no helmets at all. All closets are empty. Ger1

**Comment by Misterixmax** [comment]
Right now only 2 places on a station have helmets. They are on a racks where two shuttles docked. No helmets in eva closets at all. Syndies all good.

**Comment by JesterX666** [comment]
Not happening anymore on version 4020.
