### ISSUE TITLE
Space wind can glitch items back and forth Making a meat grinder that Instantly kills

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3043]
Stuff like doors to different pressurised rooms, the items next seem to glitch out going back and forth, fixing this is very much needed since it kills a lot of people unnecessarily

**Comment by daalta** [comment]
Is this a duplicate of https://github.com/unitystation/unitystation/issues/2994 ?

**Comment by fomalsd** [comment]
yep
