### ISSUE TITLE
I can't throw stuff

### ISSUE THREAD

**Issue by Shrek69420** [unitystation/unitystation#3047]
# Issue Template

### Detailed Bug Report
What the title says, I can't throw stuff. I have throw binded and it doesn't work, neither does the throw button

### Steps to Reproduce
I don't know how to reproduce it.

**Comment by NoooneyDude** [comment]
I haven't heard of any players complaining about this issue on Discord, and it is not known how to reproduce it. Perhaps it has been fixed? It is also possible it was not known that you must click at the area you want to throw something at.
