### ISSUE TITLE
The Vote system can be manipulated

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3052]
How it happens Votes all count up instantaneously, 
TODO
Examine what could be the issue with The not  messages

**Comment by Bod9001** [comment]
Turns out not an issue

**Comment by Bod9001** [comment]
Still an issue

**Comment by Bod9001** [comment]
some other parts of it seemed to cause the text to get spammed, and the admin panel to break

**Comment by Alainx277** [comment]
CmdRegisterVote takes the user id from the client. Obviously somebody was going to abuse it, it's Unity after all.

**Comment by fomalsd** [comment]
oh, it's an obvious security hole. client can send whatever user id he wants in that cmd, and server will register it anyway. will be fixed soon
