### ISSUE TITLE
Botany Second Door Does not Open Automatically

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#3063]
# Issue Template

## Description
You can't open the botany second door by walking. You have to click the door.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Try to open the secondary botany door.
2.  You can't

**Comment by Misterixmax** [comment]
Already in issues #3031

**Comment by RedlineTriad** [comment]
Closing in favor of #3031.
