### ISSUE TITLE
Fire sometimes doesn't burn

### ISSUE THREAD

**Issue by qbit-0** [unitystation/unitystation#3064]
# Issue Template

## Description
Fire sometimes doesn't burn you.

### Detailed Bug Report
![Unitystation4013 2020 02 12 - 00 26 57 03](https://user-images.githubusercontent.com/19640077/74316755-002d6c80-4d2f-11ea-8006-5d7fb7424c54.gif)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Walk into fire

**Comment by ThatDan123** [comment]
Hasnt been reported recently, was probably caused when the atmos system lags but should be better now.
