### ISSUE TITLE
Shuttle RCS precision docking mode!

### ISSUE THREAD

**Issue by T-rexsuper1** [unitystation/unitystation#3070]
# What is wanted? 
A simple thing. Button in shuttle control interface, called "docking" pressing it will add four buttons. Up, down, left, right. Pressing them moves the ship one tile in said direction, very slowly, but steady, allowing you to position your ship the way you want. 
Russian versión.
Простая вещь. Кнопка в меню управления шаттла, названная "стыковка". Если её нажать, добавятся четыре кнопки. Вверх, вниз, влево, вправо. Нажатие каждой из них двигает корабль на один тайл в указанном направлении, позволяя удобно разместить корабль, например для стыковки.

**Comment by ghost** [comment]
Why not add the ability to pull the throttle stick backwards to reverse slowly, like in an automatic car?

**Comment by T-rexsuper1** [comment]
> Why not add the ability to pull the throttle stick backwards to reverse slowly, like in an automatic car?

A good feature, but strafes are still neccecary for docking

**Comment by Misterixmax** [comment]
Good thing, nice like Shuttle RCS precision docking mode

**Comment by ghost** [comment]
> > Why not add the ability to pull the throttle stick backwards to reverse slowly, like in an automatic car?
> 
> A good feature, but strafes are still neccecary for docking

Strafes are definitely not necessary, just memorize some coordinates, part of the game! I'll share some of mine: To dock with escape, Y=9, to dock with the emergency shuttle, Y=14....

**Comment by StrikS** [comment]
I see that only as upgrade module

**Comment by T-rexsuper1** [comment]
> I see that only as upgrade module

No, it's a neccecary thing for every shuttle.

**Comment by T-rexsuper1** [comment]
> > > Why not add the ability to pull the throttle stick backwards to reverse slowly, like in an automatic car?
> > 
> > 
> > A good feature, but strafes are still neccecary for docking
> 
> Strafes are definitely not necessary, just memorize some coordinates, part of the game! I'll share some of mine: To dock with escape, Y=9, to dock with the emergency shuttle, Y=14....

Yeah, sure, you can memorize stuff, but normal people want normal controls

**Comment by PerfectTangent** [comment]
this was satisfied by #5111
