### ISSUE TITLE
Make Unity Test Runner generate human-readable reports

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#3072]
## Description
Right now Unity Tests runs on a github actions CI. It works nice and smooth, but the generated report is non-human readable. It's NUnit3 .xml output that looks like this:
```
...    
<test-case id="1007" name="CheckChannelAndClearMessage(&quot;&quot;,None,&quot;&quot;)" fullname="Tests.ChatParseInputTests.CheckChannelAndClearMessage(&quot;&quot;,None,&quot;&quot;)" methodname="CheckChannelAndClearMessage" classname="Tests.ChatParseInputTests" runstate="Runnable" seed="1775714569" result="Passed" start-time="2020-02-10 21:38:55Z" end-time="2020-02-10 21:38:55Z" duration="0.000645" asserts="0">
<properties />
</test-case>
...
```

There are several way to implement this:

- Use third-party test reporter like Jenkins, Circle CI, Travis, etc. Sounds like overkill, because our current CI fit all needs, easy to setup and free.
- Use [Github Checks API](https://developer.github.com/v3/checks/) to generate report after actions execution. Sounds nice, but hard to implement ([example of Travis check report](https://github.com/Baystation12/Baystation12/runs/439813912))
- Generate .html by unity actions and download this as artifact. I really like this approach, fits nice to current CI. [Check this forum topic for more details.](https://forum.unity.com/threads/unity-test-runner-xml-report-to-html.826545/)

Feel free to write your idea and suggestions. I will make some research about how to run .NET apps in github actions environment.

**Comment by NoooneyDude** [comment]
Looks like that PR #3146 fixes this issue and so this should be closed.
