### ISSUE TITLE
Hub Station fails to update due to file in use on Windows

### ISSUE THREAD

**Issue by sirnuke** [unitystation/unitystation#3073]
## Description

Hub prompts for and downloads new release, but cannot apply it, presumably because the hub process does not terminate during the upgrade process.

### Detailed Bug Report

New release of the hub apparently got pushed out recently, and the hub prompts to update on start.  Download updates, command prompt window appears and prints an error.  Hub loads again and prompts for updating again.

```
"Updating hub please wait.."
Y
D:\Games\StationHub\StationHub.exe
The process cannot access the file because it is being used by another process.
Y
Access is denied.
        0 file(s) moved.
"Update complete."
```

Windows 10, btw.  Not sure how to get the hub version, but I downloaded not long after the public alpha was announced.

Seems there two issues:

- [ ] Hub process needs to terminate to allow the update to apply
- [ ] Updater needs to check exit code (?) and confirm it actually succeeded

**Comment by jamessimo** [comment]
Is this still an issue?

**Comment by sirnuke** [comment]
I admittedly haven't played or updated the game in a while, so I fired up the Station Hub app.  It updated from 926 to 930 without the permission issue (yay), but when trying to launch it I got:

    Error:
      An assembly specified in the application dependencies manifest (StationHub.deps.json) was not found:
        package: 'Avalonia.Controls.DataGrid', version: '0.10.6'
        path: './Avalonia.Controls.DataGrid.dll'

So not this error, but we're still not there yet.  I guess you can mark it as closed?

**Comment by sirnuke** [comment]
Actually going to mark this as closed, since https://github.com/unitystation/stationhub/issues/127 is a more relevant bug report
