### ISSUE TITLE
input focus isn't properly deregistered when dragged away from command console

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3075]
results in you not being able to do anything
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  open command console type in something
2.  get another player to drag you away so it disappears
3.  oobbserved lack of input

**Comment by NoooneyDude** [comment]
Couldn't reproduce. It seems similar to #4077, which was fixed by #4264.

**Comment by vlandemart** [comment]
True, this was fixed in #4264
