### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#3078]
I'm not touching Discord, that shit is spyware

So lads please unban my account woross from GER since all I did was kill one catgirl which is a big damn deal in an environment where you get a shuttle ram or plasma fire every 10 minutes

Banned by Doobly boy

**Comment by DooblyNoobly** [comment]
You were shitting up the LRP and MRP servers. I only gave you a 4 hour ban. Maybe you should just stick to USA01 where there are no rules

**Comment by ghost** [comment]
who's gonna ban the lads who burn plasma roundstart every round

**Comment by ghost** [comment]
Oh hell yeah this is the 1000th closed issue in this repo, nice nice!

**Comment by DooblyNoobly** [comment]
I'm working on the plasma issues today
