### ISSUE TITLE
Extinguisher water can pass through windows

### ISSUE THREAD

**Issue by UristMcRilo** [unitystation/unitystation#3080]
### Detailed Bug Report
I was playing as Janitor cleaning the hall near the cells using an extinguisher (the ultimate cleaning tool), when I noticed that the inside of the cell got water on the floor too, I tried on the next cell and I noticed that the water from the extinguisher can pass throught the glass and wet the floor inside

### Steps to Reproduce

1.Acquire an Extinguisher  
2. go to the hall near the cells 
3.try to use the extinguisher on the direction of the cell
4. Profit(?)

**Comment by fomalsd** [comment]
not just extinguisher, spray too.
not just windows, walls as well
