### ISSUE TITLE
Admin tool improvements and start of AutoMod B: 350

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3083]
There is a serious need to improve all of the admin tooling. Here is the criteria for the next upgrade of the system:

# Critera:
- Begin the foundation for AutoMod an optional service that server owners can run by adding a config with togglable features
- Implement Auto Protection for nefarious attacks through AutoMod
- Implement auto ban for spamming through AutoMod
- Implement auto ban for forbidden words through AutoMod
- Add admin notifications. Allow automod to send notifications to all admins
- Allow server admins to turn off automod if they want too
- Allow options of automod to be togglable via config
- Add the first AutoMod notification. The RDMing notification. Which will alert admins when someone RDMs without being an antag
- Add the second AutoMod notification. The plasma release notification which will alert admins of players opening a plasma canister without it being attached to anything and only if they are a non antag
- Allow ghosts to teleport and follow other players (this will help admins to monitor the game)
- Add the option to teleport to a notification event

**Comment by Bod9001** [comment]
You could use something like logger.admin. 
For the AutoMod notification.

**Comment by Scorr** [comment]
I agree with the others, but I think the punishment for spam protection and forbidden words should be resolved through the chat system (e.g. dropping those messages or censoring), rather than auto banning.

**Comment by ThatDan123** [comment]
Just as a side note, Admins should be able to veto vote banning people.

**Comment by DooblyNoobly** [comment]
> 
> 
> I agree with the others, but I think the punishment for spam protection and forbidden words should be resolved through the chat system (e.g. dropping those messages or censoring), rather than auto banning.

yep I'll do that instead

**Comment by DooblyNoobly** [comment]
> 
> 
> Just as a side note, Admins should be able to veto vote banning people.

vote banning was dropped as a lot of people objected to it

**Comment by DooblyNoobly** [comment]
splitting 50 of this bounty to ThatDaniel for completing the teleport feature in: #3723. Will pay it out when this issue is closed

**Comment by DooblyNoobly** [comment]
All criteria is completed. Will probably need to follow up with some smaller jobs to improve other areas of admin tools
