### ISSUE TITLE
You should not be able to punch out windows with your bare hands

### ISSUE THREAD

**Issue by Ranzarth** [unitystation/unitystation#3086]
### Description

You should not be able to punch out windows with your bare hands.

### Detailed Bug Report 

![](https://i.imgur.com/QqR8MWx.gif)

### Steps to Reproduce

1.  Approach a window menacingly 
2.  Show that window whos boss
3.  Notice that you have hands of steel

**Comment by JesterX666** [comment]
You can't do that in /tg ?

**Comment by Ranzarth** [comment]
Nope, not even on the weakest window type
