### ISSUE TITLE
Be able to tell if item is going out of players core inventory on client

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3089]
I mean core inventory as in The slots that are part of the UI, since currently there is no way to tell client if this object is going into a backpack

**Comment by fomalsd** [comment]
so basically an inventory slot event listener?

**Comment by NoooneyDude** [comment]
I think `IClientInventoryMove` interface handles that. Should we close this issue?

Edit: it seems `ClientInventoryMove` does not provide as much information as `ServerInventoryMove`.

**Comment by corp-0** [comment]
it works for that purpose but you know what? A wrapper for the logic we do to test that would be cool, a single bool we can consult.

**Comment by PerfectTangent** [comment]
@Bod9001 is this issue still relevant?
