### ISSUE TITLE
Can't start a game in Unitystation.exe (Possible missing Scripts in Instalation.)

### ISSUE THREAD

**Issue by ALE199** [unitystation/unitystation#3093]
## Description
Maybe its just me but for some reason I don't come with all the files, from what the Console says I'm missing referance scripts behavior on variety of game objects, the objects being:
BentPipe
Connector
FourWayManifold
Manifold
Meter
Pipe

I already have an Account and I'm using Win 7 if that helps.
### Detailed Bug Report
![help](https://user-images.githubusercontent.com/54281175/74443793-1133c600-4e74-11ea-8f09-7679c13e88e3.PNG)

### Steps to Reproduce

1.  Start Unitystation. Exe
2.  See Console.

**Comment by fomalsd** [comment]
try launching game with a VPN on and see if it helps. you might have certain IPs/ports blocked

**Comment by ALE199** [comment]
Now it seems to working, (without using the VPN)
Strange I guess.
