### ISSUE TITLE
Update to 2019.3

### ISSUE THREAD

**Issue by Scorr** [unitystation/unitystation#3095]
Currently Unity 2019.3.1 is out. This has multiple benefits, such as:

* Skip domain reload (faster iteration times in editor)
* AssetDatabase V2, should speed up first time import, and faster platform switching, might improve build times on build server?
* Profiler improvements
* Allows us to add ECS (also possible right now but 2019.3 version has a lot of changes)
* Allows us to use UIElements for editor scripts (also possible right now but 2019.3 version has changes)
* New editor theme

I think we should switch when possible.

**Comment by Macoron** [comment]
- Skip domain reload doesn't work (thanks, Mirror). Also will cause a lot bugs with current codebase
- AssetDatabase V2 sounds neat, should try it. Import speedup would be great.
- I still against ECS in project, cause overhead, but yeah, 2019.3 made it much more usable

I also looking forward for new 2D lighting (available from 2019.3). It's my dream to try it out and see how well does it work. Also new pixel perfect camera worth a try.

**Comment by Scorr** [comment]
Ah, unfortunate about domain reload, that was my most looked forward to thing. :(

ECS is a good point for discussion, I agree that it adds a lot of maintenance overhead. Having two different architectures in the project that need to interact with eachother, but also being basically unmaintainable by people who have never worked with it, whereas monobehaviours are much simpler to understand.

I'm not sure wether it would be a net positive for this project. I wouldn't be the one to add it, and I understand if it won't be, but if unitystation leads do decide to add it to the project, I would use it because I personally prefer that style of programming.

I think the new 2D lighting is only supported by the universal render pipeline, but I could be wrong. Switching to that would be a big change because all shaders and materials would need to be changed. 

Pixel perfect camera might be good, it would get rid of sub-pixel movement (which I think is the case now), and we could lower render resolution to increase performance. It's possible to add this today from the package manager (it's labeled preview, but I don't think there are any significant changes, they just slapped a stable label on it in 2019.3).

**Comment by Jibbajabbafic** [comment]
Done in #3847
