### ISSUE TITLE
You can still open doors while handcuffed

### ISSUE THREAD

**Issue by Scorr** [unitystation/unitystation#3097]
To reproduce:
1. Handcuff yourself
2. Walk into a door you have access to
3. Door opens

Expected: Door does not open.

Handcuffs do appropriately prevent you from clicking a door to open with, it's just walking into doors that's handled differently.

**Comment by hecksadecimal** [comment]
I'm pretty sure this is the normal behavior in SS13 on many codebases. Doors will open for you if you have ID in your ID slot. To stop this you can drag their body onto yours (help intent), and nick their ID. Though it won't stop public-access doorways from being opened I think.

**Comment by Scorr** [comment]
I think you're right, thanks for letting me know. I don't know if /tg/ does let you click to open while cuffed, but I could imagine clicking = using hands so doesn't work but walking into = different type of action not involving hands.
