### ISSUE TITLE
Glass Crate will bug out Cargo Shuttle

### ISSUE THREAD

**Issue by nullAurelian** [unitystation/unitystation#3098]
## Description
Attempting to call the cargo shuttle from CentCom with a Glass Crate will bug out the shuttle, preventing it from returning to the station. The Glass Crate is not loaded. Send button becomes non-functional.

### Detailed Bug Report

![unknown](https://user-images.githubusercontent.com/23534649/74488355-9674a600-4e87-11ea-96af-c2e495e1a115.png)

### Steps to Reproduce

1.  Go to the Supply console
2.  Send shuttle to centcom
3.  Add Glass Crate to cart and checkout
4. Attempt to recall the Supply shuttle

**Comment by nullAurelian** [comment]
Further investigation showed that a crate spawned in the shuttle but was empty, presumably the Glass Crate.

**Comment by CodeKalias** [comment]
In file Assets/Scripts/UI/Cargo/CargoData.asset
Under Supplies>Engineering>Supplies>Glass Crate: Items is a 60 size array with no references to the glass gameobject
![image](https://user-images.githubusercontent.com/7896673/74596920-cbcaf080-504d-11ea-9961-1f5a1d9a08ce.png)
There are similar issues with other parts of the asset (such as the Security Officer Set of Uniforms having an entry with a missing object reference as well)

**Comment by CodeKalias** [comment]
Looking through the full lists, entries with missing references are
Uniform Sets > Janitor Set, Roboticist Set, Chief Engineer Set, Station Engineer Set, Atmospheric Technician Set, Head of Security Set, Security Officer Set, Warden Set
Engineering > Glass Crate
Everything else seems fine

The LogWarning at line 162 of CargoShuttle.cs will need to check that orderedItem isn't null before calling orderedItem.ExpensiveName() to prevent this exception killing the cargo shuttle in future.

**Comment by hecksadecimal** [comment]
I'm working on fixing up those missing references. 
Edit: Someone else is working on fixing CargoShuttle.cs, so I'll hold off on changing CargoData.asset for now.
