### ISSUE TITLE
Nuke is too easy to access.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3122]
## Description
Nuke is way too easy to get to.
### Detailed Bug Report

![Screen Shot 2020-02-15 at 3 20 03 AM](https://user-images.githubusercontent.com/40842973/74587330-fe211300-4fa5-11ea-9ceb-354d0c99edb3.png)
Getting nuke is trivial if you know what you're doing. Nukies have tools and can easily just deconstruct one wall, and blow nuke.
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Be nukie
2.  Go to point where there's only one wall between you and nuke.
3.  Deconstruct wall and you're in.

**Comment by fomalsd** [comment]
Deconstruction makes noise, I tried that once as a nukeop and sec moved the nuke elsewhere

**Comment by Uristthedorf** [comment]
> Deconstruction makes noise, I tried that once as a nukeop and sec moved the nuke elsewhere

Oh, I've done it twice and neither time did security put up any resistance.

**Comment by fomalsd** [comment]
hm, could ensure there are at least two reinforced walls then

**Comment by Ranzarth** [comment]
I will fix this
