### ISSUE TITLE
Server feature. Motd to every single client and other info.

### ISSUE THREAD

**Issue by Misterixmax** [unitystation/unitystation#3124]
We need a possibility for headless (dedicated) server to send many kinds of info about server, rules, community, changelogs, discord, patreon and so on to the;
 

- [ ] Chat, splitted to public type ones and private ones for every client.

- [ ] Info tab (in the up right corner of the ui there controls and stats are placed). For example for rules page or so, it may be done in some kind of Book or so, cause rules may include pics and etc.

- [ ] Links to sites and such, with rules, wiki, discord channel and such.

- [ ] Info for every single client at connect to server loading, in lobby or/and at job selection.

Of course it needs to be configurable and hooked to external txt, html files or something like that.

**Comment by ThatDan123** [comment]
Partially done in #4541.
