### ISSUE TITLE
Infinite floor tiles

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3129]
Experienced a situation on EU LRP 4019 when picked up floor tile never got removed from my inventory when using it on the floor.
No related exceptions were found in the log.
![infitiles](https://user-images.githubusercontent.com/10403536/74595330-14d07400-5051-11ea-80e2-f60af4b0127d.gif)

**Comment by Necromunger** [comment]
On the PlacableTile script, it now has an ItemCost value.

I have defined this value for all necessary Prefabs but the variable keeps becoming unset x number of builds later.

Doing pull release again soon with meta files defining Item Cost for wood FloorTile's.

Metal floors should be fixed already on develop.
