### ISSUE TITLE
Dead players can run horizontally on very rare occasions

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3130]
I witnessed such player once and heard mentions about it twice, seems like a very rare bug. Horizontal player moved with running speed.
"I died and yet I could control my body, floating around but bumping into walls/glass"

**Comment by fomalsd** [comment]
got some footage: https://youtu.be/WnbggLQuKF8?t=33
it's interesting that undead was eventually turned into a ghost by an asteroid

**Comment by PetMudstone** [comment]
Can anyone confirm that this still happens?

**Comment by PerfectTangent** [comment]
I experienced it exactly one time in early February when the game was very unstable. It's still a problem, just seems really rare.

**Comment by jamessimo** [comment]
Is this even possible with healthV2 now in? Can’t replicate it personally

**Comment by fomalsd** [comment]
I think this can be closed. Will reopen if someone reproduces this with healthV2 in
