### ISSUE TITLE
Hub executable does not launch for some users

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3131]
User Science Bear#2584 on our Discord Server reports that their installation of the Station Hub fails to launch entirely. StationHub.exe does not open and does not continue running in the task manager. They were eventually able to get it to work - but on a different Windows account.

@DooblyNoobly suspects that this might be a rare bug with [Avalonia](https://github.com/AvaloniaUI/Avalonia).

We are currently not aware of how to reproduce this issue.

They have attempted the following things, none of which succeeded:

* Restarting computer
* Reinstalling (On several different drives)
* Running as admin
* Running through CMD
* Attempting to locate through task manager
* Spam launching while simultaneously looking through task manager to see if it even appears (It doesn't)
* Redownloading the setup wizard
* No temp file to replace normal .exe (As shown in the #FAQ channel on discord)

**Comment by Uristthedorf** [comment]
I think I've had a similar issue on my mac. Sometimes after a while, like a few days, stationhub would just stop opening, and if I remember correctly it said it was missing an executable. I don't know what caused it, I've been able to fix it by reinstalling the game and restarting my computer. It has happened twice so far.

**Comment by fomalsd** [comment]
it randomly stopped working for me on mac today as well.
```
machine:~ user$ /Applications/StationHub ; exit;
Error:
  An assembly specified in the application dependencies manifest (StationHub.deps.json) was not found:
    package: 'Avalonia.Direct2D1', version: '0.9.2'
    path: 'lib/netstandard2.0/Avalonia.Direct2D1.dll'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by daalta** [comment]
I think the issues @Uristthedorf and @fomalsd might be related. But they're on a different operating system and actually show an error message. This is weird.

**Comment by DooblyNoobly** [comment]
related: https://github.com/AvaloniaUI/Avalonia/issues/3587

**Comment by DooblyNoobly** [comment]
looks like its related to the single exe build option: https://github.com/AvaloniaUI/Avalonia/issues/3587#issuecomment-588082922
