### ISSUE TITLE
click dragging affected by intent

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#3142]
When click dragging a container or a person, you are unable to perform the dragging action if you are on disarm or harm intent.

### Detailed Bug Report
The line itself preventing this is in mouseInputController.cs HOWEVER it was originally put there to curb the issue of click dragging something during intense moments. 

ss 13 does allow click dragging with all intents.

to meet both criteria, the mouseinputdrag could be given a slight delay to confirm between a click and a click and hold or some other solution

**Comment by NoooneyDude** [comment]
I couldn't reproduce this issue. Dragging on all intents is possible with items, objects (containers included) and other players.
