### ISSUE TITLE
(Clone) appearing in item name messing with cooking recipes

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#3158]
## Description
In #3101 , it was noticed that sometimes object names show up with (Clone) at the end. This is what Unity does to the game object name when we clone a game object, but it should not be getting used for game logic - we have ItemAttributes fields for defining the object name.

This required creating 2 versions of a recipe in RecipeManager - one for the (Clone) version as well as the non (Clone) version, otherwise the recipe would not work when the recipe item name was showing up with (Clone).

Investigate what is happening and fix this so that objects being cloned show up with their correct name and remove the duplicate recipe in RecipeManager. 

It might also be that our naming logic is already fine, it's just that RecipeManager was using the wrong field or method to read the item's name when putting it into the microwave. Ensure that RecipeManager uses the correct method so it is unaffected by (Clone) being in the game object name.

**Comment by NoooneyDude** [comment]
Cooking is done via `Cookable` component now.
