### ISSUE TITLE
Syndicate items shop.

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#3175]
Right now we are missing the most important part of any syndies arsenal the item shop.
The syndicate provides a shop for the up and coming traitor/operative to buy a selection of goodies that will help them complete their objectives.

1. first things first the [uplink](https://tgstation13.org/wiki/Syndicate_Items#Syndicate_Uplink) this allows the antag to access the shop by entering a specific code they are given at round start via pop up window or chat.  exact amounts of starting TC is up to the coder. the uplink should be open until specifically locked, and if someone else clicks the uplink while its unlocked it should show them the buy menu.

2. Where this uplink is should be selected in the character screen, a pen, PDA, or radio headset plus any other choices the maker of the uplink decides

3. A number of [traitorous items](https://tgstation13.org/wiki/Syndicate_Items) need to be made to populate this shop, the exact items to be added are up to the coder of the PR. with more powerful items costing more.

4. [Telecrystal items](https://tgstation13.org/wiki/Syndicate_Items#1_Raw_Telecrystal)need to be buy-able from the shop for equal cost to amount the TC item is worth. when you click you uplink with them they need to be added to your pool of TC.

5. Job specific traitor items also need to be supported, and only visible when you are that job

6. [Discount system ](https://tgstation13.org/wiki/Syndicate_Items#Discounts) that discounts a small selection of items randomly by 80-10% with deeper discounts being much rarer.

7. [Syndicate Surplus Crate](https://tgstation13.org/wiki/Syndicate_Items#Syndicate_Surplus_Crate)

8. [Bundle support](https://tgstation13.org/wiki/Syndicate_Items#Bundles_and_Telecrystals) 

9. Nuclear Operatives need to also get the shop.

10. Nuclear operatives should start with slightly more tc then a normal traitor. 25 by default and a additional 10 for every 10 people.

11. Nuclear Operatives also need a special section in the shop only they have access to.

**Comment by PetMudstone** [comment]
A couple of things in this list aren't quite finished yet.
