### ISSUE TITLE
Grown plants should be edible

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3181]
Currently grown plants are basically useless since they transform into seeds on activation and aren’t getting consumed. So botanists‘ purpose is questionable  at the moment.
Bananas should also leave peels when eaten!

**Comment by nullAurelian** [comment]
There is a bit of groundwork that would need to be done as well beforehand, primarily for how seeds are generated. At the moment if you click on a crop with your active hand you generate seeds for the crop. However this is also the same interaction that current foods like MeatSteak have for eating. 
So we have two options: 

1. Make a machine to extract seeds from the plants. This could be like how ore smelting works, crop in one end seeds out another using a dictionary.
2. Change how eating works to specify using the food on self. Maybe require mouth targeting?

**Comment by Auri3l** [comment]
Just a side note but it's called "edible" not "eatable". I suppose turning into seeds is a placeholder, should be easy to do if that part is in the bag.

**Comment by Tjarr737** [comment]
Currently seeds are all the same prefab with different PlantData (including graphics) slapped on them, with the PlantData also being inside the harvest.
Using a dictionary would therefore require more changes and I don't see the appeal - as you have to use the PlantData anyway to store the specific stats of the plant (i.e. after mutation).
There is already a nonfunctional seed extractor machine right next to botany, so I think it would be reasonable to use it (the necessary code may be extractable from GrownPlants and the InteractableMicrowave / Microwave (just without delay)).

**Comment by fomalsd** [comment]
still doesn't work as of build 4031

**Comment by fomalsd** [comment]
fixed now
