### ISSUE TITLE
Solar Panels non-functional

### ISSUE THREAD

**Issue by Eyilwrass** [unitystation/unitystation#3189]
# Issue Template

## Description
It appears that Solar Panels aren't working. Unsure if bug, or currently unimplemented feature. Issue raised for tracking purposes.

Would appreciate rough ETA on implementation timeline for Solar Panels as power source.

**Comment by Evan-R-Rogers** [comment]
Unimplemented feature. Would like this to be implemented soon, good suggestion.

**Comment by PerfectTangent** [comment]
closing in favor of #5256
