### ISSUE TITLE
RFC: Differentiated melee damage types

### ISSUE THREAD

**Issue by Tjarr737** [unitystation/unitystation#3198]
## Description
Inspired by #3086 (which may be solved with this).
The current resistance categories might be seen as somewhat questionable, especially in the realm of melee, where fists, swords and welders all get the same damage reduction.
Therefore it might be reasonable to split resistances into more categories, like for example fist/brute=blunt/cut/pierce for melee weapons (where a welder would probably use fire/laser).

This may be useful to inject a bit more strategy by making the choice of weapon more dependant on the situation, however it currently seems questionable, where there may be a sensible gap between resistances (apart from fists which may be completely resisted by tiles).

Alternatively/Simultaneously general damage thresholds (subtracted from damage before/after application of resistances) might also be a reasonable addition, especially for more solid objects (tiles, mechs, hardsuits).

## Preliminary implementation considerations
The needed AttackType for damage calculations may be derived from the original AttackType and the DamageType (with new damage types) to minimize effects on the deeper parts of the code, with many changes to Armor.cs and very small changes to Integrity.cs and TilemapDamage.cs. (a new damage type for fists would also necessitate a very small change to WeaponNetworkActions.cd, were DamageType.Brute is assigned to fist attacks).
This would of course mean, that all prefabs would need the new resistance types, but most do not have any resistances as of now (if any - I have to this point only seen, that the tiles have actual resistances).

Comments would be appreciated.

**Comment by daalta** [comment]
I like the idea, though we would deviate from tgstation quite a bit then.

**Comment by drneuris** [comment]
Dunno exactly if it helps or complicates things, but if you had a further logical layer in between, say a material, you could add one property and derive damage reductions from that.

**numbers ass-pulling ahead**
materials: glass | steel | plasteel
dr% to cut: 10  | 30 | 50
dr% to blunt: 0 | 20 | 30
dr% to fire: 20 | 20 | 50
dr% to pierce/bullet: 0 | 20 | 60

then a general modifier for things of same material but not combat oriented, say steel machinery doesn't reduce damage further but steel armor might. 

This way you don't need to go through all prefabs for balance, but you can balance out materials relative to each other then if necessary tweak further. 

Might be too much detail for spessmen tho. I think it depends much on a higher level design discussion of combat and complexity in general.

**Comment by Tjarr737** [comment]
@drneuris Not a bad Idea. That should easily be doable by making them child classes of Armor with fixed values. This would allow people to use premade materials or custom resistances on their prefabs.

**Comment by Tjarr737** [comment]
Closed due to inactivity.
