### ISSUE TITLE
Regression: Stuck in login screen after failing to connect to a server B: 30

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3201]
## Description

Attempting to connect to a server that does not exist leaves the player stranded in the main menu. They then have to quit the game.

This happens when the server is offline or the wrong IP was entered.

### Steps to Reproduce

1.  Enter a random IP into the main menu and try to connect
2.  The UI disappears and never re-appears. Stare at the clown. STARE.

**Comment by corp-0** [comment]
Since we're doing this. You also get stranded when you don't join any game, there is currently no way to exit the application on the main menu and you need to kill the proccess instead.

**Comment by AutumnNova** [comment]
just gonna add to that:
when a server restarts to update, you get thrown to the clown menu and get stuck on it until you kill proccess

**Comment by daalta** [comment]
@corp-0 Uh, really? That feel like something we should address too! 

Would you like to create a ticket? 😙
