### ISSUE TITLE
Headless is broken as of build 4021! 🚨

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3202]
## Description
All our servers are currently down. The exact issue is unknown, but we suspect that it's due to the new outpost map.

We've been investigating this issue for... uh... *some time* now, and our progress can be seen on our Discord. I've created this issue for posterity.

Users have reported that:
* The server becomes unresponsive as soon as the start round timer hits zero.
* They're able to spawn, but can't interact with doors and other objects

In either case the server continues to run and doesn't yield very helpful logs.

### Steps to Reproduce

1.  Host a headless server
2.  Join it
3.  Observe that it breaks! (Well, it continue to run, but yeah.)

**Comment by AutumnNova** [comment]
4. Cry as you suffer from unitystation withdrawals

**Comment by AutumnNova** [comment]
headless was working fine on version 4021 yesterday iirc

**Comment by daalta** [comment]
Should be **mostly** fixed as of https://github.com/unitystation/unitystation/pull/3208
