### ISSUE TITLE
Printers!

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3213]
As a lawyer I have no way to replicate my legal documents!

Printers keep telling me to put in more paper, but no quantitiy seems to suffice. It's a travesty.

Printing and document copying would make all paper-based professions much more playable.

**Comment by daalta** [comment]
I just realized that copying and pasting text into documents is also an option. Hmm.

**Comment by corp-0** [comment]
> I just realized that copying and pasting text into documents is also an option. Hmm.

But where is the fun on that.
