### ISSUE TITLE
Eating grown food via botany displays the wrong name

### ISSUE THREAD

**Issue by Raptorizer** [unitystation/unitystation#3226]
# Issue Template

## Description
Eating grown food via botany displays the wrong name
### Detailed Bug Report
The PlayerNetworkActions.cs files has this, on line 485, that prints out for chat when you eat anything
`Chat.AddActionMsgToChat(gameObject, $"You eat the {food.Item().ArticleName}.", $"{gameObject.Player().Name} eats the {food.Item().ArticleName}.");`

This works fine with all other foods EXCEPT botany grown food which pulls the name of the food from `_DefaultPlantData.plantData.Plantname` instead of `_DefaultPlantData.plantData.Name`

`

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Grow a seed
2.  Eat the produce
3.   Read the chat
4. You've eaten what grew out of the tray, not what grew out of the plant

**Comment by daalta** [comment]
Related PR: https://github.com/unitystation/unitystation/pull/3211

**Comment by corp-0** [comment]
this shouldn't be a thing now since we made produce be its own gameobject. Closing.
