### ISSUE TITLE
Refactor airlock prefabs

### ISSUE THREAD

**Issue by AutumnNova** [unitystation/unitystation#3235]
## Description
the current airlock prefabs are all independent prefabs, some having different component ordering
this should be changed so as to make it similar to the other prefabs, having a hierarchy of prefabs that add components

**Comment by Raptorizer** [comment]
~dibs!~

After taking a few stabs at this, I seem to not be understanding what needs to get done. my initial thought was to remake every single door prefab by having each be based on the Object prefab asset located in `Assets/Resources/Prefabs/Objects`.

But looking through each other folder and prefab asset in these folders makes me think that maybe those are intentionally made to be independent prefabs? Either way, until more info is told/found, i shall let another try their hand at it.

**Comment by PetMudstone** [comment]
I would like to take a look at this now that I've converted all the other doors to variants. Problem is that working with the airlock animator is a nightmare and apparently gives me migraines.
