### ISSUE TITLE
Uninstall airlocks

### ISSUE THREAD

**Issue by Snowy1237** [unitystation/unitystation#3255]
# Issue Template

### Detailed Report
We cant uninstall airlocks which is annoying when someone spams them and destroyng them takes a lot of time and not the RP way to do this

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Build an airlock 
2.  try to uninstall it
3.  realise you cant

**Comment by PerfectTangent** [comment]
Closing in favour of #5819.
