### ISSUE TITLE
Box Station issues mega-list B: 70

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3256]
**Here I will try to document all of the issues currently found on Box-Station**

- Unable to place objects on tables, all tables tested.

- Kitchen shutters do not ignore objects beneath them, unable to stay down.
![kitchen](https://user-images.githubusercontent.com/60525878/75016868-8ba2ae00-5451-11ea-8a40-8dd85021a4bf.png)

- This light switch in the hallway interacts with a light in surgery.
![swtich](https://user-images.githubusercontent.com/60525878/75016923-a70db900-5451-11ea-9148-485d2f6f1f53.png)

- While this light switch seemingly does nothing.
![nothing](https://user-images.githubusercontent.com/60525878/75016961-bf7dd380-5451-11ea-8032-9f2cad808fd2.png)

- Missing walls/windows in the chapel.
![walls](https://user-images.githubusercontent.com/60525878/75017007-d7edee00-5451-11ea-8e6b-7373a7c907b2.png)

- More missing walls in security
![walls2](https://user-images.githubusercontent.com/60525878/75017155-1683a880-5452-11ea-9a62-01f5707e3027.png)

- Cloners do not function correctly, seem to be static objects with no interactions. Unable to be opened and appears to already have someone inside of it.
![cloning](https://user-images.githubusercontent.com/60525878/75017088-f522bc80-5451-11ea-8963-5f56a1eaeacc.png)

- Second console in Captain's quarters as well as an empty locker. (Windoor being broken when placed vertically is already a known issue).
![console](https://user-images.githubusercontent.com/60525878/75017195-2ac7a580-5452-11ea-9148-4c22d216665a.png)

- No airlock door leading to this shuttle, only a frame.
![no door](https://user-images.githubusercontent.com/60525878/75017296-4f238200-5452-11ea-9839-8b7e6f4bbd6c.png)

- The _escapisn't_ shuttle, facing the wrong way.
![escapenot](https://user-images.githubusercontent.com/60525878/75017346-6e221400-5452-11ea-8ab9-367593a0fb8e.jpg)

**Comment by fomalsd** [comment]
I think shutters don't block interactions below them anyway, and it's a separate issue

**Comment by Evan-R-Rogers** [comment]
@fomalsd There is a box to check for them to ignore whatever is below them.

Also calling dibberoonies, (That means I'm fixing it)

**Comment by Evan-R-Rogers** [comment]
- The Cargo Shuttle will also be fairly inoperable, it will cause obvious issues when live.
![image](https://user-images.githubusercontent.com/60525878/75018843-7039a200-5455-11ea-8493-c73126716656.png)

Sorry, Daniel. Gonna have to rework cargo so it has more clearance.

**Comment by Evan-R-Rogers** [comment]
[Issue is fixed here!](https://github.com/unitystation/unitystation/pull/3262)
