### ISSUE TITLE
Botany plant tray sync issues with late joiners

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3258]
Joined as a botanist late in the round, none of the trays had any indication until I actually applied tools to them:
![gif](https://user-images.githubusercontent.com/10403536/75018023-21583080-5486-11ea-9b77-4aa4db8f247d.gif)

**Comment by ThatDan123** [comment]
Going to say this has been fixed with bods sprite networking stuff. But i'll double check before closing.
