### ISSUE TITLE
Add PDA and traitors uplink in it.

### ISSUE THREAD

**Issue by Destrolaric** [unitystation/unitystation#3264]
I think it's time to add one of the most most usefull thing by fellow spacemans. I am suggesting to make realization of traitor up-link too. 
*Functions of PDA*
*Send messages..
*Turn on flashlight.
*Crew Manifest.
*Traitor's up-*link.
(IF possible)The ability to add some functionality by inserting special chips.

**Comment by fomalsd** [comment]
Suggested approach – NetTab and layout like this:
![palm](https://user-images.githubusercontent.com/10403536/75033800-9be37900-54a3-11ea-91ae-f1382b58f83d.png)

**Comment by RedlineTriad** [comment]
Related: #3175

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Working on it, if anyone minds assigning me.

**Comment by DooblyNoobly** [comment]
@TheOneAndOnlyCreeperJoe check the Examples/ChatScroll scene to see the new chat scroll prefab in action. You can create one by going UI>GUI>ChatScroll when adding a new object. This should help with the mail screen

**Comment by DooblyNoobly** [comment]
also avoid making uimanager.prefab changes today. I should be finished with it soon

**Comment by RedlineTriad** [comment]
@TheOneAndOnlyCreeperJoe are you still working on this?

**Comment by Nukeuler123** [comment]
Can someone bother assigning me? Iv been allowed to take over development on the PDA and traitor uplink
