### ISSUE TITLE
Killing shutters.

### ISSUE THREAD

**Issue by Destrolaric** [unitystation/unitystation#3265]
# Issue Template
You can be smashed by closing shutter
## Description
They insta killing you! Beware them!
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
1.  Step under the shutter
2.  Press button to close it.
3.  Die

**Comment by Evan-R-Rogers** [comment]
This can be easily turned off via an option in the inspector when map-making. If this is a widespread heart ache then we can change it.

**Comment by Snowy1237** [comment]
I think it doesn't needed to be changed, dust do not be under shutters for very long

**Comment by daalta** [comment]
I think it's hilarious... And it's nice that it's a map making decision.

Instakill is probably **too** much though. Instead shutters closing could be made more obvious (warning lights / warnings on floor + an activation delay) or it needs to be less punishing!

Squish.

**Comment by ReiderJack** [comment]
![ShutterKill](https://user-images.githubusercontent.com/42844726/75104371-737d8b00-5619-11ea-8550-404158976307.gif)

**Comment by Ranzarth** [comment]
They should just deal less damage than instakill, closing shutters is still the main weapon of choice by chefs on graytides trying to jump the kitchen counter
