### ISSUE TITLE
Job preferences screen B: 140

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#3266]
Players should be able to setup their job preferences so that they can be assigned roles randomly at round start instead of everyone choosing from a list at the same time like we currently do.

Related to #3267 

Criteria:
- [x] Job preferences screen
- [x] Show all possible jobs
- [x] Allow choosing none, low, medium or high for each job
- [x] Only allow picking 1 high priority job
- [x] Show the already implemented job descriptions
- [x] Save preferences with current character settings
- [x] Add antagonist preferences screen too

**Comment by spessgamertv** [comment]
Should also include Antagonist role preference.

**Comment by Jibbajabbafic** [comment]
Added

**Comment by DooblyNoobly** [comment]
Bounty added for you Jibby so you can prioritize the job
