### ISSUE TITLE
Add more kinds of hardsuits/spacesuits.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3272]
Right now, there is only one kind of hardsuit that's available to crew, and it can hard to tell which department someone is from or if they have any authority if they are wearing a hardsuit.

So I think it would be a good idea to add more hardsuits/spacesuits. Maybe one for each head/captain, and one for each department? Not sure if every department needs one though.

They don't have to be functionally different yet, they just need to look different.

**Comment by AutumnNova** [comment]
afaik the plan is to use a palette system so we dont have a bunch of variations of the same sprite with just the color changed

**Comment by PetMudstone** [comment]
We could also port over the other spacesuits from tgstation such as the atmospherics, engineering, and security hardsuits as well as the EVA softsuit. In fact, department heads (including the Captain while excluding the Quartermaster and HoP) do indeed have unique hardsuits which are found in their offices.
