### ISSUE TITLE
Unable to create new tiles 

### ISSUE THREAD

**Issue by Raptorizer** [unitystation/unitystation#3281]
### Description
Adding any new assets into the tilemaps folder causes an error to be spammed everytime you move the new asset around the scene

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Right click in project folder
2.  Click `Tiles` -. `General`/`Floor`/`Wall`/`Window`/`Table`/`Object`/`Wall Mount`
3.  Click on newly created asset and add any new asset sprite to the `sprite sheet`
4. drag asset onto tile on tile palette
5. click tile and drag onto scene
6. watch as the scene spits out two errors every time you drag across a tile

Error:
```Error running GetTileData for new TileIndexOutOfRangeException: Index was outside the bounds of the array.
ConnectedTile.GetTileData (UnityEngine.Vector3Int position, UnityEngine.Tilemaps.ITilemap tilemap, UnityEngine.Tilemaps.TileData& tileData) (at Assets/Scripts/Tilemaps/Tiles/ConnectedTile.cs:115)

UnityEngine.Tilemaps.ITilemap:RefreshTile(Vector3Int)

BasicTile:RefreshTile(Vector3Int, ITilemap) (at Assets/Scripts/Tilemaps/Tiles/BasicTile.cs:115)

UnityEngine.Tilemaps.Tilemap:SetEditorPreviewTile(Vector3Int, TileBase)

Layer:SetPreviewTile(Vector3Int, LayerTile, Matrix4x4) (at Assets/Scripts/Tilemaps/Behaviours/Layers/Layer.cs:201)

MetaTileMap:SetPreviewTile(Vector3Int, LayerTile, Matrix4x4) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:481)

LevelBrushEditor:SetPreviewTile(MetaTileMap, Vector3Int, LayerTile) (at Assets/Scripts/Tilemaps/Editor/Brushes/LevelBrushEditor.cs:109)

LevelBrushEditor:PaintPreview(GridLayout, GameObject, Vector3Int) (at Assets/Scripts/Tilemaps/Editor/Brushes/LevelBrushEditor.cs:75)

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)```

**Comment by PerfectTangent** [comment]
Is this issue still relevant? I haven't heard any issues with adding new tiles in a very long time.

**Comment by PerfectTangent** [comment]
closing as this does not seem relevant any longer.
