### ISSUE TITLE
struggling out of cuffs  doesn't have a progress bar

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#3282]
struggle out of cuffs  observe lack of progress bar

**Comment by vladb99** [comment]
I would create the progress bar in `RestraintOverlay.ServerBeginUnCuffAttempt()` with
`StandardProgressAction.Create(new StandardProgressActionConfig(StandardProgressActionType.Uncuff), null)
					.ServerStartProgress(thisPlayerScript.gameObject.RegisterTile(), 30f, thisPlayerScript.gameObject);`
Now I'm not sure if this is the correct way to do it. I saw that when a player gets uncuffed by someone else, the progress bar gets created through `RequestUncuffMessage`. 
What would be the right way to do this?

**Comment by Akronymus-git** [comment]
I'll take a look on friday, if you aren't working on it anymore.
