### ISSUE TITLE
Display Server Name In-Game

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3292]
Players currently have no indication of what their current server is. We might want to display this information somerwhere, maybe on the pause screen.

The server name should be retrieved from ```ServerData.ServerStatus.cs``` and displayed somewhere. ~~Alternatively we could make the in-game name separate from ```ServerData.ServerStatus.cs``` and store it in a ```.txt``` file instead. I'm not sure which option is better.~~ nnaaaah.

**Comment by RedlineTriad** [comment]
I don't think the name should be different, that would just cause confusion and introduce unneeded complexity.

**Comment by daalta** [comment]
I agree, but it was more of an implementation question. `ServerData.ServerStatus.cs` is mostly for serving the Hub, so we may not want to use that data.

Though on second thought... I think that's the only option if we want the data to be accessible on Hub too!
