### ISSUE TITLE
Staging 4039 issues

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3317]
List them here

**Comment by AutumnNova** [comment]
- banana peel is not dropped from banana, banana plant stopped dropping bananas after a few harvests (had a go at fixing it, wasnt successful however)

- shoes are not rendered on your character on client and the captains shoes icon is green

- removing a grill with wirecutters no longer drops rods, worked previously in 4036 (fix to be merged)

the below were also in versions before 4039
eating food sometimes displays "you unwillingly eat <food item>" (apparently not a bug, TIL)

- cappuccino in an edible cup leaves a cup after consuming it (fix to be merged)

- putting a cutlet in a microwave will always give 3 cooked cutlets, no mater the amount of cutlets put into the microwave

**Comment by corp-0** [comment]
“You unwillingly eat” is not an issue. It displays that text when you eat without hunger.

**Comment by ReiderJack** [comment]
![NoRods](https://user-images.githubusercontent.com/42844726/75145979-1a8e1f80-570b-11ea-85aa-b6b940f3f9a9.gif)
Rods are not spawned when grille is wirecutted.

**Comment by ghost** [comment]
> ![NoRods](https://user-images.githubusercontent.com/42844726/75145979-1a8e1f80-570b-11ea-85aa-b6b940f3f9a9.gif)
> Rods are not spawned when grille is wirecutted.

Should also somehow get rid of the possibility to affect things diagonally when you can't go there

**Comment by Mazhavil** [comment]
Can't craft metal rods

**Comment by ReiderJack** [comment]
![LockerClosed2](https://user-images.githubusercontent.com/42844726/75160802-c182b380-572b-11ea-9a5c-9b7b942c5ad8.gif)

Can't open lockers

**Comment by DooblyNoobly** [comment]
Server NRE spamming that is causing all of the rubber banding: 
```
NullReferenceException: Object reference not set to an instance of an object
  at SpriteFunctions.CompleteSpriteSetup (SpriteSheetAndData textureAndData) [0x0002d] in /home/unitystation/UnityProject/Assets/Scripts/Sprite Handler/SpriteFunctions.cs:28 
  at ClothingV2.SetUpSheetForClothingData (ClothingData clothingData) [0x0002a] in /home/unitystation/UnityProject/Assets/Scripts/Clothing/ClothingV2.cs:151 
  at ClothingV2.TryInit () [0x00019] in /home/unitystation/UnityProject/Assets/Scripts/Clothing/ClothingV2.cs:76 
  at ClothingV2.Awake () [0x00025] in /home/unitystation/UnityProject/Assets/Scripts/Clothing/ClothingV2.cs:68 
```

**Comment by DooblyNoobly** [comment]
Lockers have an NRE on client:
![image](https://user-images.githubusercontent.com/20813925/75195706-2d096700-57a6-11ea-8049-6386b337eed1.png)

Not a dev build so don't have a line number

**Comment by DooblyNoobly** [comment]
Clothing also has an issue on client:

![image](https://user-images.githubusercontent.com/20813925/75195748-401c3700-57a6-11ea-8bd7-487566b204e2.png)

**Comment by AutumnNova** [comment]
ill have a pr up that fixes the grille/rod issue soon

**Comment by PetMudstone** [comment]
Genetics and Science Backpacks don't appear while equipped or held in hand.
Also, the Mime and Research Director have incorrect populator assets, which means they don't spawn with their unique backpacks.

**Comment by AutumnNova** [comment]
ill fix the populator stuff and give the genetics/science stuff a shot i guess

**Comment by PetMudstone** [comment]
i thought I fixed the populator and backpack sprite issue earlier today, but apparently only the changes to the mime populator and .png files for the genetics/science sprites went through. The Research Director populator and asset files pointing to sprites were apparently not changed properly.

**Comment by AutumnNova** [comment]
the assets are fine on my end, it was just the populator stuff that wasnt correct

**Comment by PetMudstone** [comment]
Did you check out the Genetics and Science backpacks? Are their sprites not broken on your end? Try spawning them in with admin tools.

**Comment by DooblyNoobly** [comment]
thanks to everyone who fixed up these issues
