### ISSUE TITLE
Make mime mute.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3319]
Mime shouldn't be capable of talking. Unless he uses the action system to disable his muteness. (Turning off muteness should be permanent and have consequences.)

**Comment by Evan-R-Rogers** [comment]
The mime ever talking, at least in TG, makes him lose his mime powers. I _do_ like this suggestion if he were not to have powers in US, however.

**Comment by SelectiveHouse** [comment]
I agree with Evan - think the Mime should be able to talk, but when he does he loses his powers immediately, need a good punishment message sent to the mine player though.

**Comment by fomalsd** [comment]
I'd suggest adding mime's invisible wall first, so that mime had something to lose

**Comment by braincrab** [comment]
mime talking in most servers makes him valid, I think that's a big enough consequence.

**Comment by NoooneyDude** [comment]
This was implemented by #4334 and so can be closed.
