### ISSUE TITLE
Add unity station to linux repositories

### ISSUE THREAD

**Issue by Destrolaric** [unitystation/unitystation#3323]
As a Linux user i prefer to have packages in my package manager. Because the unitystation is under GPL3 we can easily add it to linux package managers. It may invite more players from highly knowledged Linux community.

**Comment by ghost** [comment]
Isn't Unity itself proprietary

**Comment by RedlineTriad** [comment]
The question as always are, which repositories to support, and who knows how to do it.

**Comment by Zagamun** [comment]
I've added it to the AUR for Arch based systems. It's not on other repositories yet.
(https://aur.archlinux.org/packages/stationhub/)

**Comment by NoooneyDude** [comment]
Station Hub now exists on Flathub, too. https://flathub.org/apps/details/org.unitystation.StationHub

**Comment by MaxIsJoe** [comment]
Closed because we already support stationhub as a flatpack currently at https://flathub.org/apps/org.unitystation.StationHub and stationhub issues should be handled on https://github.com/unitystation/stationhub
