### ISSUE TITLE
Add neutral/good objectives for non-antags

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3341]
As the title says, non-antags could or should have neutral or even 'good' objectives such as:

- Make sure Ian boards the escape shuttle and gets out alive
- Grow x amount of y produce
- Create a virus that does x
- Never go hungry the entire round
- Kill the clown
- Convert every crew member to your religion (Chaplain, mainly)
- Steal all the pens on the station

Basically some filler objectives for the regular crew to do.

**Comment by corp-0** [comment]
>Kill the clown
>neutral
lol

**Comment by Evan-R-Rogers** [comment]
I did also say "good" in the title.

**Comment by alexheartnet** [comment]
Captain has to make sure that mining makes x amount of money
Destroy something on the station as a form of insurance fraud
Research has objective to keep non-research personell outside of the lab area
Assistants might be given objectives from other jobs, like finding a medkit and healing x amount of damage or serving as a test subject for research
CMO has to save runtime! Noticed that players keep trying to murder that poor cat

**Comment by RedlineTriad** [comment]
@alexheartnet Captain already has mining objectives.

**Comment by PerfectTangent** [comment]
completed by #6878
