### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by makuru-org** [unitystation/unitystation#3352]
i tried to update the launcher as it says and then it sayse  it can't because data got moved?

"Updating hub please wait.."
Y
C:\Program Files (x86)\StationHub\StationHub.exe
Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
Y
Zugriff verweigert
        0 Datei(en) verschoben.
"Update complete."

AND

[Launcher20200224_001.log](https://github.com/unitystation/unitystation/files/4251610/Launcher20200224_001.log)
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  download the latest version on the website
2.  start update

**Comment by makuru-org** [comment]
found work around:
Just cut the data of tmp paste it in dokuments and cut it again delete Unity stations data and paste

**Comment by RedlineTriad** [comment]
Closing since it seems to be solved.
