### ISSUE TITLE
Move chat bubbles to screen space canvas B: 70

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3356]
# Issue Template

Chat bubbles get occluded by FoV shroud and it is also hard to control their size. We need to find a way of moving the chat bubbles to the screen space canvas.

## Criteria:

- Make a chat bubble handler that will control a pool of chat bubble objects and the public methods used to spawn a chatbubble (this will allow chat bubbles to be used by not just humans but anything else that needs a chat bubble)
- Convert player worldspace positions to viewport positions and convincingly move the chat bubble so it follows the player
- Clean up chat bubbles when finished and return to the pool
- Make sure chat bubbles are the same size on all resolutions
- Test in MP

**Comment by daalta** [comment]
Yeah this should probably be done. Though I understand why the bubbles were directly attached to players (it's convenient).

> (this will allow chat bubbles to be used by not just humans but anything else that needs a chat bubble)

Yeah, we could show examine messages like we display chat messages, i.e. above the object. Wouldn't that be nice? 🙄

This also opens up the possibility of a single player showing multiple chat bubbles at the same time. This could be used to have bubbles slowly fade away, or to display them beneath each other when a player has sent several messages.
