### ISSUE TITLE
Finish & polish all job descriptions

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3362]
We have job descriptions for most of our jobs. But these still contain some errors and some jobs still lack a description.

See our progress here: https://docs.google.com/document/d/1ZYBtoh4tAWKykmbViitqhFMdmdLVpPHIN_y2MgsYzI4/edit

Last related PR: https://github.com/unitystation/unitystation/pull/3234

**Comment by corp-0** [comment]
To anyone who contributes to the descriptions. Try to don't modify the green ones unless it is truly necesarry. 

Check the state of the description and see if you can make one that hasn't been done yet (Mime and Chaplain at the moment of this comment).

**Comment by daalta** [comment]
Looks like most descriptions are OK. We'll continue updating them as required, it'll be an ongoing task.
