### ISSUE TITLE
Health doll updates can send you previous state instead of current one

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3381]
Damage two limbs.
Let someone heal the first one (you shouldn't see any updates),
Then let them fix the second one. You'll only get the update for the first one.
Most likely not reproducible locally, but it certainly is on live server.

User submitted image:
![img](https://user-images.githubusercontent.com/10403536/75426966-8f48a000-593d-11ea-96a2-c9fcca036658.png)

**Comment by PerfectTangent** [comment]
is this still a problem in new health and with the new UI?
