### ISSUE TITLE
Not stackable glass sheet with any intent.

### ISSUE THREAD

**Issue by ReiderJack** [unitystation/unitystation#3386]
![UnStackable](https://user-images.githubusercontent.com/42844726/75453638-40265d80-5985-11ea-93a5-bb22dd1128f5.gif)

**Comment by JesterX666** [comment]
I've seen this before.  It happened when someone accidentally removed all Stackable component "Stacks With" entries.  Might be the issue.

**Comment by Tjarr737** [comment]
Are we sure this issue still exists? Does this happen to all stacks of glass sheets? I couldn't reproduce it (in the editor).
(The stackable component of the glass sheets seems fine too.)

**Comment by AutumnNova** [comment]
it seems inconsistent

**Comment by ReiderJack** [comment]
![NotStacking](https://user-images.githubusercontent.com/42844726/75606028-cf548200-5af9-11ea-9ce0-6b89ace516f8.gif)
checked today on USA 3 server

**Comment by NoooneyDude** [comment]
This is probably no longer an issue since the old material prefabs have been deleted. Closing, but feel free to reopen if this is still an issue.
