### ISSUE TITLE
Windows Defender protection false positive?

### ISSUE THREAD

**Issue by Tarasus** [unitystation/unitystation#3392]
I have downloaded a hub setup from https://unitystation.org and got a windows defender warning message, telling me about virus threat coming from HubSetup.exe
I am running Win10 x64.

![image](https://user-images.githubusercontent.com/11211913/75486997-a67ba200-59be-11ea-9a44-307653b4dfdd.png)
The screenshot is in russian. It tells: 

> Windows system has protected your pc.
> SmartScreen filter of Windows Defender has prevented a launch of an unknown app, that can bring the system to a risk.
> App : HubSetup.exe
> Publisher: unknown.

### Steps to Reproduce

1.  Download HubSetup.exe from https://unitystation.org
2.  Double click it to launch

**Comment by RedlineTriad** [comment]
This is known, and we can't do much about it currently.
We will open source launcher soon hopefully, that way you can check it yourself.
For now I am closing this, but thanks for the report.
