### ISSUE TITLE
Gameplay Loops & Objectives: Slight revisions to current game modes and UI updates.

### ISSUE THREAD

**Issue by spessgamertv** [unitystation/unitystation#3393]
# Description
This is an idea to streamline rounds a little more by creating a bit more for players to do until departments receive more attention. I also include the need for an objective tracker on the UI.

I think giving players a bit more to do around antagonist game types allows for new players to experience an actual game-play loop that they can get better at and come back to each day feeling they have something to play. This, as opposed to spawning into an incomplete department, fiddling around with the limited features (if any at all) and then subsequently waiting for the round to end 20 minutes later or getting bwoinked/disciplined for RDM.

## Extended Rounds
It's no secret that extended rounds can become tedious and give way to self-proclaimed antagonists. For this reason I believe this game mode should be removed until more focus can be put on department interactions and station objectives that promote cooperation.

## Syndicate Rounds
At the moment, syndicate rounds feel they have a really good pace at which they complete their objectives. The only improvement I could see to be made to the syndicate round is to have the ship spawn in different locations around the map. This will also solve a rare issue of people farming the syndicate ship on non-syndicate rounds.

## Traitor Rounds
Station Traitor rounds could use a little more functionality. In this case I suggest assigning the number of traitors to be proportional to the number of players currently on the station. In accordance with balancing, a decent place to start seems like 1 traitor for every 10 people on the station. Average 2 or 3 traitors on any given day with 30 players online (which is a guestimate of the average from what I see day to day in the evenings). Once you pass 10 traitors randomly assign the next player traitor until you reach 2:18, 3:27 etc.

## Bonus: Xenomorph Waves
After a given time limit (can be selected randomly between say 7-15 minutes) begin multiple monster-closets of xenos around the station in spawn locations. Either we all die or we escape on the shuttle. This was an idea in conjunction with what admins already tend to do to help wrap up long winded games as well as providing a PVE gamemode.

## UI Updates
Additionally, there is a definite need for some sort of objective tracker for antagonists because once the chat rolls by there is no way for the antags to reference their objectives. Instead of posting objectives to the chat they should simply be pasted to the top of the UI (further implementation should see them added to the drop down menu in the top right corner.)

## Suggestions & Improvements:  

- [x] Removal of "Extended" game mode until departments are more feature complete to allow for more robust station objectives.
- [ ] Additional Spawn locations for Syndicate ship creates slight diversity for trajectory of approach and handles syndicate ship looting on non-Syndicate rounds.
- [x] Increase the number of traitors proportional to the number of players connected to the station during traitor rounds. 
- [ ] Implementation of antagonist objectives to the UI instead of the Chat Window
- [ ] BONUS: Xenomorph survival rounds for PVE encouraging players to work together.

**Comment by fomalsd** [comment]
Extended has been removed after build 4046;
Good idea about nuke ship pos randomisation;
Antag objectives could be moved to PDAs when they are implemented (#3264)

**Comment by PerfectTangent** [comment]
Extended has been removed. Nukie ship looting has been solved by not spawning the ship until nukies spawn. Traitors spawn proportionally to player population. the antag objectives still need to be moved out of the chat window, but there are two other issues that describe that problem and potential solutions; #4802 and #4303. The last point is probably best served by /tg/'s standard xenomorph or spider antags and admin events, so closing. If the last one still wants to be discussed, best to open a new issue for it.
