### ISSUE TITLE
Make players on Help intent able to swap places with pets.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#3398]
As the title says, players on Help intent should be able to swap places with pets like Ian or Runtime similar to how players can swap places with other players if both are on Help intent. I believe this would help avoid predicaments in which the Captain or HoP get trapped in their offices by a small dog.

**Comment by corp-0** [comment]
I believe this is already possible, isn't it?

**Comment by NoooneyDude** [comment]
The pets are now passable; you can stand on top of them.

**Comment by corp-0** [comment]
IM GONNA CLOOOOOSE
