### ISSUE TITLE
Red locker light init can be erratic

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3408]
See how red light is only present on one locker. Others have no red lights, but do show green if toggled
![img](https://user-images.githubusercontent.com/10403536/75556483-37da2b00-5a36-11ea-876a-f55198c3ae1c.png)

**Comment by Robustin** [comment]
I'm looking into this. Were the unlit lockers actually locked? Were you a late join?

**Comment by fomalsd** [comment]
reportedly yes, since toggling them showed a green light

**Comment by Robustin** [comment]
I figured it out. @Ranzarth added locker lights/lockability manually to the OutpostStation scene in #3355 and they weren't set up properly. My PR #3415 should fix them.

**Comment by Robustin** [comment]
The fix PR is now at #3467

**Comment by ReiderJack** [comment]
![Bug1](https://user-images.githubusercontent.com/42844726/80306145-24470880-87ca-11ea-93a3-7c686753e17a.PNG)
