### ISSUE TITLE
Shutters should have only one "Is Closed" field

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3432]
Both RegisterDoor and DoorController have a passable boolean. This causes big trouble if they aren't set to reflect the same value. There should be only one in RegisterDoor and DoorController should refer to it when initialising shutters
<img width="280" alt="duh" src="https://user-images.githubusercontent.com/10403536/75615365-aa8cf880-5b53-11ea-862a-0d20c3e524d1.png">

**Comment by DVanwart** [comment]
I'll put a PR in for this once my current one clears

**Comment by DVanwart** [comment]
I have this working overall, there are a few issues with the existing maps I'm noticing that'll need to get ironed out after this fix. Example is a single shutter at the SEC desk on outpost station starts in the wrong state.

![image](https://user-images.githubusercontent.com/17316823/75633349-65f87000-5bda-11ea-957e-34f171c51f2c.png)

I'll try and iron out any I notice
