### ISSUE TITLE
IAction Images are not displayed properly

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#3450]
![image](https://user-images.githubusercontent.com/56727168/75632272-6b61b480-5bf2-11ea-8550-60350dd48c32.png)

![image](https://user-images.githubusercontent.com/56727168/75632274-70266880-5bf2-11ea-9b0a-3b8c9f920987.png)

**Comment by fomalsd** [comment]
oh, so does cuffed one
<img width="1291" alt="Scr" src="https://user-images.githubusercontent.com/10403536/75632396-a7097800-5c0c-11ea-9a25-fff18348da86.png">
could you look into it @Bod9001?
