### ISSUE TITLE
Chat bubbles overlap (because they do not use the chat bubble queue)

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3452]
Our new chat bubble system does not use the previous chat bubble queue system (which displayed the player's most recent chat messages sequentially as chat bubbles). 

So players can now create **multiple chat bubbles,** which can **overlap** and make the text difficult to read.

# How to fix (suggestions)
* Re-Introduce / Fix the chat bubble queue system
* Make chat bubbles not obstruct each other by moving them up / left / right when a new bubble spawns

**Comment by DooblyNoobly** [comment]
yeah I was going to fix the queue thing last night but ran out of time. The queue is still on the chat bubble just need to find a way to feed it new strings.

**Comment by daalta** [comment]
Oh okay, I guess either one of us could fix this. Just gotta coordinate 🐬

**Comment by NoooneyDude** [comment]
Chat bubbles appear to queue now, so this issue can be closed.
