### ISSUE TITLE
On new map construction materials dissapear 

### ISSUE THREAD

**Issue by makuru-org** [unitystation/unitystation#3464]
On new map construction materials dissapear 

if you try to order construction materials / deconstruct walls the plates dissapear

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Play on version 4050

**Comment by AutumnNova** [comment]
its just an issue with 4050, its all fine on the staging server

**Comment by corp-0** [comment]
This issue can be closed since we have 4051 now and the problem is gone.

**Comment by corp-0** [comment]
Couldn’t pinpoint the actual pr, but this is solved in #3585
