### ISSUE TITLE
Suggestion: Reinforced walls that slow down shuttle ramming

### ISSUE THREAD

**Issue by vortex1942** [unitystation/unitystation#3471]
Currently it is very easy for a nukie to ram a shuttle into the nuke, To remove the doorways and then just fly in the activate it

My suggestion would be to add a Reinforced wall which negates damage done by shuttles to Key areas such as Ai Core, And Nuke room

**Comment by AutumnNova** [comment]
we have reinforced walls

**Comment by daalta** [comment]
Do the reinforced walls slow down the shuttle more than other walls?

**Comment by vortex1942** [comment]
I'm not sure, But that is what i was suggesting.

**Comment by daalta** [comment]
Thanks for clarifying!

**Comment by PerfectTangent** [comment]
this is basically the same idea as #2912. Both are about rebalancing the hardness of walls, whether rwalls, shuttle walls, or whatever. Closing in favour of that issue.
