### ISSUE TITLE
Restraint wait time is hard-coded

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3476]
## Description

It's currently not possible do change the resist time of individual restraints.

(Resist time describes the amount of time it would take to remove the restraints without another player's help)

### Detailed Bug Report
The restraint overlay has a hard coded value for how long it takes to remove restraints. This value is 30 seconds.
https://github.com/unitystation/unitystation/blob/c9917dfa29ef820868cdd850f37c3a01e1209fa5/UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs#L92

But restraints have their own variable for how long this should take.  (Currently this value defaults to 0, which should be explicit. E.g. `= 30;`)

https://github.com/unitystation/unitystation/blob/c9917dfa29ef820868cdd850f37c3a01e1209fa5/UnityProject/Assets/Scripts/Items/Others/Restraint.cs#L31

The restraint overlay should use the restraint's resist time instead of a hard-coded value.

**Comment by svakam** [comment]
I will work on this with a friend

**Comment by Akronymus-git** [comment]
@svakam Are you still working on it?

**Comment by RedlineTriad** [comment]
@svakam If you don't respond in 24 hours I will give @ChristophGra the go-ahead for working on it.
If you are working on it, please respond.

**Comment by daalta** [comment]
Here's some feedback we received about handcuffs (via our [server website](https://sites.google.com/view/unitystation-server-rules/home)). Might be related to this issue.

> handcuffs are a tad bit broke. I can never seem to break out of them, even when I waited a straight 2 minutes clicking every 45 seconds or so. The progress bar didn't show up if there were. There were also no chat messages other than 'you are attempting to break free of your cuffs' or something like that. Thanks!

**Comment by RedlineTriad** [comment]
@ChristophGra you are good to go.

**Comment by Akronymus-git** [comment]
Gonna give up on this for now.

**Comment by Jorge1o1** [comment]
Taking a crack at this, pls assign
