### ISSUE TITLE
Shuttle safety system is inconsistant

### ISSUE THREAD

**Issue by DVanwart** [unitystation/unitystation#3486]
# Shuttle safety system is inconsistent

## Description
Shuttles with Safety on are able to ram when the server is laggy or when they travel fast enough

### Detailed Bug Report
UpdateMe() is used to call the sensor collision detection, when the server is overloaded this allows enough time to pass between updates for the shuttle to crash
I'm putting together a PR to move the check to FixedUpdateMe() so Shuttles should behave the same regardless of the server state.

Sensor placement on the shuttles is also an issue, the current mining shuttle on Outpost station allows the shuttle shear off it's sides without tripping the sensors.

![Shuttle](https://user-images.githubusercontent.com/17316823/75928594-21244180-5e45-11ea-9b33-102a98df5e61.png)
Red Xs are current sensors, allowing sides to strike objects
If those were replaced with 3 sensors at the green Xs that would block that issue while still preventing the shuttle from ramming head on into a docking beam (A mistake I made in testing 😄)

### Steps to Reproduce

1.  Take Mining shuttle
2.  Set Speed to max
3.  Hit Start
4. Turn Around
5. Repeat Step 3-4 until safety fails

**Comment by AtnerNT** [comment]
This has been fixed for a long time I believe, unless it was reintroduced with new shuttle movement.

**Comment by MaxIsJoe** [comment]
Can confirm. 
This has been fixed when Bod introduced tile chunks.
