### ISSUE TITLE
Botany is broken

### ISSUE THREAD

**Issue by AutumnNova** [unitystation/unitystation#3494]
A list of issues with botany
Sometimes plants will not drop any produce what-so-ever
Sometimes they will drop things they are not supposed to (ex: other plants, metal rods)
They display the incorrect name upon consumption 
Sprites will sometimes flicker rapidly or show an incorrect state (ex: not displaying ready to harvest sprite when you can still havest them)
Plants cannot be replanted properly using their produce, the item is used up, but nothing is planted
Plants cannot be told to drop a different item, this will introduce issues when implementing the gatfruit (drops a gun)
Bucket will sometimes deposit more liquid then it is holding and display NaN as its currently held units of liquid. Upon using the bucket on a Hydroponics tray, they tray will begin to display NaN units of liquid held
During the next round the hydroponics trays will produce things they are not supposed to or not produce anything at all (ex: seeds of plants that were planted in that tray last round)
Plants will sometimes not grow past their first stage
Plants will sometimes stop producing anything after their second or third harvest
(thanks to memesalt on the discord for testing and finding some of these)
After 3 rounds, botany seems to break entirely
Weeds are grown in hydroponics trays all at the same time

**Comment by SalmonidJester** [comment]
The way seeds work right now has some shit code, mutations are basically permanent across ALL seeds it originated from, basically replacing all seeds with that type, and even existing ACROSS rounds

-To replicate, head on a server, plant bananas since they are one of the more stable plants, wait for them to mutate, watch as they all magically mutate at the same time, restart the round and be more confused on why all the banana seeds are still the mutated type

**Comment by DVanwart** [comment]
# Progress So Far
I've realized it's not 4:30 AM and I need to stop so here's where things stand, comment more issues and I'll tag them on as I go.

## Replicated Issues
- [x] Lots of cases where the client wasn't seeing the correct state of the tray/plant
- [x] Sprites will sometimes flicker rapidly or show an incorrect state (ex: not displaying ready to harvest sprite when you can still havest them)
- [x] Plants cannot be replanted properly using their produce, the item is used up, but nothing is planted
    _- This was setup to add nutriment to the tray rather than act as seeds, I've changed it but left the code commented for when the seed machine works_
- [x] Sometimes plants will not drop any produce what-so-ever
    _- This is intended by mutations, mutation changes should make this less likely however_
- [x] Mutated plant keeps original sprites for client
- [x] GeneratePlantSOs is broken
## Need to be Replicated
#### Checked ones that seem to be fixed but haven't been able to confirm

- [x] During the next round the hydroponics trays will produce things they are not supposed to or not produce anything at all (ex: seeds of plants that were planted in that tray last round)
- [x] Plants will sometimes not grow past their first stage
- [x] Plants will sometimes stop producing anything after their second or third harvest
- [x] Sometimes they will drop things they are not supposed to (ex: other plants, metal rods)
- [x] After 3 rounds, botany seems to break entirely
- [ ] Weeds are grown in hydroponics trays all at the same time
- [ ] Bucket will sometimes deposit more liquid then it is holding and display NaN as its currently held units of liquid. Upon using the bucket on a Hydroponics tray, they tray will begin to display NaN units of liquid held -
    _-  There should probably be a general NaN issue to look into these_
- [x] Produce displays a incorrect name upon consumption

## Other
- Plants mutate and prefer to mutate better stats, stats with a max of 10 however didn't work with that logic and always rounded up or down one. All mutation stats have been moved to a max of 100
- Plants cannot be told to drop a different item, this will introduce issues when implementing the gatfruit (drops a gun) 
   - Maybe split is off into it's own issue so it's more visible as a feature request?
