### ISSUE TITLE
Feature: Make The Dead Useful

### ISSUE THREAD

**Issue by Mycah142** [unitystation/unitystation#3496]
SO, deadrones

Robotics has printer.

Take engineering items like Steel, Reinforced, Wires, and Glass, possibly minerals miners can find.

Place these items on the ground over the printer (similar to Mineral refiner). Clicking printer with Assist Intent brings up a crafting menu (like construction in hand).

Crafting menu has... Four parts it can print, which only show depending on the Supply it feeds from (like hand construction).

Parts are:
Circuitry (wires)
Structure (reinforced)
Mobility (Steel)
Optics (glass)

These parts can be put together to make basic drone bodies in a way similar to de/construction Engineers do on the ground/table. Maybe an automated arm later.

Then, to give it a purpose, the drone is given either a Tool Belt, or a Mop, shit like that, to finish it.

Once finished, it can be activated with a right click hold menu, as an NPC. It can be pulled while deactivated.

If wanted, a pAI can be crafted from one of each material, maybe even 1 hardened plasma. When crafting it, the roboticist can select 1 dead IC name from the dead list. It can be inserted to let that player control the bot. (Cloning exists, so dead-to-entity exists).

Precaution: Anyone that isn't an assistant or Syndicate can deactivate the drone with a click.
OR: Robotics gets a console they can have killswitches in, for individual or all drones. Also, a comms method to ping all drone types or all drones with a message.
Drones cannot talk outside of their own chat, like Dead Chat but for bots. This Chat can be seen and spoken into by the living via the Killswitch console.

Thoughts? Once this discussion reaches an agreement on how it'll work, I will put an alright bounty on it.

Written on my cell, posted via mobile browser. Have mercy.

**Comment by Evan-R-Rogers** [comment]
> Then, to give it a purpose, the drone is given either a Tool Belt, or a Mop, shit like that, to finish it.
- I _love_ this idea as it makes them more useful overall

> It can be pulled while deactivated.
- Should be pullable in any state like everything else

> Syndicate can deactivate the drone with a click.
- Maybe with an emag card they can? But the roboticist and AI should both have killswitches for the individual bots, I imagine in the other scenario a shitter would go around deliberately turning off the drones.

**Comment by Mycah142** [comment]
> > Then, to give it a purpose, the drone is given either a Tool Belt, or a Mop, shit like that, to finish it.
> 
> * I _love_ this idea as it makes them more useful overall
> 
> > It can be pulled while deactivated.
> 
> * Should be pullable in any state like everything else

Oh they will be, just currently, they can leave the pull like an uncuffed human.

**Comment by Mycah142** [comment]
> > Then, to give it a purpose, the drone is given either a Tool Belt, or a Mop, shit like that, to finish it.
> 
> * I _love_ this idea as it makes them more useful overall
> 
Well just having them run around again makes them bored. At least with a job, tools, and being barely more respected than Assistants, keeps them in line.

> > It can be pulled while deactivated.
> 
> * Should be pullable in any state like everything else
> 
Currently bots can escape a grab while active, like a normal player who isn't cuffed.

> > Syndicate can deactivate the drone with a click.
> 
> * Maybe with an emag card they can? But the roboticist and AI should both have killswitches for the individual bots, I imagine in the other scenario a shitter would go around deliberately turning off the drones.

There's always some asshole, fukken always. So the console can maybe give drone stats too? Not like alarms, but just click a drone or symbols to say it's Empty of fuel, deactivated, busy, and where it is?

Emag for syndicate on drones sounds ideal. They can still be shot or broken, of course, but Syndicate should be able to just deactivate them so it looks like just a shitter did it.

Also I apologise for the edits and shit. At work on cell, I can't see full comments or everything I'm typing at once. Hard to keep track.

**Comment by Mycah142** [comment]
Another limitation suggestion, for realism.

Cloning needs the body to record DNA to clone. That's reasonable. How can we argue that robotics can get pAI of players without some scanning or some shit?

I don't necessarily want to need bodies, or ID cards, as that would heavily limit which players can be brought back. Which is already the issue with cloning, where power or no body = bored ghost.

Could we rationalize an in-world excuse to already have personality scans of players? Or a quick like, gate, players can enter to record their personality to a database?

**Comment by corp-0** [comment]
normally, pAI's are absolutely  disconnected from the character the player was when alive. Player make a pAI profile with name and description of what kind of AI they are, roboticist download the AI from the ones avaible and installs it into the device.

Being a pAI is an opt-in thing, you need to create your profile and toggle the button to tell the system you want to be a pAI when ghosted.

**Comment by Mycah142** [comment]
I misinterpreted your post, my bad.

So a player can just have a pAI profile prebuilt for in-game realism.

**Comment by Mycah142** [comment]
> > normally,
> 
> We aren't the other stations. We can be our own thing. TG is the Base, not the end goal. But yeah the drones aren't the player, not IC. They're just a thing the dead can do to keep busy

**Comment by Mycah142** [comment]
So I was told that currently, the only hard stop is actually putting players into something other than the original/clone body they log in with.

**Comment by VernaSaurus** [comment]
I know this is a pretty old thing, but I've been seriously considering doing Drones for a while now.

**Comment by VernaSaurus** [comment]
You know what? Screw it, I'm making drones.

**Comment by NoooneyDude** [comment]
The new ghost role system introduced by #5675 should help facilitate these ideas.

**Comment by PerfectTangent** [comment]
The main objective of this issue has been satisfied with the ghost role system and the ghost roles that have been added thusfar. Drones and pAIs should be given their own issues.
