### ISSUE TITLE
Network: incorrect client's inventory on round restart [B: 10]

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#350]
On the round after the round client joins,
When client picks his job he appears to only have a unicloth (with a service texture) in the uniform slot, and nothing else.
![scr 2017-07-01 16 30 35](https://user-images.githubusercontent.com/10403536/27763214-b4781ba2-5e87-11e7-81e0-d788ec9b4308.PNG)
This **does not** affect server host.

**Comment by DooblyNoobly** [comment]
Very strange, the hier string and cloth type is not updating on the client when the item is constructed: 
![image](https://user-images.githubusercontent.com/20813925/27952317-300775fc-634b-11e7-919c-39530da98fa8.png)

**Comment by DooblyNoobly** [comment]
or is this normal behaviour?

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

    Fix it

Contributor will receive the bounty after merge (paypal)
