### ISSUE TITLE
Shooting object/player at 45 degrees deals no damage...

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#351]
...however another player's client might decide that it does:
[Player vs FuelTank](https://drive.google.com/file/d/0B8qFtM5MgWAdQjB0T1ZNY3pBQzg/view?usp=sharing)
[Player vs Player](https://drive.google.com/file/d/0B8qFtM5MgWAdell6M2lBQW5uZEU/view?usp=sharing)

**Comment by DooblyNoobly** [comment]
fixed
