### ISSUE TITLE
Round won't end bug

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3520]
# Issue Template

## Description
Round wouldn't end, shuttle was bugged or something? Then the station blew up, (the animation of station blowing up happened.) I was still able to fly around as ghost, and could see in the bottom of my screen the ingame map moving as I moved.
### Detailed Bug Report
It helps if you include any relevant DM code / config (for describing how new features should work), images, gifs, or youtube videos!
![Screen Shot 2020-03-07 at 12 06 07 PM](https://user-images.githubusercontent.com/40842973/76152766-7eec9f80-6078-11ea-8caa-895099191302.png)
Round was stuck like this.
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Bug shuttle?
2.  Destroy station?
3.  ?

**Comment by corp-0** [comment]
This was solved in #3542
