### ISSUE TITLE
Issue: Books R Bad

### ISSUE THREAD

**Issue by Mycah142** [unitystation/unitystation#3536]
So I wanted to dick around and be a lame fanfic writer for a round or two.

I've been copy-pasting shit from notecards to the game, to see what does or doesn't and whatnot.

But at the end of a round, I still had paper open. The beginning of the next round, I can pick my character (didn't try changing name), picked Curator, and now I'm stuck in the library only able to spin and click objects within immediate range. I cannot move, I cannot type.

It's as if I still have paper open capturing keyboard strokes, not letting me even change prefered intents or attack zones using keypresses. I can do so by clicking them though.

**Comment by Mycah142** [comment]
Update: Pressing F5 was able to open the console. I could type into it. Closing the console, I could move.

**Comment by PerfectTangent** [comment]
this sounds like another case of #4728 or #4254. perhaps this issue should be closed in favor of those ones.
