### ISSUE TITLE
Generate Plant SOs Bugs

### ISSUE THREAD

**Issue by DVanwart** [unitystation/unitystation#3540]
# Generate Plant SOs Bugs

## Description

It generates broken SOs that need to be manually combed though, re-linked to their seed packet, re-linked to their mutateInTo SOs and re-linked to any sprites that failed to load.

### Detailed Bug Report
1. GeneratePlantSOs.cs tool works only partially, the ScriptObjects it creates have broken references to the plant SO it should mutate to, results in "missing" in the inspector panel
    - Restarting unity after running the script might fix this?
2. Seed packets also might lose reference to generated plant SOs. This only happened the first time I ran the script
3. Many sprites aren't properly setup/named so they arn't loaded at all.
    - Bluespace banana trees's bananas exhibits this issue

### Steps to Reproduce
1.  Run Tools>GeneratePlantSOs
2.  Look though "ScriptableObjects>Plant default" folder SOs
3.  See some SOs have a MutateInTo with a count > 0 but "missing" for all entries
4. See some SOs not are missing sprites
5. Check SeedPackets and see seed packet SOs no longer have a valid plantData SO

**Comment by DVanwart** [comment]
Ok I think I found a real fix for the SOs references breaking, I'm going to see if I know how to fix the sprites otherwise I'm just going to push a PR and leave this issue open for someone else

**Comment by NoooneyDude** [comment]
I am not sure if this is still relevant anymore. That `GeneratePlantSOs` tool does not appear to exist.

**Comment by PerfectTangent** [comment]
Plants are prefabs now, so this issue in no longer relevant. Closing.
