### ISSUE TITLE
Suggestion: Mid-round Excitement

### ISSUE THREAD

**Issue by Mycah142** [unitystation/unitystation#3557]
So people get bored within 10 minutes, when Syndicate never shows up, or the traitor dies in space but no one knows.

So why not introduce mid-round traitors? Specifically traitors.

Y'know the ones. Three objectives, kill 1 dude, steal the declaration of independence, and then escape into fame.

Objectively speaking, they're a neutral antagonist type that is not naturally aligned to any game-mode antagnostic party. Syndicate's end goal is to blow up the station. Cargonia's goal is to be the only survivors on the shuttle.

Traitor needs to survive to the escape shuttle to 'win'.

So, traitor wouldn't naturally work with any other antagonistic party, at least not for any sort of long shot, Maybe take advantage of the confusion, but not -really- join.

**How it could be implemented:**
--- For Syndicate game mode, for the first five minutes, the normal "dice roll" selection process is done to have people join Syndicates, at random. After five minutes, anyone that would become syndicate, now just become a traitor.

--- For Cargonia, since there's no randomizing aspect for the team selection, the traitor would be a dice roll randomization as well, just no initial time limit. These traitors couldn't be part of Cargo/Supply.

With this change, it would give people a hope that maybe THEY will be the guy who can RDM and try to use "BUT I WAS TRAITOR" as a shit excuse. And some mid-round excitement.

**Comment by Evan-R-Rogers** [comment]
Along with this, it'd be pretty nice if admins could then give people custom objectives so if a round were to get boring, or even interesting, the admin could intervene to change that.

**Comment by NoooneyDude** [comment]
The new event system should help with this when more events are added.

**Comment by PerfectTangent** [comment]
This issue more or less has been completed with late joining traitors, the event system getting filled out, and ghost roles being added.
