### ISSUE TITLE
Fake walls don't appear fully closed on headless, also cover wallmounts

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#3572]
They never fully close which makes them quite obvious.
Also they cover wallmounts which I think isn't intended

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
1.  Go to any live server
2.  Build a fake wall

**Comment by fomalsd** [comment]
@Robustin could you look into this please?

**Comment by Robustin** [comment]
@fomalsd 

Sure thing. For the wall-closing, are you also seeing it close 3/4ths of the way? Or is it not even attempting to close for you?

For the wallmounts, I don't recall how /tg/ handled them, it might be possible that it was covered there too, which might require some new behavior on our end if we don't want false-walls covering them.

**Comment by fomalsd** [comment]
@Robustin everyone sees its closed state as 3/4ths of the way

**Comment by NoooneyDude** [comment]
While the fake walls now close all the way, they still don't connect with the neighbouring walls.

![fake wall](https://user-images.githubusercontent.com/6926225/88274382-b90cc400-cd2f-11ea-9ad3-14cd58f3e539.gif)

**Comment by AutumnNova** [comment]
not exactly what this issue is about, no?

**Comment by MaxIsJoe** [comment]
This has been fixed in #9911
