### ISSUE TITLE
if internet connection disconnects your player gets braindead

### ISSUE THREAD

**Issue by makuru-org** [unitystation/unitystation#3581]
If the internet connection (IC) Disconnects you get thrown in the player editor screen and you need to choose a new role and your old guy waits braindead

### Steps to Reproduce

Disconnect LAN cable and put it back on

**Comment by PetMudstone** [comment]
Oh dear, this sounds like the issue that several people faced today and yesterday.
To elaborate, sometimes you get randomly disconnected from a round and get booted to the main menu.
If you rejoin the round you got booted from, you will not reenter your character's body and will have to choose a new role. Notably, your first character will take up a slot in the role chosen for them. After you pick a new role, you will spawn in a new body. There will then be two of your character on the station. The first character will be braindead, yes.
The second instance of your character will have "2" added to the end of their name (for example, Colby Rose and Colby Rose2). Eventually, the server will recognize that your first character is not an actual player and will free up the slot that they were occupying.

**Comment by NoooneyDude** [comment]
Could successfully reproduce this.
1. Join server.
2. Disconnect client from internet and wait for error message.
4. Close client. Reconnect to internet.
5. Rejoin. Be prompted with character selection.

**Comment by corp-0** [comment]
closing in favour of #4031
