### ISSUE TITLE
Suggestion: Hardsuits and Disarming Tweaks

### ISSUE THREAD

**Issue by Mycah142** [unitystation/unitystation#3583]
Currently hardsuits give protection from temperatures, pressure. That's really it from a broad perspective.

I know there are now special hardsuits for jobs. This suggestion is PRIMARILY about Security/Syndicate/Combat Hardsuits and hardsuits in general.

All Hardsuits should:
---Movement Resistance. Meaning, walk/sprint slower, increase metabolism, be harder to shove, less affected by space wind. They're bulky, heavy carapace.

Security/Syndicate Hardsuits should:
---"Magnetic Gloves". An officer should not be as easily disarmed/floored by a shithead assistant with nothing but a backpack.

---Riot Gear should be borderline immune to disarming/shoving.

Disarming should:
---Be relative to the item you're trying to disarm with. Sec Hardsuits should have enough disarm resistance that unarmed assailants shouldn't knock the rod out of their hand. But a crowbar, fire extinguisher, and other hard hitting things, could. Just imagine that there is Damage and Armor, but it's another two variables directly related to Disarming.

---Should damage the disarmer if attempted bare handed and fail.

**Comment by slimaaconroy** [comment]
Mag gloves sound like a crutch item, if sec want to not get disarmed, they should work on their skills with the combat system.

The hardsuit changes sound good, but we might need to introduce a stamina system like on TG for that one

**Comment by NoooneyDude** [comment]
Hardsuits now cause the wearer to slow down, and magboots exist now.

**Comment by PerfectTangent** [comment]
Some ideas here have been integrated. I think the rest will be addressed by other systems and balance changes coming in health and a future rebalance of disarm. Closing.
