### ISSUE TITLE
Plants need food prefabs setup

### ISSUE THREAD

**Issue by DVanwart** [unitystation/unitystation#3588]
# Plants need food prefabs setup

## Description
This is mostly a reminder for me of what needs to be done, relates to PR #3587 so until that is merged this doesn't actually apply. I'll remove this issue if that PR doesn't work out.

Need to pull name/description/reagents from .dm files and create new prefab variant of `Assets/Resources/Prefabs/Items/Botany/food.prefab`
Add produce sprite and any other relevant data

If you add any of these, thanks! Just add a comment so I know not to do it twice. I'll check them off as I go

### Top Priority

- [ ] wheat_meat
- [ ] wheat_oat
- [ ] wheat_rice
- [ ] cherry
- [ ] cherry_blue
- [ ] cherry_bulb
- [x] gatfruit
- [ ] potato_sweet

### Second Priority

- [ ] cannabis_ultimate
- [ ] ambrosia_gaia
- [ ] apple_gold
- [ ] carrot_parsnip
- [ ] chili_ghost
- [ ] chili_ice
- [ ] coffee_robusta
- [ ] corn_snapcorn
- [ ] eggplant_eggy
- [ ] pumpkin_blumpkin
- [ ] tobacco_space
- [ ] watermelon_holy

### Other

- [ ] angel
- [ ] amanita
- [ ] chanter
- [ ] chanter_jupitercup
- [ ] cocoapod_bungotree
- [ ] cocoapod_vanillapod
- [ ] cotton
- [ ] cotton_durathread
- [ ] firelemon
- [ ] garlic
- [ ] glowshroom
- [ ] glowshroom_glowcap
- [ ] glowshroom_shadowshroom
- [ ] grape
- [ ] grape_green
- [ ] grass_carpet
- [ ] lemon
- [ ] liberty
- [ ] lime
- [ ] nettle
- [ ] nettle_death
- [ ] orange
- [ ] orange_3d
- [ ] pineapple
- [ ] plump
- [ ] plump_walkingmushroom
- [ ] poppy_lily_trumpet
- [ ] rainbow_bunch
- [ ] redbeet
- [ ] reishi
- [ ] soya
- [ ] soya_koi
- [ ] starthistle
- [ ] starthistle_corpse_flower
- [ ] sunflower
- [ ] sunflower_moonflower
- [ ] sunflower_novaflower

### Needs Other Features

- [ ] Grass
- [ ] Grass_Fairy
- [ ] bamboo
- [ ] replicapod
- [ ] kudzu
- [ ] random( ??)

**Comment by DVanwart** [comment]
I'm going to leave this until Redline has his chem changes in since adding all reagents again would be a pain

**Comment by NoooneyDude** [comment]
What's the status with this issue?

**Comment by corp-0** [comment]
I'd say we have all of those done now, if any is missing then someone can open a new issue with the specifics.
