### ISSUE TITLE
disguises don't really work.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3600]
If someone wears and mask and takes off their ID, so that when you mouse over them it says "unknown," it will still say the players real name in the chatlog whenever they do something, like attack someone.

It's also like this when someone wears someone else's ID.

**Comment by NoooneyDude** [comment]
Fixed by #5532 and #5774, though there may be a few stray cases where the true identity is incorrectly revealed. Best to open a new issue with the exact interactions, if discovered.
