### ISSUE TITLE
Feature: Whitelisting

### ISSUE THREAD

**Issue by hecksadecimal** [unitystation/unitystation#3614]
## Description

A config option and whitelist.txt similar in usage to admins.txt to allow a 'panic bunker'-like setup, where people must first be whitelisted before they're able to connect to the server. Being able to change this config through RCON while the a round is ongoing would also be nice. 

Bonus points if it were to allow for different modes. 
Examples:
Admins only - Only IDs defined in admins.txt can connect. 
Whitelist - IDs in admins.txt and whitelist.txt can connect. 
Off - No ID checking. 

By allowing only administrators on the server without having to completely change the current whitelist.txt, it would allow admins to set up events prior to other players joining for the round.

**Comment by ThatDan123** [comment]
Ive done most of that in #3666 

But not admins only explicitly though there is a way to do it:
The best way to do that with my system would be just to rename the whitelist file temporarily and put a dummy whitelist in with a couple of keyboard mashes, then only admins can join.

The whitelist will only activate if theres something in it. And should auto update during round if changed.
