### ISSUE TITLE
Fix player jobs count updating B: 20

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#363]
Make it update regularly

**Comment by DooblyNoobly** [comment]
Jobs will be used for their proper intention in 0.2.0 when we move away from DM. So will revisit then

**Comment by DooblyNoobly** [comment]
Criteria:

  - Make it update regularly

Bounty of 20usd will be awarded after a successful merge

**Comment by Em3rgencyLT** [comment]
Taking this
