### ISSUE TITLE
Server breaking bug, bag dupes B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3634]
Reported by Space Aussie and confirmed to break the server:

```
The server can break by a bag dupe shit thing.

The game already has code preventing boxes from entering boxes and the same for backpacks, but you can by past this if you place a bag into another bag the second it spawns in from a vendomat. 

IE not picking it up and triggering logic. So you now have infinite bags in a bag and the more you do it the more the server chugs... 

Someone else knows this and didn't report it. +I don't want to make a github account to spam email me.
```

**Comment by AutumnNova** [comment]
toolboxes can be placed in other toolboxes, same goes for cardboardboxes

**Comment by SeniorMeenal** [comment]
I have managed to recreate the issue in a custom server with two standard-red toolboxes. Nothing in the code suggests that it is bypassing any logic. It appears that boxes and toolboxes shouldn't be able to enter each other. The code doesn't encompass everything that can store items in other items. This is the problem as I see it for I can consistently crash the private server utilizing this method.

**Comment by DooblyNoobly** [comment]
> 
> 
> toolboxes can be placed in other toolboxes, same goes for cardboardboxes

yeah but that doesn't have anything to do with this bug. They are managing to place their backpack inside of a backpack that is coming out of the vendor by using an auto clicker to perform the Inventory interaction on the very first frame as it leaves the vendor. Real hard to recreate but I think it might be a good idea to implement a cool down in OnEnable before any interactions can take place.

**Comment by DooblyNoobly** [comment]
> 
> 
> I have managed to recreate the issue in a custom server with two standard-red toolboxes. Nothing in the code suggests that it is bypassing any logic. It appears that boxes and toolboxes shouldn't be able to enter each other. The code doesn't encompass everything that can store items in other items. This is the problem as I see it for I can consistently crash the private server utilizing this method.

ok this is new information. How can I easily recreate it? Do I need an auto clicker?

**Comment by SeniorMeenal** [comment]
I managed to recreate it manually with no auto clicker, it is possible to complete this is in the newest build as I executed it on a private server. Which should be the same version running on USA 01 MRP, It is very simple to trigger.
Just utilize multiple bags vended from the green machine, then drop all of the backpacks into that backpack vended by the machine. The only problem is that this worked by the second attempt. I assume that there is an artifact in the code that is separate from the logic that prevents bags from entering each other but only triggers randomly, depending on what's been done recently unrelated. I can recreate it but not consistently, more testing needs to be done. I'll run through the code later when I have spare time. Also, how much are the bounties?

**Comment by DooblyNoobly** [comment]
this is a 50 usd bounty, I'm already working on it tho but if I'm still stuck when you have spare time lets split it and work together

**Comment by SeniorMeenal** [comment]
Ok.

**Comment by DooblyNoobly** [comment]
`Just utilize multiple bags vended from the green machine, then drop all of the backpacks into that backpack vended by the machine.` I've been trying to do this for past 15minutes to no avail. Any more information you can provide as to how you dropped them in there? Did you vend a backpack and try to put another backpack in it as soon as it came out of the vending machine?

**Comment by SeniorMeenal** [comment]
Whoever gave you the information most likely was lying to you, or there was an error in communication somewhere. There isn't a problem relating to vendors or it being thrown. Only those items that store other items should not store themselves infinitely. The problem I assume your trying to describe is how boxes can be stored in other boxes when in backpacks. This can be done from the editor or manually. There is not a single problem with the vendors or anything that has to do with auto-clicking. There is no problem here, but for some reason, the server is crashing. I'm confused about what you were saying in your original statement.

**Comment by SeniorMeenal** [comment]
This has a simple fix, stop boxes from entering other boxes. That's the simplest fix. In order to stop the infinite box conundrum. The boxes in boxes problem should be coded out.
EDIT: there is no duplication, I may just be onto something. Preventing boxes from entering boxes may stop the dupe bug.

**Comment by DooblyNoobly** [comment]
hmm I'm still having trouble trying to recreate it. I stacked a whole bunch of boxes into one box but nothing. I'll do as you suggest and prevent boxes from being in boxes and we will test in next build

**Comment by SeniorMeenal** [comment]
There is no creation of new items, only moving items to storage in infinite capacity. More testing needs to be done to see if duplication can happen, but I believe that there is plenty of boxes placed in one another, potentially going on infinitely. This has been a meaningless quest that seems to have no end without testing. I retire hunting for my first few bounties here.
