### ISSUE TITLE
Door pressure system sometimes opens door while alerting

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#3645]
## Description
Sometimes, when pressing into an airlock that has a pressure difference, the airlock will open at the same time as it starts the alert. Seems to happen more if the server, or perhaps the client's connection, is lagging.

**Comment by PerfectTangent** [comment]
Is this issue still relevant?

**Comment by PerfectTangent** [comment]
do new doors have this problem?

**Comment by NoooneyDude** [comment]
I'm not sure. Can close this issue if you like.

**Comment by PerfectTangent** [comment]
going to close this for now since we've switched doors and the bug is likely not present.
