### ISSUE TITLE
Admins can’t see who is antag in cargonia/rebel rounds

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#3658]
According to what has been said in discord, admins can’t see who is antag in Cargonia/Rebel game mode, which makes hard for them to identify RDM.

**Comment by corp-0** [comment]
this may have been solved in one of Doobly's admin PRs. Can we get an admin to confirm?

**Comment by Evan-R-Rogers** [comment]
We can view antags, they are highlighted in yellow.

**Comment by Jibbajabbafic** [comment]
Fixed in #3703
