### ISSUE TITLE
Buildable essential items

### ISSUE THREAD

**Issue by ZeroMODE0** [unitystation/unitystation#3687]
Me and some friends were making a station on an empty server and ran into issues trying to make it lively.
We thought it'd be cool if at some point in the future it would be possible to make some more essentials- Cloners, specifically, as well as plant pots for botanists. Maybe vents, too, as we had to loot those from the station itself. Things that are essential to the station and if something horrid were to happen to them, all wouldn't be lost as you could create more at some point with the help of engineering.

**Comment by ZeroMODE0** [comment]
* We might have more ideas for this on the way in the near future, it's a bit late to brainstorm

**Comment by ThatDan123** [comment]
I feel that most essential items are now buildable, including vents (via pipe dispenser) and cloning pods (machine construction). So im gonna close this.
