### ISSUE TITLE
Disappear with chair

### ISSUE THREAD

**Issue by ZeroMODE0** [unitystation/unitystation#3694]
So, with any chair you can buckle yourself to, you can disassemble it while buckled to become invisible on the spot. Also, invulnerable. However, you can be hit by things flying past you, or bullets. You can also get flung to the escape shuttle (top right of the map, I believe), which has nothing to collide with, so you sort of just drift down and to the left.

https://www.youtube.com/watch?v=-Xz3giO3S0Y
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Buckle to a chair
2.  disassemble the chair
3.  unbuckle to reappear
4. works with other people, dead bodies etc
5. if the chair becomes sideways and a dead body is "disappeared" on it, it will never be found again because you cannot build sideways chairs and the dead body cannot unbuckle itself

additional note: you can "summon" the person using the bug by building the same chair, given that they hadn't sat on a turned chair.

**Comment by ZeroMODE0** [comment]
another note: the video shows the weird thing happening where somebody else disassembles the chair, and then I throw the metal rods. That teleports me up to the escape shuttle.

**Comment by daalta** [comment]
Related issue with lockers: https://github.com/unitystation/unitystation/issues/3001

**Comment by NoooneyDude** [comment]
It seems you can no longer disassemble chairs if they are occupied. That interaction is ignored and the wrencher attacks the chair instead.

Edit: if the chair was destroyed (by melee) the occupant is not hidden. Seems fine.

**Comment by AutumnNova** [comment]
I do believe at some point you could pick up the chair someone was sitting on to do the same thing

**Comment by NoooneyDude** [comment]
Picking up a chair with an occupant seems to be fine now. The occupant is left behind and is not hidden.
