### ISSUE TITLE
Epic camera switcher using chairs and lockers

### ISSUE THREAD

**Issue by Call-Me-You** [unitystation/unitystation#3698]
# Issue Template
nah man thats for nerds
## Description
You can get your camera to stay in a locker while you freely move around, in a chair or without it.
### Detailed Bug Report
No idea how it works, just read the steps to reproduce

### Steps to Reproduce
or just watch these video's
(If i was to stand still in the chair when i got sold my character would have freaked out and lagged back and forth in the chair)
https://www.youtube.com/watch?v=xdKoWwTKLC0
https://www.youtube.com/watch?v=N2xKKYOy2oc&feature=youtu.be
Please enter the steps to reproduce the bug or behaviour:  

1.  Buckle into chair
2.  Push chair into locker and close it

**Comment by Call-Me-You** [comment]
Also this was on staging 1481, i suspect it also works on the normal servers.

**Comment by daalta** [comment]
We've had a couple of bugs with lockers, such as players ceasing to exist. But those might not be related.

**Comment by NoooneyDude** [comment]
#3840, #3694, #4275.
