### ISSUE TITLE
Make chaplins that wear clown gear speak like a clown.

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3705]
For example, if a chaplin wears a clown mask, he will speak like a clown.

Also, it's probably a good idea to add a clown mask to chaplin backpack so he may become a priest of the honkmother if he wants to.

**Comment by corp-0** [comment]
Crap, forgot to link this issue. It should be solved in #3836

**Comment by Zagamun** [comment]
Just tested it on build 4080. It's working. If you wear the clown mask you speak like a clown.

**Comment by NoooneyDude** [comment]
This isssue should be closed.

**Comment by corp-0** [comment]
closing this one as the requested feature was implemented!
