### ISSUE TITLE
Mentors B: 30

### ISSUE THREAD

**Issue by T-rexsuper1** [unitystation/unitystation#3728]
# Mentors

## what are they gonna do? 
Mentors are the people who help other people to get familiar with game mechanics. This is done with a Mentor help chat, which is just like the Admin help chat, but is accessible by Admins _and_ mentors.

### Why do we need them? 
We need them because we lack admins and we can easily assign mentors to see if they do job good or not, they can be promoted! It's a good way to see if person can make a good ADMEME, and reduces the amount of work admins have to do.

### How will it work? 
Add mentorhelp. Same as adminhelp but as well as admins, it will be seen to people with new role - mentors. They are trusted people, familiar with the game mechanics, and willing to share this information with newbies. Only difference between normal players will be that they can answer mentorhelp and see it, and they get a (Mentor) tag on their username just like admins do.

They can be designated as mentors just like how admins are, with the server system operator copying and pasting their account ID into a mentors text file.

## what is needed

- [x] A mentor help chat that functions just like Admin help chat. Admins will need access to this as well.
- [x] The **Mentor** username tag in OOC chat
- [x] The ability to add and remove mentors from a server in a similar manner to Admins
- [ ] The discord bot webhooks must be modified to also track mentor-help logs

Your Goose. (edited by Jack to make it more concise)

**Comment by T-rexsuper1** [comment]
Who comments first gets a candy

**Comment by Evan-R-Rogers** [comment]
OwO?

**Comment by Bod9001** [comment]
direct donation bounty

**Comment by craftxbox** [comment]
claiming this issue, if its not already

**Comment by NoooneyDude** [comment]
I don't think it has been. I've assigned ya.
