### ISSUE TITLE
Dead Pete doesn't look dead when joining the server B:10

### ISSUE THREAD

**Issue by sunshinehunter** [unitystation/unitystation#373]
Steps to reproduce:

* Kill some Petes in an active round and restart the client, or let someone else kill them and then start the client
* All dead Petes will still look alive

[Screenshot](http://i.imgur.com/VmxRQvq.png)

**Comment by Karmelov** [comment]
The status of mob is not being sync'd when a player joins the server. Making the mob status SyncVar, and update the status of mobs in the OnStartClient() would update the status of the Pete's when a players connects.

The thing is that no info is being sync'd (beside transform info through the Network Transform), so any effect or status present in an object would not sync for new players connecting into the server.

We need a way to keep all current and future info sync'd for players that join after an status/effect was applied.

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

    Create a simple separate component named NPC health as old mob health code is obsolete
    Make sure new component syncs state on new client connect

Contributor will receive the bounty after merge (paypal)

**Comment by fomalsd** [comment]
on a related note: when existing player is standing on open doors tile and a new player joins, he sees these doors as closed
