### ISSUE TITLE
Knife duplication bug B:10

### ISSUE THREAD

**Issue by Lexorion** [unitystation/unitystation#374]
When you drop a knife or place it on a table and pick it up again, it reappears on the floor/table for a moment. If you use the hotkey mode to switch fast enough you can duplicate that item. Doesn't affect the guns! Below is a short video where I dupe a knife.
https://www.dropbox.com/s/2q8txjgt1bpn7mh/2017-07-30_00-02-51.mp4?dl=0

**Comment by krille90** [comment]
do both knives work when you try to slash something?

**Comment by DooblyNoobly** [comment]
Yep, both work when slashing. But if you try to drop both of them only one is placed on the ground.

**Comment by DooblyNoobly** [comment]
Suggestion: I've noticed that sometimes when you pick up an item that it seems to pick it up and drop it then pick it up again in a few milliseconds. Maybe if we fix that issue it will fix this one.

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

    Investigate and apply fix

Contributor will receive the bounty after merge (paypal)
