### ISSUE TITLE
Server player is visible on map start B:10

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#376]
A simple fix would be to turn off all the renderers and colliders on the server player at start.

**Comment by krille90** [comment]
better way would be to use the NetworkManager.StartServer method instead of StartHost, then the NetworkManager won't spawn a player for the Server

**Comment by DooblyNoobly** [comment]
The server is based on a host so turning it into just a server would require a massive rewrite. To get an idea of the scale just turn the StartHost call to StartServer and observe the logs. Big job. I think we just apply a minimum solution here and move on, no use wasting valuable dev time on a rewrite when there would be hardly any noticeable benefit.

**Comment by krille90** [comment]
I would rather have a proper solution than a hack, which will probably lead to other problems eventually.

**Comment by Karmelov** [comment]
I agree with Krille. If the fix is a pain to implement now, it will be a bigger pain in the future, and most likely it will never get fixed.

**Comment by DooblyNoobly** [comment]
I think from my initial experiments with StartServer I found that StartServer does not simulate the actual game on the server, you need to write server handling logic for your game where as StartHost simulates the game on the server and therefore it is a lot easier to code. I know a lot of big games that use unet use StartHost rather then StartServer. 

Yes turning off the renderers is a hacky fix but I don't see how this will cause problems in the future? To do this job properly I'd imagine you'd need to just stop the spawning off the server player all together in the OnStartServer override. Either way I'd just be happy with any solution that stops the server player from showing, hack or otherwise.

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

    Find a simple solution to fix it

Contributor will receive the bounty after merge (paypal)

**Comment by DooblyNoobly** [comment]
Solution I went with:

On the server I check if the request to spawn a player is coming from the localClient attached to the server. If it is a headless server or it is in test server mode then it does not spawn the player. 

Otherwise if it is just a hosted game (someone just wants to run their client as a server to play with friends) then I allow it to spawn and I allow the FoV and lighting system to become active.
