### ISSUE TITLE
Two players attempting to pull the same object causes bug B:10

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#377]
If two players attempt to pull the same object then the objects moveTowards gets confused and warps around the screen. I thought I had handled this scenario but apparently not. Requires further investigation.

**Comment by DooblyNoobly** [comment]
Bounty: 10usd

Criteria:

    Diagnose problem and provide a fix

Contributor will receive the bounty after merge (paypal)

**Comment by DooblyNoobly** [comment]
When the second player attempts to pull the object then the 1st players PlayerSync needs to be reset in regards to the pulling variables.

**Comment by krille90** [comment]
So would "Diagnose problem" be part of the solution, as in giving reasons what the cause of the problem is and why the solution presented is good?

**Comment by DooblyNoobly** [comment]
I implemented a check to see if the current puller of the object is not the LocalPlayer and if it isn't then send a Command to PNA to call the StopPulling Command on the player that is currently pulling it on the serverside. Tested and confirmed working
