### ISSUE TITLE
Discussion: network code improvements B:20

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#378]
There has been some talk and a few experiments about how to improve the network code to be more managable and easier to use. Please share any thoughts about how and where you think improvements should be made here.

A few ideas include:
- using the messagebade class to send network msgs instead of relying heavily on SyncVars. (MrLeebo working on experiment here)
- Using some kind of eventsystem to sync the state of the game with new players
- developing a standard set of components to handle mob sync

Anything else I have missed?

**Comment by fomalsd** [comment]
Ok, here's a theoretical structure that concerns both network and coupling (and also hack-safety):

There's one or several (separated by concern) static EventManagers.

Every GameObject has a NetComm component that references corresponding EventManager and sends and receives/processes network messages. 
All other GO components have just the NetComm reference (ideally no interaction between each other) and send messages to server should they want to run some non-clientside method. 
Also components register their callable methods in EventManager through the NetComm.
When the message is processed back on client, NetComm tells EventManager to broadcast whatever event data was received (calling methods etc).
![ling](https://user-images.githubusercontent.com/10403536/28880526-0540f7ae-77ae-11e7-8f58-b17e4005d3d2.png)

Potential benefits:
- loose coupling
- predictable networking
- hack safety

Potential downsides:
- high-ping pals might suffer (could be mostly avoided by simulating most stuff on client, too)

Other:
- not yet sure what should be sent through the net
- currently don't have anything to say about syncing state with new players

**Comment by fomalsd** [comment]
Updated v2 scheme.
![ling2-3](https://user-images.githubusercontent.com/10403536/28925183-c7e0f9c6-786c-11e7-9d45-b08e6c0fce6c.png)

**Comment by DooblyNoobly** [comment]
Looking good. Would like to see an experiment of it in action. The STSS would need to be added to the playerobject once it is determined that he is the local player. And I'm assuming this will tie in with the message base experiments that MrLeebo was working on?

**Comment by fomalsd** [comment]
Yes, you're right, this would require working network message system to make that experiment happen.

**Comment by DooblyNoobly** [comment]
Bounty: 20usd

Criteria:

    - Create a working model of the proposal above (v2 scheme)
    - Keep research on the custom-network-messages branch
    - Keep in mind the objectives (to find a way to make netcode easier to write
    and maintain. To reduce the amount of code in networkActions components.
    To facilitate growth in the future development of unitystations network)

Contributor will receive the bounty after merge (paypal)

**Comment by HeadClot** [comment]
Bit of a suggestion - Why not use [forge networking remastered](https://github.com/BeardedManStudios/ForgeNetworkingRemastered)?

It is free, open source, and actively maintained.
