### ISSUE TITLE
Diagnose on new client sync issues B:25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#380]
Sometimes a networked object will fire the hook for the updated SyncVar before the dependent objects that the method updates are even spawned on a new client connection. For example:

The ShutterSwitches do all of the shutter sync updates as the shutters themselves are not networked objects. When the client joins and the switches SyncVar is obtained by the server then the hook to update the shutters is fired before most of the shutters have even been spawned causing some to be open and some to be closed. Most games wait 2-3 seconds before updating the state and I think this is a good enough solution for us. 

To fix: Go through all the networked objects, make sure they are updating the state from the OnStartClient override (some I noticed just use start, this is bad practice as the syncvar may not even be loaded yet) and implement a coroutine to wait for 2-3 seconds before firing the hook. 

You can do this by calling the hook method manually after the WaitForSeconds or hold off calling the base.OnStartClient and do it after the wait time is complete.

**Comment by DooblyNoobly** [comment]
Bounty: 25usd

Criteria:

    Make sure that all networked objects are syncing properly on new client connect as per post above

Contributor will receive the bounty after merge (paypal)

**Comment by krille90** [comment]
doesn't that correlate with #373 ?

**Comment by DooblyNoobly** [comment]
Yeah but #373 requires a new npc only component to be developed
