### ISSUE TITLE
Create new map to move away from DM called the OutPost B:20

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#381]
Create a new map based off this design: 

![image](https://user-images.githubusercontent.com/20813925/29000680-34dce7e2-7ab6-11e7-8aae-d97778f65364.png)

The outpost map will make way for the development of Department Jobs, Security, Medbay, Space movement and exploration, electricity and atmos. The map needs to be ready before the commencement of 0.2.0 development

**Comment by DooblyNoobly** [comment]
Bounty: 20usd

Criteria:

    Complete the map to a satisfactory standard (no holes in the hull, proper tiles being used 
    in the correct departments etc)

Contributor will receive the bounty after merge (paypal)

**Comment by Epicworlds** [comment]
#382

**Comment by Epicworlds** [comment]
#383

**Comment by Epicworlds** [comment]
#384

**Comment by DooblyNoobly** [comment]
Well done! Looks really good. This marks the beginning of real spessman adventures
