### ISSUE TITLE
Make object destruction cosistent with TG values

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3830]
## Description

As described in https://github.com/unitystation/unitystation/issues/2967 certain objects are rather easy to break. Such as windows, walls, and many more.

Many of their health values are taken straight from tgstation, yet they are destroyed more quickly than they should.

There are many possible reasons for this inconsistency. That reason should be identified and fixed.

## Reproduction

https://github.com/unitystation/unitystation/issues/2967#issuecomment-609063467 did not offer any reproduction steps, but users report that objects are easier to break than in tg. Proper reproduction is needed.

*Feel to edit this issue or to reword it as progress is made*

**Comment by Evan-R-Rogers** [comment]
Personally, I attribute the easy of breakage to the fact that Unity moves much faster than that of TG.

**Comment by corp-0** [comment]
One possible reason for this to happen is that we ported health value but not armor values.

As far as I know, only reinforced windows have armor values now, making them equally harder to destroy with the byond version.

**Comment by corp-0** [comment]
Objects and tiles have armor values now and also damage deflection. This might be safe to close.

**Comment by daalta** [comment]
Yep I suppose we can!
