### ISSUE TITLE
Invisibility bug + "teleportation" bug

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#3840]
## Description
If you are strapped into something, and that something is deconstructed, you disappear, and if something of the same type is constructed, you "teleport" there, but aren't really there. You can still interact with the world. Unbuckling yourself makes you reappear.
### Detailed Bug Report
-When invisible, you can't move because you're buckled, but you can still do things such as throwing, or punching.
-When you are teleported, your camera moves and your body appears where the new object was constructed, but you can't interact with anything around where your body is, but you can still interact where your body "really" is, for example, if you throw something, instead it coming from your body, it comes from where your "true" location is.
-While teleported, if people try to punch or throw things at your body, it doesn't work, they can't interact with you there.
-People can't punch you if they punch where your "true" location is.
-If someone throws something where your "true" location is, it will hit you.
-If you deconstruct on a shuttle, the camera will not follow the shuttle, but your "true" location will follow the shuttle.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Strap in
2.  Deconstruct
3.  disappear
4. If you want to teleport, have a friend build something of the same type.

**Comment by Uristthedorf** [comment]
I think this may be related to #3001

**Comment by NoooneyDude** [comment]
Cannot reproduce. The chair can no longer be deconstructed while occupied, and smashing the chair does not produce the bug.
