### ISSUE TITLE
Start of the leveling system B: 220

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3843]
We need to start the leveling system early. This will be a basic system that accumulates xp based on certain actions taken in your job. This will allow us to evolve such system so later on we can restrict job roles and equipment to certain levels.

## Criteria:

- Create a way to store a job level for each job in Firestore
- Create an interface or attribute that can be used to tag methods for experience gains
- Create SO's to store the XP values for certain objects
- Start the system by rewarding cargonians for loading empty crates on the supply shuttle
- Upload the xp to firestore
- Have a way for the player to view the xp or show it off to others

This will be a plan as you go job starting with cargo and by loading empty crates onto the cargo shuttle.

**Comment by VernaSaurus** [comment]
I'd like to take this one, is that alright?

**Comment by DooblyNoobly** [comment]
yep sure but be warned it is a big job. Please talk to me about the intricacies especially with firestore

**Comment by VernaSaurus** [comment]
Question, what exactly _is_ firestore?

**Comment by KuzyXD** [comment]
Question, what exactly is firestore?
Question, what about levels in Barotrauma, @DooblyNoobly?

**Comment by DooblyNoobly** [comment]
firestore: https://firebase.google.com/docs/firestore

**Comment by PJB3005** [comment]
Bro have you ever played SS13?

Also: why the fuck would you use something shit like firestore instead of just plain SQL.

**Comment by SweptWasTaken** [comment]
Pledge 5$ and receive a permanent 5% level boost to all your items in-game!

**Comment by SomeoneYouProbablyKnow** [comment]
I don't quite understand how that system would work. Is it IC levels for IC actions? OOC account levels effecting what jobs you can pick? Or something else? I just really hope it's not OOC account level effecting your options in-game

**Comment by RedlineTriad** [comment]
I am also against it having effects other than available roles.

**Comment by Jibbajabbafic** [comment]
I don't think the levels should be displayed in game (IC) or have any effect on the round *at all*. It should only provide cosmetic changes and maybe change the role progression like @RedlineTriad says.

**Comment by Bod9001** [comment]
Effects that are okay,
round start uniform variance (E.G senior engineer uniform / hats )
using it as a jump off point for unlocking Different roles on station
I think the effects should only be round start affecting
E.g they don't change anything  during the round

**Comment by VernaSaurus** [comment]
Well I was planning on doing only role progression anyway, but cosmetics sound fun. I plan on making the levels viewable via the PDA once it's done, though.

**Comment by VernaSaurus** [comment]
Obviously, giving people an "advantage" thanks to "experience" is no fun for anybody, so I'm not going to do that.

**Comment by craftxbox** [comment]
I personally dont like the concept of 'levelling' and 'experience', I feel that instead a raw playtime system should be used instead. Easier to track, Easier to check against, etc. Paradise does this well, maybe look at how theyre doing it?

**Comment by Fortune117** [comment]
I feel like a leveling system is something you'd want a server to add in itself using mods, not really sure how it'd integrate smoothly into the base game without locking people out of roles. Could add cosmetics though, that'd be a nice reward.

**Comment by craftxbox** [comment]
Paradise restricts by playtime such that, you have to play a certain amount of time to unlock higher powered jobs, etc. ex, you need to spent atleast a few hours as an assistant before you can play ANY other  role (differing for roles such as science, security, engineering, as those can cause more damage than others), and an additonall amount of time before you can be a head in those departments.

**Comment by Fortune117** [comment]
That's a great example of why modding support for that sounds like a better idea. Different communities would want to do it differently. So maybe if we were to implement it, we'd be better of adding an easy to modify base, rather than a fixed system.

**Comment by craftxbox** [comment]
Adding mod support sounds like a horrific idea that will shatter the ecosystem, The way codebases are employed for this is a much better option.

**Comment by VernaSaurus** [comment]
So as it turns out, this is a much more difficult project than I initially thought. In addition, it seems a significant portion of the playerbase do not even want this. As such, I will no longer be working on this.

**Comment by DooblyNoobly** [comment]
pullin the rug out of this job. I was pretty hap hazard with the description and didn't mean to give the impression that it would be used for locking down equipment and jobs. That was just a suggestion. But it seems there is no support for a leveling (i should of called it player stats) system so I'm closing this ticket. Sorry to anyone working on it.

**Comment by SweptWasTaken** [comment]
Cool
