### ISSUE TITLE
Upgrade Unity Editor to 2019.3.8f1 B:100

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3844]
## Criteria:

- Upgrade the project to Editor version 2019.3
- Resolve all errors caused by the upgrade
- Fix the Tilemap errors caused by the upgrade
- Test in multiplayer with 2 clients
- Update the automated GitHub builds and tests to work with the new version

Contributor who has a PR that has been successfully merged to solve the criteria points above will receive the 100usd bounty via paypal

**Comment by daalta** [comment]
Could you elaborate on why the upgrade has a high priority? I feel like the 260 dollar bounty could use a bit more justification.

**Comment by RedlineTriad** [comment]
Yep, I would also like a justification for the abnormally high bounty.

**Comment by NateStanley** [comment]
yeah we should do a 260 dollar update video

**Comment by ThatDan123** [comment]
Wheres my bounty for getting us past 10000 commits?

**Comment by badbon** [comment]
I can do it for 1000 dollers

**Comment by RedlineTriad** [comment]
The justification for the bounty is:

- It needs to be done fast.
- The migration breaks a lot of tilemap stuff.
- Doobly doesn't want to deal with it himself.
- Doobly tried for over an hour and failed.
- It's first merge gets the bounty, no one will be assigned, and people who did it but later will not be paid.

**Comment by Jibbajabbafic** [comment]
Who ever does this you need to update the automated build scripts and testing scripts too.
That involves generating a new licence file for the new unity version (instructions are in https://github.com/unitystation/unitystation/blob/develop/.github/workflows/main.yml), and specifying a new docker image of unity in the YAML files.

There might also be other things that break when that's done.

Edit: I have a throwaway unity account you can use to activate the .alf file, PM me if you need the details.
