### ISSUE TITLE
Discord AHelp Notification [Admin Tool Suggestion]

### ISSUE THREAD

**Issue by Zagamun** [unitystation/unitystation#3846]
## Issue
At the moment, people often ping the admins on the Discord server when they are having issues that could be resolved in-game with the ahelp tools as they presumably are not getting a response in-game.

## Suggestion

- Make a special channel on the Discord server for admins only and make it so any new ahelp issues that appear in the official servers are posted there by UnityStationBot so the relevant admins can then jump onto the server to resolve them.

- Potentially make the bot ping the relevant admins for the server instead of having a generic message without pings or pinging all the admins.

- Make it so the bot doesn't ping Discord if an admin is already in-game.

**Comment by ThatDan123** [comment]
Partly done in #4339 

Doesnt ping, just puts the Ahelp messages into a discord channel.

**Comment by PerfectTangent** [comment]
I think this has been satisfied enough by #4339. If not, it can be reopened.
