### ISSUE TITLE
Dooblys big  ̶d̶̶̶a̶̶̶y̶̶̶ days of bug squashin B: 220

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3863]
Throw your bugs in this thread and I'll squash them so help me god:

Current bugs:

- Wirecutters no longer work - done
- Department battery NRE spam -done
- Can't throw in space - done
- Machine connector is broken - not doing this one, it is going to be apart of a job to simplify wiring
- Camera focus is lost when entering cupboard of dna scanner - done
- Cloner doesn't work on pog - not broken, works on latest
-  Pog directional windows are rotated for no reason - done

**Comment by DooblyNoobly** [comment]
`You can go back to the role select screen when you die, if you exit your current game, then enter another one, then come back, this can also be used to clone yourself if you haven't died.
This bug/glitch/whatever it is has been here since before the distinct hardsuits for the departments was added (this is the best benchmark i have personally) sooo yeah` - fixed

**Comment by PetMudstone** [comment]
Directional windows in departures on Outpost all appear to be facing south in their sprites, but still stop movement thru them from the west or east. Haven't checked other directional windows, such as those in the casket room. - done

**Comment by DooblyNoobly** [comment]
- Update.sh does not save the previous automodconfig and instead the update overwrites it - done

**Comment by vflee** [comment]
on macOS the hit boxes for most of the UI is shifted 2/3rds of the way off of the actual UI elements.

**Comment by vflee** [comment]
Fresh fire extinguishers have two sprays - done

**Comment by DooblyNoobly** [comment]
`
NullReferenceException                                                                                                                                                                        at (wrapper managed-to-native) UnityEngine.Component.GetComponentFastPath(UnityEngine.Component,System.Type,intptr)                                                                         at UnityEngine.Component.GetComponent[T] () [0x00009] in /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/Component.bindings.cs:42                                           at Mirror.NetworkBehaviour.get_netIdentity () [0x00012] in /github/workspace/UnityProject/Assets/Mirror/Runtime/NetworkBehaviour.cs:127                                                     at Mirror.NetworkBehaviour.SetDirtyBit (System.UInt64 dirtyBit) [0x00001] in /github/workspace/UnityProject/Assets/Mirror/Runtime/NetworkBehaviour.cs:629                                   at Mirror.NetworkBehaviour.SetSyncVar[T] (T value, T& fieldValue, System.UInt64 dirtyBit) [0x00069] in /github/workspace/UnityProject/Assets/Mirror/Runtime/NetworkBehaviour.cs:617         at DepartmentBattery.set_NetworkCurrentState (BatteryStateSprite value) [0x0001c] in <f814e27578cb4827a920e321a653c055>:0                                                                   at DepartmentBattery.UpdateBattery (BatteryStateSprite oldState, BatteryStateSprite State) [0x00008] in /github/workspace/UnityProject/Assets/Scripts/Electricity/PowerSupplies/DepartmentBattery.cs:111                                                                                                                                                                                at DepartmentBattery.PowerNetworkUpdate () [0x00094] in /github/workspace/UnityProject/Assets/Scripts/Electricity/PowerSupplies/DepartmentBattery.cs:103                                    at ElectricalNodeControl.PowerNetworkUpdate () [0x00027] in /github/workspace/UnityProject/Assets/Scripts/Electricity/NodeModules/ElectricalNodeControl.cs:129                              at ElectricalSynchronisation.PowerNetworkUpdate () [0x000b9] in /github/workspace/UnityProject/Assets/Scripts/Electricity/Electrical processes/ElectricalSynchronisation.cs:529             at ElectricalManager.Update () [0x00074] in /github/workspace/UnityProject/Assets/Scripts/Electricity/Electrical processes/ElectricalManager.cs:74   
`
- fixed

**Comment by Ranzarth** [comment]
FOV doesn't work for space, which means you can see stuff you shouldn't be able to see by zooming out, I.E. the Syndicate Shuttle - not doing

**Comment by thevandie** [comment]
You can go back to the role select screen when you die, if you exit your current game, then enter another one, then come back, this can also be used to clone yourself if you haven't died.
This bug/glitch/whatever it is has been here since before the distinct hardsuits for the departments was added (this is the best benchmark i have personally) sooo yeah - fixed

**Comment by DooblyNoobly** [comment]
> 
> 
> FOV doesn't work for space, which means you can see stuff you shouldn't be able to see by zooming out, I.E. the Syndicate Shuttle

this one is a bit out of my scope. Didn't work on the new FoV

**Comment by DooblyNoobly** [comment]
- Some gamemodes prevent the round from restarting (I think cargonia) - done

**Comment by Evan-R-Rogers** [comment]
- Thrown items seem to do no damage and the victims don't bleed. - Looks like damage works but clientside blood isn't working. Will fix - splats are now fixed

**Comment by DooblyNoobly** [comment]
- all the bots are stationary - done

**Comment by Mute-Man** [comment]
oxygen tanks don't go into oxygen canisters when you click on them
you just hit the canister with the tank when you click - done

**Comment by DooblyNoobly** [comment]
- Electrical power doesn't work on round restart. (Lights are on but all APC's are red, providing a source doesn't change anything) - done

**Comment by AutumnNova** [comment]
- Admin destroy menu throws NRE's
- Admin & Player chat show players from previous rounds, eventually making it very difficult to find a player to bwoink them
- Player logs show duplicate enteries (i.e player a rdms, player b rdms, log shows two player a rdm events and one player b rdm event)

I'll be doing admin jobs in a separate issue

**Comment by DooblyNoobly** [comment]
ok I'm changing this to a two day event

**Comment by vflee** [comment]
The clowns horn no longer honks when you click on it - done

**Comment by vflee** [comment]
The light switches are no longer interactive - done

**Comment by hecksadecimal** [comment]
If you tableclimb in a moving shuttle, you'll no longer be on the shuttle's matrix and will be left behind. - cannot recreate. If you can tell me exactly how to recreate I'll try it on my side

**Comment by AutumnNova** [comment]
welder fuel tanks only hold 100 units of fuel, same with water tanks - done

**Comment by Adalino** [comment]
> The clowns horn no longer honks when you click on it

i have already fixed the horn but have not made a pull request yet. I also changed that it will no longer hurt someone if no harm intent is selected.

**Comment by DooblyNoobly** [comment]
Massive game breaker:

`
NullReferenceException: Object reference not set to an instance of an object
  at Mirror.NetworkBehaviour.SendTargetRPCInternal (Mirror.NetworkConnection conn, System.Type invokeClass, System.String rpcName, Mirror.NetworkWriter writer, System.Int32 channelId) [0x000d0] in /github/workspace/UnityProject/Assets/Mirror/Runtime/NetworkBehaviour.cs:300 
  at PlayerMove.TargetPlayerUIHandCuffToggle (Mirror.NetworkConnection target, System.Boolean activeState) [0x00010] in <7698f749fec4415faf5906fd9b799437>:0 
  at PlayerMove.Cuff (HandApply interaction) [0x00073] in /github/workspace/UnityProject/Assets/Scripts/Player/PlayerMove.cs:508 
  at Restraint+<>c__DisplayClass10_0.<ServerPerformInteraction>g__ProgressFinishAction|0 () [0x00029] in /github/workspace/UnityProject/Assets/Scripts/Items/Others/Restraint.cs:61 
  at StandardProgressAction.OnServerEndProgress (EndProgressInfo info) [0x00121] in /github/workspace/UnityProject/Assets/Scripts/UI/ProgressBar/StandardProgressAction.cs:241 
  at ProgressBar.UpdateMe () [0x001b5] in /github/workspace/UnityProject/Assets/Scripts/UI/ProgressBar/ProgressBar.cs:245 
  at UpdateManager.Update () [0x0002a] in /github/workspace/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:241 
`

- fixed

**Comment by DooblyNoobly** [comment]
footstep sounds don't play normally when 2 or more people are in the same area - attempt at better sound pool handling

**Comment by DooblyNoobly** [comment]
> 
> 
> on macOS the hit boxes for most of the UI is shifted 2/3rds of the way off of the actual UI elements.

@vflee Trying to recreate this bug, what UI elements specifically can I recreate it on?

**Comment by DooblyNoobly** [comment]
fake walls do not close properly

**Comment by AutumnNova** [comment]
> fake walls do not close properly

coulda sworn i fixed that

**Comment by corp-0** [comment]
they do close properly. They just don't blend in with the walls 
![unknown](https://user-images.githubusercontent.com/43683714/79403375-c6f6c000-7f5c-11ea-9e3a-a86bdf3976df.png)

**Comment by DooblyNoobly** [comment]
Ahh! I think thats a bit too complex for this list

**Comment by DooblyNoobly** [comment]
Ahh! I think thats a bit too complex for this list

**Comment by DooblyNoobly** [comment]
Ahh! I think thats a bit too complex for this list
