### ISSUE TITLE
Players and mobs no longer bleed.

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3866]
In the new build, characters do not bleed anymore yet of course they still take damage.

Simple as that.

**Comment by AutumnNova** [comment]
do note that the blood object is spawned, but is invis

**Comment by Macoron** [comment]
They bleed on host player, but not on a client. Blood sprite render seems to be disabled in prefab for some reason. I tried to find code that makes it's enabled on host, but no luck yet.

Does anybody know why it's disabled in prefab in a first place?

**Comment by Macoron** [comment]
Btw, if you late join - you can see blood on the floor.

**Comment by DooblyNoobly** [comment]
I fixed it

**Comment by DooblyNoobly** [comment]
because I'm a fixer

**Comment by DooblyNoobly** [comment]
I fix things
