### ISSUE TITLE
Entering shuttle causes shuttle to disappear

### ISSUE THREAD

**Issue by duskwalker05** [unitystation/unitystation#3867]
Don't know how this happens but occasionally when a player enters a shuttle all objects on a players screen except for the shuttle contents disappear and you can't move. Other players can still see you and can pull you out of the shuttle. Objects that are meant to be in the shuttle are not visible to the player until after they enter the shuttle.

Steps to Reproduce 
1.  enter a shuttle (won't work all the time, you will know if the objects in the shuttle aren't already there)
2. notice how shuttle, station and astroids disappear but the contents of the shuttle don't
3. have someone pull you out
4. everything goes back to normal till you go back in

**Comment by duskwalker05** [comment]
could be related to #3840

**Comment by PerfectTangent** [comment]
I haven't heard any reports of this. It may not be an issue anymore. Closing unless we get other reports.
