### ISSUE TITLE
Robotics Exosuit Fabricator and basic production system

### ISSUE THREAD

**Issue by Cardioxo** [unitystation/unitystation#3879]
We need basic functionality for the robotics department. The exosuit fabricator is essential for the roboticist, as the job requires you to produce parts and create cyborgs and mechs. 
# Criteria
When a player clicks the exosuit fabricator the Exosuit Fabricator GUI should appear as a pop up NetTab.

- Show the current amount of materials inside the Exosuit Fabricator.
- Three buttons for each material that dispenses 1, 10 and 50 sheets of material respectively.
- The visibility of the three buttons for each material must depend on the current amount of materials. For instance, If it's possible to dispense 1 sheet of a material, the 10 and 50 button must be disabled.
- Show the list of product categories available as buttons, leading to the product list.
- Show the material cost of each product.
- A button for each product to add it to the queue.

- A visual queue display that contains and shows a list of all products in the queue and their current number in the line. 
- Show products in the queue that cannot be produced due to lack of material as red text.
- A button for the Exosuit Fabricator to process the queue
- A button for the Exosuit Fabricator to clear the queue
- Two buttons that allows a product to be moved further or behind in the queue.
- Show that a product is under fabrication when the Exosuit Eabricator is fabricating one.
- When a product has finished fabricating an object, the object must spawn one tile below the Exosuit Fabricator object, and start fabricating the next object in the queue.
- Fabrication must stop when there's a lack of materials for the next product in queue.
- While the Exosuit fabricator is fabricating, the sprite must start animating to show it's processing a material, and go back to the idle animation when done.

Attached are references for the current Exosuit Fabricator GUI on TGStation:

![74b124d5e0a3958e2ddc207394c96fd8](https://user-images.githubusercontent.com/52182160/79051511-ed50ee80-7c30-11ea-9d04-a068f3343f7f.png)

![7491deb6e47299cc3af2a1532c5d1b3c](https://user-images.githubusercontent.com/52182160/79051522-f772ed00-7c30-11ea-857e-fd468faa6977.png)
![d62d34a83880ffcfde920ed12fc16adb](https://user-images.githubusercontent.com/52182160/79051536-05287280-7c31-11ea-9524-1b515e53bada.png)

**Comment by Cardioxo** [comment]
I'm working on this

**Comment by corp-0** [comment]
this issue should be closed, solved in #3915
