### ISSUE TITLE
Xenos are brain dead

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#3884]
# Xenos are brain dead

## Description
Xenos don't attack players anymore. They don't even move. Looks like something happen with mobs AI.

**Comment by CodeKalias** [comment]
It looks like they're fine until they manage to see a player, then they completely freeze unless you pull them around
Same with other hostile npcs

**Comment by CodeKalias** [comment]
Issue not present in build 1903 https://github.com/unitystation/unitystation/actions/runs/73255882 PR #3855 
Issue appears in build 1904 https://github.com/unitystation/unitystation/actions/runs/73286343 PR #3856
