### ISSUE TITLE
Feature: Ability to repair windows with the welder TB: Budget Sprint 1

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3890]
## Criteria:

- When a window is cracked make it possible to repair it using the welder
- Ensure welder is turned on before starting the action
- Show the progress bar when doing the welding and play the welding soundfx
- Determine a good time span for doing the action
- Remove the cracked overlay tiles when the window is repaired
- Test in MP

------------
### Time Based Bounty:

This is a time based bounty. Only one developer can work on a time based bounty at a time, unless you are collaborating. To claim that you are working on this job please talk to Doobly and you will be given instructions on what to do next. Current time based bounties are locked in to $11usd/hour as we have a small budget. We hope this will increase over time.

------------

**Comment by Bod9001** [comment]
Still needs to be Validated In staging  Aranclanos's PR
