### ISSUE TITLE
Feature: Conveyor Belts TB: Budget Sprint 1

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3891]
## Criteria:

- Create the Universal Conveyor Belt prefab that can turn in to all the different types of conveyor belt configurations: Vertical, Horizontal, UpRight Corner, UpLeft Corner etc
- Use the sprites found in Textures/Recycling folder:

![image](https://user-images.githubusercontent.com/20813925/79085692-db7c6200-7d7c-11ea-801c-81b7c1aec1e0.png)

- Create the directional lever switch and allow it to be switched to forward or backwards:
![image](https://user-images.githubusercontent.com/20813925/79085664-c69fce80-7d7c-11ea-8641-f3ae589f7a77.png)

- Add the ability to build conveyor belts from the build menu
- Add the ability to turn conveyor belts on and off using the floor lever
- When a conveyor belt is on have it check the matrix for any items that are on its tile and move it in the specified direction
- Develop a way to also build the floor lever switch from build menu and create an automatic way for it to find conveyor belts nearby that it can control
- Limit movement to a tick rate (so do a movement every 1-2 seconds)
- Map the very first conveyor belt system in cargo on Outpost station
- Make sure everything works in MP by testing with 2 clients 

------------
### Time Based Bounty:

This is a time based bounty. Only one developer can work on a time based bounty at a time, unless you are collaborating. To claim that you are working on this job please talk to Doobly and you will be given instructions on what to do next. Current time based bounties are locked in to $11usd/hour as we have a small budget. We hope this will increase over time.

------------

**Comment by ThatDan123** [comment]
I'll give the conveyors a go tomorrow if no one wants them, i havnt touched construction but i should be able to do the item moving stuff "easily".
