### ISSUE TITLE
Chemical reactions don't result in the sums of their reagents.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#3930]
## Description
Chemical reactions do not give the proper amount of resulting chemicals after reagents are mixed. For example, 15 nitrogen and 45 hydrogen creates just 15 ammonia and that 15 ammonia mixed with 15 water creates just 15 space cleaner. This makes mass production of some chemicals more difficult then they should be.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
1.  Mix reagents together to react with the chem dispenser.
2.  Notice the amount of resulting chemicals is not the sum of the reagents you mixed.

**Comment by RedlineTriad** [comment]
Currently we only have unit tests for reagent container transfers, the best way to debug this is issue is to add some tests for reactions.
