### ISSUE TITLE
HoP gets a taser and baton in his locker but has no weapon permit

### ISSUE THREAD

**Issue by braincrab** [unitystation/unitystation#3931]
## Description
The HoP has no weapons permit on his id but his starting locker contains a taser and baton
### Detailed Bug Report
The id of the HoP doesn't have a weapons permit, but his locker has two weapons in it round start, this seems like a minor oversight.

### Steps to Reproduce

1.  Be HoP
2.  Look at your id under the id editing machine to see you don't have a weapon permit
3.  Open your locker, notice a taser and baton
4. call security on yourself for illegal possession of weaponry

**Comment by NoooneyDude** [comment]
HoP locker does not have a taser and baton - at least on SquareStation. Which map was this on? ~~Tasers don't appear to exist anymore, either.~~

**Comment by PerfectTangent** [comment]
The HoP does get a taser and telescopic baton in their locker in /tg/, they just don't have permission to carry it around unless given the right alert level or orders to.
