### ISSUE TITLE
Easier way to access player ID

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3932]
## Feature Request

There should be an easier way for players to access their player ID. For examble via a keyboard shortcut which copies their ID to their clipboard.

## Notes

Our community HRP server currently requires users to retrieve their player ID.

This is currently done by pressing F5 and using the `myid` command. However, the ID cannot be copied and users must write it down elsewhere.

Alternatively, users can check their log to copy the ID - which isn't very convenient either.

**Comment by corp-0** [comment]
I'm looking at this one. It seems like storing something in clipboard is not a trivial task, if you want to make it work with all platforms.

**Comment by corp-0** [comment]
I’m no longer trying this one. In case someone else wants to give try it.
