### ISSUE TITLE
Feature: Isometric walls and window tiles

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#3936]
## Criteria:

- Create isometric tilesets that work with our autoconnect system for these tiles:
-- Metal Wall
-- Reinforced Metal Wall
-- Window
-- Reinforced Window

- Do not replace the classic tilesets, instead create new ones that can easily be interchanged
- See SS14 on a good example of solid walls and windows

**Comment by corp-0** [comment]
Closing since the last poll opted for 3/4 walls, which don't play nice with our auto tile system and thus the requirements have changed. We might eventually open a new issue to implement those, but the focus has shifted for now.
