### ISSUE TITLE
Excessive effectiveness of light tubes to escape brig cells

### ISSUE THREAD

**Issue by Richie2154** [unitystation/unitystation#3945]
# Excessive effectiveness of light tubes to escape brig cells

## Description
The brig cells currently all have light tubes, which can be very easily used to escape by smashing the glass window and the metal grille. It takes approximately 1 minute to smash the glass and grille with a light tube, which has the similar effectiveness as using a fire extinguisher or stun baton to smash it. In principle, this means that each cell comes with its very own escape tool.

### Detailed Bug Report
Possible suggestions:
- Remove light tubes from cells entirely. Would be a helpful stopgap measure, as any secoff that knows about this will remove light tubes from cells anyway.
- Greatly reduce the capacity of light tubes to damage objects. They might be slightly effective at breaking objects, but certainly not to the current extent.
- Using reinforced cell windows. Somewhat suggested in #3556, but I don't think it fundamentally resolves the issue, the fact that light tubes and broken light tubes are similarly as effective as batons or extinguishers at breaking windows.
- Allow using bare hands to break windows. Must take quite some time to do so, but would prevent being in a cell being totally inescapable. A kind of balancing thing. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Place searched prisoner into cell.
2. Prisoner takes light tube, and smashes glass and grille.
3.  Prisoner escapes cell in approximately 1 minute.

**Comment by corp-0** [comment]
Has this been tested now with the reinforced window buff?

**Comment by Adalino** [comment]
shouldn't the lamp break when you hit with it?

**Comment by Ranzarth** [comment]
An easier solution would be to implement the missing feature in which you burn your hands if you try to grab a lightube barehanded, requiring gloves to remove it. Also armor values for windows are fixed in #3933
