### ISSUE TITLE
Portal can be moved with conveyor belts.

### ISSUE THREAD

**Issue by dan6798** [unitystation/unitystation#3958]
# Issue Template

## Description
Portal can be moved using conveyor belts. I presume this works with other objects that shouldn't be moved.

### Detailed Bug Report

https://www.reddit.com/r/unitystation/comments/g42g8j/discovered_this_little_bug_with_the_portal_mind/

![PortalSS13Shenanigans](https://user-images.githubusercontent.com/63944747/79682276-d2611a00-81ee-11ea-975c-22a8521e40c3.gif)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behavior:  

1.  Put a conveyor belt on the lower-middle end of the portal.
2.  Hook it up. 
3.  The portal will move, and with a bit of hooking things up, you can get it to move pretty far.

**Comment by ThatDan123** [comment]
If you have time can you see if you can still do it.

**Comment by NoooneyDude** [comment]
I couldn't reproduce this.

![try move gateway](https://user-images.githubusercontent.com/6926225/88280315-b020f000-cd39-11ea-98d3-18352838f04a.gif)

**Comment by ThatDan123** [comment]
Put a conveyor in the middle one.

**Comment by AutumnNova** [comment]
you also need a contraption on the other side of the portal i believe
its also activated in that preview, may be related to it not working

**Comment by NoooneyDude** [comment]
How to do that with an inactive gateway? Is the bug only when the gateway is active?

**Comment by NoooneyDude** [comment]
Adding a conveyor to the middle tile didn't help. When you spawn the gateway, it seems the main tile is the lower middle one.

![gateway with conveyor in middle](https://user-images.githubusercontent.com/6926225/88280586-31788280-cd3a-11ea-800c-cd720b76058f.gif)

**Comment by ThatDan123** [comment]
Maybe it was fixed then.

**Comment by NoooneyDude** [comment]
I waited until the gateway connection formed. Seems fine so this issue can probably be closed. Also - love the ambient light.

![active gateway](https://user-images.githubusercontent.com/6926225/88280814-a2b83580-cd3a-11ea-92f2-3c81b0370db9.gif)
