### ISSUE TITLE
Player lerps back for a moment when running through an opening door

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#396]
Say, player sees closed door and needs to get through it fast. He's holding directional button to run through it as soon as it opens. When passing through just opened door (while still holding directional buton) player stays on door tile a bit longer than he should and then lerps to the position he should be at.

**Comment by fomalsd** [comment]
Try simulating 200 ms ping in NetworkManager

**Comment by Em3rgencyLT** [comment]
Tried with 200 and 400ms latency. Ran into closed doors and open doors. While there was normal input delay due to latency, I witnessed no lerp issues. Even tried opening the door right before colliding with it.

Does it really still exist? Can you provide a gif/mp4?

**Comment by DooblyNoobly** [comment]
Looks like it may be resolved. Closing for now
