### ISSUE TITLE
Shooting firearms deals no damage unless you're 1 tile away B:15

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#397]
Also sometimes shooting side sees bloodsplats that aren't seen on victim's side.
Tested on Outpost.

**Comment by DooblyNoobly** [comment]
Bounty: $15 USD

Criteria:
    - Fix the damage bug
    - Investigate and fix the blood bug

Bounty paid after successful merge

**Comment by DooblyNoobly** [comment]
Fixed
