### ISSUE TITLE
Late joined ghost name missing

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#3983]
## Description
When you join as observer ghost and send message to ghost channel, your nickname doesn't show up. OOC works correct.

**Comment by Ninjaboi8175** [comment]
I'll look into this.

**Comment by Ninjaboi8175** [comment]
You might want to check again and see if the issue still exists for you. I started a private server on the latest develop build and ran two other clients as ghosts ( third as host was alive ). One ghost was joined normally and then died to become a ghost. The other late joined the server and started spectating as a ghost. In both instances their names showed up when I typed in the Ghost channel, both for that client and all other ghosts.

So it might have been fixed at some point through some other bug that was noticed.

**Comment by Macoron** [comment]
Just replicated this on USA MRP (build 4094). Didn't check latest develop yet.
![image](https://user-images.githubusercontent.com/6161335/80610813-7a25e580-8a42-11ea-97d3-cb02043e1e8a.png)

**Comment by Ninjaboi8175** [comment]
I just tested on the same server you did and I can confirm it does happen there. However when doing the exact same thing on the latest develop build it seems to be fixed. Joined both servers late as a spectator and then messaged "f" in the chat. On the current public server build it shows blank for the name, but on the latest build it correctly shows the name.

Let me know if it still happens for you when you update and test on the latest develop build.

**Comment by NoooneyDude** [comment]
Managed to reproduce this on USA MRP [4101]:

![image](https://user-images.githubusercontent.com/6926225/82038480-b5d5d600-96f7-11ea-93ab-6d5f85fa2cc1.png)

So I do think there's still a problem. I was a human mob in the previous round too, if it helps.

**Comment by CodeKalias** [comment]
> Let me know if it still happens for you when you update and test on the latest develop build.

Issue is still present on Staging Dev Build 2228
Joined late and went straight to spectate
![image](https://user-images.githubusercontent.com/7896673/82934205-0a444580-9f83-11ea-8c57-3c5f90b2f887.png)

Joined with a second client as AtmosTech, died and my new ghost is correctly named.
Used this new client to look at the spectator ghost and could see they were not named
![image](https://user-images.githubusercontent.com/7896673/82934952-3f9d6300-9f84-11ea-84f8-bfd119d1085d.png)
