### ISSUE TITLE
Microwaved cutlets disappear if you don't pick up the previous cooked batch first.

### ISSUE THREAD

**Issue by Blackthron** [unitystation/unitystation#3999]
## Description
Microwaved cutlets disappear if you don't pick up the previous cooked batch first.

### Detailed Bug Report
Tested on USA servers on build 4091. It is true for both stations. 
Cutlets should stack on one tile, at least like Meat Steak does.

### Steps to Reproduce
1. Cook 3 cutlets 
2. Do not pick up cooked ones from the table 
3.  Cook 3 more cutlets
4. Wait for them to finish cooking, pick up cutlets from the table.
5. Notice you only have 3 cutlets, not 6. The other 3 disappeared.

Laggy low res video:
https://youtu.be/8Pq_tz4P3uA

**Comment by CodeKalias** [comment]
In progress
