### ISSUE TITLE
Investigate / Implement Photon

### ISSUE THREAD

**Issue by unitystation** [unitystation/unitystation#4]
- https://www.assetstore.unity3d.com/en/#!/content/1786

**Comment by DooblyNoobly** [comment]
Looking at photon now. Have set up an appID and imported the library. After I've played with it I will add an entry to .gitignore and update the dependency instructions on the readme.

**Comment by DooblyNoobly** [comment]
script reference: http://doc.photonengine.com/en-us/pun/current/reference/glossary

Will run on free hosting as we set it all up (20 max concurrent users, 500message/s chatroom)

**Comment by DooblyNoobly** [comment]
@unitystation Anyone good with git? I can't get the gitignore to work for the Photon plugin. 

The goal:
- [x] Go to the Asset store and install Unity Networking Free 1.78 plugin
- [ ] Successfully have gitignore, ignore all of the files and folders 

What I've tried:

```
- folder/*
- folder*/
- folder/**
- folder/**/*
```

none work. Returning this for someone else to figure out
