### ISSUE TITLE
Text overlapping in the menu 

### ISSUE THREAD

**Issue by rishabhyata** [unitystation/unitystation#4006]
## Description
Text overlapping in one of the Profession Descriptions

### Detailed Bug Report
In "Choose Professions Menu -- Detective", the word "Cancer" is overlapping over the first paragraph. 

### Steps to Reproduce
Steps to reproduce the bug or behavior:  

1.  Login
2.  Choose player customization and click next
3.  find the profession, "Detective" under "Choose Professions" Menu.

![InkedDetectivebug_LI](https://user-images.githubusercontent.com/59940133/80047623-860a2880-84d3-11ea-81e2-ea721aebec88.jpg)

**Comment by corp-0** [comment]
I imagine it is because the text is just too long. If you're willing to help us, you can suggest changes here: https://docs.google.com/document/d/1ZYBtoh4tAWKykmbViitqhFMdmdLVpPHIN_y2MgsYzI4/edit
and do a shorter version of the description, maintining its intention and soul.
