### ISSUE TITLE
Text exceeding the screen resolution

### ISSUE THREAD

**Issue by rishabhyata** [unitystation/unitystation#4007]
## Description
Text exceeding the screen resolution in one of the Profession Descriptions

### Detailed Bug Report
In "Choose Professions Menu -- Chaplain", the description text is exceeding the screen resolution and is hard to read.

### Steps to Reproduce
Steps to reproduce the bug or behavior:  

1.  Login
2.  Choose player customization and click next
3.  find the profession, "Chaplain" under "Choose Professions" Menu.

![Inkedchaplainbug_LI](https://user-images.githubusercontent.com/59940133/80048204-20b73700-84d5-11ea-9deb-a6beef134215.jpg)

**Comment by daalta** [comment]
@rishabhyata Thanks for the bug report!

This will be fixed the next time we update the job descriptions in-game.

Related issues:

https://github.com/unitystation/unitystation/issues/3362
https://github.com/unitystation/unitystation/issues/3985
https://github.com/unitystation/unitystation/issues/4006
