### ISSUE TITLE
[Feature] In-game Telecomms

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4032]
Implement in-game telecommunications equipment for voice and messaging (PDA messaging and others) . Similar topology to /tg/station:
Headset to main station receiver > Signal processor > station transmitter > headsets.

An interesting suggestion that could add some unique gameplay to Unitystation is to transmit as a ciphertext: perhaps the normal channels could use a simple cipher, such as shift cipher, while command/security use a substitution cipher - a little harder, but both can be cracked in-game for the nefarious player's entertainment. An accommodating traitor tool, to speed up the cracking process.

**Comment by Jibbajabbafic** [comment]
I think the encryption cracking should be left as a traitor item otherwise players will easily figure out the cipher and will write a tool to crack it straight away at round start. 

Example of it happening with /tg/ telescience in the past: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=1915

**Comment by JukeJukestar** [comment]
Would also be nice to have a way for traitors to send anonymous messages. This could be done with a 1 TC traitor shop item.
Possibly have the anonymous message sender displayed as "Anon-1" or something along those lines in case multiple anonymous traitors send messages to the same person

**Comment by PerfectTangent** [comment]
Traditionally, that's done with PDA messaging. I'm not strongly against the idea of providing a purchaseable syndicate radio (like the nukies come with) for traitors to buy, but I think it will end up being a waste of money most of the time. It gives you no value when you buy it and no other traitors do. There's a bit more utility for blood brothers, though, so it might be worth it for them, but that also removes the fun and utility of code words. I don't think it's a good idea.
