### ISSUE TITLE
Players can move while talking

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4038]
Players move when pressing the a, s, d, & w keys, even while in the talk menu. This is really annoying, for obvious reasons.

Please enter the steps to reproduce the bug or behaviour:  

1.  Literally just type anything that uses a, s, d, or w, and your character will move despite being in the talk menu.

**Comment by VernaSaurus** [comment]
Additionally, I have noticed that ANY keys bound to movement will move the character, even if you are typing in the chat menu. For example, if you were to bind ijkl to movement, typing those keys would move the player while talking. This extends to non-letter keys as well, such as the up, down, left, and right keys.

**Comment by Ninjaboi8175** [comment]
I'm going to work on this. Will check back here if I feel I've resolved it and have sent a pull request.

**Comment by Ninjaboi8175** [comment]
I think it's fixed now. Awaiting pull request to and verification from everyone else.

**Comment by VernaSaurus** [comment]
THANK YOU
