### ISSUE TITLE
Esword/FlashLight bug

### ISSUE THREAD

**Issue by ReiderJack** [unitystation/unitystation#4044]
![Bug](https://user-images.githubusercontent.com/42844726/80305868-58b9c500-87c8-11ea-960b-2c50f03e94c7.png)
Also sprties are wrong for holding in hands. They are in seperate hands but character has it in one.

**Comment by NoooneyDude** [comment]
While the latter issue does not seem to occur anymore, toggling the flashlight or the energy sword still has problems. See the gif and the error screenshots.

![flashlight esword](https://user-images.githubusercontent.com/6926225/88281885-91702880-cd3c-11ea-82a6-5dbfa8b68dbd.gif)

![client error](https://user-images.githubusercontent.com/6926225/88281999-ca100200-cd3c-11ea-9873-07844e6092e2.png)

![server error](https://user-images.githubusercontent.com/6926225/88282204-2d9a2f80-cd3d-11ea-8ce8-541005d3ac51.png)
