### ISSUE TITLE
Cannot cut red wires

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4046]
You can't cut red wires with a wirecutter as of build 4093
(but cutting blue LV ones works alright)

Tested on Pog in the cloning room

**Comment by NoooneyDude** [comment]
I cannot reproduce this. Assuming insulated gloves, the red wires in Pogstation's main medical room (couldn't find any red wires in cloning room) cut fine, on local headless.

https://i.imgur.com/YA2BpFP.png
![image](https://user-images.githubusercontent.com/6926225/82030403-88375f80-96ec-11ea-8d0a-23fc87223f61.png)

**Comment by fomalsd** [comment]
what about live server?

**Comment by NoooneyDude** [comment]
No problem on staging or USA MRP.
