### ISSUE TITLE
Ordering multiple Robusting Crates through Cargo Console only sends 1 crate worth of contents

### ISSUE THREAD

**Issue by DefinitelyNotAyunu** [unitystation/unitystation#4055]
# Robusting crates content issue

## Description

When ordering 1 robusting crate at cargo console, the crate arrives with its full contents.
When ordering more than 1 at the same time, all the crates arrive, but only 1 has its contents, the other crates are empty (only affects robusting crates, non-robusting crates ordered simultaneously are unaffected).

### Steps to Reproduce

1.  Order more than 1 robusting crate at the cargo shuttle
2.  Send the cargo shuttle back to cargo
3.  Observe the contents of the received crates

**Comment by PerfectTangent** [comment]
Could not reproduce. Closing.
