### ISSUE TITLE
Cape Not High Enough Layer

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4061]
Not really a very pressing issue, but shoes and belts and the like show up over capes and it looks funky. Also, I would appreciate it if capes could show up outside of hardsuits too instead of being covered up.

Steps to reproduce:
1. wear a cape
2. wear shoes or a belt
3. you can see the shoes and belt through the cape

**Comment by craftxbox** [comment]
This also occurs with capes/shoes/belts in that with some clothing items (ex, suits) obscure them when they should(nt)?

**Comment by NoooneyDude** [comment]
Still occurs. Wearing a bedsheet.

![cape](https://user-images.githubusercontent.com/6926225/88283091-e4e37600-cd3e-11ea-8194-cbb88edeef5f.png)

**Comment by PerfectTangent** [comment]
This appears to no longer be an issue, likely after the recent QA pass to many of the clothing layers.

![Screenshot 2021-04-29 005052](https://user-images.githubusercontent.com/68730437/116503850-0d2b7280-a885-11eb-844b-844e2236facd.png)

Closing.
