### ISSUE TITLE
You can climb on table through closed window

### ISSUE THREAD

**Issue by cremp-bush** [unitystation/unitystation#4068]
Put and take items too

**Comment by NoooneyDude** [comment]
Still occurs. See the gifs.

![window](https://user-images.githubusercontent.com/6926225/88283359-54596580-cd3f-11ea-9bd3-6f228db8162b.gif)
![windoor](https://user-images.githubusercontent.com/6926225/88283364-56bbbf80-cd3f-11ea-91bd-2b02c78dd529.gif)
![items](https://user-images.githubusercontent.com/6926225/88283541-ad28fe00-cd3f-11ea-8bdc-bdcb9c5af587.gif)

**Comment by NoooneyDude** [comment]
Fixed by #5434.
