### ISSUE TITLE
Time to weld shut/open doors is static and not based on speed multiplier in the tool component.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4074]
### Description
As in the title, the time taken to weld doors shut or weld them open is fixed and not affected by the "Speed Multiplier" field in the "Tool" component that welders possess. I am certain that this should not the case.

### Steps to Reproduce
1.  Spawn a "WeldingTool" (speed 1), "ExperimentalWeldingTool" (speed 2), and "Speedy Welder" (speed 10).
2.  Test them on nearby walls to get a sense of how fast they work normally.
3.  Use them to weld shut and weld open doors and notice that they all take the exact same time to do so.

**Comment by Ninjaboi8175** [comment]
Can anyone confirm the intended speed rate increase on the latter two welders? If it's simply multiplicative of the base speed then it should be easy enough to implement as is, otherwise we'd probably need to know the intended rate of increase.

**Comment by fomalsd** [comment]
@Ninjaboi8175 yeah, as far as I know it’s just a multiplier

**Comment by NoooneyDude** [comment]
I've snagged this. Fixing unweldable doors too.
