### ISSUE TITLE
HiddenPos Hijinks: Weird stuff happening at around 0,0 coordinates. (Picking up ghost backpacks and masks, and gibbing ghosts for infinite meat.)

### ISSUE THREAD

**Issue by dan6798** [unitystation/unitystation#4089]
# Issue Template

## Description
At around 0,0 coordinates (not exactly on them but pretty close) you can hover your mouse over to find weird invisible items, with the backpacks and masks (and occasionally materials) the only item you can pick up. Likewise, you can find (and farm) weird invisible ghosts (previous rounds?) which you can keep attacking for infinite meat. If you are rather malicious you could lag up the server spamming this as both the blood and meat stack.
### Detailed Bug Report
![image](https://user-images.githubusercontent.com/63944747/80669320-17e4d900-8a72-11ea-98d5-9ba820ba9bf8.png)

### Steps to Reproduce
1.  Travel to 0, 0 coordinates
2.  Move mouse around until you find a person's name or a backpack item.
3.  Click

**Comment by chairbender** [comment]
yuck, 0,0 is hiddenpos so we stick a bunch of supposedly "despawned" stuff there when we want to put it back into the object pool...sounds like the stuff there can still influence game logic

**Comment by chairbender** [comment]
...and not just despawned stuff but also hidden things like players in lockers and everything in inventory
