### ISSUE TITLE
Refactor the Health system

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#4100]
## Description
Health system could use a refactor to make it more robust and flexible, API-like written for easy interaction with other systems and future-proof so we can build and expand over it.

### What should the health system be:
1- Generic enough to hold and contemplate all forms of living creatures
2- Flexible enough to make childs of the base class and tweak specifics of particular life forms.
3- Decoupled enough to don't generate hard co-dependencies and break everything with an error.
4- Easy enough to be understood for any other dev and to interact with it from any other system in the game (make the system with an API mentality).

### Things that the health system should allow 
(Not necessarily implement from the get go, but allow to do in the future)
- Races with different bodies, body parts, inner organs, blood systems, respiratory systems and metabolisms.
- Surgery
- Brain transplant (All creatures in the game should be able to be controlled by a player)
- In consequence of the afore-mentioned, cyborgs.
- Dismemberment

### Current phase:
Planning, finding patterns designs and minor refactors to current implementation.

You the document where we discuss the plan here: https://docs.google.com/document/d/1KvmpuN2uulMW94dtAzmn8D8u5fCE58aRGHNBzrTIQYM/edit

This issue will be updated with our progress.

**Comment by jamessimo** [comment]
Just FYI this is currently the most uptodate code relating to health refactor 

~~https://github.com/Fortune117/unitystation/tree/healthrefactor~~

This fork is being merged into a new UnityStation Branch #5252

**Comment by PerfectTangent** [comment]
This was added in #6152. May god have mercy on our souls.
