### ISSUE TITLE
CMD chat and OOC chat are the same color

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4101]
## Description
The CMD chat and OOC chat are the same exact shade of blue. This is an _incredibly_ easy fix, since all of the chat colors are stored in the same prefab. Like, literally all you need to do is click the color of one of them and make it like purple or something. Or even just a darker shade of blue.

### Why would this be an issue?
Because people are _constantly_ mixing the two chats up, mistaking cmd chat for ooc statements. Someone please just fix this.

**Comment by Mute-Man** [comment]
shouldn't this... be closed?

**Comment by VernaSaurus** [comment]
it shouldn't though, that mentioned thing was never merged

**Comment by corp-0** [comment]
but was the color changed?

**Comment by VernaSaurus** [comment]
i don't think so

**Comment by ThatDan123** [comment]
It was changed, ages ago

**Comment by ThatDan123** [comment]
In #4262
