### ISSUE TITLE
In-Game rules display

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#4106]
Currently there's no way to view the [server rules](https://sites.google.com/view/unitystation-server-rules/server-rules) while playing on an official Unitystation server.

The server rules should be visible to players in-game. And / Or we should prompt players to read the rules.

We could do this via a new GUI window which displays text content, or we could embed the webpage in-game.

**Comment by corp-0** [comment]
Embedding the webpage is cool because then other code bases/servers can embed their own and personalize its style.

**Comment by fomalsd** [comment]
see #3124

**Comment by daalta** [comment]
Embedding a webpage might actually be difficult. It's not platform indepentent (unless we use a fancy plugin).

Though hosting the rules on a website still seems like a good idea to me. Maybe having it open in the user's browser would be sufficient.

**Comment by MaxIsJoe** [comment]
Already added in #9048
