### ISSUE TITLE
Security radio headsets not functional

### ISSUE THREAD

**Issue by Richie2154** [unitystation/unitystation#4108]
# Security radio headsets not functional

## Description
The security radio headsets given to security officers and the warden do not work. They cannot send or recieve security or general radio channels. It is still possible to broadcast on the security channel, but it requires a headset that is not the security radio headset.

### Detailed Bug Report
N/A

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Attempt to use general or security radio channel using the security radio headset.

**Comment by RedlineTriad** [comment]
Closed in #4090
