### ISSUE TITLE
Map in fire doors and fire alarms to all maps

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#4118]
## Description
Once #4041 is merged, fire doors and fire alarms need to be added around the stations to help stop plasma fires from getting out of control.

Steps to do:
1. Split up hallways into sections with fire doors (doors can overlap if needed)
2. Add a fire alarm in between each set of fire doors to control that section
3. Connect all fire doors in a section the the corresponding fire alarm

Related to #3027 

Maps to do:
- [x] Outpost station
- [x] Pog Station

**Comment by PetMudstone** [comment]
Might want to add Boxstation to the checklist as well, especially if #4142 gets merged (it makes Box appear at 30 pop).

**Comment by NoooneyDude** [comment]
I think all maps now have fire alarms and doors mapped. This issue can be closed.

**Comment by corp-0** [comment]
closing we have firelocks in all maps now.
