### ISSUE TITLE
Rebuilt wires become invisible on client

### ISSUE THREAD

**Issue by CodeKalias** [unitystation/unitystation#4122]
## Description
When you cut a wire and then put down a replacement wire of the same arrangement (eg. an east-west cable pair replaced with another east-west cable pair) the resulting wire becomes invisible on a client. The invisible cable is functional and also visible on the server.
Only applies to cables which already exist in the map, your own new cables in new spots update correctly.

### Builds
**Issue present in**
- Production builds `4097`
- Development builds `2089, 2091, 2102, 2116, 2139`

**Issue not present in**
- Development builds `2078`

### Steps to Reproduce
1.  Join a server, doesn't matter if it's headless or not
2.  Pry up some tiles until you find some existing low/med wiring
3.  Wirecut it with insulation
4.  Put the wire back exactly as it was

**Comment by NoooneyDude** [comment]
Unable to reproduce on build `5380`. Likely has been fixed for a while, as I have not heard anyone complain about this particular bug for quite some time.
