### ISSUE TITLE
Stuff Appearing in Wrong Place in Client Builds

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#4124]
Host in editor, join as client.

Walk around a bit.

See stuff appearing in the wrong place, like the client's version of the scene is somehow corrupted.

![image](https://user-images.githubusercontent.com/1329062/80872973-3c0b0a80-8c6a-11ea-9c3c-ce23c4551dae.png)

It might just be a local dev environment issue since I don't see everyone complaining about it. 

Please upgrade to a higher priority if others are able to reproduce this.

**Comment by NoooneyDude** [comment]
Haven't seen any complaints about this. Reopen if needed.
