### ISSUE TITLE
Investigate Git Pre-Commit Hooks to improve or enforce code quality

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#4125]
# Suggestions

We could use Git Hooks to automatically inspect new commits (or PRs).

* Does the code use proper casing?
* Would the commit cause known Unity warnings (e. g. [CS0649](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0649)) ?
* ...

When an issue is detected, we could make Git display a warning (or even an error).

# Why?

Our reviews tend to miss certain issues. Git Hooks could be used to let our contributors know about issues in their code (before a reviewer is able to overlook the issues).

# Caveats

According to @RedlineTriad we can't force contributors to use Git Hooks. Though it would still be a useful tool for regular contributors.

**Comment by corp-0** [comment]
https://sonarcloud.io/documentation/integrations/github/ this for code quality?

https://sonarcloud.io/documentation/analysis/pull-request/

**Comment by daalta** [comment]
Hmmm, looks interesting! That would let us enforce things.

Looks like sonarcloud has some caveats though: 
> Compiled languages (Java, C#, VB.NET, C/C++, and ObjectiveC) cannot be analyzed by Automatic Analysis.

So we'd need something like Travis CI, too. Maybe using Git Hooks would be simpler?

**Comment by corp-0** [comment]
what's wrong with making Travis do it?

**Comment by daalta** [comment]
Nothing at all! Just thinking out loud 🙂

Doing things via Travis would mean that we notice issues when someone submits a PR. Git Hooks would trigger on each commit, but only if they're installed.

Both solutions would work, I think?

**Comment by chairbender** [comment]
Having to maintain and pay for more infrastructure would be my concern with using a CI tool. Not saying I would rule it out. I am fine with Git Hooks as at least a temporary better alternative. I get a lot of benefit out of automatic static analyzer tools on other large software projects I've worked on so I definitely am for it.

**Comment by RedlineTriad** [comment]
@daalta we can use github Actions for sonar cloud analysis.

**Comment by ThatDan123** [comment]
Still planing to add this? Seems easy to do:

https://github.com/SonarSource/sonarcloud-github-action

**Comment by corp-0** [comment]
sonar sonar sonar 🎶 !

**Comment by corp-0** [comment]
@ThatDan123 
> Do not use this GitHub action if you are in the following situations
> * Your code is built with Maven: run 'org.sonarsource.scanner.maven:sonar' during the build
> * Your code is built with Gradle: use the SonarQube plugin for Gradle during the build
> * You want to analyze a .NET solution: use the SonarCloud Azure DevOps Extension to analyze your code on SonarCloud with Azure Pipelines
> * You want to analyze C/C++ code: rely on our Travis-CI extension and look at our sample C/C++ project

Nonetheless, I found this one https://github.com/marketplace/actions/unity-sonarscanner .

@RedlineTriad can you explain how you got it working in your fork?

**Comment by RedlineTriad** [comment]
@corp-0 I didn't automate it, I ran it manually, the reason to use azure devops is because you can't have secrets in PR builds in GHA, so that dotnet action would only work on master.
