### ISSUE TITLE
Refactor SoundManager to use ScriptableObjects

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#4133]
## Description
Currently the SoundManager uses game objects for each sound which isn't ideal since any changes affect the prefab and often cause merge conflicts, and adding and referencing new sounds is not intuitive at all.

ScriptableObjects provide a much better way of storing each sound since they are designed to be data containers. 

Each sound can then be references through a `SingletonScriptableObject` similar to the way Occupations and PlayerCustomisationData use them.

This should make everyone's life easier and will reduce the amount of prefab merge conflicts a lot.

**Comment by Macoron** [comment]
The reason behind using each audio as game object is that it allows to setup default settings for each sound. This data should be exposed in scriptable object somehow.
![image](https://user-images.githubusercontent.com/6161335/80954027-4f9ea880-8e05-11ea-8cc5-7d40148b0d97.png)

The real annoying part for me is that each link to sound right now made using string id. Though it allows flexibility (using wildcard #), it's also maylead to human errors and not efficient.
![image](https://user-images.githubusercontent.com/6161335/80954486-23375c00-8e06-11ea-9618-b54220217b7f.png)
