### ISSUE TITLE
Clothing and windows don't protect against fires despite high armor values.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4136]
## Description
Despite having high fire resistances, clothing such as firesuits and windows do not protect against fires. This makes firesuits useless despite the armor rework by Gilles and the changes to window armor made in #3933 ineffective at slowing down fires.

### Steps to Reproduce
1. Set yourself on fire and see how quickly you die.
2. Put on a firesuit and firefighting helmet, they have 100 resistance to fire. Also go near reinforced windows, they have 80 resistance to fire.
3. Start a fire again, watch as you die just as horribly as last time and witness the reinforced windows break within seconds.

**Comment by BubblegumBlue** [comment]
Should also note that on the /tg/ codebase, firesuits are pressure-proof like an EVA suit, but cannot protect against low temperatures. Might be a useful addition.

**Comment by corp-0** [comment]
wasn't this fixed?

**Comment by PetMudstone** [comment]
yeah, it should be fixed now.
