### ISSUE TITLE
Tile Armor and Resistances aren't applied correctly

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#4137]
## Description
In TilemapDamage, the DoDamageInternal method applies damage to tiles. At the top, it uses the Armor field of the BasicTile (if the tile is a BasicTile). But lower in the method, it calls various Add(Blah)Damage methods which also apply a hardcoded armor value (like WALL_ARMOR). Also, only the "Indestructable" resistance flag on the tile is checked, other resistance flags are ignored.

For this ticket:
1. Remove all hardcoded Armor settings (WALL_ARMOR and the like). Armor should only come from the BasicTile.Armor field.
2. Add the logic to properly check all the possible Resistances from BasicTile.Resistances.
3. Ensure appropriate tiles have armor values filled in (you can reference TG). Because we were previously relying on hardcoded values, some of the tile assets may have 0 armor, which may make them fragile. As a start, you could set them to use the same hardcoded values that were deleted in step 1 if they don't have any filled in.

**Comment by chairbender** [comment]
fyi @corp-0

**Comment by corp-0** [comment]
related issue #4136 

This could also have the good first issue tag, me thinks

**Comment by corp-0** [comment]
I took a look at this one, it is not a Good first issue.
