### ISSUE TITLE
Pogstation needs renovations

### ISSUE THREAD

**Issue by Ranzarth** [unitystation/unitystation#4141]
## Description

Currently Pogstation is a mess in its current state, large parts need to be remade to make it playable
I've made a list of the problems and also personal opinions on what can be done to improve the map.

### Medical

- Needs to be redesigned with a more understandable layout.
- Chemistry needs to have access to hallway with secure windoors for two chemists.
- Virology needs to be more isolated from medical, possibly making it a small satellite from medical.
- Cloning needs to be separated from geneticists in its own separate room which connects to the genetics room.
- Surgery needs to be downsized and an observation room added.
- Chief Medical Officer's office needs to be moved to a better location.
- Security office needs to be added.

### Science

- Science is basically non existent, only a room in medical and some weird xeno room above evac.
- Security office needs to be added.

### Security

- Is missing permanent residence.
- Lacks an execution room.
- Needs a secure suit storage separate from armory.
- Needs an evidence room with evidence lockers.

### Command

- Current Command is too small, only containing a small captain's room, bridge, and hop's room.
- Missing a general hallway connecting everything.
- Is missing a meeting room.
- Hop needs to have a waiting line and not a waiting room.
- Missing Telecomms room.

### Engineering

- Weirdly designed and with too many windows.
- Suit storage should be located in the secure room.
- Missing secure storage.
- Technical storage needs to be moved as its own separate room from engineering and with a secure technical storage at the end for high risk boards.
- Room needs to be added for a future possible nuclear reactor (bod).
- CE's office needs shutters and shutter over the front entrance to engineering, with the button in CE's office.
- Security office needs to be added.

### Atmospherics

- Too small, will make fitting piping difficult once added.
- Too unsecure, easy to break in, should have a middle area between front and the atmospherics piping.
- Should have a two way windoor office with the atmos secure storage there, and a shutter to move canisters out to the hallway.

### Service

- Kitchen is way too big, needs be downsized, with a table with shutters connecting it to main hallway, and a secure windoor access to botany, and possibly bar as well.
- Bar needs to be put in its own separate area with a backroom for the bartender.

### Cargo

- Cargo shuttle needs to be adjusted so it doesn't crash into the docking bay
- QM's office needs to be able to clearly see cargo bay, and no door to main hallway
- Needs a security Office.

### AI

- Needs a separate AI upload somewhere in the station
- Needs proper AI core room, glass surrounding the AI won't work.

### Other 

- Maintenance is severely lacking and is too basic, needs to be thicker and more maze like, and most rooms should have maintenance access.
- Maintenance could do with some secret rooms.
- Maintenance needs some airlocks here and there around the station.
- Too many outer windows in maintenance.
- Needs better floor design in some areas, for example, grass tiles in botany is no bueno.

### Syndicates

- Syndicate shuttle needs to be redesigned, and use the plastanium walls and windows.
- Needs a Syndicate Outpost.

Feel free to add any suggestions below.

**Comment by VernaSaurus** [comment]
We also need a centcom

**Comment by NoooneyDude** [comment]
**_Complete_** Morgue directions aren't set in their Directional components, as seen in the second image of #4160. Note that there are also two morgues in security.

**Comment by corp-0** [comment]
How much of this list is still relevant?

**Comment by corp-0** [comment]
closing as discussed in #4438 and because this issue has gone stale. A new issue will be made with current problems on the map and check boxes to keep track of progress.
