### ISSUE TITLE
Certain antag details should be saved somewhere in OOC (e.g. status tab)

### ISSUE THREAD

**Issue by Goldiloxx** [unitystation/unitystation#4151]
## Description

When you start a round as the traitor the "You are a traitor/other antag" message is almost seemless from any other message. Meaning that if the ooc is flowing or you just weren't looking you can completely miss it. Also if you forget your objectives there's no way to reread them.

It would be very nice to

- [x] Differentiate the message from the rest of the text with Colour, font and or effects (Bold, Italic, etc.)

- [x] Put the objectives in the notes section or something like that

Thank you for your help

**Comment by ThatDan123** [comment]
Also play the an antag sound effect. 

Also maybe a middle of the screen popup, would be good for new players.

**Comment by VernaSaurus** [comment]
I could probably do this, especially considering I'm already planning on storing the Drone rulesets in a popup box so they don't forget it.

**Comment by NoooneyDude** [comment]
Probably related to #1937.

**Comment by NoooneyDude** [comment]
Antagonists now receive a banner, and the text in the chat log was coloured and resized. No longer an issue.

**Comment by Mute-Man** [comment]
was there anything to solve the "never see it again" part?
because I think that part was about not being able to scroll all the way up in the log, and therefore not being able to see your Objectives.

**Comment by NoooneyDude** [comment]
Yes you're right, that is still an issue. Probably better to create a new one detailing it.

Edit: no, I'll just reopen this one - title is enough I suppose.

**Comment by PerfectTangent** [comment]
There is now an action button to see what your objectives are. Closing.
