### ISSUE TITLE
Feature: Hide Player in Cupboards B:25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#416]
Study the component called ItemControl on any item to see how it functions when being hidden in a cupboard and then create a component to apply the feature to players.

Criteria:

- Atm closets check the matrix for a list of items on the matrixnode, expand this to also check for players
- Hide all of the players SpriteRenderers and add to cupboard inventory when player attempts to hide in the cupboard
- Ensure the matrix is updated to remove player from the tile when hiding in cupboard
- Ensure the matrix is updated when player leaves a cupboard
- Do not disable the Player gObj as this will not update over network
- Test over the network to ensure it all works

Bounty: 25 usd paid via paypal after successful merge

**Comment by krille90** [comment]
Afaik the player shouldn't be able to move, and when people pull the closet, the player inside also has to be moved. 

"Atm closets check the matrix for a list of items on the matrixnode, expand this to also check for players"
Generalize that with an interface or something. I think, NPCs could also be hidden in closets?

**Comment by DooblyNoobly** [comment]
Yeah what really happens with the items is they are removed from the matrix node and a reference to the item is added to a list on the closet (they don't actually move with the closet, they are just hidden by switching off the renderers) and then when the closet is opened the items transform.position is set to the closet position and the matrix node they are on are updated. Same will happen with player.
