### ISSUE TITLE
Doors/crats/toolboxes display there doors wrong sometimes

### ISSUE THREAD

**Issue by TheGreyDiamond** [unitystation/unitystation#4161]
## Description
There is a small chance that a crat/toolbox or door is open and closed at the same time.
![2020-05-07 13_51_25-Window](https://user-images.githubusercontent.com/32875212/81341864-906f1980-90b2-11ea-8417-276fb2a2a897.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Get a random locker or something
2.  Open and close it again
3.  And it is closed and open at the same time

**Comment by NoooneyDude** [comment]
This is a duplicate of #2873 and so this issue can be closed.

**Comment by TheGreyDiamond** [comment]
You're right.
