### ISSUE TITLE
Dev blog 2 video update B: 120

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4163]
## Description

Explore the latest development since Dev Blog 1 and communicate them into an update video. Making this 120 as I have run out of time to provide footage and a plan so it is up to the video creator to investigate and then report on the latest developments in the video. Keep video as short as possible and follow format from Dev Blog 01.

**Comment by NateStanley** [comment]
copy that

**Comment by daalta** [comment]
Done, finished, released! https://www.youtube.com/watch?v=HUHmrrS5gX8
