### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4167]
There's a nasty memory leak that seems to happen during round restarts

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Launch client and join a populated server, join as observer
2. Open process explorer and look at ram usage
3. See memory usage increasing after every round start

**Comment by chairbender** [comment]
suspect it relates to object pooling...I'm looking into it. On my local I am not having this issue with my new changes.

**Comment by DooblyNoobly** [comment]
A big chunk of the mem leak was cleaned up in #4202, but client still grows about 120mb every restart. I have a feeling now it might be due to the LightingSystems render texture

**Comment by corp-0** [comment]
closing in favour of the most recent issue
