### ISSUE TITLE
Feature: Spawn job specific ID's to equipment roll out on start B:15

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#418]
Criteria:

- Add an ID card to the ID slot in equipment when player spawns. 
- Add the relevant ID access to the ID restrictions list
- Give the Captain the gold ID on spawn

Bounty: 15 usd paid via paypal on successful merge

**Comment by fomalsd** [comment]
also I think it would be nice if IDs were equippable from your hand via E hotkey

**Comment by DooblyNoobly** [comment]
This job has been unassigned now. This was the basic TODO's needed to complete the job (extracted from pm's with the last dev who attempted it):

> So basically, alter the JobType prefabs in Assets > Prefabs > Outfits > Resources to now take an IDCardType (which can be standard, command, captain. It just changes the ID sprite), JobType (That should be part of the prefab already? if not get it from the prefabs gameObject.name), Make a list of all the access for that job title (Using the Access Type). Then in Equipment.cs below the gear assignments (around line 168) add a new GameObject and get the ID card from Item Factory
> like this:
> GameObject idCard = ItemFactory.Instance.SpawnIDCard(all the card variables from the JobOutFit object)
> Then assign it to the players equipment inventory: 
> SetItem("id", idCard);
> that should do it, hmu if you get stuck
> btw I've handled all of the network stuff from ItemFactory -> IDCard so you don't have to worry about it
