### ISSUE TITLE
Staging Issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4184]
![image](https://user-images.githubusercontent.com/56727168/81470670-dc6dab80-91e3-11ea-8e18-2e719e1d9360.png)

![image](https://media.discordapp.net/attachments/312454684021620736/708608341483454464/aaaaaaa.png?width=1203&height=143)

-Error messages when joining a server, might only happen when the round hasnt started(or is restarting), late joining seems to not have these errors.

![image](https://user-images.githubusercontent.com/56727168/81471072-83534700-91e6-11ea-85a7-5480bd73c183.png)
-Doing a round restart locks you to this screen, server still works and if you join after it works, but players already in game cant get past this screen.
-Same errors as the pictures above.

![image](https://media.discordapp.net/attachments/312454684021620736/708613115574485022/unknown.png?width=661&height=562)
-Late joining as a ghost people have no clothes (visual bug).
-rejoining doesnt fix the issue and causes any people who joined after you to also have no clothes.

https://imgur.com/a/FJe3uA3
-going into a different matrix seems to keep pushing you back
Seems like exploration sites are ok though.
Ghost only, players seem fine, however:

![image](https://user-images.githubusercontent.com/56727168/81470699-18a10c00-91e4-11ea-98a2-b84fbdf33ce1.png)
-Teleporting to a player that's on a shuttle sends you somewhere else.

![image](https://user-images.githubusercontent.com/56727168/81470723-41c19c80-91e4-11ea-846b-46095e252b3d.png)
-Logged off players seem to go to weird coords. (The two middle ones)
-And when they rejoin they lose all their equipment (not a visual bug).

![image](https://user-images.githubusercontent.com/56727168/81470760-746b9500-91e4-11ea-8a7c-c8ebe54a2cbc.png)
-Not sure whats caused this, but a player has had their sprite stuck to the forwards version.

**Comment by CodeKalias** [comment]
Leaving and rejoining, appear at proper location, teleport to 0,0 shortly after
Errors due to no gear showing up on client
![image](https://user-images.githubusercontent.com/7896673/81471182-46d41b00-91e7-11ea-9cfe-e66461afb069.png)
![image](https://user-images.githubusercontent.com/7896673/81471189-4f2c5600-91e7-11ea-85ef-b5417b5cc024.png)
I put down a mask in the shuttle before the rejoin, it thinks it is here as well
![image](https://user-images.githubusercontent.com/7896673/81471297-02954a80-91e8-11ea-9881-48252b67ae3f.png)
Someone pushed me at my old log-off location and it updated my position
Now I can't interact with any object that isn't newly placed
Invisible ID card still works, trying to put any item into the slots updates it with the correct contents

Confirming these issues fixed in #4191

**Comment by DooblyNoobly** [comment]
- The Hub shows the current map as online scene.

**Comment by CodeKalias** [comment]
#4191
The `Rejoining Round..` / `Waiting for players...` screen stays on the screen if you logged off/back in while inside a locker. Disappears when you open the locker.

**Comment by DooblyNoobly** [comment]
damn lockers, I'll look into it

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/81507864-1c25b780-92f8-11ea-93d6-187aa79c508c.png)

Client side after the game froze up on joining and had to wait a few mins, 8 people were on.

**Comment by ThatDan123** [comment]
Redline grabbed this from the server logs.


NullReferenceException: Object reference not set to an instance of an object,
  at UnityEngine.Events.InvokableCall`2[T1,T2].Invoke (T1 args0, T2 args1) [0x00010] in /home/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:245 ,
  at PlayerHealth.OnPlayerConsciousStateChangeServer (ConsciousState oldState, ConsciousState newState) [0x0000c] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/HumanHealth/PlayerHealth.cs:159 ,
  at UnityEngine.Events.UnityEvent`2[T0,T1].Invoke (T0 arg0, T1 arg1) [0x00025] in /home/builduser/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_2.cs:58 ,
  at LivingHealthBehaviour.set_ConsciousState (ConsciousState value) [0x00026] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:91 ,
  at LivingHealthBehaviour.Death () [0x0002b] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:558 ,
  at LivingHealthBehaviour.CheckHealthAndUpdateConsciousState () [0x000b9] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:614 ,
  at LivingHealthBehaviour.UpdateMe () [0x0011f] in /github/workspace/UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs:452 ,
  at UpdateManager.Update () [0x0002a] in /github/workspace/UnityProject/Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:209

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/81508150-44161a80-92fa-11ea-8ffc-17612d6b3ba8.png)

Seems like sounds have got messed up and freeze the game when joining.

**Comment by DooblyNoobly** [comment]
Fixed shootmessage which has fixed up the big pause on client when it happens

**Comment by DooblyNoobly** [comment]
null checked the player health NRE
