### ISSUE TITLE
Improvement: Remove the remaining Door MechAnims B:25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#419]
For all the vertical opening doors the MechAnimator remains from the beginning of the project. This needs to be removed and a VerticalDoorAnim component created to handle the animations automatically in the same manner that HorizontalDoorAnim works.

This will make creating new vertical doors in the future real easy as you just need to feed the sprite sheet to use. It will also improve scene start performance as MechAnims take a hit to initialize. 

Also while doing this job, all of the ID access restrictions should be filled out for all of the existing doors and applied to their prefabs.

Criteria

- Create a VerticalDoorAnim component and copy the keyframe data from the MechAnim and implemented programmatically into a coroutine (See horizontaldooranim.cs)
- Test all Vertical opening doors and fix any bugs
- Apply the ID restriction access strings to all of the existing doors and apply to their prefabs

Bounty: 25 usd paid via paypal on successful merge

**Comment by Lancemaker** [comment]
can i do this one ?

**Comment by DooblyNoobly** [comment]
@Lancemaker assigned to you :)

**Comment by Lancemaker** [comment]
@DooblyNoobly  made a PR on the first 2 bullets (reworked the doors and pass tested all doors, except for fireDoor mabe but i can do it.)
Im goign to check the ID restriction, mabe we should make it a drop down menu (enum i think) just like the doorType system.

**Comment by DooblyNoobly** [comment]
Yeah I think an enum would work better. And maybe after further thought lets not apply default restrictions to the doors. We should add restrictions while mapping as a maint door can have many different restrictions etc
