### ISSUE TITLE
Crates change their texture when you open them

### ISSUE THREAD

**Issue by TheGreyDiamond** [unitystation/unitystation#4196]
## Description
A crate changes its texture when you open it and resets afterwards.
Normal (closed):
![2020-05-10 16_02_14-unitystation](https://user-images.githubusercontent.com/32875212/81502370-d78d2280-92dd-11ea-82ff-562c4f756b84.png)
Wrong (open):
![2020-05-10 16_02_22-unitystation](https://user-images.githubusercontent.com/32875212/81502379-deb43080-92dd-11ea-8edf-b5a9c4b250bb.png)
I don't know if it works with diffrent crates too.
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Join as someone who has Cargo acces
2.  Walk into that little storage room
3.  Get one of those 
4. Open and close it

**Comment by NoooneyDude** [comment]
I couldn't reproduce this. It was probably fixed when the crate sprites were updated and so this issue can be closed.

![crates](https://user-images.githubusercontent.com/6926225/88354414-ee0f2a00-cdb4-11ea-9ff1-92c5b79cb496.gif)

**Comment by TheGreyDiamond** [comment]
Probably, gonna create a new one if it reappers.
