### ISSUE TITLE
Ability to mark fields as "safe to edit" in VV

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#4199]
## Description
Admins of course want to be able to screw with stuff during the game but don't want to break the server. There's probably a lot of stuff in VV that is not "robust" to editing and could potentially break the game.

To support this, I suggest adding a way to mark fields as "safe to edit", meaning admins have our "stamp of approval" that changing a given value shouldn't break the entire game. Perhaps a custom attribute that VV can recognize.

EDIT: Also should probably be clear if the variable is actually "server side" thus would have an actual effect on all players. Not sure if VV already supports changing server-side vars and syncing them to other players. Otherwise admins might change vars that are only effecting their local instance of the game.

**Comment by chairbender** [comment]
fyi @Bod9001 seems up your alley

**Comment by Bod9001** [comment]
VV is always server side, I've added a feature recently so you can push variables to client If it's on a mono behaviour

**Comment by corp-0** [comment]
done in #6788
