### ISSUE TITLE
Feature: Allow wiring on dirt/sand and remove need for endpoint on connectors: TB: Budget Sprint 2

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4203]
## Criteria:

- Complete #4156
- Move all of the sand tiles on the asteroids so that they are on the underfloor layer. This should allow players to place wire on top of the sand and too also place metal tiles on them for building out bases.
- Adjust digging action to accommodate the layer change
- Test the ability to place wiring on top of sand, if it doesn't work then investigate the problem and provide a solution
- Remove the need for machine connectors to have a wiring end point under them to work. Do this by checking surrounding tiles for wires and then use them as the power source.

We want to get rid of these underneath machine connectors:
![image](https://user-images.githubusercontent.com/20813925/81522618-825d1980-938e-11ea-93b2-284a57acd860.png)
 
------------
### Time Based Bounty:

This is a time based bounty. Only one developer can work on a time based bounty at a time, unless you are collaborating. To claim that you are working on this job please talk to Doobly and you will be given instructions on what to do next. Current time based bounties are locked in to $18usd/hour. You must also be able to finish this job within the 2 week sprint window.

------------

**Comment by Bod9001** [comment]
https://github.com/unitystation/unitystation/issues/4156
Basically requires implementing

**Comment by DooblyNoobly** [comment]
@Bod9001 added it as the first criteria

**Comment by VernaSaurus** [comment]
i could probably do this
