### ISSUE TITLE
Feature: Add ability to build all wall mounts and provide visual aids when mounting: TB: Budget Sprint 2

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4204]
## Criteria:

- Make sure all wall mounts can be built by hand: Apcs, Fire panels, LightTubeMounts, LightBulbMounts, Light Switches
- Develop a way to visually help the player place the wall mount on the wall when they have the wall mount in their hands (we want to improve the UX for newer players)
- Make sure all wall mounts can be connected to their required devices with the multi tool. So light switches to lights, lights to apcs etc
- Make sure everything works fine in multiplayer

------------
### Time Based Bounty:

This is a time based bounty. Only one developer can work on a time based bounty at a time, unless you are collaborating. To claim that you are working on this job please talk to Doobly and you will be given instructions on what to do next. Current time based bounties are locked in to $14usd/hour. You must also be able to finish this job within the 2 week sprint window.

------------

**Comment by Bod9001** [comment]
There's already a Script for placing wall mounts on walls, though it doesn't have the feature specified,
and There is a Re-factor to the multitool, That is on my Nuclear reactor branch That makes it much easier to generically specify connections And stuff

**Comment by DooblyNoobly** [comment]
alright cool we still need all of the other wall mounts buildable and the visual aids

**Comment by Bod9001** [comment]
yeah, anyone working with multitool stuff, I don't mind sending over my scripts for it

**Comment by DooblyNoobly** [comment]
Aranclanos has claimed this

**Comment by DooblyNoobly** [comment]
@Aranclanos are light switches completed?

**Comment by Aranclanos** [comment]
yeah
