### ISSUE TITLE
Bug: meat dupe

### ISSUE THREAD

**Issue by Fiftyllama** [unitystation/unitystation#4215]
### Detailed Bug Report
by putting a body on a chair and gibing it, infinite meat can be made

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  find dead body. If no dead body is to be found, make one
2.  put body on chair
3.  gib the body using knife or other method of gibbing
4. meat will drop, but body will stay in the chair letting you repeat steps 1-3 indefinetly

**Comment by corp-0** [comment]
this problem should be fixed in #4214
