### ISSUE TITLE
Bug: windows can only be shoot out from 2/4 sides

### ISSUE THREAD

**Issue by Fiftyllama** [unitystation/unitystation#4217]
## Description
windows can only be broken from 2/4 sides using guns, behaviour consistent between reinforced and normal glass, hitting them with tools seem to damage windows irrespective of side
### Detailed Bug Report
![glass1](https://user-images.githubusercontent.com/45442346/81618632-0f808c80-93e8-11ea-87cc-57289b768acf.gif)

![glass2](https://user-images.githubusercontent.com/45442346/81618753-57071880-93e8-11ea-87e3-8f2ef03402ab.gif)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  find a window, get a gun
2.  shoot window, if it gets a crack go to other side
3. see that window only takes damage from bullets on one side

**Comment by Humonitarian** [comment]
By my experience some guns just don't damage windows at all, while others do from all sides.

**Comment by NoooneyDude** [comment]
I tested with the Tommy gun. It only destroyed the tile (grille, in my case) when below or to the left of it.

**Comment by fomalsd** [comment]
blame raycasts, see #2424
