### ISSUE TITLE
Bug: Big Yellow Centcom's cargo shuttle doesn't actually leave the station but instead gets stuck in a propetual loop

### ISSUE THREAD

**Issue by Goldiloxx** [unitystation/unitystation#4239]
## Description

The Yellow cargo shuttle used to buy and sell items doesn't really leave the station but keeps moving over and over again, if you try and exit to where it is it will keep appearing and disappearing and will most definitely kill even if you stand way further than it actually is. Also when it returns it does this weird loop, but not sure that's a bug.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Send the cargo shuttle
2.  Watch
3.  Call back the cargo shuttle
4.  Watch
That's about it

**Comment by NoooneyDude** [comment]
I think this would be station-specific and may have been fixed by now. Which station did this occur on?

**Comment by corp-0** [comment]
closing since the poster didn't provide more information. Feel free to reopen if this is still happening.
