### ISSUE TITLE
Cargo computers should need an ID check, like the sec computers

### ISSUE THREAD

**Issue by Goldiloxx** [unitystation/unitystation#4242]
## Description

Not only will that prevent abuse, it will also make the game more interesting for antags and make the "Who ordered 6 crates of laser rifles" questions answerable

Just a minor issure

**Comment by fomalsd** [comment]
maybe requiring a swipe when confirming order would be enough?
(instead of locking out the whole computer unless an id is inserted)

**Comment by Nukeuler123** [comment]
Ill look into this one
