### ISSUE TITLE
BUG: Taking off magboots doesnt reset walkingspeed

### ISSUE THREAD

**Issue by Fiftyllama** [unitystation/unitystation#4244]
## Description
Taking off mag-boots doesn't put your walking speed back to normal,
but keeps it at the same speed it was when you put them on.
running still works as expected.

### Detailed Bug Report
![untitled](https://user-images.githubusercontent.com/45442346/81885280-4f877100-959a-11ea-9636-b5a704da1dc4.gif)

### Steps to Reproduce

1.  put on mag-boots and turn them on.
2.  take them off.
3.  turn on walking, you will walk as if you we're still wearing mag-boots.

**Comment by fomalsd** [comment]
@ReiderJack could you look into this one?

**Comment by vlandemart** [comment]
Fixed in commit 95c6915bdfd84228b58caf9f84304d1837da8f5d (I kinda fucked up and pushed it directly instead of making pr)
