### ISSUE TITLE
Player not updating facing direction when moving diagonally

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#425]
If player is moving diagonally he never changes his facing direction. 
Steps to reproduce: first face down, then press and hold left+up simultaneously and you will move in that direction while still looking down.
Suggesting to update player facing sprite to "up" when walking l+u and r+u and to "down" when l+d and r+d.

**Comment by Lancemaker** [comment]
in the original ss13 one cannot walk diagonally i think.

**Comment by PrPleGoo** [comment]
Correct, moving diagonally should not be a thing at all.

**Comment by DooblyNoobly** [comment]
There are many ss13 servers that do diag movement. If you would like to see the difference in unitystation all you need to do is turn of diagonal movement on the player prefab, apply it and then start the game. IMO diag makes it much easier to move around but at least the option is there for people to customize their servers with

**Comment by DooblyNoobly** [comment]
It seems to me that on TG it only allows you to move diagonally for 1 tile movement when holding down diag keys then it will choose the left or right to continue the movement. Maybe we should do that?
