### ISSUE TITLE
Stability and bug fixes 

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4252]
Opening a TB to focus on getting through our bug list. Log your time in intervals while working through these:

~~https://github.com/unitystation/unitystation/issues/4244~~
~~https://github.com/unitystation/unitystation/issues/4217~~
https://github.com/unitystation/unitystation/issues/4193
~~https://github.com/unitystation/unitystation/issues/4122~~
~~https://github.com/unitystation/unitystation/issues/4077~~
~~https://github.com/unitystation/unitystation/issues/4074~~
https://github.com/unitystation/unitystation/issues/4061
~~https://github.com/unitystation/unitystation/issues/4048~~
~~https://github.com/unitystation/unitystation/issues/4046~~
~~https://github.com/unitystation/unitystation/issues/3999~~
~~https://github.com/unitystation/unitystation/issues/3983~~
~~https://github.com/unitystation/unitystation/issues/3903~~
~~https://github.com/unitystation/unitystation/issues/3840~~
~~https://github.com/unitystation/unitystation/issues/3803~~
~~https://github.com/unitystation/unitystation/issues/3694~~
https://github.com/unitystation/unitystation/issues/3581
https://github.com/unitystation/unitystation/issues/3281
https://github.com/unitystation/unitystation/issues/3280

------------

~~This is a time based bounty. To participate on this job please talk to Doobly and you will be given instructions on what to do next. Current time based bounties are locked in to $18usd/hour~~. 
No longer a bounty.
------------

**Comment by DooblyNoobly** [comment]
This is a good start, if you have an issue that is not in that list that you think should be included then please create one and drop the link here or in discord

**Comment by DooblyNoobly** [comment]
we will have a separate tb for problems that require refactoring, will be up soon

**Comment by DooblyNoobly** [comment]
~High priority bug that I'll honor under this TB: https://github.com/unitystation/unitystation/issues/4345 need someone to do it asap~

**Comment by Bod9001** [comment]
still relevant issue no bounty

**Comment by PerfectTangent** [comment]
This issue was originally a timed bounty bundle. Since that is no longer the case, and each issue it lists stands on its own, this issue is no longer needed. Closing.
