### ISSUE TITLE
Unable to move at next roundstart

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4254]
## Description
Unable to move or interact with the world after loading in a new round. Can still chat IC and OOC.

### Steps to Reproduce
1.  Play a round until it is restarted 
2.  Join the new round when it is already in progress (Readying up may trigger it too)
3.  Attempt to move.

I suspect this may be difficult to reproduce.

![image](https://user-images.githubusercontent.com/6926225/82036109-938e8900-96f4-11ea-951a-e4b926bd24c3.png)
Errors in client:
![image](https://user-images.githubusercontent.com/6926225/82036159-a5702c00-96f4-11ea-9f17-9170314eca80.png)

**Comment by AutumnNova** [comment]
none of those errors seem to be related

**Comment by DooblyNoobly** [comment]
there is some old code that updates new joiners with the state of every object in one swoop regardless if those objects are ready on the client or not. I'm going to refactor it today so the objects take the responsibility of updating themselves when they are ready. Hopefully it solves all of these rejoining issues

**Comment by fomalsd** [comment]
had this happen to me too in 4101 – not sure if it's related to sync on join
