### ISSUE TITLE
Progress bar shouldn't be covered in the darkness

### ISSUE THREAD

**Issue by vlandemart** [unitystation/unitystation#4265]
## Description
Video - https://cdn.discordapp.com/attachments/312454684021620736/711256709808521287/bar_bug.mp4
Currently, progress bar is covered in darkness, made by FOV

### Steps to Reproduce

1.  Find the door, stand one tile down from it
2.  Start welding it, so progress bar appears
3.  Notice that progress bar is invisible due to it being covered in darkness

**Comment by CodeKalias** [comment]
Related to #3222

**Comment by vlandemart** [comment]
Oh, thats a complete duplicate. Sorry, didn't found the related issue in search.
