### ISSUE TITLE
thrown floor tiles need a nerf

### ISSUE THREAD

**Issue by braincrab** [unitystation/unitystation#4271]
## Description
at the moment, floor tiles do 20 damage when thrown and are very easy to get a large amount of.
if you throw, grab, and throw again while spamming the throw hotkey, you can do hundreds of brute damage in seconds, and match the firepower of things like the UZI. even if that's not done, the damage of these things and the ease of getting a stack of them makes it pointless to punch someone, they even come with the advantage of being a ranged weapon.

**Comment by NoooneyDude** [comment]
I think I agree. What damage value would you suggest?

**Comment by PetMudstone** [comment]
In /tg/, floor tiles do just 10 thrown damage (they do 6 in melee).
![image](https://user-images.githubusercontent.com/38266309/82134777-4cfe6480-97b0-11ea-9b2a-0e7d70088e3e.png)

**Comment by PetMudstone** [comment]
![image](https://user-images.githubusercontent.com/38266309/82134886-72d83900-97b1-11ea-9897-683a46aaeaaf.png)
Apparently floor tiles already use /tg/ values...

**Comment by VernaSaurus** [comment]
As it turns out, ALL thrown items deal twice the normal thrown damage for some currently unknown (as far as I know) reason.

**Comment by CodeKalias** [comment]
![image](https://user-images.githubusercontent.com/7896673/82250288-160c8800-9943-11ea-85ed-d933615d8d22.png)

**Comment by VernaSaurus** [comment]
i fucking hate programming

**Comment by corp-0** [comment]
lol why. Why is multiplicated by 2?

**Comment by VernaSaurus** [comment]
who the hell did that

**Comment by braincrab** [comment]
this uh, isnt my first issue.

**Comment by VernaSaurus** [comment]
anyway can someone just fix this so we can close this
