### ISSUE TITLE
"Drop all"/Disrobe progress action not aborting after player becomes conscious

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4277]
## Description
Disrobe action doesn't account for player gaining consciousness, while it should be aborted

Relevant code:
https://github.com/unitystation/unitystation/blob/03dd65610513bac3e7f4129d671db19537d5b0e4/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs#L224-L256

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Stun another player
2.  Initiate "drop all" action when stun is about to end
3.  See player still drop everything after standing back up

**Comment by yoysam** [comment]
doesnt seem to hard
