### ISSUE TITLE
Hacking: connections don't get randomised until hard reset

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4278]
If someone figures out how to open doors via hacking, they can keep doing it across rounds until hard reset

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Successfully hack a door once
2.  Wait for next round
3.  Try the same wire combo

**Comment by fomalsd** [comment]
haven't confirmed it personally yet but that's what guys in discord say

**Comment by VernaSaurus** [comment]
not a bug

**Comment by Call-Me-You** [comment]
*shouldprobablyremoveneedsreproduction

**Comment by Mute-Man** [comment]
dunno why no one else has said it yet, but yeah
this happens
and everyone who knows how to hack doors knows that this happens
