### ISSUE TITLE
Canisters consume tanks and dont spit them out

### ISSUE THREAD

**Issue by braincrab** [unitystation/unitystation#4285]
## Description
When you shove a tank into a canister with intent to fill it, the canister wont let you take it out, saying that no tank is inserted. attempting to put in another tank says that the canister already has a tank inside

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  take a canister and a tank
2.  shove tank in canister
3.  the tank is now both in and not in the canister

**Comment by Nukeuler123** [comment]
Claiming this, ill look into it.

**Comment by Nukeuler123** [comment]
Uhh, this is a bit more complicated that I expected

**Comment by NoooneyDude** [comment]
This issue should be closed as of #4662.

**Comment by Nukeuler123** [comment]
Can this get closed?
