### ISSUE TITLE
Feature: ALT+LMB

### ISSUE THREAD

**Issue by PrPleGoo** [unitystation/unitystation#429]
Add the ALT+LMB feature.

Clicking the left mouse button in the world while holding ALT down should do the following:
- Check if what was clicked is something visible;
- Check if what was clicked on is in on a floor that is visible;
- Check if that floor is adjacent to your mob.
If all the previous is true then:
- Open a new tab next to "Status";
- Name the tab the same as the floor;
- List every visible object on the floor in this tab (technically visible, items buried under a stack of items should be visible here);
- Objects are listed with sprite followed by name;
- The floor counts as an object and should be at the top of this list;
- Clicking on objects in this tab should do the same thing as clicking on them in the world;
- Objects in the list have a square hitbox;
- Hitboxes are all the same size.
When ALT click is used any already open tabs should close.
When the floor is no longer visible the tab should close.
When the mob is no longer adjacent to the floor the tab should close.
When the floor is removed try to rebuild the tab for the new floor.
When objects enter/exit the floor the list should be updated.
When the tab is created make it the active (open) tab for the player.

**Comment by DooblyNoobly** [comment]
Criteria:

     Meet the criteria in the above post

Bounty: 15 usd paid via paypal on successful merge

**Comment by DooblyNoobly** [comment]
Bounty has been removed for the time being, this job is planned for a future project
