### ISSUE TITLE
seed extractor doesn't make seeds

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4295]
## Description
exactly as the title says, the seed extractor doesn't make seeds and just eats the plant you put inside

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  get any plant
2.  put it in the seed extractor
3.  cry as you have no more plants or seeds

**Comment by fomalsd** [comment]
did you open the seed extractor ui afterwards? it shows everything you've inserted

**Comment by VernaSaurus** [comment]
it did not, actually

**Comment by VernaSaurus** [comment]
the ui was empty no matter how many times i clicked it

**Comment by Mute-Man** [comment]
seed extractor UI was also empty for me the few times I interacted with it recently

**Comment by BubblegumBlue** [comment]
yeah, the extractor UI broke recently

**Comment by AutumnNova** [comment]
seed extractor is currently functioning, i dont know what pr fixed this however

**Comment by PerfectTangent** [comment]
this has been fixed
