### ISSUE TITLE
booze dispenser doesn't allow things to be put in it

### ISSUE THREAD

**Issue by VernaSaurus** [unitystation/unitystation#4296]
@otherguywolf  you messed up

**Comment by AutumnNova** [comment]
yeah yeah im workin on it

**Comment by VernaSaurus** [comment]
oh cool

**Comment by VernaSaurus** [comment]
![Annotation 2020-05-19 150609](https://user-images.githubusercontent.com/64121399/82393510-4b1be780-99e2-11ea-943f-a5df1f1f60b4.png)
these are all the containers i tested btw

**Comment by VernaSaurus** [comment]
yes even the salt and pepper shakers lmao

**Comment by BubblegumBlue** [comment]
it's baaaaaaaaaack

**Comment by AutumnNova** [comment]
latest staging?
