### ISSUE TITLE
Dead humans can hold items in their hand.

### ISSUE THREAD

**Issue by PrPleGoo** [unitystation/unitystation#430]
Shortly after ghosting you can still pick up items (different bug). The item then does not drop immediately due to being held by a dead human.

**Comment by fomalsd** [comment]
isn't it fixed as #410 ?

**Comment by PrPleGoo** [comment]
No that just prevents ghosts from sticking items in hands. The issue is that in-hand items should be dropped by unconscious mobs. They still need to be able to enter the inventory slot though for fingerprint purposes.

**Comment by fomalsd** [comment]
They are being dropped when a person is dying (not when becoming unconscious though). 
I think the bug was that you could pick item after items were dropped, and then it would stay equipped, because they drop only once, in PlayerHealth.OnDeathActions()

**Comment by PrPleGoo** [comment]
Yeah so the bug is that they aren't being dropped immediately after getting equipped. Not that ghosts could equip things for their dead mob.

**Comment by DooblyNoobly** [comment]
Well things to determine:
1) Can you pick things up when unconscious (if so then we need a check to stop this from happening)
2) Should we drop items from hands on unconscious or on death?
