### ISSUE TITLE
Enable vsync to stop tilemap tearing and allow client to switch it off via options B: 80

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4314]
## Criteria:

- As per the title make vsync every blank default quality setting: https://docs.unity3d.com/ScriptReference/QualitySettings-vSyncCount.html (option 1)

- Create a toggle button in Options to disable vsync

- Use player prefs to determine setting at start and set/toggle setting from options

This is an urgent TODO so doubling the bounty. Contributor will receive 80 usd on a successful merge of a solution that satisfies the criteria above

**Comment by krille90** [comment]
Would vsync actually fix tilemap tearing? 
I thought it's caused by positions that are not aligned to the pixels of the tiles.

**Comment by DooblyNoobly** [comment]
> 
> 
> Would vsync actually fix tilemap tearing?
> I thought it's caused by positions that are not aligned to the pixels of the tiles.

yep, I done a local test and it fixed tearing for me on fullscreen
