### ISSUE TITLE
Multi monitor mullscreen always uses main monitor resolution

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#4323]
## Description

`/Assets/Scripts/UI/OptionsMenu/DisplayOptions.cs` uses `Display.Main` to fetch the screen resolution for fullscreen, even if the application is running on another monitor.

### Steps to Reproduce

1.  Open Unitystation on a non-primary monitor which has a higher (lower?) resolution than the main screen
2.  Go into windowed mode, then enter fullscreen via the display menu option (NOT Alt + Enter, see https://github.com/unitystation/unitystation/issues/2575)
3.  Fullscreen resolution is that of the primary monitor

**Comment by CodeKalias** [comment]
Working on this
