### ISSUE TITLE
Quick Iteration mode for editor

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4330]
Often you really want to test something ingame quickly and don't care about 89637 asteroids and round start countdown. You don't need a huge map either. Here's what I propose:
- When starting up from editor: start round immediately and let player go straight to role picker
- Create a small DevStation:
   - up to 500-1000 objects total (vs 7000-10000 on scenes we have currently), 
   - containing all working mechanisms and no extra fluff
   - extra matrices should be small and barebones: one freely pilotable shuttle, cargo shuttle, escape shuttle, maybe syndicate shuttle – just enough to simulate normal round flow
- Make a Quick Iteration mode/configuration/custom define that would somehow:
   - disable subscene loading
   - modify build settings to only include most necessary scenes: StartUp, Lobby, OnlineScene, DevStation
   - still be compatible with multiplayer testing
   - be easily toggleable from menu item and require no prefab diving

All aimed to minimise startup time and get in game as fast as possible!

**Comment by vlandemart** [comment]
I'm already making that part with "Quick Iteration mode" to improve build time

**Comment by NoooneyDude** [comment]
#4129 is similar to this.

**Comment by ThatDan123** [comment]
Bod added a bool in the GameManager to only load the station subscene not the others, this starts the game very quickly.

Doesnt affect builds though.

**Comment by NoooneyDude** [comment]
PR #5323 adds a dev station, and with the `Quick Load` boolean in GameManager prefab and no Physics2D on tiles, the game can be started quite quickly. Using the experimental no `ReloadDomain` setting in project settings helps significantly, too. Closing.
