### ISSUE TITLE
Displaced Uninteractable On-Spawn

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4342]
Issue: There's a chance that Clients will spawn displaced (usually one tile south-west) from their actual spawn point, causing them to be unable to interact with anything

Reproduction:
1. Join a server and ready up
2. Wait for the shift to start, and for you to spawn
3. Notice that you spawned in a wall, or on a table instead of the spawn point
4. Can't climb on tables, can't use items, etc.
5. Relog to fix

Non-Dev's Theory: Client-side player pos isn't updated to Server-side player pos, so when the client tries to send commands to the server using the client-side player-pos, the server rejects them

**Comment by fomalsd** [comment]
players appear at this displaced position for a split second even when hosting locally, looks like it was introduced with subscenes

**Comment by NoooneyDude** [comment]
Related to #4254 and #4728.
