### ISSUE TITLE
Fire stacks build up forever if you're wearing fire-resistant clothing.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4343]
## Description
If you're on fire and wearing clothing with 100 fire armor, then fire stacks will keep building up (maybe). Unsure if there's an upper-limit, but most I've seen in the variable viewer was about 4555 stacks.

### Steps to Reproduce
1. Have admin permissions, so you can use stuff like the variable viewer.
2.  Hold control and right click on yourself, select the "View Script Variables" bubble.
3. Put on a set of clothing with 100 fire armor, such as an emergency firesuit and firefighter's helmet.
4. Set yourself on fire, either using a spawned-in flamethrower or by starting a plasma fire. Being in a plasma fire should make fire stacks on you increase rather quickly.
5. Open the variable viewer in the admin tab in the top right.
6. Click on the PlayerHealth button on the window that shows up, another window that looks like a book on the right will appear.
7. Click on the button on the book window that shows an ASCII arrow pointing right, it will "turn a page".
8. On the right page of the book window, you will see "FireStacks" and "NetworkfireStacks" (sic). They tell you have many fire stacks they have on you.

**Comment by stvnksslr** [comment]
@PetMudstone thank you for the detailed steps found the issue will have a fix posted soon.
