### ISSUE TITLE
Implementing the Makeshift Hazmat Suit

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#4353]
## Description
Tex on Discord has made a wonderful sprite for a makeshift hazmat suit. This is a formal request to see it implemented in-game.

[Here's the sprite package](https://cdn.discordapp.com/attachments/402986688114065409/717031906226733087/hazmat.dmi)

The suit should offer lesser protection than the proper radiation and biosuits, with the same slowdown effect.

Examine text:
_Makeshift Biohazard Suit_
Just like momma used to make. Stitched together from whatever materials were to hand, this suit offers some protection from radiation and biological hazards.

**Comment by NoooneyDude** [comment]
This issue should be closed. #4433 adds the suit.

**Comment by corp-0** [comment]
closing as #4433 implemented it
