### ISSUE TITLE
Add a bounty for UI/UX whitepaper 

### ISSUE THREAD

**Issue by Dropgunner** [unitystation/unitystation#4360]
Long story short: We need a bounty for a UI/UX designer making a decent whitepaper for designing user interfaces and first-time user experiences. 

>  1.  Each UI should be accented with the department signature colour like the cargo UI is accented with Orange.
> 
> 2. We should generally aim for a CRT-looking style to the screens.
> 
> So there needs to be a list of departments and if existing, what signature color is currently used
> 
> Example: 
> 
> Cargo - Orange
> Medical - Light blue
> Security - Red
> Science - Purple
> Engineering - Yellow
> Service - Green
> 
> a list of what each department's UI does. Security has different features/tasks, then medical and science. 
> 
> Cargo - Cargo Handling UI
> Medical - Medical records, suit sensor tracking, genetics, cloning and chemistry
> Security - Security records and prisoner management, security cams
> Science - Research and Inventions, xenobiology and AI management
> Engineering - Reactor management, power monitoring, atmospherics monitoring
> Service - Botany genetics, drinks dispensing
>

**Comment by DooblyNoobly** [comment]
you must be reading our minds because we are already drafting up a bounty for this issue

**Comment by Dropgunner** [comment]
> Long story short: We need a bounty for a UI/UX designer making a decent whitepaper for designing user interfaces and first-time user experiences.
> 
> > 1. Each UI should be accented with the department signature colour like the cargo UI is accented with Orange.
> > 2. We should generally aim for a CRT-looking style to the screens.
> > 
> > So there needs to be a list of departments and if existing, what signature color is currently used
> > Example:
> > Cargo - Orange
> > Medical - Light blue
> > Security - Red
> > Science - Purple
> > Engineering - Yellow
> > Service - Green
> > a list of what each department's UI does. Security has different features/tasks, then medical and science.
> > Cargo - Cargo Handling UI
> > Medical - Medical records, suit sensor tracking, genetics, cloning and chemistry
> > Security - Security records and prisoner management, security cams
> > Science - Research and Inventions, xenobiology and AI management
> > Engineering - Reactor management, power monitoring, atmospherics monitoring
> > Service - Botany genetics, drinks dispensing

. just doing analysis on something where no ux consideration was paid to before going this far down developent is crazy tedious. just making a list of complaints won't help because there will be a million arguments be made by members who say that some things having a horrible usability are cool because it's the same as the original. so not only do I need to work myself through an experience I don't understand whatts there, why or whats the expected experience to happen but also make ideally some visualiation of what is needed or done differently better. shit like inventory handling, "looting" or just even having a player understand what he is supposed to do, what he can do and how is stuff that should have been concepted before setting up interactions and putting stuff into code. 

the ui stuff i got in yesterday, trying to figure out whats is its variables, inteentions and reasons. i asked for a feature list, a detailed list but so far got mostly headlines and generaal descriptions. so I'm gonna start with the interaction with items, inventory and environment since it's the most complete chunk of self-punishment to straighten out.

**Comment by CdrCross** [comment]
@DooblyNoobly Maybe give this issue a close, given the progress being made on the actual paper.
