### ISSUE TITLE
Armours immune to tazer

### ISSUE THREAD

**Issue by Humonitarian** [unitystation/unitystation#4364]
## Description

Make thicker armour vests, riot suits and hardsuits immune to tazer shots.

Syndicate is pretty underwhelming when an assistant can take them out in one shot from a weapon with extremely high firing speed.

I'm honestly surprised we didn't have an issue made for this already. At least, not one I could find.

**Comment by braincrab** [comment]
if a nuclear operative armed with a SMG lets a random unarmored grey shirt get that close to them and taze them, and arent with their team, they deserve it.
