### ISSUE TITLE
Let ghosts see player inventory

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4379]
Let ghosts drag players onto themselves so they can see their inventory.

Has been disused on the discord and might be a conflict with people seeing if people have antag items, then get cloned and metagame.

Might have to be admin only or have a system where players permanently become spectator, cant rejoin, but have access.

No idea how the system currently handles it, might be easy to add.

**Comment by Call-Me-You** [comment]
You see, metacommons exist

**Comment by corp-0** [comment]
I think this should be closed as admin can now see inventories and there isn't much support on the idea of letting normal ghosts see inventories.
