### ISSUE TITLE
FOV memory leak

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#438]
Whenever FOV is enabled on main camera, it starts leaking memory right from the "Start game" dialog (usually around 2 MB/s, tested on Windows machine) and seems to only stop when the game process occupies ~80% of entire RAM.

**Comment by DooblyNoobly** [comment]
Foma you noticed the leak since I cleared the list on the thread?

**Comment by fomalsd** [comment]
Will check and report

**Comment by fomalsd** [comment]
Leak seems to be gone. There is some garbage generated while moving, but it is cleared after a while.
