### ISSUE TITLE
Add Stun Charges for Stun Batons

### ISSUE THREAD

**Issue by C4BRA** [unitystation/unitystation#4393]
## Description
People can just stun spam people, I propose that we modify the baton so that it requires some time so it can stun again.

![stunchargeredone](https://user-images.githubusercontent.com/58652908/84399412-8092aa00-ac09-11ea-9164-9cc3eb48b922.png)

The delay should be at least 2.5 seconds

**Comment by yoysam** [comment]
can i take this on

**Comment by yoysam** [comment]
if (registerPlayerVictim && canStun)
		{
			registerPlayerVictim.ServerStun(stunTime);
			SoundManager.PlayNetworkedAtPos(stunSound, target.transform.position, sourceObj: target.gameObject);
			// deactivates the stun and makes you wait;
			canStun = false;
			CreateTimer();
			// Special case: If we're on help intent (only stun), we should still show the lerp (unless we're hitting ourselves)
			if (interaction.Intent == Intent.Help && performer != target)
			{
				wna.RpcMeleeAttackLerp(dir, gameObject);
			}
		}
	}	
private void CreateTimer()
	{
		Timer stunTimer = new Timer();
		stunTimer.Interval = delay * 1000;
		stunTimer.Elapsed += StunTimer_Elapsed;
		stunTimer.Enabled = true;
	}
	// lets you stun again
	private void StunTimer_Elapsed(object sender, ElapsedEventArgs e)
	{
		canStun = true;
	}

**Comment by yoysam** [comment]
how does this look

**Comment by ThatDan123** [comment]
Fixed in #4610 and #4614
