### ISSUE TITLE
Pog needs improvements

### ISSUE THREAD

**Issue by Call-Me-You** [unitystation/unitystation#4397]
https://prnt.sc/syedm4
https://prnt.sc/syegck
https://prnt.sc/syegmx
https://prnt.sc/syehie
https://prnt.sc/syei23
https://prnt.sc/syei9r
https://prnt.sc/syeiix
https://prnt.sc/syeiv9

as lantek said, maintenance is now a closet
it has been replaced with useless inaccessible boxes...
https://prnt.sc/syen1l
too easy to get plasma
there is a hole under the smes at the rightmost solar panels

**Comment by fomalsd** [comment]
next time just paste images directly to the issue instead of links

**Comment by Call-Me-You** [comment]
> next time just paste images directly to the issue instead of links
deal with my style nerd

also people improved pog, its less poopoo now so ignore the images and look at what autumn/otherguywolf did
