### ISSUE TITLE
Add damage deflection.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4408]
## Description
In /tg/, there exists a stat called "damage_deflection" which causes any item that doesn't do enough damage to do absolutely no damage at all. For example, below is code showing deflection on a secure crate.
![image](https://user-images.githubusercontent.com/38266309/84559970-46520700-acf4-11ea-97e4-8136dfe337d1.png)

As you can see above, the damage deflection value is equal to 25. That means if a weapon doesn't do at least 25 damage, then it does no damage at all. It must be noted that if a weapon crosses the damage deflection threshold, then it does full damage and not lessened damage (before armor calculations anyways). If the crate is hit with a weapon that does 25 damage, then it will take 25 damage and be reduced from 500 integrity to 475 integrity (before armor calculations).

I mentioned armor calculations in preferences before, and that's because damage deflection calculations are done before armor calculations. If damage done bypasses said the deflection threshold said inflicted damage is reduced by armor calculations. 

Secure crates have 30 melee armor and when attacked with a melee weapon that does 25 damage, that 25 damage will be reduced by 30 percent to 17.5. This means that a secure crate with armor will have its integrity reduced by 17.5 to 482.5 instead of by 25 to 475. If a weapon does less than 25 damage then it will do no damage to the secure crate, armor or no armor.

I believe damage deflection would help prevent scenarios like those presented in #4387 and #3945 where people can eventually destroy supposedly strong structures like airlocks and reinforced windows using items that do negligible damage. ~~This should also prevent stuff like cargo using PKAs to bust open secure crates (especially _weapons_ crates) should they get uppity.~~ Turns out PKAs do 25 damage and would pass the damage deflection threshold in this case. On a side note, I couldn't find any articles of clothing that have "damage_deflection" so we probably don't have to worry about that.

**Comment by Humonitarian** [comment]
To me it feels like advanced mining equipment breaking closets is more than reasonable

**Comment by yoysam** [comment]
so is the point of this to do damage deflection  after armor calc

**Comment by PetMudstone** [comment]
No, the deflection calculation is before armor calculations. There's a whole bit where I talk about how the two connect.
