### ISSUE TITLE
Glass shards don't have random sprites when they should.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4423]
## Description
In /tg/, glass and plasma glass shards can have one of three sprites at random when they are created. In Unitystation, they only ever use one. Strangely enough, the "Glass Shard" script attached to the glass shard appears to have things related to using different sprites.
![image](https://cdn.discordapp.com/attachments/273774715741667329/722712795505754182/unknown.png)

I asked on the Unitystation Discord if anyone had seen different glass shard sprites in-game before (I certainly haven't or I wouldn't have made this issue) and Autumn responded "i have, but they only seem to use one sprite at a time, like its changed when the server is hardreset? or maybe it only works as host?".

Either way, I've only seen "shards_medium" used in-game, which is also the default sprite used in the prefab.
![shards_medium](https://user-images.githubusercontent.com/38266309/84870285-f9439d00-b033-11ea-9f49-e833adf2b2a4.png)

**Comment by fomalsd** [comment]
they certainly used to be random
