### ISSUE TITLE
Disconnecting and rejoining makes you lose your mime powers.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4428]
## Description
Title. If you disconnect from a game and rejoin, you won't have your mime powers for some reason even if they were working perfectly before.

### Steps to Reproduce
1.  Join round on server as mime. Test mime powers to make sure they work.
2.  Disconnect.
3.  Rejoin, try to use your mime powers and fail. Contemplate purpose of being.

**Comment by NoooneyDude** [comment]
I could reproduce this. It seems all player action buttons at the top of the screen need to be synced when client joins. See #4193, which is also affected.

**Comment by PerfectTangent** [comment]
Fixed with #5790
