### ISSUE TITLE
PogStation is not poggers

### ISSUE THREAD

**Issue by C4BRA** [unitystation/unitystation#4438]
- maint bar, directly in front of maint access
- maint is mostly 1-wide corridors, does not allow for hiding bodies etc
- maintenance is separated hugely, more like 7 - 8 different 'maintenance' areas, you should be able to traverse most of station without leaving maint if needed
- multiple doors (sec and lower med) aren't setup properly and don't respond to access, only ID card naming
- very little atmos equipment in cargo, leads to the whole department depressurising
- little atmos equipment across whole station
- map design is a huge circle, lacks a central hub that makes it easy to access all departments from (something box does incredibly well, if you're at the bridge you can get to any departments in seconds
- medical vendors are understocked, no large med storage area
- security armory is a joke to break into
- captains office is an utter meme, why is the backup power for bridge in there???
- no direct bridge between engineering and atmospherics other than a tiny maint tunnel
- HoS office is tucked away next to permabrig
- execution chamber doesnt actually let you space corpses
- detectives office in the middle of sec
- bomb launch chamber goes through maint????
- most maintenance tunnels are just shells around the entire map,no ways to get through quickly
- there are windows looking into maintenance
- library has everything facing AWAY from the entrance
- most cables are just wired under the floor rather than through maintenance
- most doors, APCs, and buttons are unnamed, multiple in sec are just "Door switch (8)" etc
- there is a space with reinforced walls on one side and windows on the other, both just leading.....into space?
- bridge doors aren't airlocked (see outpost / box for how they should be)
- bar is 3 rooms away from the kitchen, should be in the same area ideally
- only like 2 plasma tanks on the entire station
- very few shuttles, most departments should have one
- the station itself isn't at 0,0, causes confusion for syndicate / nuke ops teams
- nuke ops dont have their own base / asteroid, just a single shuttle in space

Thanks Slim for this insight

**Comment by Mute-Man** [comment]
The YouTool in Cargo still has Engi-only Restrictions.
None of the Cargo crew, even the QM, can buy tools from it.
Seems like Pet Mudstone PRd a fix, but not really sure.

**Comment by PetMudstone** [comment]
Yeah, YouTool issues should have been resolved by #4418.

**Comment by NoooneyDude** [comment]
This is related to #4141.

**Comment by corp-0** [comment]
how much of this list is still relevant?

**Comment by SluggyWuggies** [comment]
well

**Comment by SluggyWuggies** [comment]
For the most part, things have been fixed, however we still have problems with atmos, apcs and wiring, shuttles, sci, and the bridge.

**Comment by corp-0** [comment]
would you mind doing a more specific issue with check boxes so we can close this one and keep track of what has been done?

**Comment by SluggyWuggies** [comment]
Yeah, feel free to close it. Im going to need to ask the populace what their problems are first before I do much, but check boxes would help
