### ISSUE TITLE
Introduce features differentiating the e-gun from the lasgun

### ISSUE THREAD

**Issue by GenericDaemon** [unitystation/unitystation#4439]
The energy gun and the laser gun are effectively the same with the same projectile sprite and speed, furthermore, there is no apparent difference in damage output (other than damage type)
i suggest that lasers and e-projectiles have different sprites and advantages (e.g having the lasgun fire lightspeed projectiles and temporarily blinding nearby glare-unprotected players while having high power consumption and heat problems) in order to increase variety in combat scenarios.

**Comment by PetMudstone** [comment]
Oh! Another thing. In /tg/, the energy gun can switch modes. It has a lethal mode where it fires standard laser bolts, and a non-lethal mode where it fires disabler bolts instead that deal stamina damage which puts people into a special kind of crit state.

**Comment by GenericDaemon** [comment]
True

**Comment by PerfectTangent** [comment]
With the alternate firing modes in game now, the las and e guns have been differentiated. Closing.
