### ISSUE TITLE
Finish glass sliding door functionality B: 40

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#444]
Criteria:

  - Currently the glass sliding door has its own components but they are empty. Determine if a more generic component can be worked out between normal doors and glass sliding doors. Remove any components from the repo that are no longer required
  - Investigate the new TileMap sprite animation feature: https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Tilemaps.TileBase.GetTileAnimationData.html and determine if it can be used to improve the workflow for current and future door animations. Implement the feature if it is deemed so.

EDIT: TileMap sprite anim won't work. Also the glass sliding door is pretty much the same as a normal door but the sprite numbering in the sprite sheets may not match up. Investigate the normal door anim component and go from there by checking to see if the sprite numbering system is the same. 

Bounty: 40 usd paid via paypal on successful merge

**Comment by rmhenn** [comment]
I'm up for doing this, will probably start once I get home

**Comment by krille90** [comment]
regarding the new TileMap sprite animation feature:
the animations can't be stopped and will run indefinitely. That means that our best option would be to stay with the current Door objects.

**Comment by DooblyNoobly** [comment]
Assigned to @rmhenn

**Comment by DooblyNoobly** [comment]
Updated bounty +5
