### ISSUE TITLE
User names of admins can be impersonated

### ISSUE THREAD

**Issue by Call-Me-You** [unitystation/unitystation#4449]
![image](https://user-images.githubusercontent.com/62477979/85297385-5b285a80-b4ab-11ea-81b5-b4c3bf4315ab.png)
you know what i did

**Comment by Call-Me-You** [comment]
guess people took this as cryptic, i changed my nickname to [Admin] Doobly
cant have no fun these days

**Comment by PerfectTangent** [comment]
Addressed with #5638, however it may still be an issue that [admin] can appear in someone's username still.
