### ISSUE TITLE
Gibbing people is too easy

### ISSUE THREAD

**Issue by Uristthedorf** [unitystation/unitystation#4454]
Right now, you can gib someone in about ten seconds, or faster with a knife
-This makes rampages/murderboners extremely deadly, as they can easily gib people, denying them from being cloned.
-This makes disposing of corpses trivial after assassinations, where you can just gib them instead of hiding/spacing the corpses.

In tgstation, to my knowledge, you can generally only gib someone with very strong explosions, or with the chef's gibber machine, (which without upgrades can't gib clothed people.)

**Comment by braincrab** [comment]
i agree that gibbing is absurdly powerful. i also think damage based fibbing should be kept, but only for weapons that deal above a certain amount of damage per attack, so things like death squad pulse rifles can still be used to blow someone to chunks but a pistol,given enough rounds, cant.

**Comment by braincrab** [comment]
however, at the moment, the absurdly strong gibbing is a counter to the absurdly strong cloning.

**Comment by ThatDan123** [comment]
Closing as #4651 defaults gibbing to off for most circumstances.
