### ISSUE TITLE
Wires don't place correctly tiles. TB

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4462]
Wires dont place on the tile where you start wiring, only where your mouse is when you finish: 

I had fixed in an earlier PR that you could only place the wires if you were in range, see second attempt in gif, but the problem of it going on different tiles wasnt fixed.

![](https://imgur.com/7cm9F44.gif)
gif from :# on discord.

**Comment by tjrelyts** [comment]
Is this issue still up for grabs, because if it is I'll take it on.

**Comment by corp-0** [comment]
it looks like it was fixed with #4538 in which case, this should be closed.
