### ISSUE TITLE
Cargo console doesn't show prices for supply crates unless you go to the cart.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4466]
## Description
 As in the title, you can only see how much crates cost when you add them to the cart and view them there. This is quite inconvenient.

Where are the prices?
![image](https://user-images.githubusercontent.com/38266309/85664891-a1c6b200-b66f-11ea-8688-e0699a652082.png)

In a separate tab.
![image](https://user-images.githubusercontent.com/38266309/85665115-e94d3e00-b66f-11ea-9195-c1bb11cf3807.png)

**Comment by fomalsd** [comment]
they're supposed to be located on buy buttons, but something happened to fonts apparently
<img width="999" alt="Scr 2020-06-25 в 9 19 11" src="https://user-images.githubusercontent.com/10403536/85666316-f47e8900-b6c4-11ea-8d85-57f0d8916d49.png">
https://youtu.be/fFuLGzgH9Ck?t=13
