### ISSUE TITLE
Allow admins/developers to call the shuttle and set alert levels using admin/dev tools.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4470]
## Description
I believe that admins (and developers using admin tools) should be able to call the shuttle and also set alert levels. I believe this should be so that admins can intervene if rounds get stuck and won't end for some reason, and also so that developers can more quickly test what happens when the escape shuttle is called.

**Comment by Humonitarian** [comment]
One step closer to AImin

**Comment by ThatDan123** [comment]
Done in #4597 forgot to close this.
