### ISSUE TITLE
License image incorrect

### ISSUE THREAD

**Issue by AliceDTRH** [unitystation/unitystation#4472]
## Description
The license image in the README.md reads:
![cc-by-nd](http://forthebadge.com/images/badges/cc-by-nd.svg)
Which refers to the [Creative Commons 3.0 BY-ND](https://creativecommons.org/licenses/by-nd/3.0/) license.
But the text under it says: 
All assets including icons and sound are under a [Creative Commons 3.0 BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) license unless otherwise indicated.

I propose we change it with another badge with the correct license like ![this one](https://img.shields.io/badge/Creative%20Commons-BY--SA-lightgrey?style=for-the-badge).

I figured I'd make sure first though, in case the license was actually meant to be BY-ND or someone has a better-looking badge.

**Comment by PerfectTangent** [comment]
Oh, there was even an issue for it. Fixed with #6390. Closing.
