### ISSUE TITLE
Replacing closets, lockers, crates, body bags, in scenes with new versions. Delete old versions.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4522]
## Description
Now that #4513 has been merged, mappers should replace all the closets, lockers, crates, and body bags in scenes with the new variants. It should be noted that at least a few lockers, closets, etc. in scenes have been modified from their parents. Mappers should try to carry over these changes. Afterwards, the old variants of closets, lockers, etc. should be deleted.

**Comment by corp-0** [comment]
what's the state of this issue?

**Comment by PerfectTangent** [comment]
Has this been completed?

**Comment by PerfectTangent** [comment]
This issue is no longer relevant
