### ISSUE TITLE
multi-round server profiling, B: 100

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#4528]
The server has a few performance leaks, 
this bounty is to get a profile of what scripts are causing the leak and why they are causing the leak

For consistency ensure that the first and last profiles are on the same map

have clients connect and disconnect basically simulate server conditions as close as possible

Build a headless server with the ability for the unity profiler to attach to it,  Take a profile of normal performance,  Get to a state where the server is chugging even after a round restart, And take a profile and look at the two profiles you taken to identify what the lost CPU time has gone into

Optional extra:
obtain what bottlenecks there are when a lot of clients connected to the server

**Comment by Aranclanos** [comment]
I'm getting this done

**Comment by Aranclanos** [comment]
two weeks ago the admin profile maker got merged in but I'm still waiting for the servers to update, and eventually to lag so any admin can press the create profile button

**Comment by Aranclanos** [comment]
Another update, server admins have been making builds on development mode, getting different profiles for different moments of performance hits and uploading for the devs and linking them in discord.
The profile maker tool is still getting some small updates.

**Comment by Aranclanos** [comment]
Noticed a lot how servers lagged when large fires sparked up, so I decided to run some local tests

![image](https://user-images.githubusercontent.com/701959/99866228-2b7e9b00-2b8e-11eb-8c73-0ac8516ddae6.png)
playerconnection.poll is high because the profile editor couldnt keep up with the data being sent by my client build, but it was mostly pointing out at FogModifyAdd on the spikes

![image](https://user-images.githubusercontent.com/701959/99866458-04c16400-2b90-11eb-9aff-1cfb4053fe98.png)
Here's me using the standalone profile connecting to a build, it was pointing out that the spikes of fires were on the Update() of the ReactionManager

**Comment by NoooneyDude** [comment]
Yes, this is what I found in local testing too. The gas sprite overlays seem to be rather expensive.

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/99866593-2bcc6580-2b91-11eb-9f28-485cbd7120b3.png)

The other day players were reporting that each one minute, the server would lag a lot for a few seconds, so I timed it a bit and with the tool managed to get a profile in. These lagspikes remained even after the round ended and the next one started

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/99867038-e0b45180-2b94-11eb-819a-5ca41cc61369.png)
![image](https://user-images.githubusercontent.com/701959/99867055-05102e00-2b95-11eb-94a7-112c6049fe4e.png)

Then, an easy way to get constant lag spikes on the server is rush into ancient temple and die, triggering the statues
This screenshot is on a local server, the spikes remain for the rest of the round

These spikes get worse with time, after 15 minutes it looked like this:
![image](https://user-images.githubusercontent.com/701959/99867145-8f589200-2b95-11eb-9a36-5aaec98512bd.png)
The hostile npcs were not disturbed, I just went afk as a ghost

**Comment by Bod9001** [comment]
yeah this is good, Bounty approved

**Comment by Bod9001** [comment]
there's been some good ways to get profiles implemented and some good performance sink found
