### ISSUE TITLE
Code fixes for server lag, continuation of #4528 

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#4529]
Relies on #4528 
once the issues that have been found with the server performance leak in  #4528 
this bounty will work on addressing those issues and providing adequate fixes and improvements,
to ensure that the server will be stable performance wise,
**NOTE** 
FogModifyAdd 
ReactionManager update
Atmospheric GC (fixed I think)

fix lag from temple statues

**Comment by NoooneyDude** [comment]
Related to issues #2948 and #3177.

**Comment by Bod9001** [comment]
this has been changed to a time bounty

**Comment by Bod9001** [comment]
now back to bounty

**Comment by SantaGitHub** [comment]
is it relevant?

**Comment by PerfectTangent** [comment]
The bounty on this issue has been withdrawn until we can better outline what is required to complete it.
