### ISSUE TITLE
Adding extra defences to the Syndicate station on outpost

### ISSUE THREAD

**Issue by duskwalker05** [unitystation/unitystation#4536]
Adds (hopefully) extra protection to the syndicate station to prevent metagaming miners from stealing syndicate equipment

Ideas:
• Blast doors on the airlocks to the station due to buttons not being hackable currently
• Auto turrets on the sides of the station
• Set the station to a different z-level when it isn't a syndicate round

**Comment by braincrab** [comment]
both turrets and z levels don't exist yet.

**Comment by DooblyNoobly** [comment]
' + 1 for auto turrets. It would then lead us into manned turrets

**Comment by NoooneyDude** [comment]
Closing; the Syndicate station is now in its own subscene.
