### ISSUE TITLE
Drunk effect doesn't work on Mac, maybe?

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4537]
## Description
Full disclosure, I'm not a Mac user so I can't actually test this myself but according to Q4ik and ADÆMONÖOB on Discord the drunk effect introduced #4521 doesn't work if you're on Mac, apparently. 
![image](https://user-images.githubusercontent.com/38266309/86438205-f9da6580-bcba-11ea-91e6-f34321145ef2.png)

### Steps to Reproduce
1. Be on Mac?
2. Drink alcohol (on latest or staging)?
3. Don't receive drunk effect.

I dunno, I don't have a Mac as said above.

**Comment by fomalsd** [comment]
<img width="1136" alt="Scr 2020-07-03 at 09 32 59" src="https://user-images.githubusercontent.com/10403536/86439085-819e8f00-bd10-11ea-8bb9-1885fe0b6d5d.png">
I did get the effect, but it's a bit glitchy with some black overlays

**Comment by fomalsd** [comment]
also after restart it was fine. I'm using Metal capable hardware by the way
![Scr 2020-07-03 at 09 41 23 2020-07-03 09_46_41](https://user-images.githubusercontent.com/10403536/86439897-1fdf2480-bd12-11ea-88fa-33ed861d8614.gif)

**Comment by GenericDaemon** [comment]
can confirm, entire screen with the exception of UI elements goes black on mac

**Comment by jamessimo** [comment]
This is due to METAL inverting z coords. I am working on this now.
