### ISSUE TITLE
Drunk effect inverts camera on linux

### ISSUE THREAD

**Issue by AutumnNova** [unitystation/unitystation#4542]
## Description
Camera inverts when drunk (related to #4537)
### Detailed Bug Report
![2020-07-05-13:47:05](https://user-images.githubusercontent.com/55225562/86525137-8b69f300-bec6-11ea-9436-9d8d4cd76f15.png)
distro is archlinux, version is 4110

### Steps to Reproduce
1.  pour yourself a glass of booze
2.  drink it
3.  panic as your world is turned upside down

**Comment by Nutjob** [comment]
Linux user, can confirm it.
Distro: Ubuntu 18.04.04 LTS
Version: 4110

**Comment by Nukeuler123** [comment]
Does is revert back to normal after you're no longer drunk?

**Comment by AutumnNova** [comment]
yep

**Comment by Nukeuler123** [comment]
Id call it a feature then, but who knows.

**Comment by jamessimo** [comment]
This is due to OpenGL and DirectX having different coordinate systems. I am working on a fix.
