### ISSUE TITLE
You can make cleanbots using wooden buckets 

### ISSUE THREAD

**Issue by vlandemart** [unitystation/unitystation#4551]
## Description
You can make cleanbots using wooden buckets. It looks strange as sprites are wrong and it is illogical.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Put wooden bucket on floor
2.  Use proximity sensor on wooden bucket
3.  Witness what you shouldn't have

**Comment by PetMudstone** [comment]
I've just tested in /tg/ and you can indeed attach a proximity sensor to a wooden bucket. You get the standard cleanbot assembly based on the normal blue bucket sprite. You can then use it to make a standard blue cleanbot.

Perhaps we should implement assembly and bot variants depending on what variety of toolbox/first aid kit/bucket you use?

**Comment by vlandemart** [comment]
Didn't know that tg had same logic. In that case, I guess it's not a problem.

About bot variants - sounds good, but requires spriting work.

**Comment by PetMudstone** [comment]
/tg/ already has a couple of variant sprites for bots depending on the exact variety of toolbox or whatnot used in their construction.
![floorbot_floorbot-c](https://user-images.githubusercontent.com/38266309/86808369-a310bb00-c02f-11ea-9599-a05fc4f19b12.png)
![floorbot_gfloorbot-c](https://user-images.githubusercontent.com/38266309/86808384-a9069c00-c02f-11ea-8928-b47ce848439e.png)
![floorbot_rfloorbot-c](https://user-images.githubusercontent.com/38266309/86808401-ad32b980-c02f-11ea-84fc-a2ff29e98c84.png)

Don't match current sprites for toolboxes and other items though. Perhaps they could use an update.
![storage_blue](https://user-images.githubusercontent.com/38266309/86809120-5e395400-c030-11ea-9e17-75f13b68a4d3.png)
![storage_green](https://user-images.githubusercontent.com/38266309/86809156-685b5280-c030-11ea-88ed-5b0d0105be39.png)
![storage_red](https://user-images.githubusercontent.com/38266309/86809171-6db89d00-c030-11ea-894a-fb3f352c10d0.png)

**Comment by BootlegBow** [comment]
![cleanbot_bucket](https://user-images.githubusercontent.com/69032410/89268177-83df6a80-d67b-11ea-96a3-3301f049de8a.png)
![cleanbot_cleanbot-c_off](https://user-images.githubusercontent.com/69032410/89268182-85109780-d67b-11ea-9861-d17fba572601.png)
![cleanbot_cleanbot0](https://user-images.githubusercontent.com/69032410/89268184-8641c480-d67b-11ea-855d-3f9ed7ae41bd.png)
![cleanbot_cleanbot1](https://user-images.githubusercontent.com/69032410/89268185-8641c480-d67b-11ea-9383-e8271a2eabf1.png)
here's the sprites, just need to be implemented
