### ISSUE TITLE
Naming game folder with non-latin symbols destroys Firebase initialization

### ISSUE THREAD

**Issue by vlandemart** [unitystation/unitystation#4552]
## Description
Naming game folder with non-latin symbols destroys Firebase initialization
You can't login into the game if your game folder is located under non-latin symbols

Tested with game folder named "жопа"
Tested on build that was made automatically with some PR
Tested on Windows 10

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Download any build of the game
2.  Unarchive it and put it so it is located somewhere with non-latin symbols (for example, rename game folder into "жопа")
3.  Launch game and try logging in

If the bug is reproduced (in my case reproduce rate is 3/3), you will see same errors in console(F5) and won't be able to log in.
![изображение](https://user-images.githubusercontent.com/19672958/86806832-eeec5000-c081-11ea-933f-28712ff65ba6.png)
Renaming folder into "ass" fixes this error and you will be able to log in.

**Comment by pyrosshade** [comment]
Should be closed when we ditch firebase

**Comment by AtnerNT** [comment]
Didnt we nuke firebase?

**Comment by MaxIsJoe** [comment]
Yes, we no longer have issues with the game getting stuck on the login screen.

**Comment by corp-0** [comment]
We did. We still need to see if Cyrillic and other non Latin characters break something else, but this issue in particular is fixed.
