### ISSUE TITLE
Vents are BROKEN! We're Gonna Have to Touch the ATMOS SYSTEM! PANIK!

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4557]
## Description
vents don't output anymore, for some reason

### Steps to Reproduce
1.  make a sealed room in space
2.  put vent in the room, wrench it down
3.  take off oxy mask
4.  check room with an atmos scanner
5.  note that there's only C02
6.  die to oxyloss

**Comment by AutumnNova** [comment]
resolved by #4555
