### ISSUE TITLE
Usable Map Editor (UME): Basics: B: 0.02btc 

### ISSUE THREAD

**Issue by Dropgunner** [unitystation/unitystation#4558]
## Description
 The current workflow in map-making is insufficient. Unitystation needs a custom solution since maps are easily breakable (at least currently). This bounty is used to put up a groundwork to fund a solution which fits the needs of Unitystation: highly customizable and expandable for being reused in other systems (Admintools, Event management for live editing rounds for example) 

### Inspiration 
https://www.servuo.com/archive/uo-black-box-open-beta.1327/

### Requirements
Please enter the steps to reproduce the bug or behavior:  

1.  Check out [#2311] since the map editor should be using this sprite animation system as well. (https://github.com/unitystation/unitystation/issues/2311) 
2.  Provide your rationale and decent documentation on how you want to approach this project. For future developers should be comprehensible about how and why you came up with certain design decisions. Examples can be found below
3.  This is gonna be an EPIC project similar to SAS and requires a team rather than one developer.  
4. Making this player-friendly as possible. The map-making community should provide early feedback and should give input which features they currently miss  
5. Usable either in-game or as a third party tool in runtime. This is important for a faster workflow in testing new maps

### Ressources to Read 
[Building a Level Editor in Unity](https://www.red-gate.com/simple-talk/dotnet/c-programming/building-a-level-editor-in-unity/)
[UI Extension Project](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/src/release/)
[Sharing means caring: Things I wish I knew before starting with Tilemaps & 2D](https://forum.unity.com/threads/sharing-means-caring-things-i-wish-i-knew-before-starting-with-tilemaps-2d-2-5d.771020/)

**Comment by Dropgunner** [comment]
I am cancelling this bounty. Basz got the btc for UI/Ux design and I put off the people working on it =)

**Comment by corp-0** [comment]
closing since the bounty was cancelled and the issue, as is, is not relevant anymore. Feel free to re-open or open another one if the requirements change.
