### ISSUE TITLE
Some Actions don't trigger Dialogues

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4565]
## Description
When you weld a door, "<character> starts welding the door... " plays in chat publicly to those in viewing/hearing range.
Other actions need this too.

## Actions that need Dialogues
- [ ] Table Climbing
- [ ] Handcuffing
- [ ] Opening Maint Panel on Doors

**Comment by VernaSaurus** [comment]
i thought maint panel gave a message? or is that just to the player who does it
