### ISSUE TITLE
The Soul - Player Permanence

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#4576]
## Description
ReiderJack has raised attention to the issue, that we do not yet have a system in place to have a player "soul" counted separate from the player body. This is important for lots of reasons:

- Delayed Cloning
- Transforming antags (Like Wizards and Changelings)
- Transformation chemicals (Like those from Xenobio)
- Weapons that transform other characters

In all these cases, the player needs to maintain control and a place in the round (I.E. Permanence) even if their original body is transformed or destroyed.

**Comment by fomalsd** [comment]
Um, but we do have Mind and it's basically as you described it. Cloning wouldn't work without it.

But there are a few reconnect-related bugs that give you a different body/mind on some occasions for some reason
