### ISSUE TITLE
Explosion Sounds are Global

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4578]
## Description
When some miner dingus crashes their ship into an asteroid, everyone still on the station hears it.

### Steps to Reproduce

1. ask someone to take a shuttle and crash it into a faraway asteroid  
2. wait for it to happen
3. hear the explosion sound, even though you're nowhere near it.

**Comment by corp-0** [comment]
this might be able to be fixed with changes to sound manager that are going to be implemented with #4724
