### ISSUE TITLE
Improving Door Hacking

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4595]
## Description
Door Hacking is currently too OP
And there're some features that would help balance it

### Features
- [ ] proper door randomization (see issue #4278)
- [ ] maintenance interfaces differing across doors with different accesses (sec door having a different node setup than the chef's doors)*
*different node setup meaning that the same I/O wire that works to open the chef's door can't be used to open a sec door

**Comment by corp-0** [comment]
https://tgstation13.org/wiki/Hacking#Secure_airlocks doors also have different security measures to make it harder for one to get to the panel
