### ISSUE TITLE
The ability to craft items (slicing meat, chopping logs, etc.) outside of your inventory.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4599]
## Description
Right now in order to slice meat, chop logs, make hamburgers, etc. you need to use the appropriate items on eachother inside your inventory. This doesn't take too long if you're just slicing a single meat slab, chopping a single log, or making a single hamburger, but if you need to make stuff in bulk it gets rather tedious very quickly putting and using stuff in your inventory and then dropping products repeatedly. Therefore, it would be nice if you could perform recipes (as they are currently) without having to put all appropriate items in your inventory. Why can't we just use a knife on a slab of meat that's sitting on a table to cut it or just chop logs that are sitting on the floor?

**Comment by VernaSaurus** [comment]
not burgers, i don't think. pretty sure i made those work out of inventory, but i'm not entirely sure

**Comment by PetMudstone** [comment]
#7024 allows for crafting outside of one's inventory. Closing.
