### ISSUE TITLE
Mob AI Optimisation.

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4608]
Mod AI needs some optimisation, since they do a flee check if they get damaged, this includes atmos damage.

With a lot of mobs can cause server lag until they die:

![image](https://user-images.githubusercontent.com/56727168/87717738-cf9fa200-c7a8-11ea-8240-839079a61fb7.png)
![image](https://user-images.githubusercontent.com/56727168/87717758-d75f4680-c7a8-11ea-9cd0-51f73beae146.png)

Corgi Ai needs some optimisation too: 

![image](https://user-images.githubusercontent.com/56727168/87717801-e940e980-c7a8-11ea-9ebe-618f7498b95a.png)
![image](https://user-images.githubusercontent.com/56727168/87717817-ee059d80-c7a8-11ea-90dc-135fbe3cccb7.png)

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/87820221-9aa55500-c865-11ea-8749-a8ea09bce7f0.png)

![image](https://user-images.githubusercontent.com/56727168/87820232-a1cc6300-c865-11ea-9c9e-1149ab56079b.png)

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/87825585-4bfcb880-c86f-11ea-9440-5a942e3c3d70.png)

Got it down to this.

Note this is a profile of the editor while the other screenshots are of headless, so should be even better there.

**Comment by corp-0** [comment]
is this good to close after #4618 or does it need more work?

**Comment by ThatDan123** [comment]
Yeah good to close.
