### ISSUE TITLE
You can see ghosts occupying inspected tile with alt+click

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#4619]
fun fact

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  ask some dead player to stand on your tile
2.  alt+click your tile and see a ghost in the list

**Comment by yoysam** [comment]
any clue why this happens?

**Comment by fomalsd** [comment]
it's pretty logical – it gets all objects on tile, and ghosts can be found in that list as well
they should be excluded like underfloor wires are (I think)

**Comment by yoysam** [comment]
i read this as ghost tiles and was very confused

**Comment by fomalsd** [comment]
rephrased title a bit
