### ISSUE TITLE
Create the jukebox prefab [First Iteration] TB

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4624]
## Description

The bar needs a jukebox. We need the first iteration of the jukebox created and mapped to the bar of outpost station.

Criteria:

- Find the jukebox sprites in the repo: 
![image](https://user-images.githubusercontent.com/20813925/87850317-9004c180-c932-11ea-8f73-57df08f551f7.png)
- Create a new interactable machine prefab (you can duplicate an existing machine and change it to make it into the jukebox prefab)
- [Speak to ReiderJack about this part if you need some quick directions] Find a way to play the music that plays on the lobby screen from the jukebox
- Make sure the jukebox music can only be heard up to a reasonable distance and follows the other sounds when it comes to being muffled when heard through walls (soundmanager should handle all of this you just need to know how the new soundmanager works as it was recently refactored by reider)
- Make sure the music playing is network synced properly by testing with 2 clients (you can mute one to make sure the other can hear)
- Create a small pop up window for the players that click the jukebox to skip songs or replay songs. Show the song title in this pop up window. Make sure the window closes when the player moves away or gets knocked over

**Comment by corp-0** [comment]
#4724 was just merged. Is this good to close? Maybe we need a Q&A column in the project kanban to confirm everything is alright

**Comment by corp-0** [comment]
@JesterX666 We're testing on staging and have some suggestions:
1. Add a volume slider 
2. Reduce the range in which the music is audible
3. If possible, make the muffle effect stronger
