### ISSUE TITLE
Computer Frames Stopped Working

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4627]
## Description
A Computer Frame constructed through the Construction Menu, using Metal, can't be wrenched down, let alone have a Computer Board be put into it.

### Detailed Bug Report
My guess is that the computer frame is initialized wrong: the constructed computer frame inspect dialogue is missing the "use a wrench to secure it, or use a welder to deconstruct it" text.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behavior:  

1.  Get 5 metal
2.  Build a Computer Frame using the Construction Menu
3.  Bash the Computer Frame with a Wrench, because you can't actually secure it down.

**Comment by ThatDan123** [comment]
Probably related to #4601
