### ISSUE TITLE
libssl unrecognized

### ISSUE THREAD

**Issue by communistkiro** [unitystation/unitystation#4652]
### Detailed Bug Report
The provided linux binary doesn't recognize both up-to-date version of libssl found in the Void Linux repo- `libssl48-3.1.3_1`, and `libssl47-3.0.2_2`. Hence, I couldn't launch it.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Download [archive](https://unitystationfile.b-cdn.net/StationHubLinux.zip);
2.  extract;
3.  chmod +x StationHub
4. ./StationHub

**Comment by MaxIsJoe** [comment]
Is this still an issue?

**Comment by corp-0** [comment]
no, it isn't
