### ISSUE TITLE
Antags need better End Round goal detection

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4658]
- [x] Currently Antags dont green text if the item they have is inside a box  in their inventory
- [x] Currently Antags dont green text if they are in a locker.
- [ ] Additionally a system for detecting being handcuffed on the shuttle so prisoners can fail the escape objective

**Comment by NoooneyDude** [comment]
The box issue was fixed by PR #4797. Is the locker issue still a problem?
