### ISSUE TITLE
Click Move For Pulling

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4659]
In old ss13 while pulling an object you can click on a tile around yourself and move the item to that locations, this is useful to stop getting yourself stuck and to move objects where you want them.

We currently lack this feature.

It would also be helpful for moving objects onto teleporters.

**Comment by Mute-Man** [comment]
![image](https://cdn.discordapp.com/attachments/668605946691452949/772587212960694282/unknown.png)
Bumping, because someone posted a good image of them being stuck.
