### ISSUE TITLE
Server Stability

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4670]
## Description

Our headless servers are suffering from a whole swathe of NRE's. We need to start providing solutions to solve them. This job is to outline what is required and can be open for an indefinite amount of time.

## Critiera:

- Join our discord server and find the ingame-errors channel:
![image](https://user-images.githubusercontent.com/20813925/88132339-8f19ab80-cc22-11ea-941c-00aed1e54436.png)
- Make sure you are up to date with the latest develop branch
- Start investigating the line numbers for each of the stack traces and error reports in the ingame-errors stream
- Try to find a solution or a stop gap to prevent the server throwing the exception
- If a solution cannot be found in a timely manner then apply a sufficient null check condition with a Log Warning added
- When submitting PR for the fix or fixes also add a comment to this ticket about what NRE was fixed and link it to your PR

**Comment by DooblyNoobly** [comment]
gingerbread0 has this one in progress

**Comment by DooblyNoobly** [comment]
Anyone can work on this issue. If you would like to help out and have not been inducted into the time tracking system pm me on discord.

**Comment by Bod9001** [comment]
no longer time bounty though still a relevant issue, in case needed in the future

**Comment by PerfectTangent** [comment]
closing this issue as it doesn't have a clear criteria for completion and it's long buried by now under tons of other issues.
