### ISSUE TITLE
Explosions dont remove pipes

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4676]
~Explosion code doesnt remove disposal pipes or damage players currently.~

Last thing to fix is removing pipes currently they are just disabled(#4738).

**Comment by corp-0** [comment]
@yoysam was this fixed by #4695 ? I didn't understand the PR description

**Comment by ThatDan123** [comment]
Pipe removal hasnt been added, but player damage was. Bod might be adding pipe removal in what hes working on atm.

**Comment by JesterX666** [comment]
Not reproductible

Before the bomb:
![image](https://github.com/unitystation/unitystation/assets/32009105/7d03f05a-6712-4b43-af23-6461bec18375)

After:
![image](https://github.com/unitystation/unitystation/assets/32009105/2d91c4d9-7cd3-40e8-8482-d14a1dcb8625)

We can clearly see the pipes are destroyed even those below the floor.

**Comment by corp-0** [comment]
woah what? When was this fixed? Does it also work with disposal pipes?

**Comment by JesterX666** [comment]
> woah what? When was this fixed? Does it also work with disposal pipes?

I'll try with disposal pipes.

**Comment by JesterX666** [comment]
> woah what? When was this fixed? Does it also work with disposal pipes?

Your intuition is right:  Disposable pipes are not destroyed.  Repopened.  I'm on it.

![image](https://github.com/unitystation/unitystation/assets/32009105/49859673-ed94-49ab-9d97-c8998e017bf7)

**Comment by JesterX666** [comment]
Cause :  when a disposable pipe is wielded it is transformed to a tile by ChangePipeObjectToTile()
At the present, before correction, there is no code to change back from tile to prefab when explosion occurs

**Comment by corp-0** [comment]
How are the other tiles handed? They can receive damage
