### ISSUE TITLE
Space Suit Storage

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4683]
![image](https://user-images.githubusercontent.com/56727168/88205963-71aa0900-cc45-11ea-81e7-9cf780bcf991.png)

Implement the suit storage unit, to store space suits.

Need to be able to specify which suit is inside when mapping.

**Comment by Nukeuler123** [comment]
Ill look into doing this. IIRC you can put people inside these storage units and "decontaminate" (kill them) want me to put that in too?

**Comment by PetMudstone** [comment]
Huh, I was actually implementing really basic Suit Storage Units before but got sidetracked. Were to act just like closets.

**Comment by Nukeuler123** [comment]
> Huh, I was actually implementing really basic Suit Storage Units before but got sidetracked. Were to act just like closets.

You wanna handle this one then or?

**Comment by PetMudstone** [comment]
I can add _really_ basic suit storage units and populators to fill different variants of them with. However, I don't have the expertise to implement stuff like decontamination or the storage slots and interface that suit storage units have in /tg/.

**Comment by Nukeuler123** [comment]
That should be good, just make an issue after you're done so someone else can work on the extra features.
