### ISSUE TITLE
Doors on Staging don't work

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4686]
## Description
Probably related to PR #4680 

On Staging, Doors don't open and the hacking interface might not initialize correctly

### Detailed Bug Report
* Hacking Interface is empty on-spawn, when it should have the wires needed for it to operate by default
* Can't make new connections between nodes, yes I had a wire in hand
* Doors don't open, maybe for additional/other reasons

### Steps to Reproduce
1. spawn in, try to open door
2. door doesn't open, so you open the panel check the wires on the hacking interface 
3. hacking interface is barren, so you try to make new connections (and remember to have a wire in the active hand)
4. clicking on the nodes does nothing, interface stays barren no matter what
5. Robust the door because it's impossible to open.

**Comment by ThatDan123** [comment]
Due to NREs, issue is known.

**Comment by NoooneyDude** [comment]
I believe this was fixed by PR #4691.

**Comment by corp-0** [comment]
One more confirmation and I close. What about the door switch nre at round start? Are you not experiencing that one?

**Comment by ThatDan123** [comment]
Yeah its been fixed.

**Comment by corp-0** [comment]
Closing, thanks
