### ISSUE TITLE
Lockers on Staging FallStation are Bugged

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#4687]
## Description
Lockers are missing items on-spawn

### Detailed Bug Report
Spawned as CE on FallStation
* Items in CE and Engie locker were rendered on top of lockers, instead of "inside" them
* CE locker only had the advanced hardsuit set and the CE's Cloak. No Toolboxes, Magboots, etc.

Something's causing the locker populators to not work

**Comment by Mute-Man** [comment]
Tested on Square, Lockers work fine there

**Comment by ThatDan123** [comment]
Fall is having nre problems, #4686 is linked.
