### ISSUE TITLE
cables, atmos pipes, and disposal pipes sprite layers inconsistency 

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#4701]
## Description
![image](https://user-images.githubusercontent.com/701959/88351843-130c8a00-cd2e-11ea-9855-108d610fd4de.png)
cables and disposal pipes seem to disagree with layers, going up and down depending on the type of cable and pipe on the tile

red cables are unaffected by this

**Comment by ThatDan123** [comment]
Also now happens with atmos pipes

**Comment by Aranclanos** [comment]
![pipes layer](https://user-images.githubusercontent.com/701959/96939086-65cb1e80-14a2-11eb-83c5-4c52d41bb3f5.gif)
an example of atmos pipes and disposals

**Comment by CdrCross** [comment]
I can confirm this remains a problem as of April 9th 2022.
