### ISSUE TITLE
Join Round Sync Loading Bar

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4708]
When you join an on going round that has been going for a while the sync will cause the joining client to freeze and if clicked will crash out. If you wait it will eventually join though.

If possible a loading bar should be implemented to avoid the crashing out, and to show the game is still doing stuff.

**Comment by NoooneyDude** [comment]
This is significantly less of an issue since the tile behaviour was tweaked and so this issue can probably be closed.
