### ISSUE TITLE
Update ML package to latest release.

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4718]
Add the package from the unity package manager (currently isnt package and stored in Assets) and update all the scripts to use the new system.

Last time this was update was last year and theres been a lot of updates since, hopefully boost performance of mobs.

Might require retraining of agents.

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md

**Comment by corp-0** [comment]
how certain are you that this will improve performance and what priority would you give it?

**Comment by ThatDan123** [comment]
Well currently every fixed update theres a spike for mob actions

![image](https://user-images.githubusercontent.com/56727168/88717491-893b3300-d118-11ea-9a84-cb777fa9ffa6.png)
That is just two mice in the scene, no other mobs, its a lot worse for a normal rounds as xenos are spawned on asteroids and the department mobs.

I would hope theres been an performance improvement since as it seems like its an internal issue, not something which we have done.

**Comment by corp-0** [comment]
aight, I will give this a try. I'm kind of afraid of updating it, honestly.

**Comment by corp-0** [comment]
yes, no. This needs to be done by someone who actually understands the library as a lot of logic must  be redone.

**Comment by PerfectTangent** [comment]
is this issue still relevant? I think the plan is to move away from ML Agents.

**Comment by pyrosshade** [comment]
https://discord.com/channels/273774715741667329/629136621006094337/814986297173213194
https://discord.com/channels/273774715741667329/312454684021620736/821697500573466655

As per these conversations it seems the consensus is indeed to move away from ML Agents

**Comment by PerfectTangent** [comment]
Righto. Closing.
