### ISSUE TITLE
Mob spawnpoints on maps that are activated by events.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4719]
## Description
We could use spawnpoints placed around maps that spawn mobs when certain events fire. For example:
- Spawnpoints in maint that spawn mice for a event that causes groups of mice to spawn in maint in order to chew up wiring.
- Spawnpoints around the outside of the station that spawn carp during a "carp migration" event.
- Spawnpoints in maint that spawn alien eggs/larvae during a "xeno infestation" event (could replace the random egg spawners).

**Comment by NoooneyDude** [comment]
What maps still lack maintenance spawns? All maps will now need to add "space exterior" points as of #5831, too.

**Comment by Mute-Man** [comment]
should someone set up an issue to track the status of which maps have a maint and "space exterior" spawns?

**Comment by NoooneyDude** [comment]
Yes I think that'd be most helpful. I thought one existed for maint. spawns, but couldn't seem to find it.

**Comment by Mute-Man** [comment]
according to #5346 all maps have "fugitive" spawnpoints, but I don't actually know if that means that all maps have maint. spawns.
I'm just gonna make an issue for "space exterior" spawns.

**Comment by NoooneyDude** [comment]
Hmm. Fugitive spawnpoints do use maint. spawnpoints yes, though I suspect there may not be enough of them in every map. I think at least a dozen of maint. and space exterior spawns would be acceptable - for the bigger maps, anyway.

**Comment by Mute-Man** [comment]
Should probably come up with guidelines for how many spawns to put in, and where
I can't really make a checklist if I don't know what conditions need to be met.
Oh yeah, side note, who can actually tick the check boxes on Github issues?

**Comment by NoooneyDude** [comment]
Repo maintainers and the OP can check the boxes.

**Comment by corp-0** [comment]
closing in favor of #5832
