### ISSUE TITLE
The ability to use objects that occupy the same tile as a wall (buttons, switches, APCs) from an extra tile away.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4720]
## Description
In /tg/, you could use objects that occupied the same tile as a wall such as light switches, buttons, and APCs from an extra tile away due to a quirk of how they were mapped. This was a very useful quirk since those things often appeared across tables and what-not and the ability to use them from an extra tile away made them still convenient to use. However, you have to be directly adjacent to the wall said objects are on in Unitystation to use them which causes some issues.
![image](https://user-images.githubusercontent.com/38266309/88470157-cc459e00-cead-11ea-83e2-bf6adc5e70af.png)
For example in the above image, the switches for the blast doors and mass driver are on a wall. If this were /tg/, you could just click them from two tiles south or southeast across the table. However in Unitystation you have to be right next to said switches to use them you have to climb onto the table to open the blast doors and activate the mass driver, which proves annoying.

**Comment by Ruzihm** [comment]
@PetMudstone  If a player is at the position to the right of the chair, marked X below, should the player be able to interact with the switches?

![x to right of chair](https://i.imgur.com/OCYr5l3.png)

**Comment by PetMudstone** [comment]
I think by /tg/ logic, you wouldn't be able to.

**Comment by Ruzihm** [comment]
@PetMudstone  Pardon the hackjob photoshop here but in this picture below, which positions (lettered A-G) should be able to interact with the switches on the corner?

![image](https://user-images.githubusercontent.com/966423/98761415-6240fe00-23a3-11eb-9600-2e2f114ae03b.png)

I assume not G because a window is in a way. But until the last post, I would have guessed all of  A-F should interact. Is that not the case? Maybe only B, C, D, and F?

**Comment by PetMudstone** [comment]
Eh, keep it A-F for sake of consistency.

**Comment by NoooneyDude** [comment]
In /tg/, the wallmounts are actually not on the wall, but on a tile in front of the wall - just the sprite is offset onto the wall. Reach code was not altered, so the eight tiles around the real wallmount position can reach it. It also solves visibility problems (which sides of the wall should be able to see it?). However, in Unitystation the wallmounts are actually on the walls and you can't actually see a wallmount if it is on a corner tile, but it is facing the side that you're not on.

So if that switch wallmount is facing down, then you couldn't view (and so interact) with it from A - C.

**Comment by Ruzihm** [comment]
@NoooneyDude If that's the case, then you wouldn't be able to interact with it from D or E either right?

**Comment by NoooneyDude** [comment]
Yep, that's exactly right.

**Comment by Ruzihm** [comment]
If that is the desired behavior, then it certainly seems like the change should be done in offsetting the sprites. With that in mind, I'm going to roll back my (buggy) fix for this and reopen it.

**Comment by NoooneyDude** [comment]
Alright. We'll probably need new code for offsetting the sprite dynamically based on the set direction, and, when determining reach, getting the actual gameobject position and not the sprite object's position. Not sure how that would be handled at the moment. There's a bunch of code for determining wallmount visibility, too, that could be removed.

I do remember there were one or two quirks to having the wallmounts offset like in /tg/, but I can't remember them.

**Comment by PetMudstone** [comment]
This needs to be reopened after the changes in #5589. New issue for automatic sprite offsets perhaps needed.
