### ISSUE TITLE
The ability to view a player's inventory as an admin.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4721]
## Description
The ability to check a player's inventory somehow as an admin would prove useful for moderation. For example, if someone is suspected of stealing something important while they were a non-antag without proper justification in doing so, an admin could view their inventory to see if they do indeed have those stolen goods. It would also be useful if someone raids the armory as an non-antag and an admin needs them to return their stolen weapons. The ability to view their inventory would help confirm for admins if the offending player kept to their word and returned everything or not. 

I imagine this would be a functionality of a-ghost, though perhaps it normal player ghosts could use it too. I do fear that the ability for normal player ghosts to view the inventories of living people could result in metagaming however.

**Comment by NoooneyDude** [comment]
Somewhat related to #4379.

**Comment by PerfectTangent** [comment]
fixed by #5879 and #5912
