### ISSUE TITLE
Bug: Player is able to press ready even though "None" is selected for all Job Preferences

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4722]
## Description
A Player can select "None" Priority for all Job Preferences and click the ready button. When the pre-round countdown timer hits zero and the round starts, the player is not given a job and gets stuck looking at space.
### Detailed Bug Report
GUI_PreRoundWindow.cs has a function called private void SetReady, which does not check the Job Preferences when clicked. I'm not sure if a check should be placed there or somewhere else in the code.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Open up Character ->Job Preferences 
2.  Select "None" Priority for all Jobs
3.  Click Apply
4. Navigate to PreRoundWindow and select Ready
5. The PreRoundWindow should disappear when the countdown timer reaches 00:00 and you are now stuck.

**Comment by Nukeuler123** [comment]
nabbing this one
