### ISSUE TITLE
Players unable to move at round start.

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4728]
On some round starts players are not able to move until they reconnect.

Occurs if a player readies up, not if joining after round start.

There is no client side error or known server error.

![image](https://user-images.githubusercontent.com/56727168/88581061-8242f080-d044-11ea-8239-366ba07e9388.png)

![image](https://user-images.githubusercontent.com/56727168/88581078-87a03b00-d044-11ea-9f69-c243df7090cb.png)

**Comment by NoooneyDude** [comment]
Is this different from issue #4254?

**Comment by ThatDan123** [comment]
Ah i did do a search before opening this, guess i missed it. It is virtually the same, but people were saying it happens if you ready up and not if you join after start.

**Comment by Akbadain29** [comment]
Interestingly, while you cannot pick up or move around (but still use the chat to talk), you can throw objects from your spawned inventory no problem. These objects are thrown from your original spawn position that you are not currently in, making it look like the objects are being thrown by a ghost. Why does that still function? Is the throwing managed server side only?

I should also add that I didn't ready up and I still got it.
