### ISSUE TITLE
Antags Objectives Can have Centcom Officals As Targets

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4735]
Need to add a check for objectives to not choose specific job types to avoid the situation in the title.

-Causes issues for mid round traitors.

**Comment by corp-0** [comment]
What issues? Are the officials not present in the station?

**Comment by ThatDan123** [comment]
Yeah, theyre not necessarily on the station.

**Comment by yoysam** [comment]
working on this
