### ISSUE TITLE
Client Tile Sync Issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4741]
If a client logs out and back in any ore they have mined will have that effect reappear.

Also its been reported that there will be indestructible walls on asteroids after relogging.

**Comment by corp-0** [comment]
you think this should have high priority?

**Comment by ThatDan123** [comment]
In a way but also not as it only affects clients which have to rejoin a round, but for them its bad.

**Comment by ThatDan123** [comment]
Dont think this is an issue any more so closing
