### ISSUE TITLE
Client hangs when attempting to join while server is loading scene

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4745]
## Description
On staging (sometimes while connecting to a local server, too) client sometimes hangs when attempting to load scene.

### Steps to Reproduce

1. Join staging.
2. Restart the round.
3. While the client is loading the scene, it may hang. If not, repeat steps 1. to 3.

**Comment by corp-0** [comment]
I think it is directly related to #4743. Same NRE if you get the staging logs

**Comment by NoooneyDude** [comment]
It doesn't appear to be the same bug as I have fixed that in my latest PR #4744, so I've added the High Priority label.

**Comment by NoooneyDude** [comment]
This issue seems to no longer be the case - as of staging build 3975. Will close it for now. Update: seems #4951 fixed this! Yes!
