### ISSUE TITLE
Jukebox Volume Slider doesn't register click every time.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#4761]
Jukebox volume slider doesn't registrer click and drag correctly.
Also, we can see that the "handle"  doesn't even register the mouse over color change!
I've tryied solving it but can't find the cause.  (I'm not very good in Unity UI).

It might be something related to Raycast target, bounding boxes, placement of controls and such.

It might even be simple enough to be a good first issue.  No code is involved.

Steps to reproduce:

1.  Click on the jukebox
2.  Try to move the volume handle (doesn't work)
3.  Click somewhere like the middle of the slider
4.  Now the volume handle works.

**Comment by Korywon** [comment]
The volume slider looks disproportionately small. Increasing the size of the handle and slider solves this issue and makes it look a little better.

Is anyone planning on improving the GUI for the Jukebox? It seems a little minimal at the moment.

**Comment by ThatDan123** [comment]
This is just version 1, so i expect it'll be improved in the future. Jester has this idea too #4754 . Not sure if theyre working on this or the sickness stuff. But you can work on improving the juke box if you want, though talk to Jester as they might also have some more ideas about the next features. 

If you're talking about pure UI aesthetics, talk to Cross on the discord, the UI team might have looked at this.
