### ISSUE TITLE
Kitty ears should have the same color as the wearer's (non-facial) hair.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4770]
## Description
Title. In /tg/ kitty ears when worn take on the color of the wearer's hair (not their facial hair, the hair they have on their cranium). This would be cool, I think.

**Comment by BootlegBow** [comment]
I guess this shouldn't be too hard

**Comment by corp-0** [comment]
I don't think our kitty ears are paletteable, that might be the only thing stopping us.

**Comment by Fogapod** [comment]
Does this mean tail must have dynamic color too?

**Comment by PetMudstone** [comment]
Yes. The tails and ears are part of the same sprite, actually.

**Comment by PerfectTangent** [comment]
now that we have cat people in the game and we do not need to rely on the cat ears item, is this issue still relevant?

**Comment by MaxIsJoe** [comment]
> now that we have cat people in the game and we do not need to rely on the cat ears item, is this issue still relevant?

I think yes, Cat people can only have customizable cat ears and tails but other races who wear that item won't have their color's synced with their hair.

**Comment by MaxIsJoe** [comment]
Why was this locked? I just said that we still have this issue with the item it self.
