### ISSUE TITLE
Sickness system - Iteration 1

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#4776]
Includes a basic sickness system

- Comprises at least 4 different basic sickness, including Space Cold, Space Flu.  + at least two more to determine.
- Known sickness can be spawned by admin event.
- Sneezing and coughing will be contagious, spreading the sickness on whoever step in the contagious area before it dissipates.
- Will comprise the following 5 symptoms : Wellbeing, Immune, Sneeze, Cough, Custom Message ("You don't feel well", *hiccups**, "you swear you saw something move in the corner of your eye." etc.)
- Will include a component to create new sicknesses
- Sickness will be contagious or not.
- Sickness will be made of different stages, with a time elapse between each stage
- Symptoms will trigger at random between min and max parametrized interval

Sickness in that iteration should not kill or impair gameplay by a lot as **there will be no cure**. (See iteration 2).

A percentage of the players starts with mild allergies (making them sneeze or cough at random).  This will not be contagious and won't have any side effect.  The purpose of this is to hide a real sickness.  Without this, as soon as someone cough or sneeze, people will know there is a real sickness starting.

**Comment by GenericDaemon** [comment]
Does death and cloning cure the disease

**Comment by JesterX666** [comment]
> Does death and cloning cure the disease

It might.  Should it?
