### ISSUE TITLE
Sickness system - Iteration 2

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#4777]
Will improve the iteration 1 sickness system.

- Virologist will be able to take samples, analyse them and make assumptions on basic cure.
- The more sample from different people, the more the analysis will be precise and the more the cure is likely to succeed.
- Said cure could be made by the chemist.
- Will add at least 3 more basic sickness
- Will add the possibility for the admins to spawn a round custom unique sickness
- Will add those symptoms : Bleed, Malaise (will not be able to run), Dizziness (similar to alcohol visual effect), Fall on the floor, Inflict damage, Death by GIB, Confusion (mix up controls)
- Wearing mask or helmet will reduce and/or eliminate the sneezing / coughing contagion zone.

**Comment by PerfectTangent** [comment]
closing because Jester's MIA and Max has taken the sickness system in a different direction.

**Comment by MaxIsJoe** [comment]
> closing because Jester's MIA and Max has taken the sickness system in a different direction.

It's not really a different direction, it's just cleaning up some incredibly bad code and system desgin and actually adding some functionality into some of the sicknesses that we have instead of just cough cough sneeze sneeze.
