### ISSUE TITLE
Clothing items that have toggleable lights should have different worn sprites depending on their light state.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4779]
## Description
In /tg/, clothing items that have built in lights have different worn sprites depending on if the lights are turned on or off. It should be the same case here. While you can change the sprite of a clothing item's inventory icon depending on their light state, it doesn't apply to worn sprites yet.

**Comment by NoooneyDude** [comment]
Depends on issue #2594.

**Comment by jamessimo** [comment]
I’ve noticed PDAs do this. How do they get around issue #2594 not being finished?

**Comment by corp-0** [comment]
We can do this now as I have seen helmets and torches do it. I imagine any other object that should and doesn't is because we just haven't set the sprite.

**Comment by PetMudstone** [comment]
Checked and every hardhat and hardsuit helmet has different sprites depending on light status now. Closing.
