### ISSUE TITLE
Pogstation "cargo console" NRE

### ISSUE THREAD

**Issue by Nukeuler123** [unitystation/unitystation#4796]
## Description
Im not fixing this issue myself because im scared to touch the map myself but im hoping it's as simple as adding the "Cargo Console" component. This issue produces an NRE when you click on the console, the NRE simply means that the object is missing a component. My recommended fix would be to simply replace it with a "Supply Console".

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Find the supply console named "Cargo Console" (near where the shuttle docks)
2.  Click on it
3.  NRE

**Comment by PerfectTangent** [comment]
This appears to no longer be an issue. Closing
