### ISSUE TITLE
Skeletons attack the floor tiles on the Dark Jungle Map

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4799]
## Description
Skeletons (as pictured below) attack the floor tiles in this room inside the Dark Jungle Map. It is expected that they are able to smash windows and tables, but not punch a hole into space.

https://cdn.discordapp.com/attachments/668605946691452949/741137269146255465/Annotation_2020-08-06_233442.png

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Select Dark Jungle away site on round manager in admin panel
2.  Restart round
3.  Wait for the portal to connect and head through it
4.  A-Ghost and move towards the top right corner where the exit portal is
5.  Observe the skeletons

**Comment by corp-0** [comment]
Were they targetting a player when you found about this?

**Comment by PerfectTangent** [comment]
I was the one who found the bug. They had already punched through the floor when the players arrived.

**Comment by PerfectTangent** [comment]
mobs can't attack tiles in any way currently, so this bug is no longer relevant.
