### ISSUE TITLE
Game Matrix - Discussion

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#48]
We need to develop a realtime collision matrix of our own that knows where collide-able tiles and objects are at all times so that we can check if our player can move into that space with our player move components. Or if two players are trying to occupy the same grid co-ordinates then the matrix should move both the players so that they are side by side.

The Game matrix will do this by returning the grid co-ordinates to our player move component while doing all of the necessary checks before hand to see if it is:

- Passable (like walls and tables, in which case we don't allow our player to move into that grid)
- Is another player (In which case if both players are trying to stop on the same tile, then move them apart)
- Our current intent (if it is harm or grab then we need to push the other player out of the tile)

I'm hoping to remove the player from being moved by the rigidbody2D component and using a transform.move function instead and then having a separate object that will follow the player with a rigidbody to do all of the trigger stuff like opening doors, detecting if you are in space etc)

This matrix then could form the foundation for lighting and the atmos tile graphics. 

I've opened this issue so it could be used for discussion on how to best create a matrix as this could end up being pretty complex..

**Comment by DooblyNoobly** [comment]
@Gavinvin this was originally something you thought of and I was wondering what your thoughts were

**Comment by DooblyNoobly** [comment]
I've also uploaded a video from the byond version: https://vimeo.com/195087109

It shows colliding with another player with the grab intent on and then with the help intent on.

P.S the black tile is because I'm running it through Wine on macOS.

**Comment by krille90** [comment]
How about we let tiles "register" to their specific grid cell? e.g. when a wall is placed, it will register to the Game matrix and block the cell it is standing on. Each cell would have a state from an enum, e.g. PASSABLE, WALL, DOOR, CLIMBABLE (e.g. tables), etc..

I also would say, that stuff like floors and items, wouldn't have to register, since it doesnt matter.

Although I don't know yet how players and intent could be handled.

**Comment by DooblyNoobly** [comment]
I started something for a very specific purpose (adding items to cupboards across all clients): https://github.com/unitystation/unitystation/blob/master/Assets/scripts/GameMatrix.cs 

To add the item to the cupboard each client needs to know the viewID of the cupboard and the item which is stored in a dictionary synced for all players. Then on sync the client can know which items need to be in the cupboard or not. Along with adding items at runtime. 

Lets evolve this over time to handle anything matrix related (item positions, atmos levels, apc power levels etc), I will eventually make a separate component to handle the master create/destroy RPC methods which you can see in the script.
