### ISSUE TITLE
Server Player Cap

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4803]
- [x] Add a player cap that is set in the config json.
- [x] Add a check in the playerlist script for when players join to check whether the current number is under the cap.
- [x] Let admins skip the check
- [x] Put the check after the rejoin check to allow players who disconnect mid round to join back even if over cap.

#### Notes 

- Make sure you put a reason why the client wasnt accepted.

**Comment by PerfectTangent** [comment]
completed by #8209.

**Comment by corp-0** [comment]
> Put the check after the rejoin check to allow players who disconnect mid round to join back even if over cap.

are you sure this is working?

**Comment by PerfectTangent** [comment]
> -Excludes admins _and players that joined once during a round_ (clears and repopulates at round end to remove players that have left)

says so in the PR.
