### ISSUE TITLE
The stars from the space background can be seen on some station objects

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4839]
## Description
LastCaptainBonk has discovered that windoors, the plasma generator smoke puffs and possibly anything else transparent (chem beakers) are transparent enough to let the stars appear if the light sources aren't bright enough.
It could be a layering issue, as the floor tiles don't exhibit the same problem.
Screenshots:
https://media.discordapp.net/attachments/668605946691452949/742962973437329428/Screen_Shot_2020-08-11_at_9.29.29_PM.png (plasma generator smoke)
https://media.discordapp.net/attachments/668605946691452949/742961530034978906/Screen_Shot_2020-08-11_at_9.23.31_PM.png (windoors)
https://media.discordapp.net/attachments/668605946691452949/742966046499012628/Screen_Shot_2020-08-11_at_9.41.31_PM.png (beaker)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Kill the lights on the station
2.  Zoom in the transparent object to see the stars

**Comment by ThatDan123** [comment]
Windows/Glass was fixed in #4971. So needs to be tested with the other objects as it might be fully fixed.

**Comment by NoooneyDude** [comment]
Looks like all instances of the issue were fixed by that PR. Closing.
