### ISSUE TITLE
Player sometimes is told that they don't have their prefences set, even though they have set them.

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4848]
## Description
After #4722 was resolved, we got reports stating that sometimes the ready up button doesn't recognise preferences the player has selected and displays the warning. 
https://cdn.discordapp.com/attachments/273774715741667329/743350493593468938/Scr_2020-08-04_10.03.32.png (photo of error)

### Detailed Bug Report
It may/may not have something to do with how the SetAssistantDefault or LoadJobPreferences methods function, as it is intermittent bug, which can't be accurately reproduced yet. I'm going to assume you have to be pretty quick when choosing your job preferences and readying, as it may be taking some time for a method to update?

### Steps to Reproduce
1.  Open up the job preferences menu?
2.  Quickly select your preferences and close it?
3.  Ready and receive the message that you haven't selected any preferences?

**Comment by NoooneyDude** [comment]
There has been a lot of changes to character preferences. Reopen if this is still an issue.
