### ISSUE TITLE
MainStations, Away Sites and Centcoms require Lighting adjustments

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4849]
## Description
Since whatever PR it was, the lights have had their code changed. All the maps need to have the lighting redone as a result of this because they are blinding or too dark. They'll be ticked off below when they are not so bright or pitch black.
##Maps
- [x] BoxStationV1
- [x] FallStation
- [x] OutpostStation
- [x] Pogstation
- [x] SquareStation
- [x] AncientTemple
- [x] Caverna
- [x] DarkJungle
- [x] Palace
- [x] Relicta
- [x] CentCom
- [x] Fallstation CentCom
- [x] Lavaland

Change the cargo shuttle wall layer to wall to stop bullets passing though

**Comment by ThatDan123** [comment]
Just Pog Left

**Comment by corp-0** [comment]
was Pog updated? @PetMudstone

**Comment by PetMudstone** [comment]
Not with new lighting, no.

**Comment by corp-0** [comment]
does it look bright as fuck?

**Comment by PerfectTangent** [comment]
I'ma check

**Comment by PerfectTangent** [comment]
yeah, there's a few oddities with the lights. Lots of things are over exposed, and I found a couple places where there's duplicated lights on top of eachother. Pog needs a lighting pass.
