### ISSUE TITLE
Permadeath should be enabled through the Server Config file

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#4853]
## Description
Some players who will play UnityStation in the future may object to the use of cloning in the health system and want it removed as they have become accustomed playing it without it. I think we should make it possible for the Server Config File to enable permadeath.

So when it is turned on it:
1. Switches the cloning tube and the cloning console out for medical crates full of medical supplies or cyrotubes etc. It would have to be a custom script which has an inspector component, allowing you to set the object to be on the switch-out-list.
2. Sets a boolean inside OnServerSpawn() for some objects to be false so it doesn't spawn them in, even if they are admin spawned.
3. Makes it impossible for the admin to respawn players back into their original role, but still allows the admin to respawn them as a centcom intern, syndicate or other antag later in the round.

**Comment by corp-0** [comment]
sounds more like a server config file thing than a button in round manager, unless that's a thing in byond?

**Comment by Akbadain29** [comment]
No, it's not. I couldn't remember our previous discussion about it properly, I'll change it to server config like we discussed.
If it's like that it won't suddenly revert every build update right?

**Comment by PerfectTangent** [comment]
we now have alternative forms of resuscitation, so this issue isn't relevant anymore. If people do not want to have a cloner in their game, they can simply remove the cloning pod from their maps in their own build of the game, but idk if there's even a market for people interested in that, currently.
