### ISSUE TITLE
Projectiles fired out of a gun should depend on the ammo used instead of the gun itself.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4862]
## Description
Title. Right now guns determined the projectile that is fired and not the ammo that is loaded into it. This means that sawn-off shotguns will always fire non-lethal stunning projectiles even if lethal slugs are loaded into it and other shotguns will always fire lethal slugs even if you load lethal rounds. What variety of ammo you load into a gun doesn't matter as long as you can load it.

### Steps to Reproduce
1.  Empty out a Riot_Shotgun_Ballistic and Sawn_Shotgun_Ballistic (probably by firing it till it's emptied).
2.  Spawn two Magazine_Shotgun_Slug and Magazine_Shotgun_Beanbag each, supposedly lethal and non-lethal shots respectively.
3.  Spawn a HealthAnalyzer.
4. Load one Magazine_Shotgun_Slug and Magazine_Shotgun_Bean bag each into the riot and sawn shotgun.
5. Shoot yourself (remember to heal), notice that effects and damage remain the same between the two shots that each shotgun has.

**Comment by corp-0** [comment]
> I would put a steps to reproduce section here if bullets weren't somewhat bugged at the moment. Right now they all seem to do the same damage on latest and beanbag projectiles don't stun

this sounds like it should be its own issue reporting the bug.

**Comment by PetMudstone** [comment]
Resolved,. Different ammo can now give different projectiles thanks to Autumn. I forget which PR did it though, whoops.
