### ISSUE TITLE
Bullet damage scriptable objects mostly share the same damage values.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4864]
## Description
Title. For some reason most of the SOs in "Assets\Resources\ScriptableObjects\Gun\DamageInfo" share the same damage of 15. At time of writing only Bullet_KineticShot and Bullet_Sniper do different damages.

**Comment by ReiderJack** [comment]
Yeah, i was lazy to properly assign values to them.
*someone* needs to do it...

**Comment by PetMudstone** [comment]
i'll try to do it today with muh bullet .prefabs. Thankfully, I have access to original /tg/ code as well.
