### ISSUE TITLE
Mainstations, Away Sites and Centcoms require piping changes!

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#4874]
After #4859 a new gas piping system was introduced and the maps need to update and integrate the new stuff.

This issue exists to keep track of the progress on this task:
- [x] BoxStationV1
- [x] FallStation
- [x] OutpostStation
- [ ] Pogstation
- [x] SquareStation
- [x] AncientTemple (Optional)
- [x] Caverna (Optional)
- [x] DarkJungle (Optional)
- [x] Palace (Optional)
- [x] Relicta (Optional)
- [x] CentCom
- [x] Fallstation CentCom
- [x] Lavaland (Optional)

Note from ThatDaniel: When you map pipes try to go through maints as well, makes them look better, and actually useful, having a loop in the main hallway is good too. See the Box station pipe mapping for a good example. This does mean it will take longer, but means it wont have to be redone later.

**Comment by corp-0** [comment]
Daniel is working on Box and Square.

**Comment by ThatDan123** [comment]
For the awaysite they shouldnt need changing too much unless a pipe systems wants to be added, eg for relicta

**Comment by corp-0** [comment]
aight let's tick all of them then

**Comment by corp-0** [comment]
same with lavaland, I assume

**Comment by ThatDan123** [comment]
I changed it to Optional

**Comment by corp-0** [comment]
@the-other-autumn what's the state of Fall after #4957 ? PR says nothing in the description.

**Comment by AutumnNova** [comment]
the atmos is entirely finished on fall

**Comment by ThatDan123** [comment]
Just Pog Left
