### ISSUE TITLE
You should be able to walk from table to table once you've climbed on top of them.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4879]
## Description
In /tg/, you can just walk from one table to another once you climbed on top of one. In Unitystation, you have to slowly climb onto other table tiles even if you've already climbed on-top of one. The ability to walk on top of tables after you have climbed on top of them would make moving across them a bit less annoying. In relation to #4878, you should be able to walk from crate to crate or other climbable objects or from an object to a table or a table to an object.

**Comment by PerfectTangent** [comment]
added in #5344
