### ISSUE TITLE
Admin spawn of grenade prefab crash connected clients

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#4889]
## Description
Title. No idea what is so special in grenade prefab. Client just freeze and can be killed only by task manager.
Using connected debuger it seems that server send a lot of spirte changes packets. Maybe it loops client to death.

### Steps to Reproduce
1.  Connect client to server
2.  Spawn grenade using admin tools

**Comment by PerfectTangent** [comment]
I have been unable to reproduce this issue. Closing for now unless we get a new report.
