### ISSUE TITLE
Fix machine construction

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4910]
So some the machines which can be built dont have a Machine component added so dont despawn when built.

All the buildable machines will need to be checked:
![image](https://user-images.githubusercontent.com/56727168/90481100-1c202980-e129-11ea-8b10-69fe96f1448e.png)

And if they are missing the Machine component:

![image](https://user-images.githubusercontent.com/56727168/90481133-2e01cc80-e129-11ea-962a-693dc63a1b14.png)

Add it and fill in the values:

![image](https://user-images.githubusercontent.com/56727168/90481177-4376f680-e129-11ea-828a-1709f139f00b.png)

**Comment by PetMudstone** [comment]
This is my fault and so I ought to be the one to deal with it.
