### ISSUE TITLE
Window won't stay maximized

### ISSUE THREAD

**Issue by kdkaergaard** [unitystation/unitystation#4914]
## Description

When running in windowed mode, the window won't stay maximized.
up to one second after being maximized, it will pop out of maximized state, and be slight offset from the top and left edge of the screen.
Something like this seems to have been reported before. #836

### Detailed Bug Report
I suspect only the display and its configuration is interesting here, so i'll include that for now.
I have two DELL U2515H 25" monitors installed. One horizontally oriented, and the other vertically oriented on the right side.
The first is set as 2560x1440 and the other as 1440x2560.
Maximizing the window on either of these produces the same result.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Get a 25" monitor, i suspect. 💸
2. Configure it for 2560x1440 resolution.
3. Start game in windowed mode.
4. Maximize the game window.

### Extra
If you need me for some interactive debugging, i am available in GMT+2 usually between 8pm and 10pm.

**Comment by LittleNyanCat** [comment]
1+,  having the same issue.

I have two monitors, both in landscape mode but with different resolutions (1920x1080 & 1366x768), maybe this issue is due to monitors with different resolutions?

Also I noticed something interesting, if you maximize the game while it is still loading it will remain maximized, until you reach the character settings menu.

I don't have issues with other unity games, which is something I find really odd.

**Comment by LittleNyanCat** [comment]
Since it may a little vague to say the window "won't stay maximized" here is a visual example:

https://i.gyazo.com/66089688f5c33622dd4fd29bd0b44b52.mp4

@kdkaergaard, does it look like this to you too?

**Comment by kdkaergaard** [comment]
> https://i.gyazo.com/66089688f5c33622dd4fd29bd0b44b52.mp4

This is exactly what I am experiencing. 😁

**Comment by sigfalt** [comment]
+1, possibly (re)introduced in #4261 with the same cause as mentioned in #836. When maximizing on my 1440p landscape monitor, the window resolution is 2560x1417, with the Windows title bar taking 23 pixels off the height.
