### ISSUE TITLE
Remove Syndicate Base From Scenes

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4919]
Syndicate bases needs to be removed from map scenes as its now on its own scene

- [x] Square Station

- [x] Box Station

- [x] Fall Station

- [x] Pog Station

- [x] Outpost Station

**Comment by corp-0** [comment]
only pog and outpost are left to close this

**Comment by ThatDan123** [comment]
Just Pog Left

**Comment by corp-0** [comment]
only Pog is missing 💢

**Comment by PerfectTangent** [comment]
this isn't very poggers
