### ISSUE TITLE
Short tracks should play when you spawn as an antagonist

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4932]
## Description
In /tg/, short snippets of audio play when you spawn in as an antagonist. Audio file for [traitors](https://cdn.discordapp.com/attachments/390288738418294784/746178343644299264/tatoralert.ogg). Audio file for [nuclear operatives](https://cdn.discordapp.com/attachments/390288738418294784/746178476855263232/ops.ogg).

Not only would this provide a nice little touch, this would also alert players that they are an antagonist. This should let them know that they should take notice of their objectives immediately.

**Comment by PerfectTangent** [comment]
the system was added with #5125 and the sound effects were added in #5524. The Fugitive and wizard are still lacking sounds.
