### ISSUE TITLE
AssetManager, AssetLoading Screen and Lobby Music converted to addressables

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4936]
## Description:

We need to start porting all of our assets to addressables / assetbundles and loading them from the CDN as soon as possible. This job is to start the process of converting the lobby music assets and the AssetManager to do validation and control a asset loading screen.

## Criteria:

Loading Screen:
- Add a new Canvas in UIManager so you can show and hide a asset download screen and that it appears over all other screens
- On this screen add a loading bar and a text label to display the status to the player
- Find some art work to plonk on the background of this scene for the time being
- Make sure the layout settings are correct that the screen works for all screen sizes

Lobby Music:
- This might have to be a job for Reider as all of the music is in a giant sound manager prefab
- Find a way to separate the lobby music from the prefab and turn them in to their own prefabs
- Add them to an addressable group
- Build assetbundles and upload them to cdn
- Add logic in SoundManager to check for new version of the assetbundles, download any missing ones and to display status by using the Loading Screen

AssetManager:
- Add a new static manager called AssetManager to the Managers prefab
- Develop the public methods that allow you to send an asset pointer (like a AssetReference or path string) along with a callback action for it to be invoked when the asset has finished downloading. If it already exists in cache this will just invoke the callback immediately. 
- While the async operation is running this method should also open the loading screen and update the loading bar and status text and also close it when it has finished
- Maybe we need a Queue so we can Queue up assets waiting to be downloaded?

**Comment by corp-0** [comment]
last thing I knew about this is that lobby music can't be moved to addressables because you're not connected to the server yet when in lobby, but we moved all sounds to addressable. Can we close this one now?

**Comment by corp-0** [comment]
It wasn't done exactly how the criteria was thought initially, but we have most of the job ready. Closing for now.
