### ISSUE TITLE
Objects that are "behind" (have a higher-Y transform than) other objects should automatically render below them.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4937]
## Description
It should be that if another object is at a higher Y level/transform value than another object, then that object should automatically render under the object that is at the lower Y level. With the common 3/4 perspective used it seems that the lower the Y-level is on an object the more to the "front" it is. 
However, objects that logically should appear behind other objects due to Y-level differences will render above whatever they ought to be behind if they're on a higher layer. Check the below image for an example of a player standing behind a microwave yet rendering on-top of it.

### Steps to Reproduce
1.  Go to Outpost Station.
2.  Go to the kitchen and stand on the tile above a microwave.
3.  See that despite you logically standing behind the microwave you appear in front of it, some how.
![image](https://user-images.githubusercontent.com/38266309/90905413-00b15a80-e385-11ea-9e75-3548bfa6d7cc.png)

**Comment by corp-0** [comment]
https://www.youtube.com/watch?v=CTf0WjhfBx8 I guess this is related but I don't really know much about our sprite system.

**Comment by PerfectTangent** [comment]
This was done iirc, but I can't find the PR because it's impossible to parse the meaning of some of Bod's PR titles. closing.
