### ISSUE TITLE
Unable to place wrenches onto tables since you'll try to deconstruct them instead.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4940]
## Description
Title. Trying to put a wrench on a table makes you try to deconstruct it regardless of intent. This is somewhat annoying.

**Comment by NoooneyDude** [comment]
I believe in SS13 the solution is to drag it onto the table, right? Or does it use the intent system?

**Comment by corp-0** [comment]
deconstruct should only happen on disarm intent, I think.

**Comment by PetMudstone** [comment]
Hmm, I did some basic code regarding intent based interactions in #4362. However, that was just for one script and it only checked for harm intent. Perhaps a more robust system would be in order for determining intent for interactions.

**Comment by corp-0** [comment]
More robust? What's wrong with comparing ``interaction.intent`` ?
