### ISSUE TITLE
Adjust health values of all tiles to reasonable levels.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4941]
## Description
Since most tiles in Unitystation are based on "turf" from /tg/ that don't use integrity like objects, the integrity values used for tiles are a bit... off. Right now a simple low-yield water-potassium explosion can immediately cause a hull breach through the floor. 

The integrity values for windows have already been dealt with and it should be easy to apply proper values to lattices, catwalks, grilles, and tables since they're actually objects in /tg/ and therefore use actual integrity values there.

**Comment by Emma3DSS** [comment]
Yo ill do this real quick
