### ISSUE TITLE
Atmos Pipes Performance Issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4952]
Calling setup neighbours every frame is decreasing performance. This is a headless server deep profile.

![image](https://user-images.githubusercontent.com/56727168/90978717-c217cd80-e547-11ea-9d3d-282dc60a7ab2.png)
Fall Station, with just vents and scrubbers, not the pipe system

![image](https://user-images.githubusercontent.com/56727168/90978718-c47a2780-e547-11ea-862d-1281218b846f.png)
Square station with the pipe system.

**Comment by NoooneyDude** [comment]
Was this fixed by #5004?

**Comment by Bod9001** [comment]
need some testing, the wind is probably a bit laggy still

**Comment by corp-0** [comment]
now that Aran moved pipes to atmos thread, what's the state of this one?

**Comment by corp-0** [comment]
@Aranclanos can you tell?

**Comment by ThatDan123** [comment]
Dont think this is an issue now
