### ISSUE TITLE
You can open/close lockers two tiles distant, if you click the door hinge

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#496]
# Preliminary information

## Category
Bug

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
Clicking the exact pixel of the locker door hinge allows a locker to be opened and closed when it is at a distance of 2 tiles. Clicking the door or the locker itself works as expected.

## Expected/Wanted/Requested Behavior
Hinges should conform and not get special treatment.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. Find a locker.
2. Step 1 tile away from the locker.
3. Find the hinge pixel and click like a madman. (May take several tries to find the pixel)

## Notes:
![lockerhinge](https://user-images.githubusercontent.com/15195221/33516273-c76c6992-d778-11e7-926a-b37f64e11f0c.gif)

**Comment by Em3rgencyLT** [comment]
Wait but... If I click the open DOOR, which is closer than the hinge, it correctly does not close at that distance. I understand why the distance is like this (I had to solve the same issue with alt+lmb inspect), but why is it registering on the hinge pixel?

**Comment by rmhenn** [comment]
maybe the opened sprite has the same hitbox as the closed sprite

**Comment by Em3rgencyLT** [comment]
The raycast for item interactions is pixel perfect. But yeah, I haven't investigated the cause of this yet, so no idea.

Good guess!
