### ISSUE TITLE
You can open/close nearby lockers while locked inside one.

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#497]
# Preliminary information

## Category
Bug

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
If you're locked inside a locker, clicking a nearby locker will allow you to open/close it, while you remain inside. You can do this with lockers up to 2 tiles distant, if you aim at the hinge (see #496).

## Expected/Wanted/Requested Behavior
You should not have telekinesis while in lockers.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. Find two adjacent lockers.
2. Close yourself into one of them.
3. Click on the other.

## Notes:
You can close a locker 2 tiles distant, if its already open, by clicking on the door. You can't open it again while inside. This only happens if inside a locker.

**Comment by levyadams** [comment]
_In my recent PR_ PlayerScript.cs <del>now</del> has an added public pool standingInCloset with public getter setter which is accessed and used by individual closetControl.cs which checks or adds the player via the bool alone, meaning no GC.

Moderator Edit:
Your PR is not merged at the moment, please take note before posting that "Now" always refers to the head of the branch and not to any PR's
