### ISSUE TITLE
Add prefixes to GitHub labels

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#4970]
## Description

We could categorize our GitHub labels so they appear next to each other on the label list. Inspired by https://github.com/Relequestual/sensible-github-labels and other GitHub repos.

#### Types
```
Bug
Feature
Discussion
```
```
Type: Bug
Type: Feature
Type: Discussion
```

#### Scene changes
```
SquareStation
PogStation
FallStation
OutpostStation
BoxStation
```
```
Scene: SquareStation
Scene: PogStation
Scene: FallStation
Scene: OutpostStation
Scene: BoxStation
```
#### Affects (System)
```
Headless only
MacOS only
Windows only
```
```
Affects only: Headless
Affects only: MacOS
Affects only: Windows
```

#### Examples in a list
```
BoxStation
Bug
Discussion
FallStation
Feature
Headless only
MacOS only
OutpostStation
PogStation
SquareStation
Windows only
```
```
Affects only: Headless
Affects only: MacOS
Affects only: Windows
Scene: BoxStation
Scene: FallStation
Scene: OutpostStation
Scene: PogStation
Scene: SquareStation
Type: Bug
Type: Discussion
Type: Feature
```

**Comment by daalta** [comment]
Required changes for the automatic levels are in https://github.com/unitystation/unitystation/pull/4969/files

**Comment by corp-0** [comment]
deweet

**Comment by daalta** [comment]
Renamed the labels mentioned in this issue. Working on others, too.

**Comment by daalta** [comment]
Related: https://github.com/unitystation/unitystation/pull/4973
https://github.com/unitystation/unitystation/pull/4972

**Comment by daalta** [comment]
Everything works. Nice!

We can revisit the exact labels at any time. But at least we now know that the automatic labeller works with colons, too.
