### ISSUE TITLE
The ability to break out of locked containers such as lockers by using the RESIST button.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4997]
## Description
In /tg/, when you get locked into into a locker (or any lockable container, really) you can move or click the RESIST button to start breaking out. By default, it takes 2 minutes (or 120 seconds) to break out of a locker, although this number can be adjusted. 
Breaking out of a locker also breaks the lock on said locker, making said locker unable to be locked again.

![image](https://user-images.githubusercontent.com/38266309/91648960-ffd29580-ea22-11ea-80d7-cfcb1bd7cce5.png)
Default breakout time above. Note, it's 1200. Perhaps it's measured in tenths of a second?
![image](https://user-images.githubusercontent.com/38266309/91648953-eaf60200-ea22-11ea-840a-6be003bb6d2e.png)
Message in chat when you start breaking out.
![image](https://user-images.githubusercontent.com/38266309/91649061-66a47e80-ea24-11ea-9a45-c0265bcf68ab.png)
Message in chat when you successfully break out.

**Comment by jamessimo** [comment]
Going to work on this. 

I know in /tg/ its a flat 2 mins to get out but would it be more realistic if it only takes 1min if locked/emaged and 1 min if welded and if both then make it 2 mins? (maybe a lock is easier to break than a weld so we can tweak these).

I know I can't lock the closet anymore, but can I still open and close the door? Technically we could break the door off its hinge (remove the door sprite and drop some metal/planks.

**Comment by PetMudstone** [comment]
The properties of how long it takes to break out of welded/locked closets are up to you.
In regards to opening and closing the door, that is still possible after breaking out of a locker. It's just that the lock becomes non-functional.
