### ISSUE TITLE
Department Batteries not working properly

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5006]
If a department battery is used when the plasma gens turn off it seems when the plasma gens turn on and recharge them and then switch off again the department batteries dont turn on and so everything loses power.

1)Turn off plasma gens

2)Use up power

3)Turn on plasma gens

4)Turn off plasma gens after the batteries have charged a bit.

5)Department batteries will not use their stored energy even if switched on and off.

**Comment by NoooneyDude** [comment]
I would like to add that if the SMES is discharged and hits 0 and starts recharging, it won't output power again until it is back to 100 percent. This might be the same issue as department batteries.

**Comment by NoooneyDude** [comment]
Quite certain it was #5377 that fixed this issue.
