### ISSUE TITLE
Medical Console NRE

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5010]
Happens in editor or on server when you open the console, theres one in Squares bridge if testing needed to fix:

`NullReferenceException: Object reference not set to an instance of an object
NetworkTabManager.Add (NetTabDescriptor tabDescriptor, UnityEngine.GameObject player) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:81)
NetworkTabManager.Add (UnityEngine.GameObject provider, NetTabType type, UnityEngine.GameObject player) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Managers/NetworkManagement/NetworkTabManager.cs:84)
TabUpdateMessage.Send (UnityEngine.GameObject recipient, UnityEngine.GameObject provider, NetTabType type, TabAction tabAction, UnityEngine.GameObject changedBy, ElementValue[] values) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/Server/TabUpdateMessage.cs:114)
HasNetworkTab.ServerPerformInteraction (HandApply interaction) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Objects/HasNetworkTab.cs:40)
RequestInteractMessage.ServerCheckAndTrigger[T] (T interaction, System.Collections.Generic.IEnumerable`1[T] interactables) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs:347)
RequestInteractMessage.ProcessInteraction[T] (T interaction, UnityEngine.GameObject processorObj) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs:329)
RequestInteractMessage.Process () (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs:142)
GameMessageBase.Process (Mirror.NetworkConnection sentBy) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/GameMessageBase.cs:25)
ClientMessage.Process (Mirror.NetworkConnection sentBy) (at D:/github/corp-0/unitystation/UnityProject/Assets/Scripts/Messages/Client/ClientMessage.cs:14)
GameMessageBase.PreProcess (Mirror.NetworkConnection sentBy, GameMessageBase b) (at D:/g`

**Comment by creadth** [comment]
MedicalRecordsConolse has TabType set to None. We don't have appropriate tab prefab ready for the medical records, so this is the source of the issue here. We have another source of a problem here though, in case that TabDescriptor.Spawn methods returns null we just add it and it causes NRE. It might be better to log an error and do nothing in that case.
