### ISSUE TITLE
Properly functioning flares and glowsticks.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5012]
## Description
Flares and glowsticks in /tg/ are children of the flashlight, technically, but behave in peculiar ways.
  - Both:
    - Can be turned on, but not off.
    - Start with a randomized amount of fuel. One or the other?
    - Consume fuel over time while on, when all fuel is consumed, turns off and can not be turned on or otherwise used again. (How much fuel consumed per second/frame?)
    - Use new sprites while on (including in-hand sprites) and new sprites when all fuel is spent (not including in-hand sprites).
     - Have different messages for turning on, and having all fuel expended.

  - Flares
    - Produce a certain amount of heat while on.
    - While on, do 7 fire damage (variable, see torch below).
    - Has a torch (as in a burning stick) variation that does 10 fire damage while on.
    - New sprite while on and depleted completely replaces the old sprite.
    - Can start with 800 or 1000 fuel in /tg/.

  - Glowsticks
    - Don't produce heat at all.
    - Don't do damage while on. 
    - Have a variety of different colored variants.
    - New sprite while on is an overlay that goes over the old sprite. Depleted sprite replaces old sprite however.
    - Can start with 1500 or 2000 fuel in /tg/.

**Comment by PerfectTangent** [comment]
completed with #8405 and #8406. The fire damage of flares and torches still needs to be implemented, but otherwise they're good.
