### ISSUE TITLE
The ability to weld lockers shut.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5013]
## Description
In /tg/, you can weld lockers shut. This is done to prevent people from just opening lockers from both the outside and from inside. However, you can't weld crates and cardboard boxes, which are children of lockers, shut. Therefore, the ability for a container to be welded should be a variable. There should also be a field for a welded overlay sprite as well.

Related to #4997. You can break out of welded lockers (and other containers, if they are weldable) the exact same way you can break out of locked lockers. It is also important that players be able to break out so that people can't just trap everyone else forever by stuffing them into welded lockers.

It takes roughly 5 seconds to weld or unweld a locker.

**Comment by jamessimo** [comment]
I am working on this issue now and have closets welding shut on my local. 

Is there a reason why you cant weld crates (assuming their metal) in /tg/?

**Comment by corp-0** [comment]
In my opinion, it makes sense to have weldable crates

**Comment by PetMudstone** [comment]
There aren't weld overlay sprites for crates in /tg/. That's it, really. I don't see why you shouldn't be able to weld crates shut.

**Comment by jamessimo** [comment]
#4657 

Some overlap with this issue since closet/crate Emag, weld and crowbar logic will be in its own InteractionsCloset script (same as  how doors work).

**Comment by corp-0** [comment]
Large crates are meant to only be openable with crowbars

**Comment by jamessimo** [comment]
Also touches #5068 since a fix to this would be breaking out of locked/welded lockers

**Comment by jamessimo** [comment]
I think this issue can be closed now, see merges above.

**Comment by PerfectTangent** [comment]
so lockers can be resisted out of, the lock can be broken with an emag, and you can't weld yourself into lockers, correct?

**Comment by jamessimo** [comment]
@PerfectTangent yes, yes and yes!
