### ISSUE TITLE
Gas canisters need work

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#5022]
- Gas canisters drop metal when they are broken, instead of switching to burst state.
- Gas canisters need overlays.
- Gas canister mapped positions have been lost.

I have actually completed the work but will wait for bug-month to be over before PRing as it is a feature now, so I've made this issue and assigned myself in case someone wants to see if someone is already tackling it.

**Comment by ReiderJack** [comment]
PR it if it's finished
