### ISSUE TITLE
Some doors give off a pressure warning as one of the adjacent tiles is considered to be in deep space.

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5027]
## Description
Some of the doors give off a pressure warning despite the difference in the atmosphere around the door to be negligible. This is because one of the MetaNodes inside DoorController.cs returns a MetaDataNode.None value instead of the position on the server. The difference between the nodes is now massive because one is on the station and one is in the middle of deep space.  

### Detailed Bug Report
Inside the GetMetaDataAt in the MatrixManager,cs, there is an if statement on line 441 which is causing the problem. The node exists on the matrix, but it also believes that the tile is in space (!node.IsSpaced), causing it to not return the correct position. We believe it is specific to doors that have a pipe on a tile adjacent to it. So I think checking if the node's Pipe Count > 0 could fix this, however I think its better if we find out what causes the node to think it's in space instead.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Set a breakpoint at line 441in the MatrixManager,cs and Turn on the Matrix Check for pressure.
2. Find a door with an atmos pipe up, down, left or right to it.
3. Run the game in the editor and navigate to the chosen door.
4. Observe the pressure warning despite the atmos

**Comment by NoooneyDude** [comment]
I haven't seen this issue for some time. Reopen the issue if it occurs again.
