### ISSUE TITLE
Exception in OnStartClient:Object reference not set to an instance of an object at PlayerScript.ShowSpells ()

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5031]
## Description
Got this message after selecting character on build 4192, EU02 Staging server.

### Detailed Bug Report
It helps if you include any relevant DM code / config (for describing how new features should work), images, gifs, or youtube videos!
![image](https://user-images.githubusercontent.com/22667809/91965286-f134f880-ed18-11ea-9222-41de874fddb6.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Confirm character

**Comment by Fogapod** [comment]
Message triggered again after spawning

**Comment by ReiderJack** [comment]
This code was reverted, closing the issue
