### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5032]
## Description

Got these spammed after restarting game (after spawning).

build 4192, EU02 Staging server.

### Detailed Bug Report
![image](https://user-images.githubusercontent.com/22667809/91968826-e6309700-ed1d-11ea-9c54-f0f9a9199665.png)

### Steps to Reproduce

1.  Restart game and spawn

**Comment by Aranclanos** [comment]
doesnt seem to happen on the editor

**Comment by Fogapod** [comment]
Doesnt happen on build 4213

**Comment by corp-0** [comment]
> Doesnt happen on build 4213

this can be closed then?

**Comment by Fogapod** [comment]
Think so. Haven't got similar errors since then.
