### ISSUE TITLE
Inconsistent sprites of EVA helmet

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5049]
## Description

build 4221

sprite in hands:
![image](https://user-images.githubusercontent.com/22667809/92229553-5839e500-eeb2-11ea-901f-31e75e72a072.png)

sprite in inventory/floor:
![image](https://user-images.githubusercontent.com/22667809/92229667-7ef81b80-eeb2-11ea-942d-ad448facdf4b.png)

**Comment by PerfectTangent** [comment]
was fixed in #6332
