### ISSUE TITLE
Player character names aren't shown in attack messages or admin windows until they die and are respawned.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5054]
## Description
For some reason, you can't see the names of other characters in attack messages when they are the attacker and you can't see them in admin windows.

Below, Butch Miller attacks me, and is shown as Unknown. I, Norah Coldsteel, then attack Butch Miller and chat messages correctly identify him.
![Image1](https://cdn.discordapp.com/attachments/668605946691452949/751593733568593950/unknown.png)

Below, player alerts show me releasing plasma. Then, Butch Miller kills me but his name is not shown at all in the alert.
![Image2](https://cdn.discordapp.com/attachments/668605946691452949/751591704263655534/unknown.png)

Below, player alerts show Butch Miller releasing plasma several times in a row. His name is not shown, again.
![image3](https://cdn.discordapp.com/attachments/668605946691452949/751592941394591794/unknown.png)

Below, Butch Miller repairs a window and then attacks it. Note how the repair messages correctly show Butch's name and the attack messages have him listed as Unknown.
![image4](https://cdn.discordapp.com/attachments/668605946691452949/751594120048279572/unknown.png)

Below, Butch Miller's name and job (captain) isn't properly shown in the player window. Account censored. 
![null](https://user-images.githubusercontent.com/38266309/92293711-7d424e00-eeda-11ea-98fe-17f8c62034d2.png)

Below, Butch Miller finally dies, and is shown as dummy.
![Def](https://cdn.discordapp.com/attachments/668605946691452949/751597059475505212/unknown.png)

And now here's another thing to note. After I killed Butch Miller and respawned him, his name started properly appearing in attack messages and admin windows.

Below, Butch attacks me.
![Butch attacks, revelaed](https://user-images.githubusercontent.com/38266309/92293785-15403780-eedb-11ea-9e06-6936b4b06352.png)

Below, Butch releases plasma in player alerts.
![Plasma](https://cdn.discordapp.com/attachments/668605946691452949/751598378130866266/unknown.png)

Below, Butch Miller and his job properly show in the player window.
![unknown](https://user-images.githubusercontent.com/38266309/92293866-8d0e6200-eedb-11ea-83c7-b62e94b6bd0b.png)

## Addendum
Players that show up as NULL may also be missing from the player list in the bottom right. NoooneyDude noted that he didn't see as many players in the player list window (button in the bottom right) as he should have.

**Comment by PetMudstone** [comment]
On a side note, according to NoooneyDude: "When players are null in admin thing are they also missing from player list"

**Comment by corp-0** [comment]
haven't heard of this since september. What's the current state?

**Comment by PetMudstone** [comment]
Oh yeah, Bod actually fixed this along the way but forgot to close it in PR. Closing.
