### ISSUE TITLE
Conga lines entering teleporters are squashed into one tile Dwarf Fortress party style

### ISSUE THREAD

**Issue by AvenDonn** [unitystation/unitystation#5062]
## Description

Introduced with #5007 

### Detailed Bug Report
Due to the way teleporters have a single destination tile (Due to previously only supporting teleporting basically only what walked on them at the time) and the change allowing conga lines to enter teleporters, all who enter the teleporter will be tossed horrifyingly into the same tile.

This means a conga line of 100 people suddenly becomes a very dense mosh pit. 
While hilarious, it is not intended behavior and is a consequence of me being lazy when developing #5007. It's simply not easy to maintain some kind of relative positioning through teleporters without accidentally either putting someone into space, a wall, back on the teleporter, or worse. 

### Steps to Reproduce
Easiest to reproduce on SquareStation due to the Quantum Pads. The code is the same for both Gateways and Quantum Pads in this regard. (I know because I wrote it)
However, it might be relevant to distinguish between pulling "things" and "people" as there are slight differences.

1.  Start pulling someone/something
2.  Walk into a Quantum Pad, or a Station/World gateway (The big portals that open up 5-20 minutes into the round)
3.  Continue walking after being teleported

### Expected result:
You all make it to the other side in a way that makes sense

### Actual result: 
Conga lines turned into mosh pits, hopes and dreams shattered.

### Demonstration

![Sad conga noises](https://user-images.githubusercontent.com/1438444/91669918-72299f80-eb21-11ea-8bd8-14001ddc3deb.gif)

**Comment by PerfectTangent** [comment]
Honestly, not really a problem. everyone appearing on the same tile is the safest, most bug free way to do it, and it's what ss13 does. Closing.
