### ISSUE TITLE
Dropping your ID in a Locker Locked by the ID Softlocks You

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5068]
## Description
Softlock means that the game hasn't crashed, but there's no way to further progress.

### Detailed Bug Report
Dropping your ID in the locked locker makes you unable to pick the ID up, so you're trapped in the locked locker with no way out.

### Steps to Reproduce
1. Get in locker 
2. Lock locker while inside by clicking with ID in hand.  
3. Drop ID while in locked locker.
4. You're stuck in GBJ now, good job.

### Possible Solutions
* Implement resisting out of lockers
* Implement picking up items inside lockers while in lockers
* I've ran out of ideas

**Comment by craftxbox** [comment]
> Implement picking up items inside lockers while in lockers

Lock yourself in a locker and try to pick up a dropped credit card IRL, I dare you.
