### ISSUE TITLE
Canisters in Atmos Department Reservoirs Aren't Open on Round Start

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5070]
## Description
In order to have any gas in the Reservoirs, the reserve tanks need to be siphoned.
Pretty sure this isn't by design.

### Detailed Bug Report
The canisters inside the Reservoirs are able to be opened if the Reservoir walls are broken into and the canister manually opened

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Start round, go to the Atmos Department
2.  Turn on the Pump from any Reservoir
3.  Notice that the Metre attached to the aforementioned Pump shows no pressure

**Comment by NoooneyDude** [comment]
I would also like to add that the canisters in the reservoirs should probably be set to a higher tier (check the `Canister` component of the aforementioned objects in the scene). ~~While this currently has no functionality yet, it will be added at some point.~~

**Comment by NoooneyDude** [comment]
Maps that have reservoir tank canisters set to tier 2, valve open and release pressure of 1000 kPa:
- [x] Outpoststation
- [x] Squarestation
- [x] Fallstation
- [x] Boxstation

**Comment by NoooneyDude** [comment]
Closing; fixed by #5150.
