### ISSUE TITLE
Nuclear Operative Base Subscene should Load when Admins Respawn someone as a Nuclear Operative

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5074]
## Description
Currently, players Respawned as Nuclear Operatives spawn at arrivals, on the Station.
This forces the spawned Operatives to operate without the gear in their base, and instead make do with a single pistol.

### Steps to Reproduce
1.  Use Admin Player Panel to respawn a Player as a Nuclear Operative.
2.  Notice that they spawned at arrivals, on the Station.
3.  Notice that they had no chance of winning, with their one pistol against the entire station.

### Suggestions
* Make Loading the Subscene Optional, maybe a Tick Box or a Dialogue Box

**Comment by NoooneyDude** [comment]
Does this only apply for respawned players, or for players automatically assigned nukeop in that gamemode, too?

**Comment by Mute-Man** [comment]
Only for Respawned Players.
I haven't seen RoundStart Nuclear Operatives without a base before.

**Comment by corp-0** [comment]
This is because we don't have a spawn point for nuke ops. The system falls back to arrivals spawn point. We need to make the syndie base spawnable at will during the round so people actually have a place to spawn in.
