### ISSUE TITLE
Build number is meaningless/Alternative version syntax suggestion

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5089]
All of this applies both to hub and game itself.

## Description

From what I heard, build number is just ant integer that gets incremented each time build happens in some env/machine.
This number could be reset at any moment.

While build number is supposed to be something like that, it is exposed via UI in multiple places instead of proper complete version info.
This makes it difficult for people to know on which version of the game they are exactly, maybe server uses a fork? Maybe build number got reset for some reason?

There is additional info on installations tab, fork name (sometimes redundant):
![image](https://user-images.githubusercontent.com/22667809/92598750-e72f6e80-f2b1-11ea-8592-bff11ea70801.png)
There is no info about branch, commit, date, etc.

In server list it is impossible to know which fork is used:
![image](https://user-images.githubusercontent.com/22667809/92598812-04643d00-f2b2-11ea-9d66-29cb9faa9507.png)

## Possible solutions

Get rid of build number completely as it does not contain any useful info and use version identifier with high information density.
With this info it would be easier for developers to sort out new issues as they would no longer need to map build number with commit.

### Suggested version syntax

The following is a suggested pseudo-syntax where `{NAME}` are placeholders for variables, `()` are optional fileds.

`(FORK_NAME-){SHORT_COMMIT}(:{BRANCH_NAME})(-dirty)( DEVELOPMENT_STATUS)`

* SHORT_COMMIT: `git rev-parse --short HEAD`
* BRANCH_NAME: `git branch --show-current`, omitted if current branch is default (I suggest renaming current develop branch into master or main, not sure if `develop` makes sense without the main branch, but this is unrelated to this proposal)
* dirty or not: `git diff --quiet` will exit with status `1` if dirty
* DEVELOPMENT_STATUS: hardcoded, one of ALPHA, BETA, RELEASE
* FORK_NAME: hardcoded

#### Some examples of possible versions:
* `8546e60 ALPHA` - commit https://github.com/unitystation/unitystation/commit/8546e60a4cea97a4555171ed264f64f55c54a6af would look this way
* `Solidaruty-8546e60 ALPHA` - Solidarity fork would look this way
* `d90a929:feature/theWarningsNeverEnd ALPHA` - commit https://github.com/unitystation/unitystation/commit/d90a9299766ad20d782fd6884386f2902d6317a4 would look this way
* `8546e60-dirty ALPHA` - commit https://github.com/unitystation/unitystation/commit/8546e60a4cea97a4555171ed264f64f55c54a6af would look this way with local (dirty) uncommited changes

Proposed version syntax includes some additional symbols like ` `, `:` and `-`. I experimented a bit and found this composition the most fitting one, but feel free to propose other separators or reordering of tokens.

There is a lot more possible compositions of these tokens including a bit more SemVer compatible ones, but these will require a bit more work to implement.

### Additional changes
* Implementing this will require changing UI a bit to make sure longer version fits in it. `Build` word could stay.
* Issue posters should be asked to make a screenshot or type version number.

**Comment by corp-0** [comment]
How do you determine if a version is older than other?

**Comment by Fogapod** [comment]
> How do you determine if a version is older than other?

Well, you could use some magic git command.

The alternative is to use a slightly different format that can be anchored to releases and count commit count from there:
`1.0-alpha.4+dev.116.g83e9f530`: this is release `alpha4` of version `1.0` with additional `116` commits on top, latest one is `g83e9f530`

This format is a little bit harder to implement and more verbose, but could work too. I can post a similar proposal that adds commit count token.

**Comment by Fogapod** [comment]
Actually I think that the latter format is better since UnityStation follows SemVer and is on 0.4.0 now, I completely forgot about that with all these build numbers. I don't think 0.4.0 is exposed anywhere in the UI currently.

**Comment by Fogapod** [comment]
### Alternative syntax
This is syntax that has commit count on top of latest SEMVER release. In order to be able to get commit counts you should add tags in git repo each time release is made. This tag is used to count number of commits on top of it.

`[{FORK_NAME} ]{SEMVER}[ (dirty)]` for release builds.
`[{FORK_NAME} ]{SEMVER}+{NUM_COMMITS}.{SHORT_COMMIT}:{BRANCH_NAME}[ (dirty)]` for development builds.

### Tokens
* `{NAME}` - placeholder for variable `NAME`
* `[...]` - optional part

### Variables explained:
* `FORK_NAME` - `basename $(git rev-parse --show-toplevel)` for linux or just parse `git rev-parse --show-toplevel` in code. Omitted if `== "unitystation"`
* `SEMVER` - is read from somewhere where you store hardcoded SEMVER version
* `NUM_COMMITS` - `git rev-list SEMVER.. --count` where SEMVER is a tag for latest release. There are many other possible commands for this
* `SHORT_COMMIT` - `git rev-parse --short HEAD`
* `BRANCH_NAME` - `git branch --show-current`
* `(dirty)` - is added if environment is dirty. True if `git diff --quiet` exits with 1

### Examples
#### Releases
* `Solidarity 1.0.0 (dirty)` - Release 1.0.0 on fork Solidarity, with dirty repo (why would you release from dirty repo???)
* `0.5.0` - Release 0.5.0 of unitystation

#### Dev versions
* `Solidarity 1.0.0+1.g83e9f530:develop` - 1.0.0 on Solidarity fork with 1 commit on top, latest commit is g83e9f530, branch is develop
* `0.5.0+25.d90a929:feature/theWarningsNeverEnd (dirty)` - Unitystation 0.5.0 with 25 commits on top, latest is d90a929, it is branch feature/theWarningsNeverEnd, repository was dirty
* `0.4.0+102.8546e60:develop` - Unitystation 0.4.0 with 102 commits on top, latest commit is 8546e60, branch is develop

This looks pretty compact and readable, implementations should be straightforward, I described how to get each variable. The sooner this is implemented, the easier life would be for issue reporters and devs who process isssues. Format itself is still up to discussion, but I think all the important variables are in place.

After looking a bit deeper I found that build number is used as folder name by stationhub, suggested syntax will not be a valid folder name in most cases.
If these folders are not intended for users then something like `SHORT_COMMIT` could be used instead or version name sha256/md5.
Alternatively, folders for release versions could contain fork/semver parts and dev versions could be named after commit/version hash.

**Comment by PerfectTangent** [comment]
We changed the build numbering process a long time ago. Closing.
