### ISSUE TITLE
Attacking with items that don't have force (damage) values should play a tap sound by default.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5094]
## Description
In /tg/, when you attack someone with an item that has no force value (that is, it does no damage) then tap.ogg is automatically played. Having a tap sound play gives feedback that whatever attack you're doing is completely ineffectual to both you and whoever is around you. This might cause people to no longer kill eachother over attacks that do nothing. 

![image](https://user-images.githubusercontent.com/38266309/92665920-a426c880-f2bc-11ea-96fe-5c487f2d5abd.png)

tap.ogg in Unitystation is currently used in the sound manager and is called by the toy energy sword. It is under the object called "Tap".

**Comment by NoooneyDude** [comment]
Quite confident this has been implemented. Reopen if I'm wrong.

**Comment by PerfectTangent** [comment]
it hasn't. Reopening.

**Comment by NoooneyDude** [comment]
Alright, I can definitely hear the tap sound now!

**Comment by PetMudstone** [comment]
From what I see, MrAsbestos handled this in #6213 by simply giving any item that happened to deal 0 damage the tap sound effect. He didn't put in some different code to check if items dealt 0 damage, he just looked for any item that dealt 0 damage and made the sound it played the tap sound which works just as well I suppose.
