### ISSUE TITLE
All mouse buttons can be used to equip and unequip from inventory slots

### ISSUE THREAD

**Issue by Necromunger** [unitystation/unitystation#510]
Steps to reproduce:

1. Pickup a clothing item.
1.b. incase of middle mouse: switch to offhand, as switchhand is triggered before the equip
2. Click an empty slot with an inhand equipable item or 
2.b. click an already equiped item with an empty hand

**Comment by Em3rgencyLT** [comment]
MMB triggers item Interact() in general for any item in the main hand.

**Comment by Ornias1993** [comment]
I am testing this as we speak.
preliminary results seems it either does not exists, or Necromongers mouse is just broken and triggers both mousebuttons at middle mousebutton click
