### ISSUE TITLE
There Should Be a [Dev] Tag for OOC, so Players will Respond to Questions

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5104]
## Description
Devs might get ignored when asking questions about bugs in OOC in-game.

#### Detailed Description
I just saw it happen to Aranclanos, rip

## Solution
Make a new [Dev] OOC chat tag, so that players have a higher chance of noticing and paying attention to Dev questions.

**Comment by PetMudstone** [comment]
How would you give the [Dev] tag? Same way you make players admins using a .txt file and user IDs?

**Comment by NoooneyDude** [comment]
Closely related to issue #4933.

**Comment by Mute-Man** [comment]
The tag would probably be gotten from the Dev ingame role described in issue #4933
Although, having it be like the [Admin] Tag/Role means that community server Admins would have to give Devs their Dev roles manually.
Could possibly have the Dev role be across servers, not sure if this is a good solution, but I don't know much anyways.

**Comment by PerfectTangent** [comment]
closing in favour of #4933.
