### ISSUE TITLE
spam of "Why is CurrentMagazine null on this client?" each round

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5105]
![image](https://user-images.githubusercontent.com/701959/92982037-e42fac00-f472-11ea-9a6b-de2e3e6d136f.png)

this is on a client
screenshot from regularstation, I believe it shows up a lot when players use guns

**Comment by NoooneyDude** [comment]
I think this is no longer an issue since BVOld prefabs were completely removed by #5691.
