### ISSUE TITLE
client warning when toggling internals

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5106]
![image](https://user-images.githubusercontent.com/701959/92982105-2658ed80-f473-11ea-866c-1aef74f6e360.png)
each time I toggled internals on and off, I received 37 warnings with this message
as client, on regular station

**Comment by corp-0** [comment]
warnings are caused by [Server] decorator but it means that method is inteded to be called only on server and we're lazilly calling the method and relying on the decorator to stop the client.

**Comment by PerfectTangent** [comment]
is this still relevant after all the changes to health and internals?

**Comment by PerfectTangent** [comment]
going to close for now as no warnings are being spammed relating to internals on staging
