### ISSUE TITLE
clients ghostchat being repeated

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5108]
![image](https://user-images.githubusercontent.com/701959/92983182-3d4e0e80-f478-11ea-9889-e9799398b66f.png)
clients see themselves talking twice in ghostchat, this is only for their own talk
regular station

**Comment by Fogapod** [comment]
![image](https://user-images.githubusercontent.com/22667809/92996533-0974f680-f515-11ea-8eee-a5bf206ab62d.png)
I've seen this multiple times from other people as well. Seems like this is not just client side

**Comment by coolcat1711** [comment]
I think I have a fix for this. Ghost chat is one of the last channels to get updated from player chat and I think I found a duplicate "send message" call in the code. After I test it out, I'll throw in a PR.
