### ISSUE TITLE
spacebackground too small for ghost max camera distance

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5109]
## Description

![image](https://user-images.githubusercontent.com/701959/92983520-59eb4600-f47a-11ea-82c4-4934a9e56197.png)

spacebackground too small for ghost max camera distance, can see a big chunk of black nothingness 

to reproduce you have to move towards one side, its mega noticeable if you're inside a shuttle

**Comment by NoooneyDude** [comment]
![Unity_7jKmN7Dvau](https://user-images.githubusercontent.com/6926225/93010186-ad29d980-f5dd-11ea-9393-9152d612433e.png)

Character is at the cursor position. Looks like the background isn't centred on the character.

**Comment by MaxIsJoe** [comment]
this was fixed by me in #9143
