### ISSUE TITLE
Easy-to-add and useful traitor items for PDAs

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5110]
## Description
Currently, the traitor Telecrystal store on the PDA is limited to the cutthroat, extra magazines for the cutthroat, and the laser sword. However, there are several other items that already exist in game or could be easily implemented that would be substantially useful if added to the TC store for the first release of PDAs to the public build.

# Items that could be added _right now_:

- The Emag (now useful for being able to break open doors) - 4 TC
- .357 Revolver - 13 TC
- .357 speedloader - 4 TC
- Syndicate Jaws of Life - 3 TC
- Syndicate Fully Loaded Toolbox (mechanical toolbox that does 15 damage per hit and comes with black insulated 'combat gloves') - 2 TC
- Chest Rig - 1 TC
- Syndicate Soap - 1 TC
- Syndicate Hardsuit and Helmet - 8 TC
- Syndicate Magboots - 2 TC
- Syndicate Cigarette pack - 2 TC

# Items that could be very easily coded according to G̶i̶l̶l̶e̶s̶ NooonyDude:

- C4 Explosive - 1 TC
- C4 Explosive bundle bag - 8 TC
- Syndicate Bomb - 11 TC
- Syndicate Minibomb (essentially a 6 second fuse grenade) - 6 TC

**Comment by NoooneyDude** [comment]
I would like to add that the emag is already added to the Uplink SO, it is just in a different category.

**Comment by corp-0** [comment]
> Items that could be very easily coded according to Gilles

I will need a quote on that.

**Comment by PerfectTangent** [comment]
Excuse me. NooonyDude said it.

**Comment by NoooneyDude** [comment]
Hmm yeah, the Syndicate Bomb may be more difficult, as it has disarming mechanics to consider.

**Comment by wraith-54321** [comment]
maybe also stun batons.

**Comment by PerfectTangent** [comment]
well, most of the stuff was added, exempting bombs + Jaws, So I think this issue's done.
