### ISSUE TITLE
Move atmospheric reactions into atmospheric thread : B 50

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5124]
currently I believe that, the code responsible for doing the reaction of fire is on the main thread while atmospherics is running, this causes strange situations between the two threads,
the proposed fixes to move the code to run on the atmospheric thread, so any reactions that interact with atmospherics should run on the atmospherics thread,

Later on this could include the pipe nets, 
optional extra you could look into doing the pipe nets on the atmospheric thread?

**Comment by Aranclanos** [comment]
currently on this
