### ISSUE TITLE
Evac Shuttle Timer Carries Over to New Rounds

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5128]
## Description
At the start of a new round, if the previous round existed and ended via Evac, the station monitors still show Centcomm: 03:00 counting down.

### Detailed Bug Report
Servers have recently been crashing on the majority of round ends, so this might already be an outdated report.

### Steps to Reproduce
1.  Start Round
2.  End Round via Evaccing
3.  Load into a new round
4.  Notice that the station monitors are still counting down

**Comment by Aranclanos** [comment]
can't reproduce on editor
