### ISSUE TITLE
Absolute zero exhaling and Atmos Poltergeists

### ISSUE THREAD

**Issue by braincrab** [unitystation/unitystation#5132]
## Description
For some reason, the CO2 breathed out by people comes out very, very cold (and possibly spontaneously generated?). normally said co2 expands but is removed by scrubbers before it can cause issues, however, if one wires the waste gas pipe (red) directly to the station atmos pipe (dark blue), possibly because of "hehe traitor turn off life support" antics, said supercooled CO2 is pumped back in, heats up, and massively increases pressure. With ss13 atmos being wonky as fuck, physics gets thrown out the window and this supercooled co2's massive increase in pressure heats up the system because PV = nRT is a poor formula to use in this case and the combined gas law would be better. Regardless, this magic increase in heat (which, surprise, wouldn't occur in real life) causes new cooled co2 coming in to get heated up even more, making more pressure, making more heat, and creating an infinite loop. This creates huge pressure differences and heats up the station considerably, to the point that just being in the air may cause burn damage if it gets far enough. These pressure differences lead to strange other atmos behaviours, such as atmos tornadoes and poltergeists which both have the capacity to gib/kill players instantly.

### Steps to Reproduce
In order to break the laws of physics:

1.  connect the red output into blue input pipe, switch pump so waste goes back into the station air
2.  wait for a very long time (well over an hour)
3.  Observe atmos shit itself and create swirling vortexes of garbage and slam nukies into walls so hard they splatter

In order to fix this, you could either rework atmos completely or make people not breathe out co2 at absolute zero.

**Comment by braincrab** [comment]
Probably related to #2644 and #3823

**Comment by coolcat1711** [comment]
I'll take a peek and see if it's easier to maintain the current implementation with some patch fixes, or if we should convert to something like the combined gas law.

**Comment by NoooneyDude** [comment]
How did you determine the massive increase in pressure? Just checked respiration; it puts as many mols of CO2 in as it takes O2 out. I haven't determined the CO2 being at absolute pressure yet, but if that is the case, once it equalises with ambient the final pressure should be similar.

**Comment by NoooneyDude** [comment]
Relevant recording provided by `oksts2904#4959` on Discord

https://streamable.com/7r0vfw

**Comment by coolcat1711** [comment]
![image](https://user-images.githubusercontent.com/3880412/93163565-7b9c3580-f6e5-11ea-82d8-799f2a5b4209.png)
