### ISSUE TITLE
Ore redemption machine isn't intuitive to use.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5136]
## Description
Title. It ain't particularly clear to an inexperienced player how to use the ore redemption machine. First, you can't use the ORM by using the mining satchel on it. Instead, you have to drop ore right above the ORM and then click the ORM in order to process the ORM. However, this only works if ore is as said before, **right above** (a tile north) of the ORM. If ore is adjacent but on the western, eastern, or southern tile and not the northern one then the ORM won't process that ore.

**Comment by Akbadain29** [comment]
I think it could be made clearer if we put a conveyor belt above and below the ORM which moves round start. The ore then moves from the belt to the ORM to the other side.
Or maybe a Morgue tray which is open round start, so the player puts all the ores on the tray above and then closes the tray to start the process. After it's complete it opens up again. With that, maybe it could all operate on the same side for both the input and output.

**Comment by PerfectTangent** [comment]
closing in favour of #6151
