### ISSUE TITLE
For research

### ISSUE THREAD

**Issue by spectre1122** [unitystation/unitystation#5155]
Since research is pretty useless right now they could have a console that can be used to get stuff like an xeno queen, cultist items, alien technology, I say they only get 2 research items, except if it's a xeno queen they can only get 1, if cultist items, 2 cultist items, etc.
Because right now only admin can make those events happen, it would be more "interesting" for science jobs.

**Comment by PerfectTangent** [comment]
This has been indirectly satisfied by #5623
