### ISSUE TITLE
The ability to take more than one item from a stack of items.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5174]
## Description
Right now you are only able to remove one item from a stack at a time. This is quite tedious if you want to remove more than one item, in which case you have to keep removing single items and drop them on the floor before removing another single item from a stack. The ability to take multiple items from a stack would therefore be a nice quality of life improvement.

**Comment by PetMudstone** [comment]
There is a way to take a certain amount of items from a stack in /tg/. You alt click the stack (with a free hand, obviously) when it is in your inventory then a dialogue window pops up asking you to type in the number of items you want to remove from the stack.

**Comment by ilinm1** [comment]
working on it, hope Ill succeed
