### ISSUE TITLE
The ability to place chair items and turn them back into chair objects.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5183]
## Description
Title. You can pick up chairs as items right now but you can't place them back on the floor and turn them back into chair objects that you can sit in.

### Steps to Reproduce
1.  Pick up chair.
2.  Try to place on floor, fail.
3.  Despair.

**Comment by NoooneyDude** [comment]
We have an issue for this. Issue #4103.

**Comment by PetMudstone** [comment]
Dang, how could I forget the other chair issue.
