### ISSUE TITLE
HUD and Examination GUI

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#5206]
[![US13 HUD Layout.png](https://i.imgur.com/1xRFD3ul.jpg)](https://i.imgur.com/1xRFD3u.png)

The following is a full breakdown of the HUD and Examination GUI designs, intended for implementation by gingerbread0.

## Section 1: Chat

- Chat text, both in the text box and the chat log, must be written in Press Start 2P, in 10pt size
- The borders around the chat log should be transparent.
- The chat should show which channel a line of speech is being said on, by highlighting the speaker&#39;s name in an appropriate colour. Refer to the style guide for colour palettes. Mousing over a speaker&#39;s name should provide a tooltip to clarify which channel they are speaking on.
  - Standard speech: Normal white font #FFFFFF
  - Whispering: Italics
  - Common radio: Green #006600
  - Command radio: Navy Blue #334E6D
  - Security radio: Rusty Red #9F2828
  - Medical radio: Light blue #7CB8DD
  - Science radio: Purple #6633CC
  - Civilian radio: Light green #90BA58
  - Cargo radio: Brown #5F350B
  - Engineering radio: Yellow #C19B2D
  - Syndicate radio: Blood red #841409
- The volume slider on the left provides a control for shifting between whispering, normal speech and yelling, respectively.
- The chat log should _not_ host feedback on the player&#39;s actions, like turning electronics on or off, or feedback on firing weapons. These should instead float above the player character&#39;s head, ascending for two seconds before disappearing.
- The chat log should still display actions initiated by other players within view.
- Chat log opacity should be customizable. All chat text must have an outline the same colour as the chat log background, so that the outline is invisible with high opacity, and highly visible with no opacity.
- The centering of the gameplay viewport should not count the chat area by default, but this should be a toggleable option, as some might prefer and transparent chat log and being able to play &quot;under&quot; it.
- Optional: There should be an option to switch the chat and chat log from the left to right side.
- There should be a help button above the chat volume slider (Just a question mark that opens a tooltip or window showing all the chat channels and associated prefixes available to the player at the time.
- Optional: The ability to double click on a particular channel name in the chat log, causing all communication in that channel to be highlit until double clicked again.

## Section 2: Wearables

[![HUD6.png](https://i.imgur.com/xgfAHpdl.jpg)](https://i.imgur.com/xgfAHpd.png)

- The wearables section is functionally reminiscent of the current ones, with two exceptions:
  1. Whether clicking the coat hanger icon will expand or collapse the menu should be displayed by the diagonal arrow or the cross indicated above.
  2. The new layout of icons should be implemented, per the above picture

## Section 3: Inventories

- The Backpack, PDA and Belt slots serve the same purpose as in current code.
- Hotkeys must be displayed in the upper right of the three icons. The hotkeys must be displayed above any sprites displayed in the slot.
- The displayed hotkeys must change according to customized controls.
- At the top right of any inventory, two numbers in the format xx/yy should show the current fullness (xx) of the container, versus its capacity (yy).

## Section 4: Hands

[![HUD2.png](https://i.imgur.com/HEUMdcDl.jpg)](https://i.imgur.com/HEUMdcD.png)
[![HUD3.png](https://i.imgur.com/1S8FBICl.jpg)](https://i.imgur.com/1S8FBIC.png)

- Players should be able to click the border around each hand or press a customizable hotkey (Default is X) to switch hands.
- New functionality: Holding down the switch hands key or pressing the two arrows in the middle of the new HUD element, allows you to use both hands simultaneously.
- The light-coloured border should _always_ highlight which hand(s) is active.
- Either or both hands should be greyed out and unusable if hands are dismembered.

## Section 5: Pockets

- Increase from 2 to 3 pocket slots
- If the player is not wearing clothing in the uniform slot, all but one pocket should be greyed out.
- Pressing 1, 2 or 3 (customizable, displayed on the slots in the HUD) takes an item from the pocket slot if the player hand is empty, attempts to put an object in the pocket if the player hand is full.
- Should the player have an empty hand and an empty pocket, and press the pocket key, a feedback message should float over their head saying &quot;There&#39;s nothing in that pocket&quot;
- Should the player have a full hand and full pockets (plural), and attempt to use a pocket slot, a feedback message should float up saying &quot;My pockets are full&quot;. Feedback messages should float above the player&#39;s head.
- Should the player have a full hand and attempt to use a full pocket, while other pockets are empty, just transfer to object to an empty pocket.

## Section 6: Mini Actions

[![HUD4.png](https://i.imgur.com/Dzy56adl.jpg)](https://i.imgur.com/Dzy56ad.png)

The six mini action buttons are, from left to right, top to bottom:

1. Intent – This is a binary toggle between help and harm intent. Bound by default to the C key. Clicking this changes the icon border to red, the icon to an angry face, and moves the player to harm intent. The reverse is also true.
2. Rest – Pressing this button triggers the rest intent and should also trigger a feedback message floating above the player, saying &quot;You try to lie down.&quot;
3. Crafting – Pressing this button opens the crafting options. These are not yet designed, so this button can be greyed out for now.
4. Run and Walk – Pressing this button switches back and forth between walking and running. Running is the default state. Pressing the button should elicit a feedback message above the player, saying &quot;You start running&quot; or &quot;You start walking&quot;.
5. Resist: Pressing this button triggers the &quot;Resist&quot; action. It is highly context sensitive, so for now, just have it trigger that action.
6. Help: This will eventually tie into a player training system, but for now, it should open a menu where you can A) Report something to the Admins B) Request the help of a Mentor C) Open the Wiki in your browser

## Section 7: Health readout and targeting doll

Starting with the easy part: The heartbeat monitor has its background colour change to respond to the player&#39;s health. The code for this response is already in the game. Only difference is the background changing colour instead of the pulse line. The pulse line will instead change its curvature according to health condition.

The doll serves dual purposes, being both the interface for targeting interactions with other characters, and showing the condition of the player&#39;s own body parts. The doll has the following (clickable) zones:

- Head
- Eyes
- Mouth
- Left arm/Right Arm
- Left hand/Right hand
- Torso
- Groin
- Left leg/Right leg
- Left foot/Right foot

Clicking any of these zones moves the red highlight to that zone, and makes actions taken on other characters target that area. Additionally, the hotkey for these are, by default:

- Numpad 8: Head/Eyes/Mouth (cycles with repeat presses)
- Numpad 4: Left arm/Left hand
- Numpad 5: Torso/Groin
- Numpad 6: Right arm/Right hand
- Numpad 1: Left leg/left foot
- Numpad 3: Right leg/Right foot

The red zone highlight is its own sprite, rendered with 50% Opacity and a linear light effect to enable the following to work:

Each of the player&#39;s major body parts and limbs (head, torso, groin, each leg, each arm) show damage taken on the doll as well, with a diagonal line pattern coloured yellow for minor damage, red for serious damage, and the limb sprite is shown in black if a body part is disabled, and completely removed if a body part is destroyed (like if a limb is severed).

## Section 8: Internals indicator

This section fundamentally has five states. Clicking the icon in states 4 or 5 toggles airflow on/off, I.E. between states 4 and 5.
- In states 2, 4 and 5, the air tank icon should display how full it is with a light colour from the bottom up showing pressure/capacity.

1. Player is wearing neither a tank nor a mask. No tubes and mask are shown in HUD, the air tank is greyed out.
2. Player is wearing a tank, but no mask. The tank icon now shows the fullness/capacity of the tank, but no tubes/mask are shown.
3. Player is wearing a mask, but no tank. Tubes and mask are shown in the HUD, but the tank remains greyed out.
4. Player is wearing a mask and a tank, but airflow is off. The air tank is shown in blue in the HUD, and the mask is shown too.
5. Player is wearing a mask and tank, and the airflow is on. Same as above, but the air tank in the HUD is given a green hue to show the difference.

## Section 9: Player Examination

[![HUD5.png](https://i.imgur.com/urhYLKVl.jpg)](https://i.imgur.com/urhYLKV.png)

This section is only active when the player examines another humanoid character by shift-clicking on them. The Examination GUI is meant to be modular, as different player equipment, like a health analyser or a security HUD, can attach new information panels to the GUI. For now, we shall focus on the core examination GUI available to every player.

The top of the Examination GUI, currently marked with question marks, hosts the name of the player character. Do note that if the player is not wearing an ID or has no visible face, they can be &quot;Unknown&quot;. Should face and ID conflict, derive the name from the ID.

The Race, Job and Status boxes are largely self-explanatory. Their information derivation will be explained here:

1. Race is primarily derived from the face of the character being visible. If the face is not visible, the information should be derived from security records on the character. If the character is an unknown, mark Race as &quot;?&quot; as well
2. Job is primarily derived from the security records tied to the ID name, secondarily from the records tied to the person whose face is visible. If the character is an unknown, mark Job &quot;?&quot; as well.
3. Status has four potential values: Alive, Unconscious, SSD (Disconnected) and Dead. This information is pulled from the Health system which is currently under reconstruction, so leave this field a placeholder for now.

The Wearables area shows what items the character is visibly wearing, similarly to Section 2 of the player HUD. Since you&#39;re examining another character, there are however several nuances:

- If the character is wearing an exosuit like a space suit, any worn items covered by it cannot be examined, and those fields will be redded out.
- If a player is wearing nothing in a slot, simply show the background/placeholder icon as derived from Section 2 of the player HUD.
- You can interact with other characters&#39; pockets, but if there&#39;s anything in a pocket, it will always show up as a question mark in the Examine GUI, as you can see they have something in a pocket, but you cannot know what.
- This also doubles as the search/stripping GUI. This means that if you click on an occupied slot in another character&#39;s inventory, you will attempt to take that item from them, as with the current stripping interaction. If you have an empty hand, the item you take will fill that hand. If your hand is full, the item you are taking will drop on the ground.
  - The above also works in reverse. You can give or plant items on other characters, by clicking on an empty slot in their inventory with a full hand. If your hand is empty, nothing happens.

Clicking on the expansion arrow on the right side of the Examination GUI expands the window, showing additional information in bullet point form, often relating to the character&#39;s visible health. These bullets might highlight information like visible bruising or burns, bleeding, broken limbs, paleness, being asleep and their soul status (if dead). When expanded, the arrows should invert into a collapse button, which when clicked will hide the extra information again.

Edit1: by community request ensure bottom UI slots are properly in the middle of the screen, instead of off to one side

Edit2: by the poll on the discord when you're not interacting with a chat, the boxes Disappears only Leaving the text to be visible, note changes were requested so it needs to be tweaked and designed

**Comment by Bod9001** [comment]
Would like to Preface this, that this is the first iteration of the public UI so, There are going to be plenty of changes and polls in the Discord channel on what changes should be made  so this is not final, I have a few gripes about it as well

**Comment by Bod9001** [comment]
feel free to discuss anything you would changed about the new UI

a good channel to talk about it or not is #ui-ux on the discord

I'm currently testing the waters to see what unanimous decisions there is so it saves the developer working on this sometime

**Comment by corp-0** [comment]
what do the red X's on the mockup mean?

**Comment by Bod9001** [comment]
I think it's stuff that is not included in the issue

**Comment by CdrCross** [comment]
> 
> 
> what do the red X's on the mockup mean?

Yep, stuff that's not covered. The right click radial is being implemented by the UX Team, and the player action log has been scrapped.

**Comment by CdrCross** [comment]
Amended the Specifications with the following additions based on community feedback:

Section 1:
- Optional: There should be an option to switch the chat and chat log from the left to right side.
- There should be a help button above the chat volume slider (Just a question mark that opens a tooltip or window showing all the chat channels and associated prefixes available to the player at the time.
- Optional: The ability to double click on a particular channel name in the chat log, causing all communication in that channel to be highlit until double clicked again.

Section 8
- In states 2, 4 and 5, the air tank icon should display how full it is with a light colour from the bottom up showing pressure/capacity.

**Comment by jamessimo** [comment]
Can we see what the clickable face zones will look like? Also is the heart beat on top of the target rag doll my health or the targets?

**Comment by ZeroDayDaemon** [comment]
@jamessimo Heartbeat should indicate the player you're controlling's health and not the target.

I'm also concerned with how small the target/health doll and how small it is on screen

**Comment by corp-0** [comment]
Now that you mention it it does feel weird that the player health status and target doll are using the same section in the UI

**Comment by CdrCross** [comment]
> Can we see what the clickable face zones will look like? Also is the heart beat on top of the target rag doll my health or the targets?

There's no lock-on system. It's your health.

> Now that you mention it it does feel weird that the player health status and target doll are using the same section in the UI

It may _feel_ weird, but CBF has put significant time into making the interaction between the target layer and health layer work. I concede that I am not 100% comfortable with the size of the doll, but those modifications will come after playtest feedback.

**Comment by Akbadain29** [comment]
When you hold shift, the cursor should change into a magnifying glass so the player knows they are in examine mode.
Like this: https://imgur.com/Uh35DWE
