### ISSUE TITLE
Music too loud inside closet

### ISSUE THREAD

**Issue by jamessimo** [unitystation/unitystation#5208]
## Description
When you enter a closet the ambient space music plays. Because your technically miles away in space when you enter a closet (you teleport to 0,0,-100) the game thinks your in deep deep space and scales the music accordingly.

### Steps to Reproduce

1. Enter any closet  
2. Listen to the music 
3. Take off your headphones when the sound gets too much

**Comment by corp-0** [comment]
https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Sound/AmbientSoundArea.cs

Maybe you check if while leaving the area, player didn't go to hiddenpos

**Comment by NoooneyDude** [comment]
I don't think this has been an issue since the last major changes to lockers a couple months ago.
