### ISSUE TITLE
Cleanbot Mayhem

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#5222]
## Description
Cleanbots make lube invisible instead of actually cleaning it up
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Create and use lube
2.  Create clearbot near them
3.  Observe results.

**Comment by LastCaptainBonk** [comment]
I meant "Hippocrates Bust" instead of "Socrates Bust"

**Comment by Aranclanos** [comment]
I cant reproduce a bust being removed by a cleanbot

**Comment by corp-0** [comment]
What bust are you guys talking about?
