### ISSUE TITLE
You are unable to use RCS while buckled into a chair.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5232]
## Description
Title. If you are buckled into a chair while using a shuttle console, then you are unable to use the RCS mode to move your shuttle. 

### Steps to Reproduce
1.  Get onto a pilotable shuttle, confirm a plasma canister is wrenched to the fuel port.
2.  Buckle yourself into a chair adjacent to the shuttle console.
3.  Turn on RCS mode. Try to use WASD keys to move the shuttle around, fail.

**Comment by Bod9001** [comment]
moving from 4116 since it uses the player movement system to work out what to move next and if you buckled it doesn't send it, requires re-factor of the method uses to move around

**Comment by Semuca** [comment]
Can we close this?

**Comment by NoooneyDude** [comment]
Sure. Handy tip: prefixing an issue number in a PR with `fixes` or `closes` will automatically close the linked issue when the PR is merged.
