### ISSUE TITLE
Add incendiary bullets that don't rely on fire attacks to set mobs on fire.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5234]
## Description
In /tg/, there are incendiary bullets that are able to set mobs on fire when they are hit with said bullets. Unlike the projectiles fired by the flamethrower as of writing, incendiary bullets still do brute damage and are of the bullet attack type. Instead of setting mobs on fire by being of the fire attack type, incendiary bullets instead add a variable amount of fire stacks to struck mobs.

![image](https://user-images.githubusercontent.com/38266309/94762051-813b8180-035b-11eb-9191-2ebea31e218b.png)

**Comment by PetMudstone** [comment]
#### Addeneum
I didn't realize this before testing in-game, but incendiary bullets create hotspots on every single tile that they passover. Hotspots by the way, are patches of fire. Incendiary bullets create small patches of fire that last a second over every single tile they pass over.

Below: a single incendiary shotgun slug being fired.
![incendiary hotspot](https://user-images.githubusercontent.com/38266309/94763293-b85f6200-035e-11eb-818c-5ded57b21ffe.gif)
Below: two dragonsbreath shells being fired, with multiple pellets per shot.
![dragonsbreath hotspots](https://user-images.githubusercontent.com/38266309/94763321-cd3bf580-035e-11eb-8358-e9c216e32b6e.gif)

![image](https://user-images.githubusercontent.com/38266309/94763991-931f2380-035f-11eb-9cb3-f9bd7b03628a.png)

**Comment by NoooneyDude** [comment]
Completed by #5341.
