### ISSUE TITLE
Corpses sometimes get stuck on one tile for no discernible reason.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5249]
## Description
Occasionally, dead players just get stuck. They can't be moved by atmos or by dragging. If you try to drag stuck dead players then they'll appear to move a tile then snap back into place. Stuck dead players can however be moved around by putting them into lockers and then moving said lockers around. When the locker is opened the dead player pops out and remains anchored to the tile they were unleashed upon instead.

I don't have any steps to replicate this because I don't know how to replicate this.

**Comment by Ruzihm** [comment]
dev note: Just from the description, it sounds like a mismatch between client and server side code which causes corpses to not be pushable or for something to be detected as blocking their movement on the server side.

**Comment by NoooneyDude** [comment]
Still relevant on 4119.

**Comment by PerfectTangent** [comment]
needs verification after #7710

**Comment by craftxbox** [comment]
Present in 22010322

**Comment by MaxIsJoe** [comment]
I was just wondering but could this be related to #8357 somehow?

**Comment by NoooneyDude** [comment]
Hmm unlikely, this painful bug has been around for a long time.

**Comment by MaxIsJoe** [comment]
This still happens even after the new movement rework

**Comment by AtnerNT** [comment]
Has this been observed recently?

**Comment by MaxIsJoe** [comment]
This hasn't been an issue since the new movement system has been finalized.
