### ISSUE TITLE
Some people get stuck on the "Verifying account details" section on certain servers for no discernible reason.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5255]
## Description
As of late, a few players have become unable to connect to particular servers as they become stuck on "Verifying account details". Strangely, this only happens on certain servers. For example, Siwwy Slug is unable to get past "Verifying account details" on Solidarity but apparently can get past it on other servers.
![Loading...](https://cdn.discordapp.com/attachments/723540316207972393/762102080269582336/unknown.png)

I've heard suggestions that it's a Firebase related issue, but I wouldn't really know myself.

**Comment by PetMudstone** [comment]
Update: SimplySmiley is now unable to join _any_ server, which is quite problematic as he is admin on several on them. Aleecia Rosewater is also unable to join any server.

**Comment by jamessimo** [comment]
I can’t join but it’s confirmed my reason is due to firebase being blocked in my region (China).

**Comment by corp-0** [comment]
I haven't seen this happening recently. I will close but feel free to reopen if it is still an issue.
