### ISSUE TITLE
Stackable items in the inventory render over the number that shows how much of them there are in a stack.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5261]
## Description
Title. Stackable items in the inventory render over the number that shows how many items in the stack. This is somewhat annoying.

![Stack](https://cdn.discordapp.com/attachments/668605946691452949/763418005035417650/unknown.png)

### Steps to Reproduce
1.  Get a stack of items, such as metal sheets.
2. See sprite render over number sprite.

**Comment by NoooneyDude** [comment]
Looks like it is fixed.

![overlay](https://user-images.githubusercontent.com/6926225/116768367-2ea97b80-aa8a-11eb-8f69-a2b42a4c6881.png)
