### ISSUE TITLE
Everyone is notified about gunfire

### ISSUE THREAD

**Issue by BootlegBow** [unitystation/unitystation#5287]
When a gun is fired, a message in chat is displayed saying the type of bullet and what it hit. This message is displayed to everyone currently in-game, meaning that people who aren't nearby can figure out where potential antags are based on the location of gunfire.

**Comment by PerfectTangent** [comment]
is this still an issue?

**Comment by PerfectTangent** [comment]
This is no longer an issue. Closing.
