### ISSUE TITLE
robo should spawn with toolbelt

### ISSUE THREAD

**Issue by BootlegBow** [unitystation/unitystation#5296]
In /tg/, roboticists spawn with toolbelts. In unitystation, they don't. Roboticists seem like they should spawn with toolbelts.

Please enter the steps to reproduce the bug or behaviour:  

1.  spawn as roboticist
2.  not have a toolbelt

**Comment by ThatDan123** [comment]
I somewhat disagree with giving belts on spawn as i think it'd be better game design, or at least lets the player need to think of what would make their life easier, and go find and equip one.

Though if you do want to add one maybe just give them an empty one so they at least need to do some work :p

**Comment by BootlegBow** [comment]
The problem is that unless someone lets them into Engineering, they can't get one since the science lathe doesn't print them. Toolbelts will also be kinda mandatory for later content, and they spawn with them in /tg/, so making roboticists have to go find them doesn't make a whole lot of sense imo
