### ISSUE TITLE
Keystrokes while typing in admin windows still register in terms of player movement, bring up chat, and more. B:25

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5303]
## Description
Right now when you type in admin windows, such as player chat, your keystrokes will sometimes still do things like move your character, drop things, or even open normal chat (which is **especially** annoying as everything you type afterwards will be in normal chat and not admin to player chat or whatever). This shouldn't be happening.

The key word is sometimes. Pressing Y will sometimes do nothing while typing in admin windows, while other times it will open up normal chat and do as described above.

### Steps to Reproduce
1.  Open up an admin window, such as admin to player chat.
2. Start typing in any text fields.
3.  Press random keys, see if they do anything. With some (mis)fortune the WASD keys will move your character around and the T, Y, and U keys will open up chat for example.

**Comment by Ruzihm** [comment]
I was able to reproduce in admin to player chat but not in admin only chat. might be as simple as copying and pasting whatever one has the other doesn't.

**Comment by Mute-Man** [comment]
update: version Staging 21012100

I haven't been able to reproduce opening chat while focused on a text field on any of the admin windows.

I have been able to reproduce the movement keys still registering as movement keys while typing in specific admin windows
* Ahelp chat textbox (pretty important)
* Mhelp chat textbox
* Player Manager -> Kick Player window reason textbox
* Player Manager -> JobBan Player window reason textbox

**Comment by PerfectTangent** [comment]
This issue is being promoted to bounty status, valued at 25 USD.
