### ISSUE TITLE
Most admin buttons don't show up in the editor until you start a second round.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5304]
## Description
Title. For some reason when you enter play mode in the editor the admin button in the top-center of the screen are initially missing (this excludes the Admin button on the top right, with the drop-down window). However, when you end the round you're in and start a new one, all the missing admin buttons come back and are fully usable.

### Steps to Reproduce
1.  Enter play mode, see that all the admin buttons in the top-center are missing.
2.  End your first round.
3.  Start second round, see that all the admin buttons have returned.

**Comment by NoooneyDude** [comment]
Interesting, I don't seem to have this issue.

**Comment by corp-0** [comment]
I can confirm. I have complained about it before

**Comment by ThatDan123** [comment]
Yeah, i have that issue

**Comment by ThatDan123** [comment]
And i cant find the script which switches it on and off

**Comment by NoooneyDude** [comment]
Ohhh no, this just started happening to me, too.

**Comment by corp-0** [comment]
it was probably already there, you just didn't notice

**Comment by NoooneyDude** [comment]
I'm not so sure, because I was constantly reminded that the wizard spells are overlapping with the admin tools. But, perhaps.

**Comment by MaxIsJoe** [comment]
This bug no longer happens
