### ISSUE TITLE
Add working handheld shields.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5305]
## Description
In /tg/, there are shields that you can hold which have certain properties.
- Shields have a variable chance of blocking attacks, including both melee attacks and also projectiles. Shields will receive the damage that was blocked.
- Shields have a lower chance of blocking thrown objects.
- Shields such as the riot shield can be transparent, which means projectiles that pass through glass (such as laser bolts) can not be blocked by them.
- Shields can break once they take enough damage (reach 0 integrity) and may drop something alongside playing a sound. For example, riot shields drop a glass shard when they break.
- Some shields can be repaired using certain materials. For example, you can repair riot shields using titanium sheets. This should use traits.
- You can examine a shield to see its rough state of integrity.

Not to be confused with the bubble-like energy shields attached to certain articles of clothing.

**Comment by AtnerNT** [comment]
Closed by #10489
