### ISSUE TITLE
Prisoners in jail cells (and just about anyone else) are able to adjust the time on cell timers to let themselves out.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5314]
## Description
The time on cell timers can be reduced using the right click context menu. This is good. However, anyone is able to do this, and prisoners are often able to reach cell timers from inside their cells. This means that prisoners can lower their own sentence and let theirselves out. The ability for anyone to use brig timers could be solved by making it so that adjusting timers requires security access.

### Steps to Reproduce
1.  Set timer on cell timer. Go into relevant jail cell.
2.  From inside jail cell, right click on the timer and reduce your own sentence.
3.  Watch as door opens in response to timer counting down to 0. You're free now.

**Comment by PerfectTangent** [comment]
my god that's funny

**Comment by corp-0** [comment]
maybe make the timer require access?
