### ISSUE TITLE
Crafting recipes should use traits to identify ingredients instead of names.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5320]
## Description
Right now the ingredients in crafting recipe SOs are determined not by referencing a trait the ingredient objects might have, but instead by having the name of the ingredient entered into a text field.

Below, the recipe for making meat cutlets. As you can see, "meat" is in the ingredient text field. This means that the recipe only turns things into cutlets if they are called "meat".
![image](https://user-images.githubusercontent.com/38266309/96295089-326c2980-0fa2-11eb-96ed-3fdb57d64cd8.png)

Below, an item called "meat". 
![image](https://user-images.githubusercontent.com/38266309/96295305-870fa480-0fa2-11eb-8670-1b73dd3c14e3.png)

Crafting recipes should use item traits so that items that share the same name can be used in different recipes and so that you can use differently named items in the same recipe, especially in the case of .prefab variants which can inherit the traits used by their parents. This would also prevent recipes from breaking if the names of the ingredient items were changed.

**Comment by PetMudstone** [comment]
![image](https://user-images.githubusercontent.com/38266309/104233377-a170e700-5406-11eb-994b-eb075380176b.png)
Another reason why crafting recipes should use traits. If an item is renamed using a hand labeler it can't be used to cook anymore.

**Comment by corp-0** [comment]
sounds like it is using ``Name`` instead of ``InitialName``. Initial name does not change, ever. Yes, using strings makes coders angry, but making a trait for each and every ingredient sounds like hell.

**Comment by PerfectTangent** [comment]
closing as this issue is no longer relevant.
