### ISSUE TITLE
Fugitive Spawnpoints and Rebalance

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5346]
## Description

Before the fugitive has any hope of being a fun and viable antagonist, they must have spawn points mapped into all maps in rotation. Otherwise, they will be dead on arrival(s).

- [x] Add Fugitive spawnpoints to Square station
- [x] Add Fugitive spawnpoints to Outpost station
- [x] Add Fugitive spawnpoints to Pog station
- [x] Add Fugitive spawnpoints to Fall station
- [x] Add Fugitive spawnpoints to Box station

Additionally, after some discussion in the discord, some of us believe it'd be best to give the Fugitive a pair of budget insulated gloves inside the toolbox to give them a _slightly_ fairer chance at hacking their way out of maintenance.

- [x] Add Budget Insulated Gloves to the Fugitive's starting toolbox

**Comment by PetMudstone** [comment]
Doesn't the fugitive need wires to hack as well?

**Comment by PerfectTangent** [comment]
If the fugitive has gloves, it helps them to not cook themselves to death through hacking doors, which will be a common way for them to get out of maintenance and into other places.

**Comment by PetMudstone** [comment]
You need wires in order to connect nodes in the hacking interface to other nodes, pretty sure.

**Comment by PerfectTangent** [comment]
correct, but the gloves are significantly harder to come by. If it seems like a bad idea to add the gloves, then perhaps we shouldn't.

**Comment by PetMudstone** [comment]
Could make the gloves appear in the fugitive's hand slot and add wires to his toolbox, easy.

**Comment by PerfectTangent** [comment]
could they just start with wearing the gloves?

**Comment by corp-0** [comment]
I wouldn't say this is high priority. At this point of development only game breaking bugs are high priority, balance and flavor can wait.

**Comment by PerfectTangent** [comment]
If this is not a high priority, then Fugitive should be disabled until it is fixed. The fugitive is pretty unplayable with spawns in arrivals.

**Comment by corp-0** [comment]
Yeah, I think I will disable fugitive from rotation and make it admin spawned only until I attach event system to dead players and respawning as antag.

**Comment by corp-0** [comment]
That said, this issue doesn't hurt anyone. All of those are nice things to have.

**Comment by PerfectTangent** [comment]
completed with #5755
