### ISSUE TITLE
You can't respawn players who die as blob.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5351]
## Description
Title. If someone dies as blob, they can not be respawned. Presumably this is because they completely lack a body and have ceased to exist, similar to what happens when bodies get sold on the cargo shuttle. 

### Steps to Reproduce
1. Have a blob appear.
2. Wait for blob to die.
3. Try to respawn dead blob, watch as you completely fail.

**Comment by corp-0** [comment]
they are a ghost in current implementation

**Comment by PerfectTangent** [comment]
After some of the patches that have come through for blobs, is this still an issue?

**Comment by PerfectTangent** [comment]
as far as my testing goes, this is no longer an issue, seemingly fixed with #5372
