### ISSUE TITLE
Allow attacks to do armor penetration.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5353]
## Description
In /tg/, attacks can have armor penetration values. The armor penetration value of an attack is subtracted from the armor value that is relevant to the attack's type.

For example, a spear is a melee weapon that has 10 armor penetration. The spear is used to stab someone who is wearing a armor vest in the chest. The armor chest has 35 melee armor. However, since the spear has 10 armor penetration you subtract 10 from the 35 melee armor value. 35 - 10 = 25. So now, the armor vest effectively has 25 melee armor after calculations.

**Comment by PerfectTangent** [comment]
an important specification is that armor penetration should not take a target's total armor _below 0_

**Comment by PerfectTangent** [comment]
closing in favour of #6288
