### ISSUE TITLE
Bugged weapons as Wizard

### ISSUE THREAD

**Issue by Humonitarian** [unitystation/unitystation#5354]
### Detailed Bug Report
As wizard I cannot see other people's projectiles, nor hear the sound effects their guns make. I died to such shadowbullets twice on staging, and stumbled upon an interesting error that might help fix it.

### Steps to Reproduce
Be wizard

![image](https://user-images.githubusercontent.com/61586732/96543803-7a8e9300-12a5-11eb-9e70-7a16ed8101d3.png)

**Comment by PetMudstone** [comment]
Note, I saw this as a blob on staging as well. I asked about it in OOC and no one else could hear guns nor see projectiles either. Exact same error, of course.

![gunerorr](https://cdn.discordapp.com/attachments/668605946691452949/767925995130585108/unknown.png)

**Comment by wraith-54321** [comment]
you can see your own projectiles

**Comment by NoooneyDude** [comment]
This issue as described in #5408 has been fixed by #5411.
