### ISSUE TITLE
Sprite Handler Colour isnt sync to new joining clients

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5361]
Sprite Handler Colour isnt sync to new joining clients

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Easiest way is to spawn in as blob
2.  Connect a second client
3.  See blob colour as white not green

**Comment by corp-0** [comment]
can someone test if #5364 fixed this one?

**Comment by ThatDan123** [comment]
Looks like it been fixed, tested with blob. So going to close.
