### ISSUE TITLE
Emagged Lockers only showing serverside

### ISSUE THREAD

**Issue by Skrimble** [unitystation/unitystation#5367]
## Description
Emagging lockers does not show correctly for clients
### Detailed Bug Report
Server
![Server host](https://user-images.githubusercontent.com/72901951/96673171-80c75280-132b-11eb-9e3b-387a7e07882b.png)
Client
![Client](https://user-images.githubusercontent.com/72901951/96673170-80c75280-132b-11eb-8e55-283192f4849d.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Open 2 instances of the game
2.  Host a server on one and join on the other
3.  Spawn an Emag and Emag a locker from either game
4. View black dot on server, and green on client

**Comment by corp-0** [comment]
I think lockers code is ancient with some patching. Updating it to use the new spriteHandler might be the best.
