### ISSUE TITLE
Square Station cargo shuttle ghost

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5374]
Cargo shuttle works fine in editor but on headless the shuttle doesnt leave the station and you can walk through it where you die from suffocation as you cant move anymore.

Tested outpost station and shuttle worked fine there, couldnt find anything different about the two setups.

1)Build headless
2)Load square map
3)Send cargo shuttle
4)See cargo shuttle hasnt left and walk into it:

![image](https://user-images.githubusercontent.com/56727168/96747247-f3820d80-13bf-11eb-8e2a-b541b4944b4e.png)

**Comment by Bod9001** [comment]
I was able to reproduce theshuttle just turning into station and being stuck there tho, I didn't get stuck in it when moving around

**Comment by Bod9001** [comment]
the shuttle on Square actually rotates you have to re-log to see the change
