### ISSUE TITLE
Wizards Ship/Area needs expanding

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5375]
Wizards Ship/Area needs expanding

For obvious reasons:
![image](https://user-images.githubusercontent.com/56727168/96749303-8d4aba00-13c2-11eb-9306-97949b522e5d.png)

**Comment by Bod9001** [comment]
due to delays this will have to be postponed for 4116

**Comment by PerfectTangent** [comment]
completed with #5525
