### ISSUE TITLE
Hacktoberfest label missing

### ISSUE THREAD

**Issue by TheoGimenez7** [unitystation/unitystation#5378]
## Description
You forgot to add the hacktoberfest-accepted label.

### Detailed Bug Report
This year, hacktober needs a new label called hacktoberfest-accepted.

Here is the webpage where it's described : 
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Here is a link to the specific solution : 
https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-label-add-gif-min.gif

Thanks and good hacktoberfest !

**Comment by corp-0** [comment]
we have the Hacktoberfest topic so we don't need the label. You can try doing a PR and you will see how when merged it will count for the event.

**Comment by TheoGimenez7** [comment]
Oh ok ! I thaught that the label was necessary.
