### ISSUE TITLE
Ebow does not work

### ISSUE THREAD

**Issue by ProtivogaSpriter** [unitystation/unitystation#5381]
## Description
The traitor-spawned ebow does not work,in general. It appears unloaded,and refuses to generate new ammo.

### Steps to Reproduce

1.  Roll traitor
2.  Buy ebow
3.  Try to shoot ebow but fail miserably

**Comment by Bod9001** [comment]
guns are Been strange
NullReferenceException: Object reference not set to an instance of an object
Weapons.Gun.UpdateMe () (at /Assets/Scripts/Items/Weapons/Gun.cs:459)
UpdateManager.Update () (at /Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:256)

-------------------------------------
NullReferenceException: Object reference not set to an instance of an object
Weapons.Gun.DisplayShot (UnityEngine.GameObject shooter, UnityEngine.Vector2 finalDirection, BodyPartType damageZone, System.Boolean isSuicideShot) (at Assets/Scripts/Items/Weapons/Gun.cs:654)
Weapons.Gun.DequeueAndProcessServerShot () (at Assets/Scripts/Items/Weapons/Gun.cs:557)
Weapons.Gun.UpdateMe () (atAssets/Scripts/Items/Weapons/Gun.cs:423)
UpdateManager.Update () (at /Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:256)
------------------------------------------------

**Comment by NoooneyDude** [comment]
This does not appear to have been fixed by #5418.
