### ISSUE TITLE
CloningConsole does not give feedback on some user actions

### ISSUE THREAD

**Issue by JustinTrotter** [unitystation/unitystation#5382]
## Description
Whenever a player uses the cloning console, button presses on the UI do not give any responsive feedback. For example pressing the 'Lock Scanner Door' button does not change the interface in any way. This is a problem if the scanner is not powered by an APC.

### Detailed Bug Report
Implement proper error messages for the CloningConsole.
For 'Lock Scanner Door' button:
- [ ] Disconnected from APC
- [ ] Unpowered / Low voltage
- [ ] Successful Lock
- [ ] Successful Unlock

For 'Start Scan'
- [ ] Disconnected from APC
- [ ] Unpowered / Low voltage
- [ ] Scanner is empty

### Steps to Reproduce
Please enter the steps to reproduce the bug or behavior:  

1. Use screwdriver on DNAScanner to disassemble.
2. Use screwdriver on DNAScanner to reassemble. (This disconnects it from APC)
3. Use screwdriver on CloningConsole to disassemble.
4. Use screwdriver on CloningConsole to reassemble. (This connects console to scanner)
5. Try to start scan or lock the scanner door, note that the interface does not change.

**Comment by JustinTrotter** [comment]
I'll have a PR for this soon.

**Comment by corp-0** [comment]
you make the issue and the fix? What a good service ⭐ ⭐ ⭐ ⭐ ⭐
