### ISSUE TITLE
Stuck firespot

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5387]
![firespot](https://user-images.githubusercontent.com/701959/96938975-1f75bf80-14a2-11eb-9f8a-cca2e8760b73.gif)

## Description
Found this in staging, there was plasma all around it before I stared recording. The firespot was there before the plasma disappeared and after it was gone. I didnt see any other firespots but I latejoined

**Comment by PetMudstone** [comment]
I do believe I walked onto that firespot. Notably, it doesn't actually do anything. I walked through it and stood in it, but it did absolutely nothing.

**Comment by Aranclanos** [comment]
![afk fire](https://user-images.githubusercontent.com/701959/98162038-7f675f80-1ebf-11eb-9b2e-fba5fd18669c.gif)
another example, just now on staging

people used fire extinguishers on them with no effect

**Comment by PerfectTangent** [comment]
closing in favour of #6398
