### ISSUE TITLE
Vote window stays on forever if you dont vote

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5395]
## Description

![image](https://user-images.githubusercontent.com/701959/97064115-32f45980-157a-11eb-8cbd-64b5069caebd.png)
I didn't vote and this window was still on
I believe the round was restarted manually by an admin before the vote finished but I can't be 100% sure about that
The buttons didn't do anything so all players in that round had the window up, it went away when I clicked veto

**Comment by NoooneyDude** [comment]
Yes, I believe the criteria is to have an admin restart the round via the admin tools while a restart vote is recurring.

**Comment by MaxIsJoe** [comment]
Does this still happen? I believe it's fixed after my expansion of the vote system
