### ISSUE TITLE
Refactor shuttle fuel system

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#5397]
Now that atmospheric piping exists, player-controllable shuttles should be updated to utilise it.

- Engines should require a plumbed source of fuel, and not effectively teleported from the fuel canister.
- Stock engines should probably use hydrogen fuel, given that they are considered hydrogen engines.
- Engine variants and different fuel sources to provide different shuttle performances could provide gameplay.

**Comment by MaxIsJoe** [comment]
This is done.
