### ISSUE TITLE
Multiple blob antags cause the latest blob antag to be able to place special tiles

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5398]
## Description
There is a bug that occurs when there are multiple blobs; it seems only the latest blob can place special tiles, resulting in all the previously established blobs to lose the ability to place anything other then a normal blob tile (strong/reflective/factory tiles) or delete a tile.

### Detailed Bug Report
When I tested this on staging we got a lot of these sending commands without authority, so the code probably think we shouldn't be able to place the blob tile as we aren't the latest blob.
https://media.discordapp.net/attachments/668605946691452949/769468475969765376/unknown.png?width=1026&height=247
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Give two players blob infection
2.  Wait for them to become blob
3.  Watch as only one blob can place the important tiles

**Comment by NoooneyDude** [comment]
I've observed this behaviour on staging, too.

**Comment by NoooneyDude** [comment]
Might be fixed by PR #5384?

**Comment by ThatDan123** [comment]
Yeah, should be fixed
