### ISSUE TITLE
Palettable shoes lose their assigned colors then regain them every time you change direction.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5419]
## Description
For some reason, palettable shoes will lose their assigned colors when you change directions and then regain them when you change directions again. It goes like this.
Lose colors > regain colors > lose colors > regain colors > lose colors > regain colors
and so on.

![weird palette](https://user-images.githubusercontent.com/38266309/97116435-4c9cba80-16ba-11eb-8f70-319ce7bc2816.gif)

### Steps to Reproduce
1.  Spawn in.
2.  Change direction, your shoes will be green.
3.  Change direction again, your shoes will become their proper colors again.
4. Change direction for the third time, your shoes will be green again, and so on.

**Comment by PetMudstone** [comment]
@Ruzihm Could you try looking into this?

**Comment by Ruzihm** [comment]
@PetMudstone  Yes, #5405 will fix this ;)
