### ISSUE TITLE
Deconstructing false reinforced walls gives you 4 metal sheets instead of 2 metal sheets and 2 plasteel.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5424]
## Description
Title. Deconstructing false reinforced walls using a welder doesn't give you 2 plasteel and 2 metal sheets as it should. Instead, it gives you 4 metal sheets.

### Steps to Reproduce
1.  Make a girder using 2 metal sheets and unsecure it.
2. Place 2 plasteel on it to make a false reinforced wall.
3.  Use a welder on the false reinforce wall to deconstruct it, receive 4 metal sheets instead of the materials you used to make the false wall.

**Comment by DTraitor** [comment]
Now it gives 1 plasteel and a gridder

**Comment by PerfectTangent** [comment]
Just tested in game and this doesn't appear to be the case. When dissassembling an rwall, the first sheet is gotten by taking apart the wall down to the reinforced girder and the second sheet is gotten by disassembling the girder down to a regular one. Closing.
