### ISSUE TITLE
Ding! Add the Service Bell

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#5435]
- [x] The object of this issue is to add the service bell world object to the game, for mappers to place. The service bell sits on a tabletop at the kitchen or bar, and when clicked on, will emit a single, clear, ding.

- [x] Additionally, there is the big service bell, which should have a 0.5% chance of replacing any normal service bell at round start. Instead of the standard ding, it will emit a much larger bell dong! to reflect its bigger size and acoustic capability.

Sprites by Erinexx:
Service Bell: https://cdn.discordapp.com/attachments/409110435900424196/771411832211636315/unknown.png
BIG BELL: https://cdn.discordapp.com/attachments/402986688114065409/731227871321915603/unknown.png

Sounds:
Service Bell: https://puu.sh/GI5HD/6b05344dfc.ogg
BIG BELL: https://puu.sh/GI5Ic/7adc11e7f1.ogg

**Comment by CdrCross** [comment]
@corp-0 Requesting that the issue get reopened. The big bell was not added in #5558, and thus the issue is incomplete.

**Comment by ewy1** [comment]
I've been working on this and it's nearly done but I'm quite busy this week, so it might take a little longer.
