### ISSUE TITLE
Ghost Orbit

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5437]
## Description
Ghost players should get the button to orbit because it is taxing to follow people around all the time. To make this work, the players pressing the existing orbit button down the bottom to follow another player from a menu and see their point of view. Roughly the following features should be implemented to achieve this:

- When the orbit button is pressed, the player initially selects from a menu similar to the “Teleport to Player” menu
- Their ghost sprite should orbit around the player that they are following in a circle.
- ghosts can orbit a number of different entities, not just players. They can orbit any object or item by double clicking it, allowing ghosts to follow singularities, the nuke disk, or other important things.
- The left and right movement keys allow them to cycle their viewpoint allowing them to quickly navigate around to other points of interest (probably would help admins out a lot)
- While in this mode the orbit button turns into a red X, notifying the player that by clicking it they will stop orbiting altogether and be free to move again. Also closes the menu that is similar to the “Teleport to Player” menu.

**Comment by NoooneyDude** [comment]
Might I suggest using the arrow keys to navigate the different POI, instead of the movement keys? Keep the movement keys for disengaging from the current POI orbit to move around the local area.

**Comment by Akbadain29** [comment]
Yeah, that'll probably work a lot better.

**Comment by JustinTrotter** [comment]
I’ll take this one.

**Comment by corp-0** [comment]
I assigned you. If for any reason you stop working on it, just let us know so we can change the labels to better represent current state of the issue.

**Comment by JustinTrotter** [comment]
@corp-0 go ahead and unassign me. Got some personal stuff to deal with for the next couple of days.

**Comment by corp-0** [comment]
sure thing man
