### ISSUE TITLE
Add a "You have no body!" notifier

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#5444]
## Description
Add a "You have no body!" notifier to when you try to re-enter your body when gibbed
The text should be bright red

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Re-enter your "body" when gibbed, no text.

**Comment by Macoron** [comment]
Closing it - copy of #5445

**Comment by Cboyjet4** [comment]
> Closing it - copy of #5445

whoops, i must have accidently duplicated it somehow. thanks.
