### ISSUE TITLE
Examination Items should have an icon next to the text.

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#5448]
## Description
When you examine someone, the items they are wearing have an icon next to them.

Example - 
![image](https://user-images.githubusercontent.com/71295203/97793627-ba118500-1bab-11eb-9271-b787028e5c15.png)

**Comment by Fogapod** [comment]
Isn't it something that would be reworked by #5206? Seems like a separate window is suggested for examination (9)

**Comment by CdrCross** [comment]
Yeah, this issue is rendered irrelevant by #5565. Feel free to Close this issue.

**Comment by NoooneyDude** [comment]
I've linked the issue, so it'll autoclose when merged.

**Comment by PerfectTangent** [comment]
Hm, looks like it didn't close as it should have for some reason. Closing.
