### ISSUE TITLE
Xenos ignore players

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5450]
## Description
Build 5440

### Detailed Bug Report
Xenos move properly, but they ignore players completely even when attacked. From facehuggers to queen, they all do this.

### Steps to Reproduce
Find Xenos and go near it or try attacking.

**Comment by Macoron** [comment]
They don't attack on sight, but if you punch it three times, they will attack you. I'm not sure if it's intended behavior or not.

**Comment by Fogapod** [comment]
I'm not sure what is going on, but xenos are hostile again on staging, same build. Were some settings changed?
There are a few more bugs like this that depend on some broken state I guess. Closing for now as I can no longer reproduce and preconditions are unknown.
