### ISSUE TITLE
Problems with numpad and keybinds

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5451]
## Description
Build: 5440
OS: ARch linux
Keyboard: Razer USA, Ltd BlackWidow (2019)
Driver: openrazer

Numpad layout
7 8 9
4 5 6
1 2 3

### Detailed Bug Report
* With default settings my targetting controls on numpad are offset to the right by 1 key, 7 and 4 do nothing and 1 cycles between intents.
* When overriding targeting hotkeys with numpad, game confuses left and right parts of my numpad. For example, if I want left hand on 4, I must use 6 when configuring.
* Default point hotkey involves mouse, but it does not work, hotkey configurer does not allow me use combinations involving mouse.

I think I didn't have these issues a few months ago. I remember using point and numpad worked properly. All other apps properly process numpad keys.

**Comment by corp-0** [comment]
can you check what are the set keybindings on your settings?

**Comment by Fogapod** [comment]
@corp-0 Do you need my config file? Or screenshot of in-game settings?
Default settings or the ones I set?

**Comment by corp-0** [comment]
screenshot is fine or just see if they match with what you're experiencing. What's your keyboard layout?

**Comment by Fogapod** [comment]
```shell
$ setxkbmap -query                                                                                       [0]
rules:      evdev
model:      pc105
layout:     us
```

My settings:
![image](https://user-images.githubusercontent.com/22667809/101342001-fadb7880-3892-11eb-814f-1cbf0dd81c05.png)

What buttons do:
4 - right hand
1 - right leg
6 - left hand
3 - left leg
8 - head
5 - chest
2 - groin

**Comment by Fogapod** [comment]
I no longer have this issue, I think it disappeared after installing game from flatpak around a month ago
