### ISSUE TITLE
Hitting W/A/S/D while typing in chat makes you leave body as ghost

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5455]
## Description
Build: 5440

### Detailed Bug Report
See title. (includes both normal chat and ahelp)

### Steps to Reproduce
Die, remain in body/reenter, type w or a or s or d in chat.

**Comment by duskwalker05** [comment]
moving whilst typing into the chat occurs in more recent builds too, even if not a ghost

**Comment by Fogapod** [comment]
In my particular case I didn't move, ghost left body, but remained on same tile

**Comment by NoooneyDude** [comment]
Related to issue #5303.

**Comment by PerfectTangent** [comment]
I haven't experienced this issue since #6775. Closing.
