### ISSUE TITLE
suggestion: UI button for bug reports

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5458]
## Description
Since the game is in alpha, bugs are pretty frequent. Users should have a quick way to report them.

### Detailed Description
Initial idea: A button called "Report a bug" that opens a window with options:
* GitHub - opens new issue link, described below
* Discord - opens discord invite
* Something else?

GitHub supports new issue urls that could work as a template, try this:
https://github.com/unitystation/unitystation/issues/new?body=%23%23%23%20Version%0ABuild%3A%205440%0APlatform%3A%20Linux%0A%0A%23%23%20Description%0A%0A%23%23%23%20Detailed%20Bug%20Report%0AIt%20helps%20if%20you%20include%20any%20relevant%20DM%20code%20%2F%20config%20(for%20describing%20how%20new%20features%20should%20work)%2C%20images%2C%20gifs%2C%20or%20youtube%20videos!%0A%0A%23%23%23%20Steps%20to%20Reproduce%0APlease%20enter%20the%20steps%20to%20reproduce%20the%20bug%20or%20behaviour%3A%20%20%0A%0A1.%20%20%0A2.%20%20%0A3.%20%20

P.S. Title can be set too with `&title=Something` but it's probably better to leave it blank to avoid a few invalid reports that users might post without describing issue properly.

Some info like operating system and game version (will work even better with #5089) can be formatted automatically.
There could also be a template for suggestion.

**Comment by Fogapod** [comment]
Alternatively, user can be directed to this url: https://github.com/unitystation/unitystation/issues/new?template=bug_report.md
Pros:
- Labels are added automatically
- No need to keep 2 versions of bug template in sync

Cons:
- You can't add info like game version automatically

**Comment by NoooneyDude** [comment]
Related to #5064.

**Comment by PerfectTangent** [comment]
honestly, redundant with #5064. Closing.
