### ISSUE TITLE
Janitor trash bag can't be unloaded into disposals

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5462]
## Environment
- Game Version: Build 5440
- OS Version: 

### Detailed description of bug
I'm not sure how am I supposed to put items into disposals: empty trash bag near it and put each item inside by hand? It takes a lot of time.

### Steps to reproduce

1. Collect item with trash bag
2. Click on disposals
3. See error: nothing to pick up

**Comment by NoooneyDude** [comment]
Please use the search function to see if a similar issue already exists. In this case, that is issue #4938. Thanks!
