### ISSUE TITLE
Sometimes you can punch yourself when clicking on something else while on harm intent

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#5467]
## Environment
- Game Version: Staging 5422
- OS Version: Windows 10 1803

### Detailed description of bug

Sometimes rapidly clicking on something on harm intent, you will end up punching yourself

(May be due to my bad internet, please close it if that's the case after testing)
### Steps to reproduce

1. Rapidly click on harm intent
2. Punch yourself
3. don't die

**Comment by Fogapod** [comment]
I get some issues with missclicking including this one, when wrong tile gets activated. Not sure if this is the same issue, can't figure out yet in what conditions this happens
