### ISSUE TITLE
Item pickup box occupies entire tile after hovering sprite with mouse

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5469]
## Environment
- Game Version: Bild 5440
- OS Version: 

### Detailed description of bug
When you hover mouse over some item and then move mouse outside of item sprite (mouse should remain on the same tile), item description gets stuck and you will pick it by clicking any pixel on this tile until mouse leaves tile. This is especially annoying with lockers when you want to close them, but pick an item instead.
Not sure if this is intentional, but this is annoying to me and I would prefer picking items only when my mouse is directly above their sprite.

Not sure if it always been that way, but I've noticed this only recently because I started having problems with closing lockers and boxes.

### Steps to reproduce

1. Drop something small on floor
2. Hover mouse over item sprite
3. Click mouse anywhere on the same tile, outside of item sprite
4. Observe how item is picked and item description being stuck while mouse is outside it's sprite

**Comment by Fogapod** [comment]
New round just started and I don't have this issue anymore. It looks like there is some precondition to it, but it happens fairly often.

The other bug in that round was all vending machines never updating stock numbers visually. Could this be related?

Happened 2/2 times I tested on Fallstation, might be map related.

**Comment by PerfectTangent** [comment]
I have been unable to reproduce this issue. Closing for now. It can be reopened if we get another report.

**Comment by Fogapod** [comment]
I still experience this on latest staging, on FallStation again.
Here's the video:
https://user-images.githubusercontent.com/22667809/118249543-34ea1f80-b4ae-11eb-9b90-f22b1a2b76d8.mp4
I can click on locker until i hover mouse over item. Ater this I start picking up that item anywhere i click on that tile.

@PerfectTangent could you reopen this?

**Comment by Fogapod** [comment]
Since I'm the only one who reported this and I haven't had this issue for a while now I'm closing it
