### ISSUE TITLE
Name is displayed as Unknown if you have PDA with ID equipped in ID slot

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5470]
## Environment
- Game Version: Build 5440
- OS Version: 

### Detailed description of bug
When you examine someome with PDA equipped on ID slot and ID inserted, name is Unknown.

There was a discussion on discord about ID/PDA inconsistency. Either PDA should not be equippable into ID slot and not act like ID (open doors when held) or it should behave exactly like ID and display name properly.

### Steps to reproduce

1. Insert ID into PDA
2. Equip PDA on ID slot
3. Examine yourself

**Comment by Fogapod** [comment]
Another round just started and I don't have this issue anymore. It looks like there is some precondition to it, but it happens fairly often.

**Comment by NoooneyDude** [comment]
Fixed by #5774.
