### ISSUE TITLE
Gun bugs

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5487]
A few errors I found in develop:

1- Clients cant fire energy guns unless they click on them while holding them in their hand
2- Clients dont sync the energy gun firemode with the server, ej: the clients see themselves shooting a disabler while the server and other clients shows a laser
3- Energy guns can get stuck and refuse to fire for any player
4- Sometimes a runtime pops out when a mob gets hit by a gun

**Comment by AutumnNova** [comment]
#5418 fixed 3-4

**Comment by Aranclanos** [comment]
I got all four in current develop
