### ISSUE TITLE
Grenades don't appear when spawned in by admins and minibombs aren't created by the uplink while connected as a client.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5498]
### Environment
- Game Version: Staging Build 5491
- OS Version: Windows 10

### Detailed description of bug
For some reason, grenades and minibombs spawned in by admins don't seem to exist. Minibombs also don't appear when you buy them with the uplink. Right clicking on tiles where they should be after they get placed done brings up nothing. On the other hand, combustible lemons don't render for clients when spawned in by admins but using right click on tiles where they are shows that they indeed do exist. Lemons can also be picked up and also primed for detonation.

This only happens if you are connected to a server as a client. As the host (including in the editor), you will see everything as you normally would.

### Steps to reproduce.
1. As an admin connected as a client, search up grenades, explosive lemons, and minibombs in dev spawner.
2. Select and spawn them, notice that they don't seem to appear.
3. Right click on their would-be locations where you clicked. Notice that grenades and minibombs just don't exist and that the lemons exist but are invisible.

**Comment by wraith-54321** [comment]
its just nades in general, the centcom armory ones are gone and they dont spawn when bought from a nukie vendor
