### ISSUE TITLE
Spawned in scenes have initialisation issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5514]
Spawned in scenes like the nuclear operatives shuttle/base and wizard scene have these issues:

-Populators do not work for mapped items, eg lockers populators not working.

-Items mapped on top of lockers do not go into the lockers on spawn.

![image](https://user-images.githubusercontent.com/56727168/98255941-e2b3c900-1f75-11eb-86a7-ab1a2fe2cbb5.png)

### Steps to reproduce

1. Respawn self as wizard/nuclear operative
2. See lockers have no contents
3. See items on top of lockers/crates which should be in them at spawn

**Comment by Bod9001** [comment]
I think this should be fine to not have in 4116 , if No one can do it by the time
