### ISSUE TITLE
NPC bodies become invisible when gibbed

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5519]
### Environment
- Game Version: Build 5497
- OS Version: 

### Detailed description of bug
When you gib mobs with kitchen knife, kill mouse, destroy body with weapon, it leaves invisible corpse that can be seen in left click menu. It can also be dragged.

Seems like this was introduced by https://github.com/unitystation/unitystation/pull/1436. There is a comment addressing this: https://github.com/unitystation/unitystation/pull/1436#discussion_r247429898 not sure if they actually fixed it or no.

### Steps to reproduce

1. Find and kill a mouse
2. Hover cursor over dead body
3. Left click

**Comment by Fogapod** [comment]
These bodies also spam a million nullreference exceptions when mouse hovers over them

**Comment by NoooneyDude** [comment]
Is this related to gibbing or just when mobs are killed? If the latter, this issue can be closed in favour of #6427.
