### ISSUE TITLE
Can't interact with lockers and other things

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5540]
I think it's related to clients server mismatch location maybe

**Comment by Bod9001** [comment]
interestingly its intermittent, humm  requires further testing linked to #5541

**Comment by NoooneyDude** [comment]
Is this still an issue?

**Comment by Korywon** [comment]
I tried it out myself. I wasn't able to lock lockers and chests with ID before; I could only open them. I don't have that issue anymore.
