### ISSUE TITLE
client thinks it can walk into disposals, water tank, lockers when it can't

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5541]
is on staging currently

**Comment by wraith-54321** [comment]
this happens to other objects and a relog fixes it, for things like lockers it also makes it so you cant open them

**Comment by Aranclanos** [comment]
more stuff related to this

![image](https://user-images.githubusercontent.com/701959/98444094-98098c80-20ee-11eb-9874-6a02c3e484a1.png)
the countdown timer went on several times and players experienced a "space screen" where they couldnt do anything, upon relogging they were met with the countdown timer again

I triggered the admin end round button and the animation played, but the round never actually restarted

![image](https://user-images.githubusercontent.com/701959/98444089-8de78e00-20ee-11eb-87dd-c76004a8d85d.png)
After relogging I was able to join the round as a ghost -jobs were forbidden with a "round hasnt started" message- and noticed how lockers didnt run their OnSpawnServer()

**Comment by Aranclanos** [comment]
There's no runtime report on the server either, this is all on staging

**Comment by Aranclanos** [comment]
The round was marked as nukeops on the admin buttons

**Comment by Aranclanos** [comment]
I fixed the one I posted in the comments but im unsure if its the one in the OP, however, does it still happen?

**Comment by NoooneyDude** [comment]
Still an issue?
