### ISSUE TITLE
Bloodstains in space

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5550]
![image](https://user-images.githubusercontent.com/701959/98442709-03e6f780-20e5-11eb-8fea-c5696af7b3f5.png)

These bloodstains dont really fit with the 0 gravity emptyness of space, making them look out of place

**Comment by wraith-54321** [comment]
maybe they should instead use the blood droplet sprite, as I believe thats how the blood would behave

**Comment by jamessimo** [comment]
With the new tile reagent system it is correct that reagents should also be able to float in space. I’m interested to learn more about this “droplet” sprite. Can somebody link to the file. The FX factory already checks if you’re on space or not so would be quite trivial to replace a sprite with an “in space” sprite if that would look better.
