### ISSUE TITLE
Movement gets clunky when moving through different matrix

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5553]
![matrix move](https://user-images.githubusercontent.com/701959/98442860-2cbbbc80-20e6-11eb-8164-324c1f3d571f.gif)
here I'm holding the arrow key nonstop, yet my character makes a small stop each time it changes from the shuttle matrix to the station/space matrix

**Comment by Aranclanos** [comment]
ping related! you wont reproduce it locally easily
on the gif I'm probably at 200ms

**Comment by PerfectTangent** [comment]
Interesante. Is it not necessarily something that's fixable?

**Comment by Aranclanos** [comment]
cant say until figuring out exactly whats the issue

**Comment by ThatDan123** [comment]
Doesnt seem to be an issue with the new movement
