### ISSUE TITLE
BoxStation/Others have a lot of BVOld Stuff

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5563]
### Environment
- Game Version: Staging 5538
- OS Version: Windows

### Detailed description of bug
The maps still have BVOld objects on them, I'm currently solving this on BoxStation, _please just assign me to make it official please._
(BVOld gameobjects are objects which are too old for a scene and do not work properly)

**Comment by NoooneyDude** [comment]
BVOld prefabs were completely removed by #5691.
