### ISSUE TITLE
Weapons no longer work in current develop

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5573]
Just updated my local with develop and made a build

Tested with PKAs, energy weapons, ballistics, foam and syringe guns, clients cant shoot anything

The server player cant seem to be able to shoot with syringe guns either

**Comment by AutumnNova** [comment]
#5546 was tested by nooney, according to them they encountered no issues, you sure its just not unity being weird?

**Comment by PetMudstone** [comment]
After making a build, I can confirm that guns don't properly work as a connected client. Server host can indeed fire weapons as stated above.

**Comment by corp-0** [comment]
I giving this high priority as it is game breaking and a regressive bug

**Comment by NoooneyDude** [comment]
That's interesting. I did test PR #5549 on headless with two clients, the first could shoot fine and the second did see the projectiles from all the guns in TestStation armoury. Quick Load was enabled and extra scenes were disabled with the new feature from PR #5564. I did not test the guns after a round restart.
