### ISSUE TITLE
You are able to interact with window and wall tiles from an extra tile away.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5578]
### Environment
- Game Version: Develop, as of [commit 36a3211a5c3958979f433c3531f1a0b21286dcd6](https://github.com/unitystation/unitystation/commit/36a3211a5c3958979f433c3531f1a0b21286dcd6).
- OS Version: Windows 10

### Detailed description of bug
#5570 and #5568 made it possible to interact with objects on windows and walls from an extra tile away. However, it also made it possible to interact with the walls and windows themselves from an extra tile away. This allows you to attack windows or deconstruct both them and walls from range.

### Steps to reproduce
1. From two tiles away, click on a window tile with an item (such as a toolbox) in hand.
2. Watch as you attack it.
OR
1. From two tiles away, click on an ordinary wall with a lit welder.
2. Watch as you start cutting it apart.

**Comment by corp-0** [comment]
maybe offsetting the sprite was good enough

**Comment by Ruzihm** [comment]
@corp-0 From discussion in #4720 it seems like sprite offsetting is the way to go, not even including this problem. I'll remove the extra square reachability in a new PR.
