### ISSUE TITLE
Missing wire at Box

### ISSUE THREAD

**Issue by DTraitor** [unitystation/unitystation#5582]
### Environment
- Game Version: last, build 5538
- OS Version: Windows 10

### Detailed description of bug
At coordinates -191, 45 (medbay) if I am not mistaken missing low voltage wire so part of the medbay is not powere at all
<!-- What is broken? What should be happening instead? Include as much informations as possible. Images, gifs, or youtube videos are welcome! --!>

**Comment by PerfectTangent** [comment]
has this been done?
