### ISSUE TITLE
Status display showing both shuttle timer and news

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5587]
![image](https://user-images.githubusercontent.com/701959/98730521-298d2e80-237b-11eb-812e-eafd6dd14e7e.png)
Just spotted it after latejoining as observer in potatostation

**Comment by DTraitor** [comment]
Now it doesn't work at all

**Comment by PerfectTangent** [comment]
Could not replicate, likely fixed by #7670
