### ISSUE TITLE
App for mapping

### ISSUE THREAD

**Issue by DTraitor** [unitystation/unitystation#5594]
### Description
What about to make some sort of app for making maps? It will use standart admins "Spawn object" + walls/floor tiles etc and add feature to manually connect stuff like cloning pods, make shuttles etc. Since a lot of players cant run Unity with stable 60 fps this app will be very uselful. If you need I can add some arts how it should look.

**Comment by AtnerNT** [comment]
Bod is working on an ingame mapping system, is this issue still relevant?

**Comment by MaxIsJoe** [comment]
we have mapping tools in-game now.
