### ISSUE TITLE
Unable to interact with lockers, vendors, items that spawn on map start, canisters, etc

### ISSUE THREAD

**Issue by AutumnNova** [unitystation/unitystation#5603]
### Environment
- Game Version: 
- OS Version: Arch Linux x64

### Detailed description of bug
when loading into a round i was unable to use nettabs, i quit out of the game entirely and rejoined, noticing a error message about job preferences. When i regained control of my character i was unable to interact with most mapstart objects, if i attempted to walk into them i would appear to walk ontop of them before rubberbanding back to the tile i was just standing on.
This was not exclusive to roundstart items as i was unable to pick up objects dropped by other players
### Steps to reproduce

1. Quit out of a game a little while after roundstart
2. Reopen the game and rejoin the server

**Comment by PetMudstone** [comment]
This appears to be a oddly common issue. It is often that multiple people in a single round report having similar issues. They can't interact with lockers and other objects, which greatly complicates gameplay.

**Comment by AutumnNova** [comment]
seems to be the same issue as #5540

**Comment by Aranclanos** [comment]
cant reproduce locally

**Comment by AutumnNova** [comment]
seems to have been fixed at some point, closing
