### ISSUE TITLE
NaN temperature when trying to fill an empty tank

### ISSUE THREAD

**Issue by jedi5218** [unitystation/unitystation#5630]
### Environment
- Game Version: Build 5608
- OS Version: Windows 10, reproducible on Linux clients as well

### Detailed description of the bug
If an empty canister (like unlabeled yellow canisters or those created from metal) is connected to a pipe section, that section gets a NaN temperature. Any attempts at filling the pipe section would drain the gas down to 0KPa while keeping the temperature of that section at NaN. The only way to then use that pipe section normally is to reconstruct it entirely. Any canister, connected to the NaN-temperature pipe section will be immediately drained to 0KPa and then behave exactly like an empty canister. mentioned above.

### Steps to reproduce

1. Construct a pipe section with a canister connector attached, or use station atmospherics filling setup, with a pressure meter attached.
2. Attach an empty (see description above) canister to the connector, and open the valve
3. Temperature in the pipe is now NaN, as indicated by the pressure meter.
*Edit: pressure readout is actually at 0kPa, and the temperature is NaN*

**Comment by NoooneyDude** [comment]
I have reproduced this, but I have also had the canisters work as intended. It might be intermittent or need some other condition to occur for it to happen.

**Comment by jedi5218** [comment]
were the canisters working as intended already partially filled?

**Comment by NoooneyDude** [comment]
No. These were empty, unassigned canisters that were mapped in.

**Comment by jedi5218** [comment]
can confirm. Any canister mapped in without any gas will work normally, but crafted, default empty, or those that were connected to NaN-temperature pipes will replicate the issue. Another interesting point is that any canister affected has its tank filling cap missing on the sprite, like the one shown on the right.
![Снимок экрана (35)](https://user-images.githubusercontent.com/9496281/99218517-58742c00-27e3-11eb-9125-27d8992050b2.png)

**Comment by jedi5218** [comment]
After further attempts at replication, it seems like there are several additional details:

- Pipe section attached immediately to the tank must have no gas inside
- **A pump must be pumping into the section**. The pipe section and the attached canister get NaN temperature when the pump is enabled. 
- Tanks and pipes still contain the amount of gas in moles they had before getting NaN temperature
- NaN temperature does not propagate through pumps
- Having a running pipe leading out of the NaN-temp section will make the meter temperature reading 0K, however attached tanks will still get NaN temperature. The same behavior can be observed if a tank with NaN-temperature gas is attached to an emty pipe section
