### ISSUE TITLE
Adminmusic, and some other sounds are strangely muffled

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#5652]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Playing adminmusic is muffled, some other sounds also seem to have this problem (jukebox,etc)

### Steps to reproduce
1. Play adminmusic
2. Play jukebox
3. Etc

**Comment by PerfectTangent** [comment]
addressed by #6044 and #6058
