### ISSUE TITLE
Admin tool for viewing/editing user inventory

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5657]
### Description
Currently admins have no way of checking user inventory and giving/removing items.

Requirements for new UI element:
- view items and clothing/inspect variables
- remove items
- ability to go inside arbitrarily nested boxes (So that you won't have to move box to hand slot first to open it)
- a way to put item directly into slot

**Comment by PerfectTangent** [comment]
Was fixed with the aghost inventory examination. (still can't open container in person's inventory yet, though.)
