### ISSUE TITLE
Picking up the service bell with right click menu causes it to stop existing.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5659]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Since you can't pick up service bells by left clicking on them (that dings them instead), you might try to pick them up using the right click menu instead. However, trying to pick up a service bell in this way cause the service bell to stop existing, for some reason.
### Steps to reproduce

1. Right click on service bell.
2. Go to pick up option.
3. Try to pick up service bell, watch it disappear.

**Comment by duskwalker05** [comment]
theres a similar issue with posters but if you don't put anything in your hand and click on a wall it functions normally but as soon as you put something into that hand it disappears

Steps to reproduce:
1. pick up poster
2. watch it not show up in hand and disappear from floor
3a. place it on a wall or
3b. pick another object up in that hand
4. if you placed it on a wall watch it be placed normally, if you picked up another object watch the poster disappear

**Comment by Lizurt** [comment]
This only affects the headless server. I can't even make a `Ding!` sound on it

UPD: Well, we have 3 cases:

- Non-headless server: everything works fine
- Headless server: everything is broken
- Server 5608: some things are broken, but not all

Logout and subsequent login to the server helps to return the bell to the game.

Unfortunately I have no idea what causes this bug.

**Comment by Lizurt** [comment]
Another attempt to fix this bug failed, but I'm ready to share information if anyone needs it here.

- The service bell dissapears before the `ServerPerformInteraction()` method is called(at least on the client)
- `ServerRollbackClient(interaction)` call(if the bell can't be picked up(the intent isn't "Grab")) won't help
- The stack traces of the pick-up methods are almost same, except that picking up using LMB calls `ServerCheckAndTrigger()` to run `ServerPerformInteraction()`(line 350 in `RequestInteractMessage.cs` atm). When using the RMB, `ServerPerformInteraction()` is called directly, but with the same checks(`ServerCheckInteract()` and `TryStartServer()`)

I also noticed a new bug that may be somehow related to this bug: #6306 
But removing the animation doesn't solve this bug

**Comment by ThatDan123** [comment]
Might be fixed by #6538, will leave open though until staging has been updated to test this

**Comment by jamessimo** [comment]
Still not fixed, also discovered the bell only disappears for the client, other people on the server can still see it and interact with it.
