### ISSUE TITLE
Stuff that needs to be fixed with addressables

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5669]
sounds yeah kind of obvious (like all of them, if it is a sound manager play string you have to convert it to a addressable sound reference )
lobby Clown in background needs music source
disposal bin RechargeSFX

 GeneratorRun in Generator

Microwave Microwavesound

All-In-One Grinder

music in lobby menu, need a system for that

BVOld_StillBeatingHeart

set up a build process for pointing the catalogues towards the CDN for the official Builds
and a way for catalogues to be updated on the CDN

**Comment by corp-0** [comment]
I feel like this issue is missing information. I don't really get what stuff is needed to be fixed with addressables by reading the description

**Comment by PerfectTangent** [comment]
closing in favour of #5807
