### ISSUE TITLE
You should be able to turn meatwheat into meatwheat clumps.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5672]
### Description
In /tg/ you can turn meatwheat into meatwheat clumps (identical to raw meat slabs) by using them in-hand with the Z key. Meatwheat clumps can be turned into steaks.

Turning meatwheat into clumps creates action messages and also plays a sound. The sound is the same one used for blob attacks.
Third Person Message: [User] crushes the [meatwheat] into meat.
First Person: You crush the [meatwheat] into something that resembles meat.

**Comment by PerfectTangent** [comment]
what about using the food processor? That gives it one more thing it can do. It feels appropriate and could be implemented now.

**Comment by ThatDan123** [comment]
Can make it into a crafting recipe now that #7024 is in
