### ISSUE TITLE
You can't hear footsteps on non-station matrices.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5676]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Title. You can't hear footsteps that happen on non-station matrices for some reason. If someone walks around on a shuttle or asteroid, you won't be able to hear their footsteps.

### Steps to reproduce
1. Walk on the main station, listen to your footsteps.
2. Walk on a shuttle, such as the arrivals one. Hear no footsteps.

**Comment by corp-0** [comment]
@Bod9001 does your reimplementation fix this?

**Comment by corp-0** [comment]
Findings regarding this issue:
``FootStepsSounds.cs:67``

This code is returning me station matrix even tho I'm walking on arrivals matrix:
```cs
var matrix = MatrixManager.AtPoint(worldPos.NormalizeToInt(), false);
```

The AtPoint loop, you can see here
```cs
public static MatrixInfo AtPoint(Vector3Int worldPos, bool isServer)
{
    for (var i = Instance.ActiveMatrices.Count - 1; i >= 0; i--)
    {
        MatrixInfo mat = Instance.ActiveMatrices[i];
        if (mat.Matrix == Instance.spaceMatrix) continue;
        if (mat.Matrix.IsEmptyAt(WorldToLocalInt(worldPos, mat), isServer) == false)
        {
            return mat;
        }
    }

    return Instance.ActiveMatrices[Instance.spaceMatrix.Id];
}
```

Is returning the station matrix after looping all active matrixes and determining they are all empty at the coords I'm walking at.

![unknown](https://user-images.githubusercontent.com/43683714/106118002-6115a680-6132-11eb-8431-a2267671b522.png)

![unknown](https://user-images.githubusercontent.com/43683714/106118048-6f63c280-6132-11eb-862c-df562cd73a1d.png)

This could also be related to gases not being visible in non-station matrixes.
