### ISSUE TITLE
Sizes of items should be "Medium" by default.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5677]
### Environment
- Game Version: 5608
- OS Version: 

### Detailed description of bug
Title. Items by default should be "Medium" sized, as in /tg/. Right now, items are all "Tiny" by default. This means that items that really shouldn't fit in cardboard boxes and also pockets (many guns, other items), do.

**Comment by corp-0** [comment]
this is very easy to do. Just change the size default value on ItemAttributesV2 tho all the items that didn't manually change their value will be overwritten to medium.
