### ISSUE TITLE
Welding closed old airlocks shut also (trys to) opens them.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5687]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Title. If you use a welder to weld an airlock shut (by being on harm intent) then the airlock will open when you use the welder. The welder will still weld the airlock shut, but the airlock opening when you try to weld it closed is a problem because again, you want it to stay closed.

### Steps to reproduce

1. With a lit welding tool, click on an airlock on harm intent.
2. See the airlock open while you start welding it shut.

**Comment by corp-0** [comment]
tried this on new doors?

**Comment by PetMudstone** [comment]
Addendum: Airlocks will only open when you weld them if your access allows it. Otherwise, they will beep and play the denied animation.
Also, this only applies to old airlocks, not the new ones. However, the new one are yet to replace the old ones.

**Comment by corp-0** [comment]
But I think the issue doesn’t exist on new doors which means putting effort on fixing old doors isn’t the best. Better put that effort into getting new doors production ready.

**Comment by Fogapod** [comment]
This affects all doors, not just airlocks

**Comment by jamessimo** [comment]
How does one test the type of door it is?  Had the same issue on fall station

**Comment by PerfectTangent** [comment]
well, currently, almost all scenes use old doors. The only scene that uses new doors is the Ancient Station scene, iirc.

**Comment by PerfectTangent** [comment]
In order for new doors to be put in place, we have to finish #5815, which is a bounty, if anyone is interested. @corp-0 was working on it, but he's dropped it so it's free to take.

**Comment by jamessimo** [comment]
Tested V2 Doors on UnReal Station and the problem does not happen there https://github.com/unitystation/unitystation/pull/6556

Can confirm this is an old doors issue and maps need to be updated

**Comment by PerfectTangent** [comment]
I'm updating doors to the V2 variants across all maps right now.

**Comment by jamessimo** [comment]
Is this still an issue?

**Comment by pyrosshade** [comment]
This will need to be closed, old doors must die.

**Comment by jamessimo** [comment]
Do we have a larger issue that is tracking the progress of the door converts?

**Comment by PerfectTangent** [comment]
> Do we have a larger issue that is tracking the progress of the door converts?

We do. #6554

**Comment by PetMudstone** [comment]
Closing, since old doors ought to be history soon.
