### ISSUE TITLE
Anything in the mask slot hides your identity even when they really shouldn't

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5688]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Anything that is worn in the mask slot hides your identity and makes you appear as Unknown. This ranges from gas masks to breath masks and _cigarettes_. These items don't have anything special about them other than fitting in the mask slot. This could be fixed if there was a variable that made masks hide identities when equipped. Gas masks could be set to hide identities while other items like breath masks and cigarettes could be set not to. This variable should also work with hats, since some of them (like hardsuit helmets) should logically hide identities but don't right now.

EDIT: Looks like PlayerScript.cs is responsible for showing people as unknown.

### Steps to reproduce

1. Without a mask on, put your cursor over your character. There will be a tooltip in the bottom left telling you your character's name.
2. Put on a cigarette, put your cursor over your character. There will be a tooltip in the bottom left telling you that your character is now "Unknown".

**Comment by NoooneyDude** [comment]
Fixed by #5774.
