### ISSUE TITLE
It is possible to shoot accidentally yourself if you click too close to yourself.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5692]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
If you click too close to yourself with a gun, you will shoot yourself despite not clicking directly on your character. This is bad because well, you shoot yourself without meaning to. The range in which this happens appears to be within half a tile from your character in the cardinal directions (north, east, south, west), and a small area in the intercardinal directions (northwest, northeast, southeast, southwest) that I'm not sure how to describe. See below for a visualization.
Area in purple below makes you shoot yourself if you click in it.
![selfshoot](https://cdn.discordapp.com/attachments/767514702812151828/783407997203775508/selfshootrange_visualization.png)

### Steps to reproduce

1. Click in the area around your character, as visualized and described above, while holding a fire-able gun.
2. Hit yourself with said gun when you fire it.

**Comment by Cboyjet4** [comment]
Possibly related to my issue. https://github.com/unitystation/unitystation/issues/5467

**Comment by PetMudstone** [comment]
Lessened by #5707. Octagon of doom is now smaller and only covers the tile the player is on. Still present, however.

**Comment by corp-0** [comment]
is the current state acceptable enough to close this issue or should we keep working on it until the actual sprite boundaries are needed to shoot yourself?
