### ISSUE TITLE
Addressable Sound Conversion B: 85

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5702]
so, most of the systems still use the old sound method , play(string name)  vs play(addressable audio source) 

convert over all the sounds to the new addressable ones,
upgrade footstep code to use it

 in sound manager  any play method that takes a sound are the old ones
so, any functions that use the string method gets converted over to using the same name with AddressableAudioSource
//jester
comments need to be done as well, there is still a few stuff that uses direct audio sources , written up in issue #5669

there is SingletonSOSounds.Instance for sounds that would be annoying to set in a million prefabs or a static instance

**Comment by Bod9001** [comment]
Borzoi is doing this

**Comment by Emma3DSS** [comment]
Assign me

**Comment by corp-0** [comment]
are you Borzoi? @Emma3DSS

**Comment by Emma3DSS** [comment]
yes

**Comment by PerfectTangent** [comment]
issue has been mostly completed and bounty has been paid.
