### ISSUE TITLE
Stun baton should need power cells in order to stun people.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5720]
### Description
In /tg/, stun batons start with high-capacity power cells inside of them. Every time you hit someone with a turned-on stun baton, you use up 1000 watts from the power cell. High-capacity power cells come with 10,000 watts, so it takes ten hits with a turned-on baton to completely deplete the cell by default. Obviously, if a baton runs out of charge for its battery it should automatically turn off.

Since batons have depletable charges, you can put batons with cells inside weapon rechargers to recharge said cells similar to energy guns. 

Additionally, you can use a screwdriver on a stun baton to remove the power cell inside. This changes the stun baton's sprite and lets you put a new power cell inside. You can put cells with higher capacities to give stun batons more charges. Note: if a cell's capacity is less than the amount of charge that would be removed by a baton upon stunning someone, the cell cannot be inserted into a baton.

Finally, examining a stun baton tells you it the charge remaining in the cell in percentage form, similar to energy guns.

**Comment by Pottingmix** [comment]
Can I please be assigned this one. Thanks
