### ISSUE TITLE
Fugitives show up in the stats tab and security records console when they shouldn't.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5724]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Right now, fugitives (labeled as prisoners) show up in the stats tab in the top right and also the crew database within the security records console. This is bad because it tells the crew that there are fugitives around and also who they are, exactly.

### Steps to reproduce

1. Check stats tab or security records console.
2. Find fugitives (labeled as prisoners) in them.

**Comment by DTraitor** [comment]
Wizards also show up

**Comment by NoooneyDude** [comment]
I don't think the fugitives, wizards should show up on security records as of #5380.

As for the player list in the stats tab, I think the idea is to retire that display in favour of the in-game crew manifest lists and the OOC player username list.
