### ISSUE TITLE
Uncuffing someone while on a server makes you unable to pick up the handcuffs that get dropped.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5726]
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
For some reason when you uncuff someone on a server (such as of this writing, Potato Station), when the handcuffs that were on the cuffed person are removed and dropped on the floor, they cannot be picked up. They can be pulled, but they cannot be picked up. This is bad because you can't reuse handcuffs.

### Steps to reproduce
1. Use handcuffs on someone while on a server.
2. Uncuff them.
3. Click on the handcuffs that have been dropped, fail to pick them up.

**Comment by DTraitor** [comment]
Also it happens to all items you touched before death including clothes. If someone put it in your hands and you will put it bug fixes

**Comment by Fogapod** [comment]
Usually other people can pick up these cuffs.

**Comment by JesterX666** [comment]
Also : Handcuffs don't seem to be spawnable by the Admin panel.  You chose handcuffs in the admin spawn and click on the ground to drop them -> Nope... nothing.

**Comment by ThatDan123** [comment]
Fixed by #6538, reopen again if it wasnt
