### ISSUE TITLE
Putting items on the table doesn't work

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#573]
# Preliminary information

## Category
BUG

## BUG: Version
latest Develop

# Report
## Current Behavior
After you picked up item from the table you can't put it back

## Expected/Wanted/Requested Behavior
Clicking on the table with an item should put items on that table

## Steps to Reproduce
1. Walk to the table with something on it
2. Pick up an item from the table
3. Try putting it back on the table by clicking on it

**Comment by krille90** [comment]
rather put a public bool variable "HasCollider" on the connectedtile to check if it should have a collider or not
