### ISSUE TITLE
things like bottles should break when thrown

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5744]
### Description

This is a very simple request. When a fragile item, such as an egg or a bottle is thrown, they should shatter/break, leaving behind broken parts, such as glass shards. It would be useful if this was added to the throwing component and also it should be configurable to spawn whatever broken item that is needed.

**Comment by Emma3DSS** [comment]
Ah shit here  we go again

**Comment by Emma3DSS** [comment]
Break when thrown? or break when thrown and it hits another object? because I think the latter would be the best for UnityStation's throwing.

**Comment by PerfectTangent** [comment]
maybe check what /tg/ does, but go with whatever you feel.
