### ISSUE TITLE
Floor Hazards - Watch your step!

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5754]
### Description

- [x] Glass shards, when walked on should deal damage to peoples' feet if they are not protected by shoes. 
- [x] Mouse traps should be armable and placeable to deal with cable-chewing mice or unobservant crewmembers
- [x] armed mouse traps when placed inside a container should snap at anyone who opens the bag _one at a time,_ unless the person opens the bag on disarm intent.
- [x] igniters, grenades, and remote signallers should be attacheable to mouse traps, and should trigger when the mouse trap is triggered.

**Comment by craftxbox** [comment]
beep

**Comment by corp-0** [comment]
first part should be easy to do using this: https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/Objects/Enterable.cs

**Comment by corp-0** [comment]
@craftxbox any progress on this one?

**Comment by craftxbox** [comment]
not atm, been busy around christmas

**Comment by MaxIsJoe** [comment]
>  armed mouse traps when placed inside a container should snap at anyone who opens the bag one at a time, unless the person opens the bag on disarm intent.

this is already in btw, though i accidently deleted the disarm intent logic.
will re-add it in the next PR when i tackle attaching things to mouse traps
