### ISSUE TITLE
Cuffing and buckling someone else into a chair often traps them there permanently

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5757]
### Environment
- Game Version: 4608

### description of bug

when a person is cuffed and buckled into a chair, they are often trapped there and cannot escape without help from another player. The resist key does nothing. It won't even say that the player starts to break out of their cuffs. The unbuckle button also is unclickable.

### Steps to reproduce

1. cuff another player
2. buckle that player into a chair
3. that player's resist key and unbuckle action button usually will not the majority of the time

**Comment by Lizurt** [comment]
I'll try to fix it
