### ISSUE TITLE
Buttons and Light Switches do Not Function when Clicked

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5781]
### Environment
- Game Version: Staging 20122700
- Joined as Client to Staging Server
- OS Version: Windows 10

### Detailed description of bug

Buttons and Light Switches do not trigger what they are linked to when Clicked on.

### Steps to reproduce

1. Connect Light Switch to Powered Light Tube using a Multitool
2. Click on Light Switch
3. Notice that the LightSwitch sprite state doesn't update and that the Light Tube is still on

### Note:
* When Buttons that are Mounted on Windows are Clicked, the "\<Player\> knocks on \<window\>" message is triggered.

**Comment by jackpotttt** [comment]
I haven't been able to reproduce this

**Comment by PerfectTangent** [comment]
I have experienced an issue with requiring many clicks to get buttons and switches to work.

**Comment by PerfectTangent** [comment]
this has been fixed to the best of my knowledge, but I can't find the PR that fixed it. I tested and couldn't find any issues.
