### ISSUE TITLE
Drink animations don't work

### ISSUE THREAD

**Issue by had3z** [unitystation/unitystation#5788]
step 1: create a Wizz Fizz | 1 Triple Sec , 1 Soda Water , 1 Champagne
step 2: observe the drink. notice it does not have any animation, even if the file in the textures folder is a spritesheet:
https://unitystation.github.io/unitystation-wiki/assets/images/items/drinks/drinks_wizz_fizz.png

correct behaviour: image should animate

**Comment by NoooneyDude** [comment]
Looks like `MorphableReagentContainer` and `MorphableReagentContainerData` need to be converted to use our sprite SOs instead of Unity `Sprite` object. See #4704.
