### ISSUE TITLE
Make new UI playable: tweak action feedback timming

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#5795]
Currently the action feedback is hard to read because it floats away and vanishes way too fast.

To solve this issue, we should make it so the timming depends on the amount of characters the action text has. It should also stay stationary for a while and in case the action is repeated, refresh the timming it stays still before vanishing away along with adding the x2, x3, x4, ect.

To ensure the text is legible, we should also broadcast the action text to chat log like it always did and for consistency, make all action text follow the transform of the performer, for everyone.

**Comment by NoooneyDude** [comment]
Related to issue #5643.

**Comment by Aranclanos** [comment]
on it

**Comment by corp-0** [comment]
you sure you want to fight with UI again?
