### ISSUE TITLE
Infinite vendomat refill

### ISSUE THREAD

**Issue by had3z** [unitystation/unitystation#5801]
Step 1:

1) Go to a vending machine, on fallstation.
2) buy whatever
2) Use the screwdriver on the machine twice, once to unscrew and once to screw it back
3) Notice the vending machine is fully stocked.

*note: on some other stations (square) some vending machines cannot be dissasembled

correct behaviour: consumed items items should be stored in the canister

**Comment by wraith-54321** [comment]
I am not sure this has ever worked, I might be wrong
