### ISSUE TITLE
Addressables Sound Conversion - The Final Lap

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5807]
this issue covers the remaining work to be done left over from #5702. A handful of scripts must be edited to get sounds converted and working in the development build again

these are the remaining scripts that must be addressed as far as we are aware:

- [x]  PlayerScript.cs
- [x]  Antagonist.cs
- [x]  AntagManager.cs
- [x]  AntagBannerMessage.cs
- [x]  SoundAmbientManager.cs
- [x]  SpellBook.cs
- [x]  Jukebox.cs
- [ ]  Microwave.cs (unchecked) - should be _random_ punch sound on both closing and opening
- [ ]  Anything still using the Audio Source component
- [ ]  Anything that Jester has commented in
- [ ]  Anything with the "RRTL" comment in its code (from Bod)
- [x] PDA sound effects
- [x] lobby music player
- [x] Disposal Bin recharge sound
- [x] Reimplement footstep sounds

others that still may need to be looked at -BVOld_StillBeatingHeart, All-in-one Grinder, lobby clown honk

- [ ] set up a build process for pointing the catalogues towards the CDN for the official Builds
and a way for catalogues to be updated on the CDN

**Comment by wraith-54321** [comment]
nice

**Comment by corp-0** [comment]
would be handy to have the list of scripts here.

**Comment by PerfectTangent** [comment]
PDA sounds were updated with #6078

**Comment by corp-0** [comment]
only last task missing but that one isn't trivial and should have its own issue. Closing.
