### ISSUE TITLE
Let admins examine and interact with player inventories while aghosting

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5812]
### Description

After heavy discussion, we've determined that the most needed feature for admin tools is the ability to examine the inventories of players and interact with their inventories remotely.

admins need to be able to: 

- [x] **see what a player has in their inventory, while aghosting** including seeing what clothing they have equipped and seeing inside boxes, backpacks, and other containers they have on their person.
- [x] **examine** any items in players' inventories
- [x] **smash** any items in players' inventories
- [x] **take** items from player inventories as an aghost (aghosts should get some kind of storage, perhaps hands and pockets)

**Comment by PerfectTangent** [comment]
Supposed to be satisfied with #5879. Will test when it's available on staging and then close this issue.

**Comment by Aranclanos** [comment]
I'd like feedback for adjustements before closing it
