### ISSUE TITLE
Access Rework B:80

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5815]
this is a bounty for refactoring the way we do ID access in the game.

### Access Rework:

- [x] Update the access enum to the latest TG definitions.

- [x] Make access work based on a list of accesses instead of a single access to better reflect how it works in byond.

- [x] Access check should have two modes: ANY and ALL. For any, it approves your access request if your ID has any of the defined accesses on that door. For all, it will only approve your request if you have all of the defined accesses.

- [ ] Update HOP console to better represent these changes and show categorised list of accesses (Like the areas in the original console UI. Also make sure that #5664 is included)

- [x] The HOP console should also allow custom job names

**Comment by corp-0** [comment]
First task says update  but to ensure support of legacy access and don't break all maps in one PR, we should probably do all the new access code work in parallel to legacy by not overriding anything.

**Comment by ThatDan123** [comment]
If possible making a tool to move the access requirements from the old system to the new system would be great as having to set the access again on all the objects (eg doors) on all the maps would be very painful

**Comment by PerfectTangent** [comment]
@corp-0 based on the last time I asked you about this bounty, I am going to unassign you. Thanks for getting it as far as you did.

**Comment by corp-0** [comment]
Convertion progress:
- [x] IDLockedPins.cs
- [ ] MobAgent.cs
- [ ] MobFlee.cs
- [ ] MobPathFinder.cs
- [x] Vendor.cs
- [ ] ClosetControl.cs
- [x] DoorController.cs (replaced by Doors V2)
- [x] Occupation.cs
- [x] Cremator.cs
- [x] Emitter.cs
- [ ] OreRedemptionMachine.cs
- [ ] DoorSwitch.cs (Door switches use door v1 only, can't updgrade)
- [ ] GeneralSwitch.cs
- [x] AccessRestrictions.cs (replaced by ClearanceCheckable.cs)
- [ ] IDCard.cs
- [x] PDALogic.cs
- [ ] SecurityRecordsConsole.cs
- [ ] CargoConsole.cs
- [ ] CommsConsole.cs
- [x] AccessType.cs (replaced by Clearance.cs)
- [ ] ExaminablePlayer.cs
- [ ] GUI_PDAMainMenu.cs
- [ ] GUI_Comms.cs
- [ ] GUI_IDConsole.cs
- [ ] GUI_IDConsoleEntry.cs
- [ ] IdConsole.cs
- [ ] GUI_SecurityRecords.cs

**Comment by corp-0** [comment]
I'm auto-assingning this again but I have removed the bounty so it doesn't seems like there are ulterior motives.

**Comment by PerfectTangent** [comment]
Reinstating the bounty on this because there isn't really any reason why Gilles should be exempt from pursuing bounties. The whole point of separating the role of project head and business manager was to eliminate any conflict of interest. I am doing this without consulting Gilles because I know he will tell me to save the money. Gilles, if you don't want the money, you can just donate the bounty back to the ledger.

**Comment by vlandemart** [comment]
Currently working on custom job names
![image](https://user-images.githubusercontent.com/19672958/151011474-44b356f3-f7c5-45d8-9ef5-d11708b63ac5.png)

**Comment by vlandemart** [comment]
Sorry, need some clarification, what exactly is meant in point 4? Console already has categories for access

![image](https://user-images.githubusercontent.com/19672958/151539607-d33896e3-3569-46fa-86b9-6e66700b590d.png)
with original reference being this:
![image](https://user-images.githubusercontent.com/19672958/151539672-60eeea36-6581-484e-8e3e-6cc78f44f88c.png)

**Comment by AtnerNT** [comment]
Feel like this should be closed? Like pointed out above we already sort the console by categories. feel like the 4th box should be classified or this issue marked as closed.
