### ISSUE TITLE
Improved Antagonist Managing tools for Admins B: 150

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5816]
Currently, Admins do not have the ability to modify or manage antagonists other than giving people roles or forming a deathsquad. In order to better create admin run events and improve the options available, A new antagonist management tool is needed.

### What is Required:

a future-proofed, flexible system would allow an admin to:

- [ ] offer new ghost role listings for any antagonist and configure how many slots there are for new ghost role listings as well as  some role specific listings (such as whether ERTs have special ops access or not)
- [ ] change how many objectives any antagonist, ghost role, or the station has (if I want to give 8 objectives to a fugitive I should be able to)
- [ ] add custom objectives
- [ ] the ability to see the objectives of any antagonist and track progress (checkboxing custom objectives once admins decide they are completed)
- [ ] team-oriented objective tracking (members of a team measure success of certain objectives together and should be listed together in the end of round result) Here are some examples from ss13;

![Screenshot_2020-11-26_093547](https://user-images.githubusercontent.com/68730437/103586111-658fcc00-4eb2-11eb-9f29-a8b83e0e337a.png)
![Screenshot_2020-11-26_093205](https://user-images.githubusercontent.com/68730437/103586448-1b5b1a80-4eb3-11eb-876f-4dcc0b73a445.png)

**Comment by Pockets-byte** [comment]
It would be nice to include the ability to make and toggle custom spawnpoints, and the ability to make your own roles with a custom loadout. 
also control over what people can spawn as would be really nice

**Comment by PerfectTangent** [comment]
starting with this bounty, I'm going down the list of bounties, including assigned bounties, and raising bounty money by 25ish dollars each. It's like 15 bounties, so I thought I'd just say it once here and save time and comment space.

**Comment by Pockets-byte** [comment]
![TraitorPanel](https://user-images.githubusercontent.com/55299415/189802155-c17fcb88-cd39-49aa-81d8-81ba0e865f22.png)

**Comment by SerheyKr** [comment]
Gonna try that one
