### ISSUE TITLE
Airlock Construction and Department Access Remotes Bounty B:120

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5819]
- [x] Airlocks should be _constructable_ and _deconstructable._ The process is quite similar to building machines with machine frames, only requiring an Airlock Assembly instead, and should require very little new code. 

However, there are some extra particularities with Airlocks, such as _naming the Airlock with a pen_ and _painting the airlock with a spray painter._ 

- [x] Airlocks also need to have their access be configurable using Access Remotes. Each department head has an Access Remote that they can use to add or take away access requirements to doors in their department, apply emergency access (removing access restrictions), as well as bolt or unbolt the doors. They _cannot_ electrify doors.

construction recipe for airlocks:
![Screenshot 2021-01-04 200957](https://user-images.githubusercontent.com/68730437/103595965-c7f4c680-4eca-11eb-898c-1c9a7b8e226f.png)

access remotes .dm from /tg/
https://github.com/tgstation/tgstation/blob/f5bd6a381d18765624b81b4aca7fa4126b9dc2ca/code/game/objects/items/control_wand.dm

**Comment by PerfectTangent** [comment]
this first requires #5815 to be merged, but it is being promoted to a bounty, amount TBD.

**Comment by PerfectTangent** [comment]
the parts of #5815 relevant to doors has been completed and merged, so there is nothing holding up this bounty from being completed any longer.

**Comment by Ahion** [comment]
Assign me. I will try to do it.

**Comment by Ahion** [comment]
I'm very sorry, but I won't be able to continue working on this task. Please unassign me so that another person can continue the work. Here it remains to do only remote airlock control. Hope I don't let the community down too much

**Comment by NoooneyDude** [comment]
's all good man, thanks for letting us know.

**Comment by AtnerNT** [comment]
Should be closed by #9035?

**Comment by PerfectTangent** [comment]
@Ahion Are you in the discord? What's your username?

**Comment by Ahion** [comment]
> @Ahion Are you in the discord? What's your username?

Yes, I'm in discord. Ahio#4668

**Comment by PerfectTangent** [comment]
Marking this bounty complete. Bounty paid.
