### ISSUE TITLE
Optional Dark UI switch

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#582]
# Preliminary information

## Category
Feature Request

# Report
## Current Behavior
Currently the right pane and some windows (like chat) are light-grey with white.

## Expected/Wanted/Requested Behavior
It would be nice to have an option for dark UI theme that would turn these windows dark grey with light grey fonts to be easier on the eyes

# Other

## Notes:
Suggestion from the top of my head - inverting HSV's V for these windows and fonts, so that the colours are preserved, but brightness is inverted, maintaining readability

**Comment by DooblyNoobly** [comment]
Started work on this. The beginnings can be found here: #963 

Will do the other elements like the inside windows and fonts soon

**Comment by alex180500** [comment]
This is fixed right now, isn't it?

**Comment by fomalsd** [comment]
No, tab content background isn't themable yet
