### ISSUE TITLE
More craftable foods

### ISSUE THREAD

**Issue by had3z** [unitystation/unitystation#5826]
As of  now, only a small portion of the available food textures are craftable. this wiki page has all the food recipes crawled from the game (updated 06-jan-2021) :
https://unitystation.github.io/unitystation-wiki/#Guides/Service%20guides/Guide-to-Food-and-Cooking/

what remains are a ton of assets with no direct way of crafting them. Soups, Cakes, pizzas, breads, muffins, donuts, slime recipes and more.
[unlinked_foods.txt](https://github.com/unitystation/unitystation/files/5778176/unlinked_foods.txt)

warning: the file is a raw dump of all the pictures in the food folder that can't be crafted. some may not be relevant because they are vendomat items, and some may depend on unimplemented machinery like the frying machine or gibber.

**Comment by wraith-54321** [comment]
I think this is due to a lack of crafting menu

**Comment by ThatDan123** [comment]
Crafting has now been added by #7024, so food recipes can now by added

**Comment by PetMudstone** [comment]
This can be closed now that I added a lot of craftable foods in #7248.
