### ISSUE TITLE
Space Exterior Spawns Added to Maps

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5832]
### Description
A new "Space Exterior" spawnpoint was added in #5825 to trigger spawns on ingame events, for spacecarps, xenos, and the like.
Since it is an entirely new spawnpoint, at least one needs to be added to every map.

* [x] Add "Space Exterior" spawnpoint to Square Station
* [x] Add "Space Exterior" spawnpoint to Fall Station
* [x] Add "Space Exterior" spawnpoint to Outpost Station
* [x] Add "Space Exterior" spawnpoint to Box Station
* [x] Add "Space Exterior" spawnpoint to Pog Station
* [x] Notify Mappers working on new Maps/Stations to add "Space Exterior" spawnpoints to them

**Comment by NoooneyDude** [comment]
Related to #4719.
