### ISSUE TITLE
Eject container into an empty hand if possible

### ISSUE THREAD

**Issue by had3z** [unitystation/unitystation#5846]
QOL: in original ss13 i just noticed when you press eject container from bar, you end up with the glass in the hand. 
in unitystation the container is ejected in the tray of the machine, and you have to click on it to pick it up

pros: this saves 1 click

**Comment by had3z** [comment]
even better: close the reagents window when pressing eject. it's what you want to do anyway

**Comment by corp-0** [comment]
This is a good first issue, don't you want to give it a try yourself? We can help you through it.

**Comment by pyrosshade** [comment]
Will attempt to make this a thing with the ChemMaster. When i get that working i should be able to copy the behavior over to applicable machines.
