### ISSUE TITLE
Cannot deconstruct light fixture

### ISSUE THREAD

**Issue by had3z** [unitystation/unitystation#5858]
build tested: both potato and staging
Steps to reproduce:

1. attach a light fixture to any wall
2. attempt to remove the fixture (this fails, with every tool, on every intent: screwdriver, wrench, crowbar)
3. (optional) put a lightbulb on it, connect it to an apc
4. deconstruct the wall
5. notice the light fixture is stuck in place, without the wall. if you did step 3, the lightbulb would still be on.

![image](https://user-images.githubusercontent.com/8790301/104224290-78277980-544d-11eb-9044-03f71f6ea874.png)

**Comment by MaxIsJoe** [comment]
> notice the light fixture is stuck in place, without the wall. if you did step 3, the lightbulb would still be on.

This is an issue for all objects that aren't tied to the wall tile itself, should be it's own separate issue.
