### ISSUE TITLE
Fix Prefabs in each Map with Sprite set to "None"

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5860]
## Description
Prefabs had their Sprite set to "None" after being placed into a Scene, causing it to have no sprite in-game.
This problem is specific to each map, since overrides affect only the scene the prefab is in and not the base prefab.

### tl;dr 
Right-click and press revert on the child sprite object(s) on the overwritten field. 
Repeat for every object in the scene that has such issue(s).

### Main Stations
* [x] Fix Missing Sprites in Outpost Station
* [x] Fix Missing Sprites in Square Station
* [ ] Fix Missing Sprites in Box Station
* [x] Fix Missing Sprites in Fall Station
* [x] Fix Missing Sprites in Pog Station
* [x] Fix Missing Sprites on Test Station

### Awaysites / Other Scenes
* [ ] Fix Missing Sprites on the Outpost Station Syndicate Base Scene
* [ ] Fix Missing Sprites on Buldinn's Centcomm Scene
* [ ] Fix Missing Sprites on the Wizards Asteroid Scene
* [x] Fix Missing Sprites on the Wizards Shuttle Scene
* [ ] Fix Missing Sprites on LavaLand Scene
* [ ] Fix Missing Sprites on Ancient Temple Awaysite
* [ ] Fix Missing Sprites on Palace Awaysite 

* [x] Fix Missing Sprites on Fall Station Syndicate Base Scene
* [x] Fix Missing Sprites on Fall Station Centcomm Scene 
* [x] Fix Missing Sprites on Pog Station Syndicate Base Scene
* [x] Fix Missing Sprites on Dark Jungle Awaysite
* [x] Fix Missing Sprites on Cavernia Awaysite
* [x] Fix Missing Sprites on Relictica Awaysite
* [x] Fix Missing Sprites on Asteroid Scenes 

#### Pictured: Suit Storage Overlay with Sprite Overidden to be None (Blue Bar on Left means that it was Overridden)
![](https://cdn.discordapp.com/attachments/312454684021620736/798382494600527882/2021-01-12-134626.png)

**Comment by PerfectTangent** [comment]
I'll handle the Wizard Ship and Wizard Asteroid scenes

**Comment by PerfectTangent** [comment]
Some progress made with #5890. Will tackle outpost next.

**Comment by PerfectTangent** [comment]
I am no longer working on Outpost. Someone else is welcome to do it.
