### ISSUE TITLE
Add a Mentor Help button to chat and add a keyboard shortcut

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5865]
Now that we have reverted to the old chatbox while the new one is sorted out, we need a button to open the Mhelp windows for players so they may ask for help from and consult with Mentors. It would also be nice to have a keyboard shortcut to open the window as well; perhaps f2 if that key is not assigned so that it can mirror f1 opening Ahelp.

**Comment by PerfectTangent** [comment]
Finished with #5916

**Comment by corp-0** [comment]
the key binds are missing, I will add them now
