### ISSUE TITLE
Wires should always render over atmos and disposal pipes and atmos pipes should render over disposal pipes.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5866]
### Description
Title. Right now it's weird and inconsistent what order disposal pipes, atmospheric pipes, and electrical wires render over each other in game. Presumably, this is because they all use the same sprite layer. Therefore, wires, atmos pipes, and disposal pipes should all use different sprite layers. The layers should be set up in a way so that electrical wires render over both kinds of pipes and that atmos pipes render over disposal pipes.

**Comment by NoooneyDude** [comment]
Closely related to #4701.

**Comment by PerfectTangent** [comment]
fixed by #9049, no? Closing.
