### ISSUE TITLE
Extend the functionality of Sickness system

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#5905]
### Description
While I was trying to make radiation intoxication a sickness I found myself with a couple problems.

- [x] Make Sickness stages able to have more than one symptom per stage and choose a random symptom to perform. This is somewhat already possible with the custom messages symptom, but it would be cool to simply set one of the standard symptoms which also can have more specific behavior, like vomiting.
- [x] Make sickness  able to freeze progression or disable auto progression. Also make sickness manager able to set the current stage of a sickness to a particular stage.
- [x] Make any mob with health able to get sick, instead of just players. We will need to handle exceptions, but we can see those later.

**Comment by MaxIsJoe** [comment]
> Make any mob with health able to get sick, instead of just players. We will need to handle exceptions, but we can see those later.

This is technically still possible but NPCs do not use HealthV2, when we make MobsV2 a thing with the AI update we should remember to update them to HealthV2 so we can have things like surgery on NPCs and.. well.. sickness.
