### ISSUE TITLE
Add sound to food processors. 

### ISSUE THREAD

**Issue by Lennoxite** [unitystation/unitystation#5906]
Right now food processors are fully functional gameplay wise, but are lacking a sound and the shaking animation that occurs while it's actively processing food.

The basic functions for the animation are already in FoodProcessor.cs, but due to a LeanTween build error it was commented out. 

Right now there is a syncvar that changes to true while the processor is on and false while the processor is off, and is used to play a looping sound, which was taken from Microwave.cs. However in light of the new sound addressable system both food processors and microwaves do not play sounds while active, probably meaning the function needs to be adjusted to fit the new system.

- [x] add shaking animation
- [x] add sound effect

**Comment by corp-0** [comment]
Animation is done, now it is missing the looped sound. AFAIK the generator has a looped sound so whoever wants to implement it can take a look there.

**Comment by PetMudstone** [comment]
There is a sound that plays when using the food processor, just tested it.
