### ISSUE TITLE
Killing someone with a melee weapon breaks the weapon

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#591]
# Preliminary information
When you stab someone who is also hosting to death, the weapon disappears from your hand. It still remains visible on the character sprite.

## Category
Bug

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
You stab so hard, your weapon goes poof.

## Expected/Wanted/Requested Behavior
You should not be able to make your weapon go poof just by using it.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. play game as hosting player
2. Get knife/screwdriver
3. Find an unfortunate test subject
4. Stabby stabby
5. Poof

**Comment by DooblyNoobly** [comment]
Found the problemo:
```
var currentSlot = UI.UIManager.Hands.CurrentSlot;
var otherSlot = UI.UIManager.Hands.OtherSlot;
currentSlot.Clear();
otherSlot.Clear ();
```

So basically the server only method is grabbing the servers hand slots to drop the clients item with (the client that died). Which is why the slot clears on the server. Finding a solution...
