### ISSUE TITLE
Make mining satchel auto pick up ore if you walk over them

### ISSUE THREAD

**Issue by RustyEngi** [unitystation/unitystation#5913]
### Description
In many servers of ss13 mining satchels auto pick up ores if you walk over them so that you dont have to click all the ores.
This makes it so that mining is better for the player doing it since he can keep mining and not having to stop all the time after they clear an ore node.

**Comment by PerfectTangent** [comment]
this functionality was satisfied by the ore box, and adding this feature would make ore satchels generally better than ore boxes, so, closing this issue.
