### ISSUE TITLE
mob variants of _SimpleAnimalHostileBase are not Hostile.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5945]
### Detailed description of bug

Either some or perhaps all variants of the _SimpleAnimalHostileBase are not hostile and do not attack players. This includes hivebots, giant spiders, and bread monsters.

### Steps to reproduce

1. spawn any of the afformentioned mobs
2. they ignore players completely

**Comment by corp-0** [comment]
fixed by #5966
