### ISSUE TITLE
Lightning is invisible for clients

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#5962]
Lightning is invisible for clients

To test respawn as wizard and try lightning spell, or if singularity PR merged try setting up field generators, no lightning will be shown for clients.

**Comment by NoooneyDude** [comment]
Can you confirm this with wizard's LightningBolt spell prior to Singularity PR? Should be good since #5790.

Actually, it'll be on staging.

**Comment by ThatDan123** [comment]
Strange its fine on staging
