### ISSUE TITLE
candle sprite remains in place when picked up by a player until it is put down somewhere else

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5989]
### Environment
- Game Version: latest staging (build 21021100)

### Detailed description of bug

When the ever burning candle is picked up, it appears both in the player's inventory and stays on the ground where it was until the player places it in a new spot, causing the old one to vanish. This was observed by multiple clients.

**Comment by ThatDan123** [comment]
Seems like its to do with items with animating sprites, and happens with all of them

**Comment by ThatDan123** [comment]
Should be fixed by #6006
