### ISSUE TITLE
There are many random issues with joining servers and loading the game.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5991]
### Detailed description of bug

Players are often either failing to join servers, not loading correctly when they do join, or not spawning correctly once in game (such as spawning with no clothes in space, either due to spawning at 0,0 or because the station and items didn't initialize, it's unclear). Pretty much every new round on Staging has mutliple errors from the start. This is possibly caused by multiple independent bugs.

**Comment by alxmra** [comment]
can relate, for me the game freezes multiple times on each selection menu, but atleast a minute after I'm in game it's butter smooth

**Comment by PerfectTangent** [comment]
partially fixed with #6024

**Comment by corp-0** [comment]
I think we should close this one and make report for the individual bugs we can find.

**Comment by PerfectTangent** [comment]
sure
