### ISSUE TITLE
The Singularity Engine should be mapped into at least 1 map

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5992]
### Description

Now that the Singularity is in game, it should be added as the main power source for at least one Mainstation.

**Comment by Akbadain29** [comment]
I can map it to UnRealStation and replace the nuclear reactor with it. I've still got those weird Matrix mismatches though, but I think it would be a good fit for it.

**Comment by SluggyWuggies** [comment]
Ooh. I could put it into Pog as well.

**Comment by PerfectTangent** [comment]
was completed with #6023
