### ISSUE TITLE
Radial menu:  Clicking on Drag cursor on  equipped items (Belt and Rucksack) doesnt work

### ISSUE THREAD

**Issue by Dropgunner** [unitystation/unitystation#5994]
You cant use the button for dragging the item to your hand

**Comment by corp-0** [comment]
I did not understand this ticket. Can you fill the template please? And elaborate on what should happen and what happens instead.

**Comment by PerfectTangent** [comment]
Without clarification of what exactly the issue covers, I'm going to close it. Can be reopened if it's found to still be relevant.
