### ISSUE TITLE
New Doors Bugs

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6012]
Issue for the bugs with the new doors

- [x] Seems like theres an issue where you cant move through an open door, might not be set to passable when open
- [x] some new doors block line of sight through them.
- [ ] ~~Hacking needs to be re-implemented on the new doors~~

**Comment by NoooneyDude** [comment]
Hacking needs to be re-implemented on the new doors, too.

**Comment by corp-0** [comment]
both of those issues sound like it is not syncing the layer change to clients. When you open a door, it changes from DOOR_CLOSED to DOOR_OPEN which handles passable and sight. It works fine when you're the server, but not for the client.

**Comment by PerfectTangent** [comment]
the bugs were fixed in #6302. Closing this issue and moving the hacking reimplementation to its own issue.
