### ISSUE TITLE
Electrical thread death + FPS drop

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6016]
Staging - Linux

Currently on staging. rounds suffer severe FPS loss. and then multiple threads crash. but always electrical. currently is making the game completely unplayable. this needs to be fixed  

as far as I can tell this just happens when a round is running

**Comment by corp-0** [comment]
> as far as I can tell this just happens when a round is running

Can you try to find what triggers it?

**Comment by Pockets-byte** [comment]
> Can you try to find what triggers it?

I've seen this error spammed a lot 
![Screenshot at 2021-02-13 11-23-12](https://user-images.githubusercontent.com/55299415/107857082-35651280-6dfa-11eb-8edc-7c0f4c6d7461.png)

**Comment by corp-0** [comment]
after the last build you stated this is better, can you confirm here how it has improved?

**Comment by Aranclanos** [comment]
Both were different issues, both fixed
