### ISSUE TITLE
Add food processors to existing maps

### ISSUE THREAD

**Issue by AutumnNova** [unitystation/unitystation#6038]
### Description
A new machine for the chef to use was added by aran called the food processor which, processes foods
Atleast one should be added to the kitchen in each of the main station maps

- [x]  Fall (done in #6037)
- [x] Outpost
- [x] Pog
- [x] Box
- [x] Square
- [x] UnReal

**Comment by PerfectTangent** [comment]
both box and square station got food processors in #5901
