### ISSUE TITLE
You shouldn't be able to use the ID and belt slots without a worn uniform.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6066]
### Description
Title. You already can't use pockets without a uniform, to note.

**Comment by craftxbox** [comment]
Not being able to wear ID makes sense, but, I'm pretty sure you can wear a belt without pants.

**Comment by corp-0** [comment]
> Not being able to wear ID makes sense, but, I'm pretty sure you can wear a belt without pants.

I certainly can
