### ISSUE TITLE
Animations for picking up items, falling and thrown mobs

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6074]
In Byond SS13, there is a little leantween animation when characters fall or get flung by explosions or people, this will make the game feel more SS13.

How it looks like:
Falling
![bandicam 2021-02-18 09-47-59-819](https://user-images.githubusercontent.com/65787528/108583309-da4d8700-72f5-11eb-91e5-ca0cf06857ae.gif)

Getting flung or thrown
![bandicam 2021-02-18 09-48-20-846](https://user-images.githubusercontent.com/65787528/108583311-e0436800-72f5-11eb-8a01-f668439aab65.gif)

Also, there is an animation when picking up items, it is a subtle animation but it will give some feedback of what is happening, plus SS13 feels and it just looks good instead of the item instantly dissapearing.
![bandicam 2021-02-18 09-48-35-490](https://user-images.githubusercontent.com/65787528/108583342-09fc8f00-72f6-11eb-9ebf-7870e122e76f.gif)

**Comment by MrAsbestos** [comment]
Closing since #6214 was merged

thxs Max

**Comment by MaxIsJoe** [comment]
> Closing since #6214 was merged
> 
> thxs Max

Note : 
I only added animations to falling and picking up, and picking up animations is server sided for the time being.

Will add a throwing animation and make the pickup animation appear on all clients later.

**Comment by MrAsbestos** [comment]
Alright, still I am going to leave it closed
