### ISSUE TITLE
Gun sounds appear to be global

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6085]
### Environment
- Game Version: Latest staging build (21022100)

### Detailed description of bug

When testing gunfire, I could hear gunshots from across all of pog station. It appears that gunshots are currently global sound effects.

### Steps to reproduce

1. have one person shoot a gun
2. observe how it can be heard clearly from anywhere

**Comment by MrAsbestos** [comment]
Mudstone was working on this, but he never made a PR.

Apparently guns have a sound range of 90, lol.
