### ISSUE TITLE
Explosions play only the distant explosion sound effect

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6086]
### Environment
- Game Version: latest staging (21022100)

### Detailed description of bug

Explosions (either all or at least some) are currently playing the distant explosion sound files exclusively, no matter how close you are to the detonation.

### Steps to reproduce

1. spawn a grenade
2. let it blow up in you hand or right next to you
3. no traditional explosion sound effect, only the metal creaking and distant boom sfx.

**Comment by MrAsbestos** [comment]
Some other stuff:
Actually they don't make any sound, they just make the metal creaking sfx
https://user-images.githubusercontent.com/65787528/111098135-155f6680-8500-11eb-9e3d-a13962bb3a0e.mp4

Distant explosion sounds seem to be working correctly though:
(can't upload it for some reason)

**Comment by MrAsbestos** [comment]
huh weird, one of my vids won't upload, but yeah, distant explosions do work
