### ISSUE TITLE
Add Player Ping To Player List

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6092]
![image](https://user-images.githubusercontent.com/56727168/108755138-c8aaf000-753e-11eb-9911-3a4bf66c2835.png)

-Add each players ping to the server, to the player list tab.

-Also update and make UI cleaner

**Comment by corp-0** [comment]
where is the ping in the screenshot?

**Comment by corp-0** [comment]
ah its an issue, lol my bad
