### ISSUE TITLE
Windows don't have breaking sounds

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6097]
### Detailed description of bug
When you break a window, it is completely silent

### Steps to reproduce
1.  Find any window
2.  Break it
3.  Notice how it doesn't make any sound

**Comment by ewy1** [comment]
I'm working on a generalized solution for this that should allow breaking sounds for all tiles.

**Comment by MrAsbestos** [comment]
Oooh cool

If I remember well, I partially fixed the window breaking sounds, but there was something weird, window breaking sounds only played when they were unanchored, very weird...

**Comment by NoooneyDude** [comment]
Unanchored windows are gameobjects, while installed ones are tiles. The two types are handled quite differently.

**Comment by NoooneyDude** [comment]
Presumably fixed by #6345.
