### ISSUE TITLE
Remote Signallers straight up aren't having a good time

### ISSUE THREAD

**Issue by AtnerNT** [unitystation/unitystation#6101]
### Environment
- Game Version: 21022300
- OS Version: Windows 10

### Description

Remote Signallers, though being able to be wired and attached to wire panels, aren't able to send signals. (Clicking on the item when in hand, on any intent, has no effect). And as such, in their current state, are completely useless.

### Steps to reproduce

1. Acquire 2 remote signallers (Doesn't matter how)
2.  Wire one of the signallers to a door
3. Try use the second signaller to trigger the first, admire the lack of things happening

### Notes:
This bug seems to be inconsistent, and talking with others it seems that occasionally they do work. However through my testing I wasn't able to reproduce a scenario in which they did.
Although not working, no errors occur upon their use. The only errors accounted for during this testing process was an "Asset is not loaded" error upon cutting wires. Not sure if this is related, but may be a good starting place for anyone planning to work on this.

**Comment by PerfectTangent** [comment]
@MaxIsJoe has this been resolved by #7678 and #7922? In order for it to be closed, remote signallers should be functioning with doors.
