### ISSUE TITLE
Nightvision goggles have a few technical and usability issues

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6123]
### Detailed description of bug

- [x] Night vision goggles can reveal certain objects out of line of sight that shouldn't be seen, including glass tiles and shards of glass. Here's an example;
![nightvision glitches](https://user-images.githubusercontent.com/68730437/109223944-49f5c300-7789-11eb-8e4c-26b6f6686cda.png)

- [x] Night vision goggles also don't actually let the users seen very far, only about 3 tiles from the user in total darkness. They would be a lot more useful if they could provide normal line of sight in darkness. See here;
![nightvisionrange](https://user-images.githubusercontent.com/68730437/109224050-6e519f80-7789-11eb-99db-098dc0d5f30f.png)

**Comment by PerfectTangent** [comment]
It looks like the issues of seeing things out of vision have some correlation with items that are see-through, like glass.

**Comment by MaxIsJoe** [comment]
The second issue is an easy fix. Just update the visibility variable by adding * 2 next to the variables inside the inspector and you'll get a bigger visibility range.

**Comment by ThatDan123** [comment]
This has all been fixed, reopen if not
