### ISSUE TITLE
Footstep sounds always make the same generic tile footstep.

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6131]
### Detailed description of bug
Footsteps always make the same generic footstep sound not matter what material you are stepping on.

### Steps to reproduce

1.  Choose a material to walk on (like wood, grass, plating, etc)
2.  Walk on it
3.  You'll notice that you make the same generic tile footstep sound, no matter what.

**Comment by PerfectTangent** [comment]
This issue is redundant with #5813, so closing it. Your zeal for bug reporting is appreciated, though.
