### ISSUE TITLE
Jukebox is muffled

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6133]
### Detailed description of bug
Self explanatory, songs in the jukebox are muffled.

### Steps to reproduce
1.  Find jukebox
2.  Play any song
3.  Song is muffled

**Comment by Bobtheapple** [comment]
The original code had it set to muffled so I didn't change it.  Its just a setting in its audio parameters in jukebox.cs, pretty easy to switch to master.  I figured the idea was that if you set it to master it would sound too perfect, like its not coming from a jukebox 'in world' and instead is a 'music track' for the game.  Really probably could use its own mixer, and a track change sound as well (that classic kachunk of records moving).

**Comment by MrAsbestos** [comment]
Hmmm, Imma test it out, well, when the food processor fix gets merged.

If it does sound way too weird on master, well I might just close this issue.

**Comment by MrAsbestos** [comment]
Alright tested it out and you are right, it does sound weird without the muffled effect, it doesn't change dynamically when you get behind walls, like you said it sounds like it's not coming from the jukebox, so okay, closing issue.
