### ISSUE TITLE
Control Internals Update NRE

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#6139]
### Environment
- Game Version: 21022501
- OS Version: Windows 10

### Detailed description of bug
![image](https://user-images.githubusercontent.com/23048385/109374751-47b77400-7903-11eb-8bb3-4d46b905b51f.png)
Control internals NRE pictured above can occur when station room becomes breached and you walk into it without any internals on. The error spam can be halted if you die and are recloned, upon entering the atmos effected area it will begin again. Turning on your internals after this error doesn't stop the spam either.

### Steps to reproduce
1.  Cause hull and floor breaches through Meteor Event (Catastrophic) through Admin Panel
2.  Enter breached place without oxygen mask, tank or hardsuit in any slots
3.  Check NREs and receive the Control Internals Update Errors

**Comment by PetMudstone** [comment]
The NRE also occurs whenever you have a gas tank in your external inventory slots and a breathing mask worn on your face. Possibly related to #6069.
