### ISSUE TITLE
War Ops, reinforcements, and Syndicate Uplink tweaks bounty B:90

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6148]
**This is a bounty! This issues calls for a couple additional features to the Nuke Ops game mode. First It should introduce the ability for Nuclear Operative to declare war on the station, which gives a large TC bonus, but makes the presence of the Nuclear Operatives known to the station and forces them to wait for a period of time, which means that the station has time to mount a defense.

This issue also calls for some tweaks and design additions to the Syndicate Uplink we have in game and also to add syndicate operative reinforcements as a purchaseable option in the TC uplink**

### Design Considerations:

when nukies declare war, a message is broadcast to the station that war has been declared. From there, nukies received a trickle of extra TC on a dedicated telecrystal upload/receive station. These Telecrystals (TC) can be distributed across the nukie team to allow them to buy signifcantly more items than they normally can. 

The bonus TC takes a while to be deposited on the on the upload/receive console, giving the station time to prepare for the nukie attack. _Given how Unitystation handles shuttles and shuttle travelling differently than ss13, this is how the extra TC should be gotten from declaring war. The immobility of the upload/receive station forces the nukies to wait at the syndicate base to get their rewards for declaring war_

This issue requires a few changes to the current implementation of the syndicate TC uplink. First, TC must be shareable, so Nukies can divide up, store, trade, and spend TC flexibly. 

Second, Nukies and Traitors need to have their TC stores separated so that Nukies can have access to the much more powerful and devastating equipment that is not appropriate for traitors.

In addition, this issue should also see the addition of the nukie reinforcement teleporter. The reinforcement teleporter is a purchaseable uplink item that when deployed, allows a single ghost to become a new nukie using the ghost role system. _This nukie comes with standard equipment, but no TC of their own and must be supplied it by other generous Nukies._

Lastly, it needs to be decided whether the Nukie Officer should be brought back as a feature or not. The method of declaring war could be handled by the Officer, but it could also just as easily be integrated into the syndicate console or the upload receive station.

### What is expected to fulfill the bounty:

in order to fulfill the bounty this is what is required:

- [x] A method for Nukies to declare war, either on the syndicate operations console or on the upload/receive station
- [x] TC upload/Receive station that allows nukies to deposit and withdraw TC like a money machine. 
- [x] Physical, shareable Telecrystals
- [x] Separated nukie and traitor TC uplinks
- [x] Nukie reinforcement - both the ghost role and their teleporters
- [x] weapon bundles should be added to the nukie TC uplink, as well as any other nukie items that can be added (this should not require any new code, and could be handled by maintainers)
- [x] all new mapping features need to be mapped into the appropriate scenes (should be easy)

**Comment by AutumnNova** [comment]
ill have a jab at this bounty so to speak

**Comment by PerfectTangent** [comment]
Bounty re-evaluated to be 90 USD instead of 75 USD.
