### ISSUE TITLE
Add the random bounty system and make the Cargo Console Emaggable bounty B:140

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6150]
### Description

**This Bounty calls for the addition the random bounty system and emagging to the cargo console as well as allowing admins to generate custom bounties.**

Bounties are a way for Cargo to make additional money by snooping through the station or asking other departments for assistance. Each bounty has a name, description, reward in credits, and a priority marking. High priority bounties multiply the reward, with the default multiplier being 2.

Bounties are split into categories to get a distribution of bounties across different departments.

The bounty console lists all of the available bounties. It can print paper listing every bounty available. Bounties that have been fulfilled can be claimed with the console - money is not added to the cargo account until they are claimed. After 5 bounties are claimed, additional ones are added to the list. Currently, it is not possible to add all bounties that exist in /tg/ because several of them require other system such as science to be developed, but we should add all of them that we can.

When the Cargo console is Emagged, it should allow players to purchase special crates that they can not typically purchase. (asthetically, if you want my 2c, these options should be colored red as opposed to the cargo console's typically yellow appearance.)

Lastly, Admins should have a system that allows them to generate brand new bounties with custom text, item fulfillment requirements, and variable credit payouts.

### what is required to fulfill the bounty:

- [x] add the bounties tab to the Cargo console. (added in #6330)
- [x] add an addition to the event system for randomly drawing bounties from a pool. Admins should be able to disable the generation of new bounties if they so wish, as well.
- [x] create a method for admins to generate custom bounties.
- [x] let the cargo console sell additional items after being Emagged. (added in #8632)

### Notes

Bounty Generation in /tg/:
https://github.com/tgstation/tgstation/blob/fa47976cbedc44cf41751d5a0db5701f69412eaa/code/modules/cargo/bounty.dm
Bounty Console:
https://github.com/tgstation/tgstation/blob/2029163d335356dc5f78ddf04f0750c4fa06c429/code/modules/cargo/bounty_console.dm
List of Bounties:
https://github.com/tgstation/tgstation/tree/2591ce17a6609002109fc8eafa48ae0479fc0b8e/code/modules/cargo/bounties

I guess you could say this is a _bounty bounty...._

**Comment by Aranclanos** [comment]
gonna tackle this one

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/114322156-0a92f400-9af5-11eb-98de-1d9ce545408c.png)

adding these requests to the list of things that should be done

**Comment by corp-0** [comment]
yo btw, this issue is not affected by the freeze since it was claimed before it happened.

**Comment by PerfectTangent** [comment]
@Aranclanos has been unassigned from this bounty as they've been busy with other PRs for a while. This bounty is free to be claimed again.

**Comment by MaxIsJoe** [comment]
I just noticed this while browsing through the list of issues we had but one of these things have been fulfilled by #8557

willing to do this, adding the random bounties is easy as well since i know how to do em.

**Comment by PerfectTangent** [comment]
marking this issue complete.
