### ISSUE TITLE
Changelings Stage 1 Implementation Bounty B:200

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6155]
## Description:

This bounty calls for the first implementation of changelings to the game. Before it can be started, it requires #6152 to be merged.

Changelings are alien predators that take on the appearance of those that they slay and drain the DNA of. They're pretty rad. As one of the most developed antagonists in /tg/, they have a lot of content. This bounty is for only the core gameplay systems and a couple evolution abilities for a first release.

The core gameplay features of changelings in draining DNA from other players to assum their identities. It is done either by a DNA extraction sting, which leaves the victim alive or by absorbing the victim, which leaves the victim a dead husk. Once a Changeling has acquired the DNA of a victim, they can at will transform to any of the last 7 identities they have collected the DNA for.

A secondary game mechanic for changelings is the chemicals management system. Changelings have a resource generically referred to as chemicals, which lets them use a variety of special abilities. Chemicals regenerate at a fairly quick rate after use.

A stock changeling comes with a few standard abilities:

### Reviving Stasis 
the changeling enters a dormant state that looks like death. After a period of time in stasis, the changeling can choose to reactivate, getting a massive on activation healing effect. Changelings do not produce chemicals while in stasis. _Changelings can use this ability even while **dead** if they have enough chemicals left over before they died to revive themselves._ If a changeling dies due to gibbing, husking, or other similar deaths, they cannot revive themselves.

### Regenerate
the changeling instantly regenerates lost limbs and organs.

### Transform
The changeling transforms into any of the DNA identities they have stored.

### Extract DNA
The changeling stings are target to take their DNA. This is a stealthy method of assuming the identities of still living crew members
### Absorb DNA
Absorbing a victim does a few things. First, it gives you the target's DNA. It also refills your chemical storage. It also gives you an opportunity to refund and respec any purchased changeling abilities. Also, when done to another changeling, you get all of their stored DNA. If the target was a syndie or traitor with a syndicate uplink, the changeling also receives their uplink code via absorbing their memories.

A person that has been absorbed by a changeling is turned into husk that cannot be cloned or revived with any rudimentary methods.

The Hive channel feature of changelings is not required in this bounty, as it has not been decided whether we want to include it or not for game balance reasons. If need be, it will be added at a later point.

### Evolved abilities
For a first implementation, only a handful of the changeling's evolved abilities are required; enough to have a total cost of 12 evolution points.

## What is required to fulfill the bounty:

- [x] Add the changeling and changeling gamemode.
- [x] Add player DNA genomes.
- [x] Add all stock changeling abilities listed, including Reviving Stasis, Regenerate, Transform, Extract DNA, and Absorb DNA.
- [x] Add the system for picking and receiving, and respeccing evolved abilities.
- [x] Add at least two evolved abilities.

## Additional Notes:

Some evolved ability recommendations below based on their feasibility of incorporation:

Augmented Eyesight
Biodagrade
Chameleon skin
Adrenaline Sacs
Fleshmend
Lesser Form
Mimic Voice
Arm Blade
Tentacle
chitinous armor
transformation sting
mute sting
blind sting
cryogenic sting

**Comment by wraith-54321** [comment]
The chemicals system would most likely also work for xenos

**Comment by SerheyKr** [comment]
Gonna try that one

**Comment by Bod9001** [comment]
finished
