### ISSUE TITLE
Add A Crafting System And A Method For Learning New Recipes Bounty B:200

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6158]
## Description

This bounty calls for the addition of the crafting system from /tg/, along with a single fundamental change with how crafting recipes are known and learned. Currently we have a temporary crafting system, but it is inadequate to handle the larger more complicated recipes that are quite common in ss13. Here are the specifications;

- The crafting system uses items and reagents, **requirements**, that are either on reachable tiles or in your external inventory slots (pockets, hands). Requirements are used to create other items, called **results**.
  - Reagents are sourced from items that hold them.
- Some requirements are also **parts**. Parts are either put into the result or otherwise alter its behavior. 
  - For example, what kind of bottle (or carton) you use to make a molotov cocktail affects its volume (and safety) and its held reagents are transferred over to the resulting molotov.
  - For another example, whether you use a normal glass shard or plasma glass shard affects the resulting spear's damage and sprite.
- The act of actually crafting is set to a **timer**. The timer is set in seconds and when it finishes, the requirements are used up and the result is produced.
  - The timer should be a float value, as /tg/ timer values are float values.
-  Recipes can need one or more **tools** to perform. Tools are not consumed upon crafting completion.
   - For example, the recipe for a motorized wheelchair needs a welding tool, a screwdriver, and a wrench to perform.
   - Meanwhile the recipe for a securitron only needs welding tool to perform.'
- Recipes can require multiple of one requirement.

(Thanks for saving me work by writing the details up, @PetMudstone)

In addition, to reduce the clutter of the crafting system's recipe menu, and to make several roles feel more unique, including the Cook and Curator, certain recipes must be learned via reading books. This will greatly reduce the clutter of the menu, as the majority of the more niche recipes (such as the huge numbers of different craftable food dishes) will be only automatically known to the Cook. The rest of the crew will have to read cooking books to learn how to make them.

This system of recipe learning should be built off of NoooneyDude's simple books component added in #5426.

The addition of the crafting system is going to require a robust, flexible UI to be created. Organize with the artists in the discord to get the UI assets designed.

## What is needed to fulfill the bounty

- [x] Add the Crafting system functionality and menu
- [x] Add recipe learning to simple books.

## Additional notes

tg wiki resources:
https://tgstation13.org/wiki/Makeshift_weapons
https://tgstation13.org/wiki/Food#Crafting_Recipes

**Comment by Lizurt** [comment]
I'll try to do it. Assign me if necessary

**Comment by PerfectTangent** [comment]
Sounds good. You are assigned. This particular job will require UI work, and so we will need to make a plan for how this system should look. A discussion should be held in the #ui-ux channel in the discord.

**Comment by Lizurt** [comment]
> - Some requirements are also parts. Parts are either put into the result or otherwise alter its behavior.
>   - For example, what kind of bottle (or carton) you use to make a molotov cocktail affects its volume (and safety) and its held reagents are transferred over to the resulting molotov.
>   - For another example, whether you use a normal glass shard or plasma glass shard affects the resulting spear's damage and sprite.

Can this requirement be implemented based on variant inheritance in Unity? 

I mean, for example, there will be 2 recipes for a spear: a "glass" spear and a "plasma" spear. Or for molotov cocktails, there will be a normal molotov cocktail for all bottles, and a small molotov coctail for a small bottle and its variants.

Because I don't see any effective, reliable and easy-to-use implementation. Yes, we can use reflection for fields and a serialized field processing action when crafting a specified recipe, but this is not reliable because, for example, fields can change their name and then a recipe will be broken and the only way to find out about it is to try to craft an item in the game.

@PerfectTangent
