### ISSUE TITLE
No one can survive the nuke.

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6162]
### Detailed description of bug
No matter how far you are from the nuke or station nuke, you will die, everyone will, this makes it impossible for nukies to get greentext, or from saving yourself.

### Steps to reproduce

1.  Start local server
2.  Select Nuclear Emergency game mode
3.  Spawn as nukie
4.  Go to the station
5.  Plant nuke
6.  Get as far as you can from the nuke
7.  You die anyways

**Comment by wraith-54321** [comment]
could just make it so it does not kill anyone like in BYOND as there is no real reason for it to kill everyone, that would be an easy fix
