### ISSUE TITLE
Guns with the "SawnOff" component can't be reloaded.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6166]
### Environment
- Game Version: Unitystation - 4117
- OS Version: Windows 10

### Detailed description of bug
For some reason, you can't reload the following guns using their associated ammo (shotgun shells or 7.62mm cartridges). They all have the "SawnOff" component which may or may not be causing the reloading issue. Notably, they can't be reloaded before or after being sawn off.
- ImprovisedShotgun
- RiotShotgun
- S3HunterShotgun
- MosinNagantM1891

### Steps to reproduce
1. Obtain an S3 Hunter by spawning as a bartender on Outpost and checking your backroom.
2. Unload the S3 Hunter by firing it.
3. Get beanbag shells from the BarDrobe. See that you can't reload your S3 Hunter.

**Comment by corp-0** [comment]
what's the state on this one? I thought it was an easy fix, awknowledged by Autumn

**Comment by PetMudstone** [comment]
No work has been done on this issue yet.

**Comment by AutumnNova** [comment]
pft
totally forgot about this, ill start workin on a fix asap

**Comment by JesterX666** [comment]
According to @the-other-autumn :

the issue is the sawnoff component uses a interaction method that gun.cs uses, so only one will trigger, which in this case is the sawnoff method, preventing all the behaviour within the gun.cs method

**Comment by corp-0** [comment]
components are evaluated from bottom to top, adding a condition to WillInteract in the SawnOff component that is only relevant to that component should suffice, like checking the interaction hand object is not ammo or better yet, checking if the object is the saw.

**Comment by JesterX666** [comment]
> components are evaluated from bottom to top, adding a condition to WillInteract in the SawnOff component that is only relevant to that component should suffice, like checking the interaction hand object is not ammo or better yet, checking if the object is the saw.

The problem is that SawnOff component has a special ServerPerformInteraction that allows to wield it.  And ServerPerformInteraction are not called in cascade bottom to top like WillInteract does.  
I have not yet looked how this work, and why arn't they called in cascade bottom to top like WillInteract does.  Do you know it by hearth?
One easy way to solve it without risking breaking the chains of calls, would be to call "gunComponent.ServerPerformInteraction" inside the SawnOff.ServerPerformInteraction function.

**Comment by corp-0** [comment]
I'm not aware of how the chain of ServerPerformInteraction is evaluated. I would have guessed it does the ServerPerformInteraction of the script that first evaluated true in WillInteract.
