### ISSUE TITLE
Nuke Ops cant use their guns

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6186]
Apparently nuke ops cant use the guns they spawn with.

~To reproduce respawn as nuke ops try to fire guns~

This problem only happens when you spawn as a nuke ops naturally, this can be reproduced by setting the next gamemode as ops then you should spawn in after you ready up for the next round.

**Comment by Semuca** [comment]
I'm working on this bug at the moment

**Comment by ThatDan123** [comment]
Theres a bug currently which means all guns arent working due to this error:

![image](https://user-images.githubusercontent.com/56727168/115689394-f00e1580-a353-11eb-9217-d33794c57546.png)

just comment that line of code out , and add a return true as it is unrelated to this issue. For future reference it is caused by the client not knowing what job it has as that part (the mind class and occupation class) is not sync'd

**Comment by ThatDan123** [comment]
Sorry, also realised that i forgot to update the original post with how to get the bug to appear, it will only happen when you spawn as a nuke ops naturally not if you respawn using the admin respawn. So you'll need to set the gamemode to ops, restart the round, ready up and then you should spawn naturally (if you have ops ticked in the antag preferences), and then the bug should happen.

**Comment by Semuca** [comment]
I can't seem to reproduce the bug at the moment no matter what I do (Spawning naturally, unnaturally, as reinforcements, and testing the handguns and machine guns). I'm also not getting that NullReferenceException error relating to PinBase.cs in the console, and all guns seem to be working for me.

I've checked to make sure I'm using the latest version of unitystation. Could someone else also verify the bug is happening?

**Comment by NoooneyDude** [comment]
It sounds like you're not testing this as a client. You might need to build the game and run two instances.

Edit: oh, this is in relation to 

> Theres a bug currently which means all guns arent working due to this error:
> 
> ![image](https://user-images.githubusercontent.com/56727168/115689394-f00e1580-a353-11eb-9217-d33794c57546.png)
> 
> just comment that line of code out , and add a return true as it is unrelated to this issue. For future reference it is caused by the client not knowing what job it has as that part (the mind class and occupation class) is not sync'd

**Comment by Semuca** [comment]
Aha, that did the trick. Thanks

**Comment by PerfectTangent** [comment]
reopening this issue as it was reported again by Leander in #7532 

> while testing it i tried shooting the syndicate guns on staging as a nukie and nothing happened. This error showed off in the console each time i tried to shoot a syndicate gun.
> 
> [error.txt](https://github.com/unitystation/unitystation/files/7302117/error.txt)
> 
> NOTE: i restarted the round and the first thing i did was respawning myself as a nukie, i immediately tried the guns and they shot without problems, however after i declared war in the war console they broke again somehow with the same error.
