### ISSUE TITLE
Map surgery rooms

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6208]
Add surgery rooms with all the equipment to each map if they dont have them already

- [x] Square
- [x] Fall
- [x] Outpost
- [x] Unreal
- [x] Pog
- [x] Box
- [x] Test

**Comment by PetMudstone** [comment]
List of surgical equipment by the way:
- Cautery
- CircularSaw
- Hemostat
- Retractor
- Scalpel
- SurgicalDrill

**Comment by PerfectTangent** [comment]
progress made with #6216, but more to go.
