### ISSUE TITLE
Add defibrillators to the mainstations

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6232]
### Description

Once PR #6231 is merged, all mainstations will need to have defibrillators mapped into medical rooms and wherever else is appropriate. The current implementation is basic, and doesn't come with the wallmount version, just the standard one.

- [x] Unreal
- [x] Square
- [x] Fall
- [x] Box
- [x] Outpost
- [x] Pog
- [x] Ancient

**Comment by Cboyjet4** [comment]
Check off pog and outpost please.

**Comment by PerfectTangent** [comment]
No need to comment, maintainers will get to it. Referencing the issue in the PR is enough.

**Comment by PerfectTangent** [comment]
finished with #6248 and #6249
