### ISSUE TITLE
Bloody footprints 

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#6234]
Walking over blood in SS13 leaves bloody footsteps over the new few tiles you walk on
Use sprites from TG.
![image](https://user-images.githubusercontent.com/71295203/110968115-01531380-830c-11eb-8e16-f4ce3d3d28ee.png)

**Comment by fomalsd** [comment]
Depends on #2314

**Comment by Pockets-byte** [comment]
this also is part of stains, cleanliness, and fluids

**Comment by eurtod** [comment]
This should be in already, right? Can be closed.

**Comment by corp-0** [comment]
> This should be in already, right? Can be closed.

is it working with blood?

**Comment by AtnerNT** [comment]
This works with blood and can be closed
