### ISSUE TITLE
global sound player missing sounds

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6235]
Staging and release- linux

99% of sounds aren't listed in the global sound player making it virtually useless now
it would also be nice to have a larger selection of sounds for admins to use with events

**Comment by ThatDan123** [comment]
The global sound player hasnt been transferred over to the addressables system as im not sure what the best way is to load a list of sounds from the bundles.

**Comment by corp-0** [comment]
Addressables can be tagged. We should use those tags to find SFX, Music and other categories we can come up with.
