### ISSUE TITLE
Hydroponic tray overlays (lights, plants) are invisible to clients.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6255]
### Environment
- Game Version: 4118
- OS Version: Windows 10

### Detailed description of bug
Title. For some reason the light and plant overlays on hydroponics trays cannot be seen by clients. This means that clients have no idea what the current state of the plant in a hydroponic tray is as no information is provided due to a lack of sprites.
Note: This bug does not appear to exist on build 4117.

### Steps to reproduce
1. Host build 4118 from the installations tab and connect to it as a client using a second instance of Unitystation.
2. Place seeds in hydroponics tray.
3. Notice that no growing sprite appears on the hydroponics tray from the clients perspective while the host is able to see it as intended.
4. Wait for the plant to finish growing and for the green harvest light to appear on the host's end. Notice that neither the plant's fully grown sprite nor the harvest light are visible to the client.

**Comment by Bod9001** [comment]
been fixed in on develop

**Comment by PetMudstone** [comment]
In any particular PR?

**Comment by PetMudstone** [comment]
Can confirm that this bug no longer exists as of build 21032300. Closing for now.
