### ISSUE TITLE
Health Analyser UI

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#6259]
OH GOD the text is pretty hard to read, Improve it with the UI, and have a button to dump text version into chat as memory/print out piece of paper with information on,

fill out moore with desired look

**Comment by PerfectTangent** [comment]
If someone would like to work on implementing this with me, I am building UI assets for the health analyzer.

**Comment by Cboyjet4** [comment]
Please provide an example for what it should look like.
---
![image](https://user-images.githubusercontent.com/71295203/111350201-1a76ff80-863f-11eb-890a-524a3ccb6fff.png)
Damaged
----
![image](https://user-images.githubusercontent.com/71295203/111350695-9d985580-863f-11eb-8f57-0147b6fcc7b4.png)
Crit
----
![image](https://user-images.githubusercontent.com/71295203/111350882-cf112100-863f-11eb-8d2a-1a99c29ea466.png)

I think it's also important to note that the health analyzer should NOT show organ damage, that should be reserved for advanced scanners/body scanners.
-------
images taken from paradise
