### ISSUE TITLE
Combat Dismemberment and Disemboweling B:150

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6270]
## Description:

**This is a health-related bounty.** This bounty calls for the implementation of limb and organ loss due to weapon attacks and explosions.

In ss13, victims of particularly vicious attacks may lose their head, legs or arms. This can result from a few different situations including:

- explosions.
- attacks from very powerful weapons.
- attacks from particular or specialized weapons (the plasma cutter being the most well known one).
- extremely forceful impacts such as players gettting launched by catastrophic decompression or getting too close to the singularity
- airlocks slamming with safeties disengaged.

Rarely, organs can be directly ejected or cut out of a victim's chest in the middle of combat from certain attacks (attacks from the energy sword and the power fist being the most common cases). Organs and limbs can also rarely be completely pulverized and destroyed.

Obviously, any of these things happening to a crew member is generally bad news. If a limb is lost in such a way, it will usually cause serious amount of bleeding. Losing an organ vital to survival is also very bad, especially if it is the heart or brain. Patients missing a head will die in most cases as their body lacks its brain.

**Armor also has an effect on how likely any of the methods of dismemberment or disembowelment above are to happen. Highly protective armor should reduce the risk of such things occurring.**

## What is required to fulfill the bounty:

- [x] Add dismemberment due to explosions, violent weapon attacks, extreme blunt force, and blast doors/airlocks, which can be counteracted by high tier armors.
- [x] Add disemboweling due to explosions, extreme blunt force, and powerful attacks directed at the chest, head, or groin.
- [x] Add pulverization of organs and limbs.

With the new health system in game, the majority of the effects of organ and limb loss have been addressed. However, currently, mobs do not die when they have lost their head or brain. That is an important feature specifically for the topic this bounty covers, and should be included with this.

- [x] Death should occur instantly if a target of an attack is decapitated or loses their brain.

## Suggested implementation

- Add a new field to ItemAttributesV2.cs for whether the attacks of the weapon causes dismembering when used to attack and how likely the weapon is to dismember.
- Change the damage method parameters to send this ``canDismember`` field and also the ``dismemberChance`` of the attack, so different weapons/objects can have a different chances of dismembering.
- After armor reduction, check the damage and compare it to a damage threshold set in the body part. If the reduced damage passed the threshold, roll the dismembering chance.

**Comment by PerfectTangent** [comment]
price reevaluated to 60.00 USD

**Comment by MaxIsJoe** [comment]
I noticed that I was working on this by accident and apparently I'm already half way done with it. I'm claiming this. Yoink.

**Comment by PerfectTangent** [comment]
yeah, alright.

**Comment by PerfectTangent** [comment]
bumping the bounty to 150 USD since we discussed and expanded the scope of the requirements in the health channel.

**Comment by MaxIsJoe** [comment]
> Add pulverization of organs and limbs.

I think I'll work on this along side #6272 as this shares some things that work best with that other bounty.
For now disemboweling and dismemberment should be 100% added in after #6643 gets merged. Surgery, burns, blunt force trauma and a slight new additions to items that heal/damage the player will be added in later PRs (probably there will be 2 of them) that will tackle #6272 and healing for everything I've added so far. After that there will be some smaller PRs that will add in things like door crushing, liver internal damage due to toxins, Infections that can start diseases for rotting corpses and other scenarios that will fully utilize both bounties to showcase what we can do with these new modular systems.

**Comment by MaxIsJoe** [comment]
Disemboweling and pulverization have been added. We can tick these off now.

**Comment by corp-0** [comment]
what's the current situation of this bounty? I see all tasks done but still open

**Comment by MaxIsJoe** [comment]
It's done and I got paid for it.

**Comment by PerfectTangent** [comment]
yeah, it was left open for the rework that was requested, but that's been merged, too. closing.
