### ISSUE TITLE
Fix player sprite and creation issues and allow the character customization window to save multiple characters B:150

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6276]
### Description

**This is a health-related bounty.** This bounty requires a quality assurance pass on the player sprites in the character customization window and in game. Currently on develop, a variety of sprites are not displaying correctly,

known issues include;

- sprites not displaying when they should from certain character facings both in game and in the customization window
- sprites are offset or overlapping other layers in strange ways
- sprites are not coloring correctly (for example, the lizard tail)
- characters are occasionally appearing as disembodied floating skulls
- certain limbs or extra bits (moth antennas) are not appearing removed when they should be after surgical removal
- characters are spawning or respawning with the wrong or default skin color.
- ghost sprites are not visible

The randomize button in the character customizer also currently cannot randomize hair, facial hair, and socks. This needs to be reimplemented.

This bounty also calls for adding the feature to save and load multiple characters in the character customization window, saving all details about them.

## What is needed to fulfill the bounty:

- [x] fix all visual and layering issues with player sprites in the customizer and in game
- [x] reimplement the remaining broken features of the randomize button
- [x] add the ability to save and draw up multiple characters to the character customization window.
- [x] Make ghost sprites visible again

**Comment by MaxIsJoe** [comment]
Since I'm already working on #6271 I'll claim this bounty.
That PR will still be pushed however once it's been reviewed and tested by Gillies, bod or dan.

**Comment by MaxIsJoe** [comment]
Tick one off for this.

Now I'm going to work on ghosts and see why they're not showing up on clients most of the time.
Also if anyone has steps to reproduce this issue please send it to me, I've been killing myself both on local servers and on staging to see what's wrong and I can't replicate this issue.

**Comment by MaxIsJoe** [comment]
The character creator task can be ticked off now

**Comment by PerfectTangent** [comment]
this bounty has proven to be particularly nasty to sort out, and is being raised to 125.00 USD.

**Comment by PerfectTangent** [comment]
After 16 PRs, this bounty is being marked as complete. there are a couple remaining bugs, like the disembodied skull bug, but the vast majority of the problems covered by this bounty have been fixed, assuming #6518 is merged.
