### ISSUE TITLE
[Admin Tools] Players who get smited can't become ghosts

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#6291]
### Environment
- Game Version: Latest (develop/upstream)
- OS Version: Windows 10

### Detailed description of bug

Smite does it's job for killing the player but in the process of doing so it prevents the player from becoming a ghost and observing the game. Forcing them to be stuck in one place.

### Steps to reproduce

1. Be an admin
2. Smite a player from the admin tools -> Player manager
3. Observe how you cannot become a ghost and are now stuck in one place forever.

**Comment by MaxIsJoe** [comment]
This should be added to #6195

**Comment by Charlese2** [comment]
It seems to be gibbing in general that causes you to get stuck.

**Comment by Aranclanos** [comment]
cant reproduce
