### ISSUE TITLE
Medical chemistry DONE/Partially Implemented list

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#6307]
**implemented/partially** 
AmatoxinInBody
Anti-ToxinInbody
BadFoodinBody
BicaridineInBody
CarpotoxinInBody
ClonexadoneInBody
CryoxadoneInBody
KelotaneInBody
PestKillerInBody
Plant-B-GoneInBody
PoloniumInBody
PotassiumIodideInBody
TirizeneInbBody
ToxinInBody
TricordrazineInBody
WeedKillerInBody
Mannitol
Impedrezene

**partially implemented** 
Clonexadone (needs to Only work in cold environments) ( requires a custom inspector for temperature range and increase performance for colder mix)
Pest Killer (increased damage to fly people when added)
Plant-B-Gone (increased damage to pod people)
Potassium Iodide (set to work on the low radiation amounts?)
Cryoxadone (needs to Only work in cold environments)

**Comment by PerfectTangent** [comment]
closing this as it's not really an issue.
