### ISSUE TITLE
White Beard Bug

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6337]
### Environment
- Game Version: 21040800
- OS Version: MacOSX

### Detailed description of bug

Spawning into the game spawns you in a a pale person with a white beard seemingly over your original body, nothing more to it.

![Screen Shot 2021-04-08 at 10 00 54 AM](https://user-images.githubusercontent.com/61613068/114067399-a3094a00-9851-11eb-89c0-0b573cb8dd3b.png)(url)
### Steps to reproduce

Just spawn in, see results.

**Comment by MaxIsJoe** [comment]
Related to #6323 

Characters seem to (for some reason) not only fail to save at some times but also fail to load in as well.

**Comment by MaxIsJoe** [comment]
This has been completely fixed thanks to my PRs.

**Comment by PerfectTangent** [comment]
Which specific PR fixed it and how?

**Comment by MaxIsJoe** [comment]
> Which specific PR fixed it and how?

It's in a number of PRs that I've introduced but the final nail in the coffin that fixed this completely is #6440

**Comment by PerfectTangent** [comment]
Good enough for me. Can be reopened if it proves to still be around. Closing.
