### ISSUE TITLE
Respawn Randomness

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6338]
### Environment
- Game Version: 21040800
- OS Version: MacOSX

### Detailed description of bug

Respawning any player with the "Respawn" button respawns said player as a random job rather than the one they died as.

![Screen Shot 2021-04-08 at 10 05 31 AM](https://user-images.githubusercontent.com/61613068/114068097-5e31e300-9852-11eb-853f-ffd3dd43ddb7.png)

### Steps to reproduce

1. Spawn in.
2. Respawn yourself specifically with the "Respawn" button

**Comment by LastCaptainBonk** [comment]
(For context: I originally spawned in as captain.)

**Comment by LastCaptainBonk** [comment]
I'm assuming that this is intentional, closing issue.

**Comment by PerfectTangent** [comment]
it should be random if you don't specify a job in the drop down. So, yeah, what you are experiencing is probably intentional.

**Comment by corp-0** [comment]
uhm, it could seek for the job the player had though. Easy to do.

**Comment by PerfectTangent** [comment]
well, being able to randomise the job as an admin is a feature that has some utility. The best solution is to probably have a separate option in the drop down for randomization, though.
