### ISSUE TITLE
Health Doll Selection Bug

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6339]
### Environment
- Game Version: 21040800
- OS Version: MacOSX

### Detailed description of bug

Trying to select any other part of the body on the health doll just doesn't work, at all.
![Screen Shot 2021-04-08 at 10 10 11 AM](https://user-images.githubusercontent.com/61613068/114068600-f334dc00-9852-11eb-8739-a32f5fd8111c.png)

### Steps to reproduce

1. Try to select any other part of the health doll than the torso.

**Comment by PerfectTangent** [comment]
Did you get any errors are n the console related to this when it happens?

**Comment by LastCaptainBonk** [comment]
No, but would these NREs that happened at the start of the game help?
![Screen Shot 2021-04-08 at 10 55 16 AM](https://user-images.githubusercontent.com/61613068/114074191-f8952500-9858-11eb-80b2-5743893bafec.png)

**Comment by PerfectTangent** [comment]
Ones that sound like they are related to the health doll would be nice see have here

**Comment by LastCaptainBonk** [comment]
These are the only NREs that I have in-game.

**Comment by DTraitor** [comment]
Probably my bad, I'll take a look tomorrow

**Comment by DTraitor** [comment]
You can still select any part using numpad
