### ISSUE TITLE
Roller Bed Patient Disappearing

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6344]
### Environment
- Game Version: 21040900
- OS Version: MacOSX

### Detailed description of bug
If you take a roller bed with a body strapped on it, the roller bed immediately makes the body on it disappear.

### Steps to reproduce

1. Strap body onto roller bed
2. drag roller bed to your character

**Comment by Semuca** [comment]
I'll give this bug a crack
