### ISSUE TITLE
Invincible Circuit Imprinter

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6348]
### Environment
- Game Version: 21040900
- OS Version: MacOSX

### Detailed description of bug

Circuit Imprinter is invincible to admin destruction tools and even the "Smash" variable simply creates a machine frame behind the circuit imprinter.

![Screen Shot 2021-04-10 at 2 02 22 PM](https://user-images.githubusercontent.com/61613068/114284587-beb55180-9a05-11eb-87fa-9d0be25189ad.png)

### Steps to reproduce
1. Place Circuit Imprinter
2. Attempt to destroy it

**Comment by Semuca** [comment]
Could I try and take on this issue? It'll be my first issue I've done with unitystation and I'd like to do something rather simple.

**Comment by corp-0** [comment]
Sure thing, ask in our discord if you have any questions
