### ISSUE TITLE
Admin Spawn does not work when connected to a server.

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#6349]
### Environment
- Game Version: Develop Branch, April 20, 2021
- OS Version: Windows 10

### Detailed description of bug

The Admin spawn menu is not able to spawn any item when connected to a built server.
However, in the editor, when the server and client is the same, it works just fine.

### Steps to reproduce

1. Build the server
2. Connect to the server either with client or in the editor.
3. Try to spawn an item with the admin spawn menu.

**Comment by ThatDan123** [comment]
I cant seem to reproduce this bug when on the staging server

**Comment by NoooneyDude** [comment]
I didn't experience this on current staging either.

**Comment by corp-0** [comment]
I think it is safe to close this issue. Maintainers, feel free to reopen if you think I did wrong.
