### ISSUE TITLE
PogStation tile bug

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6350]
### Environment
- Game Version: 21041100
- OS Version: MacOSX

### Detailed description of bug

There is a tile on PogStation in the energy ball/singularity engineering area that has a tile on it, but you can't wrench down a rad collector down on it.

![Screen Shot 2021-04-10 at 7 26 04 PM](https://user-images.githubusercontent.com/61613068/114290238-e66ede80-9a32-11eb-81fc-21c454caeed3.png)

### Steps to reproduce

1. Go to the specific energy ball/singularity area in engineering on PogStation
2. Try to wrench down a rad collector on the specified tile

**Comment by Semuca** [comment]
I can do this issue
