### ISSUE TITLE
Random Bleeding

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6355]
### Environment
- Game Version: 210141100
- OS Version: MacOSX

### Detailed description of bug

Sometimes players will just randomly bleed out of nowhere, without any damage being taken.

![Screen Shot 2021-04-11 at 9 26 51 AM](https://user-images.githubusercontent.com/61613068/114312677-59ff0300-9aa8-11eb-9e8a-bbeb21c30a0b.png)

### Steps to reproduce

1. Get into potentially dangerous situations, without getting in harm's way

**Comment by LastCaptainBonk** [comment]
Product may just be a radiation bug

**Comment by MrAsbestos** [comment]
They will also bleed if they are hit by any object, even if it doesn't do any damage

**Comment by Fogapod** [comment]
Might be irrelevant after numerous health reworks and new trauma rework. Never seen this

**Comment by NoooneyDude** [comment]
Good enough for me.
