### ISSUE TITLE
Right arm overlay is broken

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6364]
### Environment
- Game Version: 21041400
- OS Version: MacOSX

### Detailed description of bug

Right arm's overlay overlays everything, even hard suits and gloves

![Screen Shot 2021-04-14 at 10 59 17 AM](https://user-images.githubusercontent.com/61613068/114757403-ac425d00-9d10-11eb-84c0-5a0c5d8805fe.png)

### Steps to reproduce

1. Spawn in
2. Turn right

**Comment by PerfectTangent** [comment]
fixed by #6358
