### ISSUE TITLE
Wires are broken

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6366]
### Environment
- Game Version: 21041400
- OS Version: MacOSX

### Detailed description of bug

Newly created wires cannot be cut properly, and do not have a proper power current
![Screen Shot 2021-04-14 at 1 33 46 PM](https://user-images.githubusercontent.com/61613068/114775498-3812b400-9d26-11eb-9fec-eb180ecd134c.png)

### Steps to reproduce

1. Place wires
2. Attempt to power them

**Comment by NoooneyDude** [comment]
I could get power of wires on staging recently, and wire cutting issue should be fixed.
