### ISSUE TITLE
Xeno corpses cannot be butchered anymore

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6367]
### Environment
- Game Version: 21041400
- OS Version: MacOSX

### Detailed description of bug

Xeno corpses cannot be butchered into Xenos meat (probably because of new variants.)

### Steps to reproduce

1. Kill a xeno
2. Attempt to gib it via kitchen knife

**Comment by DTraitor** [comment]
Did you try to gib on harm intent?

**Comment by LastCaptainBonk** [comment]
yes, as always

**Comment by PetMudstone** [comment]
From what I see, no mobs can be butchered currently in-game. I've checked the prefabs in the inspector and xenomorphs (and most other mobs) are set to be butcherable too. I think this might be related to the bug that prevents you from petting or attacking mobs in melee.

**Comment by PetMudstone** [comment]
This bug still seems to be present from playing on production 4119. I was unable to butcher xenomorphs and space carp using a knife on any intent. Using harm intent only caused me to attack them.

**Comment by MaxIsJoe** [comment]
Xenos apparently can be butchered again as well as all other mobs, so this has been fixed at some point.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/188259048-dd486413-8b72-4a57-910d-7c9841671958.png)

Below is me butchering a xeno and above is me butchering pete

**Comment by NoooneyDude** [comment]
On headless / staging?

**Comment by MaxIsJoe** [comment]
> On headless?

![image](https://user-images.githubusercontent.com/34368774/188259074-12ee3c09-8ce1-48ea-8e27-276aba557432.png)

It shouldn't be an issue on headless because this function is used all around and does not cause only problems; if it did we would have noticed a lot more worse bugs than this.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/188259248-c70ac758-4434-4539-b934-6d86d0f16365.png)

Tested on staging, works as well
