### ISSUE TITLE
broken medical menu B:40

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#6380]
### Environment
- Game Version: 21041501
- OS Version: windows 10, latest

### Detailed description of bug

essentially when i went into the medical menu
![image](https://user-images.githubusercontent.com/78688207/115107982-df315e80-9f65-11eb-90fe-1ffaab363163.png)
and clicked on the top option it didnt close the menu and allow me to remove my arm, it simply opened this empty menu
![image](https://user-images.githubusercontent.com/78688207/115108023-14d64780-9f66-11eb-918a-f2ab2fcc09fc.png)
i tried pressing enter and other buttons but to no avail, i then closed the menu and tried to perform surgery but the original menu popped up again

### Steps to reproduce

1. go into staging
2. attempt to replace your left arm with a robot one using the instructions in the TG wiki

also here are some errors
![image](https://user-images.githubusercontent.com/78688207/115108513-ce361c80-9f68-11eb-8c3a-17eaaa5c7e97.png)

**Comment by PerfectTangent** [comment]
This issue is being promoted to bounty status. Evaluated at 40 USD

**Comment by MaxIsJoe** [comment]
When you're on a operating table, you cannot be clicked on anymore and don't appear in the chat wheel, as if you no longer exist.

Just posting this here so people can be aware about this
![image](https://user-images.githubusercontent.com/34368774/121825903-3c6f3500-ccb5-11eb-9703-606bfb6f4232.png)
