### ISSUE TITLE
FOV on windows freaking out

### ISSUE THREAD

**Issue by LuigiBoi** [unitystation/unitystation#639]
# Preliminary information

## Category
bug

## Bug: Release or Dev?
dev

## BUG: Version
When submitting a bug report, please give us the release version or GITHUB branch used.
develop
# Report
## Current Behavior
_What is the current behavior?_
fov is fucky, walking around will usually cause it to get stuck and walk around inside darkness

Please enter the steps to reproduce the bug or behaviour
1. Just walking around in maint should reproduce it, thats what is happening on my end
2. What happens is that FOV crashes and freezes the FOV shader. 

![image](https://user-images.githubusercontent.com/33106161/33946354-33224618-dfe7-11e7-9441-72b07701203a.png)

## System specs:
Windows 10
i5-8400
GTX 1060 6gb
1TB Toshiba Sata HDD

**Comment by krille90** [comment]
still happening. (In Editor, 2017.2)

![capture](https://user-images.githubusercontent.com/7312905/34275896-776680a0-e69f-11e7-8b33-796ebd33942d.PNG)
![capture1](https://user-images.githubusercontent.com/7312905/34275897-777f82bc-e69f-11e7-992d-2bdaef8e89fd.PNG)

**Comment by Ornias1993** [comment]
@krille90 It's the way FoV always looks when it crashes.
So it would be cleaner to post a new issue, because it now links it to a solution for another FoV related bug.

**Comment by Ornias1993** [comment]
NAZI-Note:
No opening issues, unless it really is related. 
Which this may or may not be, but without reproducibility we cant know anyway.
