### ISSUE TITLE
Eternal Flames and Fire Damage Problems B:50

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6398]
### Description

**This is a stability related bounty, and is immune to the feature freeze.** This bounty calls for fixing an issue with fires breaking and never dissipating. Quite frequently nowadays, fires will break and never end. Fires are also reportedly not doing damage to players when they should, and players are unable to resist out of burning and staying lit on fire forever. The specific causes for the bugs are not known. The issue of players not taking fire damage may be related to fires never ending or it may be a separate bug introduced with the new health content.

This bounty also calls for a small feature. Now that we have crawling in the game, resisting flames should initiate crawling as players are trying to put out the flames by rolling around on the ground.

### What is needed to fulfill the bounty:

- [x] Fix any bugs that are causing fires to never end or that cause them to cease interacting with their environment.
- [x] Fix any bugs with player characters not receiving damage while on fire
- [x] Fix any bugs with players not being able to extinguish themselves with the resist key. Resisting out of fire should also cause players to begin to crawl, as they stop, drop, and roll.

### Steps to reproduce

depiction of an endless fire on square station
![Screenshot_at_2021-04-19_13-00-53](https://user-images.githubusercontent.com/68730437/115423856-2a4cab00-a1cc-11eb-8365-18a95bb9c3cc.png)

**Comment by PerfectTangent** [comment]
Bounty price set at 100.00 USD.

**Comment by Semuca** [comment]
I'll take this bounty up and see how I go

**Comment by PerfectTangent** [comment]
alright, you've been assigned.

**Comment by Semuca** [comment]
I'm going to document this here for other devs and also myself. This error is reproducible, but in specific circumstances.

<img width="960" alt="Screenshot 2021-05-09 200823" src="https://user-images.githubusercontent.com/62051810/117572266-b0417f00-b104-11eb-9c2b-b76ec5055c66.png">
By placing the plasma canister in this specific position on SquareStation and starting a fire, it will consistently cause the fires to become stuck. Some other notes:

- If the canister gets pushed by space wind while the fire occurs, this eternal fire will break.
- If the canister gets pushed by a player after the fire has become eternal, the fire will not break. If it is pushed into an non-flame tile, it will only ignite that tile.
- The fire will hurt you and set you on fire, but it seems like it won't register with the UI on the right-hand side of the screen.
- Strangely enough, this eternal flame doesn't seem to be affected by where the fire is started.

**Comment by corp-0** [comment]
what's the state of this issue? People report the eternal fires are still a thing after https://github.com/unitystation/unitystation/pull/6606

**Comment by Semuca** [comment]
I won't be able to finish up this bounty. Sorry about this, you can unassign me from it.

**Comment by PerfectTangent** [comment]
ah, alright. We understand. Thank you for notifying us. You did complete a portion of it; I think it's fair you get a portion of the bounty.

**Comment by PerfectTangent** [comment]
bounty partially paid out to @Semuca. bounty price reevaluated to 50 USD for the last task left.

This bounty is free to be taken again.

**Comment by PerfectTangent** [comment]
Marking this issue complete with Aranclanos's PRs. If new cases of fire overlays not being removed happen, make a new issue.
