### ISSUE TITLE
Garbage reduction and crash fixes bundle B: special, see details

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6399]
## Description

**This is a stability related bounty, and is immune to the feature freeze.** This bounty bundle calls for reducing gc, improving performance of the game, and finding and killing crash causes.

This is not a traditional bounty. This bounty need not be assigned, and can be done by anyone, though it is still held to the standard bounty guidelines in the [contribution guide.](https://unitystation.github.io/unitystation/CONTRIBUTING/)

Any contributor may claim a reward for doing the following in a PR:

- substantially reducing gc of a system or method that is utilized often in the game.
- improving performance or speed of a system or that is utilized often in the game.
- fixing any bug that could cause either the host or clients to crash.
- fixing any bug that could prevent the game from properly launching, or initializing in a state that renders the game unplayable.

**the reward for fulfilling this bounty is set at 25.00 USD.**

This bounty is meant to encourage collective action. To give as many contributors the opportunity to get the reward as possible, **EACH CONTRIBUTOR MAY CLAIM A REWARD FROM THIS BOUNTY ONLY ONCE.**

There is _225.00 USD_ left for this bounty, providing **9** remaining rewards to be claimed. Each Pull Request will be evaluated on request by @Bod9001 and @corp-0 as to whether the PR qualifies for a reward from this bounty bundle. If you have any questions about what _might_ qualify for a reward, please ask in the #bounties channel in the [unitystation discord.](https://discord.gg/BcGvpmqz)

We are opening this bounty opportunity retroactively to all Pull Requests merged since the feature freeze was put in place (Tuesday, March 23rd). If you would like to claim on a PR that has been merged, you can request an evaluation in a comment under that PR. _If you submit a PR for another bounty we have posted, but it satsifies one of the requirements listed above, you can still claim a reward for this bounty._

**Comment by Aranclanos** [comment]
since it opened 11 days ago I can only try to claim my humble share of the pot with #6405 made a day after

**Comment by Aranclanos** [comment]
I removed a most of the game's gc after the freeze started in these prs: 
#6295 - Thread safe list wrapper with no allocations on iteration
#6340 - Fixes the gigantic GC production of wind
#6346 - Self sufficient vent & scrubbers GC reduction
#6368 - Reagents garbage collection fix part one
#6386 - Fixes the GC generated by Total from ReagentMix
#6405 - Fixes half of bloodpump GC

more to come of course!

**Comment by PerfectTangent** [comment]
@Aranclanos has been approved for his contributions and has gotten 1 of the rewards. 9 rewards remaining.

**Comment by PerfectTangent** [comment]
This bounty will be closed on September 15th due to inactivity. If you want to get a reward for work done, you have 1 month remaining to claim.

**Comment by metalgearsloth** [comment]
Is this still being closed? It's passed the deadline. Keeping performance bounties up seems useful as a general incentive.

**Comment by PerfectTangent** [comment]
thanks for the reminder. I don't see much point in keeping it open when only one person engaged with it ever. It was an experiment, and people have shown they don't understand or don't care about it, so not much reason to lock this money away. I'd rather find quicker, more effective and to the point bounties to improve game performance than let a bounty like this gather dust. Closing.
