### ISSUE TITLE
Vomitting B:80

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6400]
### Description

**This is a health related bounty and is immune to the feature freeze.** This bounty calls for the addition of a generalized method for letting characters vomit when needed from various causes.

## What is needed to fulfill the bounty

- [x] provide a generalized system that can be utilized to allow for a character to vomit in response to specific circumstances. the vomiting tool should be configurable to allow for flexibility, such as enabling blood to be vomitted up, how likely someone is to vomit from a specific stimulus and other similar parameters.
- [x] make a component that lets food and reagents induce vomitting when consumed.
- [x] vomitting should cause a temporary movement penalty.
- [x] make vomitting cure a small random amount of toxin damage when done.
- [x] make characters dry heave when they have no food or reagents left in the stomach to vomit up.
- [x] make a *vomit emote for when people wish to willingly force themselves to vomit.

**Comment by PerfectTangent** [comment]
bounty valued at 50.00 USD

**Comment by PerfectTangent** [comment]
price reevaluated to 70.00 USD

Update: 80 USD

**Comment by 80sVectorz** [comment]
I am looking to work on this request. I am new to the project but not new to unity and programming ( in Unity). I want to try taking a stab at this but I cannot promise I'll succeed. I am however quite confident I will.

**Comment by PerfectTangent** [comment]
@krijnlol That's awesome! If you need any help or have any questions, you can ask in the discord: https://discord.gg/MPmyQX5V

Make sure to take a look at our contribution guidelines as well: https://unitystation.github.io/unitystation/CONTRIBUTING/

Goodluck!

**Comment by 80sVectorz** [comment]
@PerfectTangent I have found multiple sizes of vomit splats. How should the size of a splat be determined? Should it be random? or a parameter that changes based on what caused the vomiting. Another thing is that I found plasma vomit in the project files are these also a part of this system?

**Comment by PerfectTangent** [comment]
multiple sizes? Uhm, I'm not sure what that's about. I only added one vomit splat and one plasma vomit splat in #8399. We do have a couple sprite variations for them, Is that what you're referring to? In that case, random sprites are nice, but I might have already set it to be random; I can't recall.

> Another thing is that I found plasma vomit in the project files are these also a part of this system?

yes, it is, but it isn't complicated. plasma vomit is specifically for plasmamen, one of the player species in ss13 (not yet added in unitystation because no one's been arsed to.). It's appearance is entirely asthetic. If you could let the stomach define what kind of vomit splat (normal or plasma, or one of the other unusual vomit types as an example), that would be nice. 

There's also a third main variety, which is a toxic vomit splat (no prefab in the project for it, but the sprites are in there), which is supposed to indicate that the given vomiter is vomiting because of high toxicity. Being able to vary the sprite based on that condition is needed, as it's an indication that the player is suffering from high amounts of toxin damage and helps inform them what they need to do to treat themselves.

**Comment by PerfectTangent** [comment]
if you're not that familiar with space station 13 or how it handles this situation, you are welcome to come to the discord and we can talk about how this is intended to function in greater detail.

**Comment by 80sVectorz** [comment]
> 

Okay, Thanks for the reply! that is enough detail for me to be able to continue.

**Comment by 80sVectorz** [comment]
@PerfectTangent I have been working on this for some time now... But I think it is better if you unasign me from this job as I am growing less confident that I can finish it and I would want someone else with more experience to do it.

**Comment by corp-0** [comment]
don't you want to keep trying with our help? What is blocking you right now? We don't mind helping people to get into the codebase

**Comment by Bod9001** [comment]
yeah, I don't mind helping too

**Comment by 80sVectorz** [comment]
It is mostly mental block and mental problems. I quickly loose motivation and energy to work on projects. Most of the time I start with things and end up unable to finish I'd describe it as a sort of very quick burnout and I feel like I should not expect it to go any different with this. I don't want to take up a spot and waste peoples time.

**Comment by corp-0** [comment]
Okay, fair enough.

**Comment by Elijahrane** [comment]
Let's go

**Comment by MaxIsJoe** [comment]
I'm going to be working on this since no one has been actively working on it.

**Comment by corp-0** [comment]
completed by #9931
