### ISSUE TITLE
Generic UI Windows

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6417]
While we do aim to have diegetic UI where appropriate, some generic, simple UIs would be good for quicker development - perhaps as a temporary measure.
Such generic UIs might include:
 - dialogue with a few buttons (I think there are a couple prefabs that are quite similar to this; they could perhaps be refactored into one)
 - selection dialogue where you can select from options
 - input dialogue to take a text input.

Some requirements;
- The dialogs should be easily instantiable via code only, or perhaps with a serialized reference to the UI prefab.
- They should be customisable with just code: set the title, body, button labels, etc.
- A more involved feature would be for the ability to add various inputs to the UI all from code: adding dropdowns, text fields, etc to create a form, though this isn't strictly required.
- The UIs don't need to be networked: this would all be clientside only so it is up to the instantiating code to handle the result.

**Comment by MaxIsJoe** [comment]
All of these have been finally added. As of  #9606
