### ISSUE TITLE
Documenting the skeleton re-login bug / AKA the multiple broken body parts bug

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#6419]
After more than a week of closing and opening the game multiple times, cutting body parts, waiting 4 hours for Unity to build a headless server for me to mess around, having meltdowns and being utterly confused at bodcode, I've finally had some sort of lead for this absolutely disgusting bug.

### What is this Bug Report?
This bug report is me (and possibly others) documenting and reporting their findings on what's causing this issue and what's the root cause of it. It's very hard to pinpoint exactly what's causing all of this but I have covered enough ground for us to narrow down the search for what could be causing this error.

### Before we talk about the discoveries
Since there is no debugging tools for any exported builds of US13 that are actually useful, we need to use the editor and visual studio/jet brains to have more info to work with. Open unity then look for your buildinfo.json file. Open it and change your build number to staging's own build number then enter play mode in the editor and prepare to play on staging inside of the editor.
you can copy paste staging's IP address and it's build number from [here](https://api.unitystation.org/serverlist).
Once you're in, we can debug as much as we like to our heart's desires and have more detailed info on what's going on everywhere.

### The Discoveries
Our journey starts with line 70 in SpriteHanlderManager.cs where Unity throws an error there saying something is null. After doing a lot of tests I can confirm that NOTHING is null and unity was throwing a bunch of errors like these everywhere for sprite handlers. At first I was confused so I decided to dig deeper and I discovered this monstrosity :
 
![image](https://user-images.githubusercontent.com/34368774/116072567-882b3800-a68f-11eb-8b59-c1ab1a4ed4e7.png)

Six heads? all these multiple body parts? what is going on here? But wait! there's more!
![image](https://user-images.githubusercontent.com/34368774/116072624-a2651600-a68f-11eb-85e8-d740b6d9a35d.png)

All of these have wrong values! meaning that these things were never set to start with!
So we've narrowed down the issue from being a SpriteHandler issue to a "what the hell is going on with character spawning" issue.
Oh also, we aren't turning into skeletons 
![image](https://user-images.githubusercontent.com/34368774/116072801-dd674980-a68f-11eb-8088-f0068e4e337a.png)

I'm sorry to disappoint but we're not skeletons, we're just floating skulls. This is because the head has a default skull sprite and everything else doesn't. Also all body parts have a skeleton head SO, so while we have six heads that are actually six skulls. We actually have 20 skulls layering on top of each other because no sprite SO was set for any of these body parts!

![image](https://user-images.githubusercontent.com/34368774/116074317-d4777780-a691-11eb-986f-78349b40fb35.png)
all body parts have this SO

### Theories
Until we find what exactly is causing all of this, let me share with you my theories : 

1. I have a feeling that #5512 could be causing this but with the game spawning multiple body parts of the same thing and not setting any values to it I don't want to say for curtain that this is the case.
2. With the amount of errors that the game throws at you while the game is loading or just playing I have a feeling that all of this is catching up to us and is causing the game to be extremely unstable which ends up creating this issue and maybe other issues like people spawning in space or in the wrong location from what they were in. However that's just a very weak theory because I don't have evidence to back it up like the first one.

### What should we do now?
We need all hands on deck, the more people who can debug this and find the cause of this issue the sooner we can get rid of this nasty bug once and for all. If you believe you have found something useful that explains all of this, report it so we can document it. if you believe you have a fix, fix it then push a PR for it.
I want off Mr.Bones wild buggy ride already and I can't do it alone.

**Comment by MaxIsJoe** [comment]
```
Mono path[0] = '/home/pao13/.var/app/org.unitystation.StationHub/Installations/UnityStationDevelop21042400/Unitystation_Data/Managed'
Mono config path = '/home/pao13/.var/app/org.unitystation.StationHub/Installations/UnityStationDevelop21042400/Unitystation_Data/MonoBleedingEdge/etc'
Preloaded 'FirebaseCppApp-7_0_2.so'
Preloaded 'libenet.so'
Preloaded 'libgrpc_csharp_ext.x64.so'
Preloaded 'sunvox.so'
Unable to preload the following plugins:
	FirebaseCppAuth.so
Display 0 'ASUS VP247 24"': 1920x1080 (primary device).
Display 1 'EK220Q 22"': 1920x1080 (secondary device).
Display 2 'EK220Q 22"': 1920x1080 (secondary device).
Loading player data from /home/pao13/.var/app/org.unitystation.StationHub/Installations/UnityStationDevelop21042400/Unitystation_Data/data.unity3d
Desktop is 1920 x 1080 @ 60 Hz
Initialize engine version: 2020.1.6f1 (fc477ca6df10)
[Subsystems] Discovering subsystems at path /home/pao13/.var/app/org.unitystation.StationHub/Installations/UnityStationDevelop21042400/Unitystation_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.10.27-pao13, LLVM 11.1.0)
Vendor:   AMD
Version:  4.6 (Core Profile) Mesa 20.3.5 (git-cd3161895e)
GLES:     0
 GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_multisample_advanced GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_dist
ance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel
_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_sparse_buffer GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB
_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_
rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_meminfo GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decod
e GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_multimode_draw_arrays GL_INTEL_blackhole_render GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NVX_gpu_memory_info GL_NV_alpha_to_coverage_dither_control GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_shader_atomic_int64 GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_S3_s3tc
OPENGL LOG: Creating OpenGL 4.6 graphics device ; Context level  <OpenGL 4.5> ; Context handle 24129712
Begin MonoManager ReloadAssembly
- Completed reload, in  0.081 seconds
Default vsync count 1
requesting resize 1920 x 1080
Using native desktop resolution 1920 x 1080
requesting fullscreen 1920 x 1080 at 0 Hz
Desktop is 1920 x 1080 @ 60 Hz
UnloadTime: 0.471945 ms
Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: SerializableDictionaryBase`3.m_dict
 
(Filename:  Line: 121)

Serialization depth limit 10 exceeded at 'SerializableDictionaryBase`3.m_dict'. There may be an object composition cycle in one or more of your serialized classes.
... (275 KB left)
```

I think this is important to leave here as well because this is what the game reports inside of log files which can be useful later on.

**Comment by MaxIsJoe** [comment]
Interesting
![image](https://user-images.githubusercontent.com/34368774/116079494-28855a80-a698-11eb-9210-9e6a0c37aad2.png)

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/116085467-21ae1600-a69f-11eb-8047-481e79f3de71.png)
It can do this for some reason
everything will appear to spawn correctly except your chest.

This entire bug is inconsistent and I'm at a dead end once again, no clue as to where this issue could originate from.

**Comment by Aranclanos** [comment]
I just revamped SpriteUpdateMessage in #6480 keeping some of the logic but making it way easier to read and follow for a dev, I thought it would interest you to seek the problem of this issue. There's a chance that this fixed it too but that's just a bet since I dont know what exactly caused this.
There's also #6489 which is a followup fix to my own PR

**Comment by jamessimo** [comment]
I haven’t seen my skull for a while now, is this still a bug?

**Comment by MaxIsJoe** [comment]
Good question, did it get fixed on staging recently?
Not just for relogging in but for when it randomly happens while the player is moving?

**Comment by pyrosshade** [comment]
It seems this is still a bug?
[This was taken not too long ago](https://www.youtube.com/watch?v=pJ-aIoHghVs)

[Discussion of this in #issues-and-suggestions](https://discord.com/channels/273774715741667329/668605946691452949/851525639172653087)

**Comment by MaxIsJoe** [comment]
For those who keep saying they're not experiencing it anymore.

This is from today :
https://youtu.be/pJ-aIoHghVs

**Comment by pyrosshade** [comment]
Max, that's the first link i posted from my comment right before yours

**Comment by MaxIsJoe** [comment]
whoops, didn't see yours because my page didn't refresh.

I have this page pinned

**Comment by corp-0** [comment]
I don't think this is happening anymore, is it?

**Comment by ThatDan123** [comment]
Think this is good to close now
