### ISSUE TITLE
You are unable to melee attack nor pet mobs.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6423]
### Environment
- Game Version: 21042400
- OS Version: Windows 10

### Detailed description of bug
Clicking on mobs doesn't make you melee attack them nor pet (where it should be applicable) them. This means that players are unable to attack mobs either for self-defense, butchering, and general harming and killing. Possibly related to #6367.

### Steps to reproduce
1. Find a corgi, cat, any domesticated animal and while adjacent to it, click on it with an empty hand on help intent.
2. Watch as you don't pet it.
3. Switch to harm intent and click on the same animal while still adjacent to it with or without an empty hand.
4. Watch as you don't attack it.

**Comment by NoooneyDude** [comment]
May be related to #6367.
