### ISSUE TITLE
Mobs turn invisible on death if they're not facing south.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6427]
### Environment
- Game Version: 21042400
- OS Version: Windows 10

### Detailed description of bug

The vast majority of mobs have their sprites disappear when they die while not facing south. The mobs themselves do not despawn as can be seen by right clicking on the tile that they occupy. In fact, it is possible to pull dead mobs using right click's pull option even if they are invisible. Notably, pulling invisible mobs south will make their sprite appear again and it won't turn invisible again if you pull it in other directions.

Hypothesis for why this happens: Sprite data SOs can have sprites for multiple directions. Most mobs have directional sprites while alive. However, the vast majority of mobs have dead sprites that aren't directional and only have a southern sprite. So if a mob is facing west, east, or north and dies the game will try to use a directional sprite that doesn't actually exist. 
The reason why dead mobs don't turn invisible while facing south is because south is the default direction for sprites, so therefore dead sprites without additional directional sprites will only have southern sprites.

### Steps to reproduce
1. Kill a mob somehow, make sure it isn't facing south while it dies and doesn't actually despawn on death.
2. Watch it turn invisible. Right click on the spot where it died to confirm that the animal is still present.
3. Stand adjacent to the spot where the mob died and right click on it. Pull the dead mob.
4. Move south while pulling the mob, watch as it becomes visible again.

**Comment by NoooneyDude** [comment]
~After #6437 is merged, it might be more appropriate to form a list of which mobs need configuring to the new mob sprite state system on `MobSprite`, along with any other remaining system issues.~

**Comment by NoooneyDude** [comment]
~Related to #5325.~
