### ISSUE TITLE
Guns can no longer be fired as a client.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6428]
### Environment
- Game Version: 21042400
- OS Version: Windows 10

### Detailed description of bug
For some reason, guns can no longer be fired as a client. Hosts are still able to fire them however and don't receive the errors in the console below. 
Firing guns as a client creates NREs in the console. Notably, you get different kinds of NREs with the same gun depending on whether you try to shoot using harm intent or not. 
Meanwhile, trying to fire an unloaded gun (either without a power cell or magazine) creates a yellow warning in the console. This warning is not affected by what intent you use when  trying to fire.

Screenshot of console after trying to fire an Imperator. Yellow warnings come from trying to fire it while it has no power cell, Red warnings come from trying to fire it with a power cell. Middle red warning comes from trying to fire it on any intent other than harm intent while bottom red warning comes from trying to fire it on harm intent.
![image](https://user-images.githubusercontent.com/38266309/116317789-ab75e600-a768-11eb-93cd-055f2fb18bae.png)

### Steps to reproduce
1. Find a gun while connected to a server.
2. Click with it on something in order to attempt firing it. 
3. Fail. Check console for errors that come after clicking.

**Comment by NoooneyDude** [comment]
This error when shooting (at least, shooting the Thompson weapon) in the editor playmode may be related:

```
MissingReferenceException: The variable allSpawnablePrefabs of CustomNetworkManager doesn't exist anymore.
You probably need to reassign the allSpawnablePrefabs variable of the 'CustomNetworkManager' script in the inspector.
UnityEngine.Object.get_name () (at <bad59441812943c7b8d5a5ba85795810>:0)
CustomNetworkManager+<>c__DisplayClass21_0.<GetSpawnablePrefabFromName>b__0 (UnityEngine.GameObject o) (at Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs:153)
System.Linq.Enumerable+WhereListIterator`1[TSource].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
CustomNetworkManager.GetSpawnablePrefabFromName (System.String prefabName) (at Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs:153)
Weapons.Gun.DequeueAndProcessServerShot () (at Assets/Scripts/Items/Weapons/Gun.cs:775)
Weapons.Gun.UpdateMe () (at Assets/Scripts/Items/Weapons/Gun.cs:553)
UpdateManager.Update () (at Assets/Scripts/Managers/UpdateManager/UpdateManager.cs:249)
```

This particular error might be related to the update to a newer `Mirror` version.
