### ISSUE TITLE
Issues with the new Character Creator / Selector

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6436]
Here is a statement of accounts of my experience on the latest staging as of this issue:
- right after booting up the game, first character (out of two, in my case) has no preview.
- after clicking `Delete Character` for this first character:
    - there's no warning modal about deleting a character.
    - the count of how many characters I have is not updated.
    - I am given the `Please create a new character` pane instead of switching to the next character, if available.
    - after clicking the change character arrows, the character count is now updated, but I am stuck on the aforementioned screen. I can't select the other character.
    - the edit button is available on this  `Please create a new character` pane - if I click it, I am able to edit the second character.
        - if I hit exit, I am not returning back to the character select list, but instead launching into the server. This is disorientating. Swap the Exit and the Back button positions.
    - the character isn't actually deleted: hit Exit, close and reboot the game -> character returns.
- there's no obvious way to proceed: `Exit` isn't a good name (I might think it means to exit the game - after all, we never clicked on anything to get here right after booting the game). `Continue` would be better and needs a better location, too.
- after loading into the game, the character I spawn with is completely different to the "deleted" character and the remaining character.

**Comment by MaxIsJoe** [comment]
> right after booting up the game, first character (out of two, in my case) has no preview.
> I am given the Please create a new character pane instead of switching to the next character, if available.
> after clicking the change character arrows, the character count is now updated, but I am stuck on the aforementioned screen. I can't select the other character.

Unable to replicate these issues, what OS are you on and does the game give you any errors when loading/saving previews or characters?

> the edit button is available on this Please create a new character pane - if I click it, I am able to edit the second character.
> the character isn't actually deleted: hit Exit, close and reboot the game -> character returns.

That is intended behavior to avoid some other bugs and issues. Though I suppose we can add a check to see if the character list is empty so players don't have access to the edit button when their character list is empty.  

> after loading into the game, the character I spawn with is completely different to the "deleted" character and the remaining character.

This bug makes no sense, we're deleting an entry inside of a list. Not the character settings itself.
It shouldn't alter the currentCharacter settings at all.


>the character isn't actually deleted: hit Exit, close and reboot the game -> character returns.

Regarding this issue, I think I should update the lobby screen to account for this just like how it accounts when there is no character or the character sheet is broken. It's not *bug* per say, but it's confusing behavior for the players and probably future devs who'll touch this as well.
