### ISSUE TITLE
Fire sprite overlay is stuck standing

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#6459]
### Environment
- Game Version: 21050308
- OS Version: MacOSX

### Detailed description of bug

The burn effect overlay for character sprites stay standing up when they're supposed to align with the knocked-over character.
![Screen Shot 2021-05-04 at 7 58 26 AM](https://user-images.githubusercontent.com/61613068/117024490-e4edaa80-acae-11eb-8283-5cd4257c528c.png)

### Steps to reproduce

1. Set yourself on fire
2. Get knocked down due to damage
3. Go into a-ghost

**Comment by Semuca** [comment]
There's already an issue that covers this #6429
