### ISSUE TITLE
Players are invincible, even from Lord Singulo

### ISSUE THREAD

**Issue by Korywon** [unitystation/unitystation#6462]
### Environment
- Game Version: Staging 21050308
- OS Version: Irrelevant

### Detailed description of bug

This was encountered on the staging server. Some of the staging testers noticed that they were unable to kill one another. Even being thrown into singularity doesn't do anything.

Possibly related to the fire damage issue described in #6398.

![image](https://user-images.githubusercontent.com/22848944/117067960-47b36600-acf0-11eb-9a66-341c3a2dca4a.png)

### Steps to reproduce

1. Join a game, preferably with a client connected as well.
2. Try to kill each other.
3. Throw yourself into Lord Singulo.
4. Observe that you cannot die no matter what.

**Comment by Korywon** [comment]
Screenshot provided by kopatel on the Discord server. potatoalienof13 was the host when this issue was encountered.

**Comment by pyrosshade** [comment]
No damage from being in space without gear, no gasping prompt to remind you that you need said gear.
