### ISSUE TITLE
Green highlight around items has disappeared  

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#6474]
### Environment
- Game Version: Staging, 21050704
- OS Version: Mac OS Catalina

### Detailed description of bug

The ability to highlight items in the game seems to have been removed, originally producing green outline surrounding it this is no longer the case and makes it harder to identify what you are selecting.

![Screenshot 2021-05-08 at 22 14 18](https://user-images.githubusercontent.com/80076755/117553749-2a153200-b04b-11eb-9aa4-2df294ba5112.png)
(My mouse is over it, it didn't show in the screenshot)

### Steps to reproduce

1. Join the current staging version.
2. Hover your mouse over any item within the game.
3. Find that there is no longer any green highlight around any item.

**Comment by PetMudstone** [comment]
Green highlight still exists... at first. For some reason, picking up items from tiles that have open lockers on them seems to reduce the size of green highlights if not entirely eliminate them.

**Comment by ArmenianUnion** [comment]
This is still existent on the newest build 21051501
![Screenshot 2021-05-15 at 12 30 49](https://user-images.githubusercontent.com/80076755/118359088-bce92b80-b579-11eb-90b5-00d9027a6a6e.png)
(As you can see the green highlight works fine however after doing what is mentioned above by @PetMudstone it disappears

New steps to reproduce

1. Join newest version of staging
2. Find the green highlight is working as it should be
3. Find any locker 
4. Take an item out of the locker
5. Find the green highlight has disappeared

**Comment by Bod9001** [comment]
was fixed in #6555
