### ISSUE TITLE
Sounds don't load in Editor

### ISSUE THREAD

**Issue by Semuca** [unitystation/unitystation#6477]
### Environment
- Game Version: Windows 10
- OS Version: Staging, Latest

### Detailed description of bug

<img width="194" alt="Screenshot 2021-05-09 201629" src="https://user-images.githubusercontent.com/62051810/117572088-e03c5280-b103-11eb-8575-a841e915b171.png">
When starting Unitystation in the editor sometimes sounds don't load for items like the jukebox. This causes NullReferenceException errors whenever they're interacted with.

This seems to happen for either all jukeboxes in the game, or none of them

### Steps to reproduce

1. Make the AddressableAudioSource list in the jukebox public/serialisable
2. Start Unitystation in the editor, check the jukeboxes to see their addressable paths being null. This happens on-and-off
3. If you interact with a jukebox, a NullReferenceExeption error should occur

**Comment by MaxIsJoe** [comment]
This has not been an issue for a long time
