### ISSUE TITLE
Remove RawMeat component in favour of Cookable

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6481]
The `RawMeat` component has the sole purpose of transforming an item into a different variant when integrity is burnt away. This logic should be refactored into the `Cookable` component with a serialized boolean to determine if cooking via burn damage is eligible (default `true`).

This requires all items with all the `RawMeat` component to instead have `Cookable`, with the cooked product set accordingly.

The `RawMeat` component can then be removed.

**Comment by davodico** [comment]
Hi there! Is this issue still free? I would like to take it and contribute. Could you assign it to me? Thanks.

**Comment by PerfectTangent** [comment]
sure, I appreciate the enthusiasm.

**Comment by VernaSaurus** [comment]
I don't think this issue is open any more. i haven't seen anywhere actually use a raw meat component, and from what I can tell, cookable already handles things being burned.

**Comment by VernaSaurus** [comment]
A quick search in the editor shows that, sure enough, the "raw meat" component no longer exists.

**Comment by VernaSaurus** [comment]
I would say this issue should have been closed a long time ago.

**Comment by davodico** [comment]
Well never mind, but somebody should probably close this issue so it's clear. I will look at something else. Thanks

**Comment by VernaSaurus** [comment]
Yeah, the raw meat file was removed in #7269.
