### ISSUE TITLE
Medbot

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#6483]
### Environment
**- Game Version:** 21-05-10-02
**- OS Version:** Lubuntu 18.04x64
**- Linux version** 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021

### Detailed description of bug

**Medbot dont do anything**

### Steps to reproduce

1. 
2. 
3.

**Comment by PerfectTangent** [comment]
Not exactly a bug. It just hasn't had its features programmed. I think the best move is to open a separate issue that is a feature request. I can get to it at some point soon, if need be. Closing this issue.

**Comment by Fr-Dae** [comment]
could you at least program the bot to give a cardiac massage to someone close to it?  (CPR)

**Comment by PerfectTangent** [comment]
When it is programmed, it will likely work similar to how it does in /tg/.
