### ISSUE TITLE
Ian

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#6484]
### Environment
**- Game Version:** 21-05-10-02
**- OS Version:** Lubuntu 18.04x64
**- Linux version** 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021

### Detailed description of bug

**Ian follow!** don't work

### Steps to reproduce

1. 
2. 
3.

**Comment by PerfectTangent** [comment]
did your character have an accent? If that is the case, this issue might be the cause #4102.

**Comment by Fr-Dae** [comment]
my caracter name's are "Dae"
nothing more

**Comment by DTraitor** [comment]
Were you HoP?

**Comment by Fr-Dae** [comment]
yes
