### ISSUE TITLE
hydroponic bay stats

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#6486]
### Environment
**- Game Version:** 21-05-10-02
**- OS Version:** Lubuntu 18.04x64
**- Linux version** 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021

### Detailed description of bug

When we right clic on a hydroponic bay you have 2 bottle.
one give you statistic of hydrobay
number of water, of nutriment, of fertilizer.
but now nothing happend...

### Steps to reproduce

1. 
2. 
3.

**Comment by PerfectTangent** [comment]
> When we right clic on a hydroponic bay you have 2 bottle.
> one give you statistic of hydrobay
> number of water, of nutriment, of fertilizer.
> but now nothing happend...

Could you explain this a bit more? What are you expecting to happen?

**Comment by Fr-Dae** [comment]
jI don't know what else to describe, before there was a text on the left with the content of a hydroponic station
since a recent update, no.

**Comment by Fr-Dae** [comment]
you can clone this bug, it's fixed yet
