### ISSUE TITLE
Restricted doors can be opened with mouseclick B: 15

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#649]
# Preliminary information

## Category
Bug

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
When you have no access to a door in multiplayer, you can still open the door with a mouseclick, while it does deny access correctly when walking into it.

## Expected/Wanted/Requested Behavior
You should be denied in both cases

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. Try to walk into a door you have no access to
2. See you being denied.
3. Now click on the door
4. you the door open

**Comment by Em3rgencyLT** [comment]
Alright so the real issue is - clicking doors as a client sometimes gives you access to areas it should not.

**Comment by DooblyNoobly** [comment]
Criteria: 

 - Resolve the bugs
 - You should be denied access to the door when clicking on it if it is not part of your ID access

Bounty of 15 usd will be paid on successful merge
