### ISSUE TITLE
Character sprites buggy B:35

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6492]
Character sprite representation is glitchy when moving around.

![buggy character sprites](https://i.imgur.com/7u5VGcK.gif)

**Comment by NoooneyDude** [comment]
I managed to reproduce this locally with two clients on headless: have one client pull the other in a tight circle.

![buggy sprite](https://i.imgur.com/BMic60T.gif)

Both clients saw the exact same thing at all times.

As you can see, you can get it into a buggy state without needing lag to reproduce - permanently stays that way until moved.

**Comment by NoooneyDude** [comment]
The first client died to a fire and was lying prone. I then respawned that client, and the second client observed the corpse as such:

![standing corpse](https://user-images.githubusercontent.com/6926225/118478251-c46c2880-b763-11eb-9d4c-599bfbc94850.png)

Note the lack of visible player clothing, equipment, and the fire is behind the player. Does clothing burn up now? Though I think it is related to the bug above.

**Comment by NoooneyDude** [comment]
Another interesting image

![underwear](https://user-images.githubusercontent.com/6926225/118479946-bd461a00-b765-11eb-8efe-9645edf494c9.png)

**Comment by Bod9001** [comment]
Some issues could be from, the fact that clothing directions are done client side while body directions  sprites are done server side, 
the main issue is it's kind of a mix of the old and new systems so that needs to be sorted

**Comment by PerfectTangent** [comment]
this issue is being promoted to bounty status. Evaluated at 25 USD.

**Comment by pyrosshade** [comment]
This seems like a possible desync issue, should i exclude it from my writeup?

**Comment by PerfectTangent** [comment]
no, reference this issue in that issue if you think they are connected.

**Comment by PerfectTangent** [comment]
bounty bumped to 75 USD

**Comment by Fogapod** [comment]
clothing/body rotation desync:

Only body rotates, clothes face same direction.
This happens when:
- you rotate yourself from radial menu
- you are pulling someone and rotate them from radial menu
- you are walking pulling someone and change direction (first tile in new direction only body rotates, 2nd tile clothes rotate as well)

Demonstration:

https://user-images.githubusercontent.com/22667809/120896484-793e8a80-c62a-11eb-8914-b11d30eb68f2.mp4

### Steps to reproduce
1. rotate yourself from radial menu
2. rotate someone from radial menu (you should be pulling them)
3. pull someone changing direction

**Comment by PerfectTangent** [comment]
After playing several full rounds on staging, I feel reasonably confident that #6815 did fix the issue. I saw no instances of this bug. Closing.

**Comment by Fogapod** [comment]
this isn't completely fixed. rotating my ears:

https://user-images.githubusercontent.com/22667809/124346119-be33ed80-dbe5-11eb-8bf4-057664d83b98.mp4

This also wasn't addressed: https://github.com/unitystation/unitystation/issues/6492#issuecomment-842239408

**Comment by NoooneyDude** [comment]
Also, while alt-clicking in the editor, wasn't rotating correctly:
![rotate player](https://imgur.com/t6FEI7t.gif)

**Comment by NoooneyDude** [comment]
See also
![bad rotations](https://i.imgur.com/r8Wya8R.gif)
- Buckling in faces wrong direction.
- Chat typing icon wrong orientation.
- Table incorrect orientation.

**Comment by PerfectTangent** [comment]
40 USD of the bounty paid out to Aranclanos for #6815.

**Comment by corp-0** [comment]
currently something similar to this issue only happens to me when reconnecting a round. I think we can close this now and evalaute the severity of the new issue.
