### ISSUE TITLE
Blob UI throws errors, making it un-usable

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#6498]
### Environment
- Game Version: 21051322
- OS Version: Win10

### Detailed description of bug

Blob UI throws networked command errors when clicking on them.
None of the UI updates or does anything.

### Steps to reproduce

1. Play blob

### Notes :

I was admin on staging while playing blob

**Comment by ThatDan123** [comment]
Should be fixed by #6511
