### ISSUE TITLE
InputController.cs method Interact() needs to be rewritten to be server authoritative

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#654]
# Preliminary information

## Category
TODO

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
Clients can interact with all objects within reach, regardless of other limitations.

## Expected/Wanted/Requested Behavior
Reach should not be the only server check performed. Server should check and block all other cases, eg. being inside a cupboard.

# Other
Not critical for TDM release.

**Comment by fomalsd** [comment]
Actually, reach check is clientside-only at the moment (for the current branch)
CustomNetTransform PR will add server range check though
