### ISSUE TITLE
Change UI scale

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#6548]
### Description

change UI / GUI scale in game graphique option.
for 11" and 30" 4k screen ...

**Comment by NoooneyDude** [comment]
Duplicate of #2047.

**Comment by NoooneyDude** [comment]
Edit: this is about scaling, not resolution. Closely related to #2047.

**Comment by Fr-Dae** [comment]
resolution are the maximal the screen can accept/ display .
Ui scaling are user preferencie and change for any player.
according to their preferences / habits, abilities, or handicaps.

**Comment by PerfectTangent** [comment]
closing in favor of #7687
