### ISSUE TITLE
Character is slow after spawn

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6552]
Character is slow for a few seconds after spawn.

I suspect this might be due to the blood system spawning without sufficient dissolved oxygen.

**Comment by ThatDan123** [comment]
I asked bod a few days ago and he said it might be to do with the body fat

**Comment by Bod9001** [comment]
it's because the body parts don't stop with nutrition so they have to be supplied from the provided fat

**Comment by jamessimo** [comment]
I’ll look into this as I am working on blood code now
