### ISSUE TITLE
Pointing crashes your game

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#6559]
### Environment
- Game Version: 21051801
- OS Version: Mac OS Catalina

### Detailed description of bug

When pointing your game crashes to the space loading screen with the clown in which you need to restart your entire game OR you get set back to the character menu and if you try to progress beyond that you get hit with the previous talked about loading screen with the clown again.
EXAMPLE(S)

https://user-images.githubusercontent.com/80076755/118725795-576e9680-b828-11eb-8b51-ded13f8b5194.mov

(An example of crashing as soon as pointing)

https://user-images.githubusercontent.com/80076755/118726364-1b880100-b829-11eb-9550-eb1337898682.mov

(An example of being able to point for a while until your game crashes, this usually occurs after restarting your game because of the first crash)
### Steps to reproduce

1. Join the latest staging build
2. Point
3. Experience an immediate crash where you need to restart your game
4. Potentially experience the second video shown if you point again

**Comment by ThatDan123** [comment]
Shouldve been fixed by #6551

**Comment by NoooneyDude** [comment]
Nope! Editor crashed on me when I pointed.

![crash](https://user-images.githubusercontent.com/6926225/118785618-21431c80-b8e5-11eb-8c43-95702fc1be02.png)
