### ISSUE TITLE
How to prank call the entire station [honk]

### ISSUE THREAD

**Issue by Kehren** [unitystation/unitystation#6561]
![image](https://user-images.githubusercontent.com/79835205/118739686-bcd77d00-b852-11eb-832c-d313cb0dc8b7.png)
![image](https://user-images.githubusercontent.com/79835205/118739705-c660e500-b852-11eb-8ec2-7124a33a68d2.png)
![image](https://user-images.githubusercontent.com/79835205/118739868-2788b880-b853-11eb-832b-d78e241e4680.png)
[very based]

Deciding to which channels to send is on the clients side, thus you have no choice but to listen to me (:<<<

didnt check if i can chat in admin chat, probably can, also didnt check whether i can also see all chats, probably can

discord: Jakesolly#0966

**Comment by NoooneyDude** [comment]
Closely related to #3261.
