### ISSUE TITLE
Disposal bins not initialising correctly

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6568]
Disposal bins don't seem to be initialising correctly:
![off](https://user-images.githubusercontent.com/6926225/118791307-b09efe80-b8ea-11eb-81c8-23edf8a2f86e.png)
While the expected sprite state is:
![ready](https://user-images.githubusercontent.com/6926225/118791486-dcba7f80-b8ea-11eb-86da-b9de7a628f12.png)
~~In addition, disposal bins spawned in without a disposal pipe terminal underneath are spawning as immediately above, and not rotated, as depicted here:
![uninstalled](https://user-images.githubusercontent.com/6926225/118791943-4a66ab80-b8eb-11eb-8934-c484b10def91.png)
{spawning over a disposal pipe terminal is as expected)~~

**Comment by NoooneyDude** [comment]
As an aside, would be nice to have a sprite state for the uninstalled state instead of just a sprite rotation.

**Comment by PerfectTangent** [comment]
a'ight I'm throwing this on the disposals bug pile (#4654). There's bounty money in it if anyone's interested. Ditto for #6566.

**Comment by dapocalypse** [comment]
so I've fixed the second part, the first part is something wrong with the overlaysprite manager
