### ISSUE TITLE
Unreal Emergency Shuttle does not dock correctly

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6581]
Unreal Emergency Shuttle doesnt dock correctly and causes it to break when it arrives at centcom.

**Comment by PerfectTangent** [comment]
Good stuff, as I predicted in #6421.

**Comment by corp-0** [comment]
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

Also UnrealStation is currently abandoned.
