### ISSUE TITLE
Teleporting To Different Matrix Bug B:50

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6591]
Happened on staging with square station and asteroid scene 03, couldnt reproduce it with the other loaded asteroid or awaysite scenes.

-Moved players and ghosts to the other matrix, seemed like the server thought the matrix started there instead of further up.

(End of the video shows it clearly)

https://user-images.githubusercontent.com/56727168/119149305-4cdd1880-ba45-11eb-8b66-ff1709bf5319.mp4

![image](https://user-images.githubusercontent.com/56727168/119149690-a6454780-ba45-11eb-99bf-4f5ceef73d4c.png)

maybe related to #6300

**Comment by PerfectTangent** [comment]
This issue is being promoted to bounty status. Evaluated at 50 USD.

**Comment by Aranclanos** [comment]
Do you happen to remember if you late-joined midround or if you were in the server on the previos round?

**Comment by ThatDan123** [comment]
I was late joined as i saw people talking about it in the OOC channel on discord and joined to see what was going on.

I dont know whether this is still an issue or was just a random occurrence. Haven't seen anyone say anything recently about it happening again.

**Comment by ThatDan123** [comment]
Since this appears to have been fixed, and cant be reproduced im gonna close it
