### ISSUE TITLE
Map Security Cameras

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6619]
They could be useful in the future, wink wink. 

Try to imagine a character standing where they are as they will draw the FOV from that position.

#6626 puts a variable on the security camera script which needs to be filled in as to where the camera is e.g:

Put "RD" for rd's office and in the AI UI it will appear "RD - SecCam", so this needs to be filled in

- [x] BoxStation
- [x] Square
- [x] Fall
- [ ] Unreal
- [x] Outpost
- [ ] Pog, needs teleporter too

**Comment by PerfectTangent** [comment]
Closing as Pog and Unreal are no longer being maintained.
