### ISSUE TITLE
Respawning Causes Random Teleporting

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6637]
-Respawning and maybe spawning causes players to teleport to the spawn point

-Might also happen on matrix transition

**Comment by pyrosshade** [comment]
currently reading into this, feel free to ping me in the discord with relevant info

**Comment by PerfectTangent** [comment]
@ThatDan123 can I get a bit more detail for this issue? What exactly is happening?

**Comment by pyrosshade** [comment]
I've not seen an instance of respawning bringing other players yet, however i've seen new players joining causes some players to teleport to arrivals. As well, i've entered onto the mining shuttle and had a nearby player get teleported to me.

**Comment by PerfectTangent** [comment]
> however i've seen new players joining causes some players to teleport to arrivals.

that sounds intentional. If the round has been going for a few minutes, then all new station personnel are spawned in arrivals because they are meant to literally be arriving at the station. See #6153.

**Comment by PerfectTangent** [comment]
unless you mean that it is causing players already in the game to spontaneously teleport.

**Comment by pyrosshade** [comment]
Yes, players who aren't meant to be in arrivals, ones who are already on station.

**Comment by PerfectTangent** [comment]
Mkay. Awaiting more information before I make this a bounty.

**Comment by corp-0** [comment]
lol how does that even happen. 
[Could it be related to changes in matrix net identity? ](https://github.com/unitystation/unitystation/pull/6531). I did test that pr and stuff seemed to be ok but there are way too many cases for a simple test to find all possible issues. When did this start happening?

**Comment by pyrosshade** [comment]
Potentially important to note: this was encountered on staging, assume the circumstances are for a headless server when testing.

**Comment by pyrosshade** [comment]
Players teleported seem to have some proximity to the matrix in question that's being moved to and by consequence teleporting others to.

**Comment by pyrosshade** [comment]
An incident of teleportation happened between two ancient station players where one was teleported to the other which had interacted with the ancient shuttle somehow (assumed they moved onto the shuttle). No other players were teleported in.

**Comment by ThatDan123** [comment]
Dont think this is still happening?

**Comment by ThatDan123** [comment]
Also closing this as i havent seen or heard about it happening anymore
