### ISSUE TITLE
The Bible no longer has the ability to heal or interact with other players

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#6638]
### Environment
- Game Version: Staging 21052720
- OS Version: Mac OS Catalina

### Detailed description of bug

The Bible can no longer heal players with injuries or even interact with them despite being chaplain. Despite this it can be used on yourself but this text is prompted due to being on full health.
![Screenshot 2021-05-28 at 22 23 26](https://user-images.githubusercontent.com/80076755/120043625-36662c80-c004-11eb-8dda-eca2706806cc.png)
(Even when you do use it on yourself it only causes more damage and when trying to fix said damage it causes more damage)

### Steps to reproduce

1.  Spawn in latest staging
2. Choose the chaplain profession
3. Find you cannot use your Bible on others and only on yourself

**Comment by JukeJukestar** [comment]
Cant believe they added Atheism smh

**Comment by Bod9001** [comment]
humm, can't replicate with build and Editor hosting

**Comment by MaxIsJoe** [comment]
Can confirm that this issue can't be replicated with the bible and works fine
