### ISSUE TITLE
Dismembering body parts does not remove associated clothing.

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#6639]
### Environment
- Game Version: Mac OS Catalina
- OS Version: 21052720

### Detailed description of bug
Dismembering a body part leaves things like clothing and beards in an empty void.
![Screenshot 2021-05-28 at 23 51 05](https://user-images.githubusercontent.com/80076755/120048688-aaf29880-c00f-11eb-8d94-ce9b0a7ce4e8.png)

(Good example given by @pyrosshade the arms are gone but the gloves are still there, the head is gone but the beard, headset and hat is still existent in an empty void as if the head is still present.)

1. Join latest staging version
2. Find a body
3. Dismember body
4. Find that dismembering certain body parts leaves the clothing still present as if it's still there for example dismembering a head causes floating glasses.

**Comment by MaxIsJoe** [comment]
Hm, I think disembowling will fix the beard issue when it's added.
as for stuff like clothes and the ability to pick up items with no limbs present, that's going to have to wait until Bod's dynamic slots are introduced.

**Comment by Pockets-byte** [comment]
there's also the issue of clothing making it seem as if you still had missing limbs

**Comment by MaxIsJoe** [comment]
I've just tested this, this has been fixed by me loooooong ago.
