### ISSUE TITLE
Objects are not properly despawning when smashed by an admin (and possibly under other situations) B:25

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6641]
### Environment
- Game Version: Develop 21052202

### Detailed description of bug

shit's broke as fuck. possibly related to #6190, which was supposedly fixed.

![ghost door](https://user-images.githubusercontent.com/68730437/120052403-327dde80-bff3-11eb-8231-0361d473cf61.png)

**Comment by PerfectTangent** [comment]
is now bounty. 25 USD.

**Comment by PetMudstone** [comment]
Objects may not properly despawn when destroyed by other means too. Such as a player shooting a door to the point where it is destroyed.

**Comment by PetMudstone** [comment]
This bug is annoyingly inconsistent in its replication. Destroying objects only sometimes seems to leave "ghosts" that block movement.
Additionally, from past study of this bug it _may_ only affect clients. I might be wrong however.

**Comment by ThatDan123** [comment]
This still happen?

**Comment by PerfectTangent** [comment]
I don't think anything in particular has been done to fix it since posting. Has there been?

**Comment by ThatDan123** [comment]
There was an issue where stuff wasnt been moved correctly, which could effect destroyed objects that has been fixed.

**Comment by Aranclanos** [comment]
Can't reproduce
