### ISSUE TITLE
Late join on Job Selection Stuck

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6642]
When joining a round late it seems that players can be refused from joining the game unless joining as spectator.
When picking a job, the player is met with the following screen for a time before being returned to the job selection screen.
![image](https://user-images.githubusercontent.com/14188696/120052476-85f02c80-bff3-11eb-8217-293d65223932.png)

Steps to reproduce:
1. Join the round late
  1a. This may need testing on headless server
2. Attempt to pick an open job

**Comment by Fogapod** [comment]
I had this issue before, buh haven't seen it for a few builds. Also looks like other people stopped complaining as well.
Was this fixed?

**Comment by pyrosshade** [comment]
> 
> 
> I had this issue before, buh haven't seen it for a few builds. Also looks like other people stopped complaining as well.
> Was this fixed?

Good question, considering i was just recently playtesting yesterday and didn't run into it. I'm inclined to believe that for now it's fixed.
