### ISSUE TITLE
REST button stopped working

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6645]
### Environment
- Game Version: 21052720

### Detailed description of bug

REST button does nothing. Every time I press it error is printed:
![image](https://user-images.githubusercontent.com/22667809/120063127-5a5e5800-c06e-11eb-900e-12cbfaef8aaa.png)

I asked other people on server and they do not have this problem. I also was able to rest on this version yesterday.

### Steps to reproduce

1. Press REST button

**Comment by ThatDan123** [comment]
Does this still happen?

**Comment by Fogapod** [comment]
> Does this still happen?

This happened to me only once. Might be fixed, I can't tell

**Comment by ThatDan123** [comment]
I'll close for now, i think i fixed the speech bubble error
