### ISSUE TITLE
When doing surgery, performers name is not shown to other players 

### ISSUE THREAD

**Issue by jamessimo** [unitystation/unitystation#6649]
### Environment
Staging
Win7

### Detailed description of bug
Was watching a player do surgery and each step would not show the players name but just say {performer}

### Steps to reproduce
Have another player on a server do surgery on you or another player and the chat will say 

`"{performer} starts to use scalpel to cut open JohnDoes head"`
`"{performer} uses scalpel to cut open JohnDoes head"`
etc.... (John Doe being the patient)

**Comment by pyrosshade** [comment]
This may be an issue of forgetting to do an interpolated string

**Comment by corp-0** [comment]
certainly, seems like someone forgot to type the ``$`` before the string.

**Comment by pyrosshade** [comment]
> 
> 
> certainly, seems like someone forgot to type the `$` before the string.

i mean yeah that's the simpler gist of what i said, but i agree
