### ISSUE TITLE
Food items do not disappear after being consumed.

### ISSUE THREAD

**Issue by JukeJukestar** [unitystation/unitystation#6651]
<img width="1920" alt="eat" src="https://user-images.githubusercontent.com/76008882/120081160-50634600-c0bc-11eb-836d-cfdba122f962.PNG">

### Environment
Staging Build 21052720/ Windows 10

### Detailed description of bug

Consuming food items does not make them disappear, but plays the eating sound and displays the eating message in chat.
It seems to reduce hunger (couldnt locate the value in the Variable Viewer) but never satiates the player, the highest level of fullness appears to be "You unwillingly eat X"

### Steps to reproduce

1. Log into the game on local or any server
2. Pick up a food item
3. Attempt to consume the food item in question
4. Realize you are unable to consume the food item, eternally cursed like Tantalus

**Comment by pyrosshade** [comment]
This is likely due to erroring on attempting to deal with reagents in the edible script, as this is what happens right before removing the food item, and there have been known errors with the internals of reagent code recently.

**Comment by pyrosshade** [comment]
![image](https://user-images.githubusercontent.com/14188696/120083293-b4264880-c095-11eb-9ea1-a20b926c0648.png)

**Comment by jamessimo** [comment]
Just to add to this, you can spam click food and will play the eat noise which is annoying.

**Comment by PerfectTangent** [comment]
> Just to add to this, you can spam click food and will play the eat noise which is annoying.

that's opting in to being annoyed, though. I don't see why that's noteworthy.

**Comment by jamessimo** [comment]
> > Just to add to this, you can spam click food and will play the eat noise which is annoying.
> 
> that's opting in to being annoyed, though. I don't see why that's noteworthy.

The sound plays for everyone within ear shot. Not just client side, its being used for griefing.

**Comment by PerfectTangent** [comment]
This changes everything. Good lord.

**Comment by Bod9001** [comment]
has been fixed in #6663
