### ISSUE TITLE
Autopsy Tables Broken

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#6653]
### Environment
- Game Version: 21052720
- OS Version: Windows 10

### Detailed description of bug

You can't drag people onto autopsy tables in the new build. I have my intent set to help, and i drag them on, and still nothing. We tried with the person standing up and sitting down. Still nothing.

### Steps to reproduce

1. Find a autopsy table
2. Set intent to "help"
3. Drag person's sprite onto autopsy table
4. Get confused

**Comment by PerfectTangent** [comment]
what map was this tested on? Some maps have the old operating tables which are not actually functional. They haven't been replaced yet with the new, proper operating table.
