### ISSUE TITLE
Character's sprites don't change while crawling

### ISSUE THREAD

**Issue by MrAsbestos** [unitystation/unitystation#6671]
### Detailed description of bug
When a character moves while crawling, their sprite doesn't change, it stays the same.

### Steps to reproduce

1.  Go into crawl mode.
2.  Move.
3.  Notice how your character stays the same and it's sprite doesn't change.

Here it is in action:
![8mJ3XzMFLz](https://user-images.githubusercontent.com/65787528/120569514-4484c600-c3d3-11eb-9933-a97e731c9fd2.gif)

**Comment by Fogapod** [comment]
What is the expected behavior? Is this about some moving animation or what?

**Comment by MrAsbestos** [comment]
It should look like this:

https://user-images.githubusercontent.com/65787528/120938236-09361000-c6cf-11eb-965c-bc7b662d7f3d.mp4
