### ISSUE TITLE
Bug Reporting and Quality Assurance CONTEST B: 50 x 3

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6679]
### Description

**This is a contest centered around thoroughly detecting and documenting bugs on staging. There will be 3 winners for this contest. Each winner gets 50.00 USD.** The purpose of this contest is to help get as many bug reports on the github as possible so that contributors have as much information at their disposal as possible when trying fix the current bugs in staging. **This contest will last for 1 week. END DATE: Friday, June 11th at 20:00 UTC.**

**_The three people who post the most qualifying bug reports during the contest will be nominated the winners._**

Here is how to participate:
go onto staging and look for bugs. Once you have found a bug, document all information you can about it. Look in the console and record any errors in the console that you believe may be related (when you click an error in the console to get it's full details, it is automatically copied to your clipboard, so copying and pasting is easy).

**to qualify a bug report you've posted for the contest you must:**
1. Make sure the bug doesn't have an open issue on the github already.
2. Make sure the bug exists on staging.
3. Make a bug report issue with a relevant description and steps to reproduce. 
4. If it is a visual bug, you must include an image or video of the bug in action.
5. Comment your issue number under this bounty to apply that issue for the contest.

Whether a given bug report qualifies for this competition will be determined by @corp-0, @Bod9001, and myself. I will also remind you that you must still meet the contribution guidelines for bounties and it is your responsibility to verify you can receive payments via PayPal. Only bug reports you have posted when this contest has started may apply. You must post a minimum of 8 bug reports to qualify for the cash prize.

**Comment by Pockets-byte** [comment]
#6688 #6687 #6686 #6684 ~~#6682~~ #6680
so far
and ~~#6689~~, #6691, #6692, #6694, and #6696
also #6713, #6716, #6717, and #6727
#6731 #6734 #6736 #6741 #6744 #6746 #6747 #6748 #6749 ~~#6750~~  #6751 #6752 #6753 #6764 #6772 #6779 #6781.

**Comment by pyrosshade** [comment]
Hostile mobs attack text shows incorrectly. #6695
Pka overlays don't go away #6704 
Lavaland tiles show as if they don't have flooring #6705
Certain lavaland tiles show as invisible #6706 
UnrealStation Quantum pad from lavaland #6714
Traitor Entries overlap telecrystal cost #6720
Traitor menu placeholder still exists #6721
UnrealStation escape shuttle rendered inoperable by asteroids #6724
Players in character selection menu can hear sounds #6725
Traitor PDA uplink Error #6726
Ore sprites overlay jungle trees #6730
Ghost teleport locations still show newlines #6732
ancient engie shuttle not showing proper coords #6784 
overlay not centered properly on rotated matrices #6785

**Comment by techpriest154** [comment]
#6701
 #6702
 removed for being a duplicate
 #6711

**Comment by Fogapod** [comment]
### Notes for myself
?: pobably a duplicate
~~strikethrough~~: confirmed duplicate/invalid

- #6708: rest/stand
- #6709: PDA UI shows no ID after rejoining
- #6710: stuck in space after rejoining
- #6712: doors are invisible from certain angles
- #6715: climbing on table while buckled
- #6718: i_closing and o_closing labels
- #6719: recall spell messages
- #6722: lighting does not update
- ~~#6723: clothes do not rotate with body in some cases~~
- #6729: misleading message when spraying on tile twice
- ~~#6737: spell buttons remain after death/respawn~~
- #6739: wizard ship has no atmos
- #6740: I keep spawning as deleted character
- #6742: mobs cannot get hit by thrown objects
- ~~#6743: pulling glass shards causes no harm~~
- #6745: hidden items reveal name when removed
- #6767: bad glowstick sprite
- #6768: mining message for stone 
- #6770: Eject Cartridge drops ID on floor
- #6771: Logging off on movable chair
- #6780: Held and dropped items light levels

**Comment by Fogapod** [comment]
What about mapping issues like broken vending machines/doors/wires/bugged items? Do these qualify?

**Comment by pyrosshade** [comment]
> 
> 
> What about mapping issues like broken vending machines/doors/wires/bugged items? Do these qualify?

if it's not already reported, and there's buggy behavior, i believe that qualifies
