### ISSUE TITLE
Radiator heat pipes don't do anything

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6680]
Staging - latest release

Heat piping for radiators has the code commented out, and does not function
you can run a Supermatter with some radiators, which won't decrease the temperature at all 
also checking the code directly, it's pretty obvious
this is a pretty big issue because it makes running a supermatter impossible

**Comment by pyrosshade** [comment]
Yeah apparently this has been a thing for a while, but it's good to have this as an issue now.

**Comment by PerfectTangent** [comment]
closing in favor of #7490, which is more up to date.
