### ISSUE TITLE
Gibbing doesn't occur properly

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6682]
Staging - linux

Currently when gibbed people don't drop meat, organs, limbs, or gibs, just their items
has been an issue since gibbing by hand was disabled

see literally any gib event

also when smited, players don't comically explode - this is a game breaking issue, which needs to immediately be fixed

**Comment by PerfectTangent** [comment]
not exactly a bug, more just a missing feature.

**Comment by Pockets-byte** [comment]
I would agree with you if it hadn't been a thing in the past

**Comment by corp-0** [comment]
I don't think we ever had gory gibbing and organs weren't a thing before, we only destroyed the body and left a steak. This one is a missing feature.
