### ISSUE TITLE
Emag text feedback is missing

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6687]
Linux- staging

Loud emag interaction messages and so on don't work anymore
emagging lockers, doors and anything else makes it pretty clear

**Comment by corp-0** [comment]
make a step by step so we can reproduce.

**Comment by Pockets-byte** [comment]
uh. alright
1. spawn emag
2. emag locker, or door, or shuttle console
3.?????? no messages should be clear

**Comment by corp-0** [comment]
Spawned an emag, tried emagging doors but it didn't seem to have any interaction, maybe new doors don't have an emaggable component. Spawned a cleanbot and a floorbot, both were correctly emagged but I didn't hear any sound nor any text message, only the change of sprite and behaviour from the bots.

**Comment by PerfectTangent** [comment]
the title of this issue seems redundant with #6335. What exactly is this issue describing?

**Comment by Pockets-byte** [comment]
not actual sounds, but "loud" messages, which we used to have for at least
some interactions

**Comment by PerfectTangent** [comment]
so this issue is describing the lack of a chatbox message?
