### ISSUE TITLE
 Staging restarts causes game to be stuck

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6689]
Linux staging - 

we Admin-restarted a round. however the restart didn't work. and now we're stuck on the last frame of a video
I don't know if it's replicable. but try restarting a round in staging 
![Screenshot at 2021-06-04 20-01-54](https://user-images.githubusercontent.com/55299415/120873342-bbef5c80-c56f-11eb-8b3e-fbb56b44bb21.png)
rejoining put me right back into the game

**Comment by NoooneyDude** [comment]
I too experienced this.

**Comment by Pockets-byte** [comment]
Update. shuttle arrives funky, and still doesn't end round
![Screenshot at 2021-06-04 20-13-25](https://user-images.githubusercontent.com/55299415/120873747-674ce100-c571-11eb-9811-e68bd9e2c959.png)

**Comment by pyrosshade** [comment]
> 
> 
> Update. shuttle arrives funky, and still doesn't end round
> ![Screenshot at 2021-06-04 20-13-25](https://user-images.githubusercontent.com/55299415/120873747-674ce100-c571-11eb-9811-e68bd9e2c959.png)

which station was this? this is likely an issue with the escape shuttle's settings for the particular station.

**Comment by Pockets-byte** [comment]
this was Outpost

**Comment by corp-0** [comment]
I restarted a round today be clicking on "end round" button from the round manager page. What button are you pressing?

**Comment by Pockets-byte** [comment]
I don't know. it was wafflez who restarted the round

**Comment by corp-0** [comment]
I need at least clear steps to try to reproduce it. Until then, invalid for contest and closed. Feel free to reopen if you can get me a better description.
