### ISSUE TITLE
NPCs tend to drift towards certain areas of the station

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6693]
Linux - staging

Robots all tend to conglomerate in certain locations on the station
they also can't open doors right now

![Screenshot at 2021-06-04 20-48-53](https://user-images.githubusercontent.com/55299415/120874824-75e9c700-c576-11eb-99f4-5c29dd5f4f92.png)
![Screenshot at 2021-06-04 20-48-59](https://user-images.githubusercontent.com/55299415/120874827-78e4b780-c576-11eb-8e93-dc5871650654.png)

**Comment by pyrosshade** [comment]
mob AI probably needs to be updated to better account for what does or does not block movement.

**Comment by PerfectTangent** [comment]
could you edit the title to be legible and relevant to what you reported?

**Comment by PerfectTangent** [comment]
no longer relevant with #8025, I think.
