### ISSUE TITLE
Supermatter slivers get vaporized by supermatter

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6694]
Linux-staging

supermatter slivers disintegrate when touched to a supermatter shard
![Screenshot at 2021-06-04 20-58-08](https://user-images.githubusercontent.com/55299415/120875090-07a60400-c578-11eb-8953-363d81c1d8f6.png)

**Comment by pyrosshade** [comment]
is this not expected behavior?

**Comment by Pockets-byte** [comment]
It makes sense that it wouldn't destroy the slivers.
I'm booting up a codebase now

**Comment by pyrosshade** [comment]
in the image you linked you are literally getting a message that the sliver is getting destroyed?

**Comment by pyrosshade** [comment]
"The supermatter sliver flashes into dust-"

**Comment by Pockets-byte** [comment]
this shouldn't happen though. just like the supermatter scalpel has a
different interaction, so should the shard

**Comment by Pockets-byte** [comment]
actually in ss13 you can't even pick up the shard 
![Screenshot at 2021-06-04 22-04-06](https://user-images.githubusercontent.com/55299415/120876861-4be9d200-c581-11eb-8f62-fe24c4b60995.png)

**Comment by Pockets-byte** [comment]
I'm not sure, but I think it should just react badly with the crystal. that or put it back on

**Comment by ilinm1** [comment]
working on it and couple other SM changes
