### ISSUE TITLE
Hostile mobs attack text shows incorrectly.

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6695]
This happens on staging

1. Allow a hostile mob to attack you
2. Notice the chat message says "xxx has attacked yyy in the head"
3. Notice on the health doll that the attacked bodypart is most likely not the head
    3a. if it is the head, allow the mob to attack multiple times and note the health doll each time

**Comment by corp-0** [comment]
![image](https://user-images.githubusercontent.com/43683714/120911213-58d6f600-c653-11eb-8043-5f55942568b9.png)
![image](https://user-images.githubusercontent.com/43683714/120911215-62605e00-c653-11eb-9a46-671ac02b03c1.png)
I could reproduce
