### ISSUE TITLE
Climbing on glass tables should cause them to break.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6699]
### Description
In /tg/, you can climb on glass tables like any other tables. However, it turns out that glass isn't particularly well suited for holding up spacemen and any glass table that is climbed on will break under the weight of the person that climbs it. This creates a glass shard which will hit the person who broke the table once in a random body part and will also stun the climber for 10 seconds (which honestly seems excessive to me).
![image](https://user-images.githubusercontent.com/38266309/120881509-7ab67700-c586-11eb-83ee-39c855bc3b24.png)

**Comment by pyrosshade** [comment]
10 does seem excessive, something closer to the amount of time it takes to get up from rest, with a little extra to mind the glass sounds about right.

**Comment by PerfectTangent** [comment]
yeah, we talked about it in @craftxbox's floor hazards PR. 10 may be high, but let's go with it for now. We can tweak it down a bit if needed. also, iirc, it's a 50% chance for it to hit the person with the glass. related to #5754 and #6140 (which craftbox has said he cannot work on any longer, so anyone is welcome to finish the PR.

**Comment by PerfectTangent** [comment]
also, relevant educational material:

https://user-images.githubusercontent.com/68730437/120882215-2f12c600-c5a4-11eb-9b52-4f26ee035e29.mp4
