### ISSUE TITLE
Doors don't do air warning

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#6701]
### Environment
- Game Version: 21060314
- OS Version: windows ten, latest

### Detailed description of bug

im in fall station, and the airlocks no longer flash yellow or make a sound when i try to go into space, they still need me to walk into them twice to open though 
![image](https://user-images.githubusercontent.com/78688207/120893971-d2e48c00-c60d-11eb-8115-721d7f8e9d30.png)

### Steps to reproduce

1. just go on fallstation and try opening a door to space by walking into it
2. 
3.

**Comment by corp-0** [comment]
could reproduce. I think we forgot to set the sound on V2 doors.

**Comment by PetMudstone** [comment]
We did not. V2 doors properly path to the correct sound but it does not play anyways.

**Comment by corp-0** [comment]
https://github.com/unitystation/unitystation/blob/07be18d9f7a55093baa33c9972a68222329aad63/UnityProject/Assets/Scripts/Objects/Doors/DoorAnimatorV2.cs#L190 maybe this is the problem. I'm not sure why it is a client method that plays the sound, @ThatDan123 do you know?

**Comment by NoooneyDude** [comment]
`DoorAnimatorV2` uses its own netmessage for state update.

**Comment by PetMudstone** [comment]
From testing V2 doors do play air warning sounds but only for hosts. Clients don't receive the sound. Neither has the warning lights show.

**Comment by AtnerNT** [comment]
Airlocks have their pressure warnings back
