### ISSUE TITLE
Lavaland tiles show as if they don't have flooring

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6705]
![image](https://user-images.githubusercontent.com/14188696/120891025-55505a00-c5d4-11eb-9147-54aabe8347ae.png)

**Comment by ThatDan123** [comment]
Gonna say this was introduced by #6663, probably an issue with the default colouring?

**Comment by corp-0** [comment]
this issue was fixed by a pr but it is still valid for the  contest.
