### ISSUE TITLE
Certain lavaland tiles show as invisible

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6706]
Certain lavaland tiles show as invisible, more prominently, ores

tile to the left is not walkable
![image](https://user-images.githubusercontent.com/14188696/120891123-c728a380-c5d4-11eb-8b6e-ba8f2752e43d.png)

after being cleared, ore dropped, tile is walkable
![image](https://user-images.githubusercontent.com/14188696/120891140-df002780-c5d4-11eb-916d-f40d23c586f4.png)

**Comment by pyrosshade** [comment]
potentially related to #6705

**Comment by pyrosshade** [comment]
Found a invisible maze, west of base1
![image](https://user-images.githubusercontent.com/14188696/120892117-99def400-c5da-11eb-89ef-8801e9d5510c.png)

**Comment by pyrosshade** [comment]
This issue seems to be for those who join the round late

**Comment by corp-0** [comment]
same as the related issue, still valid
