### ISSUE TITLE
all PDAs say "no ID inserted" after rejoin until ui is reopened

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6709]
### Environment
- Game Version: 21060314

### Detailed description of bug
Title.
This is only a visual bug. PDA works as ID and "eject ID" button works.
![image](https://user-images.githubusercontent.com/22667809/120892435-f3651400-c616-11eb-9329-b9fb70216bc8.png)

### Steps to reproduce

1. put ID into PDA (you can drop it or keep in inventory)
2. rejoin round
3. open PDA (shows no ID)
4. open PDA again (shows ID)

**Comment by corp-0** [comment]
I could reproduce

**Comment by Fogapod** [comment]
This has been silently fixed by some recent change.
