### ISSUE TITLE
Centcomm has no atmosphere

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6713]
Linux - staging

Centcom on unreal has no atmosphere, and is at absolute zero
causing players to die immediately as soon as they spawn in as a centcom role 
![Screenshot at 2021-06-05 10-00-24](https://user-images.githubusercontent.com/55299415/120894206-4cb44f80-c5e5-11eb-830a-12c179c6b8c7.png)
![Screenshot at 2021-06-05 10-02-01](https://user-images.githubusercontent.com/55299415/120894209-4f16a980-c5e5-11eb-9a25-1242e90b6161.png)

**Comment by corp-0** [comment]
*gasp* v-*gasp*-alid
