### ISSUE TITLE
Climbing on table while buckled causes some bizarre behaviour

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6715]
### Environment
- Game Version: 21060314

### Detailed description of bug

Title.
After climbing on table, your camera and player model stay attached to chair (even if it's moved), but your body and your reach for item interaction move to the table tile you climbed to.
After you unbuckle yourself you get teleported to table from any distance.

demonstration:

https://user-images.githubusercontent.com/22667809/120894563-c36f3e00-c621-11eb-9a4e-862c2e072d1b.mp4

### Steps to reproduce

1. sit on chair near table
2. climb on table
3. entertain crown with magic tricks
4. ask someone to pull your chair away
5. unbuckle and get teleported all the way back to table

**Comment by ThatDan123** [comment]
Fixed by #6814
