### ISSUE TITLE
stamina damage is very lethal

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6716]
linux - staging

Stamina damage can kill, amputate, and remove internal organs
this clearly shouldn't happen
![Screenshot at 2021-06-05 10-26-00](https://user-images.githubusercontent.com/55299415/120894849-7de24f00-c5e8-11eb-92ab-3e8d40caf64a.png)

**Comment by PerfectTangent** [comment]
what source of stamina damage were you using to test?

**Comment by Pockets-byte** [comment]
Item that dealt high stamina damage

**Comment by PerfectTangent** [comment]
like what? I don't know any items in our game that deal stamina damage at this time.

**Comment by Pockets-byte** [comment]
VV is a thing Perfect

**Comment by PerfectTangent** [comment]
yeah, but that is by no means clear when you say "Item that dealt high stamina damage" cak. you could have been confused and were using things you _thought_ dealt stamina damage for testing. Think what information you give through.

**Comment by Pockets-byte** [comment]
Sorry, I was testing stamina damage with VV on a random item

**Comment by Pockets-byte** [comment]
Alright so updaate
this is actually a bug with VV not with stamina damage
it's not properly changing things

**Comment by MaxIsJoe** [comment]
it's fixed in #6643

**Comment by Pockets-byte** [comment]
nice

**Comment by corp-0** [comment]
this was confirmed to be false and only VV not displaying the right damage type. Invalid.

**Comment by Pockets-byte** [comment]
I would say it's still completely valid in terms of VV not changing the
thing properly
