### ISSUE TITLE
Bad recall spell messages in chat

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6719]
### Environment
- Game Version: 21060314

### Detailed description of bug

2 problems there:
- [x] message saying there is nothing to mark appears after messages about successful item marking
- [x] when you recall item there is unformatted text
![image](https://user-images.githubusercontent.com/22667809/120895842-7db57400-c627-11eb-8028-9a1ea9d11bce.png)

### Steps to reproduce

1. Mark item with recall spell (says you aren't holding anything valid for marking for recall)
2. Throw item away
3. Use recall (formatting tag shown)

**Comment by NoooneyDude** [comment]
I believe issue 1 is fixed in pending PR #6530.
