### ISSUE TITLE
Traitor Entries overlap telecrystal cost

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6720]
As pictured 
![image](https://user-images.githubusercontent.com/14188696/120896094-f7307080-c5ed-11eb-86ef-367e07d3a893.png)

**Comment by PetMudstone** [comment]
I was able to reproduce in editor and as a localhost. Notably, the positions of the TC and Cost text and whether or not the boxes for items overlap them is dependent on the size of the game window. There will be an overlap like that seen above in 1920x1080 fullscreen but one can get different results by going out of fullscreen and resizing the window.
![PDAResize](https://user-images.githubusercontent.com/38266309/123384297-15342580-d549-11eb-86d6-2e52a86ff75a.gif)

**Comment by PetMudstone** [comment]
Notably when I was testing in editor by resizing my game view window, the pixel perfect warning showed up in the top left when the item entry overlapped the TC cost. Possibly related to #6079?
