### ISSUE TITLE
Lighting does not update after you activate more powerful light source

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6722]
### Environment
- Game Version: 21060314

### Detailed description of bug

Flashlight is more powerful light source than PDA, but if PDA light is on, emitted light stays on same level if you turn flashlight on/off.
This applies to all light sources with varying brightness and color (color stays same until you turn off previous light source)

Demonstration:

https://user-images.githubusercontent.com/22667809/120896258-7d1ddd00-c629-11eb-964b-5c110a17b4fa.mp4

### Steps to reproduce

1. turn on PDA light
2. turn on flashlight light

**Comment by pyrosshade** [comment]
Player prefab may need more light components added to accomodate having multiple light sources on person?

**Comment by Pockets-byte** [comment]
I feel like this has been reported already because it's been around for ages, but haven't checked

**Comment by Fogapod** [comment]
> I feel like this has been reported already because it's been around for ages, but haven't checked

Yeah, i remember this for as long as I've been playing. I haven't found similar issues though.

**Comment by corp-0** [comment]
I couldn't find any issue mentioning the problem. This is valid for the contest.
