### ISSUE TITLE
Body rotates separately from clothes in some cases (pulling, rotation with radial menu)

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6723]
### Environment
- Game Version: 21060314

### Detailed description of bug

This is a new bug (definitely post health, not sure if i saw it a few builds ago).

Only body rotates, clothes face same direction.
This happens when:
- you rotate yourself from radial menu
- you are pulling someone and rotate them from radial menu
- you are walking pulling someone and change direction (first tile in new direction only body rotates, 2nd tile clothes rotate as well)

Demonstration:

https://user-images.githubusercontent.com/22667809/120896484-793e8a80-c62a-11eb-8914-b11d30eb68f2.mp4

### Steps to reproduce
1. rotate yourself from radial menu
2. rotate someone from radial menu (you should be pulling them)
3. pull someone changing direction

**Comment by Fogapod** [comment]
Probably a duplicate of: https://github.com/unitystation/unitystation/issues/6492#issuecomment-842220138

Though i added a bit more explanation and examples.

**Comment by corp-0** [comment]
I don't know what to do here, it technically is a duplicate but the other issue is a little messy. @PerfectTangent what do you think? I'd give this one a green validForContest label.

**Comment by PerfectTangent** [comment]
I'd say this issue is redundant. It does give new information, but that information should be put in the other issue. It's useful info though, so if you wanted to count it, then I'm fine with that. Though, I would require @Fogapod put this stuff under #6492. Anyways, closing this issue.
