### ISSUE TITLE
Players in character selection menu can hear sounds

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6725]
came in from a previous round, and did not choose a character, stayed around, and i could hear

1. play on staging
2. don't pick a character and wait
3. prefereably have someone start a spreading plasma fire
4. listen for sounds of the fire doing damage, incessant wrench on wall noises.

**Comment by corp-0** [comment]
I wonder if this is a bug or feature.

**Comment by PerfectTangent** [comment]
the menu is physically located in game space, so if it's near things that would make sound, it would hear them. It doesn't scream to me as being a bug. Unintended behaviour possibly, but idk if it's actually bad.

**Comment by pyrosshade** [comment]
It's maddening when it's the sound played whenever a wall is attacked or damaged, especially if it's because of a spreading plasma fire or an incessant player. Would be understandable if y'all wanna keep it in, i just thought it might be unintended.

**Comment by pyrosshade** [comment]
That being said that particular kind of sound should probably not be global in general, so as to not confuse/bug players actually in game who aren't near enough the source.

**Comment by PerfectTangent** [comment]
wall hitting and plasma fire bashing should not be global. The reason they can be heard is because the menu is physically near them.

**Comment by pyrosshade** [comment]
So, sounds playing provided they are physically near them does seem neat, some tiny bit of immersion i suppose. I do wonder though if perhaps we could give mappers an object to define where this area would be.

**Comment by PerfectTangent** [comment]
I think the ideal thing would be to completely change where it's located when we expand the pre-game lobby. Letting mappers define where it is seems fine. Making it default to the laser tag scene seems like a good idea, too.

**Comment by pyrosshade** [comment]
Just now was playing on staging, was in unrealstation cargo, and could hear someone whacking the medChem's window.

**Comment by corp-0** [comment]
windows hit sfx is global for some reason

**Comment by PerfectTangent** [comment]
is it like gun sounds which were local but had an insanely long hearing range?

**Comment by corp-0** [comment]
can't tell, would have to check in unity editor
