### ISSUE TITLE
Gateway Stops working

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6728]
Staging - linux

currently on staging gateways have a tenancy to completely stop working completely

Reproduction by ?????
start round, run it for 30-50 minutes
try gateway
profit?
![Screenshot at 2021-06-05 11-53-43](https://user-images.githubusercontent.com/55299415/120897650-41692000-c5f5-11eb-8149-1ed81071fd14.png)

**Comment by ThatDan123** [comment]
Thats due to the cable missing underneath the reinforced wall above

**Comment by MaxIsJoe** [comment]
This has been fixed in #7489

**Comment by ThatDan123** [comment]
> This has been fixed in #7489

This is a different issue with wiring, might have been fixed now though

**Comment by MaxIsJoe** [comment]
ah whoops
