### ISSUE TITLE
Ghost teleport locations still show newlines

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6732]
![image](https://user-images.githubusercontent.com/14188696/120897820-0ddac580-c5f6-11eb-9fcd-e428f1257daa.png)

**Comment by ThatDan123** [comment]
Think i fixed that in the AI PR, so can wait for that as its not too desperate unless someone really wants to fix it

**Comment by PerfectTangent** [comment]
> Think i fixed that in the AI PR, so can wait for that as its not too desperate unless someone really wants to fix it

the AI has been merged to develop, so can this be closed?
