### ISSUE TITLE
Lavaland cargo doors unresponsive

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6733]
![image](https://user-images.githubusercontent.com/14188696/120897882-572b1500-c5f6-11eb-882a-4b6a56ee4b06.png)

1. play on staging
2. Join late
3. if unresponsive, note that power/unpowered does not fix

**Comment by PerfectTangent** [comment]
does a crowbar work?

**Comment by pyrosshade** [comment]
a crowbar was unable to interact with it

**Comment by ThatDan123** [comment]
Cannot reproduce on staging, might have been the issue with door syncing which was fixed a while ago
