### ISSUE TITLE
Spell buttons remain shown while being ghost/after respawn by admin

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6737]
### Environment
- Game Version: 21060314

### Detailed description of bug

I died and i still have mime spells shown:
![image](https://user-images.githubusercontent.com/22667809/120898728-cc1d3f80-c634-11eb-8e5e-58b7651a4c74.png)

I respawned myself as wiz and have wiz and mime spells shown:
![image](https://user-images.githubusercontent.com/22667809/120898756-f8d15700-c634-11eb-8b88-b9f5fb1e29d9.png)

I respawned myself as assistant and have all previous spells shown (none are working though):
![image](https://user-images.githubusercontent.com/22667809/120898778-17cfe900-c635-11eb-8192-4458f5a35d9a.png)

**Comment by Pockets-byte** [comment]
duplicate of #6735

**Comment by Fogapod** [comment]
Yeah, this is probably the same bug. Wasn't fast enough to post it
