### ISSUE TITLE
I keep spawning as deleted character

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6740]
### Environment
- Game Version: 21060314

### Detailed description of bug

I created a character for testing and joined a few games on staging with it. Now even when I select other characters (no matter which) at round start I spawn as that deleted character.

After admin kicked me I saw this screen:
![image](https://user-images.githubusercontent.com/22667809/120899250-7007ea80-c637-11eb-8043-8b66d929becd.png)

There are 2 old characters in list and first is selected. Sprite shows deleted character though.

Cannot reproduce on local server, only on staging.

### Steps to reproduce

This is how i ended up there, I cannot test if this is 100% repro because i'm stuck with that character now.

1. create character
2. play 1 round (not sure if needed)
3. delete character
4. join new round

**Comment by MaxIsJoe** [comment]
how many times do i got to fix this until this disappears.
![for fucks sake](https://1.bp.blogspot.com/-06NpQFp-Cc0/T8_cfS3LoFI/AAAAAAAABS4/_8SoBCn-bD0/s1600/throwing-computer.gif)

**Comment by corp-0** [comment]
this is still valid for counting even tho it was fixed before the end of the contest.
