### ISSUE TITLE
Supermatter interactions don't work

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6746]
Linux- staging

being pushed or thrown into the supermatter does litterally nothing
as long as you don't move into it, it doesn't do anything
also the hugbox doesn't activate when moved into or coming in contact with an item
![Screenshot at 2021-06-05 15-13-39](https://user-images.githubusercontent.com/55299415/120903004-771c0200-c611-11eb-9a95-d04293a8231c.png)
![Screenshot at 2021-06-05 15-20-40](https://user-images.githubusercontent.com/55299415/120903025-9e72cf00-c611-11eb-9e63-39a95a118ea3.png)
also objects like pianos and stuff don't disintegrate when in contact

**Comment by PerfectTangent** [comment]
closing in favor of #8964.
