### ISSUE TITLE
outpost dorms is missing vendors

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6747]
Staging - linux 

on outpost clothes vendors and things are missing 
![Screenshot at 2021-06-05 15-43-48](https://user-images.githubusercontent.com/55299415/120903830-733eae80-c616-11eb-934c-3774724c6db2.png)

**Comment by corp-0** [comment]
were they there before? Otherwise this looks more like a mapping thing that mappers forgot to add rather than a bug.

**Comment by Pockets-byte** [comment]
I've used them before, so yeah it was a thing at one time

**Comment by PerfectTangent** [comment]
completed by #6857.
