### ISSUE TITLE
High pressure doesn't do damage

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6750]
Linux - staging

currently if you go above a spessman's tolerance for pressure, nothing will happen. you'll take a little bit of brute, leave bloodstains everywhere, and not die
smash 2-3 canisters in enclosed space and use a health scanner 
![Screenshot at 2021-06-05 16-33-58](https://user-images.githubusercontent.com/55299415/120906269-e865b000-c625-11eb-9642-b387c95b6c26.png)

**Comment by PerfectTangent** [comment]
so it dealt a little bit of damage and then stopped?

**Comment by Pockets-byte** [comment]
I think so

**Comment by corp-0** [comment]
it is going up in my case, albeit slowly 
![image](https://user-images.githubusercontent.com/43683714/121761348-2cacf080-cafd-11eb-8e20-2246303caad2.png)

**Comment by corp-0** [comment]
![image](https://user-images.githubusercontent.com/43683714/121761354-3cc4d000-cafd-11eb-927f-b8f6e66a2338.png)

**Comment by Pockets-byte** [comment]
weird. was it fixed?

**Comment by corp-0** [comment]
![image](https://user-images.githubusercontent.com/43683714/121761400-82819880-cafd-11eb-9c57-d4a33fc2b8ba.png)
ded

**Comment by corp-0** [comment]
No one has touched pressure damage, so it is unlikely it was fixed.

**Comment by Pockets-byte** [comment]
confirmed to work on staging as well. just slowly
