### ISSUE TITLE
PDA uplink has some weirdness with certain tabs

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6752]
Linux Staging
the Trator PDA's misc tab acts funky when repeatedly hopped into and out 

1. open pda
2. switch through the various store pages
3. start swapping between misc and other pages

https://user-images.githubusercontent.com/55299415/120908373-a6de0080-c637-11eb-9d71-44c26cfb42b1.mov

**Comment by pyrosshade** [comment]
Related to #6726

**Comment by PetMudstone** [comment]
I was able to reproduce the issue pictured in the video where entries from uplink categories can overwrite entries in other categories that you visit afterwards.
![UplinkOddity](https://user-images.githubusercontent.com/38266309/123384991-eb2f3300-d549-11eb-9b82-f7869075b20e.gif)
