### ISSUE TITLE
Blob stripping

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6753]
Staging linux

On staging blob can use the inspect window to strip players

it's pretty simple. shift-click and click on the equipment items 

https://user-images.githubusercontent.com/55299415/120909373-7a7bb180-c642-11eb-8036-4dca43f8e0ed.mov

**Comment by Pockets-byte** [comment]
also blob ghost sprite is layered underneath everything else
![Screenshot at 2021-06-05 20-33-44](https://user-images.githubusercontent.com/55299415/120909388-a4cd6f00-c642-11eb-8447-144da7599e63.png)
![Screenshot at 2021-06-05 20-33-49](https://user-images.githubusercontent.com/55299415/120909389-a4cd6f00-c642-11eb-9ecd-37156d64b313.png)

**Comment by corp-0** [comment]
so I take this is not intended behaviour

**Comment by Pockets-byte** [comment]
I mean I see no issue with this


lol it's not

**Comment by ThatDan123** [comment]
Pretty sure the stripping only occurs due to you being an admin and since blob is classed as a ghost you can do the admin strip.

But ive fixed the menu popping up in the AI PR as it separates out those special roles more.

**Comment by Pockets-byte** [comment]
Either way it probably shouldn't happen lol

**Comment by MaxIsJoe** [comment]
blob ERP when

**Comment by Pockets-byte** [comment]
Lol
