### ISSUE TITLE
Bells pick-up weird

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6754]
Linux - staging

Bells have some issues
 if you use the radial menu to pick them up they vanish. at least when I tried. 
 
 later bells I spawned stopped ringing
 

https://user-images.githubusercontent.com/55299415/120909424-e8c07400-c642-11eb-9403-2397c8e02394.mov

**Comment by corp-0** [comment]
I could reproduce this error in staging.

**Comment by Fogapod** [comment]
vanishing bells: https://github.com/unitystation/unitystation/issues/5659

**Comment by corp-0** [comment]
oof

**Comment by PerfectTangent** [comment]
yeah, this is redundant with #5659. closing in favour of that issue.
