### ISSUE TITLE
medium machine connectors do not appear to have a in-hand sprite. Thus, your hand appears empty even if it isn't.

### ISSUE THREAD

**Issue by RBDRMoose** [unitystation/unitystation#6755]
### Environment
- Game Version: 21060314
- OS Version: Win 10

### Detailed description of bug

When you pick up a medium machine connector, it does not show up in the hand slot of your inventory, despite disappearing from the game world. This makes it impossible to do anything with that hand until you place the machine connector back down, but if you forget, you could be screwed. The medium machine connector re-appears normally when placed back into the game world. 

### Steps to reproduce

1. Pick up medium machine connector.
2. done
3.

**Comment by JukeJukestar** [comment]
Same applies to low machine connector

**Comment by PerfectTangent** [comment]
should be fixed by #7416. closing.
