### ISSUE TITLE
move broke

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#6759]
### Environment
- Game Version: staging
- OS Version: multiple

### Detailed description of bug

After a short period of time, you get teleported back to your starting location.  This happens repeatedly.

### Steps to reproduce

1. move
2. wait
3. Get teleported back to your starting location.
4. repeat.

**Comment by PetMudstone** [comment]
This was seen on build 21060607. Curiously, locally hosting and connecting to myself as a client didn't create issues for either the host or the client.

**Comment by pyrosshade** [comment]
> 
> 
> This was seen on build 21060607. Curiously, locally hosting and connecting to myself as a client didn't create issues for either the host or the client.

were you hosting headless?

**Comment by PetMudstone** [comment]
No, I was using the launcher. I'll see if I can host headless.

**Comment by potatoalienof13** [comment]
Also, not sure if this is related, you cannot interact with anything that is out of arms reach from the place where it teleports you.

**Comment by Fogapod** [comment]
> Also, not sure if this is related, you cannot interact with anything that is out of arms reach from the place where it teleports you.

That's because you never actually move. Your client thinks you do, but on server you stay at your spawning position.
Climbing on tables/disposals work though,

**Comment by pyrosshade** [comment]
server may be erroring before it can fully receive and process player's new positions

**Comment by PetMudstone** [comment]
Tested on headless. This bug applies there as client.

**Comment by pyrosshade** [comment]
A possible suspect

```
System.NullReferenceException: Object reference not set to an instance of an object
  at Messages.Client.NewPlayer.TileChangeNewPlayer.Process (Messages.Client.NewPlayer.TileChangeNewPlayer+NetMessage msg) [0x0000d] in /root/UnityProject/Assets/Scripts/Messages/Client/NewPlayer/TileChangeNewPlayer.cs:15 
  at Messages.GameMessageBase`1[T].Process (Mirror.NetworkConnection sentBy, T msg) [0x00000] in /root/UnityProject/Assets/Scripts/Messages/GameMessageBase.cs:28 
UnityEngine.Debug:LogError(Object)
Messages.GameMessageBase`1:Process(NetworkConnection, NetMessage) (at /root/UnityProject/Assets/Scripts/Messages/GameMessageBase.cs:32)
Messages.Client.ClientMessage`1:Process(NetworkConnection, NetMessage) (at /root/UnityProject/Assets/Scripts/Messages/Client/ClientMessage.cs:15)
Messages.GameMessageBase`1:PreProcess(NetworkConnection, NetMessage) (at /root/UnityProject/Assets/Scripts/Messages/GameMessageBase.cs:17)
Mirror.<>c__DisplayClass5_0`2:<WrapHandler>b__0(NetworkConnection, NetworkReader, Int32) (at /root/UnityProject/Assets/Mirror/Runtime/MessagePacking.cs:118)
Mirror.NetworkConnection:UnpackAndInvoke(NetworkReader, Int32) (at /root/UnityProject/Assets/Mirror/Runtime/NetworkConnection.cs:194)
Mirror.NetworkConnection:TransportReceive(ArraySegment`1, Int32) (at /root/UnityProject/Assets/Mirror/Runtime/NetworkConnection.cs:232)
Mirror.NetworkServer:OnDataReceived(Int32, ArraySegment`1, Int32) (at /root/UnityProject/Assets/Mirror/Runtime/NetworkServer.cs:598)
IgnoranceTransport.Ignorance:ProcessServerPackets() (at /root/UnityProject/Assets/Mirror/Runtime/Transport/Ignorance/Ignorance.cs:420)
IgnoranceTransport.Ignorance:ProcessAndExecuteAllPackets() (at /root/UnityProject/Assets/Mirror/Runtime/Transport/Ignorance/Ignorance.cs:581)
IgnoranceTransport.Ignorance:Update() (at /root/UnityProject/Assets/Mirror/Runtime/Transport/Ignorance/Ignorance.cs:570)
```

**Comment by corp-0** [comment]
should be fixed in next build, ETA 3 hours. If it did fix it, please close the issue.

**Comment by potatoalienof13** [comment]
Move is no longer broke.  I have been able to run around the station fine.
