### ISSUE TITLE
Buying uplink items without any inventory slots to hold them in causes them to not appear.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6761]
### Environment
- Game Version: Staging 21060607
- OS Version: Windows 10

### Detailed description of bug
When buying uplink items, if you have no empty inventory slots for the item you're buying to fit in then it will not appear at all. This means that buying items without space for them will waste TC. In the case of items not having space for them to fit in your inventory they should just drop on the ground.

### Steps to reproduce
1. Be a traitor or nukie.
2. Access the uplink on your PDA, go to "Stealthy Weapons".
3. Buy as many energy daggers as you can. Notice that after energy daggers fill up your hands and pockets, they won't appear anywhere when you buy them anymore.

**Comment by pyrosshade** [comment]
Now this i can easily sink my teeth into.

**Comment by Bod9001** [comment]
can confirm replicated
