### ISSUE TITLE
item stick to a matrix even if the tiles underneath have been destroyed

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#6762]
items that stay still on matrix should check if moved in new matrix when tile underneath is destroyed

**Comment by pyrosshade** [comment]
Title is clearer than description, but if i have this correctly, items are moving with matrices despite technically seeming like they should belong to space?

**Comment by Bod9001** [comment]
yeah, it's because the registered tile doesn't get constantly updated with position

**Comment by ThatDan123** [comment]
Fixed by #6814
