### ISSUE TITLE
New Memory leak.

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#6763]
### Environment
- Game Version: Staging 21060620
- OS Version: Linux

### Detailed description of bug
Pretty fast moving memory leak.
Started to use 4 GBs in about an hour.

### Steps to reproduce

1. Play the game for some time. 
2. Open a program to watch memory usage.
3. Watch memory usage go up.

**Comment by potatoalienof13** [comment]
I should note that this is a large increase in memory leakage from previous versions.

**Comment by PerfectTangent** [comment]
didn't you say in the discord that the memory usage eventually went down after a while?

**Comment by potatoalienof13** [comment]
Pet Mudstone experienced that, I was not watching for that.

**Comment by PerfectTangent** [comment]
@PetMudstone care to share details about this?

**Comment by PetMudstone** [comment]
From my observations the memory did not rise to significant levels during the one round I played when recording my memory. The big thing here is that I only played a single round which lasted roughly 30 minutes.

**Comment by Aranclanos** [comment]
Left the game runnin for more than an hour, I wasn't able to reproduce this leak.

If possible post more information regarding if the round started, the map, the away mission, if there were players, if there were humans ingame, if the engine was turned on, if atmos was tempered with and basically any interaction that happened during said round by all players.

**Comment by jamessimo** [comment]
Possibly related mem leak
 #4167
#3177

**Comment by Aranclanos** [comment]
Got a profile snapshot from a suspicious morning where there was nobody playing and memory kept going up and up on staging, but I wasn't able to understand it.
Made a thread on unity forums asking about it.

https://forum.unity.com/threads/tree-map-lacking-information-about-memory-leak.1130650/

**Comment by corp-0** [comment]
did we ever confirm we have a mem leak?

**Comment by MaxIsJoe** [comment]
> did we ever confirm we have a mem leak?

Unrelated to the client issue but we def still have a problem server-side because the server still doesn't do well after a round or two and we have to restart the server either automatically or manually to clear performance issues.

**Comment by AtnerNT** [comment]
As far as I know all major memory leaks have now been fixed thanks to the efforts of @havietisov
