### ISSUE TITLE
felinid improper layering

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6764]
Linux staging 

on staging felinids have improper layering for their ears, and possibly tail
ears render behind hair, and tail renders behind clothes and hair
![Screenshot at 2021-06-07 16-07-15](https://user-images.githubusercontent.com/55299415/121081704-158f9b00-c7ab-11eb-9af6-1ab4da2fe765.png)
![Screenshot at 2021-06-07 16-07-20](https://user-images.githubusercontent.com/55299415/121081705-158f9b00-c7ab-11eb-9eeb-9fc64a70a5d5.png)
![Screenshot at 2021-06-07 16-07-24](https://user-images.githubusercontent.com/55299415/121081706-158f9b00-c7ab-11eb-9b63-2d1de932c444.png)
![Screenshot at 2021-06-07 16-08-03](https://user-images.githubusercontent.com/55299415/121081707-16283180-c7ab-11eb-9691-4cd2fba863e0.png)
![Screenshot at 2021-06-07 16-08-14](https://user-images.githubusercontent.com/55299415/121081709-16283180-c7ab-11eb-879f-65a4cbe4d1d7.png)

**Comment by Bod9001** [comment]
checked in editor can confirm, also tale is missing animation

**Comment by jamessimo** [comment]
Lizards tails also are in the wrong place and appear in front of the player

**Comment by ThatDan123** [comment]
Fixed by #6814
