### ISSUE TITLE
Bad mining message for stone

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6768]
### Environment
- Game Version: 21060620

### Detailed description of bug

![image](https://user-images.githubusercontent.com/22667809/121188226-94e7a200-c871-11eb-86c8-7d4e61c549d6.png)

This message is shown both for stone and ores.

This is relatively new, i think 4118 does not have this.

### Steps to reproduce

1. start digging stone with pickaxe

**Comment by pyrosshade** [comment]
good catch, i encountered this too, forgot to make an issue.
This happens without fail on staging

**Comment by PerfectTangent** [comment]
while it was fixed pretty fast, this is valid for the contest.
