### ISSUE TITLE
Light level differs significantly between equipped/held items and items on the ground

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6780]
### Environment
- Game Version: 21060821

### Detailed description of bug

PDA in hands:
![image](https://user-images.githubusercontent.com/22667809/121715147-39bee500-cae7-11eb-9c0c-da4ac186de7b.png)

PDA on ground (dimmer):
![image](https://user-images.githubusercontent.com/22667809/121715230-4b07f180-cae7-11eb-940f-0b98454ca855.png)

firefighter helmet in hands:
![image](https://user-images.githubusercontent.com/22667809/121715356-725ebe80-cae7-11eb-906e-e7c1e4740d89.png)

firefighter helmet on ground (brighter):
![image](https://user-images.githubusercontent.com/22667809/121715387-7d195380-cae7-11eb-995b-fe4a4c1c338c.png)

**Comment by corp-0** [comment]
this one is also old as fug but I didn't find an issue mentioning it, at least not when searching "light"
