### ISSUE TITLE
Non-mainstation shuttles are not showing proper coordinates

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6784]
![image](https://user-images.githubusercontent.com/14188696/121740421-0f5f2e80-cacb-11eb-96d3-009f25d2a990.png)

note in the bottom left the coords from alt-clicking, then note the coords in the piloting console

**Comment by Bod9001** [comment]
confirmed 100, 100 and editor for some reason

**Comment by PerfectTangent** [comment]
https://user-images.githubusercontent.com/68730437/121898121-0f407800-ccf1-11eb-9dba-f47c5446b2e9.mp4

this doesn't appear to be only affecting the ancient station shuttle

**Comment by ThatDan123** [comment]
Fixed by #6814
