### ISSUE TITLE
Shielded hardsuit appears in Uplink despite not being ingame yet

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6789]
Linux -staging

in the nukie uplink, the shielded hardsuit is listed for it's whole price of 30 TC, despite the fact that it doesn't exist currently
meaning that nukies could buy that thinking it was a good item, and spend 1 1/2 times their starting tc on a normal hardsuit

**Comment by PerfectTangent** [comment]
Closing in favour of #6811 so as to be more comprehensive.
