### ISSUE TITLE
nuclear ops bulldozer invisible shots

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6790]
Staging linux
the bulldozer shotgun's shots are completely invisible and silent, making it impossible to gauge

(also it has the stopping power of a fly)

**Comment by PerfectTangent** [comment]
tested, could not reproduce. iirc, this problem was fixed some time ago, but can't find the PR.

also, it seems pretty effective. Killed a fully health unarmored target in 2 shots, which sounds right to me.
