### ISSUE TITLE
New unpowered doors cannot be interacted with one or so second after running into them

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6792]
### Environment
- Game Version: 21061401

### Detailed description of bug

Unpowered door ignores your clicks with crowbar a second or so after bumping into it.
It probably tries to play flashing lights animation or something, but 1) there is no animation shown 2) in situations where there is an animation i don't see why it would block player actions.

### Steps to reproduce

1. touch unpowered door
2. click on it with crowbar instantly

**Comment by PetMudstone** [comment]
Replicated on localhost, 4119, and on staging server.

**Comment by corp-0** [comment]
The last time this was reproduced was long ago, is it still happening?

**Comment by Fogapod** [comment]
yes, nothing changed about door behavior

**Comment by JustinTrotter** [comment]
Confirmed reproducible.

1) unscrew nearby apc 
2) run into powered down airlock
3) Immediately click with crowbar in hand
4) nothing happens
5) wait about 3 seconds
6) try again
7) airlock prys open
