### ISSUE TITLE
Color & vision loss on low blood/health

### ISSUE THREAD

**Issue by jamessimo** [unitystation/unitystation#6793]
### Description
With health version 2 we now loose blood when hurt. It would be good if we could desaturate the screen when your blood dips below the “BLOOD_LEVEL_GOOD” number and keep desaturation it according to your
Blood level. 

Could also add a slight blur if you have recently  let taken a large hit. This may need to wait on the pain system to be built however.

**Comment by PerfectTangent** [comment]
completed in #6832
