### ISSUE TITLE
Smiting yourself as admin sometimes makes the game freak out.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6795]
### Environment
- Game Version: 21061401

### Detailed description of bug

I smited myself as an admin on staging and it kicked me from the game. When I reloaded the first time, my admin tools were gone. I tried relogging and when I did, tons of NREs were being spammed related to the tilemap and the station map was gone.

### Steps to reproduce

mind you, this occurred while I was a client on the staging server. I was not able to reproduce by hosting privately

1. smite yourself
2. get kicked
3. try relogging

**Comment by PerfectTangent** [comment]
might be related to #6734. Idk, I'm spitballing.

**Comment by ThatDan123** [comment]
Should be fixed by https://github.com/unitystation/unitystation/pull/6808
