### ISSUE TITLE
Global Hit Sound

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6799]
Using a toolbox on a windoor causes a global hit sound.

Other objects do it too

1. Get toolbox
2. Hit Windoor
3. Sound will be global, heard anywhere on the server

**Comment by pyrosshade** [comment]
duplicate of #6725

**Comment by corp-0** [comment]
not really. They are related but are talking about different issues. This one in particular is only about glass hit being global.

**Comment by pyrosshade** [comment]
I'll close mine, hit sounds on glass is what it's boiled down to at this point.
