### ISSUE TITLE
Tile Palette Erasure Bug in Unity Editor

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#6823]
### Environment
- Game Version: Doesn't Matter Editor Bug
- OS Version: Windows 10

### Detailed description of bug
Can't erase tiles that you place using the tile palette because of a NRE.
![image](https://user-images.githubusercontent.com/23048385/122634099-a6f1fc00-d11f-11eb-99a2-fc035864515b.png)

### Steps to reproduce

1. Open Tile palette in Unity Editor
2. Attempt to erase a tile on any matrix in a scene

**Comment by NoooneyDude** [comment]
new  NRE

```
NullReferenceException: Object reference not set to an instance of an object
Layer.RemoveTile (UnityEngine.Vector3Int position, System.Boolean removeAll) (at Assets/Scripts/Tilemaps/Behaviours/Layers/Layer.cs:227)
TileManagement.MetaTileMap.RemoveTile (UnityEngine.Vector3Int position, System.Boolean RemoveAll) (at Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169)
LevelBrush.BoxErase (UnityEngine.GridLayout grid, UnityEngine.GameObject layer, UnityEngine.BoundsInt area) (at Assets/Scripts/Tilemaps/Editor/Brushes/LevelBrush.cs:86)
LevelBrush.Erase (UnityEngine.GridLayout grid, UnityEngine.GameObject layer, UnityEngine.Vector3Int position) (at Assets/Scripts/Tilemaps/Editor/Brushes/LevelBrush.cs:43)
```

**Comment by MaxIsJoe** [comment]
I think this has been fixed in the newer versions of unity. We still have the duplicate tiles bug, but the eraser no longer NREs when erasing stuff.
