### ISSUE TITLE
Placing items on Tables no longer places at cursor location

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6824]
### Environment
- Game Version: latest develop as of 6/19/2021
- OS Version: windows

### Detailed description of bug

Attempting to place items on the table places them directly on the center of the tile, items used to be placed based on cursor location.

### Steps to reproduce

1. Have an item in active hand
2. Click on a table

**Comment by NoooneyDude** [comment]
The cause of this bug also directly affects the ability to place wires, because the only node you can select is the centre one.

I believe the cause is a side-effect of #6794.

**Comment by PetMudstone** [comment]
Possibly related, the transparent image of selected items when using the dev spawner tool snaps to tiles now. This doesn't noticeably affect how the spawner works in any negative way so it's not worthy of an issue. I do not recall seeing that behavior before, however.

**Comment by Aranclanos** [comment]
I'll fix it today dw I'm almost sure that its a copypaste mistake that I made
