### ISSUE TITLE
Disposal pipes cannot be secured onto nor unsecured from catwalks.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6835]
### Environment
- Game Version: Staging 21062001
- OS Version: Windows 10

### Detailed description of bug
Disposal pipes cannot be secured onto catwalks. This means that the only way to build disposal pipes outside the station is by using base floor tiles as catwalks cannot be used to hold disposal pipes. 
~~Disposal pipes also cannot be unsecured from catwalks. This can be seen in Squarestation, which has disposal pipes appearing outside the station on catwalks. The fact that they cannot be removed from catwalks also makes the catwalks unremovable.~~ Fixed in #6909.

### Steps to reproduce
For inability to secure disposal pipes to catwalks.
1. Obtain a disposal pipe section, either from under the floor tiles or from a pipe dispenser.
2. Drag the disposal pipe onto a catwalk in space.
3. Attempt to secure the disposal pipe using a wrench. Fail.
For inability to unsecure disposal pipes from catwalks.
1. Go to Squarestation.
2. Go outside (preferably with a spacesuit) one of the disposal pipes on a catwalk.
3. Attempt to unsecure the disposal pipe with a welding tool. Fail.

**Comment by NoooneyDude** [comment]
~~Were you using a welder first, for deconstruction?~~

Edit: nvm
