### ISSUE TITLE
Cannot put wrapping paper inside a backpack or any other wrappable container

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6840]
### Environment
- Game Version: latest

### Detailed description of bug

if you try to place a roll of wrapping paper inside a backpack on help intent, you begin to wrap the backpack, even if the backpack is equipped. If you use any other intent, nothing happens.

### Steps to reproduce

1. get a roll of wrapping paper
2. try to put it in the backpack
3. observe how none of the intents have the desired effect of stowing the wrapping paper in the backpack.

**Comment by corp-0** [comment]
lol, I never thought of that use case.

**Comment by pyrosshade** [comment]
If backpack is in itemslot?

**Comment by PerfectTangent** [comment]
in the slot or in hand

**Comment by corp-0** [comment]
how can we solve this? Do we want to always store in backpack?

**Comment by PerfectTangent** [comment]
this wasn't actually completed with #8303, was it? That PR only allowed wrapping paper to be placed inside equipped clothing, so it doesn't complete the still existing problem of placing wrapping paper into non-equippable items like boxes. Or am I wrong about this?

**Comment by mmails** [comment]
> Players are no longer able to wrap items that are equipped like backpacks, instead they must be taken off to be wrapped, fixing the annoying issue of wrapping your backpack when trying to stow items.

Seems like Atner fixed it

**Comment by PerfectTangent** [comment]
a box cannot be equipped.

**Comment by corp-0** [comment]
how would you handle that case? With a different intent?

**Comment by PerfectTangent** [comment]
I guess we need to add 2 more intents; wrap and unwrap. /s

**Comment by AtnerNT** [comment]
maybe we change wrapping paper to only wrap on an alt click - similar to alt clicks are used to change air injector modes

**Comment by corp-0** [comment]
that sounds like a solution
