### ISSUE TITLE
Random item spawners should work with cargo crates, syndicate uplink and admin spawning tool. B: 60

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6851]
### Description

Currently, if you place a random item spawner inside of a cargo crate that is purchaseable in the cargo console, when the crate arrives on the cargo shuttle, the random items will not spawn inside the cargo crate. They do not have sufficient logic support spawning inside of objects except on initialization of the map. Photo for reference:

In addition, if an admin were to select a random item spawner from the admin spawning tool, it does not successful generate a random object. Spawners should also work with the syndicate uplink and and container storage populators. Random item spawners would be a lot more useful and flexible if they could work intuitively in these situations.

## What is needed to fulfill the bounty:

- [x] random item spawner items should spawn inside of cargo crates when purchased from the cargo console.
- [x] random item spawners should work with the admin spawning tool.
- [x] random item spawners should work with storage populators
- [x] random item spawners and pools should spawn the item in player hands like other syndicate uplink items when purchased from the uplink.

example screenshot of how random item spawners are currently not compatible with cargo crates bought from the cargo console:
![Screenshot_2021-06-21_151856](https://user-images.githubusercontent.com/68730437/123289947-dec1c080-d4de-11eb-8f5b-bfb44a685628.png)

**Comment by PerfectTangent** [comment]
This issue has been promoted to bounty status, valued at 40 USD.

**Comment by PerfectTangent** [comment]
bumping this to 60

**Comment by VernaSaurus** [comment]
I'll do this

**Comment by VernaSaurus** [comment]
The random item spawners appear to work just fine with the admin spawner tool.
