### ISSUE TITLE
Add a test dummy for health testing

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#6853]
Description : 
Add a testing dummy humanoid for health testing, include all races.

**Comment by MaxIsJoe** [comment]
There is one actually but it's incredibly broken and isn't customizable or spawnable outside the editor

**Comment by Aranclanos** [comment]
its editor only or if you're the server I dont remember, its super old, press F7.
I use it all the time!

**Comment by PerfectTangent** [comment]
there can be improvements that can be made to the dummy system, but since we have a test dummy, this issue is redundant. Closing.
