### ISSUE TITLE
The cryptographic sequencer/emag needs to be usable on V2 doors.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6879]
### Description
The cryptographic sequencer does not work on V2 doors at the moment, which makes it quite less useful. It should force open normal airlocks unless they are bolted shut, in which case they cannot be unbolted and forced closed.

**Comment by ThatDan123** [comment]
Done in #6936

**Comment by PetMudstone** [comment]
Testing in 21081300, emags don't work on doors again.

**Comment by PetMudstone** [comment]
Did some testing and notably while emags don't work on doors in 21081300, they do in 4121(localhost at least, didn't wnat to disrupt Solidarity player round)
