### ISSUE TITLE
windows are rendering over posters and wallmounts

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6881]
### Detailed description of bug

Windows are rendering over most other objects, including posters, light switches, wallmounts, and other objects that should be rendering above windows.

![Screenshot 2021-06-29 225223](https://user-images.githubusercontent.com/68730437/123895038-32903780-d92d-11eb-8374-cb805062ec4e.png)

this problem exists in game and in editor.

**Comment by PetMudstone** [comment]
Would it be possible to get a comprehensive list?

**Comment by PerfectTangent** [comment]
Do you have a way of making the list in mind, because I can't sit here and try every prefab under the sun.

**Comment by PetMudstone** [comment]
Fair enough. I'll just test with the various wallmounts.

**Comment by NoooneyDude** [comment]
All this requires is that new layer component added to the prefab. Do the wallmounts have a common base? I've done this for air alarms locally to good effect.

**Comment by PetMudstone** [comment]
> 
> 
> All this requires is that new layer component added to the prefab. Do the wallmounts have a common base? I've done this for air alarms locally to good effect.

For posterity, the "new layer component" in question is the Sorting Layer component. It works similarly to the sorting layer settings on the Sprite Renderer component.
