### ISSUE TITLE
4119? build kicks players for invalid name

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#6893]
I don't know if its strictly related to 4119 or solidarity, either way thats the message the client receives after being kicked. It doesn't happen to me.

**Comment by corp-0** [comment]
in all honesty, remove the check until we do a proper, generic and robust validation of data

**Comment by craftxbox** [comment]
This bug appears to related to the config.json file not containing the required values, Namely the character name limit. Some form of configuration updating would likely be a good thing to work on.

**Comment by Bod9001** [comment]
Posted a fix to 4119  stable branch

**Comment by ThatDan123** [comment]
Check was disabled in develop by #6936

**Comment by PerfectTangent** [comment]
if the check has been disabled and that changed has been ported to the 4120 branch, then I think this issue can be closed.
