### ISSUE TITLE
Clients can't pick up their survival box

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#6894]
![image](https://user-images.githubusercontent.com/701959/124040791-f962d080-d9db-11eb-91b3-de2c1170abed.png)
when clicking on the box this error shows up and nothing happens

![image](https://user-images.githubusercontent.com/701959/124040865-20210700-d9dc-11eb-867e-857171e2c263.png)
when click and dragging to a hand slot, clicking on the box works but it shows up as empty

**Comment by Fogapod** [comment]
https://github.com/unitystation/unitystation/issues/6968
isn't this the same bug? i don't quite understand without clear reproduction steps

**Comment by Aranclanos** [comment]
it was fixed
