### ISSUE TITLE
When I was cloned, my Ui was doubled. (Edit: The new UI is just completely broken)

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#6896]
### Environment
- Game Version: 21063016
- OS Version: Windows 10

### Detailed description of bug

I tried going into space with a full EVA and 02 setup when I found that the 02 sprites where glitched and the EVA did not work. When I was cloned and went to grab my items from my dead body, instead of the normal dead body screen appearing my entire UI was doubled. My items were in the secondary UI but it seems that I somehow doubled my backpack? It's just very glitchy. I tried to walk away from the body to see if it was the body's inventory, but it did nothing.

Edit: You get a new UI every time a round restarts and if you try to reset everything goes blank. Why did the Ui even have to change...

![image](https://user-images.githubusercontent.com/85035862/124049654-9b83b800-d9de-11eb-90eb-d3d2d95f5f32.png)

### Steps to reproduce

1. Reset your game or start a new round
2. After resetting you should have a second UI which is just glitched and hides items.
3. When you reset to remove your extra UI(s) you get no Ui until a new round starts.
4. It also happened after I was cloned once.

**Comment by LoliWatcher** [comment]
I just reset a map in US13, and it was doubled. idk what causes it.

**Comment by Bod9001** [comment]
"Why did the Ui even have to change..."
to support dynamic bodies, since every UI element is linked to body part /clothing

**Comment by ThatDan123** [comment]
Should be fixed by #6935
