### ISSUE TITLE
Spacesuits and hardsuits no longer protect you from atmospheric hazards.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6899]
### Environment
- Game Version: Staging 21063016
- OS Version: Windows 10

### Detailed description of bug
Spacesuits and hardsuits no longer protect their wearers from pressure and temperature, most particularly the low pressure and temperature found in space. This makes them useless for spacewalks.

### Steps to reproduce

1. Find a spacesuit or hardsuit.
2. Go outside into space.
3. Notice that you get pressure and temperature warnings. Start dying to low pressure and temperature.

**Comment by Bod9001** [comment]
fixed in #6901
