### ISSUE TITLE
Running out of locker removes shroud and makes health bar green B: 10

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#690]
# Preliminary information

## Category
BUG

## Bug: Release or Dev?
Latest Dev

# Report
## Current Behavior
Running out of locker resets some of the health indicators

## Expected/Wanted/Requested Behavior
Lockers shouldn't have anything to do with it at all

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. Get some damage
2. Get into the closet and close yourself
3. Move out of closet with directional keys

# Other

## Notes:
![gif](https://user-images.githubusercontent.com/10403536/34200234-5b3b788c-e581-11e7-96d6-8def13895568.gif)

**Comment by DooblyNoobly** [comment]
Weird, possibly something odd in VisibleBehaviour

**Comment by DooblyNoobly** [comment]
Criteria:

   - Make sure CritOverlay and health indicators are not affected after leaving a cupboard

Bounty: 10 usd paid via paypal on successful merge
