### ISSUE TITLE
"<color=yellow>" appears before non-antagonist player names when the admin player overlay is enabled.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6920]
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
Non-antags when the admin's player overlay is enabled have "<color=yellow>" appear before their names. Presumably this is related to how antagonists have yellow text in the overlay to immediately distinguish them.

Non-antag in overlay:
![image](https://user-images.githubusercontent.com/38266309/124344888-163d0680-db8a-11eb-993b-e6456d739125.png)

Antag in overlay:
![image](https://user-images.githubusercontent.com/38266309/124344891-1fc66e80-db8a-11eb-97d7-0c80e39cde8f.png)

### Steps to reproduce
1. Launch a build of Unitystation from the Installations tab so you can be an admin. Start a game.
2. Make sure that you spawned as a non-antag. If you spawned as an antag log out and start a new game.
3. Click this button on the top of the screen to activate the player overlay. 
![image](https://user-images.githubusercontent.com/38266309/124344739-f527e600-db88-11eb-9381-2b5266d0af2a.png)
4. Look at your character and notice that "<color=yellow>" appears before your name.

**Comment by ThatDan123** [comment]
Fixed in #6927
