### ISSUE TITLE
Becoming bald after equipping hardsuit helmet

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#6925]
![losing hair gif](https://user-images.githubusercontent.com/701959/124358049-de1edd80-dbf4-11eb-8f5e-3271d6b20745.gif)

tested on latest develop on editor

**Comment by MaxIsJoe** [comment]
Tested it, does not happen anymore.

**Comment by PerfectTangent** [comment]
Going to close this issue, as I can't reproduce either. It's likely (hopefully) been fixed.
