### ISSUE TITLE
cargo Techs should have access to cargo consul in case of no QM

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#6929]
self-explanatory

**Comment by CdrCross** [comment]
This is already the case as of the 29th of January 2022. This issue should be closed.

**Comment by PerfectTangent** [comment]
> This is already the case as of the 29th of January 2022. This issue should be closed.

I don't know of any PR that has added such a feature. Currently the console just grants cargo techs access always.


![Screenshot 2022-01-30 092110](https://user-images.githubusercontent.com/68730437/151703659-3f9cbc25-d343-4a4d-b3bb-67104fe2980f.jpg)

**Comment by AtnerNT** [comment]
I think this could be considered closed by #8599 if it wasn't already.
