### ISSUE TITLE
Player Camera does not follow people who are in wrapped up lockers.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6937]
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
If the locker you are in is wrapped up, then the camera will no longer follow you and will stick to the tile where the locker was when it got wrapped. If the locker you are in is unwrapped then the camera will return to your position. Additionally, if you try moving while in the wrapped up locker you will appear from its current position, exiting it, and the camera will return to you as well.

Below, camera is fixated on the tile right of the oxygen locker while the player is in the wrapped up locker that the captain is dragging.
![image](https://user-images.githubusercontent.com/38266309/124404639-9b423000-dcf0-11eb-813c-54be687eb186.png)

### Steps to reproduce
1. Have someone put you in a locker and have wrap the locker up with wrapping paper.
2. Have the locker be moved, The camera will not move from the tile where the locker was wrapped up.
3. Move. You will appear from where the wrapped up locker currently is.

**Comment by corp-0** [comment]
after Aran's changes with PushPull, this one needs reproduction

**Comment by PetMudstone** [comment]
I can still reproduce this on 21090215.

**Comment by PerfectTangent** [comment]
need verification that this bug still exists after the closet refactor

**Comment by PetMudstone** [comment]
Tested on Staging 21101813. Was able to replicate successfully. Camera continues to not follow people if they are in wrapped-up lockers.

**Comment by corp-0** [comment]
I'd consider this game breaking now since you're spaced when inside a wrapped locker. Bumping the priority to high and adding to the big bugs project

**Comment by pyrosshade** [comment]
Working on this

**Comment by corp-0** [comment]
Thank you! I assigned you.
