### ISSUE TITLE
Multiple ore overlays can appear on one rock wall.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6940]
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
Sometimes, rock walls will have multiple ore overlays on them. When mined, they only drop one of the shown ores.
![image](https://user-images.githubusercontent.com/38266309/124407746-87e79280-dcf9-11eb-8ac2-9c0daa82f67d.png)
![image](https://user-images.githubusercontent.com/38266309/124407751-8ae28300-dcf9-11eb-9863-6ffcb51c076a.png)

### Steps to reproduce
1. Go to an asteroid or lavaland.
2. Start digging rock walls until you find a rock wall with multiple ore overlays.
3. Mine the rock wall in question, only one ore will drop.

**Comment by PerfectTangent** [comment]
is this still a problem? iirc, ore generation weirdness had a fix merged.

**Comment by ThatDan123** [comment]
Does still happen

**Comment by MaxIsJoe** [comment]
this doesn't happen anymore
