### ISSUE TITLE
Lack of proper cyborgification 

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#6949]
### Environment
- Game Version: Staging 21070515
- OS Version: Arch Linux

### Detailed description of bug

As of right now is possible to make all parts of a cyborg and attach them to a human, problem resides in the fact that removing the brain, head and heart results in immediate death with no way to bring back to life.

the only way too properly attach the cyborg torso and head without killing you is to put them on top of your original head/torso
resulting in 2 torsos and 2 heads in the process, here's a funny human nose sticking out of a cyborg head
![nose](https://user-images.githubusercontent.com/80334192/124512895-0e1eda00-ddc9-11eb-832f-e2013aac0fb0.png)

also cyborg heads should not have hair.

### Steps to reproduce

1. Start surgery with cyborg head or torso
2. directly start with attaching the limb 
3. surgery is done and now you have 2 heads or 2 torsos

**Comment by Cboyjet4** [comment]
The entire cyborgification system rn doesn't make any sense, and isn't faithful to the OG ss13 system, IMO proper cyborgification should just be added instead of this (if this system is even intentional for a long term system)

**Comment by PerfectTangent** [comment]
it's just using cyborg parts as prosthetics. It's not meant to serve as a gameplay replacement for traditional cyborgs. Pet added it because having prosthetics available is useful.

**Comment by NoooneyDude** [comment]
Yep. This is a feature request.

Edit: should probably create a second issue for the mentioned sprite issues.

**Comment by AtnerNT** [comment]
Cyborgs have been added aswell as the ability to transplant brains allowing you to remove human heads.
