### ISSUE TITLE
Toolbelts and backpacks are broken

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#6961]
### Environment
- Game Version: Staging 21070515
- OS Version: Windows 10

### Detailed description of bug

Toolbelts/backpacks(satchels,etc) will not work, they won't display the items that are in said backpack (atleast for me, the only way i got backpacks to work was by unequipping them, placing them on the floor, grabbing them and opening them in my hand slot)

### Steps to reproduce

1. Grab a backpack
2. Wear it on your backpack slot
3. Place whatever item inside
4. Items will not show inside of backpack

**Comment by Fogapod** [comment]
could be a part of #6968, which is fixed now

**Comment by Aranclanos** [comment]
This exact issue was fixed, backpacks/containers still have the issue not opening properly, but refer to that issue here #7002
