### ISSUE TITLE
You MUST have ID or PDA equipped in order to open airlock with crowbar

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6970]
### Environment
- Game Version: 21070613

### Detailed description of bug

You can close airlocks without ID, but not open. Nothing happens on any intent. There are no errors.

### Steps to reproduce

1. unequip ID
2. click on closed airlock with crowbar
3. equip ID or PDA with ID inside into ID slot
4. click on closed airlock with crowbar

**Comment by corp-0** [comment]
I guess what is happening here is access module interrupting the chain even though it should pass when unpowered. I will investigate.

**Comment by PetMudstone** [comment]
Connected to staging, wasn't able to replicate even with doors which I didn't have access for.

**Comment by Fogapod** [comment]
can reproduce on staging 100% of the time

https://user-images.githubusercontent.com/22667809/125331385-97e22080-e350-11eb-901d-c28d9b79d86b.mp4
