### ISSUE TITLE
Putting your ID card in your PDA could use text feedback.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6971]
### Description
Title. Putting your ID card in your PDA doesn't create a message in chat stating as such. This might confuse new players when they use their ID card on their PDA and it seemingly dissappears.

**Comment by NoooneyDude** [comment]
I've added the sounds label too, as I think in /tg/ a sound is played when the ID card is inserted or ejected.

Perhaps the sounds alone would be enough of a hint? Heck, we could probably do a lil' tweening to show an ID insertion / ejection animation.
