### ISSUE TITLE
Piles of soil don't render anymore.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6975]
### Environment
- Game Version: Staging 21070613
- OS Version: Windows 10

### Detailed description of bug
Piles of soil, which act as hydroponics trays minus the handy notification overlays, no longer have their sprites render. Therefore, they are invisible unless you mouse over them with highlight turned on, which then shows their sprite. Or you can right click on the tile they are on to show them in the radial menu, where they will use the normal hydro tray sprite.
Notably, the soil piles do not appear invisible in the scene view on maps nor when viewed via having their prefabs opened in editor.

### Steps to reproduce
1. Go to the room left of Boxstation's tool room, the one with the cultivators and seed vending machine.
2. Right click on the grass tiles, the radial menu will show that there are piles of soil on them but they will be invisible normally.

**Comment by AtnerNT** [comment]
Fixed in #9419
