### ISSUE TITLE
Backpack no longer opens correctly

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#7002]
### Environment
- Game Version: Latest staging build
- OS Version: Mac 

### Detailed description of bug

The backpack can no longer be opened by clicking on it and can only be opened by using alt click.

### Steps to reproduce

1.  Join the current staging build
2. Click your backpack
3. Find that clicking your backpack no longer properly opens it/displays the items it currently holds

**Comment by JukeJukestar** [comment]
Had the same issue, for me the backpack was always put into my hand instead.
