### ISSUE TITLE
Smiting yourself disconnects you from the server.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7009]
### Environment
- Game Version: Staging 21070919
- OS Version: Windows 10

### Detailed description of bug
When you smite yourself as an admin, you will be forcibly and suddenly disconnected from the server. Rejoining the server causes you to spawn as a new character and removes your admin powers. This to only seems to occur when connected as a (headless) client* and not as a host. This bug doesn't occur on 4119.

*I was only able to test while connected to headless servers since connecting to a server hosted from a build launched from the Station Hub doesn't give the client working admin.

### Steps to reproduce
1. Follow the steps [here](https://unitystation.github.io/unitystation/development/Hosting-a-Server/) to host a headless server. 
2. Go to the Station Hub's Installations tab and launch the same build you are using for the headless server.
3. Connect to the headless server from your Unitystation instance. You should have admin abilities.
4. Smite yourself. Watch as you get kicked from the server.

**Comment by Aranclanos** [comment]
Can't preproduce, its old and I did a lot of fixes and organization regarding organ removal/addition so I can assume it's fixed. If it's still present, do say and we'll open the issue.
