### ISSUE TITLE
Clicking on disposal bins with items doesn't put them in as client.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7014]
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
When you click on a disposal bin with an item as a client, the item will not go in. This means that the only way to dispose of items as a client is to throw them at the disposal bin, and the RNG associated with throwing items in the disposal bin means that items may not always go in.

### Steps to reproduce
1. Connect to a server.
2. Find a disposal bin.
3. Click on the disposal bin with an item. The item will not go in.

**Comment by Fogapod** [comment]
You must use harm intent to put items inside. Don't know if this is bug or feature, but it's been like this for a while
