### ISSUE TITLE
Typing in certain admin UI chat boxes opens comms channels

### ISSUE THREAD

**Issue by JukeJukestar** [unitystation/unitystation#7037]
### Environment
- Game Version: Any Version, Latest Staging Build
- OS Version: Windows 10

### Detailed description of bug

Finally figured out what triggers this. Spess bless.

While typing in admin tools such as ahelp, bans or job bans, chat hotkeys and movement keys are disabled for obvious reasons. However, this is broken. When you open a text window, say, a job ban, and click into the text box and type you stop controlling your character for obvious reasons.
However, if you open a second admin window, say, the ahelp menu any type a message, then close that second window again and then try to type into the job ban text box, the "control override" is gone again and whenever you type a "t"; a "u" etc. it opens the associated comms channel and throws you out of the text field. W A S D also controlls your character, which is why admins typing in admin menus can sometimes be seen spazzing around moving in random directions when they type said buttons.

Im not a coder by any degree but to me it seems like the "Dont use hotkeys" check thing is activated when you open a UI text field and disabled when you close it, but if you open two and close one it disables anyways even though one is still open.

### Steps to reproduce

1. Open a Player Job ban
2. start typing out letters into the text field
3. get an ahelp, open the ahelp menu and write them that no, they cant plasma bomb
4. close the ahelp window
5. start typing in the job ban window again
6. whenever you press "u" "t" etc you go into said comms channel and have to close it,, select the job ban windows text box again and repeat whenever you press "u" or "t" again
7. cry in agony as you have to retype everything because there is no way you can finish it like this

**Comment by NoooneyDude** [comment]
Thanks for the troubleshooting. I think you are spot-on.

One solution is that input blockers should register themselves. Could be as simple as a list. When the criteria for releasing control is met, it first checks if there are other blockers before allowing input again.

Does this occur with other windows, such as two paper UIs open?

**Comment by JukeJukestar** [comment]
Yes, it also happens when you try to write on two papers at once. Doesnt happen with Comms consoles and ID consoles. Also it doesnt seem to happen as a player when you open both ahelp and mhelp.
