### ISSUE TITLE
Empty search bar in admin spawn menu leads to extreme lag

### ISSUE THREAD

**Issue by JukeJukestar** [unitystation/unitystation#7038]
### Environment

- Game Version: Latest Staging version, any other version before that
- OS Version: Windows 10 

### Detailed description of bug

Currently, when the admin spawn menu is opened, it is empty until you type something in the search bar. However, if you remove what you previously wrote in there or hit enter while the bar is empty, it loads every single item in the game into the spawn menu, leading to the game freezing for at minimum ~5 seconds.

Fix this by having it display no items if the search bar is empty.
I realize that there is some usefulness to being able to view every spawnable item in the game, but the lag is just unbearable.

### Steps to reproduce

1. Open Admin spawn menu
2. Search up "corgi" and spawn one
3. remove the word "corgi" from the search bar and realize what you have just done
4. wait while the game is frozen for what feels like eons while it loads everything spawnable

Related to #5640

**Comment by Pockets-byte** [comment]
I could swear this was fixed

**Comment by JukeJukestar** [comment]
Oh, just checked and its fixed in the newest build. neat. How do I close this?

**Comment by DTraitor** [comment]
There should be a button to close near comment
