### ISSUE TITLE
Light bulbs and light tubes on walls that face right have broken sprites/

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7050]
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
When light tubes or light blubs are facing rights (and are one the right side of a wall) their sprites break. The light fixture itself will be facing south while the light overlay will be facing right. Notably, changing the direction to another one and back to right will seemingly fix the sprite in editor but they seem to break again once you save the scene or revert any change to the light tube.

![image](https://user-images.githubusercontent.com/38266309/125672412-3b3ae709-76da-489e-94dc-c4335782c810.png)

### Steps to reproduce
1. Find a light tube that's facing right.
2. Notice that the sprite is broken as seen above.

**Comment by PetMudstone** [comment]
I believe this might be related to how the light tubes don't use the directional sprite component.

**Comment by PerfectTangent** [comment]
Seems to have been satisfactorily fixed by #8179. closing.
