### ISSUE TITLE
Moth Character Creation

### ISSUE THREAD

**Issue by TheDoktorZ** [unitystation/unitystation#7069]
### Environment
- Game Version: 21072023

### Detailed description of bug
Moths lost the antennae choose and edit option and got human hair and facial hair buttons instead. Any old character what already had antennae in the past got white hair and beard.

### Note:
It was fixed for 4120 and originally I reported this for 21071513, but it's messed up again, You keep messing it up.    :(

**Comment by NoooneyDude** [comment]
I haven't seen this issue while working on #9654 and #9703, so this can be closed, unless reproduction steps can be provided.
