### ISSUE TITLE
PowerLightsRelatedTests could use cordinates for violating objects.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7092]
### Description
![image](https://user-images.githubusercontent.com/38266309/126225741-a072d48c-8964-43f5-a1ea-7be78066b0b6.png)
All the "LightTubeFixture" instances share the same name and are all in a scene with dozens of other instances with the same names. They would be easier to find and identify if they had their transform values appended the messages mentioning them.

**Comment by SluggyWuggies** [comment]
I will attempt to do this and probably not we shall see.
