### ISSUE TITLE
Text string error

### ISSUE THREAD

**Issue by Poea** [unitystation/unitystation#71]
`blob:http://doobly.izz.moe/e08a81f5-904d-4445-9e39-aadd09c39896:1 String too long for TextMeshGenerator. Cutting off characters.
 
(Filename:  Line: 226)
`

**Comment by DooblyNoobly** [comment]
@Poea was this happening when someone decided to spam the chat with a really long username? We are going to place a char limit for username and chat in the next update

**Comment by DooblyNoobly** [comment]
char limits have been set
