### ISSUE TITLE
Refactor all uses of serializable dicts to make use of generics

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7111]
### Description
Before Unity supported serializing generics, in order to use Serializable dictionaries we had to create child classes of a particular type pair and expose that class to the inspector. That is no longer needed and we can use ``SerializableDictionary<Type, Type>`` directly.

### To solve this issue
1. Add ``[Serializable]`` decorator to ``SerializableDictionary<TKey, TValue>``  from ``SerializableDictionary.cs``.
2. Find inheritors of ``SerializableDictionary<TKey, TValue>`` from ``SerializableDictionary.cs``.
3. Replace all inheritors usage with a direct usage of ``SerializableDictionary<TKey, TValue>`` from ``SerializableDictionary.cs``. For example, ``DemandDictionary`` from ``CargoBounty.cs`` replaced with ``SerializableDictionary<ItemTrait, int>``

**Comment by Aranclanos** [comment]
caution with SerializableDictionary they can generate large amounts of gc and cpu usage

**Comment by corp-0** [comment]
Would replacing the classes that inherited SerializableDictionary with just using generics increase the gc? I’d think in the end it will be the same, but with less classes polluting the project.

**Comment by davodico** [comment]
Hi there!  I would like to take it and contribute. Could you assign it to me? Thanks.

**Comment by corp-0** [comment]
Sure thing, I have assigned you
