### ISSUE TITLE
Loud headsets for Heads of Staff

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#7119]
### Description

I am unsure of their name on /tg/, but they were headsets that made your radio chatter 2 times as bigger, thus making your messages more noticeable. (And more annoying)

**Comment by JukeJukestar** [comment]
maybe it should just make their text bold

**Comment by mmails** [comment]
> maybe it should just make their text bold

Would work aswell

**Comment by MaxIsJoe** [comment]
Can you not close issues before they're fully solved?
