### ISSUE TITLE
Trying to make/edit character whiles not logged in causes a lot of NREs and breaks UI

### ISSUE THREAD

**Issue by jamessimo** [unitystation/unitystation#7120]
### Environment
- Game Version: latest dev
- OS Version: MacOS Catalina 

### Detailed description of bug
When you are not logged in you can still access the create character menu. When you try to do this none of the buttons work and the console gets filled with NRE ‘s.

To re-create just go onto staging load up the game and then log out of the game. Try to edit the character and you’ll notice you can’t get to the edit character screen. Check the console
 and you’ll see NRE errors in there.

**Comment by MaxIsJoe** [comment]
Nooney is working on Django Auth integration so this is a `wont fix` issue until he finishes working on it

**Comment by MaxIsJoe** [comment]
I think this has been fixed finally with the inclusion of offline mode recently

**Comment by NoooneyDude** [comment]
If this wasn't already fixed, #9654 or #9711 would have fixed this, so we can close it.
