### ISSUE TITLE
You can't pick up atmospheric analyzers on the ground by left clicking them.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7131]
### Environment
- Game Version: Staging 21072512 & Production 4120
- OS Version: Windows 10

### Detailed description of bug
When you left click on atmospheric analyzers on the ground with empty hands, you won't pick them up. Notably, you can still pick them up by using the right click menu.

### Steps to reproduce
1. Find an atmospheric analyzer.
2. Click on it with an empty hand, you won't pick it up.
3. Right click on it and choose the pick up option. You will pick it up then.

**Comment by corp-0** [comment]
does anything happen when you click them? Sounds like an issue with WillInteract, like the old problem we had with bike horns.

**Comment by PetMudstone** [comment]
> 
> 
> does anything happen when you click them? Sounds like an issue with WillInteract, like the old problem we had with bike horns.

Nothing as far as I could tell. I did not receive any chat messages relating to atmospheric analysis.

**Comment by PetMudstone** [comment]
Fixed by #7308. Closing.
