### ISSUE TITLE
Facehuggers don't change sprites after they successfully infect someone and die.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7132]
### Environment
- Game Version: Production 4120
- OS Version: Windows 10

### Detailed description of bug
Title. Facehuggers don't change sprites after they latch onto someone's face die after successfully impregnating them. This can result in terror and confusion when a dead facehugger continues to wiggle about as if still alive.

### Steps to reproduce
1. Get impregnated by a facehugger.
2. After you get back up after being knocked down, examine the facehugger to see its dead description.
3. Notice that the dead facehugger is still wiggling.

**Comment by corp-0** [comment]
ah shit, I thought this was fixed long ago.
