### ISSUE TITLE
You can't melee attack alien eggs.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7133]
### Environment
- Game Version: Production 4120
- OS Version: Windows 10

### Detailed description of bug
Title. Clicking on alien eggs always produces the "It feels slimy" message even if you're on harm intent and have a weapon in your hand. This makes it somewhat inconvenient to get rid of eggs, which block movement.

### Steps to reproduce
1. Find an alien egg. Click on it to squish it if it's already opened.
2. Click on it again on harm intent. You will receive the "It feels slimy" message.

**Comment by corp-0** [comment]
this one should be easy to fix, the interaction is probably not checking for intent.

**Comment by tomasfrankovic** [comment]
Hi, I would like to help with this project and I think I could start with this issue 🙂, can someone help me out here?

**Comment by corp-0** [comment]
Hi, what do you need help with specifically? We don't mind walking you through the initial setup of the project, we normally help people on discord so if you have a discord, join our server and make as many questions as you wish

**Comment by PerfectTangent** [comment]
Take a look at our contribution guide to see how to get started: https://unitystation.github.io/unitystation/contribution-guides/Starting-contribution/

Here is a link to the discord server: https://discord.gg/wS7Ab7DH
