### ISSUE TITLE
Damage to feet and hands does not pass to legs and arms

### ISSUE THREAD

**Issue by Lizurt** [unitystation/unitystation#7139]
### Environment

- Game Version: Latest staging
- OS Version: Windows 10

### Detailed description of bug

Humans can choose hands and feet on the health doll. Damage to feet and hands does not pass to legs and arms

### Steps to reproduce

1. Select any hand or foot.
2. Attack yourself
3. You didn't take any damage

**Comment by PerfectTangent** [comment]
> Hands don't exist in a list of organs. HasBodyPart() returns false. Feet and hands don't receive damage.

Intended. We had a discussion in the health channel a while ago. We decided that it was not necessary to break arms and legs into sub components.

Hands and feet are like the groin. If you attack them, it counts as hitting the body part they are attached to. 

Closing.

**Comment by Lizurt** [comment]
> If you attack them, it counts as hitting the body part they are attached to.

Okay, but arms/legs don't take damage when attacking hands/feet. And at the same time they can be selected on the doll at the bottom right.

> We decided that it was not necessary to break arms and legs into sub components.

So hands and feet don't exist as organs? If yes then why would they exist as an enum and can be selected on the doll?

**Comment by Lizurt** [comment]
Reopen this issue please, there is still a bug here. We discussed it with PerfectTangent and Bod9001 in the #health discord channel.
