### ISSUE TITLE
no damage trough space [map: fallstation]

### ISSUE THREAD

**Issue by ridernametaken** [unitystation/unitystation#7151]
### Environment
- Game Version:  21072512
- OS Version: windows10pro

### Detailed description of bug

i am unsure if this was lag based, but when i exited the airlock on fallstation holding my hardsuit in my hand i took no damage trough the lack of atmosphere

### Steps to reproduce

1. fallstation leftmost airlock under science department
2. put on the hardsuit
3. put off the hardsuit
4. leave the airlock and wander outside
5. you should be experiencing the bug

**Comment by Aranclanos** [comment]
Cant reproduce

**Comment by Fogapod** [comment]
Had same issue on square recently: 
![image](https://user-images.githubusercontent.com/22667809/134671787-885d81ad-132e-43e0-a2c0-bfce848b6ec7.png)
No drag from air flow/no o2 warning. Even though there is pressure warning, it did nothing.

Looks like in rare cases atmos dies

**Comment by AtnerNT** [comment]
Also believe this is fixed, have not heard anyone experience this in atleast a year
