### ISSUE TITLE
power ungaming [map: fallstation]

### ISSUE THREAD

**Issue by ridernametaken** [unitystation/unitystation#7152]
### Environment
- Game Version: 21072512
- OS Version: windows10pro

### Detailed description of bug

wiring is a massive pain because the laid wires do not transfer power and will return 0voltage if measured, the reactor also seems to not transfer its power to the wire grid 

### Steps to reproduce

1. place a reactor and connect it to a transfromer
2. wire them both accordingly
3. lay a red normal cable from the transformer
4. measure the voltage of all parts
5. you should get 0volt measurments

**Comment by ThatDan123** [comment]
Are you wiring from the reactor directly? You should be wiring from the turbine

**Comment by ThatDan123** [comment]
Screenshots are useful if you have any, you might just be missing or not connecting correctly

**Comment by ridernametaken** [comment]
![unknown (22)](https://user-images.githubusercontent.com/43878754/127196399-c6428dd9-6ac2-411a-8dbf-a4dd118c51b4.png)
here you go, i believe i have set them up correctly.

**Comment by ThatDan123** [comment]
ngl, thats such a mess of wires in not surprised it didnt work.

You dont need cables under the transformer.

Are you trying to power the turret? All you need to do is unlock it, then click a multitool on an APC and then click on the turret to link it to the power, turrets dont need power delivered directly.

**Comment by ridernametaken** [comment]
hey thats great to know, however the issue has come up multiple times before already where voltage would read 0.
one round i was playing with a very competent engineer and we were setting up the particle emitter and we had to move the entire thing back and forth at least 5 times because we had the same issue of the voltage and the reactor not supplying any power. i think its worth to check this bug out, even if my setup was chaotic, it should show energy coming from the generator to be 0

**Comment by PerfectTangent** [comment]
going to close this issue as it's better explained in #6415, and that is such an absolutely cluster fuck of wires, that it's hard to tell if there isn't user error involved.
