### ISSUE TITLE
How to point out the issues in other people more effectively (pointing needs a cooldown)

### ISSUE THREAD

**Issue by Kehren** [unitystation/unitystation#7177]
Game Version: 21072919

![image](https://user-images.githubusercontent.com/79835205/127701020-c0a0cc32-df9d-420d-b43c-c9eccad16fd6.png)
![image](https://user-images.githubusercontent.com/79835205/127701037-03280f47-e936-4af3-a43c-87ea6bf69340.png)
![image](https://user-images.githubusercontent.com/79835205/127701893-38946ecb-b301-457c-b87f-f081a0033c0e.png)
yeah so i basically ddosed the server by pointing too much, add a cooldown or something lol

**Comment by mmails** [comment]
that's funny

**Comment by corp-0** [comment]
thanks for reporting

**Comment by Aranclanos** [comment]
now, adding a simple cooldown to this is simple and easy, but how many commands can be abusable at this level?
