### ISSUE TITLE
Replace Firebase with our own Django Auth server B:180

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7179]
### Description
We have been wanting to drop Firebase for a while now and the Django auth server is in good shape, we're missing the implementation in Unitystation side.

To resolve this issue, the contributor must:
- Be able to read the host of the api from a config file, making possible for others to host their own auth servers.
- Write a wrapper for WebRequest to communicate with the Django auth server, being able to:
    - Login using username and password, receiving a token.
    - Login and verify user using a username and token.
    - Create a new account.
    - Trigger a request to change password.
    - Trigger a request for "forgot password".
    - Leave room for new requirements as the final implementation is still wip.

```
- [POST]{"id", "username", "email", "password"} http://api.register
- [POST]{"email", "password" || "token"} http://api.login
- [POST]{"email", "password" || "token"} http://api.logout
- [POST]{"email"} http://api.forgot-password
- [POST]{"email", "password", "newPassword" || "token", "newPassword"} http://api.change-password
- [GET]{"id"} http://api.users/<id>/
- [GET]{"id", "index"} http://api.characters/<id>/<index>
```

**Comment by PerfectTangent** [comment]
this issue is being promoted to bounty status, valued at 180 USD.

**Comment by NoooneyDude** [comment]
Will snag this.

**Comment by PerfectTangent** [comment]
Hey @NoooneyDude, what's happening with this bounty?

**Comment by NoooneyDude** [comment]
Hi @PerfectTangent. Still in progress. Is in good shape. Can view (out of date) progress [here](https://github.com/NoooneyDude/unitystation/tree/apiserver). I might PR changes not directly related to the changes described here separately, we'll see.
