### ISSUE TITLE
How to reproduce #7054 consistently. (new character same round bug)

### ISSUE THREAD

**Issue by Kehren** [unitystation/unitystation#7180]
- Game Version: 21072919

![image](https://user-images.githubusercontent.com/79835205/127738487-f6d93f88-5547-41a7-a906-97f6f5084dfd.png)

Reproduction
![image](https://user-images.githubusercontent.com/79835205/127738519-d698407e-12b3-45db-9520-fb96089017b4.png)
Get to this screen
Quit the game instantly (or maybe a second after you see it)
Reenter the game
![image](https://user-images.githubusercontent.com/79835205/127738614-36fecc30-22cd-4278-bc9f-0d9fc5572c7a.png)
![image](https://user-images.githubusercontent.com/79835205/127738672-2f440f8e-ca39-4f76-bb16-0b832a200755.png)

**Comment by PerfectTangent** [comment]
Thank you for reproducing. It is best to comment the reproduction methods under the original issue rather than make a new issue. Could you do that, please? Closing this issue.

**Comment by Kehren** [comment]
yeah sure
