### ISSUE TITLE
Door bolt toggle card doesn't bolt doors.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7190]
### Environment
- Game Version: Staging 21080118
- OS Version: Windows 10

### Detailed description of bug
Title. The door bolt toggle card doesn't bolt doors when used on them and in fact, just seems to do nothing.

### Steps to reproduce
1. Spawn as chief engineer.
2. Obtain the door bolt toggle card from your locker.
3. Use it on an airlock, it won't do anything to it.

**Comment by ThatDan123** [comment]
Not a bug, just hasnt been implemented

EDIT: Turns out it was implemented but is bugged

**Comment by PetMudstone** [comment]
> 
> 
> Not a bug, just hasnt been implemented

Then why does the door bolt toggle card exist? Oh well.
