### ISSUE TITLE
Canisters don't actually lose gas when opened.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7191]
### Environment
- Game Version: Staging 21080118
- OS Version: Windows 10

### Detailed description of bug
When canisters are opened, they will release gas but they will not actually lose any of their  contents. This means that canisters can effectively be infinite sources of gases. (Plasma) Canisters can still lose gas if they're wrenched down to a shuttle fuel port and the shuttle it is on is driven around, notably.

### Steps to reproduce
1. Find a canister.
2. Open the canister.
3. Watch the pressure remain constant in the canister UI despite the canister leaking gas.

**Comment by ThatDan123** [comment]
Should have been fixed by #7203
