### ISSUE TITLE
You start out suffocating when you spawn in.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7213]
### Environment
- Game Version: Staging 21080118 & Production 4121
- OS Version: Windows 10

### Detailed description of bug
Title. When you initially spawn in you'll start suffocating for a moment with a chat messages telling you that you gasp and with an oxygen alert in the corner. You'll stop suffocating very quickly but it's still odd that this happens.

### Steps to reproduce
1. Spawn in.
2. Start suffocating.
3. Stop suffocating.

**Comment by jamessimo** [comment]
This is linked with #6552

**Comment by MaxIsJoe** [comment]
Does not happen anymore
