### ISSUE TITLE
Spawning as the same character every round

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#7245]
### Environment
- Game Version: (latest staging version, can't check right now)
- OS Version: Windows 10

### Detailed description of bug

Everytime i try to choose a character, i always spawn as this old female character i deleted, i tried relogging, changing accounts, no luck.

### Steps to reproduce

1. Choose a character
2. Choose a role
3. Spawn in as a different character than what i chose

**Comment by mmails** [comment]
someone please help i want to stop playing as a woman

**Comment by Fogapod** [comment]
https://github.com/unitystation/unitystation/issues/6740

**Comment by AtnerNT** [comment]
Related issue has been closed, believe this is also fixed
