### ISSUE TITLE
Add two-handed wielding of certain items.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7254]
### Description
In /tg/, certain items such as fire axes and spears can be wielded with both hands to increase their damage. Other items such as potted plants, the cultist bastard sword, gibtonite, and the (non-Chaplain) chainsaw _require_ two hands to even hold.

There are a few variables that are relevant to the wielding component.
- wielded: Boolean, whether or not the item in question is currently being wielded.
- force_multiplier: Multiplies the damage of the item when it is wielded, doesn't work with the below two variables.
- force_wielded: Damage of the item when it is wielded.
- force_unwielded: Damage of the item when it is unwielded.
- require_twohands: If the item needs two-hands to even pick up and hold. Used for the chainsaw, potted plants, gibtonite, etc.
- icon_wielded: Sprite used for the item while it is being wielded.

When a wieldable item is used in-hand it runs a "wield" method which sets "wielded" to true unless you have an item in your other hand or if you only have one hand because your other hand got removed. Items with "require_twohands" set to true run the "wield" method upon being picked up and if wielding fails, the item is dropped.
Upon an item being wielded, its damage is adjusted either by being set to "force_wielded" or by being multiplied by "force_multiplier". Its sprite also gets updated to whatever is set in "icon_wielded". The in-hand also updates to show the wielding character holding the item with both hands.
Below, a character holding a bone spear one-handed
![image](https://user-images.githubusercontent.com/38266309/129302402-a18e78a1-0a2e-42e4-a1d9-3672ff238651.png)
Below, a character wielding a bone spear two-handed
![image](https://user-images.githubusercontent.com/38266309/129302439-58bef9ef-7da2-4c62-9d8c-19d10f3f4101.png)
Additionally, the item gets "(Wielded)" appended to the end of its name and prevents you from swapping hands. 
Bone spear with "(Wielded)" appended to its name.
![image](https://user-images.githubusercontent.com/38266309/129302988-f3ce20eb-bd75-43eb-8ff8-c278ed24b750.png)
Message upon trying to swap hands.
![image](https://user-images.githubusercontent.com/38266309/129303013-2a26242b-781f-400d-be24-c2fca2b631b6.png)

When a wielded item is used in-hand or moved out of the hand slot (either by dropping it or moving it to another inventory slot) it is in it runs an "unwield" method which sets "wielded" to false. Unwielding an item that requires two hands to use drops it in the case of potted plants and gibtonite but has alternate functions for the bastard sword and chainsaw which I will not elaborate on here.
Upon an item being unwielded it either removes the "force_multiplier" multiplier or sets damage to "force_unwielded". It also sets the icon and in-hand sprites back to normal.

**Comment by mmails** [comment]
I was about to suggest this, good call

**Comment by ilinm1** [comment]
working on it
