### ISSUE TITLE
Admins can spam click the "trigger event" button and cause the game to slow to a crawl.

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#7258]
### Environment
- Game Version:  13-8-2021 develop
- OS Version: Win10 Home.

### Detailed description of bug

Title.

### Steps to reproduce

1. Be admin
2. Spam click the "trigger event" button with random events selected.
3. Profit

**Comment by Pottingmix** [comment]
Can I be assigned This please? Thanks heaps.
