### ISSUE TITLE
Station bounced radios B: 75

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7261]
### Description

This bounty calls for the implementation of station bounced radios. Station bounced radio will function similarly to a standard radio headset if you put it in your pocket, belt-slot or in your hand.

Radios differ from headsets in a few key ways:

- Can have their frequency tuned, this changes which channel is used for sending and receiving messages by default.
  - Radios can be tuned to a minimum of 120.1 KHz and a maximum of 159.9 KHz. The default radios have a constricted range of a minimum of 144.1 KHz and to a maximum of 148.9 KHz, meaning these radios can only be tuned to the common and AI channels. 
- radios cannot have their encryption keys removed. (why, though? perhaps we want to allow it.)
- in addition to talking into the radio while equipped in a fashion like headsets, radios can also be switched to broadcast whatever they hear so long as they are in broadcast mode. Station bounced radios will pick up anything said in this mode within a 3 tile range.
- Pressing Z with a radio selected will bring up a UI that allows you to modify all the variables mentioned above.
- since unitystation has toggleable radio channel buttons and characters can have multiple radios available to use, each radio should get it's own channel buttons when equipped.
- radios can be combined with remote signallers to allow the signaller to remotely trigger or disable the broadcasting mode.

## What is needed to fulfill the bounty:

- [ ] add station bounced radios.

**Comment by MaxIsJoe** [comment]
if #7678 gets merged I'd like to work on this
