### ISSUE TITLE
Door bold ID doesn't work on staging but works on build 4121

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7267]
### Environment
- Game Version: Staging 21081300
- OS Version: arch linux

### Detailed description of bug

Door bolt ID worked on build 4121, but now it doesn't on the latest staging build. cant bolt it closed or vise-versa. 

### Steps to reproduce

1. take ID and try to use it on a door
2. doesn't get bolted and instead it behaves like you where trying to open the door.

**Comment by ThatDan123** [comment]
erm, you should have never been able to bolt doors using ID

**Comment by PerfectTangent** [comment]
he might be referring to the door bolting card Bod gave the CE.
