### ISSUE TITLE
Unable to fabricate reflectors

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7277]
### Environment
- Game Version: Staging 21081519
- OS Version: Arch Linux

### Detailed description of bug

When trying to build a new reflector you first have to make the base reflector and then add either glass, reinforced glass or a diamond. but at the second step of the crafting the base reflector simply "eats" the material and never becomes the desired result.

![reflector](https://user-images.githubusercontent.com/80334192/129496396-75433ae7-a399-4cff-9f54-37a924ebc958.png)

### Steps to reproduce

1. take metal and make a base reflector
2. add either glass, reinforced glass or diamonds
3. keep adding but it never becomes an actual reflector
4. cry because all your materials are lost forever to a hungry reflector base

**Comment by JukeJukestar** [comment]
Had this happen too a while ago! I thought I was just doing it wrong
