### ISSUE TITLE
Staging machine and console construction are broken.

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7278]
### Environment

- Game Version: Staging 21081519
- OS Version: Arch Linux

### Detailed description of bug

Can't build any machine frame or console related construction. When you make a new machine frame the next step is to add cables but right now you are unable to interact with:

Machine frames
Console frames
Turrets
Ballistic turrets

and when trying to deconstruct machines that are round start it makes a new machine frame without deconstructing the machine.

https://user-images.githubusercontent.com/80334192/129499058-5a49b970-7ed6-4f80-bfe3-8369fab6f06c.mp4

### Steps to reproduce

1. Machine building is broken.

**Comment by PetMudstone** [comment]
I received this error after using a screwdriver on an autolathe (which proceeded to create a machine frame) I spawned in using the dev spawner as localhost. 
![image](https://user-images.githubusercontent.com/38266309/129502911-b85e1ce4-622c-45ff-a5e0-e28e672f3491.png)

**Comment by Aranclanos** [comment]
Fixed in #7292
