### ISSUE TITLE
"CallCmdCheckDoorPermissions without authority" client warning spam

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#728]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Dev

# Report
## Current Behavior
Getting warning spam when running into doors as high ping client

## Expected/Wanted/Requested Behavior
There shouldn't be any

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start a mp session: host as editor, join as 200ms ping build, make sure script debugging is on for client
2. Try walking into doors as client

## Network
"200ms" simulation

**Comment by JacobSweeten** [comment]
Weird. It didn't happen before, but I think I know how to fix it.
