### ISSUE TITLE
Microwaves take twice the time they say they do when cooking food.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7281]
### Environment
- Game Version: Staging 21081519
- OS Version: Windows 10

### Detailed description of bug
Title. When a microwave is examined right after you start cooking with it, it will say it will take 10 seconds for it to cook. In actuality however, it takes 20 seconds to cook. Therefore, each microwave second is actually 2 seconds. You can see this in action by repeatedly examining a microwave as it cooks. It takes noticeably long for the microwave to go from saying 8 seconds are left to 7 seconds are left, and so on. 

### Steps to reproduce

1. Put food into a microwave, Turn on the microwave to start cooking.
2. Examine the microwave right after it's turned on, it will say cooking will take 10 seconds.
3. Actually wait 20 seconds for the food to finish cooking.

**Comment by NoooneyDude** [comment]
Haha, I wondered if this was happening, forgot to look into it.

Thank you.

What map was this on? Did the microwave's pitch sound different?

**Comment by PetMudstone** [comment]
I encountered this bug on Fallstation. I do not remember the pitch being noticeably different.
