### ISSUE TITLE
Mime Invisible Wall can force open any airlock

### ISSUE THREAD

**Issue by JustinTrotter** [unitystation/unitystation#7286]
### Environment
- Game Version: 4121
- OS Version: MacOS

### Detailed description of bug

Mimes are able to force open any airlock without access simply by using Invisible Wall on top of the airlock and then running into it repeatedly. The door will open but the invisible wall blocks your path. However, as soon as the invisible wall despawns there's enough time to pass through the airlock.

### Steps to reproduce

1.  Be Mime
2. Find Airlock you can't open and face it directly
3. Use Invisible Wall ability
4. Repeatedly move into or click on the airlock
5. Watch it magically open
6. Wait for Invisible Wall to time out
7. Gain Access

**Comment by waffielz** [comment]
gaming

**Comment by Bod9001** [comment]
![(HiFiGIF cc)_hardtofindtensecowbird-size-restricted](https://user-images.githubusercontent.com/27101670/131989962-b1a738e3-3c2f-4151-a009-0f1adb3edb68.jpg)

**Comment by MaxIsJoe** [comment]
won't fix

Mime walls can't be destroyed via code apparently and tile interactions can't have an `Awake()` or any sort of on spawn function to delete itself once it detects itself ontop of a door.
