### ISSUE TITLE
Very low roundstart antag chance

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7297]
### Detailed description of bug

Since a month or so there has been a lower count of antagonists on traitor rounds and even rounds with atleast 10 to 15 people on server with a single to none antag, backing this up with the fact that the last nuclear operative round on both servers solidarity and staging was atleast a month ago. a game mode that happened atleast twice a day.

![antag 2](https://user-images.githubusercontent.com/80334192/130164625-8b3c586a-13a4-4076-ab9a-cb5b94170ab9.png)
![antag 3](https://user-images.githubusercontent.com/80334192/130164423-594e1597-8661-4109-a1c3-475f99897ebb.png)
![antag 4](https://user-images.githubusercontent.com/80334192/130164444-4c68584c-38bf-4b5b-80ee-cfe0bc89e170.png)

there is also an increase on people leaving the game mid round becuase "nothing antag whorty" happens so the game stales until someone seft-antags or the round ends. So if there is less people on server surely there is way less chance of antags roundstart or midround? (not backed up but not imposible)

### Steps to reproduce

nothing definitive

1. maybe the antag preference section is being switched off, counting that is default to off so most people are not aware if it changed or not. 
![antag](https://user-images.githubusercontent.com/80334192/130164804-401383f0-4745-43fe-a792-ac5a10c28310.png)

2. It switches off after a round on when you exit the game and come back (just a theory)

**Comment by PerfectTangent** [comment]
should be alleviated by #7729
