### ISSUE TITLE
APC building rebalance B:20

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7298]
### Environment
- Game Version: Staging 21081715
- OS Version: Arch Linux

### Detailed description of bug

right now building a new APC just requires 2 metal and placing in on a wall, while on the TG it needs as shown here:
![APC](https://user-images.githubusercontent.com/80334192/130170667-2910e97d-2782-4d00-8c95-caf87c977036.png)

for how easy it is to make a new APC and with the doors V2 now on all stations it can lead to cheesing the apc to open any door on station.

https://user-images.githubusercontent.com/80334192/130170768-fbe955cd-28b7-49a8-a920-bb73c9e753b4.mp4

**Comment by PerfectTangent** [comment]
This is being promoted to bounty status. If anyone wants some easy money, this bounty is worth 20 USD. Obviously, steps 4, 5, and 6, are already implemented. This issue mainly covers the lack of a power control module and other parts in the construction process that would limit APC spamming. step 2 also does not apply as we do not have areas in the game.
