### ISSUE TITLE
BoxStation Ai Core Wire

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#7303]
![image](https://user-images.githubusercontent.com/56727168/130293081-cc2d97b8-c014-42c6-b916-babc3031747c.png)

Boxstation AI core lacks a low voltage wire to the AI APC

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue🙂, can someone help me out here!?

**Comment by ThatDan123** [comment]
Im afraid it might not be able to be fixed right at this second, there's a bug with placing down wires in the editor. 

Hopefully should be fixed soon.

But once it's fixed, you'll need to download unity and open the project and then use the tile palette to place down the correct wire. You can ask in the discord dev channels if you need any help.

**Comment by corp-0** [comment]
Sure thing, are you in our discord? It might be more comfortable to walk you through in chat. You can also read and follow the first contribution guide if you would rather set your dev environment alone: https://unitystation.github.io/unitystation/contribution-guides/Starting-contribution/

**Comment by corp-0** [comment]
Ah heck, I didn’t know about the bug

**Comment by ThatDan123** [comment]
Looks like pet just ignored the bug and did it anyway in #7310
