### ISSUE TITLE
Round end throws an exception instead of restarting

### ISSUE THREAD

**Issue by MaddoScientisto** [unitystation/unitystation#731]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Development

# Report
## Current Behavior
When a round ends and it attempts to restart an exception is thrown:
```
UnassignedReferenceException: The variable target of Camera2DFollow has not been assigned.
You probably need to assign the target variable of the Camera2DFollow script in the inspector.
UnityEngine.Transform.get_position () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
FieldOfViewTiled.RayCastQueue (UnityEngine.Vector2 endPos, UnityEngine.Vector2 offsetPos) (at Assets/Scripts/Camera/FieldOfViewTiled.cs:257)
FieldOfViewTiled.SetShroudStatus (ShroudAction shroudAction) (at Assets/Scripts/Camera/FieldOfViewTiled.cs:286)
FieldOfViewTiled+<FovProcessing>c__Iterator0.MoveNext () (at Assets/Scripts/Camera/FieldOfViewTiled.cs:143)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

## Expected/Wanted/Requested Behavior
I expect an exception to not be raised

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start a deathmatch round
2. Let timer run out
3. After the 10 seconds the crash occurs

## OS used:
Windows

## System specifications
Not relevant

## Network
same pc default settings

**Comment by MrLeebo** [comment]
Given that normally FOV processing would have aborted by now, I think it is reasonable to think that this issue already existed on Windows, just never saw it because the processing aborted before end of round.

**Comment by Ornias1993** [comment]
@MrLeebo If that was true, @Em3rgencyLT would have catched in testing his extensive testing of the new round meganism ;)

**Comment by DooblyNoobly** [comment]
Pretty easy to fix `You probably need to assign the target variable of the Camera2DFollow script in the inspector.` There most likely isn't a player spawned for the client for a split second on round restart leaving the target in camFollow vacant. Just need to do a dependency wait in a coroutine to solve it
