### ISSUE TITLE
Bullets phase trough objects and players

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7322]
### Environment
- Game Version: Staging 21082200
- OS Version: Archh Linux

### Detailed description of bug

Bullets, lasers and even foam darts if shot too close or even randomly if far will go trough a player or an object, and it wont damage the object that you intend to shoot:

Example 1

https://user-images.githubusercontent.com/80334192/130518744-9629d76d-672a-436b-b031-20884df4b21b.mp4

Example 2

https://user-images.githubusercontent.com/80334192/130518874-834db581-bba0-4fa9-8ff9-068674f96f5c.mp4

Example 3

https://user-images.githubusercontent.com/80334192/130519096-c0a9b5d7-ffa1-48d7-a7f7-e86c4110b22a.mp4

### Steps to reproduce

1. shoot something close

**Comment by Leander-0** [comment]
On the latest builds of staging the projectiles behave a bit diferent


https://user-images.githubusercontent.com/80334192/134825129-04dd16c1-68bd-4b26-a566-6da825298a5d.mp4


https://user-images.githubusercontent.com/80334192/134825159-0028f2aa-2c73-4ba9-bcd7-4c7ab63f1b4d.mp4


https://user-images.githubusercontent.com/80334192/134825187-f1f86cbe-d5b9-454e-93cd-0e38f8982c9d.mp4

**Comment by Fogapod** [comment]
> On the latest builds of staging the projectiles behave a bit diferent

documented projectiles passing through objects in https://github.com/unitystation/unitystation/issues/7446

**Comment by Aranclanos** [comment]
Seems to be really old and can no longer reproduce these in staging
