### ISSUE TITLE
Self-sufficient scrubbers don't seem to actually do anything.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7330]
### Environment
- Game Version: Staging 21082412
- OS Version: Windows 4121

### Detailed description of bug

Self-sufficient scrubbers such as those seen on shuttles don't seem to actually function in regards to removing gases. They don't filter out plasma, miasma, etc.

### Steps to reproduce
1. Release plasma onto a shuttle with a scrubber. 
2. Watch as the plasma never dissipates.

**Comment by PerfectTangent** [comment]
might be a result of Aran's changes to them. he reduced their  S U C C  to 1/20th of what it was before.

**Comment by PerfectTangent** [comment]
this needs to be verified now that deprecated vents and scrubbers have been comprehensively removed from the codebase in #7373
