### ISSUE TITLE
Stop electrical working on server with a single wire

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7333]
### Environment
- Game Version: Staging 21082412
- OS Version: Arch Linux

### Detailed description of bug

When a certain wire placement is made all electrical machines and wires on the floor stop working, the machines hooked to the power grid when deconstructed get cloned on top of it, you can place wires on the floor but cannot cut them off, all power displayed on the multitools show that the voltage and amperage are 0.

you also are permanently unable to link devices with APCs, and the power just never depletes with already linked machines.

demonstrative video:

https://user-images.githubusercontent.com/80334192/131192934-ea7ea812-2da9-4f37-8959-14ba05dcd289.mp4

### Steps to reproduce

The easiest place to reproduce the bug is on Fallstation plasma generator room.

1. Start round and check with multi tool correct functionality of power, cut wires and de/reconstruct the SMES to test if it works.
2. start the plasma gen
3. add the wires from the output of the transformer to the output of the SMES as show in the video at 0:35
4. repeat step 1

tested both on staging server and locally

**Comment by NoooneyDude** [comment]
"Chief engineers hate him! Learn about the one trick this guy discovered that engineers don't want you to know about."

**Comment by corp-0** [comment]
@Bod9001 any idea on what the heck is going on here?

**Comment by Bod9001** [comment]
looks like error with SMES connecting to itself

**Comment by Aranclanos** [comment]
https://user-images.githubusercontent.com/701959/138300414-3abed5c2-412c-4532-9b08-3f343c211a15.mp4

Tested step by step, everything looks fine.
Bod mentioned he fixed some infinite loop some time ago and forgot to close this issue

**Comment by Bod9001** [comment]
Fixed in #7578
