### ISSUE TITLE
Oxygen damage doesn't seem to put you in crit or kill you properly.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7344]
### Environment
- Game Version: Staging 21083022
- OS Version: Windows 10

### Detailed description of bug
Oxygen damage behaves strangely in regards to crit and death states. For some reason having 100 oxygen damage will not cause you to become unconscious and having 200 oxygen damage will not kill you. Reaching these levels is quite negligible for your character, in fact.
Reaching 600 oxygen damage causes you to go into crit, but reaching 1,200 oxygen damage and above doesn't seem to kill you oddly enough. Dealing other kinds of damage on top of the 1,200+ oxygen damage will immediately kill your character, however.
In regards to the "Overall status" of someone's health viewable via the health analyzer, oxygen damage seems to adjust the percentage less than other types of damage.
![image](https://user-images.githubusercontent.com/38266309/131775416-c5099abd-7e04-4199-a57e-a246ca40bf12.png)
![image](https://user-images.githubusercontent.com/38266309/131775917-0c4cd211-c484-48ee-bc61-1423f9667bff.png)

### Steps to reproduce
1. Go out into space while wearing a spacesuit and with a health analyzer. Keep your oxygen turned off.
2. Wait as you suffocate for a minute or so.
3. Check yourself with the health analyzer. Despite you most likely having around 200 oxygen damage by this point you will not have fallen unconscious let alone be dead.

**Comment by PetMudstone** [comment]
Interestingly, how severe oxygen damage is and how much you need to go into crit seems to be based on how many limbs/body parts you have. I amputated both my legs and I only needed 400 oxygen damage to go into crit afterwards.
![image](https://user-images.githubusercontent.com/38266309/131776677-8f631840-6a5a-44f2-8b07-5ce3b95eebdd.png)

**Comment by PetMudstone** [comment]
Update, tested what happens if I remove all my body parts except my head and torso on 21090215. I go into crit after 200 oxygen damage now.
![image](https://user-images.githubusercontent.com/38266309/132111805-3f63103a-32e6-4e14-a455-36d4f20dd5c0.png)

**Comment by Aranclanos** [comment]
seems to be using only one part of the body for the dmg
maybe chest? an organ that doesnt show on the analyzer?
