### ISSUE TITLE
Character sprites don't change direction when crawling.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7345]
### Environment
- Game Version: Staging 21083022
- OS Version: Windows 10

### Detailed description of bug
Title. Characters that are crawling don't change directions on their sprites based on where they move. This looks somewhat strange. Also your sprite changes direction when crawling in /tg/ too so.

### Steps to reproduce
1. Start crawling.
2. Move in different directions. Notice that your sprite does not change.

**Comment by PerfectTangent** [comment]
Redundant with #6671. Closing.
