### ISSUE TITLE
Dismembering arms and heads doesn't drop items when they should be.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7350]
### Environment
- Game Version: Staging 21090215
- OS Version: Windows 10

### Detailed description of bug
Title. Dismembering arms and heads doesn't certain held items when they should be dropped. Items held in hands aren't dropped on the floor when you dismember the relevant arm and just seem to disappear. The same happens with items attached to the head (hats, masks, glasses, earpieces, neckwear) but their sprites remain on the attacked character's body unlike with held items while being still inaccessible in the examine menu.

### Steps to reproduce
1. Obtain a traitor's energy sword.
2. Decapitate someone wearing a hat.
3. Notice that the hat sprite still appear's on their body even though they have been beheaded.

**Comment by PetMudstone** [comment]
![image](https://user-images.githubusercontent.com/38266309/131968251-1a354c05-e9a6-4de7-859f-f82c80b5cfaf.png)
Notably, "Drop Contents" on the storage slots in "BodyPartUISlots" on the "HumanHead" prefab is set to false on all of them. Turning it on causes the sprites for the headwear and such to dissappear on decapitation, but the relevant items are still not dropped.

**Comment by MaxIsJoe** [comment]
Quick headsup, I fixed this in
https://github.com/MaxIsJoe/unitystation/commit/655edd8e7f067dc727cf4ec7dbd81314e15e0149

a PR will be up at some point when I'm done with my other fixes
