### ISSUE TITLE
You can see and hear mobs from other matrices as a client.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7356]
### Environment
- Game Version: Staging 21090215
- OS Version: Windows 10

### Detailed description of bug
As a client, you can see mobs from other matrices when you spawn on the station. You are also able to hear them in the case of mobs that make noises like xenomorphs. Notably, you can't actually interact with these mobs and these mobs can't interact with you. Similarly, the mobs will appear to phase through walls and objects on the station.

### Steps to reproduce
1. Join a server.
2. Walk around for a bit until you see carp, xenomorphs, hivebots, etc. walking around the station.

**Comment by Aranclanos** [comment]
the sound position gets overriden by the transform.position of the mob if the client receives a netID so i believe this was fixed in the linked PR
