### ISSUE TITLE
Players dont have the correct ammount of blood

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7358]
### Environment
- Game Version: Staging 21090215
- OS Version: Arch Linux

### Detailed description of bug

![blood](https://user-images.githubusercontent.com/80334192/132110656-2e3bd871-a2ad-4c4e-b5ac-422132520f8f.png)

As the title says, when you spawn and check yourself with the health analyzer it says you have 500cc of blood when you should have 10 times that amount.

**Comment by PerfectTangent** [comment]
this is not a bug. 500 is intended as of #6861.

**Comment by PetMudstone** [comment]
I did test blood levels in the editor with the help of Gilles and 5000 cc of blood showed up as 100% on the health scanner, so I still think something is up with blood levels.
