### ISSUE TITLE
Send yourseft to the shadow realm with this simple trick

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7359]
### Environment
- Game Version: Staging 21090215
- OS Version: Arch Linux

### Detailed description of bug

lay down in a surgery table and perform the act of trowing something, you will be immediately teleported to near 0,0 unbuckle from the table and you will be brought back to the station.

![table](https://user-images.githubusercontent.com/80334192/132110762-72c3cb11-23ab-49a5-927b-8f018c902990.png)

**Comment by JustinTrotter** [comment]
Suggestion: make this the default behavior when going under anesthesia.

**Comment by Aranclanos** [comment]
Fixed in #7370
