### ISSUE TITLE
Underwear doesn't render for clients.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7367]
### Environment
- Game Version: Staging 21090215
- OS Version: Windows 10

### Detailed description of bug
Title. Underwear doesn't render for clients during a round. It still renders for hosts.

### Steps to reproduce
1. Connect to a server as a client.
2. Make sure your character has underwear in the character customization menu.
3. Take off your clothes. You not have visible underwear.

**Comment by Aranclanos** [comment]
whoops

**Comment by AtnerNT** [comment]
Been fixed for awhile now
