### ISSUE TITLE
Bodies in DNA Scanner Disappear on Deconstruct

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#7371]
(Reported on Discord)

-Bodies in DNA Scanner Disappear on Deconstruct

To fix either prevent deconstruction from happening if a body is inside (Add interface to check) or on despawn dump contents

**Comment by Aranclanos** [comment]
it was in solidarity so its unrelated to the latest position/registertile changes

**Comment by PetMudstone** [comment]
Tested on Staging 21101813. This bug doesn't seem to occur anymore. Deconstructing DNA scanners with people in them causes them to pop out on deconstruction.

**Comment by ThatDan123** [comment]
I'll close this then

**Comment by NoooneyDude** [comment]
Oh yeah, should be done w/ the closet refactor 👍
