### ISSUE TITLE
Radiation doesnt cause damage

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7391]
### Environment
- Game Version: Staging 21090800
- OS Version: Arch Linux

### Detailed description of bug

Now radiation doesn't cause any kind of damage to the players on game.

example from being on top of the nuclear reactor (highest source of radiation possible):
![reactor](https://user-images.githubusercontent.com/80334192/132604278-3dbf49a5-b10b-42d3-b82d-819bb5a0be63.png)

also if you step on top of the fully started reactor core the health doll will do this.

https://user-images.githubusercontent.com/80334192/132604404-2811e6ad-2be0-42ce-a48c-d7c0073c55aa.mp4

### Steps to reproduce

1. take health analyzer and Geiger counter 
2. start the reactor until you get the biggest amount of radiation possible
3. step on top of the core and check health

**Comment by jamessimo** [comment]
Weirdly I was playing on staging and messing with the reactor and I was getting tox damage but only after quite a while (like 10 mins of being around the reactor) Not sure if it was something else doing that to me.
