### ISSUE TITLE
Gateway portal is a trap

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7392]
### Environment
- Game Version: Staging 21090800

### Detailed description of bug

when you get teleported out of the gateway you get stuck on the tile it places you

easiest place to replicate is in the relicta away site

https://user-images.githubusercontent.com/80334192/132609717-75870d3b-d368-497f-8e4e-e1a5f51ecff7.mp4

### Steps to reproduce

1.  start round making sure the away site is relicta
2. step into the gateway portal

**Comment by Fogapod** [comment]
I got trapped in lavaland portal today same way. I can't leave this tile:
![image](https://user-images.githubusercontent.com/22667809/134547394-088167ea-61e4-4e58-8d21-48bc4b0468d9.png)

**Comment by Aranclanos** [comment]
Fixed in #7489
