### ISSUE TITLE
Going to the kitchen then going back to the lobby then back to the kitchen causes you to be invisible

### ISSUE THREAD

**Issue by Poea** [unitystation/unitystation#74]
> 2blob:http://doobly.izz.moe/24ca7536-1596-4651-b256-cf7f13272432:1 CHECK IF SPAWNED
>  
> (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/WebGL/runtime/DebugBindings.gen.cpp Line: 51)
> 
> 
> blob:http://doobly.izz.moe/24ca7536-1596-4651-b256-cf7f13272432:1 Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
> 
> blob:http://doobly.izz.moe/24ca7536-1596-4651-b256-cf7f13272432:1 warning: 3 FS.syncfs operations in flight at once, probably just doing extra work
> blob:http://doobly.izz.moe/24ca7536-1596-4651-b256-cf7f13272432:1 
> Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 24394.
> 
> blob:http://doobly.izz.moe/24ca7536-1596-4651-b256-cf7f13272432:1 Total: 46.639999 ms (FindLiveObjects: 4.395000 ms CreateObjectMapping: 4.630000 ms MarkObjects: 37.310001 ms  DeleteObjects: 0.240000 ms)
>

**Comment by DooblyNoobly** [comment]
Yep, this will be fixed in the next demo

**Comment by DooblyNoobly** [comment]
this has been fixed
