### ISSUE TITLE
Camera/light tube orientations wrong/duplicated

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7406]
### Environment
- Game Version: UnityStationDevelop-21090800

### Detailed description of bug

I'm surprised nobody reported this yet (at least i couldnt find it).
![image](https://user-images.githubusercontent.com/22667809/133289348-a0808b00-025b-4c46-a884-0ca08cd9fd13.png)
![image](https://user-images.githubusercontent.com/22667809/133289381-e12cb904-5332-410b-a645-24f26fe0129f.png)
These are all over the place.
Note that light tube sprites get duplicated while camera is rotated without duplicated sprite.
Not all objects are like this, It looks like

**Comment by PerfectTangent** [comment]
was this in game? It is a known issue in the editor, but I've never seen it happen in a released build of the game before.

**Comment by Fogapod** [comment]
It's been an issue for the last couple builds. Everyone who plays on staging will confirm this. Happens every round

**Comment by PerfectTangent** [comment]
Was able to confirm this with @corp-0 that it affects individual clients differently and it affects items of the same kind differently. From what I observed, lights, cameras, and chairs were affected, but it's probably a problem with sprite orientations in general.

notice in this shot how 2 chairs are rotated correctly towards the counter while the middle 3 are mis-rotated. They all looked correct to Gilles. Upon manually rotating the chairs, they regained their proper sprite orientation for me.

![Screenshot 2021-09-20 214529](https://user-images.githubusercontent.com/68730437/134099646-3c985785-46fd-41ff-ba76-6c8755e169e8.png)
