### ISSUE TITLE
Soap can scrub floor through table and other objects

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7411]
### Environment
- Game Version: UnityStationDevelop-21091418

### Steps to reproduce

1. Pick up soap
2. Click on table
3. Click on office chair
4. Click on lightbulb
5. Click on window tile
6. Click on yourself/other character

**Comment by Fogapod** [comment]
Something similar happens with crowbar. If it fails to interact with object it often removes floor tile underneath which is annoying

Crayons seem affected too

**Comment by apohlman23** [comment]
Can I be assigned to this?

**Comment by corp-0** [comment]
assigned, ask in our discord if you need help getting to know the codebase
