### ISSUE TITLE
You can scrub same tile multiple times creating conflicting progress bar

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7413]
### Environment
- Game Version: UnityStationDevelop-21091418

### Steps to reproduce

1. Pick up soap
2. Click multiple times on the same floor tile

**Comment by apohlman23** [comment]
Can I be assigned to this?

**Comment by corp-0** [comment]
assigned

**Comment by apohlman23** [comment]
Is this still an issue? I'm unable to replicate this, as seen here: 
![multiple scrub no bug](https://user-images.githubusercontent.com/43727304/146412478-097d7b55-f58a-438e-a7cd-81a20f20993d.gif)

**Comment by Fogapod** [comment]
No longer happens for me
