### ISSUE TITLE
Crawling over soap makes you slip anyway

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7414]
### Environment
- Game Version: UnityStationDevelop-21091418

### Detailed description of bug
https://user-images.githubusercontent.com/22667809/133427901-24b83a4c-b3ed-46dc-8259-0f494ed57b7f.mp4

You can move a few tiles forward by holding direction key, but once you stop or change direction you are unable to move.
This also features #6708 which still thinks that I need to stand up while I am standing.

### Steps to reproduce

1. Enter rest mode
2. Crawl over soap

**Comment by apohlman23** [comment]
Can I be assigned to this?

**Comment by corp-0** [comment]
sure

**Comment by apohlman23** [comment]
Is this still an issue? I'm unable to replicate this. When crawling over the soap I can't keep moving, I just slip to the next tile and can't move past that, as seen here:
![soap crawl no bug](https://user-images.githubusercontent.com/43727304/146412837-3ba48963-9dc8-44db-95b7-3efdc251f999.gif)

**Comment by Fogapod** [comment]
Yeah, weird bug with not falling until you change direction is gone, but issue title still stands. I don't think you should slip while crawling
