### ISSUE TITLE
Lavaland floor is full of holes

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7442]
### Environment
- Game Version: UnityStationDevelop-21091918

### Detailed description of bug

![image](https://user-images.githubusercontent.com/22667809/134547601-0c6fc8d2-9553-4bf7-b974-6d5e91bbe38e.png)

### Steps to reproduce

1. Teleport to lavaland (dangerous because you can get stuck: #7392 )

**Comment by ThatDan123** [comment]
Hopefully fixed by #7719
