### ISSUE TITLE
Attempting to attack someone with a reagent container instead causes you to splash its contents onto them.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7445]
### Environment
- Game Version: Staging 21091918
- OS Version: Windows 10

### Detailed description of bug
Title. Trying to attack people with reagent containers such as welding tools makes you spill their contents onto them. Trying to attack while the container is empty does nothing. Notably, you can splash the contents of any reagent container onto people, including things such as pizza and welding tools. Related to #5311.

### Steps to reproduce
1. Use a welding tool on someone on harm intent.
2. Instead of attacking, you will splash the welding fuel onto them.

**Comment by MaxIsJoe** [comment]
From what I'm reading from the code, this seems like it's an intended behavior.

**Comment by PerfectTangent** [comment]
> From what I'm reading from the code, this seems like it's an intended behavior.

it isn't. A welding tool shouldn't be splashing it's contents on the target. Whether a reagent container splashes or not should be a setting for a given item.
