### ISSUE TITLE
All projectiles go through lockers/vendors/disposals

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7446]
### Environment
- Game Version: UnityStationDevelop-21091918

### Detailed description of bug

Projectiles should hit objects you cannot walk through. Exceptions are things like table you can climb on or transparent objects for energy weapons. This is not the case:
![image](https://user-images.githubusercontent.com/22667809/134631354-a15778b9-cff4-47f8-bf5c-75c6486fdd72.png)

Visually projectiles went through everything, but messages about damage was printed for last 2 vendors. Eventually they fell: ![image](https://user-images.githubusercontent.com/22667809/134631504-82f4e38c-0eea-4fbf-9f8f-970b7def8aef.png)
Other objects do not get damage no matter the distance.
On a side note, walls seem to be indestructible: ![image](https://user-images.githubusercontent.com/22667809/134631753-a49441df-c35e-480d-92ae-005f11a9948f.png)

### Steps to reproduce

1. Fire at any of the listed objects

**Comment by Aranclanos** [comment]
Can't reproduce

**Comment by Fogapod** [comment]
Can't reproduce as well. Either it was fixed or there is some precondition
