### ISSUE TITLE
Unable to deconstruct objects using screwdriver, cable panel is opened instead

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#7462]
### Environment
- Game Version: UnityStationDevelop-21092504

### Detailed description of bug

Power storage unit is one such example. It's first deconstruction step is screwdriver, but it opens cable panel instead.
I suspect other objects might be affected by this change in hacking.

### Steps to reproduce

1. Use screwdriver on Power Storage Unit

**Comment by Q4ik** [comment]
Try a pry bar after the screwdriver.

**Comment by VernaSaurus** [comment]
i've tried every tool after screwdriving, it doesn't work

**Comment by VernaSaurus** [comment]
this bug also affects microwaves

**Comment by VernaSaurus** [comment]
gonna do this

**Comment by Q4ik** [comment]
The SMES is the only one that gives me issues so far

**Comment by JustinTrotter** [comment]
> gonna do this

Too late!
