### ISSUE TITLE
You can melee attack limbs which no longer exist, which does no damage.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7474]
### Environment
- Game Version: Staging 21092802
- OS Version: Windows 10

### Detailed description of bug
When you attack a limb that no longer exists, you will receive the same feedback as attacking an existing limb but you will not actually to damage to the person you're attacking.

### Steps to reproduce
1. Remove an arm or leg from someone.
2. Attack the now absent limb.
3. Notice the other person has not been harmed.

**Comment by MaxIsJoe** [comment]
this has been long fixed

**Comment by corp-0** [comment]
@MaxIsJoe do you happen to know what PR?

**Comment by corp-0** [comment]
oops

**Comment by MaxIsJoe** [comment]
> @MaxIsJoe do you happen to know what PR?

I don't remember which PR but I remember fixing it along side players being able to attack things like eyes and the groin and not doing any damage.

**Comment by corp-0** [comment]
alright, feel free to reopen if this still hapens somehow
