### ISSUE TITLE
Aiming at the head doesnt do damage

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7498]
### Environment
- Game Version:  Staging 21093018
- OS Version: Arch linux

### Detailed description of bug

as the title says, when you hit yourseft or someone else with melee on the head it doesnt damage him.
example:

https://user-images.githubusercontent.com/80334192/135702461-11b543c8-26da-4b61-9fef-20398f950e0f.mp4

### Steps to reproduce

1. This was tested on the staging server
2. get a weapong or tool and try to hit yourseft on the head
3. check health

**Comment by JustinTrotter** [comment]
I've done some testing on this using the latest develop branch. Currently targeting the head does damage just fine. However targeting the eyes and mouth will do no damage.

**Comment by corp-0** [comment]
> I've done some testing on this using the latest develop branch. Currently targeting the head does damage just fine. However targeting the eyes and mouth will do no damage.

did you test locally or in a server - client environment?

**Comment by JustinTrotter** [comment]
> > I've done some testing on this using the latest develop branch. Currently targeting the head does damage just fine. However targeting the eyes and mouth will do no damage.
> 
> did you test locally or in a server - client environment?

Both
