### ISSUE TITLE
All projectiles hit the chest indiferent of where you aimed

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7499]
### Environment
- Game Version: Staging 21093018 
- OS Version: Arch Linux

### Detailed description of bug

as the title says all guns when shot will always hit the chest without taking in consideration if you aimed for a different limb.

https://user-images.githubusercontent.com/80334192/135702642-07592516-7830-4063-a116-12a693aeb898.mp4

### Steps to reproduce

1. take gun and shoot aiming at any limb that isnt the chest 
2. shoot at yourseft or someone else
3. check health

**Comment by Fogapod** [comment]
What happens if your projectile hits someone by accident (out of sight), should it still hit selected limb?
You couldn't possibly calculate trajectory to do this

**Comment by PerfectTangent** [comment]
> What happens if your projectile hits someone by accident (out of sight), should it still hit selected limb? You couldn't possibly calculate trajectory to do this

I don't see any need to make it more complicated than that. Besides, In ss13, what body part you hit with projectile attacks is randomized, with a favored chance to hit the limb you're targeting. You 'aim' for what you want to hit, but don't have a guarantee. We'll have random hit allocation eventually as well.
