### ISSUE TITLE
All keybinds except for movement keys (WASD) don't work in editor.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7526]
### Environment
- Game Version: Latest Develop
- OS Version: Windows 10

### Detailed description of bug

Title. Every keybind except for the WASD keys does not work in editor. This is bad because it makes performing a number of actions such as swapping hands more awkward since you have to use your mouse and other actions such as typing in chat completely impossible.

### Steps to reproduce
1. Enter playmode in the Unity editor.
2. Hit any keybind aside from WASD.
3. Have nothing happen.

**Comment by PetMudstone** [comment]
After investigation, appears to be linked to #7449.

**Comment by Bod9001** [comment]
fixed this awhile ago
