### ISSUE TITLE
Opening crates with a knife simultaneously stabs and opens the crate,

### ISSUE THREAD

**Issue by JacobSweeten** [unitystation/unitystation#753]
# Preliminary information
Opening crates with a knife simultaneously stabs and opens the crate,

## Category
BUG

## Bug: Release or Development?
Development

# Report
## Current Behavior
Opening crates with a knife simultaneously stabs and opens the crate,

## Expected/Wanted/Requested Behavior
Opening crates with a knife does not stab the crates as well.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get a knife
2. Try to open a crate with a knife in the active hand.

## OS used:
Windows x64

## System specifications
Is this really relevant to this issue?
i3-3220 8GB RAM GeForece GTX 1060

## Network
Client/server in editor.

**Comment by fomalsd** [comment]
Do people inside containers receive a portion of damage to the container though?
