### ISSUE TITLE
BZ go poof

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7552]
### Environment
- Game Version: Staging: Square Station, 21100907
- OS Version: Mac- Catalina 10.15.7

Found while making BZ and collecting in runoff tank.

### Steps to reproduce

1. Start by making BZ and collect it in the runoff tank.
2. Now go make some more BZ and try adding it to what you collected.
3. The tank seems to make the newly made BZ vanish. 

d![image](https://user-images.githubusercontent.com/92214971/136676081-7f5c27ff-771f-4fbe-b5dc-979eac9b0ee2.png)
![image](https://user-images.githubusercontent.com/92214971/136676101-b982d8ff-6408-4b00-9f1f-e70ff2dbaf91.png)
![image](https://user-images.githubusercontent.com/92214971/136676187-936f43dc-d488-4aca-b637-f79981451e78.png)
![image](https://user-images.githubusercontent.com/92214971/136676218-ece223f6-b869-419a-80fc-9d3143011db5.png)

**Comment by PerfectTangent** [comment]
@Q4ik was this a one time occurrence or is this bug reproducible?

**Comment by Q4ik** [comment]
That was a regular thing for me when I reported it, so it should be reproducible.

**Comment by AtnerNT** [comment]
@Q4ik Are you still experiencing this bug? Or has it since gone away for you

**Comment by Q4ik** [comment]
@AtnerNT, I’ll check when I get home

**Comment by Q4ik** [comment]
This seems to be running nicely now.
