### ISSUE TITLE
"Select this character" button in the character selection window doesn't actually select characters.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7571]
### Environment
- Game Version: Staging 21101020
- OS Version: Windows 10

### Detailed description of bug

Title. Using the green button labeled "Select This Character" on the character select window doesn't actually select whatever character you are currently viewing.
![image](https://user-images.githubusercontent.com/38266309/137238649-c5a3f03e-a2f6-44b4-8c6f-5523be5b025e.png)
Instead, you have to go to "Edit Character", go to the character editing window, and then hit "Apply" in the bottom right corner.
![image](https://user-images.githubusercontent.com/38266309/137238705-24c3c3b0-c314-4e6d-b67f-848cadc016ae.png)

### Steps to reproduce
1. Have multiple characters.
2. Try to select a character different from the one you have active.
3. Load into a game, you will not be the character you "selected".

**Comment by mehmetozturk-re** [comment]
İf is it still available, can i work on it?

**Comment by PetMudstone** [comment]
No one else has expressed an interest in fixing this issue right now, so I don't see why not.

**Comment by mehmetozturk-re** [comment]
Then okay i am starting to deal with issue.

**Comment by corp-0** [comment]
adding this to the big project of terrible bugs

**Comment by corp-0** [comment]
@mehmetozturk-re hey, do you have a discord account? Are you still working on this? We want to talk with you on discord if possible.

**Comment by mehmetozturk-re** [comment]
I started to working on it but I think it is too much for my level of knowledge. You can unassigned me. Sorry for can not help

**Comment by corp-0** [comment]
Understandable, thanks for letting us know and don't get disheartened. Try looking into the issues labeled as good first issue!

**Comment by corp-0** [comment]
should have been fixed by #7749, please ask me to reopen if the issue persists
