### ISSUE TITLE
Shuttle console radar not refreshing

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7577]
### Environment
- Build Version is: 21101020:
- Mac_Catalina_10.15.7 

### Detailed description of bug
Radar does not update as shuttle moves

### Steps to reproduce

1. Jump in a shuttle prep it for flight
2. Watch the radar as you go
(Walking away from the console and then reopening it refreshs the location, but it won't stay that way once you start flying again.)

Starting point (Note the Cargo shuttle can be seen on screen)
![Screen Shot 2021-10-15 at 12 13 22 PM](https://user-images.githubusercontent.com/92214971/137527097-3b4ccc71-b925-4d60-929d-01b13ab81692.png)

Flew West a bit (The Cargo shuttle is still present)
![Screen Shot 2021-10-15 at 12 14 06 PM](https://user-images.githubusercontent.com/92214971/137527324-25a1e0bc-bb23-4420-b482-9aecd96c4876.png)

Flew around the station (Cargo shuttle still)
![Screen Shot 2021-10-15 at 12 51 46 PM](https://user-images.githubusercontent.com/92214971/137531390-3725c9d7-a74d-41b2-9b5a-4c898a34277d.png)

Walked away from console and then reengaged it (Radar finally refreshed)
![Screen Shot 2021-10-15 at 12 53 38 PM](https://user-images.githubusercontent.com/92214971/137531611-f4bff34d-f29a-4b7c-b896-5067f784e852.png)

**Comment by corp-0** [comment]
I need someone else to reproduce this error, hopefully on another OS

**Comment by Leander-0** [comment]
OS Version: Arch linux

tested on the staging server as always, somehow when i use the emag on the console the bug goes away.


https://user-images.githubusercontent.com/80334192/137536175-8f4d0270-f17e-468d-ad75-2652184a1854.mp4

**Comment by corp-0** [comment]
thank you, adding this to the bad bugs list

**Comment by NoooneyDude** [comment]
Hi @Q4ik, can you still reproduce this? I recently fixed an NRE in the GUI code.

**Comment by corp-0** [comment]
we need to know if this is still happening

**Comment by NoooneyDude** [comment]
Q4ik confirms in Discord a-ok now.
