### ISSUE TITLE
Nuke disk be gone

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7579]
### Environment
Build Version is: 21101020:
- Mac_Catalina_10.15.7  

### Detailed description of bug

Double wrapping the nuke disk causes it to teleport to 0,0 though it isn't there to retrieve

### Steps to reproduce

1. Grab the nuke disk and some wrapping paper
2. Wrap it twice

![image](https://user-images.githubusercontent.com/92214971/137538906-00c6b336-c1bb-452f-8595-63555cc3cd24.png)

**Comment by Daxam12** [comment]
I have fixed this issue.
