### ISSUE TITLE
Shutters just look shut

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7586]
### Environment
- Build Version is: 21101607. 
- OS Version:_Mac_Catalina_ 10.15.7

### Detailed description of bug

Shutters will not open when their button is engaged

### Steps to reproduce

1. Try opening any shutter with it's corresponding button

**Comment by Q4ik** [comment]
Correction- They just appear shut. You cannot hear or see them opening or closing, but you can pass through.

**Comment by Q4ik** [comment]
No button animation when it's pressed either

**Comment by Q4ik** [comment]
![Screen Shot 2021-10-16 at 10 00 09 AM](https://user-images.githubusercontent.com/92214971/137592268-3c734143-0e33-4c1a-99e3-9253cfdf0a3b.png
![Screen Shot 2021-10-16 at 10 00 15 AM](https://user-images.githubusercontent.com/92214971/137592274-4d7a78d0-bad5-4028-9c89-f7506b00fb33.png)
)

**Comment by Q4ik** [comment]
On a local game you can walk through the appearing closed shutter, but not on regular server play

**Comment by corp-0** [comment]
this should have been addressed by Bod's #7588

**Comment by Q4ik** [comment]
Cheeeers

**Comment by ThatDan123** [comment]
If this still happens say and i'll reopen this.
