### ISSUE TITLE
Fire airlocks are silent and invisible 

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7587]
### Environment
- Build Version is: 21101607. 
- OS Version:_Mac_Catalina_ 10.15.7

### Detailed description of bug

Airlocks connected to fire alarms do not appear in a closed state nor do you hear them opening or closing.
### Steps to reproduce

1. Goto a fire alarm and engage it
2. Attempt walking through an airlock that it controls. (Hit the fire alarm again, or use a pry bar to open them
![Screen Shot 2021-10-16 at 9 37 29 AM](https://user-images.githubusercontent.com/92214971/137591757-f25fd517-54d1-4818-867f-602f76816af2.png)
)

**Comment by Q4ik** [comment]
No fire alarm animation either

**Comment by Aranclanos** [comment]
Can't reproduce

**Comment by mmails** [comment]
Can't reproduce either

**Comment by ThatDan123** [comment]
> Can't reproduce

Did you test late joining when they are already closed?

**Comment by Aranclanos** [comment]
yes

**Comment by ThatDan123** [comment]
Unreproducible so closing
