### ISSUE TITLE
the sun in a lightbulb or how i learned to not touch the shinny thing

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7592]
### Environment
- Game Version: Staging 21101607
- OS Version: Arch linux

### Detailed description of bug

Lightbulbs deal the comically large damage of 10 burn, for balance reasons it should be changed to 1 damage.

here an example of your average moth crew touching the shinny bulb:

https://user-images.githubusercontent.com/80334192/137604595-14c6ed2d-a408-4bca-b64e-a4d69fa8260a.mp4

### Steps to reproduce

1. touch the lightbulb
2. ???
3. die

**Comment by PerfectTangent** [comment]
why 1 in particular?

**Comment by MaxIsJoe** [comment]
> why 1 in particular?

![image](https://user-images.githubusercontent.com/34368774/137605479-c130d7c3-69ec-4538-9f09-12c4665ce807.png)
On /tg/ the values of burn damage is randomly between 0 to 10, on /tg/ players could kill themselves if they keep touching light bulbs constantly for over 10 seconds which is stupid in my opinion.

It's better if we dropped this to a more sane number that won't cause someone to go to crit and isn't doing damage numbers that's near what a knife has.
Touching light bulbs should not kill you, it should just do slight damage to warn you that yes, this is hot.

**Comment by VernaSaurus** [comment]
actually it does 5 damage, i'm not sure where the 10 comes from

**Comment by VernaSaurus** [comment]
wait i think i got it
it does 5 on first touch, but then it does 10 damage if you touch it again(?) and removes the bulb

**Comment by MaxIsJoe** [comment]
> actually it does 5 damage, i'm not sure where the 10 comes from

this is from their **own source code**

**Comment by Q4ik** [comment]
I can see a lightbulb doing more damage to moths, but a human losing an arm over one is just hilarious.
![image](https://user-images.githubusercontent.com/92214971/137605583-829966e6-cf34-4018-b305-ac95f0d36b35.png)

**Comment by VernaSaurus** [comment]
> wait i think i got it it does 5 on first touch, but then it does 10 damage if you touch it again(?) and removes the bulb

this actually only happens if you have the lightbulb remover trait, otherwise it just does the 5 damage

**Comment by PerfectTangent** [comment]
> I can see a lightbulb doing more damage to moths, but a human losing an arm over one is just hilarious.

yeah, should not be possible once the number is lower than 10

**Comment by Leander-0** [comment]
> why 1 in particular?

maybe 1 is too low, something like a random number between 1-3 could be enough.

also its the goddam future and we still use incandescent bulbs instead of LED?! those NT guys truly cut off budget on everything
