### ISSUE TITLE
AI doesnt have clearance for Consoles/ACUs

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7602]
### Environment
- Game Version: Staging 21101712
- OS Version: Arch Linux

### Detailed description of bug

AI role players dont have ID checks for the sec, cargo, hop, announcement and the ACUs

https://user-images.githubusercontent.com/80334192/137637062-1cb88ce1-e7be-4e74-99c3-da7ce6ba45ce.mp4

### Steps to reproduce

1. try opening the sec console
2. try buying stuff from cargo
3. try changing atmos with the ACUs

**Comment by PerfectTangent** [comment]
duplicate of #7172
