### ISSUE TITLE
Gas from nowhere 

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7603]
### Environment
- Build Version is: 21101712. 
- OS Version: Mac_Catalina 10.15.7

### Detailed description of bug

Although no gas is being pumped into the mix room, O2 and N2 is continuously being created there.

### Steps to reproduce

1. Insure no gasses are flowing into the breathing air mix chamber.
2. Take some measurements on the output pipe. The pressure continues to increase.

(You can evacuate the mixing room of all gas, but it will continue to produce. Also, the corresponding ACU does not tell the true tale of what's going on in the that room.)

https://user-images.githubusercontent.com/92214971/137642026-81d3b1d3-36f7-456e-bce1-57503d7b332f.mp4

**Comment by Q4ik** [comment]
This may tie in with https://github.com/unitystation/unitystation/issues/7552

**Comment by ThatDan123** [comment]
It looks like the canister is still emptying?

**Comment by Q4ik** [comment]
Yeah that has to be what's going on.
