### ISSUE TITLE
movement between matrices isnt smooth

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7611]
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

when you move between a shuttle and space or the station there is a 1 second delay once you move to the other matrix

https://user-images.githubusercontent.com/80334192/137819399-24029935-9c34-4ae7-aa1d-2b099f1d7ac8.mp4

this also happens as a ghost

### Steps to reproduce

1. move back and forth a shuttle and space

**Comment by PerfectTangent** [comment]
redundant with #5553, closing.
