### ISSUE TITLE
players with active magboots cant go inside lockers

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7617]
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

if you have mag boots active your character doesn't go inside lockers

https://user-images.githubusercontent.com/80334192/137836660-0a09675f-bbf8-45fb-8346-ccbd122736a6.mp4

### Steps to reproduce

1. get the drip
2. activate drip
3. your drip is too strong you cannot go inside lockers now

**Comment by NoooneyDude** [comment]
I don't think there's an elegant solution for this. We check if the object is pushable (i.e. not secured) when determining whether something can be stored. Magboots set this property false.

We could add in a check for players excluding this property check, I suppose.
