### ISSUE TITLE
mobs placed inside lockers will teleport to 0,0 and still be active

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7618]
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

when a mob is placed inside a locker this one is teleported to 0,0 and then roams free around space

https://user-images.githubusercontent.com/80334192/137837295-65ff4312-e702-4720-8c86-c13cd4d714be.mp4

tested with mokey and xeno queen

### Steps to reproduce

1. find mob
2. place it inside locker
3. tada! magic done

**Comment by NoooneyDude** [comment]
Fascinating. I added a return at https://github.com/unitystation/unitystation/blob/9cb4c6b70afe83a16ef5f2159ce3aa47786b7fb2/UnityProject/Assets/Scripts/NPC/AI/MobAgent.cs#L205-L212, so it is interesting to see them continue to move even though they have a `parentContainer` assigned. I tested with mice. Does this bug occur with them too? Might be a prefab thing?

**Comment by pyrosshade** [comment]
I have a fix for this and other issues on my local branch at the moment, requesting assignment on this.
