### ISSUE TITLE
bleeding/low blood level warning icon B:75

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7629]
### Description

This bounty calls for the implementation of the bleeding status icon. With the more advanced bloodstream model added to the game in the health refactor and the trauma system additions, it's crucial to deliver better feedback to players about how badly they are bleeding.

This warning should evaluate all sources of bleeding occurring in a character's body and escalate the bleed icon as needed to communicate the total bleed rate, and update or clear the alert as the bleeding rate increases or decreases.

Once a character's blood level is particularly low, the blood icon lingers on the screen even if there is no active bleeding, though it no longer blinks bright red if there is no active bleeding.

here is the most up-to-date version of the bleed icons
![bleedicon](https://user-images.githubusercontent.com/68730437/138218423-e9da214b-62cc-4796-9067-91328c59c8da.png)

## What is needed to fulfill the bounty:

- [x] add the bleeding warning to the game.

**Comment by VernaSaurus** [comment]
i'd like to take this, i need UI experience anyway

**Comment by PerfectTangent** [comment]
sounds good, you have been assigned.

**Comment by PerfectTangent** [comment]
bont bump t 75 USD b/c scope embiggened.
