### ISSUE TITLE
Trying to move in a wrapped-up locker teleports you to 0,0.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7634]
### Environment
- Game Version: Staging 21101813
- OS Version: Windows 10

### Detailed description of bug
Title. Trying to move while in a wrapped-up locker teleports you to 0,0. This usually kills the player since 0,0 is often at the vacuum of space.

### Steps to reproduce
1. Have someone put you in a locker and have them wrap the locker up with wrapping paper.
2. Try to move in the wrapped up locker.
3. Get sent to 0,0. Likely end up in space and start dying.

**Comment by NoooneyDude** [comment]
Yep, packages should be updated to use ObjectContainer sometime too. I suspect some additional functionality will be required for the component / IEscapable.

**Comment by corp-0** [comment]
I should be able to update wrapping code to use new container script

**Comment by NoooneyDude** [comment]
That'd be great if you give it a go. Am in the middle of disposals conversion but was going to take it up next. 👍

**Comment by pyrosshade** [comment]
I have a fix for this and other issues on my local branch at the moment, requesting assignment on this.
