### ISSUE TITLE
Admin heal (aheal) doesn't automatically return ghost players to their bodies.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7637]
### Environment
- Game Version: Staging 21101813
- OS Version: Windows 10

### Detailed description of bug

Title. Ahealing dead players does not automatically return them to their bodies if they are ghosts. They can still return to their now living bodies as ghosts, but they will have to do that manually. Notably, defibs do return players to their bodies if they are ghosts.

### Steps to reproduce
1. Have an admin present.
2. Die. Try moving in order to become a ghost.
3. Have the admin aheal you. Your old body will be alive again, but you will continue being a ghost.

**Comment by Aranclanos** [comment]
Game Version: Staging 21-10-18-13, aka 13pm 7 days ago

fixed in #7607, the server version didnt have this change since it was merged near 11 hours after the build was done
