### ISSUE TITLE
Refactor movement scripts

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#7639]
Player objects currently have their own movement/position script: `PlayerMove`/`PlayerSync`, while all other objects use `CustomNetTransform`. If players really need their own movement script (I understand this might stem from movement for players is requested client-side, and we need client prediction), then they should at least be restructured such that we don't need to check what kind of object it is before we try and manipulate it. Even a quick interface for mapping of basic commands like positioning would be useful.

I think a lot of the movement code could be cleaned up in general.

**Comment by Aranclanos** [comment]
PlayerSync & CustomNetTransform are basically copypastes with tiny differences
Another point about movement code is how the position is tracked across around 8 different variables

**Comment by NoooneyDude** [comment]
Yeah. Just noticed we have an `IPushable` interface which somewhat helps cover the gap in the meantime.

**Comment by ThatDan123** [comment]
Bod refactored the whole system and now theres a base class. So gonna close this now
