### ISSUE TITLE
CO2 filter get's clogged

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#7662]
### Environment
- Build Version is: 21102523 (Fallstation). 
- OS Version: Mac_Catalina_ 10.15.7

### Detailed description of bug

Newly made gasses get clogged at CO2 filter

### Steps to reproduce

1. Make some new gas and capture it in the overflow tank. (Trit, BZ, and/or Nitryl)
2. Allow new gasses to recirculate through your system.
3. It will clog at CO2 filter

https://user-images.githubusercontent.com/92214971/138807728-670a51cc-f85d-4597-a7b5-7870622f93e7.mp4

.

**Comment by Q4ik** [comment]
If you scan the clogged filter it will show you the pressure in the line, but will say that it's all CO2. Set the filter to something like freon to free it up and it will put the gasses back in the overflow.

**Comment by PerfectTangent** [comment]
is this just a problem specific to Fallstation?

**Comment by Q4ik** [comment]
We should be able to close this one now. Sorry I just saw your comment @PerfectTangent. It may have happened on Square as well
