### ISSUE TITLE
Microwaves make a punching noise

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#7668]
### Environment
- Game Version: Staging 27-10-2021
- OS Version: Manjaro Linux

### Detailed description of bug

Microwaves make a punching sound when used.

### Steps to reproduce

1. Add or remove something from it
2. hear the noise

**Comment by PetMudstone** [comment]
Oh yeah I'm pretty sure it's a placeholder sound in the absence of actual microwave open and closing sounds.
