### ISSUE TITLE
Blob doesnt deal damage and cannot be hit by proyectiles

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7671]
### Environment
- Game Version: Staging 21102523
- OS Version: Arch Linux

### Detailed description of bug

Blob is kinda unplayable right now on staging because it cant deal damage on players and players can only damage the blob via melee

https://user-images.githubusercontent.com/80334192/139167737-87cb7a3f-bef3-4330-badb-c531adaa323c.mp4

also when you explode as a blob all your body parts stay on top of the core and looks kinda weird.

### Steps to reproduce

1. become blob via admin 
2. try to kill a player
3. let a player shoot you

**Comment by Aranclanos** [comment]
Fixes in #7677
