### ISSUE TITLE
blob can win by hidding on a asteroid

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7675]
### Environment
- Game Version: Staging 21102523
- OS Version: Arch Linux

### Detailed description of bug

if you spawn as a job that has easy access to a shuttle you can go to an asteroid quick enough to explode there and if the asteroid is big enough no one will notice you on the asteroid and you will win the round by doing nothing.

example here the QM got his mining shuttle and drove off to the nearest asteroid:

https://user-images.githubusercontent.com/80334192/139283281-e4490cdb-28cf-434e-9b0f-8cdbfb2cc900.mp4

### Steps to reproduce

1. become blob
2. go fast to an asteroid
3. become blob and win easy

**Comment by ThatDan123** [comment]
Fixed by #7677
