### ISSUE TITLE
Wearing black gloves no longer protects you from being burnt by light bulbs.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7688]
### Environment
- Game Version: Staging 21102918
- OS Version: Windows 10

### Detailed description of bug
Title. Black gloves no longer protect you from being burned by light bulbs.

### Steps to reproduce

1. Wear black gloves.
2. Click on an active light bulb.
3. Get burned.

**Comment by MaxIsJoe** [comment]
>Adds the black glove trait that's missing to all gloves
>Black gloves ironically are the gloves that don't get that trait

I can't be mad because this is too funny

**Comment by PetMudstone** [comment]
![image](https://user-images.githubusercontent.com/38266309/139558954-ac9a0964-4896-4cbf-bc98-bd2ec870d399.png)
Black gloves do have the BlackGloves item trait. From what I can tell, the code that checks whether you're wearing black gloves or not hasn't been updated to utilize dynamic inventory slots.
