### ISSUE TITLE
Everyone on Staging sometimes simultaneously becomes stuck. B:75

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7689]
### Environment
- Game Version: Staging 21102918
- OS Version: Windows 10

### Detailed description of bug

Recently on Staging, every single player has simultaneously become stuck. From the player's point of view they can still move, but after moving too far or trying to interact with something they will slowly slide back to their original position. Teleporting players sometimes fixes this, but it's not guaranteed.

### Steps to reproduce

1. Play on Staging for a while.
2. Suddenly become stuck to your position.

**Comment by PerfectTangent** [comment]
This is being promoted to bounty status, valued at 75 USD.

**Comment by PerfectTangent** [comment]
Closing as it seems to have been successfully fixed by #7710. Bounty paid to Aranclanos.
