### ISSUE TITLE
Players inside morgues appear on the morgue itself and not its tray when they are opened.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7705]
### Environment
- Game Version: Staging 21102918
- OS Version: Windows 10

### Detailed description of bug

Title. When morgues are opened, players appear on the same tile as the morgue and not on the tray. Notably this does not affect items nor dead mobs, who will appear on the tray as they should.

![morgue](https://cdn.discordapp.com/attachments/668605946691452949/904902505157230592/MorgueBug.gif)

### Steps to reproduce
1. Enter a morgue.
2. Exit the morgue.
3. See that you appear on the morgue itself and not the tray.

**Comment by MaxIsJoe** [comment]
Hey I fixed this along side a few new parity features im adding, it's gonna take a short while because Im fixing other game breaking stuff as well.

**Comment by corp-0** [comment]
closing then, thanks for letting me know
