### ISSUE TITLE
Blobby issues on staging

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7711]
### Environment
- Game Version: Staging 21110213
- OS Version: Arch Linux 

### Detailed description of bug

There is many issues on staging related with the blob, most notably:

1. When you press the re-adapt strain you will get kicked out of the server

https://user-images.githubusercontent.com/80334192/139920982-b72314a1-37b4-4cb1-a4a7-1ed24e194a5d.mp4

2. The Biohazard Alert its being spammed every 30s once the blob reaches the size to trigger it.
![blob](https://user-images.githubusercontent.com/80334192/139921165-997dea4f-1fe4-4b1f-ba9c-82f0ad0b93b5.png)

3. once you destroy the core the blob the server doesnt register the blob death

### Steps to reproduce

1. become blob
2. press readapt strain
3. get kicked out!

**Comment by PerfectTangent** [comment]
@Leander-0 please, break up bug reports into separate issues. Issues are tickets, meant to be retired when they have been completed and reopened if problems reoccur. When an issue covers more than one problem, it muddies the ability to clearly reopen and report new information.

**Comment by Leander-0** [comment]
Oh alright my bad, closing this then
