### ISSUE TITLE
The Gasping Dead

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7730]
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

When players die their corpses wont stop gasping out and bleeding out.

https://user-images.githubusercontent.com/80334192/140237358-6fc15e52-b20f-48a5-966b-fb1a47d26c3f.mp4

### Steps to reproduce

1. kys by any means available
2. as a ghost watch the chat getting spammed with your corpse gasping for air

**Comment by mmails** [comment]
Thought this had been fixed already

**Comment by PerfectTangent** [comment]
> Thought this had been fixed already

well, it's from build 21110300. Was a PR merged in the last 24 hours that fixes the problem?
