### ISSUE TITLE
Placing a new organ makes you bleed

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7731]
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

When you place a new organ you will start bleeding again.

https://user-images.githubusercontent.com/80334192/140237769-cc45aaed-8d9a-4949-a78b-e22d162fd703.mp4

### Steps to reproduce

1. spawn new organ/place back removed one
2. check blood

**Comment by corp-0** [comment]
is this still happening?

**Comment by Leander-0** [comment]
just tested it, doesnt happen anymore
