### ISSUE TITLE
tesla generator doesnt generate power

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7733]
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

I encourage to try and replicate if im wrong but as far as i tried i havent been able to produce power with the tesla generator.

https://user-images.githubusercontent.com/80334192/140250446-28a254a2-2577-40c7-813a-1d5798227174.mp4

here i tried to make a simple tesla gen, the lightning hits the generator and rod but it doesnt produce any power and i checked directly with the multitool over both the wires and generator.

also something very important i noticed with the tesla generator it that when analized with the multitool it shows RadiationCollector instead of TeslaGenerator

![tesla2](https://user-images.githubusercontent.com/80334192/140250718-caa70627-dfd2-4ae4-90d7-9a9571445e64.png)

### Steps to reproduce

1. make tesla engine 
2. wire it up tot he power grid
3. start itand check voltages and amps

**Comment by corp-0** [comment]
I need to know if this is still reproducible

**Comment by Leander-0** [comment]
https://user-images.githubusercontent.com/80334192/146661954-d83a1615-4a5a-40c1-afc8-d5967ca1a04b.mp4

tried again on latest staging, didn't manage to generate power, the lightning bolts did not hit the tesla generators even when the tesla was at stage 5 or more, all was connected and welded properly.

**Comment by MaxIsJoe** [comment]
> output.mp4 
> tried again on latest staging, didn't manage to generate power, the lightning bolts did not hit the tesla generators even when the tesla was at stage 5 or more, all was connected and welded properly.

Any errors?

**Comment by Leander-0** [comment]
server restarted before i could check the errors but i can give the player logs over discord, besides that when i analyzed the tesla coil with a multitool it said RadiationCollector instead of TeslaCoil or something like that.

**Comment by MaxIsJoe** [comment]
locally everything seems to be working just fine
was unable to find any reason for why it's not working on headless servers
