### ISSUE TITLE
You get stuck on the edges or shuttles/asteroids on space

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7734]
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

when you are on space and move around the shuttle or asteroid once you try to get out of it by moving to an edge of the asteroid/shuttle you will get stuck on place.

https://user-images.githubusercontent.com/80334192/140251546-7409a1f8-682a-4fc8-a166-8486e791a58e.mp4

### Steps to reproduce

1. find shuttle/asteroid
2. move outside on space
3. get stuck

**Comment by AtnerNT** [comment]
Old movement issue, havent heard of anyone having this issue
