### ISSUE TITLE
If you remove any internal organ you cannot click on yourseft to drink/eat

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7742]
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

When you remove an organ via surgery you will be unable to drink from cups and feed yourself via clicking on your character even other player will not be able to force feed you.

### Steps to reproduce

1. drink before sugery 
2. remove an organ
3. try to drink/eat

**Comment by corp-0** [comment]
what organ?

**Comment by Leander-0** [comment]
mistyped, basically any internal organ
