### ISSUE TITLE
A better way to assign forever IDs.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7747]
### Description
Right now assigning new forever IDs for objects is tedious, "Assign random ID" in the Prefab Tracker component doesn't actually work, and there's no way to assign every single prefab its own ID automatically. I believe this could be rectified by the Assign random ID button actually working, and by having SpawnableListTest automatically assign new IDs to any prefabs that fail the test.

**Comment by Bod9001** [comment]
fixed in  #7749 
though needs tests

**Comment by PerfectTangent** [comment]
yeah, seems fixed.
