### ISSUE TITLE
Hacking is very easy/broke on staging 

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7751]
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

hacking right now is extremely easy without counting that it might be broken right now on staging, anyone can simply cut all the wires on the door and easily open it with a crowbar without a way to close back the door.

https://user-images.githubusercontent.com/80334192/140598344-600b11da-ffb8-444f-adc4-82d6eeb3b87f.mp4

didn't got shocked or anything

### Steps to reproduce

1. open door panel
2. cut off all wires
3. use crowbar on door

**Comment by VernaSaurus** [comment]
also once the door bolts drop there's no way to raise them again

**Comment by Maximal98** [comment]
and if someone figures out which wire is the power wire, it gets even dumber because you can just cut one wire and "hack" into rooms

**Comment by Bod9001** [comment]
Fixed in #7749
