### ISSUE TITLE
Box station kitchen starts upowered due to hungry and angry mice

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7758]
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

At round start a mice will eat all the low voltage cables in the kitchen maint leaving it completely unpowered.

https://user-images.githubusercontent.com/80334192/140615922-f3261b44-0ad0-4870-b79a-f9598b7892c1.mp4

this happens because the mouse initial mood level is set to 0

### Steps to reproduce

1. start round in box station
2. check wires in kitchen maint
3. check mouse MobMood levels with VV

**Comment by corp-0** [comment]
To solve this:
- Find the mouse prefab in unity editor
- Change its initialMoodLevel from 0 to 100 in the MobMood component
