### ISSUE TITLE
Recursive lockers

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7760]
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

you can place lockers and crates inside other lockers

https://user-images.githubusercontent.com/80334192/140616185-ab2a87d1-2c6a-48d8-b760-8450dee2fbce.mp4

### Steps to reproduce

1. take locker
2. place locker inside locker
3. repeat step 2 until not possible anymore

**Comment by ilinm1** [comment]
PR with a fix soon

**Comment by pyrosshade** [comment]
I have a fix for this and other issues on my local branch at the moment, requesting assignment on this.
