### ISSUE TITLE
naughty attributes.buttons don't seem to work

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#7761]
added naughty attributes.buttons to a function, 
observe lack of existence in editor in Inspector

**Comment by corp-0** [comment]
Is it all of them or some in particular? I know if you do custom editors for components then naughtty attributes won't work

**Comment by Bod9001** [comment]
haven't tested too much but stuff like, door hacking 
HackingProcessBase  
it doesn't seem to work

**Comment by corp-0** [comment]
if they use a custom editor, then that might be the cause. There is a way to make it work with custom editor but I haven't ever had luck trying it.

**Comment by ThatDan123** [comment]
They don't work on network behaviours as mirror has a custom inspector for them

**Comment by Bod9001** [comment]
can we make the custom inspector inherit from naughtyattributes?

**Comment by corp-0** [comment]
we would have to modify mirror's source code which I would avoid every time it is possible
