### ISSUE TITLE
Lasers gib people when shot to the chest

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7772]
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

as the title says, lasers can easily vaporize the players limbs specially the chest where the player get gibbed and unable to being cloned back.

https://user-images.githubusercontent.com/80334192/140856206-b03baf79-58ab-4916-b866-c55a462768d6.mp4

### Steps to reproduce

1. spawn laser gun
2. shoot at the chest

**Comment by corp-0** [comment]
I'm adding this to playability project because although it isn't game breaking it makes the experience worse for the players

**Comment by MaxIsJoe** [comment]
This has been fixed during one of Bod's PRs.

**Comment by MaxIsJoe** [comment]
https://github.com/unitystation/unitystation/pull/7967
