### ISSUE TITLE
You can no longer anchor objects to the ground.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7790]
### Environment
- Game Version: Staging 21111003
- OS Version: Windows 10

### Detailed description of bug

Title. You can no longer anchor objects to the ground, doing so will have the game tell you that you need to do it on an actual floor instead of space even if there is a floor present.

### Steps to reproduce

1. Grab a wrench.
2. Find a locker.
3. Use wrench on locker, be told that there is no floor to anchor the locker to even though there is a floor.

**Comment by VernaSaurus** [comment]
That's... bizzare. I literally just added fermenting barrels and the ability to wrench them down and it worked just fine.

**Comment by PetMudstone** [comment]
An example.
![image](https://user-images.githubusercontent.com/38266309/141243971-79e86501-d8b2-42ea-9aa0-c127a0571803.png)

**Comment by Aranclanos** [comment]
can't reproduce, tried as a client on both fallstation and square

**Comment by Aranclanos** [comment]
nvm! found it
