### ISSUE TITLE
Add basic gibbers.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7793]
### Description

Gibbers gib whoever is put inside them and turns them into raw meat. How much meat they produce, what kind of meat they produce, and when they can turn people into meat is dependent on various factors.

Three key variables:
- meat_produced = 2 + matter bin rating.
- gibtime = 4 seconds - (0.5 seconds * manipulator rating).
- ignore_clothing = boolean, false by default but true if manipulator rating is 2 and above.

Clicking and dragging people onto gibbers will make you attempt to put them inside the gibber unless they are buckled to something or are wearing clothes while "ignore_clothing" is false. When 4 seconds pass, they will be put into the gibber.

Using the gibber with an empty hand will turn it on unless it is unanchored. In this state, it will start operating (during which it uses 1000 power and will visibly shake like the food procesor) and will gib the occupant after "gibtime" elapses. When the occupant is gibbed, gib decals will spawn and the gibber will spit out a number of meat slabs proportionate to "meat_produced" and 1 skin.

What kind of meat is produced and what skin is produced, if any, is dependent on the species put into the gibber. Humans give human meat and human skin, lizards give lizard meat and lizard skin, etc.

When examining the food processor, chat will print: "The status display reads: Outputting <b>[meat_produced]</b> meat slab(s) after <b>[gibtime]</b> seconds of processing."
If the manipulator is at least tier 2, then it will also print: "Gibber has been upgraded to process inorganic materials."

There is a different light overlay used depending on the gibber's state. If the gibber is on and idle, it uses "gridle". If it has an occupant, it uses "grjam", if it is operating, it uses "gruse". If it is unpowered, there is no overlay.

**Comment by MaxIsJoe** [comment]
Might work on this
