### ISSUE TITLE
Move the "Select Character" button

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#7799]
![4sF0Nja](https://user-images.githubusercontent.com/36482335/141350980-bfa70671-7880-4d2a-8cd5-297f5cca05c4.png)

**Comment by CdrCross** [comment]
I don't know why the "Select this character" button is in the top right, but it defies all convention and common sense. It should be moved to be in-line with the rest of the button, but still green.

**Comment by PerfectTangent** [comment]
lol, this is the same issue as #8508. You opened the same one twice, with a different graphic for each. Closing as this was done in #8512.
