### ISSUE TITLE
Some Objectives are broken

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#7814]
Reported on discord 

![image](https://user-images.githubusercontent.com/56727168/141690271-3fb3c27f-119a-4ff1-b6b6-53f159932bf1.png)

Player said they had the items and were on the shuttle when docked.

-Might be an issue with the recursive container checking, for the items.
-Unsure of the escape one as that code seems like it should work, needs debugging.

Needs investigating, unsure if you can just spawn as traitor using admin tools and then seeing if objectives complete.

**Comment by PerfectTangent** [comment]
reported to still be a problem recently.

**Comment by MaxIsJoe** [comment]
Was able to recreate the stealing issue and working on a fix for it currently.

I cannot replicate the shuttle issue however so I assume it's been already fixed by the previous PRs
