### ISSUE TITLE
Eating anything botany related insta-fills you and makes you morbidly obese

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7828]
### Environment
- Game Version: Staging 21111506
- OS Version: Arch Linux

### Detailed description of bug

Almost all foods that are botany grown fills you soo much that you become incredibly slow and negatively impacts the player

### Steps to reproduce

1. go to botany
2. eat 1 mushroom
3. become nikocado avocado

**Comment by ghost** [comment]
I was unable to reproduce this bug with any mushrooms or other botany produce, so it has probably been fixed.
