### ISSUE TITLE
Mobs attack cooldown is broken, making mobs way too deadly. B:40

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7830]
### Environment
- Game Version: Staging 21111506
- OS Version: Arch Linux

### Detailed description of bug

Mobs when they attack you can hit you twice in a single second and some are incredibly overpowered.

here you can see a live CCTV footage of your average spaceman getting decimated by a goat.

https://user-images.githubusercontent.com/80334192/142127345-f63ca864-f024-4583-b7b7-19ed4fe1cc39.mp4

### Steps to reproduce

1. go to the kitchen/spawn a goat
2. punch goat
3. die by the goat

**Comment by PerfectTangent** [comment]
after doing some investigation, it looks like the mob attack cooldown stat does nothing. A mob will attack at the same rate no matter what the cooldown is set to.

**Comment by PerfectTangent** [comment]
making this a bounty.

**Comment by CdrCross** [comment]
This issue remains a serious problem as of the 26/03 playtest. Glad to see the higher profile it just got.
