### ISSUE TITLE
matrices have tendencies of spawning on top of each other

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#7840]
can't think of a good way of handling this may be when, new map system is in we can handle it better the

**Comment by ThatDan123** [comment]
sure its not an issue with the asteroid scene distant checks?

**Comment by Bod9001** [comment]
could be that too but,  this should be universal solution where it shouldn't allow any matrix to spawn on top of another one

**Comment by AtnerNT** [comment]
Haven't encountered this issue in a long time, has it been addressed?

**Comment by MaxIsJoe** [comment]
Hasn't happen all year on any playtests, we can safely assume that it's fixed.
