### ISSUE TITLE
Server Hosts should have the option to whitelist their playerbase

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7861]
### Description

There will surely be community servers down the road that will want to require players to apply to play on their server.

**Comment by ThatDan123** [comment]
There is a whitelist already, needs a player ID's

**Comment by PerfectTangent** [comment]
https://www.youtube.com/watch?v=S02BHmWPZNs

**Comment by PerfectTangent** [comment]
I asked on behalf of the U797 guys. I'll let them know it already exists.
