### ISSUE TITLE
MacOS builds should be bundled in a .app - stationhub#119 B:100

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7926]
This issue is the bounty version of: https://github.com/unitystation/stationhub/issues/119

### Description
Currently we're building the application as a self-contained app and making Mac users execute it as is, when the proper way to distribute osx apps is to bundle them in a .app container.

To fullfill this bounty PR to the stationhub repo with a version that follows these steps: https://docs.avaloniaui.net/docs/distribution-publishing/macos . Also make sure our CI workflow takes in consideration the different steps required to build the application for MacOS.

**Comment by jamessimo** [comment]
Do we have an Apple developer account for hardendruntime and co-signing the app?

**Comment by corp-0** [comment]
we don't

**Comment by corp-0** [comment]
I'm increasing the bounty to 100 usd
