### ISSUE TITLE
Disposal Piping not deconstructable.

### ISSUE THREAD

**Issue by GDAWS696** [unitystation/unitystation#7937]
### Environment
- Game Version: 21120614
- OS Version: Windows 10

We tried deconstructing disposal pipes after someone got stuck in a constructed disposal pipe loop via input chute we tried welding them off and wrench but it didnt seem to do anything, we examined the disposal pipe to see if the decription changed and it says its still welded on the floor as we cannot wrench them off if their still welded,  Logs did not make new errors when replicating it.

### Steps to reproduce

Essentially construct a disposal pipe, wrench and weld it on the floor weld it again to remove and it refuses to be removed as it cannot be wrenched and still considered welded.

Ive posted a screenshot here for an Idea since we couldnt remove the disposal pipe.

![Screenshot (271)](https://user-images.githubusercontent.com/49326697/145109536-1f649fdc-3f4b-4f13-85ac-7f6d7aece67f.png)
d

**Comment by jamessimo** [comment]
Possibly related to https://github.com/unitystation/unitystation/issues/4676
