### ISSUE TITLE
Mousetraps are not triggered by NPC mobs, which means they don't work on mice.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7956]
### Environment
- Game Version: 21121104

### Steps to reproduce

1. place armed mousetraps in the path of a mouse
2. watch as the mouse cleanly walks past them.

**Comment by MaxIsJoe** [comment]
Dan said he's working on a fix for this

**Comment by ThatDan123** [comment]
Fixed in #8070
