### ISSUE TITLE
Armed mousetraps should prevent a character from opening a bag until all the mousetraps have been triggered or the player uses disarm intent

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7958]
### Environment
- Game Version: 21121104

### Detailed description of bug

When you place armed mousetraps inside a bag, they act as a frustrating denial mechanic by snapping on players unless they use the proper procedure (using disarm intent) to open the bag. Otherwise, it prevents them from properly opening it.

With the current implementation, a character will get snapped by the first trap, but can simply remove and disarm the rest once they have the bag open

### Steps to reproduce

1. open a bag with multiple armed mousetraps
2. get snapped by first trap
3. you are now free to remove the rest without incident.

**Comment by MaxIsJoe** [comment]
Add this to my project, going to be working on it.
