### ISSUE TITLE
Station Bounced Radio chat message format is a mess

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#7959]
### Environment
- Game Version: 21121104

### Detailed description of bug

the SBR sprite is cut off, the message repetition number picks a different spot to show with each message, 

![Screenshot 2021-12-11 142232](https://user-images.githubusercontent.com/68730437/145689032-cc8418b7-a4ce-4dab-bba9-3fe3b5bf51f3.png)

In this example, we had 2 radios adjacent to eachother, hence the chat repeated 4 times. 

### Steps to reproduce

1. use a station bounced radio

**Comment by MaxIsJoe** [comment]
whoops, looks like the icon broke again.
On it
