### ISSUE TITLE
Barrage of immovable rods at round start

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation#7976]
### Environment
- Game Version: 21121104
- OS Version: windows

### Detailed description of bug

on round start the server automatically spawns immovable rods at round start, and doesn't stop. it seems to only stay on the fair left side of the station and slowly moves over

### Steps to reproduce

1. start/restart around

2. follow the sounds of explosions 

![1](https://user-images.githubusercontent.com/15893891/146061735-e577b2a5-80b4-4f47-ac1b-faab3e378a84.png)

![2](https://user-images.githubusercontent.com/15893891/146061739-57de5a4e-5757-449a-83e9-8bd126684ebb.png)

![3](https://user-images.githubusercontent.com/15893891/146061748-9c2f23c9-66d1-4375-bf13-4897cc45a84b.png)

![4](https://user-images.githubusercontent.com/15893891/146061770-42663411-aadc-4be2-a2b2-aec266f10293.png)

![5](https://user-images.githubusercontent.com/15893891/146061779-70ad96f3-20aa-4b8d-b5d0-aee3cab99b63.png)

**Comment by PetMudstone** [comment]
Replicated on Staging 21121502, notably this happened on the third round onwards. Occured again on round 4 and 5.

**Comment by ThatDan123** [comment]
Still happening?

**Comment by PerfectTangent** [comment]
should be fixed by #8162.
