### ISSUE TITLE
We need to get Changelog.md back up and running again

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#7986]
There has been hundreds of undocumented fixes and additions to the game recently but the bot that is responsible for documenting these changes has been down for quite some time now. It's not very good for the players who don't know what's new in the game and for the devs as well who want a quick way to see changes and their PRs.

This problem happened due to the PR bot breaking due to the review changes we added where we need two approvals to allow anything inside the master branch.

**Comment by jamessimo** [comment]
And we should see if we can make the same script (or a new script) go back in time too retrofit all the missed PRs.

**Comment by corp-0** [comment]
getting all the missed changelogs isn't something that worries me, we can get all github history easily and find the PR bodies and run pr2changelog on them. The problem is, as I said before, I don't know how to allow pr2changelog to push changes to the repo and skip the branch protection

**Comment by MaxIsJoe** [comment]
> getting all the missed changelogs isn't something that worries me, we can get all github history easily and find the PR bodies and run pr2changelog on them. The problem is, as I said before, I don't know how to allow pr2changelog to push changes to the repo and skip the branch protection

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by corp-0** [comment]
reopening because it didn't work

```
Push to branch develop
remote: error: GH006: Protected branch update failed for refs/heads/develop.        
remote: error: Required status check "Unit testing on 2021.1.14f1" is expected. At least 2 approving reviews are required by reviewers with write access.        
```

pr2changelog still can't push to the protected branch

**Comment by MaxIsJoe** [comment]
> reopening because it didn't work
> 
> ```
> Push to branch develop
> remote: error: GH006: Protected branch update failed for refs/heads/develop.        
> remote: error: Required status check "Unit testing on 2021.1.14f1" is expected. At least 2 approving reviews are required by reviewers with write access.        
> ```
> 
> pr2changelog still can't push to the protected branch

I think this is because we have the "enforce rules on admins as well" option enabled

**Comment by corp-0** [comment]
No, I disabled it

**Comment by PerfectTangent** [comment]
ah, this is done. We now host the wiki on a second repository.
