### ISSUE TITLE
Trying to pull Y while pulling X makes X lerp back to initial position

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#800]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2A4

# Report
## Current Behavior
In title

## Expected/Wanted/Requested Behavior
CNT should get informed about released object's position when switching pullables

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start pulling a closet
2. Walk around and find another closet
3. Ctrl+click another closet: first one will lerp back

## Network
Test server

**Comment by fomalsd** [comment]
They don't lerp back for client anymore as of Beta 4, but there sure is a desync of some sort:
![2018-01-20 12_42_30](https://user-images.githubusercontent.com/10403536/35182116-944baffe-fddf-11e7-95b9-14e3ff2c4f33.gif)

**Comment by DooblyNoobly** [comment]
yea I think that is a register tile problem. Its stopping me from finishing space push

**Comment by krille90** [comment]
@DooblyNoobly could you elaborate what you think the problem with RegisterTile might be?

**Comment by DooblyNoobly** [comment]
It's a mystery to me. Why else would playermove allow a move into that tile? I think we might need to do some visual debugging with gizmos. Maybe create a flag on registertile for debug and then have a gizmo show where the item/obj is registering too when it is being moved around

**Comment by DooblyNoobly** [comment]
btw I changed RegisterTile.UpdatePosition from using FloorToInt to RoundToInt. Not sure if this is causing a problem but I am changing it back in my next PR

**Comment by krille90** [comment]
This bug seems to occur when you start pulling an object while already pulling another. If you stop pulling the object first, the bug doesn't happen for me

**Comment by DooblyNoobly** [comment]
Should be fixed now with the latest pushpull improvements. The 1st closet wasnt being removed from pulling correctly over network when you tried to pull another
