### ISSUE TITLE
Morgue box swallows cameras

### ISSUE THREAD

**Issue by ghost** [unitystation/unitystation#8045]
### Environment
- Game Version: 21122800
- OS Version: xd

### Detailed description of bug

[Morgue box swallows cameras](https://i.gyazo.com/4442281926f55566cc168930d4f754cc.mp4)

### Steps to reproduce

1. put camera on wall, above morgue box gurney, or find one that is already in place
2. open and close the morgue box, extending gurney below camera and retracting it back inside

**Comment by VernaSaurus** [comment]
can you test if this happens with lockers too?

**Comment by ghost** [comment]
> can you test if this happens with lockers too?

lockers behave normally, it seems, they don't eat the cameras
