### ISSUE TITLE
Bots no longer work

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#8055]
-Cleanbots, floorbots and medbots are broken.

-The mob brains were removed in #8025

They no longer start to explore and find targets.

The issue is that they are different to the other mobs as they don't have the MobAi component (as they don't have health, integrity instead)

**Comment by Nianmi** [comment]
So I need to added the MobAi functoriality to the Integrity script?

**Comment by corp-0** [comment]
sounds like it needs reparenting to an abstract class that represents all mobs and has OrganicMob (with health script) and SiliconMob (with integrity)

**Comment by Fr-Dae** [comment]
hello
From what I understand from the discord archives, this was one of dobbly's projects, right ?
Did he leave any documentation about how the mob and bot neural network works?

**Comment by ilinm1** [comment]
working on it
