### ISSUE TITLE
All consoles are still active even if no power to APC

### ISSUE THREAD

**Issue by jamessimo** [unitystation/unitystation#8066]
### Environment
- Game Version: staging/latest 
- OS Version: windows 10

### Detailed description of bug

currently all consoles on the station can be interacted with regardless of station power (but do not show their lights). The reason they do not show their lights is because they have an APC component but the APC is not connected to anything.

Possible related; 

#6554 
#7602 

The only console this doesn’t apply to right now is the reactor, singularity and power output consoles, these should be powered regardless.

### Steps to reproduce

1. Kill power to the station
2. Click console 
3. Can still access the gui
4. Console screen sprite is still visible. 

Expected outcome 
1. Kill power to the station
2. Click on any non-power related console 
3. See the message “The {console name} is unpowered”
4. The consoles screen sprite is disabled.

**Comment by NoooneyDude** [comment]
You mean APC, right? : )
