### ISSUE TITLE
Players appear on original position after being moved in closed container B: 10

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#808]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2A5

# Report
## Current Behavior
In title

## Expected/Wanted/Requested Behavior
Player should appear at container's position instead 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get in closet and lock yourself
2. Make someone push that closet
3. Open closet
![portacloset](https://user-images.githubusercontent.com/10403536/34624486-8753b96a-f266-11e7-843f-a412b8eca07f.gif)

## Network
Test server

**Comment by DooblyNoobly** [comment]
Seems to be because of change to CNT. Need to use the show at position method provided in CNT when the cupboard opens

**Comment by DooblyNoobly** [comment]
Criteria:

   - Make sure player appears at the correct position when leaving a closet
   - Make sure it works correctly over network

Bounty: 10 usd paid via paypal on successful merge
