### ISSUE TITLE
APC frames can be mounted on wall and then pulled

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8089]
### Environment
- Game Version: latest staging build at the moment
- OS Version: win 10

### Detailed description of bug
After mounting APC frame onto wall you can simply pull it out of there and move around.

### Steps to reproduce
![apc_frame](https://user-images.githubusercontent.com/57045293/147948010-28d3b3e5-27c9-4640-89e6-b4e31c238a7c.png)
1. Get APC frame
2. Mount it on wall
3. Ctrl+click on it and move from wall
4. Profit

**Comment by ThatDan123** [comment]
Arent you suppose to weld them on to the wall to stop that? Can you weld them to the floor?

**Comment by ilinm1** [comment]
I think you can't actually secure it to prevent it from moving if you won't finish construction fully. By the way, unassembled frame is also unpassable and invisible from some point of view so it can be pretty annoying

**Comment by ilinm1** [comment]
Also, even if it's possible to secure it it's still strange that you can move it from wall since you can't actually put it back onto wall.
