### ISSUE TITLE
Alt+click 0.5;0.5 offset issues B: 10

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#810]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2A5

# Report
## Current Behavior
Alt+click results are different when you click different corners of one tile

## Expected/Wanted/Requested Behavior
they should be consistent for the tile

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Come to a place with lots of different objects and walls
2. Try Alt+clicking four corners of the tile you stand on

![altclick_offset](https://user-images.githubusercontent.com/10403536/34625686-c2171f7a-f26a-11e7-966d-57a245951002.gif)

**Comment by DooblyNoobly** [comment]
Criteria:

   - Investigate the cause of the bug and make a fix

Bounty: 10 usd paid via paypal on successful merge
