### ISSUE TITLE
You cannot get out of a ghost orbit.

### ISSUE THREAD

**Issue by craftxbox** [unitystation/unitystation#8111]
### Environment
- Game Version: 22010322
- OS Version: n/a

### Detailed description of bug

It is not possible to stop orbiting something as a ghost without teleporting away, or returning to your body

### Steps to reproduce

1. Ghost
2. Double click to orbit an object
3. Try to move away

**Comment by MaxIsJoe** [comment]
Are you sure that this is still happening on staging?

**Comment by craftxbox** [comment]
Certain it is present in 22010322. This is a duplicate of #8097 and i'll re-evaluate after the next staging build is published.
