### ISSUE TITLE
Improper sanitization in chat bubbles.

### ISSUE THREAD

**Issue by craftxbox** [unitystation/unitystation#8112]
### Environment
- Game Version: 22010322
- OS Version: n/a

### Detailed description of bug

Chat bubbles are not sanitised for TMP/RichText Tags. Resulting in people being able to make *hilariously* large text and other naughty stuff inside chat bubbles.

### Steps to reproduce

1.  Enable chat bubbles
2.  Include TMP tags inside a message
3. Watch as they are honored inside your chat bubble, but stripped from the speech.

**Comment by ThatDan123** [comment]
Are you sure all players are able to and not just admins?

**Comment by craftxbox** [comment]
> Are you sure all players are able to and not just admins?

Certain. MaxiMal_98 is not a staging admin and was able to replicate this.

**Comment by Maximal98** [comment]
Captain announcements and shuttlecalls are also affected by this but this time in text chat
