### ISSUE TITLE
Defibrillators do not recharge.

### ISSUE THREAD

**Issue by craftxbox** [unitystation/unitystation#8113]
### Environment
- Game Version: 22010322
- OS Version: n/a

### Detailed description of bug

Defibrillators do not *ever* recharge after proper usage. Only way to reactivate them is to VV OnCooldown to false.

### Steps to reproduce

1. Use defibrillator on recently dead patient
2. Attempt to use on *another* patient.
3. "Paddles are still charging!"

**Comment by MaxIsJoe** [comment]
Im working on this
