### ISSUE TITLE
MacOSX launcher a Bit Bugged

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#8130]
### Environment
- Game Version: '6.1.0' (Is what I'm guessing)
- OS Version: 1.14 "Mojave"

### Detailed description of bug

When someone clicks on the application used to open the station hub, an error springs up (of which I am not well-versed in.)
![Screen Shot 2022-01-07 at 8 28 40 PM](https://user-images.githubusercontent.com/61613068/148631499-ff0994d6-58ad-4b4b-86ba-792869104974.png)

### Steps to reproduce

1.  Go open file for the StationHub launcher on the unitystation.org website
2. Open necessary files to get to 'StationHub'
3. Click on terminal

**Comment by corp-0** [comment]
related to #7926

**Comment by Maximal98** [comment]
a required file is missing. are you running it from the folder where stationhub is installed? or does your stationhub not have any extra files?

**Comment by LastCaptainBonk** [comment]
> a required file is missing. are you running it from the folder where stationhub is installed? or does your stationhub not have any extra files?

The "StationHub" is one of two terminals which actually run in the files I downloaded. The other one (NetCoreBeauty) has no errors, but it also automatically closes. There are also no other terminals in the files that I can open on the account that my system recognizes them as applications that cannot be opened and cannot be accessed in my region in the Pacific US (for some reason).

**Comment by Maximal98** [comment]
Have you tried reinstalling stationhub and is there a "Lib" folder in the stationhub folder?

**Comment by LastCaptainBonk** [comment]
> Have you tried reinstalling stationhub and is there a "Lib" folder in the stationhub folder?

Yes to both answers. Reinstalling did not help, and I checked the 'Lib' folder before making this post. The lib folder just has a bunch of documents (mainly humanizer.resources.dlll) and terminals that cannot be opened.

**Comment by Maximal98** [comment]
hmm... have you tried starting a terminal and then navigating to the folder where stationhub is and then starting it from there? it might be because you're running it from a different folder than where stationhub is located

**Comment by LastCaptainBonk** [comment]
> hmm... have you tried starting a terminal and then navigating to the folder where stationhub is and then starting it from there? it might be because you're running it from a different folder than where stationhub is located

Location doesn't matter it seems. Anything in StationHub's folder is still considered a non-openable application.

**Comment by Maximal98** [comment]
Yes, Location DOES matter. for example. if i open stationhub with a working path of for example, my documents folder, it gives me the exact same error because it cant find its directories and all that

**Comment by LastCaptainBonk** [comment]
> Yes, Location DOES matter. for example. if i open stationhub with a working path of for example, my documents folder, it gives me the exact same error because it cant find its directories and all that

Alright, now it's coming up with a completely different problem:
![Screen Shot 2022-01-08 at 9 53 55 AM](https://user-images.githubusercontent.com/61613068/148654458-581c4e78-0725-402f-b254-b06ee0b9c83c.png)

**Comment by Maximal98** [comment]
huh. how are you running stationhub?

**Comment by LastCaptainBonk** [comment]
> huh. how are you running stationhub?

Click on folder in downloads titled "osx930-2", and then open terminal called "StationHub"

**Comment by Maximal98** [comment]
hrm. try opening a completeley new terminal and typing in "cd" followed by the path to Stationhub and then Typing in "./Stationhub"

**Comment by LastCaptainBonk** [comment]
> hrm. try opening a completeley new terminal and typing in "cd" followed by the path to Stationhub and then Typing in "./Stationhub"

Tried. Something about unable to open a "pseudo-tty".

**Comment by Maximal98** [comment]
welp, now im just as lost as you are.

**Comment by liesauer** [comment]
hey guys, i am the maintainer of `NetCoreBeauty`, i noticed that this bug is caused by no using the patched hostfxr, it is the original one. thus, the app would fail to launch. how does `unitystation` publish the release?

![image](https://user-images.githubusercontent.com/8676741/148758375-807f40d4-b30e-4857-a1c0-c0487cf67df4.png)

**Comment by corp-0** [comment]
```
dotnet publish --configuration Release --runtime <platform> 
```

**Comment by liesauer** [comment]
how do you use the NetCoreBeauty, i can not find any configs of NetCoreBeauty in the project.

**Comment by corp-0** [comment]
this issue is actually related to this repo https://github.com/unitystation/stationhub

**Comment by liesauer** [comment]
i see, this issue is caused by [this config](https://github.com/unitystation/stationhub/blob/8fbdbc24d3032ff2078ae767d48573a9b0be50cd/UnitystationLauncher/UnitystationLauncher.csproj#L23):

![image](https://user-images.githubusercontent.com/8676741/148765185-2c84a313-ce77-476b-ade4-c73663c9f1e2.png)

the patch should never be disabled.

**Comment by corp-0** [comment]
thank you, I will try that!

**Comment by corp-0** [comment]
Worked!
@LastCaptainBonk we will be rolling an update soon but if you want to get the fix early you can get the mac build from here: https://drive.google.com/file/d/1If5BB11L2vcHy2zVVL1bwJGAzMB8IgFL/view?usp=sharing

Tell us if it worked for you.

**Comment by Q4ik** [comment]
Works great. Wonderful job!

**Comment by LastCaptainBonk** [comment]
> Worked! @LastCaptainBonk we will be rolling an update soon but if you want to get the fix early you can get the mac build from here: https://drive.google.com/file/d/1If5BB11L2vcHy2zVVL1bwJGAzMB8IgFL/view?usp=sharing
> 
> Tell us if it worked for you.

It's a .rar file, and my Mac cannot open it.

**Comment by Q4ik** [comment]
It didn't ask you to unzip it?

**Comment by LastCaptainBonk** [comment]
> Worked! @LastCaptainBonk we will be rolling an update soon but if you want to get the fix early you can get the mac build from here: https://drive.google.com/file/d/1If5BB11L2vcHy2zVVL1bwJGAzMB8IgFL/view?usp=sharing
> 
> Tell us if it worked for you.
![Screen Shot 2022-01-10 at 4 07 12 PM](https://user-images.githubusercontent.com/61613068/148858663-3744fed2-4f87-4494-a68b-e869f4d6542a.png)
I have no fucking idea what's even wrong with this one but I'll wait on this one until the update comes out probs.

**Comment by corp-0** [comment]
open a terminal in the folder of the executable and type ``chmod +x StationHub`` to make it executable, currently it is read as a text file

**Comment by LastCaptainBonk** [comment]
> open a terminal in the folder of the executable and type `chmod +x StationHub` to make it executable, currently it is read as a text file

Okay, I've allowed access to open it, yet my Mac does not recognize the file as existing. Frankly, everyone else seems to be downloading okay, and the update seems to be coming out *eventually*, so I'd prolly fold until the update comes out. Seems like too much hassle for nothin'.

**Comment by liesauer** [comment]
@corp-0 when i test the loading issue yesterday, i found that the logs and other stuff are stored into current working directory not the app folder, you should store them inside the app folder to make the app more portable. can be reproduced via
```shell
cd <any directory outside the app folder>
./<relative path to the app>/StationHub
```

**Comment by liesauer** [comment]
> > open a terminal in the folder of the executable and type `chmod +x StationHub` to make it executable, currently it is read as a text file
> 
> Okay, I've allowed access to open it, yet my Mac does not recognize the file as existing. Frankly, everyone else seems to be downloading okay, and the update seems to be coming out _eventually_, so I'd prolly fold until the update comes out. Seems like too much hassle for nothin'.

you should never double-click the cli app since StationHub hasn't bundled into .app, the proper way should be
```shell
cd <the app folder>
# only do this when you open the app first time
chmod +x StationHub
./StationHub
```

**Comment by LastCaptainBonk** [comment]
> open a terminal in the folder of the executable and type `chmod +x StationHub` to make it executable, currently it is read as a text file

Great news! Almost half a year later, and it turns out that I was attempting to run your commands in the wrong style. Yep, I duly apologize for the rings I have run only to find out this is because of my ineptness, but I do have a place where future Mac users can go so that they don't run the same odyssey that I did (of course, replace "osx928" with whatever build you have.):
https://www.reddit.com/r/unitystation/comments/p511pz/a_definitive_users_guide_to_installing/

And again, thank all of you for your help.
