### ISSUE TITLE
Cyborgs

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#8143]
### Description

Add borgs. 

I found many varieties of Borgs that i think would fit in perfectly in US13 in the [Paradise Station wiki.](https://paradisestation.org/wiki/index.php/Cyborg)

Miners, Engineering, Medical, Combat, Service and so on.

## Why?

Because the AI currently doesn't have much to do, other than helping the crew with their day-to-day tasks (Which is fair, that is their main purpose), There is also a Synthetic radio channel, that is unused. Science also has nothing to do, other than Roboticists who can attach prostethics to people, Scientists could make batteries and augmentations for cyborgs.

Cyborgs can be a great help to the crew sometimes, due to them not taking suffocation or toxic damage.

**Comment by mmails** [comment]
I know this isn't the priority right now, as you guys are working on ironing out every major bug, but it'd still be nice to have borgs around.

**Comment by AtnerNT** [comment]
Believe this should be closed as of #9814
