### ISSUE TITLE
Chat bubble remains on your character after leaving locker you chatted inside

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#815]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2A5

# Report
## Current Behavior
In title

## Expected/Wanted/Requested Behavior
It shouldn't reappear on your character after you leave the closet

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Lock yourself in closet
2. Type and send a chat message
3. Leave closet. Bubble will remain until you send something normally again
![chatbub1](https://user-images.githubusercontent.com/10403536/34628813-d42a1ab2-f276-11e7-8ab0-ef73b3bced82.gif)

## Network
Test server, ~60 ping

**Comment by DooblyNoobly** [comment]
VisibleBehaviour turns it on whether you are talking or not. Need to cache all of the current states of the renderers before turning them on or off via VisBehaviour

**Comment by DooblyNoobly** [comment]
actually that doesn't work because what if you are talking and then go into a cupboard. It will turn the chat bubble on again when you leave. Maybe a do not affect list on the ObjectBehaviour for visual stuff that you can customize for each object.
