### ISSUE TITLE
Freezer/heaters not getting gas

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8156]
### Environment
Build Version is: 22011114. 
- OS Version: Mac_Catalina_10.15.7

### Detailed description of bug

Gasses do not flow into freezer/heater.
### Steps to reproduce

1. Connect a freezer/heater to a pipeline.
2. Sync it and turn on.
3. Note the machine will not detect gas in the line.

**Comment by Bod9001** [comment]
#8161

**Comment by corp-0** [comment]
@Bod9001 so it is fixed?

**Comment by Q4ik** [comment]
Yeah, we can close this. Haven't run into this issue anymore.
