### ISSUE TITLE
Issues with C4

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#8158]
### Environment
- Game Version: 22011114
- OS Version: Consistent on every OS. 

### Detailed description of bug

C4 is broken in multiple ways. 
1. It does not explode. 
When it should explode, it produces this error.
`Explosion started, look at Trace log, Strength 1000 at World (0, 0, -100) `
The C4 does not disappear after use either. 
2. This window often gets out of place. 
![image](https://user-images.githubusercontent.com/51922130/149421034-12c821db-d8f9-44d8-a1ec-72a88899e8da.png)

3. This switch is drawn twice after being flipped.
![image](https://user-images.githubusercontent.com/51922130/149421126-a7d08802-1a8b-4bf4-b2d3-edb96b20fed0.png)

### Steps to reproduce

1. The first bug can be reproduced by obtaining C4 and trying to detonate it. 
2. The second bug can be reproduced by just fucking with the window a bit, closing it and opening repeatedly. 
3.  The third bug can be reproduced by flipping the switch.

**Comment by MaxIsJoe** [comment]
All of these issues only happen on headless, the 2nd and 3rd are probably something related to NetUI not liking the way values are changed currently.
the first one is weird and needs some investigation.
