### ISSUE TITLE
Field generators not putting out field

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8159]
### Environment
Build Version is: 22011114. 
- OS Version: Mac_Catalina_ 10.15.7

### Detailed description of bug

Field generators are not putting out the containment field

### Steps to reproduce

1. Set up some field generators
2. Power them
3. Attempt to start the field

**Comment by PerfectTangent** [comment]
was able to reproduce

**Comment by Bod9001** [comment]
#8160
