### ISSUE TITLE
Health UI improvements

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#816]
# Preliminary information

## Category
Refactor

## Expected/Wanted/Requested Behavior

- [ ] Make oxygen alert working with atmos + respiratory system
- [ ] Add extreme temperature meter (hot/cold)
- [ ] Add pressure meter (high/low)
- [ ] Make body parts UI indicate 100% healthy condition (blue) before turning green

Make sure it's all network synced properly (refer to how oxygen alert does the syncing).

**Comment by fomalsd** [comment]
It was working properly when health code was refactored (see #411)

**Comment by JacobSweeten** [comment]
Also sometimes if you get harmed by a stabbing object (knife, screwdriver), you don't get a white crit overlay.

**Comment by fomalsd** [comment]
this is likely caused by Rpc usage (RpcApplyDamage), which proved to be really unreliable
combined with this:
`healthBehaviorScript.RpcApplyDamage(null, 5, DamageType.OXY, BodyPartType.HEAD);
healthBehaviorScript.ApplyDamage(null, 5, DamageType.OXY, BodyPartType.HEAD);`
(apply damage code should only run on server)

**Comment by DooblyNoobly** [comment]
edited: no longer a bounty

**Comment by fomalsd** [comment]
superseded by #1722
