### ISSUE TITLE
[Research Foundation] Protolathe & Circuit Imprinter

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8164]
As part of the research foundation, building a basic functionality implementation of the protolathe is critical. This issue provides core functionality that the rest of Science Division will build upon. Proper documentation of the core implementation is expected, as others may well build upon it.

The following features are essential:

1. A means for the Protolathes to access and respond to researched technology in a live fashion (I.E. Networked UI).
2. Setting up a short (E.G. Five) list of products unique to the Protolathe, accessed through Research, producible by the Protolathe.
3. Repeat both of the above for the Circuit Imprinter.

**Comment by PerfectTangent** [comment]
completed by #8571.
