### ISSUE TITLE
Encription keys can be removed from a headset indefinitely

### ISSUE THREAD

**Issue by AtnerNT** [unitystation/unitystation#8186]
using a screw driver on any headset spawns a standrard encription key- but the key can be removed again and again, allowing you to create hundreds of encription keys

![Capture](https://user-images.githubusercontent.com/48405920/150539891-ec25a1a6-43ec-4f24-b037-a02e4b6e6ded.PNG)

**Comment by corp-0** [comment]
Without further examination this looks like a good first issue
