### ISSUE TITLE
Atmos devices are broken again

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8187]
### Environment
- Game Version: latest staging version at the moment
- OS Version: unrelated

### Detailed description of bug
Pipes n other atmos devices are often unsecurable, securing newly made pipes makes them dissapear

### Steps to reproduce
1. Try to unsecure pipe
2. Try to secure pipe

**Comment by corp-0** [comment]
what is the state of this? I didn't see people complaining about that last play test

**Comment by ilinm1** [comment]
Appears to be resolved.
