### ISSUE TITLE
food on nuke ops shuttles

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#8195]
as of right now, the nuke ops shuttle dosent have any food on it, this is an issue because if nuke ops declares war they need to wait several mins on the shuttle, this means they will be starving by the time they get to the station, which i dont think is fair

**Comment by PerfectTangent** [comment]
yeah, I was thinking about this yesterday. I think the only food available in both syndicate bases is just a single pack of syndi cakes. I have a solution in mind that I'll be employing soon.

**Comment by PerfectTangent** [comment]
have to wait for #8179 to be merged.
