### ISSUE TITLE
You can load unmatching ammo into your weapon, which breaks inventory slot and switchinghands breaks things B: 30

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#821]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2a5

# Report
## Current Behavior
You can load any kind of ammo clip in any firearm.
This makes shotguns able to shoot 50 rounds by loading P90 mag, for example
Hand slot with wrong ammo type becomes broken afterwards – can't pick anything up using that hand

Also
If your holding ammo and a gun at the same time. Shoting all your bullets from your gun swap to the ammo hand reload. Now without dropping the gun move it to the ammo hand. The gun should turn into the ammo. If you swap hands again and ammo it should turn back into a gun.

## Expected/Wanted/Requested Behavior
Inventory shouldn't get broken;
You shouldn't be able to load obviously wrong ammo type into a gun.
Switching hands shouldn't fuck things up

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Grab a gun (i.e. machine gun) and shoot it until it's empty
2. Find and pick up shotgun shells or other obviously wrong kind of ammo in the free hand
3. Load the ammo by pressing R with mag selected
4. Try shooting! 
5. After the clip was loaded that hand slot will become bugged and you won't be able to pick anything up
![unimag](https://user-images.githubusercontent.com/10403536/34641148-806bdd62-f310-11e7-855c-42fb5250b4f9.gif)

Inventory breaking might be related to #819

## Network
Test server ~60ms

**Comment by fomalsd** [comment]
Turns out these two are separate bugs, as inventory breaks even if the correct mag is loaded

**Comment by DooblyNoobly** [comment]
Criteria:

   - Make sure inventory does not break when you load a magazine into a weapon
   - Make sure only the correct ammo magazine can be used for the type of weapon it is being loaded into
   - Make sure switching hands works with both ammo, weapons and reload

Bounty: 30 usd paid via paypal on successful merge

**Comment by DooblyNoobly** [comment]
done :)
