### ISSUE TITLE
Splitting stacks crashes client.  

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#8233]
### Environment
- Game Version: 22012100
- OS Version: gentoo amd64

### Detailed description of bug

Splitting a stack with the alt click interface crashes the client. 

### Steps to reproduce

1. Acquire a stackable item, such as cheese. 
2. Pick it up. 
3. Alt click on the stack with your other hand. 
4. Enter any number.
5. Hit Confirm.
6. Crash. 
7. Cry.

**Comment by ThatDan123** [comment]
Was fixed in #8224
