### ISSUE TITLE
Can't shoot yourself

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#8245]
-Clicking on yourself with a gun doesnt work

**Comment by PerfectTangent** [comment]
There's a boolean in the gun script that decides whether a gun can be used to shoot oneself. Perhaps you used a gun that had it set to false?

**Comment by ThatDan123** [comment]
> There's a boolean in the gun script that decides whether a gun can be used to shoot oneself. Perhaps you used a gun that had it set to false?

Ah, Hybrid Taser and RiotShotGun has it set to false
