### ISSUE TITLE
Sec barriers

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#8265]
![image](https://user-images.githubusercontent.com/56727168/151676545-c738bb42-6041-4689-9675-fb9178be9fc0.png)

-Can be wrenched down and then locked with Id

**Comment by mkuppers** [comment]
Starting on this today

**Comment by corp-0** [comment]
let us know if you need any help implementing it, either with knowledge about the codebase or the actual requirements of the feature
