### ISSUE TITLE
Boxstation Issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#8267]
- [x] Atmos tank pumps backwards

- [x] Box gateway access issues (with shutters too?)

- [x] Remove fake air alarms as they are confusing for players

**Comment by DTraitor** [comment]
> Box gateway access issues (with shutters too?)

Just the door

**Comment by PerfectTangent** [comment]
> > Box gateway access issues (with shutters too?)
> 
> Just the door

what up wit da door? Looking at it, the access is set correctly.

**Comment by DTraitor** [comment]
> what up wit da door? Looking at it, the access is set correctly.

I had gateway access, but I couldn't open the door (or HoP lied to me, in that case anyone can open shutters using the button).

**Comment by CorruptComputer** [comment]
I'm just starting to get into this, so I'm not quite comfortable creating a PR for these but I found a couple of issues with atmos when testing locally. Checked these in BoxstationV1.unity at commit 0aa943fe4cf2cacf74dc603d514f031281997da5

In atmos all of the gas pumps and gas filters are off at round start, is this intended? 
In most SS13 maps atmos starts the round setup to at least be functional.

Also these gas pumps spawn backwards from the direction I think they should be:
![image](https://user-images.githubusercontent.com/5573038/212445733-e25ffaa8-daf9-4211-b9cc-1512d3f68971.png)
![image](https://user-images.githubusercontent.com/5573038/212445813-d3d5da2c-cc96-46a1-b8cc-32860e901123.png)
![image](https://user-images.githubusercontent.com/5573038/212445899-daee7aae-3918-42a6-af83-6e96f8267e60.png)

**Comment by corp-0** [comment]
> I'm just starting to get into this, so I'm not quite comfortable creating a PR 

If you are interesting, you can ask us on discord and we can walk you through the process of setting the development environment and all of that.

**Comment by CorruptComputer** [comment]
Missing air pipes near the engineering storage off the southern main hallway:
![image](https://user-images.githubusercontent.com/5573038/213825646-f602280c-c522-4f27-ae07-5efd99422b88.png)

Air pipe is either missing or the wrong type near the cargo maintenance door:
![image](https://user-images.githubusercontent.com/5573038/213825802-a0db328b-96ac-4cf2-a1b3-4abd99067abd.png)

Missing electric cable and scrubber pipes in maintenance near the chapel:
![image](https://user-images.githubusercontent.com/5573038/213826568-3fbd5412-6bb4-469f-9660-5b2a8f3ce2f3.png)

Missing scrubber pipe near atmos closet in medbay maintenance:
![image](https://user-images.githubusercontent.com/5573038/213827272-1050ac9d-b8ac-4c25-af17-486e268a32a8.png)

Missing air pipe in maintenance near EVA:
![image](https://user-images.githubusercontent.com/5573038/213827567-42e24525-42b8-4941-8935-9f4c6b81d2bd.png)

Air pipe is either missing or the wrong type in the main hallway on the west side of the bridge:
![image](https://user-images.githubusercontent.com/5573038/213828004-5533b00f-1e77-4ad1-a42b-a49732b39fa3.png)

Shutter button in the bridge does not work:
![image](https://user-images.githubusercontent.com/5573038/213828106-ecc02b3a-d9b5-4873-b16b-deea4981e559.png)

"Higher Access Level Needed" on Turret control panel in the bridge as captain:
![image](https://user-images.githubusercontent.com/5573038/213828137-e3ed50e2-9fb3-4c5b-9bcc-14eed53cc55f.png)

Both shutter buttons in HoP office do not work:
![image](https://user-images.githubusercontent.com/5573038/213828190-c8a33110-0485-4c8d-81a6-a259c2879dcc.png)

Both shutter buttons in the Chief Engineers office do not work:
![image](https://user-images.githubusercontent.com/5573038/213828439-df047163-00e6-446b-89b1-824a0e769728.png)

Shutter button in the engine does not work:
![image](https://user-images.githubusercontent.com/5573038/213828482-346b435b-6fe2-439f-85a5-9ffa11b624ae.png)

Button on the security checkpoint outside of atmos does not work:
![image](https://user-images.githubusercontent.com/5573038/213828574-86ebe6cb-d3ea-4dfd-a027-a82b3262e74b.png)

Both shutter buttons in robotics do not work:
![image](https://user-images.githubusercontent.com/5573038/213828712-a4f4de5b-fbdf-4924-9bac-b91ced5716e4.png)

None of the shutter buttons in xenobiology work:
![image](https://user-images.githubusercontent.com/5573038/213828761-b3f1a73b-630b-48a8-8cc2-8d094d63fd35.png)

Mass driver blast door button in the chapel disappears when you walk in front of it (probably just the wrong direction set):
![image](https://user-images.githubusercontent.com/5573038/213828870-bb292736-5d35-4723-b4c2-cb7e97b9a8c6.png)
![image](https://user-images.githubusercontent.com/5573038/213828889-0ead3a58-d7bf-41e8-8155-3e5dac7e3766.png)

Shutter button in lawyers office does not work:
![image](https://user-images.githubusercontent.com/5573038/213829058-05ad5363-1d16-468a-a94d-cae4833c3061.png)

Shutter button in detectives office does not work:
![image](https://user-images.githubusercontent.com/5573038/213829082-afc18fe4-7bd4-4672-bd8f-96e5b01fcc4a.png)

Shutter button in security does not work:
![image](https://user-images.githubusercontent.com/5573038/213829168-1b37b0f4-99d7-4278-a39d-9d20caff803c.png)


Probably more but that's a long enough list for me to get started on over the weekend.

**Comment by corp-0** [comment]
closing as all missing tasks were completed.
