### ISSUE TITLE
Speech bubble text speed is too slow and does not get overwritten by new messages

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8279]
During the playtest on the 29th of January 2022, I reached the conclusion that the speech bubbles display text much too slowly to be useful. If you write even a few lines, it takes quite a while for it to show up in a speech bubble. I believe this speed should be at least doubled. I appreciate that it is animated, but it must be much faster.

Additionally, if you write a second message before the first one is finished animating, the first message just sits there a while before the second gets speech bubble space. This makes the speech bubble effectively useless for back-and-forth conversation and forces you to rely on the chat log.

**Comment by potatoalienof13** [comment]
You can set the display speed to increase in the settings menu, though it would still be better to have it faster by default.

**Comment by corp-0** [comment]
I wonder if the speed is affected by server fps

**Comment by mmails** [comment]
Honestly this should be replaced by this system, ![Screenshot_20220130_233720.jpg](https://user-images.githubusercontent.com/87020681/151720840-5ee3d74a-ab15-4643-8b69-9822be12ad04.jpg)

In my opinion it's much better than chat bubbles

**Comment by CdrCross** [comment]
I can understand that perspective. For accessibility, we must keep the option for a speech bubble background available, but it could definitely be an option.

**Comment by mmails** [comment]
> I can understand that perspective. For accessibility, we must keep the option for a speech bubble background available, but it could definitely be an option. 

Definitely, i just think this is a better system overall as you can have a faster back-to-back conversation, instead of having to wait for each chat bubble to appear, you can have the messages stack ontop of eachother

**Comment by MaxIsJoe** [comment]
There is already a slider to configure the speed of text and how long they stay on screen.

Though I agree with [mmails](https://github.com/unitystation/unitystation/issues/8279#issuecomment-1025248948), Maybe we should update our current system to have more than one bubble active at the same time.
Regardless, the main problem in this issue has been fixed already it seems, so I'm closing this issue.
