### ISSUE TITLE
Cargo system counts "selling" the gas loose inside the cargo shuttle

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8280]
### Environment
- Game Version: 22012917
- OS Version: Windows 10

### Detailed description of bug

When you send the cargo shuttle to CentCom, the sales log shows the atmosphere inside the shuttle as being sold for 0 credits. In the console's log, this gets broken down per gas per tile, so it massively clutters the UI.

**Comment by PerfectTangent** [comment]
observed the cargo console selling what appears to be the air inside cargo crates.

![cargo](https://user-images.githubusercontent.com/68730437/167759780-03773ea0-6893-450d-be37-a27ded46e1af.png)
