### ISSUE TITLE
Basic blood

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#83]
Create a component that will handle all things related to blood.

- Blood is either splashed or dragged on tiles and on playersprites including clothes. For the purpose of this milestone we will only focus on blood splashes
- Determine at what point of brute damage should blood be splashed
- Create a blood splash prefab and photon.instantiate the blood splash when required

Later on this component will be expanded to handle blood types, toxicity, viruses, enhancements etc

**Comment by DevilishMilk** [comment]
In addition, you could spawn everyone with a mop (For now) to clean up the blood splashes or you could make them disappear within an X amount of time
