### ISSUE TITLE
SecHUD functionality

### ISSUE THREAD

**Issue by VictorVow** [unitystation/unitystation#8306]
### Description

SecHUDs lack their SS13 functionality currently. They should have the following traits:
- Flashproof.
- Show the job icons on top of their sprite for all mobs in your view, based on their worn ID. Allows you to tell at a glance what job someone is, and if someone is wearing an ID they shouldn't have.
- Shows their arrest status icon on top of their sprite.
- If you have Security access on your ID, then when you examine someone it should show buttons which allow you to quickly view their arrest record, or add a crime or comment to their record, and update their arrest status (e.g. None, Arrest, Incarcerated, Discharged, Monitor, Search).

**Comment by mmails** [comment]
Pretty sure someone already suggested this, they are working on adding every HUD

**Comment by PerfectTangent** [comment]
redundant with #6054. Closing.
