### ISSUE TITLE
Playtest #1 feedback 

### ISSUE THREAD

**Issue by VictorVow** [unitystation/unitystation#8307]
Not sure if a report in this sort of format is desired here, most of the issues raised are linked to pre-existing issues however so it should be okay to close this if not appropriate. 

- Equip hotkey stores items to pockets, but not into backpack or belt #2924
- You can have an empty item slots inbetween other items in your backpack or belt #2921
- Can't adjust UI scaling #7687 
- Heavy rubberbanding #7565
- Can't put seclites on helmets or tasers #8304
- Hunger is way too fast #7142 ?
- U is default hotkey for OOC instead of O https://github.com/unitystation/unitystation/pull/8305
- Can't opt for a /tg/-like UI (swapping positions of inventory slots on body and clothing mainly)
- Tasers and stun combat are outdated, stamina combat like disablers are preferred
- Climbing tables doesn't work in Disarm or Harm intent
- No "lower mask" action button when wearing a security gas mask, nor voice command action button for "HALT!"
- Police batons, tasers currently can fit in pockets and secbelt

**Comment by PerfectTangent** [comment]
yeah, generally it's not desireable to bundle a ton of unrelated bugs together in a single issue. These should each be individual issues unless they directly connected with eachother. Also, making each bullet point a task in any bundle issue is always a good practice so that bugs can be marked off as they are completed. Closing.

**Comment by corp-0** [comment]
> No "lower mask" action button when wearing a security gas mask, nor voice command action button for "HALT!"

can you describe this one further?

**Comment by mmails** [comment]
> > No "lower mask" action button when wearing a security gas mask, nor voice command action button for "HALT!"
> 
> can you describe this one further?

From what i can recall from BYOND, Security had a hotkey to shout "HALT!", which would play a voiceline

**Comment by VictorVow** [comment]
> > No "lower mask" action button when wearing a security gas mask, nor voice command action button for "HALT!"
> 
> can you describe this one further?

Lower Mask - sprite for the mask moves from the mouth to hanging down the player's neck, and means the internals are no longer on. Turning on internals will reverse the mask being lowered.

HALT! - plays an audio snippet with a robotic voice yelling "HALT CRIMINAL SCUM" or some similar line, there's several lines it randomly picks from. Very useful when chasing someone down and you haven't got time to stop and type a message telling them to stop.
