### ISSUE TITLE
Stop ghost movement validation

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#8315]
No need for the server to validate ghost movement. Let the client move wherever it pleases as a ghost.

Bonus: increase ghost movement speed.

Bonus bonus: double movement speed if shift is held.

**Comment by PerfectTangent** [comment]
ghost movement speed increase done in #8799. Did new movement remove ghost movement validation?

**Comment by ThatDan123** [comment]
Yeah seems like it
