### ISSUE TITLE
[Mapping] Fixing HOP's offices standart

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8322]
Hello, in order to improve the quality of life and standardize the office from one map to another, 

here is an image representing a simple functional office.

![HOP-Office](https://user-images.githubusercontent.com/23202421/152616126-48e58a7e-f904-425f-b578-b94d130e583c.gif)
![HOP-Office0](https://user-images.githubusercontent.com/23202421/152616129-d8e5767c-da0c-47cc-a89e-986fa50a32be.png)

Basically, all cards should be checked, from the oldest to the most recent. 
thanks you

**Comment by PerfectTangent** [comment]
converting to a discussion.
