### ISSUE TITLE
ID job name lags server and game

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#8327]
### Environment
- Game Version: Windows 10
- OS Version: Staging 22020317

### Detailed description of bug

Basically, you can put an infinite number of characters in the Job name of your ID card as shown here,
![Screenshot_186](https://user-images.githubusercontent.com/87020681/152659198-1fc34c50-afaa-4ea1-8482-15e84b425223.png)
![Screenshot_185](https://user-images.githubusercontent.com/87020681/152659202-dc740652-27f7-48d2-a05b-732044e1cf9d.png)

This creates a decent amoung of lag when shown to other players, and even lagged the entire server for a few moments

### Steps to reproduce

1. Go to the ID Console
2. Change ID name to whatever, must be an insanely long name
3.  Profit, when showing it around its gonna lag the server and the game

**Comment by corp-0** [comment]
oh boy

**Comment by mmails** [comment]
yeah, was messing around and then found this out, definetely game breaking. i didnt test a name longer than that as it could've crashed staging
