### ISSUE TITLE
Add an emote menu for using emotes quicker.

### ISSUE THREAD

**Issue by mmails** [unitystation/unitystation#8328]
### Description

Bind to do backflips, very important in.....combat....

Just a bind that you can press to do a backflip, pretty straightforward

**Comment by PerfectTangent** [comment]
cute idea, perhaps a bind to open a menu for all emotes might be a more robust way to handle it.

**Comment by mmails** [comment]
Right now the only emote is *backflip i believe, but yes, i do agree

**Comment by PerfectTangent** [comment]
there are about 30 emotes in the game, last I checked.

**Comment by corp-0** [comment]
> cute idea, perhaps a bind to open a menu for all emotes might be a more robust way to handle it.

another radial?

**Comment by PerfectTangent** [comment]
> another radial?

I don't think a radial would be ideal for it. Too many to fit.

**Comment by corp-0** [comment]
> > another radial?
> 
> I don't think a radial would be ideal for it. Too many to fit.

What if players can customise and set the emotes they want in the emotes radial's slots

**Comment by mmails** [comment]
> there are about 30 emotes in the game, last I checked.

WHAT

**Comment by corp-0** [comment]
![image](https://user-images.githubusercontent.com/43683714/152696509-a5a89a74-eee6-42fc-b52e-13a25f4276e8.png)
In dota we have a radial with predetermined amount of slots and a shit ton of shit we can assign to them from callouts, sounds, emojis, etc

**Comment by CdrCross** [comment]
I am wholeheartedly behind Gilles' idea. I imagine holding down G to open the radial, and then using the mouse to select.
