### ISSUE TITLE
Unity Editor Crash MemoryStream corrupted

### ISSUE THREAD

**Issue by Nianmi** [unitystation/unitystation#8332]
### Environment
- Game Version: 
- OS Version: Windows 10

### Detailed description of bug
Unity Editor Crashes the first time it starts up and game mode is entered. Seems that all forks of unity station have this problem.
Restarting unity solves that problem. (Is annoying takes like 10 minutes all in all even whit SSD)

![image](https://user-images.githubusercontent.com/16767661/152681044-825d5992-8b51-4b52-b08c-3d3d82b5d89e.png)

Perhaps check the unity Editor Log for more debug Info under:
%LOCALAPPDATA%\Unity\Editor\Editor.log

### Steps to reproduce

1. Delete all unnecessary files on your local Git thingy. 
2. Restart your PC.
3. Start Unity enter Play mode.
4. Watch unity die.

**Comment by Nianmi** [comment]
Seems to be a unity 2021 bug. Can do nothing about it than wait for a unity update.
https://github.com/vis2k/Mirror/issues/2792

**Comment by PerfectTangent** [comment]
Have not experienced this with the new version of unity. Has anyone else?

**Comment by MaxIsJoe** [comment]
Haven't encountered it at all
