### ISSUE TITLE
Traitor Item: CamJam(tm)

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8345]
### Description
The CamJam would be a traitor item that takes the form of a handheld remote. When used at range on a security camera, it forces that camera to show a static image (chosen at the the time of the CamJam usage) to the AI and Security Monitoring for the next five minutes, akin to a camera feedback loop. It would have a limited number of charges.

This tool would serve to help traitors prepare for criminal activities by blinding cameras in the area without immediately alerting the AI or security that something is wrong. This would help stealth gameplay for traitors and help to rein in the observational power of the AI a little. The balancing of the CamJam can be adjusted through its TC cost, the number of charges it carries, and how long the camera is affected.

**Comment by PerfectTangent** [comment]
let's keep novel gameplay ideas in the ideas page. That's what the section is for. Converting to discussion.
