### ISSUE TITLE
Mobs don't take damage from thrown objects

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation#8351]
### Environment
- Game Version: 2201002
- OS Version: Windows 10

### Detailed description of bug

Mobs don't take damage from thrown objects lmao

### Steps to reproduce

1. pick up somthing
2.  yeet
3. ???

https://user-images.githubusercontent.com/15893891/153681034-973c6e56-10b6-45ec-afd9-9fdac75fc981.mp4

**Comment by Maximal98** [comment]
now this is a quality issue

**Comment by PerfectTangent** [comment]
duplicate of #6742. Closing.
