### ISSUE TITLE
Some items need to be openable before being used, such as soda cans and flares

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8362]
### Description

Currently, there are several items that should be 'activated' to begin using the item as intended, i.e. they need to be opened.

Some examples of items that need this kind of functionality:

- [x] soda cans must be opened to be consumed
- [x] flares and glowsticks must be activated to begin emitting light.
- [x] regen meshes must have their wrapper removed before they can be applied.

### Notes

- some items need to play a sound when opened.
- items may change their sprite when opened.

**Comment by MaxIsJoe** [comment]
This done btw

However, while testing we discovered that soda cans (among various other prefabs) are not properly prefabed, meaning that they are not variants of a base soda can so only the space cola can currently has this functionality. 

I'll open an issue about this to let everyone know.

**Comment by MaxIsJoe** [comment]
Any issues found with the regen meshes?

**Comment by PerfectTangent** [comment]
Confirmed they are working. Closing.
