### ISSUE TITLE
Addressable names in editor seems to be broken

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#8379]
After @Bod9001 's PR addressable seemed to have their variable names broken only in the inspector but not the new menu name

![image](https://user-images.githubusercontent.com/34368774/154353186-b047f689-4619-4ae7-abba-82e01908162b.png)

This is a minor issue but for long lists of items it will quickly get annoying over time and mistakes might happen.

**Comment by Bod9001** [comment]
oh? but not the new menu name?

**Comment by MaxIsJoe** [comment]
> oh? but not the new menu name?

Yeah when you open the menu it self it shows the name correctly.

**Comment by Bod9001** [comment]
but is it not serialise properly?
