### ISSUE TITLE
Refactor facehuggers to implant a larvae organ into players that can be removed with surgery.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8382]
Ideally, this refactor should also be able to solve #8367.

**Comment by Silver-8ce** [comment]
Dibs

**Comment by PerfectTangent** [comment]
@Silver-8ce Are you still working on this?

**Comment by Silver-8ce** [comment]
> @Silver-8ce Are you still working on this?

Sorry, other priorities came up.
