### ISSUE TITLE
Glass counter doesn't break when someone is dragged onto it

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8431]
### Environment
- Game Version: 22022318
- OS Version: Catalina

### Detailed description of bug

As titled
### Steps to reproduce

1. Drag someone onto a glass counter.
2. Counter does not break.

**Comment by Q4ik** [comment]
Did this on a local game and the results are not the same. Glass top shatters and metal frame gets converted to glass shards. Two metal rods plus two glass sheets results in five glass sheets after tabling
![Screen Shot 2022-02-25 at 9 18 32 AM](https://user-images.githubusercontent.com/92214971/155741006-42696166-b442-4336-b20e-b27ce1e886f1.png)
![image](https://user-images.githubusercontent.com/92214971/155741023-944d9250-23ee-4856-8bb7-be25327970ab.png)
.

**Comment by Q4ik** [comment]
Wait. The guy that was dragged on the table was a moth. Could this be why it didn't shatter? Never mind just tested the moth theory.. Still breaks (local game)

**Comment by CdrCross** [comment]
_Should_ glass tables shatter just from someone being dragged onto them? I can see it from folks being thrown, but what sort of window-glass BS would be shattered just by yanking some schmuck onto it?

**Comment by PerfectTangent** [comment]
@Q4ik this is not an issue. The chance for tables to break _is random._ Sometimes they break, sometimes they don't. You can look at the break chance in the original PR that added the feature: #7818.

also:
https://www.youtube.com/watch?v=R_inHEmp5VE

Closing.
