### ISSUE TITLE
Seems to be infinite firelocks

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8432]
### Environment
- Game Version: 22022318
- OS Version: Catalina

When North to South facing airlock is broken it leaves behind what seems to be an infinite amount of airlocks. Oh and it doesn't really break either.

### Steps to reproduce

1. Robust a North to South facing airlock until it "breaks"
2. Observe the leftover airlocks. 
Observe the non-broken airlock. 
![image](https://user-images.githubusercontent.com/92214971/155637619-0f905a03-d661-4f5c-9b99-4b32dc168ed1.png)

**Comment by MaxIsJoe** [comment]
Correction : All directional firelocks are broken. 
where they are facing doesn't matter.

Was able to replicate this locally and attempting to find a fix now.
