### ISSUE TITLE
Ghost rock

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8459]
### Environment
- Game Version: 
- OS Version: 

### Detailed description of bug
Sometimes rock after being hit with kinetic force isnt actually breaking down, but just dissapearing, leaving seeming empty tile without ash overlay, but its actually impassable and may yield ore after hitting it twice

### Steps to reproduce
1. Go to mine with PKA
2. Get annoyed

**Comment by MaxIsJoe** [comment]
This has been fixed at some point, it seems.
