### ISSUE TITLE
Poly is a THIEF!

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8462]
### Environment
- Build Version is: 22031201. 
- OS Version: Mac_Catalina

### Detailed description of bug

Poly will steal any item you have in your hand if you occupy the same tile.
### Steps to reproduce

1. Walk on the same tile Poly is on with an item in your hand

https://user-images.githubusercontent.com/92214971/158065451-1f260c35-2dd4-44aa-bd7a-23659d37cd3c.mp4

**Comment by MaxIsJoe** [comment]
This is not a bug, this is an intended feature.
However, I'm making adjustments to this so Polly steals stuff less from you + making it more clear that he stole/dropped stuff.

**Comment by Q4ik** [comment]
Alright cool. Because hasn't been dropping stuff even after he's killed

**Comment by MaxIsJoe** [comment]
Yeah I fixed that

**Comment by Q4ik** [comment]
Works great!
