### ISSUE TITLE
Items sometimes not picked up by client

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#847]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop and BETA

# Report
## Current Behavior
When picking up an item, it disappears, but won't show in the hand slot, or can be used.
They will reappear after death and can be used.

## Expected/Wanted/Requested Behavior
items showing up correctly in item slots after being picked up and be used.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Be client
2. Pick up items until break
3. item disappears without being in iventory

## OS used:
Windows

## System specifications
_Please state your CPU, GPU, amount of RAM and if you have an HDD or SSD_

## Network
about 20ms and same PC

**Comment by fomalsd** [comment]
shouldn't be, didn't encounter it in testing of #851
