### ISSUE TITLE
Status Tab Descriptors (Issa alotta wha?)

### ISSUE THREAD

**Issue by Q4ik** [unitystation/unitystation#8483]
### Environment
- Build Version: 22032015
- OS Version: Mac_Catalina

### Detailed description of bug

Status tab has descriptors that state "a lot" for Station Time, Round Status, Current Map, and Game Mode.

### Steps to reproduce

1. Just open the game status box and see
![Frames!](https://user-images.githubusercontent.com/92214971/159368395-1389116f-b5c5-4fc9-984f-d3dd82b95da0.gif)

**Comment by Q4ik** [comment]
Issue's name should be said with a thick Italian accent. That is all..

**Comment by PerfectTangent** [comment]
hey, look, I know you're just meming around and you're being helpful by posting issues, but titles really need to be straight forward and descriptive of the problem.

**Comment by Q4ik** [comment]
You smiled though right?

**Comment by PerfectTangent** [comment]
> You smiled though right?

if you want honesty, I didn't. I kinda rolled my eyes because It's adding to the mess on here. I've been spending a couple hours every month editing and renaming issues to make them more clear and concise. It's not exactly what I want to be doing with my weekends.

**Comment by Q4ik** [comment]
Ok ok. But you really didn't say it with a thick Italian accent and smile.
