### ISSUE TITLE
Electrical wires/cables need a proper name when examined

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8556]
![Unitystation_8jlrAJjBN8](https://user-images.githubusercontent.com/36482335/162612158-633b6cc5-fad9-4073-b0c3-3097110e2246.png)

All electrical wires, regardless of load, are currently called "electricalcable" when examined. This compounds the difficulty of diagnosing issues with the power network. There should be proper description text, and a distinction between low, medium and high voltage wires.

**Comment by PerfectTangent** [comment]
under what condition does this happen? When they are placed?

**Comment by CdrCross** [comment]
> under what condition does this happen? When they are placed?

Yes, when they're placed on the ground.

**Comment by PerfectTangent** [comment]
![Screenshot 2022-04-22 080209](https://user-images.githubusercontent.com/68730437/164710562-93cf0080-0593-48b0-99ca-e03efd9f5086.png)

Can't recreate with multitool. What are you doing to get that specific examine message?

**Comment by CdrCross** [comment]
Simply shift-click examining.
