### ISSUE TITLE
Inventory not pixel perfect

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#860]
# Preliminary information
Problem with hand slot switching.

## Category

BUG, feature request ?

## Bug: Release or Development?

Development.

# Report

## Current Behavior

![image](https://user-images.githubusercontent.com/22187456/34919382-e57c4ec6-f95a-11e7-82fd-09ba82cb1ad0.png)

Inability to switch hands by click if an item is in them, but you can switch by clicking the outline of the slot.

## Expected/Wanted/Requested Behavior

Pixel selection in hand slots to be able to switch by clicking, which is very much appreciated for arrow key players, but, this kind of selection would be appreciated for other slots such as pocket or back.

## Steps to Reproduce

1.Grab item inside of your hands.
2.Try switching items using your mouse by click on the slot itself, while your active hand being the other one.
3.Profit???

## OS used:
Irrelevant

## System specifications
Irrelevant

## Network
Irrelevant

**Comment by fomalsd** [comment]
Fixed by @alex180500
