### ISSUE TITLE
Make chat underlayer visible when hovering with mouse over it

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#8630]
There are many instances where chat is hard to read, mostly because the underlayer isn't visible during gameplay and the background is light. You then have to stop and press the chat key to read it.

This proposal of solution is to make it so chat detects the mouse entering its area and makes the underlay visible while the mouse is in.

**Comment by PerfectTangent** [comment]
I recommend also having an option to make it always visible.

**Comment by corp-0** [comment]
and a slider to control opacity
