### ISSUE TITLE
players with their ID inside their PDA in the ID slot are not identifiable

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8640]
### Detailed description of bug

If a player places their ID inside their PDA (naturally to save some space), then place their PDA into the ID slot, other players can't read the ID, so if they are masked in any way, they appear as unknown. This is naturally very annoying.

### Steps to reproduce

1. place ID in PDA.
2. place PDA in ID slot.
3. wear a face blocker of some kind.

**Comment by JesterX666** [comment]
Detail for reproduction : Face blocker means any head item with the "Hides identity" checked in Clothing V2 component.

Example  : MiningHardsuitHelmet has this.

**Comment by JesterX666** [comment]
Not a problem anymore, irreproductible.

From the player 1 perspective with PDA in the ID slot:

![image](https://github.com/unitystation/unitystation/assets/32009105/8dc6f2d0-7879-4cd1-ae31-a7d9c55e6af4)

From player 2 perspective :

![image](https://github.com/unitystation/unitystation/assets/32009105/ba8d1a43-600b-4e8a-92b7-6fcb1f38e5e7)
