### ISSUE TITLE
Foods showing reagent container options in the radial menu.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8647]
### Detailed description of bug

https://user-images.githubusercontent.com/68730437/166924772-11871578-dbd5-4b84-9e4c-b8b2c265fc46.mp4

Basically, not all reagent containers should show these options in the radial. We should be discriminating reagent containers based on whether the container is a functional, transferrable one like a cup, and reagent containers that don't behave like a literal container, such as food and tools like welders.

Credit to Rane.

**Comment by Copern** [comment]
I'll add in something for reagent containers to choose what options can be shown. I'll blanket apply it to the welders and the foods base. Someone else will have to figure out what other items will need to have the options changed.

**Comment by eurtod** [comment]
This is fixed.
