### ISSUE TITLE
Gas setters are visible to players

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8655]
### Detailed description of bug

See the blue X under the gloves in lavaland?
![Screenshot 2022-05-05 105240](https://user-images.githubusercontent.com/68730437/166951491-7c596980-112f-47e7-98d6-408e2c8cfac0.png)

These probably shouldn't have visible sprites, or should delete once they finish setting the gas in an environment.

**Comment by ThatDan123** [comment]
Fixed in #8961
