### ISSUE TITLE
Step Changer component should make no footstep noises if left null.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8670]
### Description

Currently, if a piece of clothing has the StepChanger component but the sound asset is left null, it will default to playing normal footstep noises, even if priority in StepChanger has been set to true. What is should do is it should play no footstep sounds if it has priority and no sound set. This is necessary to get the functionality of sneak boots, which don't make any footstep noises when worn.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/170513335-8b1ebb0f-2a0a-49b7-b926-a24dc6bb1780.png)

Why not just use None on the shoes?
