### ISSUE TITLE
New Players are kicked for having no character sheet before they can make a valid one.

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8687]
### Detailed description of bug

#8534 changed the order the character creation settings are done in order to better prepare for forks, but servers check for valid character sheets upon joining a server, which means if a player does not have one, they get kicked from the server before they have a chance to join and make one.

**Comment by corp-0** [comment]
Adding needs repro label as we have to confirm that is the case, always. Can take it off once we confirm that.
