### ISSUE TITLE
cloning damage isn't healable

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#8689]
### Detailed description of bug

It seems cloning damage, because it is being tracked as its own damage type, can't be healed by the players. The damage doesn't show on health analyser despite you being able to feel its effects and also there isn't a way to solve the ghost damage even if you try to guest where it is located.

### Steps to reproduce

1. Kill and clone people repeteadly
2. Wait until their legs are damaged so they get slower
3. Try to heal it

**Comment by AtnerNT** [comment]
Cloning/Genetic damage can now be healed via chems like cryoxaedone

**Comment by MaxIsJoe** [comment]
Needs to be expanded upon but true, it's been fixed.
