### ISSUE TITLE
Paper disappears upon pick up/ becomes uninteractable.

### ISSUE THREAD

**Issue by Sharkygal42** [unitystation/unitystation#8707]
### Environment
- Game Version: 22052105
- OS Version: Windows 10 21H2 (64x based) (KB5013942)

### Detailed description of bug

While trying to pick up a piece of paper that a player has placed on a table, Dropped or thrown, the paper becomes uninteractable and cannot be clicked on to be picked up, when the radical menu is used to pick it up, it disappears from the game scene and from the users inventory, seems to happen only to table placed paper.

You are supposed to be able to pick it up and read it like a normal piece of paper.

### Steps to reproduce

1. Take paper from paper bin object or from a spawned page.
2. Place paper on a table surface/ Drop paper on ground/ Throw paper.
3. Observe how you cannot pick it up by clicking on it.
4. Using the radical interaction interface, pick up the paper.
5. Watch it cease to exist in your hands.

**Comment by Sharkygal42** [comment]
This applies to Paper in any situation when it is outside a players inventory, not only to table paper.

**Comment by AtnerNT** [comment]
Paper was last touched by protips PR- most likely an interaction bug due to its checks

**Comment by MaxIsJoe** [comment]
Nope, didn't touch any interactions.
if this was indeed because of protips we would have seen this issue on tasers as well

**Comment by PerfectTangent** [comment]
fixed by #8335, so I'm told. Closing.
