### ISSUE TITLE
Spamming the jukebox music change buttons causes multiple tracks to play

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8738]
### Environment
- Game Version: 22052105
- OS Version: Windows 10

### Detailed description of the bug
I have only observed this with two players simultaneously, but it may also happen with one player. If you spam the heck out of the "switch song" buttons, you'll break the jukebox so that  it'll play multiple songs at the same time, delayed by milliseconds next to each other, so it sounds awful

### Steps to reproduce

1. Start the jukebox playing
2. Play cookie clicker on the "Switch song" buttons (maybe with two people)
3. **Pain**

**Comment by AtnerNT** [comment]
Can confirm it happens with one player, experienced this many times, strangely enough it seems to happen with the first 4 tracks but not with the rest
