### ISSUE TITLE
Firedoors are malfunctioning on Ministation

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8740]
### Environment
- Game Version: 22052105
- OS Version: Windows 10

### Detailed description of bug
Firedoors in the central corridors on Ministation are broken in various ways. Firstly, they seem to not respond to actually pressing the fire alarms. Secondly, you are unable to manually open and close them (AKA force them).

**Comment by AtnerNT** [comment]
Is this still an issue?

**Comment by corp-0** [comment]
this doesn't seem to be a problem anymore. Closing.
