### ISSUE TITLE
Add portable Scrubbers

### ISSUE THREAD

**Issue by CdrCross** [unitystation/unitystation#8744]
### Description
Atmospheric scrubbers are an important tool for the Atmos techs, especially when it comes to cleaning up toxic gasses and plasma floods.

- [x] A scrubber has an internal container that it fills with the gas it siphons out of the air.
- [x] It also has a simple GUI, that lets you pick which gasses to filter out and also to empty the scrubber right where it stands.
- [x] Finally, it can be wrenched unto an interface into the atmos pipes network, letting you discharge the contents into the atmos pipes network for processing.

**Comment by Bod9001** [comment]
I did this already #10071
