### ISSUE TITLE
chat doesn't stop movement code from receiving key inputs

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#8752]
### Environment
- Game Version: 22060122
- OS Version: Win10

### Detailed description of bug
As said in title, your character will move while you are typing in chat.

### Steps to reproduce
1. open chat
2. type words, include some with "w", "a", "s" and "d"
3. see it happening

**Comment by corp-0** [comment]
correction, it works fine for character but not for ghosts.

**Comment by ThatDan123** [comment]
Seems like this was fixed in #8851
