### ISSUE TITLE
thrown mobs can't recover from the distorted rotation

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#8760]
### Environment
- Game Version: 22060122
- OS Version: win10

### Detailed description of bug
When throwing a mob, they will keep the scuffed rotation forever until you throw them again and therefor, rotate them again.

### Steps to reproduce
1. Grab a mob
2. Throw it
3. See it walking with wrong rotation

**Comment by eurtod** [comment]
This is fixed
