### ISSUE TITLE
Thrown lockers and other big object can't recover from scuffed rotation

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#8761]
### Environment
- Game Version: 220600122
- OS Version: win10

### Detailed description of bug

Similar to mobs, when throwing lockers or other big objects they will stay in messed up rotation forever.

### Steps to reproduce

1. Grab locker
2. Throw locker
3. See it wrongly rotated for the rest of its existence.

**Comment by corp-0** [comment]
reopening because it hasn't been fixed.
![image](https://user-images.githubusercontent.com/43683714/172729140-c482974f-b7a6-44c1-8432-125f16953650.png)

**Comment by eurtod** [comment]
This has been fixed for lockers at least.
