### ISSUE TITLE
Writing the letters T, O or Y in the character name box opens the chat

### ISSUE THREAD

**Issue by Alekshhh** [unitystation/unitystation#8762]
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

Typing the letters O, T and Y open their respective chat channels and redirects you there when trying to write a character name, and perhaps trying to write anything at all in the game menu.

### Steps to reproduce

1. Get into the character creation menu
2. Try to write the letters O, T or Y in the character name box

**Comment by fomalsd** [comment]
still a thing
