### ISSUE TITLE
Blob camera can be pushed around by air pressure

### ISSUE THREAD

**Issue by Alekshhh** [unitystation/unitystation#8769]
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

Having your blob cam close to a pressurized tile or area pushes you around as if you were an object or player

### Steps to reproduce

1. Be a blob
2. Cause something to create air pressure, like destroying any gas canister
3. Be next to said cause of air pressure

**Comment by corp-0** [comment]
does it also happen with ghosts?

**Comment by Alekshhh** [comment]
unsure, but it wouldn't surprise me if it did
