### ISSUE TITLE
Chat bubble randomly appearing when entering and exiting a locker after talking

### ISSUE THREAD

**Issue by Carbonhell** [unitystation/unitystation#877]
# Preliminary information

## Category
Is this a BUG, Feature Request or TODO?
BUG
## Bug: Release or Development?
_When submitting a bug report, is it about the a development version or the release version?_
Release (0.2.2 BETA)
# Report
## Current Behavior
_What is the current behavior?_
After talking and letting the chat bubble disappear(the little cloud with three dots in it), entering and exiting a closet causes it to reappear and stay there forever.
## Expected/Wanted/Requested Behavior
_Please describe the behavior you are expecting/requesting or want to add._
It shouldn't appear at all.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Say something, wait for the chat bubble to appear and disappear correctly.
2.Find a locker, close yourself in it, get out.
3.A bubble will magically appear and won't vanish.

## OS used:
Windows 7

## System specifications
_Please state your CPU, GPU, amount of RAM and if you have an HDD or SSD_
Intel Core i3-6300 3.80GHz, NVIDIA GeForce GTX 1060 3gb, 8GB ram, game is stored in HDD, OS in SSD
## Network
_Please state the connection (speed) to the server, in case of "same PC" please enter the ping used_
82 ms

**Comment by DooblyNoobly** [comment]
Fixed in #815 
Beta has not been updated yet on steam, we are waiting for approval.
