### ISSUE TITLE
Allow AI to access ID-restricted objects, like command console and air scrubbers

### ISSUE THREAD

**Issue by Alekshhh** [unitystation/unitystation#8774]
### Description

Self-explanatory

**Comment by PerfectTangent** [comment]
would be a bug, then because this was completed by max in #8341 and #8392.

**Comment by Alekshhh** [comment]
gotcha, thanks

**Comment by PerfectTangent** [comment]
well, did you try it and it wasn't working? If that's the case, then this issue should be reopened.

**Comment by Alekshhh** [comment]
oh I thought it was fixed for the next build, as it stands from what I can recall no it does not work. I will reopen it

**Comment by AtnerNT** [comment]
This is fixed

**Comment by MaxIsJoe** [comment]
Have you tested this? I think there are some things that don't give the AI access to yet

**Comment by MaxIsJoe** [comment]
have you made sure that all ID-restricted objects have AI access before closing this?

**Comment by corp-0** [comment]
I didn't

**Comment by MaxIsJoe** [comment]
Just checked all AI intractable stuff, its solved.
