### ISSUE TITLE
Reflectors no longer work

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8776]
### Environment
- Game Version: 
- OS Version: 

### Detailed description of bug
Laser projectiles dont get deflected, but dissapear on contact with reflector

### Steps to reproduce
1. shoot reflector with egun/emitter/whatever

**Comment by ThatDan123** [comment]
Was the reflector welded down? Can't reproduce the issue when they are.

**Comment by ilinm1** [comment]
yes, they were, I think. doesn't matter now anyway.
