### ISSUE TITLE
Energy Carbine is missing empty SFX

### ISSUE THREAD

**Issue by Alekshhh** [unitystation/unitystation#8777]
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

When the energy carbine is empty, it does not do the chick-chicky chk

### Steps to reproduce

1. Empty an energy carbine
2. Keep using it afterwards

**Comment by PerfectTangent** [comment]
Could not reproduce. Gun chicks when it's out. I also checked that it had the dry fire sound assigned in the editor and it does.

![Screenshot 2022-06-18 105723](https://user-images.githubusercontent.com/68730437/174444070-3a563a3a-8bff-436d-bc3f-39a9a0cc7dd1.png)
