### ISSUE TITLE
Speaking not working at all after a successful restart

### ISSUE THREAD

**Issue by Carbonhell** [unitystation/unitystation#879]
# Preliminary information
The server restarted, i tried to talk but nothing would appear in the chat, doesn't matter what mode i used.
## Category
Is this a BUG, Feature Request or TODO?
BUG
## Bug: Release or Development?
_When submitting a bug report, is it about the a development version or the release version?_
Release (0.2.2 BETA)
# Report
## Current Behavior
_What is the current behavior?_
Cannot talk at all after a restart
## Expected/Wanted/Requested Behavior
_Please describe the behavior you are expecting/requesting or want to add._
Should be able to talk normally

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Wait for a restart
2.Join as any job
3.Try to talk, notice that the chat stays empty

## OS used:
_Windows, OSX or Linux_
Windows 7
## System specifications
_Please state your CPU, GPU, amount of RAM and if you have an HDD or SSD_
Intel Core i3-6300 3.80GHz, NVIDIA GeForce GTX 1060 3gb, 8GB ram, game is stored in HDD, OS in SSD
## Network
_Please state the connection (speed) to the server, in case of "same PC" please enter the ping used_
83 ms

**Comment by Carbonhell** [comment]
According to Doobly, it has been fixed already. Sorry! Closing.

**Comment by DooblyNoobly** [comment]
No the chat bubble in closet issue was fixed. If this is happening it hasn't been reported yet. Reopening
