### ISSUE TITLE
squarestation unpowored

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8801]
the HOP office are unpowered at the begin or the room

**Comment by PerfectTangent** [comment]
just the HoP's office or all of squarestation?

**Comment by Fr-Dae** [comment]
juste the apc in the hop's office

**Comment by Fr-Dae** [comment]
+ bar unpowred
+ botanic

**Comment by Fr-Dae** [comment]
![2022-06-09-031437_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/172744183-d26c1cd0-2348-4293-8f65-7b6c50794a9d.png)

in white door unpowered
on fallstation

**Comment by corp-0** [comment]
don't think this is an issue anymoer, is it?

**Comment by Fr-Dae** [comment]
> don't think this is an issue anymoer, is it?

have you test it ?

**Comment by AtnerNT** [comment]
These is no longer an issue, can be clsoed
