### ISSUE TITLE
cargo bounty no longer work

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8807]
### Environment
- Game Version: 
- OS Version: 

### Steps to reproduce

1. 
2. 
3.

**Comment by MaxIsJoe** [comment]
this doesn't really explain much
what is the issue exactly? are there any errors inside the console or in the staging errors channel? what have you done to come to the conclusion that cargo bounties don't work even though I've tested them just a few hours ago and they seem to be working just fine.

**Comment by Fr-Dae** [comment]
actually I didn't look at the logs
but on a local game, the bounty tab was empty.

**Comment by MaxIsJoe** [comment]
> actually I didn't look at the logs but on a local game, the bounty tab was empty.

The bounty tab is empty because the game no longer has pre-defined bounties, it has random bounties now that appear every couple of minutes.

**Comment by PerfectTangent** [comment]
yeah, doesn't sound like a bug. Closing.
