### ISSUE TITLE
Somes bug on local mod

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8809]
on local session, i have spawn some mob, m90, magazin 

- mob don't move/attack
- incendiary ammo (OP70 9mm) don't make spatial effect
- Magboot (all) sticks you to the ground
- jukebox broken, push play and you have 2-3 jukebox in same time
- belt animation don't work
- we can't walk on lava with or without boots, magboots 

https://youtu.be/ZcMakfdYu6Q

**Comment by Fr-Dae** [comment]
.

**Comment by PerfectTangent** [comment]
issues should cover 1 bug each, Dae.
