### ISSUE TITLE
Items on the UI is scaled down

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#881]
# Preliminary information
If you pickup an item the sprite is squished and scaled down while in your inventory slot.

## Category
BUG

## Bug: Release or Development?
Development

# Report
## Current Behavior
![image](https://user-images.githubusercontent.com/22187456/35128383-38a354f4-fcae-11e7-8cec-ff4251661947.png)
![image](https://user-images.githubusercontent.com/22187456/35128392-3da37bfa-fcae-11e7-9844-30785a49d7c8.png)
Items are shrinked down in the UI, this applies to every other item that was not shown on the screenshot.

## Expected/Wanted/Requested Behavior
Items to keep their original size while in inventory slots.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Go ingame.
2.Pickup an item.
3.Notice how the sprite was shrinked and made a mess of pixels.

## OS used:
Windows

## System specifications
Irrelevant

## Network
Irrelevant

**Comment by DooblyNoobly** [comment]
fixed
