### ISSUE TITLE
mob/bot don't work

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8810]
on local session, i have spawn some mob, m90, magazin

    mob don't move/attack

https://youtu.be/ZcMakfdYu6Q

**Comment by corp-0** [comment]
Intended, you reached the mob cap. Check the admin log on top of the screen

**Comment by Fr-Dae** [comment]
It happened as soon as I spawned the first ones, they were immobile.
whatever the numbers were

**Comment by corp-0** [comment]
There are already mobs in the map. Try deleting them all and then spawn a new mob. If it still doesn't work, reopen the issue.

**Comment by Fr-Dae** [comment]
I just tested again on a brand new map.
(ministation) the queen generated by the map moves,
If I clone her or spawn another mob (floorbot, zombie, spider)
no one moves 

so no, I don't take time to open an error report for nothing

**Comment by corp-0** [comment]
Delete the mobs that were already moving. There is now a maximum amount of ai allowed to exist at once at any point of the game. New AI will be "brain-dead". K don't think they can recover from that state if slots are available after they have already spawned.

**Comment by Fr-Dae** [comment]
the limitation is really low

**Comment by PerfectTangent** [comment]
well, mobs currently take up a lot of performance, so it needs to be until we find a solution.

**Comment by Fr-Dae** [comment]
and the old method with NN (neural network) took a lot of resources ? because it worked quite well
