### ISSUE TITLE
PushPull isn't done via InputController

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#883]
# Preliminary information

## Category
Refactoring

# Report
## Current Behavior
PushPull uses OnMouseDown(), thus not being PixelPerfect

## Expected/Wanted/Requested Behavior
Refactor it to use InputController

**Comment by fomalsd** [comment]
so what's bad about using OnMouseDown()?
the only bad thing I see at the moment is some weird bug when OnMouseDown() doesn't get executed until item/object's position is changed once ( the same reason for #1064 )

**Comment by fomalsd** [comment]
nevermind, it's really not pixel perfect
