### ISSUE TITLE
folding bed cannot be ordered or built

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8847]
folding bed cannot be ordered or built

**Comment by PerfectTangent** [comment]
it is purchasable in cargo as part of the surgical supplies bundle.

**Comment by Fr-Dae** [comment]
Oh well ... Well, I'll start a wiki list with the contents of the crates. 
thanks

**Comment by PerfectTangent** [comment]
the old wiki has a mostly up-to-date list 
https://unitystation.github.io/unitystation-wiki/#Roles/Cargo%20roles/Quartermaster/
