### ISSUE TITLE
Janitor CART fucked

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8848]
the janitoral cart cannot be moved
(tested on fallstation)

**Comment by PerfectTangent** [comment]
Please make the titles of your issues relevant and descriptive of the problem.

**Comment by Fr-Dae** [comment]
on fallstation, in the janitor's room, there is a cartridge that can be filled with water, it should be pushable or pullable.
it is blocked on the floor
it can't be moved.
Do I need to be more specific or have you learned to read a description before answering like a robot?
