### ISSUE TITLE
Layer issues resulting in interaction failures

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#885]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Latest develop

# Report
## Current Behavior
There are several object layer issues that result in failed interactions:
- Can't interact with items laying above air vents 
- Knifing people standing on chairs tile doesn't always work (some pixels are "dead")
- Might be more

## Expected/Wanted/Requested Behavior
Don't want any of these issues

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Place your victim on an air vent
2. Kill and butcher him (you won't be able to pick up meat)
![c3d3760c8ac3d79a](https://user-images.githubusercontent.com/10403536/35156419-d0ff7dfc-fd41-11e7-88fb-a1beac68184a.png)

## OS used:
Windows

**Comment by fomalsd** [comment]
If you put a knife on air vent tile, you will only be able to pick it up by clicking pixels that are not intersected by vent sprite (a few top and bottom pixels only)

**Comment by krille90** [comment]
hm, I am not able to reproduce this. Neither on the latest develop version, nor the Steam beta.
@fomalsd does this problem exist for you on the Steam version`?

**Comment by fomalsd** [comment]
Hm, steam version seems fine for me as well (at least concerning air vents)

**Comment by fomalsd** [comment]
Looks like this one is fixed
