### ISSUE TITLE
[Mapping] Public Terminals need to be mapped onto all mainstations

### ISSUE THREAD

**Issue by AtnerNT** [unitystation/unitystation#8850]
### Description

As of #8808 we now have public terminals, as a result they now need to be mapped onto mainstations, as a _minimum_ stations should have _atleast_ one public terminal for each of the following: Engineering, Cargo, Medical, Command, Research, Security, Service as well as atleast one Civilian terminal, in either Dorms or another common room. 
While this is the minimum, the more the better and ideally departments should have 2-3 terminals depending on their size.

- [x] Mini Station
- [x] Fall Station
- [x] Square Station
- [x] Outpost Station
- [x] Box Station
- [ ] Pog Station

**Comment by CorruptComputer** [comment]
These have been added to FallStation

**Comment by corp-0** [comment]
Closing as all stations currently in rotation have public terminals now. 
For PogStation, we can open an issue using the new mapping template when it is back on rotation if there are missing objects.
