### ISSUE TITLE
Random spawners are not spawning correctly inside closet containers.

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8852]
tested on fallstation
![unknown1](https://user-images.githubusercontent.com/23202421/174043946-c5fd1f0f-3178-4613-89a8-2afccf316adc.png)
![unknown](https://user-images.githubusercontent.com/23202421/174043952-f9f518eb-ba43-4365-b2c7-1d4e144050dd.png)

some stuff aren't identified on medbay's closet

**Comment by MaxIsJoe** [comment]
this is old and no longer happens
