### ISSUE TITLE
[mapping] Fallstation vortex

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8861]
**Environment**

**- Game Version:** 22-06-15-20
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in FallStation, In south ouest of church

**Manipulation**
Move to the vortex

**Result**
Nothing

**Expected**
has a base under construction (or in ruins) with lots of materials

**Comment by PerfectTangent** [comment]
please title your issues appropriately.

**Comment by PerfectTangent** [comment]
just naming the map is not sufficient. Describe the problem in the title of the issue.

**Comment by Fr-Dae** [comment]
Description update
title are Fine

**Comment by Fr-Dae** [comment]
link to a pr ?
