### ISSUE TITLE
increased the limit of active mobs

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8864]
**Environment**

**- Game Version:** 22-06-15-20
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in FallStation, in Office, spawn

**Expected**
the population limit is much too low, so many entities are deactivated from the beginning of the game,
It was said that this would be to reduce lag. but even with 40 chicks the game was still running at 60fps. with a very decent latency. 

i don't understand

![2022-06-16-210502_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/174157319-50889b11-a91e-4371-889c-6647beb30d64.png)

**Comment by MaxIsJoe** [comment]
I think this has been fixed already in  #8891

**Comment by corp-0** [comment]
there isn't a cap on amount of mobs now, we deactivate them when no player is around so this can be closed.
