### ISSUE TITLE
strange bug on hub

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8876]
### Environment
- Game Version: hub 930 and 
- OS Version: Windows 10

### Detailed description of bug

game don't run 
and hub self delete

### Steps to reproduce

you launch the hub
if you don't delete the "install" folder the game won't start or be deleted from the "install" menu 
once done you can download the game again
except that today when you launch the game it tells you "connection lost".

after download the new server version
the hub self remove and we can't extract it 

https://youtu.be/wNZpKPXKAh0

**Comment by Maximal98** [comment]
Could you send the Logs when it fails to start or delete the Game? because reading the terminal output it seems to be an access issue, for deleting at least

**Comment by corp-0** [comment]
can you try running as administrator?

**Comment by MaxIsJoe** [comment]
This is no longer an issue as far as I'm aware, and there will be some major changes in the next stationhub update; so I'm closing this to avoid confusion.
