### ISSUE TITLE
[Mapping] Fallstation - Two buttons are merged on the wall

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8877]
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in Square, At Cargo

Two buttons are merged on the wall
those who control the reinforced panels, for the shuttle

they are present on top of each other, visible with a right click.
but you can't interact with them via the right-click menu,
so only one works.

**Comment by ThatDan123** [comment]
Think i fixed this on the prefab as it was set to snap to grid can you check in game please
