### ISSUE TITLE
Global Music not work

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8882]
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in Fallstation, 

on admin modes
open"global music" menu
select a sond
and ear nothing

**the music player  seems to be broken**
I assume this is related to the broken jukebox

**Comment by Pockets-byte** [comment]
duplicate of https://github.com/unitystation/unitystation/issues/6235, this is a known issue

**Comment by PerfectTangent** [comment]
#6235 describes that sounds are not all correctly listed, no? 

> select a sond
> and ear nothing

This issue says that it's failing to play selected songs. Sounds like two different bugs.

**Comment by Pockets-byte** [comment]
this issue is caused by the previously mentioned issue, the reason the
songs do not play is because they are aren't listed correctly
