### ISSUE TITLE
xeno don't take dommage

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8908]
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
HOP , in Fallstation, 

I have spawned various weapons
op70, m90, stechkin, shotgun
and I wanted to empty some magazines on xeno that I spawned in perma.
The bullets have no effect on them. neither the normal nor the phasing.
The incendiaries still have no visual effect (or damage) 
They do take damage, if you throw the magazine at their head.

**Comment by AtnerNT** [comment]
This is a bug with guns not dealing damage to living things (including players) and not mobs in general. Should be fixed by #8907 once merged.

**Comment by corp-0** [comment]
can this be reproduced now? It should have been fixed already

**Comment by ThatDan123** [comment]
closing unless reported again
