### ISSUE TITLE
Add Map Rotation w/ Meta. B: 100

### ISSUE THREAD

**Issue by Epicworlds** [unitystation/unitystation#891]
- Create a round-robin map rotation system that changes to the next map in the rotation every 10 rounds.

- Recreate Omega Station map to be included in map rotation.

Map Rotation will include:
Outpost (DONE)
Metastation (TO DO)
Flashlight (DONE)

**Comment by DooblyNoobly** [comment]
Criteria:
 
 - After round ends make the server load the next map scene (this should automatically load for the clients)
 - Make sure maps are ready and in a playable state (make sure maps are airtight)
 - Only include the currently finished maps

Bounty of 100usd will be paid on successful merge

**Comment by DooblyNoobly** [comment]
Map rotation will only happen with 2 maps: OutpostDM and Trailblazer (called flashlight.scene)

**Comment by DooblyNoobly** [comment]
Updated bounty to B: 60

**Comment by DooblyNoobly** [comment]
Updated bounty to B: 100
