### ISSUE TITLE
delet caracter bug the admin interface

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#8910]
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
HOP , in Fallstation, 

open the spawn admin interface at the top right
tools deleted
click on a character (for example yourself)
esc. (to cancel)
open "player manager" and 

see nothing functional.

**Comment by ThatDan123** [comment]
Fixed in #9016 i think
