### ISSUE TITLE
Mining Satchel UI Stuck 

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#8954]
- Game Version: 22071711
- OS Version: 1.14

The mining satchel's upper UI for changing drop amounts will persist even after dropping the satchel.

Steps:
1.) Pick up a mining satchel
2.) Drop it

Example:
![Screen Shot 2022-07-18 at 3 03 05 PM](https://user-images.githubusercontent.com/61613068/179625496-fecae881-3991-4a49-8a4e-692ffc0a7126.png)

**Comment by Q4ik** [comment]
That’s the same for botany and trash bags.
