### ISSUE TITLE
Player Move [Physics?]

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#9]
- [x] Develop move method on player control using some kind of pseudo physics move functions
- [x] Snap character to tiles
- [x] Improve the node targeting so player does not snap backwards or sidewards when they are halfway between a tile when input is stopped

**Comment by DooblyNoobly** [comment]
So, the biggest problem we have is setting the player on a tween between two points and knowing when to apply control again to the character. I.E. if the character is 1/3rd of the way to the transform.position of the target tile and the player presses a directional control again then how do we handle that? Because this can throw the character off course and ruin conditions. 

Here is what I thought: We use a ray-trace to get the current tile that the Character is standing on. Then we calculate A) Its boundaries and B) if it is walkable (I.E. Space tiles = No gravity). Then we allow movement only once on that tile. So player presses the KeyCode.D and gamemanager checks to see if the player is allowed to walk that way and if yes then we start the transform.translate / lerp / Vector2.MoveTowards [whatever we end up choosing]. BUT, once the player leaves the boundaries of that tile then we allow control input again. So the player can move even before it has reached the destination and this should look fluid A F and allow the gamemanager to make accurate determinations of the suitability of the next tile the player wants to walk too.

**Comment by DooblyNoobly** [comment]
I think we have been thinking about this problem all wrong. Why not just get rid of locked down tile movement all together? It could increase the fun. I've coded in a little test and it feels pretty good. We can just leave atmos / construction / electricity as tile based. Items become easier to place and will avoid excessive stacking, just drop them on the ground with a collider and trigger. This will dramatically decrease the complexity aswell. This will also avoid the need to calculate our own physics. I.E when a player runs into another player and instead having to calculate the movements for both players to apply the push, just let unity handle it! 

Proposed benefits:
- Improved combat
- Precise OnCollision physics (On hits, collisions, bullets, getting a bottle to the face)
- Precise OnTrigger events (operating machinery, consoles, picking up tools etc)
- Throwing shit will be cooler
- Gameplay feels smoother and faster
- removes a huge layer of complexity to our code, development will be 100 times easier
- Easier to build netcode with
- Gravity is cooler, meaning we can introduce shuttles that actually respond to zero-gravity physics and will need to be actually steered or piloted by a player! Imagine having to actually look at a radar on the mining shuttle and trying to steer the shuttle to it and dock on the mining station by using controls. Unity can handle all this stuff with ease and will breath fresh life into those departments that aren't that popular, like mining.
- cooler jetpack physics
- Evolves SS13?

I think this is a "Outside of the box" idea that could actually turn out to be the best decision for unitystation. Let me know your thoughts.

**Comment by filthmancer** [comment]
Theres a lot of value in restricting calculations to discrete intervals
like a grid based system. Without that, the system will have to calculate
all positioning info constantly, all scripts that check position will have
to run for each user, etc.

With a grid based system, you can conceivably have a single manager that
understands the positions of everything on the station or at least knows
another manager that does. Then all position calcs can be run with that
info.

anyway this would only be a problem with big stations. networking is all
about having to pass the least amount of info between machines, confining
everything to a grid allows the computers to have a good estimate of where
everything could be at a given time. but with a small station it wouldn't
be that much info to pass.

grid based also makes it a lot easier to work with collision problems. like
if a door is blocked by another player, in a non-grid game you could
feasibly get 'around' the player using the physics engine. in a gridded
game that door is totally 'blocked'

**Comment by DooblyNoobly** [comment]
Like you said this would only be a problem with big stations and we will have to scale up to see how much the network can handle and then overcome the problems as they arise. In regards to blocking things, you would just adjust the player colls to be big enough to do things like that (I think I have a good size sorted out on the player now, and will test once we have a door in). And with the player intent set to Attack this would make the players rigidbody2d.isKinematic = true making anyone else trying to get past them impossible. 

Granted, this will deviate a bit from traditional SS13 but its more of a slight evolution. 

Btw some more benefits I could think of: 
- We get access to mass and we can use linear drag and angular drag to simulate station gravity (which you will see the example I'm about to push)
- We can reduce players speed quite easily if they get sick or are injured. And on the opposite spectrum we can easily speed them up if they are buffed because of implants/drugs etc
- Why less code is needed, with grid based we have to pretty much have our own pseudo layer of physics

I'm about to push an example of non grid locked movement in action. For everyone to try out.

**Comment by kaffo** [comment]
While I'm all up for trying new things, I think grid based should be our first objective.
There's a lot of benefits from grid based too, and then mixing grid based and pixel perfect is going to be nuts. If you need to do a calc involving a grid reference, and the player is standing between 4 tiles, where is he? It also makes collisisions between doors/walls/objects horrible too.
This could be something we feature toggle later, let people decide if they want a "newer" pixel perfect movement system or if they want "classic" grid based.

**Comment by DooblyNoobly** [comment]
Yup grid based should definitely be used initially to create the map and place the objects. It should also be used for any loose tiles moves from an explosions etc. Even the singulo should move from tile position to tile position. 

 But when it comes to player movement, then you have a big problem. Because when do you allow control input while the player is "tweening" from one tile to another? Just setting transform.position is very limiting and does not look or play that great, the moving is very jerky as the character hops from tile to tile. So there needs to be a move function being used from either the rigidbody or transform components.

 My first thought was to check the boundaries of the tile beneath the character and allow player input once they leave the boundary of the tile so the player can change direction mid stream, otherwise the player has to wait until the character gets to the target tile before input is allowed again (resulting in jerky movements). 

But here lies the problem, we end up with a complex web of conditionals and tile checks. Especially when we have to calculate how many adjacent tiles need to be checked for passable bools when the player holds down the movement keys, or gets bumped by another player or just mashes all the keys to dance around like a crazy baffoon.  The complexities start to become exponential. 

So I thought whyyy do we actually need tile to tile? I'm not solely attached to this idea and don't care much on which direction we do eventually take but after mulling over this new direction I am starting to see alot of benefits that spring from it (like I have written above). I think this still needs alot of discussion before we choose which direction to take because this will underpin the foundation of the whole game itself.

Anyway, try the build, see for yourself and let me know your thoughts.

**Comment by Gavinvin** [comment]
Are far as I understand it (in the current game)  item placement is never based on the grid system.  Items are placed wherever you click, the only thing that's based on grids is water and things that make tiles slippery. So it doesn't affect items whatever movement system we use. 

In terms of combat, it depends on how we decide to do targetting. Targeting as it current is in ss13 is based on click the other avatar to hit them (or realistically spam clicking everywhere) free form movement would only make it even harder to target someone.  

I don't think it would affect development speed by a big degree either. SS13 is currently using a combination of grid and pixel based systems, once we get the movement code sorted we don't really need to touch it. We can handle collision grid or physics based even if the movement is grid based.

**Comment by DooblyNoobly** [comment]
> We can handle collision grid or physics based even if the movement is grid based. 

Cool, ok, well, after much discussion and even after talking to the coderbus devs I am wondering if it is possible to do this. Atm I am going to have a go at moving the character tile by tile but also find a way to update the physics so we can have best of both the worlds. And from what I've heard from filthmancer and jonas, a grid by grid movement will make it easier for us when it comes to the netcode. So this focus means using a move function from physics component to tween between the tiles. I was having heaps of trouble the first time I tried this as the actual grid map was off by 16x16px (didn't know it at the time which threw me off in debug) but I fixed that this morning and will re-attempt. I think we should only fork in either direction if this proves to be a huge pain in the ass.

**Comment by DooblyNoobly** [comment]
Ok, developed the basics of the grid based movement using the rb. What I did was resize all the tiles so that the position of each tile lines up with the grid vectors. This way I could use Mathf.Round to determine what tiles were nearby and target those nodes on movement. A lerp function handles the rest of the movement when the player stops input. 

Haven't cleaned up the code yet as I still need to perfect the GetNode function so it targets only nodes infront of the player when there is a velocity.magnitude value on the rb (so the player always goes forward and doesn't snap backwards when he is between two tiles). Feel free to mess with it.

**Comment by kaffo** [comment]
Need to fix the tile sprite sheets ASAP so everything pivots from the center. It gonna be a lasting problem if we don't sort out all the sheets now.

**Comment by DooblyNoobly** [comment]
Already fixed it kaffo ;) also player sprites too

**Comment by DooblyNoobly** [comment]
Movement is locked down now specifically to each grid. Diagonal movement has been disallowed as seen on the byond version. Movement seems to be alot smoother compared to the byond version. Only thing that is left to do is to check if the next tile is passable using the GameManager checkPassable bool (had to convert the input variables to float but have not tried to implement it yet). Also adjusted camera and removed the broken kloons.
