### ISSUE TITLE
Running along walls and then pressing to run into the wall as well, causes you to stop 

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#900]
# Preliminary information
Running along walls and then pressing to run into the wall as well, causes you to stop 

## Category
 this is a  BUG,

## Bug: Release or Development?
it was  on the Latest steam version Beta 5 

# Report
## Current Behavior
Running along walls and then pressing to run into the wall as well, causes you to stop 

## Expected/Wanted/Requested Behavior
like in TG code you keep on running along the wall instead of stopping

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find long stretch of wall
2.Run along 
3.Press key to go into the wall while still pressing the same key to go along the wall

## OS used:
Windows

## Network
server That is default on steam

**Comment by chairbender** [comment]
I'll take this on.
