### ISSUE TITLE
Ghost Roles Are Broken

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#9019]
### Environment
- Game Version: 22072719
- OS Version: yes

### description of bug

Ghost roles do not appear in the ghost roles menu.

### Steps to reproduce

1. Optionally create a ghost role through admin tools.
3. Die.
4. Open ghost role menu.
5. See no ghost roles including ashwalkers/ancient engineers.
6. Cry.

**Comment by potatoalienof13** [comment]
This apparently does not happen all of the time.

**Comment by potatoalienof13** [comment]
This can apparently happen to a specific person, instead of everyone on the server.

**Comment by MaxIsJoe** [comment]
is this still happening?

**Comment by MaxIsJoe** [comment]
I think this has been fixed
