### ISSUE TITLE
the facehugger does not implant anything in the body and does not cause the death of the host.

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9021]
### **Environment**

**- Game Version:** UnityStationDevelop22-07-27-19
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** EU 

**Detailed description of bug**
**Context**
Head Officer, HOP in Ministation, Xenolab

### Detailed description of bug

facehugs do not implant anything in a person's body, do not create an "organ" and do not cause a person's death.

### Steps to reproduce

1. make a hug to a facehuggers
2. nothing happening

**Comment by ThatDan123** [comment]
Can't reproduce, seems fine on staging
