### ISSUE TITLE
the juckbox is heard throughout the station in double

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9022]
### **Environment**

**- Game Version:** UnityStationDevelop22-07-27-19
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** EU 

**Detailed description of bug**
**Context**
Head Officer, HOP in Ministation, Bar

### Detailed description of bug

the jukebox plays two songs at the same time (1 and 2)
the volume controls only one of the two tracks (and the stop button the same)

moreover the music is heard in the whole station, there is no more attenuation with the distance.

the music is set in "FX volume" and not in "music".

### Steps to reproduce

1. "play" on jukebox
2. go far away
3. still lisen music

**Comment by MaxIsJoe** [comment]
I think this is intentional because the jukebox is a physical thing in game

**Comment by Fr-Dae** [comment]
and for the spatialization, before if we moved away the volume was reduced until we could not hear it anymore.

**Comment by corp-0** [comment]
> the music is set in "FX volume" and not in "music".

This is intentional, like Max said.

> the jukebox plays two songs at the same time (1 and 2)

This is a bug.

> moreover the music is heard in the whole station, there is no more attenuation with the distance.

This would also be a bug, but I can't reproduce it right now.

**Comment by craftxbox** [comment]
This was probably admin shenannigans.

**Comment by AtnerNT** [comment]
Also fixed
