### ISSUE TITLE
"Ian Follow" no longer works.

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9023]
### **Environment**

**- Game Version:** UnityStationDevelop22-07-27-19
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** EU 

**Detailed description of bug**
**Context**
Head Officer, HOP in Ministation, Hop's Office

### Detailed description of bug

our good companion IAN no longer responds to the commands "Ian follow!" and "Ian Stay!
as he is always on the move, it is even more complicated to pull him behind and save him in case of evacuation. 
### Steps to reproduce

1. Say "Ian follow!"
2. nothing happening

**Comment by ThatDan123** [comment]
Using an ! breaks it. Just say "Ian follow"
