### ISSUE TITLE
Vendor interactions stop working after round restart

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#903]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2 beta 5 steam

# Report
## Current Behavior
In title

## Expected/Wanted/Requested Behavior
They shouldn't stop working

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join test server, click vendors around you
2. Wait for round restart
3. Try clicking again

## OS used:
OSX

## System specifications
MBP mid2010

## Network
test server 60ms

**Comment by DooblyNoobly** [comment]
it's because chat breaks now every round restart

**Comment by fomalsd** [comment]
It is not just chat: dispensable items don't appear, too
