### ISSUE TITLE
Map Blast Detectors

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#9052]
Map Blast Detectors in main stations

- [ ] Boxstation
- [ ] Outpoststation
- [ ] fallstation
- [x] Squarestation
- [ ] Unrealstation

**Comment by AtnerNT** [comment]
#9377 Maps blast yield detectors to mini

**Comment by corp-0** [comment]
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

If any station is missing the blast detectors, please open an issue per station.
