### ISSUE TITLE
Hand Teleporter Just Straight Up Crashes The Server

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#9055]
### Environment
- Game Version: 22080521
- OS Version: Yes

### Detailed description of bug

Using the hand teleporter, and trying to go through a portal crashes the server.

### Steps to reproduce

1.  Use the hand teleporter.
2. Try to go through a portal.
3.  Server Crash.
4. Cry.

**Comment by potatoalienof13** [comment]
Also applies to the normal teleporter hub.

**Comment by potatoalienof13** [comment]
Lockers also cause this crash, but items thrown onto the portals do not.

**Comment by ThatDan123** [comment]
Fixes in #9058
