### ISSUE TITLE
Server rules & MOTD not editable 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9183]
### Environment
- Game Version: 22-08-29-18
- OS Version: Lubuntu 18.04x64

### Detailed description of bug
Locale server.

"add here your rules" are not a button, just text.
therefore, we cannot interact with

**Comment by ThatDan123** [comment]
You need to change the txt file in the config folder

**Comment by Fr-Dae** [comment]
Why do you close this issue, manually editing a txt document is not a solution.

**Comment by MaxIsJoe** [comment]
It's a server config thing, the server owner has to change it.
In the future we could add a way for admins to change it in-game, but I recommend adding that after we added admin ranks so only admins with the highest permissions can change it.

**Comment by Fr-Dae** [comment]
In the meantime, this window pops up permanently when you are solo, as soon as you press escape, and is not editable whereas there is clearly a message "add your message here" which implies that you can interact with it.
