### ISSUE TITLE
Admin tools are stuck on "Retrieving server data"

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation#9189]
### Environment
- Game Version: 22083121
- OS Version:  Windows 10

### Detailed description of bug

Player Manager and Game Mode Manager are stuck on "Retrieving Server Data". Alogs, Ahelp, Prayers, and round manger are broken.

### Steps to reproduce

1.  Open up unitystation version 22083121
2.  Open tools
3. 

![unknown](https://user-images.githubusercontent.com/15893891/187969750-625dc2da-17e6-4146-9960-dcd91a7c68b0.png)

**Comment by MaxIsJoe** [comment]
I heard that this still happens so I'm wondering if anyone who had this happen to them have some logs saved

**Comment by MaxIsJoe** [comment]
This hasn't been an issue in quite some time now.
