### ISSUE TITLE
The Top Left Square Buttons Are Leave????

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#9207]
### Environment
- Game Version: 22090413
- OS Version: your mom???

### Detailed description of bug
The top left buttons have stopped existing.  This includes the pda flashlight button, the antag objectives button, and the spell buttons. 

### Steps to reproduce

1. Have a pda. 
2. Have no flashlight toggle button.
or
1. Be a wizard.
2. Cry (no spell)

**Comment by mmails** [comment]
(Adding onto this)

Some AI ui is also missing, i don't know if it's related to this but it could be since It started when the update that broke the buttons released.

(To replicate)

1. become AI
2. try to move cameras by clicking instead of wasd
4. Unable to move D:

**Comment by potatoalienof13** [comment]
Fixed apparently.
