### ISSUE TITLE
Cargo console are fucked

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9289]
**Environment**

**- Game Version:** 22-10-28-00
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale

**Detailed description of bug**
**Context**
HOP , in Fallstation, 

the console, and the cargo menu is completely broken,
some items are no longer in the right section,
each click on a button, makes the interface leave.

On the EU test server, if you change the menu too quickly, it causes freezes and sometimes server crashes.
If more than one person is using the console at the same time, the freeze is even more present. 

Please warn us before touching the console, so we can test it. 

![2022-11-01-154027_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/199261083-f29bc24c-b13c-4d89-a35b-39a9e001de02.png)
![2022-11-01-154044_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/199261088-1cab408f-f270-4c35-9ea7-592e01806814.png)
![2022-11-01-154108_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/199261092-a6a76dc1-bc02-4542-92fe-324fc5fd1f0c.png)

**Comment by ThatDan123** [comment]
@Bod9001 This could be due to #9282?

**Comment by MaxIsJoe** [comment]
tested. this has been fixed.
