### ISSUE TITLE
[Character Attributes] All consoles that rely on `Occupation` spew out errors or completely break

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9293]
### Environment
- Game Version: 11/5/2022 staging
- OS Version: Windows 10

### Detailed description of bug

Tile.
For some reason, a lot of consoles rely on the occupation role on the `PlayerScript` rather than data on their `IDCard`.

### Steps to reproduce

1. Use any console that checks for your occupation
2. It will throw an NRE
3. Will break things like the Public Terminal but other stuff work just fine.

**Comment by AtnerNT** [comment]
This can be closed, believe all the consoles that were broken such as ID and communications are now fixed
