### ISSUE TITLE
The tip for face covering masks blocking facehuggers(and maybe others) does not go away correctly

### ISSUE THREAD

**Issue by wraith-54321** [unitystation/unitystation#9295]
### Environment
- Game Version: 22110505
- OS Version: 

### Detailed description of bug

If you get the pop up telling you face masks block facehuggers the window will show up again even if you click don't show up again.
It looks like if you get the hunger tip then the mask tip will go away correctly.

### Steps to reproduce

1. Put on a gas mask
2. Try and close the tip window

**Comment by MaxIsJoe** [comment]
No longer happens
