### ISSUE TITLE
Clients have their collision broken for movement

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9296]
https://user-images.githubusercontent.com/34368774/200151259-6fb4eca9-96f9-4f48-8907-28288b5d9a04.mp4

Staging 2022/6/11

**Comment by corp-0** [comment]
what the fuck how

**Comment by MaxIsJoe** [comment]
I have no clue, Bod mentioned something about something not spawning correctly but I honestly did not understand what he meant by that

**Comment by MaxIsJoe** [comment]
This no longer happens, closing.
