### ISSUE TITLE
[mapping] Fallstation , medbay acces

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9306]
**Environment**

**- Game Version:** 22-11-05-05
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale

**Detailed description of bug**
**Context**
HOP , in Fallstation, 

the hop, can access to the medbay, to the reserve, 
![2022-11-11-030532_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/201249344-9ed8c4f3-f3ba-438a-a9a0-a09114e1f944.png)
but not to the clonebay, nor to the morgue ?

**Comment by MaxIsJoe** [comment]
I just checked, this is intentional on every map; not a bug.
