### ISSUE TITLE
Announcer machine doesn't announce the new crewmembers anymore

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9309]
**Environment**

**- Game Version:** 22-11-05-05
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale

**Detailed description of bug**
**Context**
HOP , in Fallstation, ministation

when a new player joins the game, at the time of the spawn, there is normally an announcement 
"xxx has joined, he has the roles y". 
this message doesn't appear anymore, it's a problem. 

Same result at version 22.10.22.18

**Comment by corp-0** [comment]
@MaxIsJoe would you mind taking a look at this one? It's been broken for way too long and since you know better the signals system, maybe you can find faster why.

**Comment by MaxIsJoe** [comment]
this had nothing to do with the mind rework. Remove that tag, please.
