### ISSUE TITLE
Botany door sprites are not properly set

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9310]
![image](https://user-images.githubusercontent.com/34368774/201459200-de241661-0cb0-4f61-9313-4e1c7999af54.png)

![image](https://user-images.githubusercontent.com/34368774/201459203-b5cc6877-4f14-41da-baa0-d3ec0a02f68c.png)

### Environment
- Game Version: 12/11/2022 staging
- OS Version: Win10

**Comment by Fr-Dae** [comment]
linked to  https://github.com/unitystation/unitystation/issues/9308

**Comment by corp-0** [comment]
yeah, post your poictures over there as it would be a dup of that issue. I will close this and rename the other one.
