### ISSUE TITLE
Super Matter Alerts Not Working

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#9319]
The super matter chat alerts are not going to the engineering channel.

-Add the signals script to the prefab and select no power?

@MaxIsJoe probably from your radio stuff

This Chat function should probably bypass the radio requirement?

https://github.com/unitystation/unitystation/blob/b5ccad96e927a1b9bfa08b7479b29fae8147f877/UnityProject/Assets/Scripts/Objects/Engineering/SuperMatter.cs#L1068

**Comment by MaxIsJoe** [comment]
Yeah a lot of things needs to be updated to the new telecoms signals system
