### ISSUE TITLE
Tooltips issues

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9326]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

we are regularly obliged to go back to the options to deactivate and reactivate the tooltips,
 I'm talking about "old-tooltips" in red. 
sometimes, when loading the character, they are just not there anymore

**Comment by AtnerNT** [comment]
No longer relevant. Orange tooltips have been removed and red tooltips are now the default/only.

**Comment by Fr-Dae** [comment]
and the settings menu ?

**Comment by MaxIsJoe** [comment]
This is no longer relevant as pointed out. All issues related this has been sorted out already. 

Close this.
