### ISSUE TITLE
radio issue

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9328]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

the u key which regularly interacts with the chat, even when writing a paper.
sometime it's y key too (caractere creation)

**Comment by corp-0** [comment]
I don't understand the issue. You will have to rephrase it, maybe follow the following template:

1. What was supposed to happen
2. What actually happened
3. How to make it happen every time.

**Comment by Fr-Dae** [comment]
**example with character creation.**
Create a character, change the name
If in the name you use one of the keys U or Y 
it will display the character BUT will also open the chat.
so if you write quickly, your text will be half in the chat 

As if, that the active and selected text box did not have priority over the chat.

**Comment by Fr-Dae** [comment]
it doesn't seem to do it for paper, labeler or console anymore, but still does for character creation
