### ISSUE TITLE
[mapping] folder spawn

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9329]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

it is often the file of the wrong colour that spawns in the offices of the heads of services (red at the hop instead of blue
blue QM, instead of yellow
 yellow security instead of red :/)

**Comment by PerfectTangent** [comment]
this sounds like you are observing random folder spawners. The folders aren't typed to specific jobs, except for the classified documents folder and medical folder.

**Comment by Fr-Dae** [comment]
I invite you to read the description of each one yourself.
They refer to different departments.
it is intuitive that this is the case.

Red = security
Yellow = Cargo
Blue = HOP/captain
White = medical


Black and grey are not, in fact, intuitively assigned to anyone. 
![2022-11-22-124456_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/203306291-34a3e954-2f09-4b21-a1bf-5c970d63f3b5.png)

**Comment by PerfectTangent** [comment]
> They refer to different departments.

As the person who added paper folders to the game, I can tell you no, they do not refer to different departments. 

> I invite you to read the description of each one yourself. 

Let's do that:

```
grey folder description: For containing mundane paper documents.
blue folder description: For containing sad documents.
red folder description: For containing angry paper documents.
yellow folder description: For containing extremely bureaucratic documents.
```

they do not refer to departments in the descriptions of the folders.

**Comment by Fr-Dae** [comment]
the colour, plus the description, it is intuitive that certain patterns emerge.
If it is not voluntary, I hear it, but understand that the players do not have your vision of the world.

so yes, in all simplicity, you see a red folder, it's probably the security one.
