### ISSUE TITLE
[CARGO] Paper bin

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9334]
be able to order a batch of 2-3 reams of paper

**Comment by Fr-Dae** [comment]
and make paper with some plants

**Comment by AtnerNT** [comment]
Instead of opening #9332, #9331, #9330 and #9333 all for ordering single items, please try sort these into a single issue like: "Additional orders for cargo: " and include all the things you would like to suggest. As there are now around 10 issues for individual items.

**Comment by PerfectTangent** [comment]
I agree with Atner. Also, paper and many other goods don't need to be purchasable in cargo as they will be manufacturable eventually.

**Comment by Fr-Dae** [comment]
receiving a box, bundle, containing a bunch of useless junk and a pen, is very annoying ...
that's why I asked to add this to the cargo menu.


Yes, in the future, everything will be better, **I'm talking about right now.**
even temporarily, 
to be able to make your own paper would be something fantastic, but I doubt it will take two clicks of the mouse
