### ISSUE TITLE
Tooltips spam

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9337]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

---

the tooltips appear ALL THE TIME

even if they are validated with the brain icon.

Very annoying when using paper for example.

**Comment by MaxIsJoe** [comment]
This has been fixed in #9384 and #9385

**Comment by MaxIsJoe** [comment]
Hellooo, this has been fixeeedddd
