### ISSUE TITLE
[asset] open/close animation missing

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9339]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

-----

large create has no open/close animation.

**Comment by AtnerNT** [comment]
What do you mean by this? Do you mean that it doesn't have an open sprite? doesn't have a close sprite? Please eleborate

**Comment by PerfectTangent** [comment]
large crates don't have an open sprite as they are disassembled with a crowbar. There is an issue describing what's missing. #4657

**Comment by Fr-Dae** [comment]
there is no difference between open and closed mind, so I would say that the "open" one is missing 
thanks bod
