### ISSUE TITLE
page form limitation 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9349]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale & EU playstest

**Detailed description of bug**
**Context**
HOP , in Squarestation

-----

the amount of text on a page is not dependent on the size of the text.
one is limited by a 20th line of text 
that is not much

**Comment by corp-0** [comment]
eventually you will be able to bind multiple pages into a book. That's how you get more space to write.

**Comment by Fr-Dae** [comment]
Why do you close the issue so ?

**Comment by corp-0** [comment]
because it is a non issue. The limit is there intentionally.
