### ISSUE TITLE
[mapping] Cloak

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9351]
[On many maps, the cloaks are missing (cloak)
Captain, HOP, HOS, CE, CMO, RD, QM,

**Comment by PerfectTangent** [comment]
cloaks are not intended to be a part of maps. They are a choice some mappers have made to include in the maps, but they originally aren't something intended to be available to everyone. They are a reward for having played the role for a period of time. I believe the cloaks should be removed from the maps they are in currently and be given that feature when we have the ability to track play time on servers.

**Comment by Fr-Dae** [comment]
attention, I'm not talking about Skillcape, which are similar to runescape awards.

I'm talking about the CLOAKS, which are a ceremonial item for department heads only. 
They're pretty, and they have a pocket.

They are already present, in some maps, 
but not in all of them, that's the problem.

Also, some maps have cloaks, but not the HOS 

![2022-11-22-125443_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/203308634-b035dc21-e60e-474a-b4d3-a2f3f53dfa1f.png)
![cloaks](https://user-images.githubusercontent.com/23202421/203308637-d8dff625-4c0e-443b-9f4d-ff42d68bbb75.png)
