### ISSUE TITLE
MedalBoxes stuck

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9352]
MedalBoxes are all buggy and blocked.

**Comment by AtnerNT** [comment]
More details on issues like this would be appreciated as this doesn't say how they are broken just that they are

**Comment by Fr-Dae** [comment]
![2022-11-22-132730_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/203314300-e4f8abfa-6032-44d2-9db5-3ab11f264f23.png)


These are little boxes that each officer has in his locker, 
which normally attests to their excellence in the field. 
This allows for roleplay scenes, for example, to congratulate an employee who would have made a good vice-chief.

and the box is blocked, literally, you can't open it.
