### ISSUE TITLE
[mapping] clothe dispenser

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9353]
instead of having a locker with a bunch of clothes, wouldn't it be possible to have a vending machine by profession/department + officer
with the alternatives, 
for example, there is the security suit, the security jumpsuit, the security envirosuit, and the turtleneck (HOP and RD only)

**Comment by AtnerNT** [comment]
We already have those and they are used in alot of places. However we dont use them for command roles as there is only one of each command. If the clothes are only for one person it makes sense to only be in their personal locker, considering that lockers are often used for storing clothes.

**Comment by PerfectTangent** [comment]
Yeah, we already have this.

**Comment by Fr-Dae** [comment]
The personal locker is full of rubbish.
in view of the possible alternatives of some outfits, and that some of them are only available via the admin menu.

If they were all to be stored in the locker, it would be a bloody mess.
