### ISSUE TITLE
Power cells

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9354]
Be able to manufacture/order an **improved weapon power cell**

**Comment by AtnerNT** [comment]
Power cells are a stock part and manufacturing higher level parts comes under science. We have the powercells in game and they are mapped as loot in a few places, however as we do not have the techweb research complete yet thats why we are unable to manufacture. But this comes under the science W.I.P

**Comment by Fr-Dae** [comment]
**Therefore, temporarily** until the new tech-tree system arrives, I ask that it be available for expensive cargo.

**Comment by AtnerNT** [comment]
Can be closed as higher tier powercells are now availiable in the techweb
