### ISSUE TITLE
[alien] facehuger can't hug monkey

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9363]
nothing more to say

**Comment by AtnerNT** [comment]
Not a bug, just a feature we don't have. If you are suggesting features please mark the issue as Type: Feature instead of Type: Bug

**Comment by MaxIsJoe** [comment]
Facehuggers can't hug monkeys because monkeys still use HealthV1 instead of V2
Face hugging is a mechanic only creatures that use HealthV2 have.

**Comment by Fr-Dae** [comment]
ok, thanks for the information, except here how can we know that? 
have you written a note or information about this somewhere?

**Comment by corp-0** [comment]
nah, no notes. But it wasn't possible even before the health rework because we never did the feature. I will close for now, since it needs a feature request issue with all the information on how it should work.

**Comment by Fr-Dae** [comment]
If the description does not suit you, edit it or complete it.

Why close a possible future update?
Isn't the best way to do this is to create a branch from an issue, to make it easier to tracking it?

**Comment by corp-0** [comment]
you reported a bug, you didn't do a feature request.
