### ISSUE TITLE
graphic interface to host private servers

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9371]
in the idea of creating a private server, it would be interesting to have an option where, to join, a password, defined in the configuration of the server (thus with the ingame admin interface, and not a file to be edited)

This way, even if an IP is broadcasted by mistake, only the people with the IP + Password will be able to join.

**Comment by corp-0** [comment]
I will rename your issue to convey better the suggestion. We currently support private servers using a whitelist of ip's, which have to be handled by editing a file.

I think having also a graphical interface, despite not being really useful for headless servers, is a good addition.

Regarding the password, I think we don't have that feature currently, but I might be wrong.

**Comment by Fr-Dae** [comment]
> for headless servers

yes, except that EXCLY, I'm not talking about headless servers, but host servers like any basic user would do

- Open port 7777
- Host a game
- go to my ip.com
- Give the ip and port to my friend in private conversation.

I'm talking about being able to set the word of the day, the rules, or a password directly in a GUI. exactly like the "server settings" option that allows you to restrict the number of players. (by default 100) 


In the case of a headless server, yes editing a file is fine, although adding withlists is very annoying, because you need to know BEFORE the server starts the exact ID of the person you want to invite, and to add another one, you have to restart the server.

If intuitiveness were a person, it would open its veins at that moment 


> I will rename your issue to convey better the suggestion

thanks you, find a good title aren't easy all time.

**Comment by ThatDan123** [comment]
> I will rename your issue to convey better the suggestion. We currently support private servers using a whitelist of ip's, which have to be handled by editing a file.
> 
> I think having also a graphical interface, despite not being really useful for headless servers, is a good addition.
> 
> Regarding the password, I think we don't have that feature currently, but I might be wrong.

Just a correction, it's whitelisted userId's not Ip's

**Comment by Fr-Dae** [comment]
Yes, that is what I wrote.

**Comment by ThatDan123** [comment]
I'm working on this since it's pretty easy
