### ISSUE TITLE
Tooltips stuck in screen

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9376]
**Environment**

**- Game Version:** 22.11.12.16 -- 
**- OS Version:** Lubuntu 18.04.6x64
`Linux version 5.17.0-15.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-19ubuntu1~bionic (2022-06-14)`

**- Server:** Locale

**Detailed description of bug**
**Context**
captain  , in squarestation

https://youtu.be/FxbR6OXFY6g

![2022-11-24-144026_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/203798489-6ae70bad-871a-446a-984a-f8f265941e91.png)
![2022-11-24-144030_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/203798497-e04f2285-a9e5-44b2-9a21-bc9427e9f083.png)

**Comment by MaxIsJoe** [comment]
this is already fixed and the screenshot has nothing to do with it 

close it

**Comment by corp-0** [comment]
it can remain open if the fix hasn't been built yet

**Comment by MaxIsJoe** [comment]
> it can remain open if the fix hasn't been built yet

A build has been there for four days now
