### ISSUE TITLE
Changelog Cleaning

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9378]
Hello,
 is it possible to clean up the different changelogs that exist in the project?
I would like to know if it is possible to have only one changelog to follow please.

**Thank you.**

**ps:** is it possible that the web changelog could take a bit more of the screen width to make it easier to read, thanks. 

https://github.com/unitystation/changelog/blob/main/CHANGELOG.md
https://github.com/unitystation/unitystation/blob/develop/CHANGELOG.md
https://www.unitystation.org/changelog#

**Comment by corp-0** [comment]
Yes, we have to delete the changelog file in the repo. The website is the only official way to read changes now.

Regarding the style, if you know or know someone who has web dev experience, the whole website source code is at https://GitHub.com/unitystation/unitystation-web

**Comment by Fr-Dae** [comment]
j'ai un CSS responsible, je vais voir s'il fonctionne ici.
