### ISSUE TITLE
aghost issue, again

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9394]
at localhost
sometimes, without too much reason, (in admin mode only) 
the aghost mode activates all alone, that also put to arrive whereas I was not on the window of the game (it is the sound which made me return in game)

**Comment by corp-0** [comment]
are you able to reproduce this bug in latest version?

**Comment by Fr-Dae** [comment]
seen on the USA server during the playtest with bod as admin,
I was xeno queen, and twice, I was taken out of my body

fortunately I was able to go back
and I didn't take into account the HRP information when I was a ghost.

**Comment by corp-0** [comment]
this doesn't happen anymore, does it?

**Comment by Fr-Dae** [comment]
The only problem I had was that I had to delete the game from my local host.

The only problem I had was that I had to delete 
/.local/share/StationHub/prefs.json
/.local/share/StationHub/settings.json
to be able to restart the hub (otherwise it would load in a loop)

but I'm not sure if this has anything to do with the current problem 

@eurtod ? 
@LastCaptainBonk ?
@CorruptComputer ?
same for you ?

**Comment by corp-0** [comment]
that sounds like an unrelated error. Hub shouldn't have anything to do with ghosts in game. All hub does is launching the game.

**Comment by LastCaptainBonk** [comment]
Does not affect me.

**Comment by Fr-Dae** [comment]
> that sounds like an unrelated error. Hub shouldn't have anything to do with ghosts in game. All hub does is launching the game.

this is the only notable thing I noticed when I tested the game census. 
I've been able to stay logged in for several hours on a localehost without worrying about being kicked out of my body
but this happened mainly when I spawned as an alien or respawned 

I can test again if you want,

**Comment by corp-0** [comment]
> I can test again if you want,

please

**Comment by Fr-Dae** [comment]
ok i have bugs in aghost + queen

- for the moment I'm not randomly expelled from the body anymore
- the ghost has queen action buttons
- the queen always has her buttons mixed up (icon doesn't match the text)
- the interface on the right is always shifted from the edge of the screen (they "float")
- the action bar remains fixed and empty 
- the health status is deteriorating and remains orange for no reason

**Comment by corp-0** [comment]
closing as even if you found new bugs, it seems like the one this issue mentions isn't happening anymore.

**Comment by Fr-Dae** [comment]
AND i just got ejected from my drone body, i think there is a link between xeno and aghost eject

**Comment by Fr-Dae** [comment]
[Player_Dae.log](https://github.com/unitystation/unitystation/files/10484846/Player_Dae.log)

**Comment by Fr-Dae** [comment]
i have add "eject" in console to mark where the event has actived

**Comment by Fr-Dae** [comment]
so it's linked to respawn in admin,
and / or xenomorph

**Comment by eurtod** [comment]
Never had this problem, had something kinda related where when aghosting player would run around randomly for a bit but doubt its related.

**Comment by MaxIsJoe** [comment]
Not reproducible. Probably fixed long ago.
