### ISSUE TITLE
alien respawn menu order

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9395]
atm respawn alien, is not in the antagonist menu but in the "special job" menu which is not logical

**Comment by AtnerNT** [comment]
I believe Xenos are not considered antagonists as they do not have objectives and/or are not part of a gamemode. Xeno's in the game are closer to ancient engineers and ashwalkers than antagonists in terms of functionality.

**Comment by Fr-Dae** [comment]
it's strange, because ERTs exist to respond to a mission, "fix the station".

But they're more like "protagonists".

the aliens, whose only purpose is to multiply and serve the hive. 
Does it matter that this is not explicitly written? 

but yes ... a creature that exists to kill and evicerate the other living creatures it encounters, we are indeed close to the definition of an antagonist. 


ps: the fugitive is also a ghost role, yet they are listed in the antagonist =)

**Comment by AtnerNT** [comment]
Special Jobs are any jobs that dont fit into typical crew occupations and are not antagonists. Antagonist specifies something very specific in the games code, they are managed by our antag manager, have objectives and goals that appear on the end of round screen etc. Xeno's do not fit our definition of antagonists, and they are not a crew role, so they are put in special jobs. Fugitives like you mentioned, do fit our definition, in the code they are an antagonist occupation with objectives (Survive free as a bird)

**Comment by Fr-Dae** [comment]
I'm talking about gameplay only, not code. =)

**Comment by AtnerNT** [comment]
Xenos still dont have objectives and arent official antagonists, which is why they are not grouped with them

**Comment by AtnerNT** [comment]
Once stuff like carp ghost roles get added, they will go there too as space carp is not an antognist

**Comment by AtnerNT** [comment]
Could possibly add a new category like: Mobs. And that could work, especially when we get more playable mobs. But they shouldnt be grouped with antags

**Comment by Fr-Dae** [comment]
I'm sorry but the **dicionary** doesn't agree with you, anything that is not a protagonist, that seeks to block, stop, or kill the player is, therefore, an antagonist. 
in the strict sense of the word.


**and yes** you are right, it would be good if a message appeared for the xeno, something simple like
- protect the queen
- making the hive grow
- serve the hive.
- survive

**Comment by corp-0** [comment]
the reason why they are there is explained already. Closing.
