### ISSUE TITLE
[Mind Rework] Respawning doesn't always work

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9400]
### Environment
- Game Version: Staging - 29/11/2022 
- OS Version: Win10

### Detailed description of bug

![image](https://user-images.githubusercontent.com/34368774/204497337-26da17dd-b8a6-48c8-955c-b7809ff17392.png)

When trying to respawn as something else, the player doesn't get moved to their new body. Creating husks.

### Steps to reproduce

1. Be an admin.
2. Respawn the player as something.
3. Watch as the player doesn't get moved to their new body, and their new body just stays there as an empty husk.

**Comment by corp-0** [comment]
I don't think this is still happening, is it?
