### ISSUE TITLE
add an option in settings for "streamer mode"

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9405]
In a menu option (e.g. accessibility, which will be used later) a checkbox

Have an option to disable two annoying things when streaming or recording 

- IPs of people in admin mode, to avoid disclosure of sensitive information.
- flip-flop music will be skipped automatically (will not be played) thus avoiding DMCA concerns recurring on youtube.

**Comment by waffielz** [comment]
hiding IPs and muting the music when you first pop in would be amazing, manly hiding IPs because doing that in post is omega lame
