### ISSUE TITLE
[BUG] Crafting Menu does not show any recipes or catergories.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9408]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22112816

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Crafting Menu when open is blank beside the background UI box and search bar which doesn't work.

### What should have happened instead?

The crafting menu should have recipes and categories to select from. Using the search bar should show crafting recipes matching the name in the search bar.

### Steps to reproduce the issue

Simply click on the crafting button in the corner.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/205987862-d8c8842b-40fc-4336-8e3c-e4fb0959f4dd.png)

Tested on staging, seems like it was fixed.
