### ISSUE TITLE
[BUG] Asteroids can spawn in the way of Cargo Shuttle in Ministation

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9410]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22112816

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

An asteroid spawned in the way of the route the cargo shuttle takes on Ministration causing the cargo shuttle to be destroyed and losing the stuff I was trying to sell and receive.

### What should have happened instead?

There shouldn't be an asteroid there, a NO ASTEROID ZONE should be placed in that area. Or some kind of automatic tile removing thing in the path when the station is generated.

### Steps to reproduce the issue

1. Get unlucky with asteroid spawn RNG
2. Send the cargo shuttle to centcomm
3. Follow the shuttles path
4. Asteroid ):

**Comment by AtnerNT** [comment]
Must be an issue with our asteroid clearing thing not working with sideways shuttles. I will look into it soon
