### ISSUE TITLE
[BUG] Every "portable" (can be dropped on ground) light has weird bright aura of light around it.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9413]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22120122

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Grabbing a light source and turning it on will produce light and have a harsh ball of light surrounding it (see attached image).

![img](https://user-images.githubusercontent.com/119550415/205200616-b457c704-4c0a-4b9b-a327-f4a80115f7bc.PNG)
Items shown are a Desk Lamp, a Flashlight, a Hard hat, a different type of Desk Lamp, a Lantern, an Engineering hardsuit helmet, and a Banana lamp.

### What should have happened instead?

Lights should have a smoother less harsh glow.

### Steps to reproduce the issue

1. Grab a light source.
2. Turn it on.
3. Drop it on the ground.

**Comment by eurtod** [comment]
The portal as well is extremely bright.
![image](https://user-images.githubusercontent.com/119550415/205201423-08a5d3ef-9ea7-4650-a3c7-58bde08d75a5.png)

**Comment by AtnerNT** [comment]
@Bod9001 Didn't you merge a fix for this a few days ago?
