### ISSUE TITLE
Remove Methods from TMS that are only based on the position B: 15

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#942]
# Preliminary information

## Category
TODO

## Bug: Release or Development?
dev

# Report
## Current Behavior
Currently, methods like IsPassableAt(position) are being used. In the context of windoors, it doesn't makes sense though, as a direction from which it could be passable is always needed. IsPassable(position) and IsAtmosPassable(position) shouldn't exist in the first place.

## Expected/Wanted/Requested Behavior
Remove IsPassable(position) and IsAtmosPassable(position)  and rewrite those to the IsPassable(origin, position) and IsAtmosPassable(origin, position) 

## Criteria

- [ ] Search the codebase to find all uses of IsPassable(position) and IsAtmosPassable(position) and convert them to IsPassable(origin, position) and IsAtmosPassable(origin, position)
 - [ ] Test the game thoroughly and make sure there are no bugs
 - [ ] Remove the IsPassable(position) and IsAtmosPassable(position) methods from the matrix

**Comment by DooblyNoobly** [comment]
Didn't I see some of this conversion in your meta layer PR?

**Comment by krille90** [comment]
Well, that PR didn't really focus on that and there are still many locations to replace it. :)

**Comment by DooblyNoobly** [comment]
Criteria:

 - Search the codebase to find all uses of IsPassable(position) and IsAtmosPassable(position) and convert them to IsPassable(origin, position) and IsAtmosPassable(origin, position)
 - Test the game thoroughly and make sure there are no bugs
 - Remove the IsPassable(position) and IsAtmosPassable(position) methods from the matrix

Bounty of 15usd will be paid on successful merge

**Comment by techy2493** [comment]
I'm going to begin an attempt to tackle this.

**Comment by techy2493** [comment]
Doors are using IsPassable(position) to determine if the door can close... Should an origin be added to this?
Will objects on the same origin always be able to pass an object to prevent players from getting stuck? If so what origin should be used for the isPassable of a door closing, probably not the door's origin itself otherwise the door would always be able to close as any object in it's path would be on the same tile and therefore passable? 
Should there be a different mechanism to detect if there is an object blocking a door from closing?

For reference I'm talking about assets/scripts/doors/DoorController.cs line 134.
@DooblyNoobly @krille90

**Comment by DooblyNoobly** [comment]
Pulsey would be the best to answer that (does the IsPassable ignore the origin?). At the moment it ignores players too which is bad.

**Comment by krille90** [comment]
@techy2493 Hey, sorry for the late reply. Was really busy. 

> Should an origin be added to this?

Yes, and the origin should be different from the current position though (as that will be ignored)
( a different way would be to make IsPassableAt(position) as a wrapper for IsPassableAt(from, to) with the origin being misplaced (e.g. + Vector3Int.up).

A different mechanism would be possible, but I think it could be done as described above.

**Comment by Renaultius** [comment]
I'd like to give this a go, though I'm a bit of an amateur and can't really promise I'll be able to figure it out properly. It'll at least give me a reason to go trawling through all the scripts and improve my skills. :P
