### ISSUE TITLE
[BUG / Mind Rework] gender is no longer being set properly.

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9423]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22120318

### I was

Client

### OS

Linux

### What happened?

Trying to use features that reference gender show all characters as male or with he/him pronouns even though players might have set their preferences to something else.

Try this with the hover tooltips or with the laughing emotes, you'll always get male laughs and "he/him" in the detailed mode of the hover tooltip.

### What should have happened instead?

While laughing as a female character, you should make a female voice laugh.
While hovering over another player in detailed mode, you should display their correct pronouns.

### Steps to reproduce the issue

1. Type *laugh in chat.
2. Observe if the sound made is the same as your chosen gender's
3. Press and hold shift while hovering over players.
4. Ask if their characters pronouns that they set while making this character is the same as the one you're seeing.

### Additional context

Players should have their characters genders and pronouns set correctly so that systems can correctly use and display the correct values.

**Comment by corp-0** [comment]
related to #9398 more than likely
