### ISSUE TITLE
[BUG] Spawning as same character as before rather than a Ashwalker when choosing ghost role.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9431]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22120919

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Spawning as a ghost role for Ashwalker I am still the same race and character as my previous body. (Human, Old man.)

### What should have happened instead?

Should be a ashwalker race.

### Steps to reproduce the issue

1. Die
2. Ghost role menu select ashwalker

**Comment by corp-0** [comment]
Fixed by #9438
