### ISSUE TITLE
[BUG] Handheld and equip able light sources stop generating light when dropped on the ground.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9432]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22120919

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

When holding a light such as a flashlight, lantern, hard helmet, etc. that is turned on it generates light however when it is dropped onto the ground or placed on I table I suppose it stops making light.

### What should have happened instead?

The light source should still generate light if it is on even if it is on the ground.

### Steps to reproduce the issue

1. Grab a flashlight
2. Turn it on
3. Drop it

**Comment by corp-0** [comment]
Fixed by #9448
