### ISSUE TITLE
[BUG] Wet floor Holoboards are solid

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9443]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121502

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

![image](https://user-images.githubusercontent.com/34368774/207787985-638a3bed-0e29-47db-8e33-153f7a13f4d6.png)

Got stuck by holograms 

### What should have happened instead?

Should be able to walk through them and not be blocked by them

### Steps to reproduce the issue

1. Create a holograms using a holobarrier
2. Try walking through them

**Comment by eurtod** [comment]
I am able to walk through them when I stop running and choose walk in the bottom corner.

**Comment by jet-pack-cat** [comment]
Mime here, I was using mime walls to make holo-barriers appear bugged during that round. 
As for the 4 barrier trap either you forgot to go into walk mode or me pushing you in there broke it somehow.

**Comment by MaxIsJoe** [comment]
this has been fixed recently
