### ISSUE TITLE
[BUG] Relogging as Xeno Larvae breaks game rejoining.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9444]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121502

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

As a mature (I think) Xeno Larvae I attempted to relog (as the UI is broken and relogging usually fixes it.). However, upon rejoining I was let into the game however I had a very limited field of view similar to the blind effect, the "Rejoining round..." menu box was stuck open, and I could still hear menu music. Despite all of that I was able to move around (however couldn't interact with anything) and use the OOC chat. Going into the command prompt and typing "suicide" fixed the issue when I became a ghost. I was gonna get a screenshot of the red exclamation point errors it was giving me put I accidentally pressed the trash can deleting them all. 🤦🤦

### What should have happened instead?

Should've been able to rejoin the game completely and not be left in a phantom still rejoining while being in the kind of in the game state.

### Steps to reproduce the issue

1. Become a xeno after being facehugged.
2. Exit the game (in my case I just did to the main menu)
3. Rejoin the server
4. BUG!!! 🐛🐛🐛🐛🐛

**Comment by corp-0** [comment]
> red exclamation point errors it was giving me put I accidentally pressed the trash can deleting them all. 

Yes, it would have helped a lot to get the error

**Comment by eurtod** [comment]
Apologies I will try to get them tomorrow if I can.

**Comment by eurtod** [comment]
![image](https://user-images.githubusercontent.com/119550415/208325277-c4b46c9c-01bd-4252-be0a-5ddf1e9672f9.png)

**Comment by eurtod** [comment]
here's some

**Comment by eurtod** [comment]
![image](https://user-images.githubusercontent.com/119550415/208325331-4d58cb00-580b-424c-b77a-903ba2b34653.png)
this too

**Comment by corp-0** [comment]
can you expand the last one from your first picture? Click on it

**Comment by eurtod** [comment]
i'll try to test it out again later

**Comment by eurtod** [comment]
seems this bug was fixed didn't see for myself but another person told me they were fine after relogging in latest build

**Comment by eurtod** [comment]
well the ui for them was still broken they were unable to evolve but at least weren't stuck in a phantom rejoining

**Comment by corp-0** [comment]
> well the ui for them was still broken they were unable to evolve but at least weren't stuck in a phantom rejoining

This is another issue and should be reported as such. 

If you get to confirm the reported bug is gone, we can close this.

**Comment by eurtod** [comment]
Sorry forgot, this is fixed though.
