### ISSUE TITLE
[BUG] Unable to take ghost roles.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9445]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121502

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Don't have much info, when selecting a ghost role it loads a bit and then says, "There was a problem giving you this role." Or something like that I don't remember exactly. When trying it again or on different roles same thing happens. Don't think relogging fixes it either.

### What should have happened instead?

There shouldn't have been a problem giving me the role. ):

### Steps to reproduce the issue

1. Die (I know I'm sorry but it was bound to happen eventually)
2. Try getting ghost role
3. This seems to happen kinda randomly so get bad RNG
4. 🐛🐛🐛🐛

**Comment by corp-0** [comment]
does it happen with a particular ghost role?

**Comment by eurtod** [comment]
Not really it's usually random when it happens but when it happens for one it'll happen for the others.

**Comment by MaxIsJoe** [comment]
Hasn't been an issue for some time now.
