### ISSUE TITLE
[BUG] Can still hear people talking and comms even after removing ears.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9452]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121823

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Removed ears and can still hear people talking and over comms. Cannot hear in-game audio though.

### What should have happened instead?

Can't hear in-game audio or people talking near you or in comms.

### Steps to reproduce the issue

1. Go into surgery
2. Remove ears

**Comment by corp-0** [comment]
Known. The influence of hearing on chat hasn't been implemented yet. Leave this issue to track that progress tho.
