### ISSUE TITLE
Exosuits not working in 0g

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9467]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23010114

### I was

Client

### OS

Mac

### What happened?

When an exosuit is put on (at least the RD's hardsuit), the suit does not protect the occupant from low pressure or extreme temperatures anymore.

### What should have happened instead?

The exosuit should've protected from the harsh environment of outer space.

### Steps to reproduce the issue

1.) Collect the (RD's) exosuit.
2.) Put it on.
3.) Go for a stroll outside (space).

### Additional context

![Screen Shot 2023-01-01 at 10 57 33 AM](https://user-images.githubusercontent.com/61613068/210182047-a47264e2-956a-4a15-a1ad-1069541e2718.png)
![Screen Shot 2023-01-01 at 10 58 07 AM](https://user-images.githubusercontent.com/61613068/210182050-02d40d56-e7a6-400d-97ce-d70935f2c81d.png)

**Comment by corp-0** [comment]
@Bod9001 new temp changes?
