### ISSUE TITLE
Early Access Information in UI

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#947]
To make clear to players that we are still in a (very) early access phase, there should a version number + "Early Access" in the Upper left corner of the UI.

Additionally, a changelog should be added which pops up after opening in the game after a new update.

**Comment by fomalsd** [comment]
I think we should make it more explicit by having a disclaimer popup like many EA games do

**Comment by krille90** [comment]
i think we had this at some point. Doesn't still exist with the GUI overhaul? (I can't check right now)

**Comment by fomalsd** [comment]
disclaimer is now shown by clicking Info button (not by default) on login screen

**Comment by krille90** [comment]
Ok. Then I will close this issue.
