### ISSUE TITLE
[BUG] Crayons do not work

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9470]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23010114

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Crayons do not work it says "cannot use crayon on space" or something like that. Spray cans do work though for some reason.

### What should have happened instead?

Should've crayon'd y'know?

### Steps to reproduce the issue

1. Locate a box of crayons
2. Pick your favorite color
3. Select something to draw
4. Try and fail because they don't work

**Comment by PerfectTangent** [comment]
Redundant with #8837. When you check the box that says you've searched for existing issues, that's to remind you to actually go take a peek at them.

**Comment by eurtod** [comment]
Sorry
