### ISSUE TITLE
Sparkly items

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9489]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23010820

### I was

Client

### OS

Mac

### What happened?

Items will appear to "sparkle" when interacted with. Sometimes.

### What should have happened instead?

They shouldn't have sparkled.

### Steps to reproduce the issue

1.) Interact with an item. (Note: this just randomly happens to random items.)

### Additional context

![Screen Shot 2023-01-09 at 5 41 21 PM](https://user-images.githubusercontent.com/61613068/211442719-b02b43d1-95c9-44ef-97ed-01214b93c01f.png)

**Comment by LastCaptainBonk** [comment]
Maybe it's an EMP thing? The effects are pretty similar.

**Comment by AtnerNT** [comment]
Its the new telekenesis effect, seems to be triggeing regardless if someone has telekenesis

**Comment by LastCaptainBonk** [comment]
Right. With that information, I think this issue is just a copy of #9479

**Comment by Q4ik** [comment]
To be fair when you pull and immediately toss an item it looks like telekinesis.
