### ISSUE TITLE
Processing meat wheat freezes the game

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9495]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23010820

### I was

Server

### OS

Mac

### What happened?

I spawned in some meat wheat and attempted to process it, resulting in the entire game freezing.

### What should have happened instead?

The server shouldn't have frozen.

### Steps to reproduce the issue

1.) Obtain meat wheat.
2.) Process it.

### Additional context

![Screen Shot 2023-01-11 at 4 32 46 PM](https://user-images.githubusercontent.com/61613068/211948055-2979f79b-8507-4553-90ee-d8d83fa3dfb0.png)

**Comment by corp-0** [comment]
fixed by #9505
