### ISSUE TITLE
ID Consoles delete cards

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9497]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011213

### I was

Client

### OS

Mac

### What happened?

I put my ID into the ID console, tried ejecting it, and nothing popped out.

### What should have happened instead?

My ID should've popped out.

### Steps to reproduce the issue

1.) Go to ID console.
2.) Insert your ID.
3.) Click "Eject ID".
4.) Exit the ID console menu.

### Additional context

![Screen Shot 2023-01-12 at 7 44 08 AM](https://user-images.githubusercontent.com/61613068/212114039-6000aeeb-2d53-4b62-98ab-ea7a1cacc618.png)
![Screen Shot 2023-01-12 at 7 44 12 AM](https://user-images.githubusercontent.com/61613068/212114055-f737ba40-efea-43ec-9014-f9ab3f2a201a.png)
![Screen Shot 2023-01-12 at 7 44 15 AM](https://user-images.githubusercontent.com/61613068/212114066-4978636b-654a-44df-812c-3bb2c7c6d8a5.png)

**Comment by AtnerNT** [comment]
https://discord.com/channels/273774715741667329/730869781040726071/1063121020464144385
