### ISSUE TITLE
Spinning chairs while buckles no longer works

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9498]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011213

### I was

Client

### OS

Mac

### What happened?

I buckled myself in a chair and it would not allow me to rotate it.
(Although when unbuckled, it was able to be rotated.)

### What should have happened instead?

I should've been able to rotate it.

### Steps to reproduce the issue

1.) Find a chair.
2.) Buckle yourself into that chair.
3.) Try and rotate that chair.

### Additional context

![Screen Shot 2023-01-12 at 5 20 47 PM](https://user-images.githubusercontent.com/61613068/212217477-1c49d4cc-2f0e-49c4-aa38-c13d08383d26.png)

**Comment by LastCaptainBonk** [comment]
Okay, this next screenshot may actually mean this issue is bigger than just chairs.

**Comment by LastCaptainBonk** [comment]
![Screen Shot 2023-01-12 at 5 57 30 PM](https://user-images.githubusercontent.com/61613068/212219640-bd302946-68f8-4f43-b439-9cbdbc0c2ae5.png)

**Comment by LastCaptainBonk** [comment]
Okay, I did some testing, and the selection seems to be bugged whenever buckled or the hand is occupied by an item.

**Comment by MaxIsJoe** [comment]
This has been fixed at some point apparently
