### ISSUE TITLE
Text theme not changing

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9499]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011213

### I was

Client

### OS

Mac

### What happened?

I selected other text themes, and none of them worked, reseting after joining other servers or reloading.

### What should have happened instead?

The text boxes should've changed.

### Steps to reproduce the issue

1.) Go to menu.
2.) Select "Options".
3.) Go to "Themes".
4.) Select any other chat theme (B or C).
5.) Tab out.
6.) Speak.

### Additional context

![Screen Shot 2023-01-12 at 7 30 26 PM](https://user-images.githubusercontent.com/61613068/212232932-619d1bf0-08d8-4fe5-938e-8c1ecabb84e9.png)
![Screen Shot 2023-01-12 at 7 48 40 PM](https://user-images.githubusercontent.com/61613068/212232940-84ab8d5c-7ffd-4d6b-a9b9-0253752ffa79.png)
![Screen Shot 2023-01-12 at 7 30 32 PM](https://user-images.githubusercontent.com/61613068/212232943-9c6c540b-9fb9-4822-8819-0ee84db12e98.png)
![Screen Shot 2023-01-12 at 7 48 45 PM](https://user-images.githubusercontent.com/61613068/212232953-66bcf592-14e7-4e9c-b62b-e744cdba91cf.png)

**Comment by MaxIsJoe** [comment]
This is fixed as of the latest build.
