### ISSUE TITLE
Icon Reorganization

### ISSUE THREAD

**Issue by Puzzlemaker1** [unitystation/unitystation#950]
# Preliminary information

## Category
TODO

## Bug: Release or Development?
Development

# Report
## Current Behavior
Currently the icons are disorganized and scattered around the filesystem.

## Expected/Wanted/Requested Behavior
Eventually the Resources folder will be removed.  All icons should be organized into a different system TBD, probably assetbundles or the like.  The icons scattered around the project should all be moved into this new system.

**Comment by DooblyNoobly** [comment]
Make sure any sprite sheet in a resources trees stays in a resources tree as it is probably being loaded at runtime

**Comment by DooblyNoobly** [comment]
So after some discussion, it is probably a good idea to start moving away from using the resources folder. We will need to cache the assets via public members exposed to the inspector itself. Which will be a bit of a job as spritemanager will need to be converted, all of the factories and some of the UI elements. It would be best to do a Search All Files in the project for the word Resources and then go from there. Then we can easily clean up the textures file structure

**Comment by fomalsd** [comment]
We'll need to convert all clothes and items to prefabs first, as DMI metadata relies on sheet locations!
    `"icon": "icons/mob/inhands/items_righthand.dmi"`
That's why our icons folder structure matches TG's at the moment

**Comment by Puzzlemaker1** [comment]
Okay, how should I edit this ticket?  What's the gameplan?

**Comment by Puzzlemaker1** [comment]
Edited the ticket.

**Comment by fomalsd** [comment]
Bod did it
