### ISSUE TITLE
Implanting cybernetics broken

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9500]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011213

### I was

Client

### OS

Mac

### What happened?

I attempted implanting cybernetics, and nothing happens (but robotic limbs and organic organs implant/remove just fine).

### What should have happened instead?

The cybernetic organs should've been implanted.

### Steps to reproduce the issue

1.) Produce a cybernetic organ.
2.) Try to implant it as you would a normal organ.

### Additional context

![Screen Shot 2023-01-12 at 8 20 22 PM](https://user-images.githubusercontent.com/61613068/212237065-6aaec505-09df-4f9e-ab8b-646c29739ac8.png)
![Screen Shot 2023-01-12 at 8 22 04 PM](https://user-images.githubusercontent.com/61613068/212237080-bdd86059-85b8-4068-b452-bbdd763d31a5.png)

**Comment by AtnerNT** [comment]
Is it just lungs?

**Comment by LastCaptainBonk** [comment]
As the cybernetic liver shows, unfortunately not.

**Comment by AtnerNT** [comment]
have you tried a non-organ, something like a reviver implant?

**Comment by LastCaptainBonk** [comment]
Good news! The breathing tube works! It seems to be the organs mainly at fault...

**Comment by AtnerNT** [comment]
I found the issue, it was to do with item traits on the cybernetic organ variants. Have already got a fix

**Comment by corp-0** [comment]
fixed by #9505
