### ISSUE TITLE
Clothing being able to be put anywhere on the body

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9506]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011320

### I was

Client

### OS

Mac

### What happened?

As reported from other players, as well as me, I put my mask on my neck and it worked.

### What should have happened instead?

I shouldn't have been able to place my mask on my neck.

### Steps to reproduce the issue

1.) Take any item of clothing.
2.) Put it in a clothing slot where it shouldn't be.

### Additional context

![Screen Shot 2023-01-13 at 4 22 44 PM](https://user-images.githubusercontent.com/61613068/212440929-140cc6f9-e3c9-4548-96f1-6be96d0cedf6.png)
![Screen Shot 2023-01-13 at 4 22 47 PM](https://user-images.githubusercontent.com/61613068/212440940-dc237422-0efa-4b30-9a9b-245bc01c6648.png)

**Comment by corp-0** [comment]
fixed by god knows what pr
