### ISSUE TITLE
Walls are bugged

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9508]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011320

### I was

Client

### OS

Mac

### What happened?

I could remove a wall, and it just revealed a second wall underneath.

### What should have happened instead?

The wall should've been removed

### Steps to reproduce the issue

1.) Get a toolbox.
2.) Remove the wall (or try to).
3.) Observe.

### Additional context

![Screen Shot 2023-01-13 at 7 41 38 PM](https://user-images.githubusercontent.com/61613068/212449266-421dd463-4b24-430d-b04e-7f1447ad98e3.png)
![Screen Shot 2023-01-13 at 7 42 34 PM](https://user-images.githubusercontent.com/61613068/212449272-2150c0ee-e3be-44e0-b2e2-22192e82feaf.png)

**Comment by AtnerNT** [comment]
strange bug, any errors in console?

**Comment by LastCaptainBonk** [comment]
Yes, in fact.
1.) Console.
2.) New problems.

Maybe something dealing with deconstruction.

**Comment by LastCaptainBonk** [comment]
![Screen Shot 2023-01-13 at 8 00 22 PM](https://user-images.githubusercontent.com/61613068/212449775-e4aab37a-e935-4960-a75f-adcc50609ed2.png)

**Comment by LastCaptainBonk** [comment]
![Screen Shot 2023-01-13 at 7 50 49 PM](https://user-images.githubusercontent.com/61613068/212449779-d12c0c86-f257-47c6-8a5e-5a68914f74ab.png)

**Comment by AtnerNT** [comment]
Okay yeah looks like an NRE with deconstruction might be happeneing, may you disable warnings (the yellow ones in the console, just click the warning number at the top) and send a screenshot of the most recent red errors?

**Comment by LastCaptainBonk** [comment]
![Screen Shot 2023-01-13 at 8 08 24 PM](https://user-images.githubusercontent.com/61613068/212449986-5a3daa24-fcb4-41b2-9ab2-02faffb9720f.png)

**Comment by AtnerNT** [comment]
Logged into staging and am unable to reproduce

**Comment by LastCaptainBonk** [comment]
Okay, this may just be a weird thing that happened once.  ¯\_(ツ)_/¯
