### ISSUE TITLE
[BUG] Right clic sub menu

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9522]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23.01.14.16

### I was

Server

### OS

Linux

### What happened?

in version 23.01.13.20 all working correctly
in version 23.01.14.16 the right-click menu is not correctly displayed.

if several objects are against each other, the right click displays the objects, allowing you to take them, by left click
but, you can't interact with them, in the case of a mixer it's a blocking bug.

https://youtu.be/XpFxK97ELZk

### What should have happened instead?

https://youtu.be/Wolr0e2XEHk
in version 23.01.13.20 all working correctly

### Steps to reproduce the issue

right clic

**Comment by Fr-Dae** [comment]
possibly link to https://github.com/unitystation/unitystation/pull/9521
Bod9001:Staging-fixes19
@Bod9001

**Comment by corp-0** [comment]
fixed by #9521
