### ISSUE TITLE
Aloe seeds not working

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9523]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23011416

### I was

Client

### OS

Mac

### What happened?

I planted aloe seeds and nothing happened.

### What should have happened instead?

An aloe plant should've grown.

### Steps to reproduce the issue

1.) Get aloe seeds and a hydroponics tray.
2.) Plant the aloe seeds.
3.) Observe.

### Additional context

![Screen Shot 2023-01-15 at 9 51 41 PM](https://user-images.githubusercontent.com/61613068/212607949-f28618f6-720e-4afa-a677-bdc3e88fe2a3.png)
![Screen Shot 2023-01-15 at 9 51 48 PM](https://user-images.githubusercontent.com/61613068/212607957-1ed1a9f5-8ef6-4e4e-ab82-79d367db157e.png)

**Comment by AtnerNT** [comment]
Fixed by #10241
