### ISSUE TITLE
[Feature Request] Syringes taking time to inject reagents and making it obvious to player when it is occuring. 

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9544]
### There is no other issue with the same feature request.

- [X] I have searched the existing issues

### Why is this feature needed/good for the game?

This is mostly due to the fact you can literally just instantly inject salt into people very stealthy and kill them instantly. Also more realistic and in line with the rest of the game, you don't instantly inject something into someone. As well as when poking someone with a syringe they are going to feel it so it should be obvious to the player when it is occurring. It is also more in line with other parts of the game because the implanter a similar item used by syndicates to implant bombs takes a few seconds to actually implant items.

### Describe your feature in detail.

When taking blood/injecting anything into a player using a syringe I'd propose just having like a flash of red to simulate the sudden pain and then the injection or withdrawal taking 2-3 seconds, I don't know the specifics. It could possibly play a sound effect but your guess is as good as mine of what putting a syringe in someone would sound like.

### User stories
* As a player I want to see a red text on chat whenever I am injected with anything so that it alerts me of the risk of being injected with something.
* As a player I want there to be a progress bar for the action of injecting other people so that it is less abusable to instantly inject lethal reagents into other players.

It is easily abusable and since salt and syringes aren't hard to get anyone can really do it. I doubt it'd be very easy for an admin to figure out who is doing it either if someone is just murder boring a bunch of people.

### Describe alternatives you've considered.

Well, I discussed in the discord that just making salt not instantly kill people like that, but it's kind of unrealistic. Having a better cooldown when injecting someone would work better in general because it's the same when trying to feed someone something.

**Comment by corp-0** [comment]
I edited your issue so the user stories follow the user story format. The idea behind it is to have a human readable requirement that a developer can then translate into a feature. That's why it always states:

as a **USER** I want **WHAT USER WANTS** so that **WHY**

**Comment by eurtod** [comment]
Ah alright thanks sorry.
