### ISSUE TITLE
Game Logo competition B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#955]
## Category
Community competition

## Purpose
Unitystation needs a new game icon. The icon will be used for the game build and also displayed on any pages like steam and reddit. The icon itself needs to be in a round or square format as it will be used as the game icon displayed in taskbars and as shortcuts on the desktop.

## Details:
- All entries should be submitted to this github ticket by the 26th of February 
- The community will be asked to vote on which icon they think is the best in a special channel that will be opened on discord. All votes will need to be in by the 27th of February
- Shortly after the votes will be tallied and the successful winner will receive the bounty!

## Criteria
- Image size: 1024 x 1024 (this is so we can scale down to any size needed)
- Transparent background
- Please keep the source files and try not to merge layers unnecessarily in your project
- Has to represent SS13
- Has to either be a round or square icon (if going for a square icon fill right to the edges in the 1024 x 1024 canvas). See below for an example of a round icon:
![header_h1_bg](https://user-images.githubusercontent.com/20813925/35765396-8a1c91c6-090e-11e8-9a63-b2e3a741e2ff.png)

- Please use #spriting on discord to receive feedback on your progress

A 50 usd bounty will be paid to the winner announced on the 26th/27th of February that receives the most votes and meets all of the criteria above

**Comment by PJB3005** [comment]
> Image size: 1024 x 1024 (this is so we can scale down to any size needed)

Wouldn't it be better to ensure people make SVGs instead?

**Comment by DooblyNoobly** [comment]
Yea it is part of the criteria to keep the source files, so if we need SVGs we can create them.

**Comment by WhiteCurse** [comment]
![ss13logodesign](https://user-images.githubusercontent.com/36242390/35935465-972e4c3a-0c0e-11e8-942a-972d6a6fceef.png)

:)

**Comment by dodo08** [comment]
/Users/imac20/Desktop/LOGO.jpg

**Comment by dodo08** [comment]
![logo](https://user-images.githubusercontent.com/36706957/36548908-b5466c04-17f1-11e8-8e05-cea6488518e8.jpg)

**Comment by DooblyNoobly** [comment]
Update: Competition has been extended to the 26th of Feb. 3 more days to get submissions in

**Comment by Whiteanon** [comment]
![ubigsimple](https://user-images.githubusercontent.com/36060398/36570946-091a3024-17fa-11e8-89d4-66cacf3e5488.png)

**Comment by kyrahabattoir** [comment]
You guys DO know that Unity is going to give you shit for using unity in your game name right?

**Comment by Rinoka** [comment]
also a money payment for winning may also get the Unity lawyers a buzzing

**Comment by FatCat1978** [comment]
you ALSO ALSO want to note that if it's used as an icon nobody's going to be able to read that tiny ass font.

In comparison the S.S 13 is huge.

**Comment by fomalsd** [comment]
you can't go wrong with good ol 32x32

wide wings:
![default](https://user-images.githubusercontent.com/10403536/36588592-ab660bba-1899-11e8-99b2-fd4cac449744.png)
![screenshot 2018-02-23 11 25 51](https://user-images.githubusercontent.com/10403536/36588969-ca48f7d0-189a-11e8-919d-0c10e034ab15.PNG)

shuttle reference, narrower wings:
![default](https://user-images.githubusercontent.com/10403536/36588663-d946c6b4-1899-11e8-945d-f8dba3bf4b89.png)
![screenshot 2018-02-23 11 34 03](https://user-images.githubusercontent.com/10403536/36589017-f85b385e-189a-11e8-9baa-864091a47346.PNG)

bonus ✝ys✝a✝ splash screen:
![default](https://user-images.githubusercontent.com/10403536/36588688-e8c02108-1899-11e8-96fd-268afbe078de.png)

alt background:
![default](https://user-images.githubusercontent.com/10403536/36588696-ef0365fc-1899-11e8-95d4-d00e2ea6d4bb.png)
![screenshot 2018-02-23 12 56 23](https://user-images.githubusercontent.com/10403536/36589031-0093ff56-189b-11e8-8a62-ffa2da1d8dd0.PNG)

everything can be tweaked in a psd

**Comment by Nilsius** [comment]
Here are my designs

![unity5 2](https://user-images.githubusercontent.com/8015103/36644437-d99fe858-1a5a-11e8-9aed-94d34bf04878.png)

![unity1 2](https://user-images.githubusercontent.com/8015103/36644438-d9bd0a8c-1a5a-11e8-81fb-3341d75ecb5f.png)

![unity2 2](https://user-images.githubusercontent.com/8015103/36644439-d9d09174-1a5a-11e8-9cd9-c3e7110ee75e.png)

![unity3 2](https://user-images.githubusercontent.com/8015103/36644440-d9e4fe98-1a5a-11e8-9c01-28fe4ff59359.png)

![unity4 2](https://user-images.githubusercontent.com/8015103/36644441-d9f8e610-1a5a-11e8-885b-b7816c60464e.png)
