### ISSUE TITLE
Canisters Are Invisible

### ISSUE THREAD

**Issue by LastCaptainBonk** [unitystation/unitystation#9556]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23012620

### I was

Client

### OS

Mac

### What happened?

The sprite for the canisters in-game are invisible (bar for the light on them indicating how much pressure is stored).

### What should have happened instead?

They should not be.

### Steps to reproduce the issue

1.) Go to/spawn a canister.
2.) Observe.

### Additional context

NOTE: Broken canister sprites still show up (2nd image).
![Screen Shot 2023-01-26 at 8 47 49 PM](https://user-images.githubusercontent.com/61613068/215011868-706b88ed-e153-4b82-bf97-a975c8b8fe99.png)
![Screen Shot 2023-01-26 at 8 54 24 PM](https://user-images.githubusercontent.com/61613068/215012319-95110380-b50c-44b6-a569-41152293845b.png)

**Comment by corp-0** [comment]
fixed by #9557
