### ISSUE TITLE
[BUG] You can sell footprints

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9559]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

223012812

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

![image](https://user-images.githubusercontent.com/34368774/215291345-33ffbb70-b097-499d-b6c7-a1cb2bc59e0c.png)

### What should have happened instead?

not sell footprints

### Steps to reproduce the issue

1. Cause footprints on cargo shuttle
2. Send it to centcomm
3. Profit

**Comment by corp-0** [comment]
lmao I like how it even says you sold 4 footprints. For a second I thought it would be the reagents
