### ISSUE TITLE
Item type and damage recategorization 

### ISSUE THREAD

**Issue by Puzzlemaker1** [unitystation/unitystation#956]
# Preliminary information

## Category
TODO

# Report
## Current Behavior
Items are not categorized correctly

## Expected/Wanted/Requested Behavior
Currently all items are categorized into types.  These types are things like Hat, Gloves, etc.

However, they also have the type of Gun, Knife and Food in this list.

This is logically inconsistent and will cause problems down the road.  Types should be the slot they are equipped in.  Gun, Knife and Food should be changed to "Usable".  Instances of Gun, Knife and Food should be removed in the code, and handled another way.

This will allow things like bashing with a air tank, because right now since an air tank is a back item it cannot be a weapon.

This will tie into #953 and #957

**Comment by Fishfish458** [comment]
Attempting to look into this one now
