### ISSUE TITLE
[BUG] Space cleaner is too strong and cleans floor decals

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9565]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23.01.31.19

### I was

Client

### OS

Linux

### What happened?

On Fallstation, EU server
Has HOP job

In the cargo, I wanted to clean some footprints in the powder. I also erased the yellow "#" markings on the floor that indicate the location of the crates at the exit of the exchange shuttle, 

the use of the space cleaner erased all of them.

another concern, removing a floor tile does not remove the footprints. 

### What should have happened instead?

mark should not be "cleaned"

### Steps to reproduce the issue

- on fallstation
- take a space cleaner
- use it on mark on cargo
- see mark deseper

**Comment by corp-0** [comment]
renamed the issue to make it clearer. Thanks for reporting.
