### ISSUE TITLE
Refactor weapons script

### ISSUE THREAD

**Issue by Puzzlemaker1** [unitystation/unitystation#957]
# Preliminary information

## Category
TODO

# Report
## Current Behavior
Currently the weapons script doesn't handle melee weapons.  It also has hard coded input behavior.

## Expected/Wanted/Requested Behavior
The weapons script should be broken up.  
- [ ] It should become a Weapon base script, with two scripts inheriting from it:  Gun and MeleeWeapon.  
- [ ] Weapon should inherit from InputTrigger, ~~then tied into the input system as described in ticket #953 .~~ 
– _input system is yet to be redesigned_
- [ ] The melee weapon handling in HealthInput should be removed, and handled in the MeleeWeapon script.

**Comment by fomalsd** [comment]
To be honest, weapons should be rewritten from ground up as they're unsecure as hell: server authority is almost non-existent, you can stab someone without actually having a knife and tamper with firearm ammo and fire rate on the client side. It's pretty old.

**Comment by fomalsd** [comment]
@Puzzlemaker1 looks like you have a good vision on how weapons should be structured properly, could you please look into forming the detailed criteria for this task before bounty is set? ( this task is about general structure, network interactions and security will be addressed in #989, #990 )

**Comment by DooblyNoobly** [comment]
also bring back shooting prediction!

**Comment by chairbender** [comment]
Also self assigning this due to my work in #989 and #1123 as they are all overlapping, and it looks like the melee part of this ticket is already done.
