### ISSUE TITLE
[BUG] Automod does not log player deaths.

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9593]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

Upstream/Develop (2/6/2023)

### I was

Server

### OS

Windows 8, 10, 11

### What happened?

When players die by non-antags; their deaths aren't logged in admin alerts.

### What should have happened instead?

When `OnDeathActions()` is called, it should process who was the last person to attack the dead player and alert admins about it if they're non-antags or if the player did that to themselves.

### Steps to reproduce the issue

1. Kill yourself while having access to admin alerts.
2. Watch as no alerts happen.
3. Kill another player while not having an antagonist role.
4. No alerts happen still

**Comment by CorruptComputer** [comment]
> it should process who was the last person to attack the dead player and alert admins about it 

Perhaps it should say when they attacked them as well, if someone accidentally hits me with something then I walk out of an airlock 5 minutes later that player should not be punished for it.

**Comment by MaxIsJoe** [comment]
This is getting fixed in #10418
