### ISSUE TITLE
[Mapping] Vending Machine near medical is a botany vending machine not one for snacks.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9614]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Map

FallStation

### Description of the problem

By medical, there is a vending machine that instead of giving snacks gives you botanist things. This is disappointing because you cannot eat pest spray, buckets, spades, etc.

### Pictures/videos

i don't have image of it but here is visual description.
[Outside of medical, green vending machine. In the corner the vending machine menu is open and it is offering botany things.]

**Comment by YunoGasai9862** [comment]
Hey, Can you post the picture of which snack vending machine is causing this anomaly? I'm up for fixing this.

![Screenshot (415)](https://user-images.githubusercontent.com/74299910/229103550-16c5a767-2d44-4bba-87e7-b04d64ee9f7d.png)


Is it this one?

**Comment by eurtod** [comment]
No, it's the vending machine on Ministation. Right outside of Medical on Ministation, should be literally right in front of it. That one in the pic is on Fallstation and is fine though.

**Comment by YunoGasai9862** [comment]
> 

Oh. Your first comment said Fallstation, that's why I went there. I'll check the Ministation, then. Thanks.
