### ISSUE TITLE
[BUG] Removing materials from department protolathe does not decrease the material quantity inside of the protolathe

### ISSUE THREAD

**Issue by DefinitelyNotAyunu** [unitystation/unitystation#9629]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23021813

### I was

Server

### OS

Windows 8, 10, 11

### What happened?

Spawned in SquareStation in Engineering Bay. Inserted PlasmaSheets in the department protolathe and then started removing them. However, the quantity registered in the department protolathe remained constant, so I was effectively able to infinitely duplicate the plasma sheets.

### What should have happened instead?

When removing a stack from the machine, the counter of available material inside of it should decrease accordingly.

### Steps to reproduce the issue

Go to department protolathe. 
Insert plasma sheets in it. 
Remove as many.
Counter does not decrease but you get your sheets back.

**Comment by MaxIsJoe** [comment]
Correction for this because I'm testing it right now.

The UI doesn't get updated for department autolathes only but you don't get infininte amounts of sheets from this. Its a UI issue only.

working on fixing it right now.
