### ISSUE TITLE
Build new shuttle control console B: 150

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#971]
# TODO

Build the console computer that will sit in the bridge of each shuttle. When the console is clicked on it should show a UI window with the shuttle controls on it. At the moment we need a control system that takes a waypoint that the shuttle can automatically guide its way too. In the future we will add the feature for manually controlled shuttles.

A radar window should be shown that shows near by objects (just shows the other matrices positions) and the radar window should be clickable to set waypoints for the shuttle. A fly, no fly button should be placed under the radar to toggle the ships flight progress.

## Criteria:
1. Build the Shuttle control console object, using sprites from the codebase, create a ShuttleControl component and derive it from InputTrigger so it can be clicked on.
2. Create a UI window and place it in the Windows parent underneath UIManager in the Manager prefab.
3. Have the Window show when someone clicks on the control console and have the window disappear if you walk away from the console
4. Create all of the UI elements to control the shuttle with. Window should know the current shuttle it is controlling and it should send movement requests to the server (To the serverside of the MatrixMove component) to be validated.
5. Ensure there are necessary checks on the server to prevent hacking
6. Create all of the control elements and graphics and have them operational
7. Connect into the MatrixMove system which is being implemented in #970 
8. Test on headless server with 2 clients

Bounty of 150usd will be paid to the contributor on a successful merge

**Comment by fomalsd** [comment]
Actually I think that manual shuttle controls should be implemented first, and then making waypoint features on top of that

**Comment by DooblyNoobly** [comment]
But only having waypoint available on steam launch? I was thinking it would be easier to prevent people from crashing shuttles using the shuttle computer with waypoints because we haven't figured out matrix collisions yet.

**Comment by fomalsd** [comment]
yeah, always possible to disable some functionality

**Comment by DooblyNoobly** [comment]
Increased bounty to 150

**Comment by fomalsd** [comment]
![default](https://user-images.githubusercontent.com/10403536/40224509-e9b50682-5a75-11e8-9140-b20f86d3d25c.png)
initial draft for console UI

**Comment by NinjaDanz3r** [comment]
Started work on this, just FYI.

**Comment by DooblyNoobly** [comment]
moved it to 'in progress'. thanks

**Comment by DooblyNoobly** [comment]
actually technically you did do all of the criteria. I'll create a separate one in the future for Radar as it will be another beast all together
