### ISSUE TITLE
Set up the [Nuke Op vs Station] gamemode B: 150

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#972]
------------------------------------
Task Description:
------------------------------------

The task is fairly straight forward. We need to change our current
team death match game mode to a Nuke Ops vs Station game mode.

All of the game mechanics for the Nuke ops, shuttles, station, matrix move,
networking is all done we just need you to alter the game manager code and a few
other things to meet the criteria below.

We also need to set up a way point system for our escape shuttle to arrive
at a position on the map after a certain amount of time has elapsed.

Some Notes:
------------------------------------

Fork our repo to see the current game mode:
https://github.com/unitystation/unitystation
(Use 2018.2 and run the Lobby scene, you can even build a player
by including the lobby, outpostdm and flashlightdm scenes)

Criteria:
------------------------------------

- [ ] Remove all of the old reporting code (the stat reports from the gamemanager to the chat feed) from the TDM game state and now implement code to determine who won the end of the Nuke Ops vs Station round.

----
#### Rules to determine which side wins:

- [ ] If all nuke ops died and 1 station member is alive and on the shuttle after the 10 minute round time ends then the Station crew wins

- [ ] If no one is on the shuttle after 10 minutes then the Nuke Ops win (you will need to develop some logic to check the shuttles children for players who are still alive on the server. Players move to the tree of the shuttle or station they are on)

- [ ] If the nuke is set off on the station then the Nuke Ops win

----- 
- [ ] Print which side won to the chat feed and wait a minute after the round ends before playing next round

- [ ] Set the timer to count down from 10 minutes and then set the escape shuttle to arrive at the station at the end of that timer (You will need to do some trial and error here to get it arriving at the time it is meant to). Count down again for 1 minutes and then depart the shuttle. End the round after about a minute of flight time and count all of the survivors that made it onto the escape shuttle.

- [ ] Apply all of the criteria to the OutpostDeathmatch scene. Try to also apply the changes to the FlashlightDeathmatch scene (we know there is obstacles to overcome on the flashlight scene so if it becomes too tricky then a partial implementation will be good enough, just as long as it works perfectly on OutpostDM).

- [ ] Test all of the criteria in a multiplayer setting by creating two builds that include the lobby, outpostdm and flashlightdm scenes. Play with 2 players for a few rounds to confirm

Some Notes:
------------------------------------

- Shuttle movement is controlled by the MatrixMove.cs component. Create a new component for the Escape shuttle that can use the Matrix Move to accomplish the waypoint movement and the automatic start so that it arrives at the station on time.

- Check out GameManager.cs to locate some of the current code

- Check out PlayerList.cs for helpful references and tools to do with the current players

- Nuke ops can blow the nuke by using the code that they get on round start and entering it into the nuke near the middle of the outpost station (note: there is no nuke on flashlight at the moment) 

Bounty of 150usd will be paid to the contributor on a successful merge

**Comment by dapocalypse** [comment]
Claim this

**Comment by DooblyNoobly** [comment]
Bounty increases to B: 100

**Comment by fomalsd** [comment]
I think this should also include some kind of auto team balance mechanic similar to the Counter-Strike one.
Also a couple of suggestions about the nuke behaviour, what if:
-it didn't go off instantly and had like 30s timer so that ops could leave the station
-could be defused within that time by entering another code known by captain?

**Comment by dapocalypse** [comment]
How about hacking the thing with tools, finding to correct wire, then putting in the code.

**Comment by dapocalypse** [comment]
I will be doing this after my PR for the map rotation has been accepted.

**Comment by fomalsd** [comment]
Hacking would be too complex for such game mode, and we don't have convenience systems set up for that yet. That's an overkill.
Nuke countdown and disarm logic, on the other hand, could be implemented easily

**Comment by dapocalypse** [comment]
We have nuke hacking in the base game.

**Comment by DooblyNoobly** [comment]
hey @dapocalypse this job is going to someone else. There will be plenty more work coming up that you can do. Stay tuned
