### ISSUE TITLE
Create an interactable Nuclear Weapon B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#973]
# TODO:

Create the Nuke object that can be interacted with and detonated. Determine what will happen once the nuke has detonated (just show a zoomed out animation of the station blowing up in the UI, or creating a massive explosion animation that spawn from the nuke itself (dealing 1000+ damage to all players). 

A UI window should pop up when the nuke is clicked on and ask for a pin code. Pin Code should be generated randomly on the server and placed on the Nuke Op drop ship or messaged to the nuke ops discretely when they spawn.

## Criteria:
1. Find the existing Nuke Prefab and add a component to it that derives from InputTrigger. 
2. Have the nuke generate a random 4 digit pin number on the server (do not share with client) and have it communicated to the Nuke Ops when they spawn
3. Develop a way to visually simulate the Nuke being detonated (Simple but effective approach)
4. Create a UI Window and place it in the Window parent underneath UIManager. The new window should be shown when the nuke is clicked on. Remember to apply the Managers prefab when done
5. Allow the user to input a numerical code into the window and press enter. If code matches the code on the server then arm the nuke.
6. Have the server tell the client to show the Detonate button and do the explosion when the button is pressed
7. Add an Nuke Explosion sound effect to the SoundManager and trigger it on detonation 

Bounty of 50usd will be paid to the contributor on a successful merge

**Comment by dapocalypse** [comment]
I claim this
