### ISSUE TITLE
[BUG] The Hand Labeler cannot label containers

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#9730]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

17/3/2023

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Tried labeling a locker and wooden container, kept opening them instead.

### What should have happened instead?

Should have labeled these containers with the text I gave.

### Steps to reproduce the issue

1. Grab a hand labeler
2. Label a locker or container

**Comment by corp-0** [comment]
is it reasonable that you can only open a locker with an empty hand? If such case, it would be easy and clean fix.
