### ISSUE TITLE
[BUG] Larva continuously spawn after evolving into different larva stages causing serious lag and alien chat spam.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9733]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23031718

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I evolved into a young and then mature larva but my previous evolution was still there and alive. Then the alien "comms" chat would keep saying "Alien Larva has died!" over and over again. The game started lagging really hard soon afterwards I have reason to think it keeps spawning larva at 0,0 or something where I couldn't see them but there would've been like 100s by then.

### What should have happened instead?

Not that

### Steps to reproduce the issue

1. Get face hugged
2. Become a larva
3. Evolve into another larva form

**Comment by Bod9001** [comment]
hopefully fixed in #9735

**Comment by eurtod** [comment]
It was fixed.
