### ISSUE TITLE
Update NuGetForUnity and apply the required changes for CI 

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#9746]
Current version of NugetForUnity handles restoring packages differently and a lot better than what we have. 

If any new contributor opens the project right now, they will be welcomed by compiling errors that need an extra manual step to solve, said step isn't documented anywhere.

To solve this issue update our version of NugetForUnity and the CI building process on https://github.comunitysytation/build-script so it runs the dotnet tool before attempting to build.

Find out if contributors also need to install the dotnet tool, although at first read it seems like they don't.

Link to package: https://github.com/GlitchEnzo/NuGetForUnity#restoring-nuget-packages-over-the-command-line

**Comment by YunoGasai9862** [comment]
I second the flood of errors welcoming right after opening the project.
