### ISSUE TITLE
Create headset encryption key for Nuke Ops B: 15

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#975]
# TODO:
Create a new headset to spawn with Nuke Ops so they get their own channel to speak on

## Criteria:
1. Create a new encryption key and headset to spawn on the Syndicate outfit
2. Test to make sure communications on the channel are secure with Nuke Ops only

Bounty of 15usd will be paid to the contributor on a successful merge

**Comment by DooblyNoobly** [comment]
@Em3rgencyLT interested in this one?

**Comment by DooblyNoobly** [comment]
looks like this is already a thing. Closing

**Comment by Em3rgencyLT** [comment]
Yeah my original implementation already contains this. Do I still get the
15? :D
