### ISSUE TITLE
[BUG] Poly repeats flavor text

### ISSUE THREAD

**Issue by coolcat1711** [unitystation/unitystation#9798]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23041018 4/13/2023

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I spawned as an engineer and used the vending machine to get welding goggles. The flavor text, "The welding goggles was dispensed from the machine" was put in chat. A few minutes later, this flavor text was spoken by Poly.

![image](https://user-images.githubusercontent.com/3880412/231913166-557fd8bd-22ba-4d72-9121-838272af31f6.png)

### What should have happened instead?

Poly should not include flavor text in her available text pool.

### Steps to reproduce the issue

1. Be near Poly.
2. Perform an action that generates public flavor text. (i.e getting an item from a vending machine).
3. Wait until Poly repeats the flavor text back to you.

**Comment by coolcat1711** [comment]
So, I discovered that Poly looks for "SpeechChannels" to take its repeat line from. The vending machines and quite a few other in-game objects are publishing flavor text into the Local chat channel. 

In my personal opinion, I think that these actions should be publishing to the Action chat channel and just using the "othersMessage" field to broadcast the text to local actors. Especially since the descriptor for Local chat is actual speech. However, I'd want some assurance from Seniors on the project before going through and mass subbing channels like that.

![image](https://user-images.githubusercontent.com/3880412/232169759-06ef8e0a-7753-442b-bfb9-33fd49877be5.png)

**Comment by corp-0** [comment]
I agree on your observations and approach for a solution.
