### ISSUE TITLE
[Mapping] Maintrooms doors are all unpowered and bolted.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9801]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Map

Other

### Description of the problem

The doors that spawn as part of the maze generation bit (not the preplaced rooms) have doors all throughout that are all bolted and unpowered making it much hard to traverse. The doors should be powered and unbolted.

### Pictures/videos

![image](https://user-images.githubusercontent.com/119550415/232250453-db827f26-321c-4494-b2dc-d0a0ba78cf7f.png)
what the door looks like idk it requires a image.

**Comment by MaxIsJoe** [comment]
I think its intentional for them to be unpowered; but not bolted.

**Comment by eurtod** [comment]
No when Atner first made the map they were all powered. Plus if so that's dumb cause if you get stuck in there without a crowbar you literally screwed.
