### ISSUE TITLE
[BUG] Maintrooms chances are way too high.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9803]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

Current

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I got sent to Maintrooms twice in thirty minutes on the same round.

### What should have happened instead?

Should be a 0.1% or so.

### Steps to reproduce the issue

1. Literally just play on squarestation

**Comment by eurtod** [comment]
THREE TIMES NOW 😭 😭

**Comment by corp-0** [comment]
you belong to the maintrooms

**Comment by eurtod** [comment]
yeah maybe it was just a sign that I do xD
