### ISSUE TITLE
[BUG] Emergency lights are showing white light and are too bright.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9809]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

![image](https://user-images.githubusercontent.com/119550415/232623778-e0272adb-55d2-4994-8eaf-f61312d36c4a.png)
No power but the lights are still white and pretty bright.

### What should have happened instead?

Red and dimmer lights.

### Steps to reproduce the issue

1. Run out of power

**Comment by MaxIsJoe** [comment]
I've done some debugging, this only occurs when a player joins a server. People who are online while this happens get the correct color.

Not sure why it is not applying the correct color when the emergency state is on.
