### ISSUE TITLE
[BUG] Unable to exit disposal pipes from disposal chutes still.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9826]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

current

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

When crawling around disposal tubing going to a chute is still unable to leave the pipes, only way still is to crawl to ejector one at cargo.

### What should have happened instead?

I think you should be able to exit out of chutes too when crawling through the pipes?

### Steps to reproduce the issue

1. Throw yourself away
2. Press V till you can crawl
3. Go to chute

**Comment by MaxIsJoe** [comment]
huh, I fixed this twice already I believe.
something is not right.

**Comment by MaxIsJoe** [comment]
I have troubles replicating this issue both locally and on staging, are you sure that there aren't any missing info here?

**Comment by eurtod** [comment]
Sorry for misunderstanding this isn't a bug.
