### ISSUE TITLE
[BUG] Most cyborg objects lack description and just say it's Unnamed and Oops someone spawned something they weren't supposed to!

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9831]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

current

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Most cyborg objects lack description and just say it's Unnamed and Oops someone spawned something they weren't supposed to!

### What should have happened instead?

They should have a description and not say they were spawned as something they shouldn't have been.

### Steps to reproduce the issue

1. Shift click any cyborg part pretty much

**Comment by AtnerNT** [comment]
Already addressed in #9828. Can be closed once it’s merged

**Comment by eurtod** [comment]
> Already addressed in #9828. Can be closed once it’s merged

ah sorry didn't see that. nice to see you do another build again though :)
