### ISSUE TITLE
[BUG] Game does not cache your login token when running via Flatpak

### ISSUE THREAD

**Issue by CorruptComputer** [unitystation/unitystation#9866]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23052210

### I was

Client

### OS

Linux

### What happened?

When playing the game via the StationHub Flatpak, the game will not cache your login. I think it may be trying to write this info to a file outside of the Flatpak sandbox, and when compounded with bug #9865 trying to play via Flatpak is very annoying.

### What should have happened instead?

Game should remember your login token when playing in the Flatpak. 

### Steps to reproduce the issue

1. Launch the StationHub Flatpak
2. Launch a server
3. Login
4. Quit the game
5. Launch a server
6. Be asked to login again

### Additional context

Video of issue: https://www.youtube.com/watch?v=UoyRUoyqlaI

**Comment by CorruptComputer** [comment]
Figured this out, looks like the Firebase package internally tries to write this value to your keyring. Which the Flatpak doesn't have access to.

Adding `--socket=session-bus` to the permissions seems to fix this, but this significantly reduces the effectiveness of the sandbox since this essentially gives it access to a users entire session.

**Comment by corp-0** [comment]
> essentially gives it access to a users entire session.

what the fuck, how can't it just add access to store stuff in the keyring?

**Comment by CorruptComputer** [comment]
Just got a reply from some folks in the Flatpak matrix and they let me know that adding `--talk-name=org.freedesktop.secrets` should work for this. Just tested and it seems to work fine, will get a new PR opened over there for adding that.

**Comment by corp-0** [comment]
Brilliant!

**Comment by corp-0** [comment]
fixed on https://github.com/flathub/org.unitystation.StationHub/pull/5
