### ISSUE TITLE
Robust Matrix switch for player B: 180

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#987]
## Category
TODO

## Criteria
- [ ] Unnoticeable for player
- [ ] Server authoritative
- [ ] Test in MP with Headless server + 2 Clients
- [ ] Handles transitions between space gaps

Bounty of $180 usd will be paid on successful merge

**Comment by DooblyNoobly** [comment]
Updated the bounty to 180. This is the last big hurdle to finishing steam release
