### ISSUE TITLE
Firebase fails to initialise when the game is stored in a path that has Cyrillic letters

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#9885]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23053022

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Players are unable to join when the game is stored in a path that has cyrillic letters on it. 

It happens all the time in windows when the username of the computer is in Russian or other Cyrillic languages. 

Can't tell if it is also an issue on Linux and Mac.

### What should have happened instead?

Firebase should initialise, regardless of the path where the game is stored in.

### Steps to reproduce the issue

1. Have a russian user name for your windows machine.
2. Try joining using the StationHub launcher.
3. See yourself unable to join a server.
4. Press F5 to find the Firebase initialisation error.

### Additional context

![console](https://github.com/unitystation/unitystation/assets/43683714/9557d044-008e-440c-99e9-fae343396c47)

Screenshot from a Russian player, unable to join

**Comment by craftxbox** [comment]
This was closed as wontfix in 2020: #2789

**Comment by craftxbox** [comment]
Related: firebase/firebase-unity-sdk#405

**Comment by corp-0** [comment]
> This was closed as wontfix in 2020: #2789

shit we knew about it for so long

**Comment by corp-0** [comment]
sadly this is an issue with Firebase itself and we can't fix it on our side. Closing this issue.
