### ISSUE TITLE
[BUG] Wrong dirt footprints when walking horizontaly

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#9887]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23060210

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

walking through a pile of dirt/paint/blood horizontally leaves 4 footprints
https://github.com/unitystation/unitystation/assets/10403536/e1c4c301-6c57-4809-84d6-658171ee0d33

### What should have happened instead?

straight horizontal footprints

### Steps to reproduce the issue

go through the pile of paint horizontally

**Comment by corp-0** [comment]
@MaxIsJoe could this be related to the recent changes to make the character upright?

**Comment by MaxIsJoe** [comment]
> @MaxIsJoe could this be related to the recent changes to make the character upright?

nope, this has been an issue for a while.
