### ISSUE TITLE
Revamp Firearms

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#989]
# Preliminary information

## Category
TODO, related to #957 

# Report
## Current Behavior
Firearms are prone to speedhack and have client authority, fire rate and mag size can be tampered with easily

## Expected/Wanted/Requested Behavior
Firearms should have server authority!

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor, join as build 
2. Get a P90 as build
3. Enable CE speedhack for build at 3x speed
4. Empty mag in a second, verify that it looked the same on server

**Comment by krille90** [comment]
What's the progress on this one? Who is working on this?

**Comment by chairbender** [comment]
working on this as part of #1123
