### ISSUE TITLE
[BUG] Closet container tile

### ISSUE THREAD

**Issue by RikCost** [unitystation/unitystation#9909]
### There is no other issue reporting the same problem.

- [x] I have searched the existing issues

### Game Version

23061606

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I try open closet. Then i tap, on background appeared some weird texture.
![image](https://github.com/unitystation/unitystation/assets/69048938/c44a25c8-64a1-4684-89ff-89ae361a26c8)

### What should have happened instead?

I exept it nit appeared
![image](https://github.com/unitystation/unitystation/assets/69048938/6d747108-b387-4569-8a73-4323cdf844b8)

### Steps to reproduce the issue

1. Tap your mouse on closet
2. You see it.

**Comment by MaxIsJoe** [comment]
duplicate of #5091
