### ISSUE TITLE
Players aren't solid anymore (can walk through each other) B: 30

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#992]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
In title.
Looks like it's a regression caused by matrix switch functionality and/or changes to colliders

## Expected/Wanted/Requested Behavior
Players should not be able to pass freely through each other (until we have intents in, at least)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get two players on the server
2. Try walking through each other

## Network
All types

**Comment by fomalsd** [comment]
Got broken after #946

**Comment by DooblyNoobly** [comment]
Looks like this issue is also affecting Objects that are not meant to be passable.

**Comment by DooblyNoobly** [comment]
Criteria:

 - Diagnose bug and provide a fix

A bounty of 30usd will be paid to the contributor on a successful merge

**Comment by badbon** [comment]
Also looking through this myself by the way.
