### ISSUE TITLE
No spam prevention on emotes.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9959]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23070821

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

You can spam any emote by either rapidly pasting *emote into chat or quickly pressing \ and clicking the button for it. This allows players to spam sounds such as sneezing, laughing, screaming, etc. which is very loud and disruptive.

### What should have happened instead?

There should be some way to prevent players from spamming obnoxious sounds.

### Steps to reproduce the issue

1. Copy a emote and rapidly paste it into the chat
2. OR quickly press \ and click on the emote's button in rapid succession

**Comment by MaxIsJoe** [comment]
This is not a bug.

**Comment by eurtod** [comment]
what is it then?

**Comment by corp-0** [comment]
It is a missing feature. That's what Max meant.

**Comment by eurtod** [comment]
Okay sorry, I believe there is something similar where if you type out a emote in too quick succession it will say “you struggle to catch breath” and doesn’t play it .it doesn’t for the \ emote menu though.
