### ISSUE TITLE
[BUG] The Photo Copier does not work.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9980]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23071519

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

The photocopier in Libraries and where ever else do not work. You can't insert papers into it after opening the tray or fill it up with papers to be copied on to. The highlight on the item when holding the paper just goes away and you can't interact with it. onto

### What should have happened instead?

Should be able to put paper in scanner and tray.the 

### Steps to reproduce the issue

1. Go to a photo copier
2. Open the scanner
3. Try to put paper in it

**Comment by eurtod** [comment]
i don't know how to reopen this but it's not fixed. it works on local now but not on servers still.

**Comment by eurtod** [comment]
thank you

**Comment by AtnerNT** [comment]
Can be closed now, fixed in #10320 and confirmed to be working during playtest
